spine support texture compressed with alpha channel separated
cocos/cocos-engine pull request #10025
Opened 2022-01-20 06:33 UTC by zhakesi

* https://github.com/cocos-creator/3d-tasks/issues/10941

spine shader中添加支持透明通道分离格式的采样
组件中根据纹理格式选择对应的材质

2022-01-20 15:21 UTC, pandamicro requested changes

2022-01-20 15:21 UTC, pandamicro commented on cocos/spine/skeleton.ts
> +                material = builtinResMgr.get<Material>('default-spine-material');
尽量统一 material，直接在运行时用宏来控制，避免加载时的损耗

2022-01-21 02:05 UTC, SantyWang approved these changes

2022-01-21 02:20 UTC, holycanvas commented on cocos/spine/skeleton.ts
> +                material = builtinResMgr.get<Material>('default-spine-material');
现在是用宏的，只是提前编译好

2022-01-21 06:04 UTC, zhakesi commented on cocos/spine/skeleton.ts
> +                material = builtinResMgr.get<Material>('default-spine-material');
已修改

2022-01-22 03:32 UTC, pandamicro requested changes

2022-01-22 03:32 UTC, pandamicro commented on cocos/spine/skeleton.ts
>      public getMaterialForBlendAndTint (src: BlendFactor, dst: BlendFactor, type: SpineMaterialType): MaterialInstance {
```
public getMaterialVariants(src: BlendFactor, dst: BlendFactor, type: SpineMaterialType);

public getMaterialVariants(src: BlendFactor, dst: BlendFactor, useTint: boolean, format: PixelFormat) {
}
```
在实现中兼容好这两种参数，然后用 deprecated 框架 replace `getMaterialForBlendAndTint`。

避免这种无谓的函数增加，意义只是少改动以前的代码，但是增加了代码的复杂度和理解难度，从外界角度理解，会觉得 `getMaterialWithTexturePixelFormat`, `getMaterialForBlendAndTint`, `pickMaterialType` 意义不清。而且 `pickMaterialType` 还是公开函数

2022-02-14 02:53 UTC, holycanvas commented on cocos/spine/skeleton.ts
>      public getMaterialForBlendAndTint (src: BlendFactor, dst: BlendFactor, type: SpineMaterialType): MaterialInstance {
这些函数都不应该向外开放吧

2022-02-18 09:42 UTC, closed without merging