V3.6.0 scene view native
cocos/cocos-engine pull request #10044
Opened 2022-01-25 03:35 UTC by gameall3d

Re: cocos-creator/3d-tasks#

Changelog:
 * fix some problem when nativize scene editor

2022-01-27 10:28 UTC, holycanvas approved these changes

2022-01-28 05:37 UTC, shrinktofit commented on cocos/core/assets/asset.jsb.ts
> +CCClass.fastDefine('jsb.CCObject', jsb.CCObject, { _name: '', _objFlags: 0, [editorExtrasTag]: {} });
This piece of code should be sync to all portion that reference the `CCObject`. That's, you should define `CCObject.jsb.ts` and mapping it in `cc.config.json`.

2022-01-28 05:38 UTC, pandamicro requested changes

2022-01-28 05:38 UTC, pandamicro commented on cocos/core/assets/asset.jsb.ts
> +CCClass.Attr.setClassAttr(jsb.CCObject, 'replicated', 'visible', false);
Move to object.jsb.ts

2022-01-28 05:38 UTC, pandamicro commented on cocos/core/scene-graph/base-node.jsb.ts
> +
Useless blank lines

2022-01-28 06:36 UTC, gameall3d commented on cocos/core/assets/asset.jsb.ts
> +CCClass.Attr.setClassAttr(jsb.CCObject, 'replicated', 'visible', false);
move to object.ts with ‘JSB’ check

2022-01-28 08:26 UTC, shrinktofit approved these changes

2022-01-28 08:33 UTC, pandamicro approved these changes

2022-01-28 08:53 UTC, merged