add extra name like cc.xxx from legacyCC namespace
cocos/cocos-engine pull request #10076
Opened 2022-02-11 03:18 UTC by Zhmz

Re: cocos-creator/3d-tasks#11127

Changelog:
 * legacyCC 命名空间里额外导出不带 component 后缀的组件名，方便2x用户使用 cc.xxx 调用组件

2022-02-11 05:15 UTC, pandamicro requested changes

2022-02-11 05:15 UTC, pandamicro commented on cocos/2d/components/graphics.ts
> +js.setClassAlias(Graphics, 'cc.GraphicsComponent');
All LegacyCC export code should be moved to 2d/components/deprecated.ts

2022-02-14 08:46 UTC, holycanvas commented
legacyCC.xxx = xxx; 这一行可以放在原始文件里面，另外两行要放在 deprecated.ts 里面，这样感觉才对

2022-02-20 07:33 UTC, holycanvas approved these changes

2022-02-20 07:33 UTC, holycanvas commented
单元测试没过

2022-02-21 01:35 UTC, Zhmz commented
sealed-global-variables.json需要添加新增的类型名

2022-02-21 05:57 UTC, pandamicro approved these changes

2022-02-21 06:14 UTC, merged