[bug]fix constant 最后的k=1的时候，返回是1，不是0。
cocos/cocos-engine pull request #10081
Opened 2022-02-11 07:08 UTC by milk862015

问题：
若k=1的情况下，返回0.在重复播放的动画中，出现k=1这一帧时候，显示不正确的问题。

Re: cocos-creator/3d-tasks#

Changelog:
 *

2022-04-25 13:20 UTC, holycanvas commented
please do not change coding style like this,
![image](https://user-images.githubusercontent.com/15109777/165097326-2d21c3cf-9455-4ae8-aeca-6e5ab222533e.png)

2023-05-24 05:42 UTC, pandamicro requested changes

2023-05-24 05:42 UTC, pandamicro commented on cocos/core/animation/easing.ts
> +export function constant(k: number) {
```suggestion
export function constant (k: number) {
```

2023-05-24 05:42 UTC, pandamicro commented on cocos/core/animation/easing.ts
> +export function linear(k: number) {
```suggestion
export function linear (k: number) {
```

2023-05-24 05:42 UTC, pandamicro commented on cocos/core/animation/easing.ts
> +export function quadIn(k: number) {
```suggestion
export function quadIn (k: number) {
```

2023-05-24 05:42 UTC, pandamicro commented on cocos/core/animation/easing.ts
> +export function quadOut(k: number) {
```suggestion
export function quadOut (k: number) {
```

2023-05-24 05:42 UTC, pandamicro commented on cocos/core/animation/easing.ts
> +export function quadInOut(k: number) {
```suggestion
export function quadInOut (k: number) {
```

2023-05-24 05:42 UTC, pandamicro commented on cocos/core/animation/easing.ts
> +export function cubicIn(k: number) {
```suggestion
export function cubicIn (k: number) {
```

2023-05-24 05:42 UTC, pandamicro commented on cocos/core/animation/easing.ts
> +export function cubicOut(k: number) {
```suggestion
export function cubicOut (k: number) {
```

2023-05-24 05:42 UTC, pandamicro commented on cocos/core/animation/easing.ts
> +export function cubicInOut(k: number) {
```suggestion
export function cubicInOut (k: number) {
```

2023-05-24 05:42 UTC, pandamicro commented on cocos/core/animation/easing.ts
> +export function quartIn(k: number) {
```suggestion
export function quartIn (k: number) {
```

2023-05-24 05:42 UTC, pandamicro commented on cocos/core/animation/easing.ts
> +export function quartOut(k: number) {
```suggestion
export function quartOut (k: number) {
```

2023-05-24 05:42 UTC, pandamicro commented on cocos/core/animation/easing.ts
> +export function quartInOut(k: number) {
```suggestion
export function quartInOut (k: number) {
```

2023-05-24 05:42 UTC, pandamicro commented on cocos/core/animation/easing.ts
> +export function quintIn(k: number) {
```suggestion
export function quintIn (k: number) {
```

2023-05-24 05:42 UTC, pandamicro commented on cocos/core/animation/easing.ts
> +export function quintOut(k: number) {
```suggestion
export function quintOut (k: number) {
```

2023-05-24 05:42 UTC, pandamicro commented on cocos/core/animation/easing.ts
> +export function quintInOut(k: number) {
```suggestion
export function quintInOut (k: number) {
```

2023-05-24 05:42 UTC, pandamicro commented on cocos/core/animation/easing.ts
> +export function sineIn(k: number) {
```suggestion
export function sineIn (k: number) {
```

2023-05-24 05:42 UTC, pandamicro commented on cocos/core/animation/easing.ts
> +export function sineOut(k: number) {
```suggestion
export function sineOut (k: number) {
```

2023-05-24 05:42 UTC, pandamicro commented on cocos/core/animation/easing.ts
> +export function sineInOut(k: number) {
```suggestion
export function sineInOut (k: number) {
```

2023-05-24 05:42 UTC, pandamicro commented on cocos/core/animation/easing.ts
> +export function expoIn(k: number) {
```suggestion
export function expoIn (k: number) {
```

2023-05-24 05:42 UTC, pandamicro commented on cocos/core/animation/easing.ts
> +export function expoOut(k: number) {
```suggestion
export function expoOut (k: number) {
```

2023-05-24 05:42 UTC, pandamicro commented on cocos/core/animation/easing.ts
> +export function expoInOut(k: number) {
```suggestion
export function expoInOut (k: number) {
```

2023-05-24 05:42 UTC, pandamicro commented on cocos/core/animation/easing.ts
> +export function circIn(k: number) {
```suggestion
export function circIn (k: number) {
```

2023-05-24 05:42 UTC, pandamicro commented on cocos/core/animation/easing.ts
> +export function circOut(k: number) {
```suggestion
export function circOut (k: number) {
```

2023-05-24 05:42 UTC, pandamicro commented on cocos/core/animation/easing.ts
> +export function circInOut(k: number) {
```suggestion
export function circInOut (k: number) {
```

2023-05-24 05:42 UTC, pandamicro commented on cocos/core/animation/easing.ts
> +export function elasticIn(k: number) {
```suggestion
export function elasticIn (k: number) {
```

2023-05-24 05:42 UTC, pandamicro commented on cocos/core/animation/easing.ts
> +export function elasticOut(k: number) {
```suggestion
export function elasticOut (k: number) {
```

2023-05-24 05:42 UTC, pandamicro commented on cocos/core/animation/easing.ts
> +export function elasticInOut(k: number) {
```suggestion
export function elasticInOut (k: number) {
```

2023-05-24 05:42 UTC, pandamicro commented on cocos/core/animation/easing.ts
> +export function backIn(k: number) {
```suggestion
export function backIn (k: number) {
```

2023-05-24 05:42 UTC, pandamicro commented on cocos/core/animation/easing.ts
> +export function backOut(k: number) {
```suggestion
export function backOut (k: number) {
```

2023-05-24 05:42 UTC, pandamicro commented on cocos/core/animation/easing.ts
> +export function backInOut(k: number) {
```suggestion
export function backInOut (k: number) {
```

2023-05-24 05:42 UTC, pandamicro commented on cocos/core/animation/easing.ts
> +export function bounceIn(k: number) {
```suggestion
export function bounceIn (k: number) {
```

2023-05-24 05:42 UTC, pandamicro commented on cocos/core/animation/easing.ts
> +export function bounceOut(k: number) {
```suggestion
export function bounceOut (k: number) {
```

2023-05-24 05:42 UTC, pandamicro commented on cocos/core/animation/easing.ts
> +export function bounceInOut(k: number) {
```suggestion
export function bounceInOut (k: number) {
```

2023-05-24 05:42 UTC, pandamicro commented on cocos/core/animation/easing.ts
> +export function smooth(k: number) {
```suggestion
export function smooth (k: number) {
```

2023-05-24 05:42 UTC, pandamicro commented on cocos/core/animation/easing.ts
> +export function fade(k: number) {
```suggestion
export function fade (k: number) {
```

2023-05-24 05:42 UTC, pandamicro commented on cocos/core/animation/easing.ts
> +function _makeOutIn(fnIn: (k: number) => number, fnOut: (k: number) => number) {
```suggestion
function _makeOutIn (fnIn: (k: number) => number, fnOut: (k: number) => number) {
```

2026-05-28 01:32 UTC, closed without merging