Add renderMesh bias for v3.5.0
cocos/cocos-engine pull request #10102
Opened 2022-02-14 09:12 UTC by troublemaker52025

Re: cocos-creator/3d-tasks#

Changelog:
 *

2022-02-14 09:13 UTC, troublemaker52025 commented
* https://github.com/cocos-creator/3d-tasks/issues/8538

2022-02-21 09:09 UTC, jk20012001 approved these changes

2022-02-24 06:59 UTC, pandamicro requested changes
More verification to do

- [ ] Search in editor code the usage of renamed APIs
- [ ] Check MaterialUpgrade scene in test case to check whether old effect can upgrade
- [ ] Ensure backward compatibility for API usage and data migration

2022-02-24 06:59 UTC, pandamicro commented on cocos/3d/lights/directional-light-component.ts
> +    set shadowFar (val) {
Renaming need backward compatibility, including 

1. Declare `@formerlySerializedAs` to ensure data migration
2. Add replaceProperty in module's deprecated

2022-02-24 06:59 UTC, pandamicro commented on cocos/core/renderer/scene/directional-light.ts
> -    set fixedArea (val) {
Need deprecation

2022-02-24 07:15 UTC, troublemaker52025 commented on cocos/core/renderer/scene/directional-light.ts
> -    set fixedArea (val) {
这是 “v3.5.0 shadow 属性迁移至灯光组件” 时的命名，v3.5.0 还未发布，也未有用户调用到 fixedArea 接口，故更名不需要做迁移，也不需要废弃接口申明

2022-02-24 07:15 UTC, troublemaker52025 commented
>

2022-02-24 07:25 UTC, troublemaker52025 commented
> More verification to do
> 
>     * [ ]  Search in editor code the usage of renamed APIs
> 
>     * [ ]  Check MaterialUpgrade scene in test case to check whether old effect can upgrade
> 
>     * [ ]  Ensure backward compatibility for API usage and data migration

 * [x]  Search in editor code the usage of renamed APIs * https://github.com/cocos-creator/editor-3d/pull/6632
 * [ ] Check MaterialUpgrade scene in test case to check whether old effect can upgrade
 * [x]  Ensure backward compatibility for API usage and data migration [API usage] * https://github.com/cocos-creator/test-cases-3d/pull/580

2022-02-24 15:26 UTC, pandamicro approved these changes

2022-02-24 15:27 UTC, merged