add dynamic mesh
cocos/cocos-engine pull request #10291
Opened 2022-03-09 10:33 UTC by stanleyljl

Re: cocos-creator/3d-tasks#https://github.com/cocos-creator/3d-tasks/issues/11053

Changelog:
 * add dynamic mesh

2022-03-11 02:45 UTC, minggo commented on cocos/3d/assets/mesh.ts
> +        maxIndices: number;
maxVertices 和 maxIndices 没法体现出是子模型的，很容易让人理解为总的顶点数和总的索引数。

2022-03-11 03:05 UTC, minggo commented on cocos/3d/assets/mesh.ts
> +    public init () {
已经有 initialize 接口了，再加个 init 接口比较奇怪。

2022-03-11 09:01 UTC, stanleyljl commented on cocos/3d/assets/mesh.ts
> +        maxIndices: number;
1

2022-03-11 09:01 UTC, stanleyljl commented on cocos/3d/assets/mesh.ts
> +    public init () {
ts不是不能重载吗？有啥好建议

2022-03-11 09:20 UTC, minggo commented on cocos/3d/assets/mesh.ts
> +    public init () {
现在是 Mesh、DynamicMesh 要在一个类中实现？DynamicMesh 能是 mesh 的子类吗？

2022-03-11 09:22 UTC, stanleyljl commented on cocos/3d/assets/mesh.ts
> +    public init () {
不行，那改动太大了，而且也没必要，目前的改动应该是最小的

2022-03-11 11:01 UTC, minggo commented on cocos/3d/assets/mesh.ts
> +    public init () {
嗯嗯，后续需要继续重构。

2022-03-11 11:01 UTC, minggo approved these changes

2022-03-15 11:45 UTC, pandamicro requested changes

2022-03-15 11:45 UTC, pandamicro commented on cocos/3d/assets/mesh.ts
> +    export interface IDynamicStruct {
Can IDynamicInfo be merged ? It seems unnecessary.

2022-03-15 11:45 UTC, pandamicro commented on cocos/3d/assets/mesh.ts
> +                for (const idx of primitive.vertexBundelIndices) {
Do not use for of, use normal for loop (Array) or for in (Object)

2022-03-15 11:45 UTC, pandamicro commented on cocos/3d/assets/mesh.ts
> +                for (const idx of primitive.vertexBundelIndices) {
Likewise

2022-03-15 11:45 UTC, pandamicro commented on cocos/3d/assets/mesh.ts
> +            this._initialized = true;
Initialized check can be extract out of the if else block

2022-03-15 11:45 UTC, pandamicro commented on cocos/3d/assets/mesh.ts
> +        if (!this._struct.dynamic) {
Add a warnID warning to this

2022-03-15 11:45 UTC, pandamicro commented on cocos/3d/assets/mesh.ts
> +        if (primitiveIndex >= this._struct.primitives.length) {
likewise

2022-03-15 11:45 UTC, pandamicro commented on cocos/3d/assets/mesh.ts
> +            for (const ca of geometry.customAttributes) {
use normal for loop

2022-03-15 11:45 UTC, pandamicro commented on cocos/3d/assets/mesh.ts
> +    public updateSubMesh (primitiveIndex: number, geometry: IDynamicGeometry) {
There are too many data copy in this function, can we have a high performance version of updateSubMesh? like

```
interface IDynamicGeometryDirect {
    attributes: Attribute[];
    vertices: Float32Array;
    indices16?: Uint16Array;
    indices32?: Uint32Array;
    minPos?: {
        x: number;
        y: number;
        z: number;
    };
    maxPos?: {
        x: number;
        y: number;
        z: number;
    };
    primitiveMode?: PrimitiveMode;
    doubleSided?: boolean;
}
public updateSubMeshDirect (primitiveIndex: number, geometry: IDynamicGeometryDirect)
```

We can directly replace the current sub mesh `_data` with the given `vertices`, no need to copy

2022-03-15 11:45 UTC, pandamicro commented on cocos/3d/misc/create-mesh.ts
> +        for (const ca of geometry.customAttributes) {
Use normal for loop

2022-03-15 11:45 UTC, pandamicro commented on cocos/3d/misc/create-mesh.ts
> +export function createDynamicMesh (primitiveIndex: number, geometry: IDynamicGeometry, out?: Mesh, options?: ICreateDynamicMeshOptions) {
If we prefer user to use MeshUtils, then we shouldn't export this new function, only need to keep backward compatibility for `createMesh`

2022-03-15 11:45 UTC, pandamicro commented on cocos/3d/misc/create-mesh.ts
> +    static createDynamicMesh (primitiveIndex: number, geometry: IDynamicGeometry, out?: Mesh, options?: ICreateDynamicMeshOptions) {
Need API documentation for `MeshUtils` class and both functions

2022-03-15 11:45 UTC, pandamicro commented on cocos/core/assets/rendering-sub-mesh.ts
> +    set drawInfo (info: DrawInfo | null | undefined) {
API doc

2022-03-15 11:45 UTC, pandamicro commented on cocos/core/gfx/base/input-assembler.ts
> +    set drawInfo (info: DrawInfo) {
API doc

2022-03-15 11:45 UTC, pandamicro commented on native/cocos/3d/misc/CreateMesh.h
> +class MeshUtils {
We can keep `MeshUtils` class and remove all standalone functions in cpp implementation. It won't break high level API compatibility. Before 3.5 native APIs are rarely used directly

2022-03-15 11:45 UTC, pandamicro commented on native/cocos/bindings/manual/jsb_conversions.h
> +inline bool nativevalue_to_se(const cc::TypedArrayTemp<T> &typedArray, se::Value &to, se::Object *ctx); // NOLINT
Can't find `TypedArrayTemp` anywhere else

2022-03-15 11:58 UTC, stanleyljl commented on cocos/3d/assets/mesh.ts
> +    export interface IDynamicStruct {
本来只有一层，即IDynamicInfo是必要的，后来计算包围盒需要缓存所有subMesh的包围盒，所以多加了一层抽象，不一定需要合并，均可。

2022-03-15 12:27 UTC, stanleyljl commented on cocos/3d/assets/mesh.ts
> +    public updateSubMesh (primitiveIndex: number, geometry: IDynamicGeometry) {
这样是快一点点，但是缺少灵活性，用户会有各种定制属性，比如position + normal, position + normal + color等等，其实拷贝几个大数组和拷贝一整个数组性能差别不会很大，比如c++汇编都是一次8个字节这样拷贝完整个数组，没有指令能一次拷贝完，其实最优化的方式就是_data就是用户提供的，这样内存那份数据都不需要拷贝，但是之前最遗憾的设计就是有了这个_data（我猜想可能是迁就了序列化为一个bin，导致后面整个设计与实现都变形了），而应把_data分解为vertex buffers，后续这块要重构最主要就是把_data去掉，以及上面的BufferView，和不直观的接口。

2022-03-15 12:58 UTC, stanleyljl commented on cocos/3d/misc/create-mesh.ts
> +export function createDynamicMesh (primitiveIndex: number, geometry: IDynamicGeometry, out?: Mesh, options?: ICreateDynamicMeshOptions) {
因为createMesh已经导出了，所以和他保持一致

2022-03-15 13:17 UTC, stanleyljl commented on native/cocos/3d/misc/CreateMesh.h
> +class MeshUtils {
引擎中有其他地方调用了createMeshInfo，如果把createMesh放到cpp，那createMeshInfo也需要放到MeshUtils，与TS版又不太一致了。有点纠结

2022-03-15 13:18 UTC, stanleyljl commented on native/cocos/bindings/manual/jsb_conversions.h
> +inline bool nativevalue_to_se(const cc::TypedArrayTemp<T> &typedArray, se::Value &to, se::Object *ctx); // NOLINT
这个没有预先声明，android会编译不过

2022-03-16 02:05 UTC, pandamicro commented on cocos/3d/assets/mesh.ts
> +    public updateSubMesh (primitiveIndex: number, geometry: IDynamicGeometry) {
Agree with the direction

2022-03-16 02:49 UTC, stanleyljl commented on native/cocos/3d/misc/CreateMesh.h
> +class MeshUtils {
已修改

2022-03-16 04:47 UTC, pandamicro approved these changes

2022-03-16 08:55 UTC, merged