V3.5.0 renderer component 0315
cocos/cocos-engine pull request #10342
Opened 2022-03-15 05:51 UTC by arsen2010

Re: cocos-creator/3d-tasks#9907

Changelog:
 *

2022-03-15 08:11 UTC, zxx43 approved these changes

2022-03-16 08:34 UTC, holycanvas commented on cocos/core/components/renderable-component.ts
> +                this.setMaterial(null, i);
我不确定这里逻辑和之前是否一样， @zxx43 确定这样没问题么

2022-03-22 04:28 UTC, pandamicro requested changes

2022-03-22 04:28 UTC, pandamicro commented on cocos/core/components/renderable-component.ts
> +                this.setMaterial(null, i);
不行哦，要用 setMaterialInstance，编辑器要解决的问题是什么

2022-03-22 06:42 UTC, pandamicro requested changes

2022-03-22 06:42 UTC, pandamicro commented on cocos/core/components/renderable-component.ts
> +            for (let i = this._materials.length + dLen; i < this._materials.length; ++i) {
start 应该用 val.length

2022-03-22 06:42 UTC, pandamicro commented on cocos/core/components/renderable-component.ts
> +                this.setMaterial(null, i);
检查了一下对于 null 参数来说是等价的，但是除非必要不做代码上的修改，所以这里请保留使用 setMaterialInstance，目的是为了正确销毁旧的 material instance

2022-03-22 06:42 UTC, pandamicro commented on cocos/core/components/renderable-component.ts
> +            this._materials.length = val.length;
把这个移出 if 条件把，和前面的 if 一样，materials 和 materialInstances 都需要设置 length，可以统一在 `if (dLen < 0)` 后面做

2022-03-22 09:45 UTC, pandamicro approved these changes

2022-03-22 09:57 UTC, holycanvas approved these changes

2022-03-22 09:57 UTC, merged