remove hidden
cocos/cocos-engine pull request #10414
Opened 2022-03-21 04:48 UTC by holycanvas

Re: cocos-creator/3d-tasks#

Changelog:
 *

2022-03-21 11:11 UTC, shrinktofit approved these changes

2022-03-22 04:34 UTC, pandamicro requested changes

2022-03-22 04:34 UTC, pandamicro commented on .vscode/settings.json
> -        "source.fixAll": true,
This would affect the current using experience, suggest to add an option about this elsewhere and keep the current behavior

2022-03-22 07:10 UTC, pandamicro approved these changes

2022-03-22 07:11 UTC, merged