First Version Sprite Renderer(Rect mode)
cocos/cocos-engine pull request #10592
Opened 2022-03-30 08:33 UTC by LinYunMo

Re: https://github.com/cocos/3d-tasks/issues/9127
Depend: https://github.com/cocos/engine-extensions/pull/70

2022-03-31 04:01 UTC, SantyWang commented on cocos/2d/framework/sprite-renderer.ts
> +            this._spriteFrame.mesh.initialize();
这里不太好，理论上 spriteFrame 的数据是在 spriteFrame 内部处理好的，不应该让组件去初始化

2022-03-31 04:01 UTC, SantyWang commented on cocos/2d/framework/sprite-renderer.ts
> +            mesh.initialize();
不应该在组件内去初始化资源

2022-03-31 04:01 UTC, holycanvas commented on editor/assets/effects/builtin-sprite-renderer.effect
> +    pos = cc_matProj * (cc_matView * cc_matWorld) * pos;
mvp 有矩阵的吧

2022-03-31 04:01 UTC, holycanvas commented on editor/assets/effects/builtin-sprite-renderer.effect
> +        cullMode: none
这个其实也可以考虑下

2022-05-17 03:36 UTC, holycanvas commented on cocos/2d/framework/sprite-renderer.ts
> +    public onLoad () {
onEnable seems better

2022-05-19 07:43 UTC, pandamicro requested changes

2022-05-19 07:43 UTC, pandamicro commented on cocos/2d/framework/sprite-renderer.ts
> + * @module 2D
No need to add package documentation any more

2022-05-19 07:43 UTC, pandamicro commented on cocos/2d/assets/sprite-frame.ts
> +    positions: number[]; // 顶点的位置，受几个值影响的模型空间值 // 计算
Always use English comment, also comment the internal layout of the data, like 

x0, y0, x1, y1 ...

2022-05-19 07:43 UTC, pandamicro commented on cocos/2d/assets/sprite-frame.ts
> +    rawPosition: Vec3[]; // 顶点的原始位置，像素值
Why we need rawPositions

2022-05-19 07:43 UTC, pandamicro commented on cocos/2d/assets/sprite-frame.ts
> +                temp_vec3.set(rawPosition[i], rawPosition[i + 1], rawPosition[i + 2]);
`new Vec3` to replace `set` plus `clone`

2022-05-19 07:43 UTC, pandamicro commented on cocos/2d/assets/sprite-frame.ts
> +                temp_vec3.set(rawPosition[i], rawPosition[i + 1], rawPosition[i + 2]);
`new Vec3` to replace `set` plus `clone`

2022-05-19 07:43 UTC, pandamicro commented on cocos/2d/assets/sprite-frame.ts
> +        // } : null as any;
vertices need to be cloned

2022-05-19 07:43 UTC, pandamicro commented on cocos/2d/assets/sprite-frame.ts
> +    triangles: number[]; // IB
`indexes` seems more appropriate

2022-05-19 07:43 UTC, pandamicro commented on cocos/2d/assets/sprite-frame.ts
> +            const pos = vertices.rawPosition[i];
Can we just share `rawPositions` and `positions`, convert each position and store back
But we might need to save rawPositions in editor, it's not a big deal, just want to save memory foot print in runtime

2022-05-19 07:43 UTC, pandamicro commented on cocos/2d/framework/sprite-model.ts
> +export class SpriteModel extends Model {
Why SpriteModel is necessary, just update manually using Model API is enough

2022-05-19 07:43 UTC, pandamicro commented on cocos/2d/framework/sprite-renderer.ts
> +    }
No need to write empty extended function

2022-05-25 03:14 UTC, LinYunMo commented on cocos/2d/assets/sprite-frame.ts
> +    rawPosition: Vec3[]; // 顶点的原始位置，像素值
when custom change some attribute affected vertex position，wo need rawPositon to calculation

2022-06-20 07:34 UTC, holycanvas approved these changes

2022-06-20 09:03 UTC, pandamicro commented on cocos/2d/assets/sprite-frame.ts
> +    POLYGON = 1, // todo
TODO what? please mark detail for all todo

2022-06-20 09:03 UTC, pandamicro commented on cocos/2d/assets/sprite-frame.ts
> +    get mesh () {
API doc for all new public APIs

2022-06-20 09:03 UTC, pandamicro commented on cocos/2d/assets/sprite-frame.ts
> +    protected _pixelsToUnit = 100;
Why set default value to 100

2022-06-20 09:03 UTC, pandamicro commented on cocos/2d/assets/sprite-frame.ts
> +            this.updateMesh();
Do we need to update mesh here ? Update mesh have high memory footprint

2022-06-20 09:03 UTC, pandamicro commented on cocos/2d/framework/sprite-renderer.ts
> +export class SpriteRenderer extends ModelRenderer {
API doc

2022-06-20 09:08 UTC, pandamicro approved these changes

2022-06-20 09:18 UTC, LinYunMo commented on cocos/2d/assets/sprite-frame.ts
> +    protected _pixelsToUnit = 100;
Experience Value，users need to adjust the size of the resources themselves

2022-06-20 09:22 UTC, LinYunMo commented on cocos/2d/assets/sprite-frame.ts
> +            this.updateMesh();
Yes it is required, but it does not have an impact if the SpriteRenderer is not used

2022-06-20 09:35 UTC, merged