Fix MotionStreak initializing and avoid trail delay by one frame
cocos/cocos-engine pull request #10982
Opened 2022-05-06 13:32 UTC by jareguo

Re: #9693

Changelog:
 * MotionStreak effect optimization: Fix the trail to the origin when initializing and avoid trail delay by one frame.

2022-05-06 13:33 UTC, jareguo commented
https://user-images.githubusercontent.com/1503156/167142067-487012cc-dd47-4e49-9dd1-ac7f5640559e.mp4

非常抱歉，是我的锅，之前做的时候有发现这个问题，拖得有点久后来提交时就忘修复了

2022-07-17 13:40 UTC, finscn commented
这个别忘了合到 2.4.10里

2022-07-18 03:00 UTC, finscn commented
不知道是不是 github 的bug,  用 `is:pr is:open head:v2.4.10` 搜索, 搜不到这个PR .
你们别忘了合并.

2022-07-18 13:14 UTC, pandamicro requested changes

2022-07-18 13:14 UTC, pandamicro commented on cocos2d/core/renderer/webgl/assemblers/motion-streak.js
>          let matrix = node._worldMatrix.m;
`let matrix = node.getWorldMatrix(cache_matrix);`

This will ensure the matrix is always updated, and it avoid using private method

2022-07-19 03:23 UTC, pandamicro approved these changes

2022-07-19 03:24 UTC, merged

2022-07-20 07:39 UTC, jareguo commented
> 不知道是不是 github 的bug, 用 `is:pr is:open head:v2.4.10` 搜索, 搜不到这个PR . 你们别忘了合并.

我都是用 \`base:v2.4.\` 进行模糊搜索