V3.5.1 fix particle switch error
cocos/cocos-engine pull request #11139
Opened 2022-05-18 09:05 UTC by zxx43

Re: #

### Changelog

* 

-------

### Continuous Integration

This pull request:

* [ ] needs automatic test cases check // Manual trigger with `@cocos-robot run test cases` afterward

-------

### Compatibility Check

This pull request:

* [ ] changes public API, and have ensured backward compatibility with [deprecated features](https://github.com/cocos/cocos-engine/blob/v3.5.0/docs/contribution/deprecated-features.md).
* [ ] affects platform compatibility, e.g. system version, browser version, platform sdk version, platform toolchain, language version, hardware compatibility etc.
* [ ] affects file structure of the build package or build configuration which requires user project upgrade.
* [ ] **introduces breaking changes**, please list all changes, affected features and the scope of violation.

issue: https://github.com/cocos/3d-tasks/issues/12315 & https://github.com/cocos/3d-tasks/issues/12325

2022-05-18 09:06 UTC, zxx43 commented
@cocos-robot run test cases

2022-05-18 09:07 UTC, zxx43 commented
@cocos-robot run test cases

2022-05-18 09:38 UTC, fish9167 commented
@cocos-robot run test cases

2022-05-19 07:49 UTC, dogeFu commented
Resolves: cocos/3d-tasks#12297

2022-05-23 11:29 UTC, pandamicro requested changes

2022-05-23 11:29 UTC, pandamicro commented on cocos/particle/particle-system.ts
> +        } else if (this.getParticleCount() > 0) {
Just use else is enough, the condition is contrary to the if condition

2022-05-23 14:12 UTC, zxx43 commented
we have to update descriptorSet before attach，so put attach in update or lateUpdate will be fine

2022-05-24 00:45 UTC, pandamicro approved these changes

2022-05-24 02:23 UTC, merged