[WIP] Add check box
cocos/cocos-engine pull request #1126
Opened 2016-09-19 08:47 UTC by zilongshanren

https://github.com/cocos-creator/fireball/issues/1463

Changes proposed in this pull request:
 * Add Toggle and ToggleGroup
 * fix button color and scale transition issue (introduced by the last PR)
 * todo: doc strings

@cocos-creator/engine-admins

2016-09-19 08:52 UTC, jareguo requested changes
是不是应该注册到 modules.json

2016-09-19 08:53 UTC, jareguo commented on cocos2d/core/components/CCToggle.js
> +    extends: cc.Button,
如果要注册到 module.json，这里就要 require cc.Button 否则模块依赖关系无法建立

2016-09-19 08:55 UTC, jareguo commented on cocos2d/core/components/CCToggle.js
> +        isChecked: {
缺 API 文档啊

2016-09-19 08:56 UTC, jareguo commented on cocos2d/core/components/CCToggle.js
> +        toggleGroup: {
同缺

2016-09-19 08:56 UTC, jareguo commented on cocos2d/core/components/CCToggle.js
> +        checkMark: {
同缺

2016-09-19 08:56 UTC, jareguo commented on cocos2d/core/components/CCToggle.js
> +     * !#zh 使 toggle 按钮处于选中状态
缺了 `@method`

2016-09-19 08:57 UTC, jareguo commented on cocos2d/core/components/CCToggle.js
> +     * !#zh 使 toggle 按钮处于未选中状态
缺了 `@method`

2016-09-19 08:57 UTC, jareguo commented on cocos2d/core/components/CCToggleGroup.js
> +         * !#en
缺了 `@property`

2016-09-19 08:57 UTC, jareguo requested changes
API

2016-09-19 08:58 UTC, jareguo commented on cocos2d/core/components/CCToggle.js
> +    onLoad: function () {
onLoad 为什么不写到 __preload 里面？

2016-09-19 08:59 UTC, jareguo commented on cocos2d/core/components/CCToggle.js
> +                this.checkMark.active = false;
直接 `this.checkMark.active = !!this.isChecked;` 就行了吧

2016-09-19 09:01 UTC, jareguo commented on cocos2d/core/components/CCToggle.js
> +        this.clickEvents = [event];
这样会不会覆盖用户自己注册的事件？

2016-09-19 09:02 UTC, jareguo commented on cocos2d/core/components/CCToggle.js
> +    toggleToggleStatus: function (event) {
直接叫 toggle 是不是更直接？

2016-09-19 09:06 UTC, jareguo commented on cocos2d/core/components/CCToggle.js
> +            cc.Component.EventHandler.emitEvents(this.checkEvents, event, this);
为什么调用 check 时不 emitEvents ?

2016-09-19 09:06 UTC, jareguo requested changes

2016-09-19 09:10 UTC, jareguo commented on cocos2d/core/components/CCToggle.js
> +        executeInEditMode: true
executeInEditMode 不用定义因为 cc.Button 已经有定义了

2016-09-19 09:10 UTC, jareguo requested changes

2016-09-19 09:14 UTC, jareguo commented on cocos2d/core/components/CCToggleGroup.js
> +        var index = this._toggleItem.indexOf(toggle);
_toggleItem 建议用复数

2016-09-19 09:15 UTC, jareguo commented on cocos2d/core/components/CCToggleGroup.js
> +            }
我不太能理解这边的逻辑。如果 oldItem.isChecked 为 true，newItem.isChecked 也为 true，这里怎么能够保证将 oldItem.isChecked 重置？

2016-09-19 09:18 UTC, jareguo requested changes

2016-09-19 09:19 UTC, jareguo commented on cocos2d/core/components/CCToggleGroup.js
> +         * !#en
这个变量是做什么用的？

2016-09-19 09:21 UTC, zilongshanren commented on cocos2d/core/components/CCToggleGroup.js
> +         * !#en
这个变量的作用参考： https://docs.unity3d.com/Manual/script-ToggleGroup.html

2016-09-19 09:21 UTC, zilongshanren commented on cocos2d/core/components/CCToggleGroup.js
> +        var index = this._toggleItem.indexOf(toggle);
ok

2016-09-19 09:22 UTC, zilongshanren commented on cocos2d/core/components/CCToggleGroup.js
> +            }
这里的逻辑是先执行 if (item.isChecked && item.enabled) ，这里可以保证只有第一个 item 为 true 以后，isChecked 才会设置为 true. 后面如果再碰到 item.enabled 的话，都需要设置 isChecked = false. 这样就保证了只有一个 item 的 isChecked = true.

2016-09-19 09:22 UTC, zilongshanren commented on cocos2d/core/components/CCToggle.js
> +     * !#zh 使 toggle 按钮处于未选中状态
got.

2016-09-19 09:22 UTC, zilongshanren commented on cocos2d/core/components/CCToggle.js
> +     * !#zh 使 toggle 按钮处于选中状态
got

2016-09-19 09:23 UTC, zilongshanren commented on cocos2d/core/components/CCToggle.js
> +            cc.Component.EventHandler.emitEvents(this.checkEvents, event, this);
check 的时候是要 emitEvent，我改一下。

2016-09-19 09:23 UTC, zilongshanren commented on cocos2d/core/components/CCToggle.js
> +    toggleToggleStatus: function (event) {
也行。

2016-09-19 09:24 UTC, zilongshanren commented on cocos2d/core/components/CCToggle.js
> +        this.clickEvents = [event];
可能会，这里应该要改成 push

2016-09-19 09:25 UTC, zilongshanren commented on cocos2d/core/components/CCToggle.js
> +                this.checkMark.active = false;
恩， 可以。

2016-09-19 09:25 UTC, zilongshanren commented on cocos2d/core/components/CCToggle.js
> +    onLoad: function () {
恩，可以写到 __preload

2016-09-19 09:25 UTC, zilongshanren commented on cocos2d/core/components/CCToggle.js
> +        checkMark: {
正在补。。。

2016-09-19 09:26 UTC, zilongshanren commented on cocos2d/core/components/CCToggle.js
> +        toggleGroup: {
正在补。。。

2016-09-19 09:26 UTC, zilongshanren commented on cocos2d/core/components/CCToggle.js
> +        isChecked: {
正在补。。。

2016-09-19 09:26 UTC, zilongshanren commented on cocos2d/core/components/CCToggle.js
> +        executeInEditMode: true
ok

2016-09-19 09:26 UTC, zilongshanren commented on cocos2d/core/components/CCToggle.js
> +    extends: cc.Button,
require('CCButton.js')??

2016-09-19 09:27 UTC, jareguo commented on cocos2d/core/components/CCToggle.js
> +    extends: cc.Button,
对

2016-09-19 09:29 UTC, jareguo commented on cocos2d/core/components/CCToggleGroup.js
> +            }
但如果第一个为 true 的 item 是旧的 toggle，那这里就没办法把它的 isCheck 设为 false

2016-09-19 10:22 UTC, jareguo approved these changes

2016-09-19 10:24 UTC, jareguo approved these changes

2016-09-21 06:20 UTC, zilongshanren commented
new PR here: https://github.com/cocos-creator/engine/pull/1132

2016-09-21 06:20 UTC, closed without merging