add slider component for fireball/issues/1462
cocos/cocos-engine pull request #1128
Opened 2016-09-20 02:07 UTC by knoxHuang

Re: cocos-creator/fireball#1462

Changes proposed in this pull request:
 *  添加 Slider UI 组件

@cocos-creator/engine-admins

2016-09-20 02:47 UTC, jareguo commented on cocos2d/core/components/CCSlider.js
> +    PROGRESS_CHANGED : 0
就一个条目的枚举…… 有必要吗

2016-09-20 02:48 UTC, jareguo commented on cocos2d/core/components/CCSlider.js
> +        this._draging = false;
dragging

2016-09-20 02:49 UTC, knoxHuang commented on cocos2d/core/components/CCSlider.js
> +    PROGRESS_CHANGED : 0
如果有新的事件在加？

2016-09-20 02:49 UTC, jareguo commented on cocos2d/core/components/CCSlider.js
> +        executeInEditMode: false
executeInEditMode 默认就是 false 的，不需要特殊声明吧？

2016-09-20 02:50 UTC, jareguo commented on cocos2d/core/components/CCSlider.js
> +            type: 'Float',
cc.Float

2016-09-20 02:51 UTC, jareguo commented on cocos2d/core/components/CCSlider.js
> +        this._updateHandleForProgress();
为什么 preload 和 onLoad 要分开处理

2016-09-20 02:55 UTC, jareguo requested changes

2016-09-20 06:00 UTC, jareguo commented on cocos2d/core/components/CCSlider.js
> +    PROGRESS_CHANGED : 0
那还是去掉吧？这里应该不会有什么其它事件加入了。就算有的话，考虑到方便编辑器可视化编辑，也是应该定义新的回调数组而不是复用 sliderEvents

2016-09-20 06:03 UTC, jareguo commented on cocos2d/core/components/CCSlider.js
> +        sliderEvents: {
叫 slideEvents 会不会好点？

2016-09-20 06:18 UTC, jareguo approved these changes

2016-09-20 06:19 UTC, jareguo approved these changes

2016-09-20 06:56 UTC, zilongshanren commented on cocos2d/core/components/CCSlider.js
> +        var newPos = this.handle.node.position;
这里的 newPos 没必要赋值吧，因为你取的是 handle 原来的 pos，感觉应该是个 oldPos。。。 如果不赋值，阅读代码的时候就没有这个误解。。

2016-09-20 06:57 UTC, zilongshanren commented on cocos2d/core/components/CCSlider.js
> +        var newPos = this.handle.node.position;
另个这个函数建议改名： _updateHandlePosition

2016-09-20 06:59 UTC, zilongshanren commented on cocos2d/core/components/CCSlider.js
> +        if (!this.handle) { return; }
这个函数的名字也有问题，我可以理解为”处理 slide 相关的逻辑“么。。。
从这个函数里面的操作来看，它是组合了 1. 计算 新的progress  2.计算新的 handle position 3. 发送 slide 事件
建议这 3 个事件分别弄 3 个函数并放到你这个_handleSliderLogic 里面。。

2016-09-20 06:59 UTC, zilongshanren commented on cocos2d/core/components/CCSlider.js
> +        if (!this.handle) { return; }
而计算新的 handle 位置这个功能应该是与 _updateHandleForProgress 这个函数的功能有重复。

2016-09-20 07:02 UTC, zilongshanren commented on cocos2d/core/components/CCSlider.js
> +        this._handleSliderLogic(event.touch);
建议把 handleSliderLogic 这个函数去掉，这里直接调用 3 个函数。1. 更新 progress 的值 2.更新 handle 的位置 3. 发送事件  因为 handleSliderLogic 这种函数名不能给阅读代码提示任何帮助信息。

2016-09-20 07:04 UTC, zilongshanren commented on cocos2d/core/components/CCSlider.js
> +        var handleSprite = this.handle.getComponent(cc.Sprite);
handle 状态的修改应该是 button 来处理的吧，为什么这里要单独去处理 pressed 的状态？而且 handle 是一个 cc.Button，它不一定包含一个 cc.sprite 组件。只有它的 target 才会一定包含一个 sprite 组件，但是 target 不一定等于自身。

2016-09-20 07:05 UTC, zilongshanren commented on cocos2d/core/components/CCSlider.js
> +        this.background.node.position = this._offsetAnchorPos();
这个 changedAchor 函数有 typo，而且名字取的不好。

2016-09-20 07:05 UTC, zilongshanren commented on cocos2d/core/components/CCSlider.js
> +    _offsetAnchorPos: function () {
_offsetAnchorPos 我也看不出来到底是在计算什么。。。能解释一下么。。

2016-09-20 07:11 UTC, zilongshanren requested changes

2016-09-21 04:02 UTC, zilongshanren commented on cocos2d/core/components/CCSlider.js
> +        this.progress = progress;
this.progress = progress 会导致 _updateHandlePosition 多调用一次。

2016-09-21 04:02 UTC, zilongshanren approved these changes

2016-09-21 05:40 UTC, zilongshanren commented
LGTM

2016-09-21 06:03 UTC, merged