Refactor CCLoader to support multi queues and better progression
cocos/cocos-engine pull request #1135
Opened 2016-09-21 07:56 UTC by pandamicro

Re: cocos-creator/fireball#3395

Changes proposed in this pull request:
 * 支持每次 Load 独立的队列
 * 更好的进度信息

这个 PR 的思路是把所有 item 的数据管理从 pipeline 中抽离出来，全部由 LoadingItems 来管理，让 pipeline 仅仅负责在管道中运送数据，Loader 可以同时有多个 LoadingItems 队列，某个资源的依赖也是通过 LoadingItems 队列来进行加载和完成回调。

关于循环依赖，对于已经存在于 Loader 的某个队列中的资源，不重复加载，视为其已经加载完成，在 depends 设置的时候根据 item.complete 状态来决定要等待其加载完成还是直接设置依赖属性。

> Makes sure these boxes are checked before submitting your PR - thank you!
>
- [x] If your pull request has gone "stale", you should **rebase** your work on top of the latest version of the upstream branch.
- [x] If your commit history is full of small, unimportant commits (such as "fix pep8" or "update tests"), **squash** your commits down to a few, or one, discreet changesets before submitting a pull request.
- To official teams:
  - [x] Check that your javascript is following our [style guide](https://github.com/cocos-creator/fireball/blob/dev/.github/CONTRIBUTING.md) and end files with a newline
  - [x] Document new code with comments in source code based on [API Docs](https://github.com/cocos-creator/fireball#api-docs)

@cocos-creator/engine-admins

2016-09-21 07:57 UTC, pandamicro commented
先不要合并，还需要整理

2016-09-21 13:31 UTC, jareguo approved these changes

2016-09-22 10:20 UTC, jareguo commented on cocos2d/core/load-pipeline/loading-items.js
> +        else if (subDep.deps && checkCircleReference(owner, subDep)) {
这也太复杂了吧，其实你要检测的应该不是循环依赖，而是是否有相同资源在加载才对吧。用一个字典就能判断出来的。

2016-09-22 10:20 UTC, jareguo requested changes

2016-09-22 10:23 UTC, pandamicro commented on cocos2d/core/load-pipeline/loading-items.js
> +        else if (subDep.deps && checkCircleReference(owner, subDep)) {
就是要检查循环依赖诶，如果资源存在就直接当做完成的话，可能导致属性缺失的问题。所以还是需要等待正在加载的资源完成，然而需要等待，就需要解除循环依赖。

2016-09-22 10:25 UTC, jareguo commented on cocos2d/core/load-pipeline/loading-items.js
> +        else if (subDep.deps && checkCircleReference(owner, subDep)) {
当前会话中如果有相同资源在加载，就可以当做完成了，直接赋值属性就不会缺失了。

2016-09-22 10:36 UTC, pandamicro commented on cocos2d/core/load-pipeline/loading-items.js
> +        else if (subDep.deps && checkCircleReference(owner, subDep)) {
刚刚测了一下，现在新版本不用 checkCircleReference 也没什么问题，不过很难讲，要好好测试

2016-09-22 10:37 UTC, jareguo commented on cocos2d/core/load-pipeline/loading-items.js
> +        else if (subDep.deps && checkCircleReference(owner, subDep)) {
可以拿以前 AssetLibrary 的测试用例试试…… 过了问题就不大了

2016-09-24 15:24 UTC, pandamicro commented
严格的循环依赖检测已经删除，所有 unit test 都已通过
明天我会把文档注释补齐

2016-09-24 15:48 UTC, jareguo commented on cocos2d/audio/CCAudio.js
> +    proto.off = EventTarget.prototype.off;
这里建议改成 cc.js.extend(cc.Audio, EventTarget) 吧，这样 instanceof 运算符也才有效

2016-09-24 15:50 UTC, jareguo requested changes

2016-09-25 10:24 UTC, pandamicro commented
Done, ready to be merged, @jareguo 再看看

2016-09-25 14:37 UTC, jareguo approved these changes

2016-09-25 14:37 UTC, jareguo commented
我没什么问题了

2016-09-26 02:57 UTC, merged