[v3.6.0] CSM panel modification
cocos/cocos-engine pull request #11397
Opened 2022-06-08 02:44 UTC by troublemaker52025

Re: #

### Changelog

* 

-------

### Continuous Integration

This pull request:

* [ ] needs automatic test cases check.

  > Manual trigger with `@cocos-robot run test cases` afterward.

-------

### Compatibility Check

This pull request:

* [ ] changes public API, and have ensured backward compatibility with [deprecated features](https://github.com/cocos/cocos-engine/blob/v3.5.0/docs/contribution/deprecated-features.md).
* [ ] affects platform compatibility, e.g. system version, browser version, platform sdk version, platform toolchain, language version, hardware compatibility etc.
* [ ] affects file structure of the build package or build configuration which requires user project upgrade.
* [ ] **introduces breaking changes**, please list all changes, affected features and the scope of violation.

2022-06-08 02:44 UTC, troublemaker52025 commented
@cocos-robot run test cases

2022-06-08 04:13 UTC, jk20012001 commented on cocos/core/renderer/scene/directional-light.ts
>      protected _shadowCSMValueDirty = false;
_csmValueDirty

2022-06-08 04:13 UTC, jk20012001 commented on cocos/core/renderer/scene/shadows.ts
> +
UI显示为No CSM和4 Levels CSM

2022-06-09 04:13 UTC, troublemaker52025 commented on cocos/core/scene-graph/scene-globals.ts
> -        return this._size;
该函数引擎内部及编辑器已无人使用，故废弃该接口，并添加废弃申明

2022-06-09 04:36 UTC, jk20012001 commented on native/cocos/renderer/pipeline/shadow/CSMLayers.cpp
> +        if (dirLight->isCsmValueDirty() || _levelCount != levelCount ||
isCSMValueDirty

2022-06-09 04:36 UTC, jk20012001 commented on native/cocos/renderer/pipeline/shadow/CSMLayers.cpp
> +    dirLight->setCsmValueDirty(false);
setCSMValueDirty

2022-06-09 04:36 UTC, jk20012001 commented on native/tools/tojs/scene.ini
> +       DirectionalLight::[direction illuminance illuminanceHDR illuminanceLDR shadowEnabled/isShadowEnabled shadowPcf shadowBias shadowNormalBias shadowSaturation shadowDistance shadowInvisibleOcclus
CSM

2022-06-09 06:15 UTC, jk20012001 approved these changes

2022-06-09 08:30 UTC, pandamicro requested changes
How can user specify Cascade Shadow Map quality, for example use 2 levels or 3 levels csm ?
I suggest adding a global setting in SceneGlobals.ShadowsInfo

2022-06-09 08:30 UTC, pandamicro commented on cocos/3d/lights/directional-light-component.ts
> +            this._light.csmValueDirty = true;
What is CSM value ? Please choose a better meaningful name

2022-06-09 08:30 UTC, pandamicro commented on cocos/core/renderer/scene/directional-light.ts
> +    get csmValueDirty () {
API documentation

2022-06-09 08:30 UTC, pandamicro commented on cocos/core/renderer/scene/shadows.ts
> +export const VisibleLevel = Enum({
ShadowMode is better, in CSM, user could specify level for different environment to have better performance

2022-06-09 08:30 UTC, pandamicro commented on cocos/core/renderer/scene/shadows.ts
> +    none: CSMLevel.level_1,
all enum key should be upper cased: NONE

2022-06-09 08:30 UTC, pandamicro commented on cocos/core/renderer/scene/shadows.ts
> +    csm: CSMLevel.level_4,
CSM

2022-06-09 08:30 UTC, pandamicro commented on cocos/core/root.ts
> +import { SERVER_MODE } from './default-constants';
where does this changes come from, shouldn't be modified

2022-06-09 08:30 UTC, pandamicro commented on editor/assets/chunks/cc-shadow.chunk
> +#pragma define NUMCASCADES 4
Shouldn't be fixed to 4, must consider how user setup different csm level

2022-06-09 08:30 UTC, pandamicro commented on native/cocos/renderer/pipeline/Define.h
> +    static constexpr uint CSM_LEVEL_COUNT = 4;
Again, shouldn't be fixed

2022-06-09 08:35 UTC, troublemaker52025 commented on cocos/core/renderer/scene/directional-light.ts
> +    get csmValueDirty () {
* https://github.com/cocos/3d-tasks/issues/12510

2022-06-09 08:38 UTC, troublemaker52025 commented on cocos/core/root.ts
> +import { SERVER_MODE } from './default-constants';
come from web CI error, No one has handled this error report at present

2022-06-09 08:40 UTC, troublemaker52025 commented on editor/assets/chunks/cc-shadow.chunk
> +#pragma define NUMCASCADES 4
Level 4 is the maximum number of levels，user cant change this define

2022-06-09 09:02 UTC, troublemaker52025 commented on cocos/core/renderer/scene/shadows.ts
> +export const VisibleLevel = Enum({
enable csm level 1 or level 4

2022-06-09 11:28 UTC, pandamicro approved these changes

2022-06-09 13:29 UTC, pandamicro approved these changes

2022-06-09 13:30 UTC, pandamicro commented
@cocos-robot run test cases

2022-06-10 06:08 UTC, merged