update player_control for fireball/issues/4237
cocos/cocos-engine pull request #1153
Opened 2016-09-26 08:20 UTC by knoxHuang

Re: cocos-creator/fireball#4237

Changes proposed in this pull request:
 *  更新玩家输入控制代码

@cocos-creator/engine-admins

2016-09-26 08:41 UTC, pandamicro commented on cocos2d/core/event-manager/CCSystemEvent.js
> +        cc.eventManager.addListener(accelerationListener, 1);
不要在 ctor 中直接注册，在用户第一次调用 on 的时候才注册，有可能很多用户完全不需要 keyBoard 或者 acceleration 事件。

另外，把所有的 keyBoard 都改成 keyboard，这是一个单词

2016-09-26 08:42 UTC, pandamicro commented on cocos2d/core/event-manager/CCSystemEvent.js
> +cc.SystemEvent = module.exports = SystemEvent;
SystemEvent 类不需要暴露到 cc 下，只需要暴露它的对象 `cc.systemEvent`

2016-09-26 08:42 UTC, pandamicro requested changes

2016-09-26 08:44 UTC, knoxHuang commented on cocos2d/core/event-manager/CCSystemEvent.js
> +cc.SystemEvent = module.exports = SystemEvent;
这要把，不然你 EventType 要放在哪里？

2016-09-27 01:53 UTC, pandamicro commented on cocos2d/core/event-manager/CCSystemEvent.js
> +            cc.eventManager.addListener(accelerationListener, 1);
将 keyboard 和 acceleration 区分开，不要在一起判断

2016-09-27 03:24 UTC, pandamicro commented on cocos2d/core/event-manager/CCSystemEvent.js
> +            if (!hasKeyDownEventListener && !hasKeyDownEventListener) {
!hasKeyDownEventListener && !hasKeyUpEventListener

2016-09-27 04:06 UTC, pandamicro approved these changes

2016-09-27 09:14 UTC, jareguo approved these changes

2016-09-27 09:14 UTC, merged