V3.6.0 allow multiple custom scripts exist in project with one same className
cocos/cocos-engine pull request #11763
Opened 2022-06-29 14:09 UTC by arsen2010

Re: #https://github.com/cocos/3d-tasks/issues/11736

### Changelog

* allow multiple custom scripts exist in project with one same className

-------

### Continuous Integration

This pull request:

* [ ] needs automatic test cases check.

  > Manual trigger with `@cocos-robot run test cases` afterward.

-------

### Compatibility Check

This pull request:

* [ ] changes public API, and have ensured backward compatibility with [deprecated features](https://github.com/cocos/cocos-engine/blob/v3.5.0/docs/contribution/deprecated-features.md).
* [ ] affects platform compatibility, e.g. system version, browser version, platform sdk version, platform toolchain, language version, hardware compatibility etc.
* [ ] affects file structure of the build package or build configuration which requires user project upgrade.
* [ ] **introduces breaking changes**, please list all changes, affected features and the scope of violation.

2022-07-04 09:31 UTC, PPpro commented
`_getClassById`  `getClassById` should be two different interface.

`_getClassById` is a deprecated interface and for now we should not remove it 
and it's ok to provide a new interface `getClassById`

the same with `getClassId` and `_getClassId`

2022-07-04 12:02 UTC, PPpro requested changes

2022-07-04 12:02 UTC, PPpro commented on cocos/core/utils/js-typed.ts
> +function setup (tag: string, table: Record<string | number, any>, allowExist) {
```suggestion
function setup (tag: string, table: Record<string | number, any>, allowExist: boolean) {
```

2022-07-04 12:07 UTC, PPpro approved these changes

2022-07-05 05:44 UTC, shrinktofit approved these changes

2022-07-05 06:12 UTC, jareguo approved these changes

2022-07-05 07:19 UTC, merged