only reset node height in resize_height
cocos/cocos-engine pull request #1183
Opened 2016-10-10 10:16 UTC by zilongshanren

Re: https://github.com/cocos-creator/fireball/issues/4273

Changes proposed in this pull request:
 * 

@cocos-creator/engine-admins

2016-10-10 10:18 UTC, jareguo requested changes

2016-10-10 10:18 UTC, jareguo commented on cocos2d/core/components/CCLabel.js
> +            if(this.overflow === Overflow.RESIZE_HEIGHT) {
加个 else if 吧

2016-10-10 10:18 UTC, jareguo commented on cocos2d/core/components/CCLabel.js
> +                var newSize = this._sgNode.getContentSize();
这两个用 getWidth() getHeight() 更直接吧

2016-10-11 03:16 UTC, zilongshanren commented on cocos2d/core/components/CCLabel.js
> +                var newSize = this._sgNode.getContentSize();
sgNode 有 getWidth()这个 API 么。。。jsb 里面

2016-10-11 03:16 UTC, zilongshanren commented on cocos2d/core/components/CCLabel.js
> +            if(this.overflow === Overflow.RESIZE_HEIGHT) {
好的

2016-10-11 03:16 UTC, jareguo commented on cocos2d/core/components/CCLabel.js
> +                var newSize = this._sgNode.getContentSize();
不可能没有吧…… 不然怎么获取宽度？

2016-10-11 03:18 UTC, jareguo commented on cocos2d/core/components/CCLabel.js
> +                var newSize = this._sgNode.getContentSize();
好像是没有，不然就 `.width` 吧

2016-10-11 03:23 UTC, zilongshanren commented on cocos2d/core/components/CCLabel.js
> +                var newSize = this._sgNode.getContentSize();
这个修改差别不大呀，调用 getConentSize 更重要的是为了同步 this.node._contentSize
不会导致 this.node.setContentSize 的时候重复设置 node 的 size，而这个在 jsb 那层就会有 bug。

2016-10-11 03:24 UTC, zilongshanren commented on cocos2d/core/components/CCLabel.js
> +                var newSize = this._sgNode.getContentSize();
这里必须调用 getContentSize，这应该是一个 trick，后面再想更好的方法吧。现在主要的问题还是 native 和 web 的 label 实现方法差别有点大，需要统一。

2016-10-11 03:54 UTC, merged