add callbacksInvoker missing api
cocos/cocos-engine pull request #12131
Opened 2022-07-21 10:03 UTC by timlyeee

2022-07-21 15:22 UTC, pandamicro requested changes
This is not how it should be fixed, please find out which end class are missing  the APIs and try to fix it in end class level. CallbacksInvoker doesn't have once and targetOff, the implementations are also meaningless.
Be more rigorous

2022-07-22 04:05 UTC, pandamicro approved these changes

2022-07-22 04:43 UTC, dumganhar approved these changes

2022-07-22 04:49 UTC, minggo approved these changes

2022-07-22 05:31 UTC, merged