Auto release dependent resources in cc.loader.release
cocos/cocos-engine pull request #1231
Opened 2016-10-23 02:19 UTC by pandamicro

Re: cocos-creator/fireball#4498

Changes proposed in this pull request:
 * Auto release dependent resources in cc.loader.release

> Makes sure these boxes are checked before submitting your PR - thank you!
>
- [x] If your pull request has gone "stale", you should **rebase** your work on top of the latest version of the upstream branch.
- [x] If your commit history is full of small, unimportant commits (such as "fix pep8" or "update tests"), **squash** your commits down to a few, or one, discreet changesets before submitting a pull request.
- To official teams:
  - [x] Check that your javascript is following our [style guide](https://github.com/cocos-creator/fireball/blob/dev/.github/CONTRIBUTING.md) and end files with a newline
  - [x] Document new code with comments in source code based on [API Docs](https://github.com/cocos-creator/fireball#api-docs)

@cocos-creator/engine-admins

2016-10-23 03:32 UTC, jareguo commented on cocos2d/core/load-pipeline/CCLoader.js
> +        var assets = AutoReleaseUtils.getDependsRecursively(id);
这里可是连带依赖项都一起销毁了啊！这样没办法兼容用户已有项目吧？

2016-10-23 06:46 UTC, pandamicro commented on cocos2d/core/load-pipeline/CCLoader.js
> +        var assets = AutoReleaseUtils.getDependsRecursively(id);
不然清不干净，你之前认为是要怎么 release ？

2016-10-23 08:13 UTC, jareguo commented on cocos2d/core/load-pipeline/CCLoader.js
> +        var assets = AutoReleaseUtils.getDependsRecursively(id);
之前我认为是只释放资源不带依赖的

2016-10-23 12:21 UTC, pandamicro commented on cocos2d/core/load-pipeline/CCLoader.js
> +        var assets = AutoReleaseUtils.getDependsRecursively(id);
在原生中，如果只释放 Texture2D，但是不释放 SpriteFrame 的话，也没用，贴图还是释放不了

2016-10-23 13:39 UTC, jareguo commented on cocos2d/core/load-pipeline/CCLoader.js
> +        var assets = AutoReleaseUtils.getDependsRecursively(id);
原生这种行为我觉得没问题啊？

2016-10-25 03:28 UTC, jareguo requested changes

2016-10-25 03:28 UTC, jareguo commented on cocos2d/core/load-pipeline/CCLoader.js
> +     * @param {String} id
这个 id 是 uuid 吗？

2016-10-25 03:28 UTC, jareguo commented on cocos2d/core/load-pipeline/CCLoader.js
> +     * 从 v1.3 开始，这个方法不仅会从 loader 中删除资源的缓存引用，还会清理它的资源内容。
破坏兼容性不太好吧？

2016-10-25 03:28 UTC, jareguo commented on cocos2d/core/platform/js.js
> +    Array.isArray = function(arg) {
这段代码放到 engine/polyfill/array.js 吧？

2016-10-25 03:28 UTC, jareguo commented on cocos2d/core/platform/js.js
> +    Array.isArray = function(arg) {
然后用户就还是用 Array.isArray 就好了

2016-10-25 03:41 UTC, zilongshanren commented on cocos2d/core/load-pipeline/loading-items.js
> -            var dep = _queueDeps[item.queueId];
item.queueId 直接变成了 this._id 感觉逻辑改变了？

2016-10-25 16:31 UTC, jareguo commented on cocos2d/core/load-pipeline/CCLoader.js
> +     * @param {String} id
如果是的话，那用户不是很难用？

2016-10-25 17:11 UTC, pandamicro commented on cocos2d/core/load-pipeline/loading-items.js
> -            var dep = _queueDeps[item.queueId];
是一样的，对 item 来说是 queueId，对于 queue 自身来说是 _id

2016-10-25 17:12 UTC, pandamicro commented on cocos2d/core/platform/js.js
> +    Array.isArray = function(arg) {
ok

2016-10-26 08:50 UTC, pandamicro commented on cocos2d/core/load-pipeline/CCLoader.js
> +     * @param {String} id
兼容 res url  和 uuid

2016-10-26 09:02 UTC, jareguo commented on cocos2d/core/load-pipeline/CCLoader.js
> +     * @param {String} id
加个 example 吧？不然真看不出这个 API 做什么用的。

2016-10-26 09:06 UTC, jareguo commented on cocos2d/core/load-pipeline/CCLoader.js
> +     * var deps = cc.loader.getDependsRecursively('prefabs/sample');
这个 url 是……………… texture 的？

2016-10-26 09:52 UTC, pandamicro commented
DONE

2016-10-26 09:54 UTC, jareguo approved these changes

2016-10-26 09:54 UTC, merged