add pageSize for CCPageView
cocos/cocos-engine pull request #1254
Opened 2016-10-31 11:18 UTC by knoxHuang

Re: cocos-creator/fireball#

Changes proposed in this pull request:
 * 

> Makes sure these boxes are checked before submitting your PR - thank you!
>
- [ ] If your pull request has gone "stale", you should **rebase** your work on top of the latest version of the upstream branch.
- [ ] If your commit history is full of small, unimportant commits (such as "fix pep8" or "update tests"), **squash** your commits down to a few, or one, discreet changesets before submitting a pull request.
- To official teams:
  - [ ] Check that your javascript is following our [style guide](https://github.com/cocos-creator/fireball/blob/dev/.github/CONTRIBUTING.md) and end files with a newline
  - [ ] Document new code with comments in source code based on [API Docs](https://github.com/cocos-creator/fireball#api-docs)

@cocos-creator/engine-admins

2016-10-31 12:11 UTC, jareguo requested changes

2016-10-31 12:11 UTC, jareguo commented on cocos2d/core/components/CCPageView.js
> +            notify: function() {
这个空方法去掉吧？

2016-10-31 12:11 UTC, jareguo commented on cocos2d/core/components/CCPageView.js
> +         * !#zh 单个页面
单个页面的什么……

2016-10-31 12:11 UTC, jareguo commented on cocos2d/core/components/CCPageView.js
> +         * @property {cc.size} pageSize
这个应该是 `{Size}` 才能正确解析吧？试一下~~

2016-11-03 06:05 UTC, zilongshanren commented on cocos2d/core/components/CCPageView.js
> +        //this.node.on('size-changed', this._updateAllPagesSize, this);
注释尽量去掉吧，留在代码里面是一种阅读负担。。

2016-11-03 07:36 UTC, nantas commented on cocos2d/core/components/CCPageView.js
> +            offset.x = idx * this.pageSize.width;
我昨天测试了一下，这样的算法只有在第一个页面的初始位置准确的出现在 PageView 中心时，后续计算才会正确，也就是需要用户将 Layout 的 padding 准确的设置为 (pageViewWidth - pageSize)/2，而且这样做就无法适配多种分辨率的屏幕了。

如果没有其他方法解决边界 bounce 的问题，就要换个思路来做了，在 updatePageView 的时候记录每一个 page 居中时需要的偏移量（绝对数值），然后直接移动到准确的位置。_isScrollable 计算时先判断滑动方向，然后取当前页和前一页/后一页的距离，再乘以 threshold。

这种算法和强制更新每个 page 的尺寸是两种不同的模式，可以用枚举区分开

2016-11-07 01:35 UTC, knoxHuang commented on cocos2d/core/components/CCPageView.js
> +            offset.x = idx * this.pageSize.width;
那这 2 种类型的枚举要叫做什么？

2016-11-17 06:50 UTC, jareguo commented on cocos2d/core/components/CCPageView.js
> +     * !#en Each page is uniform in size
is uniform??

2016-11-17 06:50 UTC, jareguo commented on cocos2d/core/components/CCPageView.js
> +        pageTurningVelocity: {
这个 API 叫 pageTurningThreshold 会不会好点？ pageTurningVelocity 感觉是用来设置翻页速度的

2016-11-17 06:51 UTC, knoxHuang commented on cocos2d/core/components/CCPageView.js
> +        pageTurningVelocity: {
@zilongshanren 子龙你觉得呢？

2016-11-17 06:53 UTC, jareguo commented on cocos2d/core/components/CCPageView.js
> +        UnifiedSize: UnifiedSize,
UnifiedSize 叫 UnifiedSizeMode 会不会好点？ @zilongshanren @pandamicro

2016-11-18 03:03 UTC, zilongshanren commented on cocos2d/core/components/CCPageView.js
> +     * !#en Each page is uniform in size
改成 each page is in unified size 吧？

2016-11-18 03:03 UTC, zilongshanren commented on cocos2d/core/components/CCPageView.js
> +     * !#en Each page size is free
Each page is in free size

2016-11-18 03:07 UTC, zilongshanren commented on cocos2d/core/components/CCPageView.js
> +         * !#en Each page size mode in the page view
Specify the size type of each page in PageView.

2016-11-18 03:10 UTC, zilongshanren commented on cocos2d/core/components/CCPageView.js
> +        pageTurningVelocity: {
改成 autoPageTurningVelocity 吧？ pageTurningVelocity 确实有点不好。

2016-11-18 03:11 UTC, knoxHuang commented on cocos2d/core/components/CCPageView.js
> +        pageTurningVelocity: {
还是修改为 autoPageTurningThreshold ？

2016-11-18 03:12 UTC, zilongshanren commented on cocos2d/core/components/CCPageView.js
> +        UnifiedSize: UnifiedSize,
@jareguo  直接叫 SizeMode 吧？ 里面包含 unified 和 freely

2016-11-18 03:13 UTC, zilongshanren commented on cocos2d/core/components/CCPageView.js
> +        UnifiedSize: UnifiedSize,
@jareguo  Layout 那边用的也是 SizeMode

2016-11-18 03:14 UTC, jareguo commented on cocos2d/core/components/CCPageView.js
> +        UnifiedSize: UnifiedSize,
不会理解错就行

2016-11-18 03:40 UTC, zilongshanren commented on cocos2d/core/components/CCPageView.js
> +        pageTurningVelocity: {
@knoxHuang  autoPageTurningThreshold 也行。

2016-11-18 09:26 UTC, knoxHuang commented
@zilongshanren  @jareguo 修改了，有空在看看

2016-11-18 09:28 UTC, zilongshanren commented on cocos2d/core/components/CCPageView.js
> +        UnifiedSize: UnifiedSize,
这里写的还是 UnifiedSize 啊？应该是 SizeMode 吧？

2016-11-18 09:28 UTC, zilongshanren commented on cocos2d/core/components/CCPageView.js
> +        if (this.sizeMode === UnifiedSize.Unified) {
这里的代码好像都要改？

2016-11-18 09:37 UTC, jareguo approved these changes

2016-11-18 09:40 UTC, zilongshanren commented
LGTM

2016-11-18 09:40 UTC, jareguo requested changes

2016-11-18 09:40 UTC, jareguo commented on cocos2d/core/components/CCPageView.js
> +                this._syncSizeMode();
sizeMode 改变时，应该同步更新 'size-changed' 注册的回调 _updateAllPagesSize，因为现在的注册和反注册都是以 sizeMode 的值为依据的。
除非改成不论 sizeMode 多少都统一注册，然后在回调中再去判断 sizeMode

2016-11-18 10:00 UTC, jareguo approved these changes

2016-11-18 10:00 UTC, merged