improve button cancel behavior
cocos/cocos-engine pull request #1264
Opened 2016-11-04 10:04 UTC by zilongshanren

Re: https://github.com/cocos-creator/fireball/issues/4618

Changes proposed in this pull request:
 * 修复 button cancel 事件的时候， transition 为 scale 的行为不正确的问题
 * button transition 为 scale 的时候，zoom back 的时候以 node 当前 scale 为基准

@cocos-creator/engine-admins

2016-11-05 17:20 UTC, pandamicro requested changes

2016-11-05 17:20 UTC, pandamicro commented on cocos2d/core/components/CCButton.js
> +        } else {
我觉得这部分逻辑应该在 _updateState 中，否则以后维护起来很奇怪

2016-11-07 03:18 UTC, zilongshanren commented on cocos2d/core/components/CCButton.js
> +        } else {
@pandamicro  恩，我把逻辑都重构一下。

2016-11-08 09:42 UTC, zilongshanren commented on cocos2d/core/components/CCButton.js
> -    onLoad: function () {
remove onLoad method, move the logic into __preload.

2016-11-09 07:41 UTC, pandamicro approved these changes

2016-11-09 07:41 UTC, pandamicro commented on cocos2d/core/components/CCButton.js
> +            this._updateScaleTransition(state);
一个提醒，不知道 _applyTransition 的调用频度和调用栈深度怎么样，如果正常情况下调用栈比较深的话，还是不建议过细得将内部逻辑包装到函数中，调用栈越深，JS 执行效率越低下。

总之做这种逻辑拆分的时候多评估一下，目标函数的调用频度，正常情况下的调用栈深度，内部逻辑是否性能热点等等。

2016-11-09 07:50 UTC, zilongshanren commented on cocos2d/core/components/CCButton.js
> +            this._updateScaleTransition(state);
@pandamicro  这个跟用户的操作相关，频率能高到哪去。。。你每秒最多点击 2 次？

2016-11-09 07:50 UTC, zilongshanren commented on cocos2d/core/components/CCButton.js
> +            this._updateScaleTransition(state);
@pandamicro  不要过早优化。。。 我更注重可读性。

2016-11-10 02:12 UTC, merged