Improve scrollview v2
cocos/cocos-engine pull request #1267
Opened 2016-11-07 08:40 UTC by zilongshanren

Re: cocos-creator/fireball#4593

Changes proposed in this pull request:
- 修复 scrollview 嵌套 scrollview 时，拖到上面的 scrollview 下面的 scrollview 也跟着一起滚动的问题
- 修复 scrollview 添加在 button 等侦听了 bubble 阶段事件的节点上面，事件会从 scrollview 穿透到这些节点上面的问题
- 修复了 getScrollOffset 方向错了的问题

@cocos-creator/engine-admins

2016-11-07 08:51 UTC, jareguo requested changes

2016-11-07 08:51 UTC, jareguo commented on cocos2d/core/event/event.js
> +    this._preventDefault = false;
DOM 事件里的标准应该是叫 `defaultPrevented` 吧？

2016-11-07 08:54 UTC, zilongshanren commented on cocos2d/core/event/event.js
> +    this._preventDefault = false;
@jareguo  不清楚，哪里可以查到？

2016-11-07 17:03 UTC, pandamicro approved these changes

2016-11-07 17:03 UTC, pandamicro commented on cocos2d/core/components/CCButton.js
> +            }
用 

```
if (event._preventDefault) {}
else {}
```

的形式更好阅读。

另外，别忘了在另一个 PR 中将 _zoomBack 逻辑合并到 updateState 中

2016-11-07 23:38 UTC, zilongshanren commented
@pandamicro  这个 PR 破坏了兼容性，我还是推荐合上一个 PR，这个 PR 要么放到1.4，要么放到 2.0.
1.x 的版本，我觉得还是最大化兼容性比较好。

2016-11-08 03:26 UTC, nantas commented
破坏兼容性是什么情况啊，到底这两种方案要用哪个？就算是合到1.4也不能破坏兼容性啊

2016-11-08 03:32 UTC, zilongshanren commented
@nantas  这个我关了，破坏了兼容性。 等 @pandamicro 搞一个完美的不破坏兼容性的方法吧，如果没有找到，还是使用我之前的方案。

2016-11-08 03:32 UTC, closed without merging

2016-11-08 03:34 UTC, jareguo commented
这个 PR 先存档吧，虽然破坏了兼容性，但其实是正确的技术路线…… 这个 PR 解决了上个 PR 相同的问题，同时扩展起来会方便很多。有机会还是要想办法升级一下。

2016-11-08 03:46 UTC, pandamicro commented
完善了一下子龙的 PR，看大家怎么看了，这个设计是在 capture 阶段，记录 prevent default 的节点，_preventDefault 可以跳过 target 的事件派发，然后在 bubbling 阶段，从之前做了 prevent default 的节点开始向上冒泡。

其实是把捕获到冒泡的整个过程，切了一下