loader 无法识别内部资源，导致资源重复加载的问题
cocos/cocos-engine pull request #1278
Opened 2016-11-11 03:10 UTC by VisualSJ

问题表现：
使用 cc.loader.loadRes 加载一遍资源，在用 cc.loader.load 加载一遍资源，因为资源路径不同，loadRes 会使用 uuid 缓存已经加载的资源，而直接调用 load 接口的会被识别为外部资源，从而重新创建 cache。

修改主要就是在 CCAssetLibrary 中增加一个使用路径查找内部资源的方法，而后在 load 流程前，先匹配是否是内部资源，如果是，则替换为 uuid 模式。

缺点：
加载资源速度变慢，每个资源在加载的时候都会去 CCAssetLibrary 循环一次。

是否可以考虑在 CCAssetLibrary 中内置一个 urlToUuid 的 cache，这样就不用每次都去循环，只需要一次匹配判断。

@pandamicro @jareguo

2016-11-11 03:34 UTC, jareguo commented on cocos2d/core/platform/CCAssetLibrary.js
> +        if (_urlToUuid[url]) {
先存个变量吧，不然如果有还要重复查询

2016-11-11 03:34 UTC, jareguo commented on cocos2d/core/platform/CCAssetLibrary.js
> +                    _urlToUuid[finalUrl] = uuid;
这个字典为什么不用到时才初始化？感觉应该只有声音会用到，全部资源都缓存感觉有点浪费内存

2016-11-11 03:40 UTC, VisualSJ commented on cocos2d/core/platform/CCAssetLibrary.js
> +                    _urlToUuid[finalUrl] = uuid;
我觉得这个是 loader 的bug，按理来说 cc.loader.load 和 cc.loader.loadRes 加载的文件最终路径只要一样，就只能加载一次。所以所有文件都需要有个索引。

再就是，即使只是声音，只要在 cc.laoder.load 内加上检查的话，每个资源都会反复去循环，所以不如这边缓存份，也只是多了几字节的开销，相比每次加载新资源都去循环我觉得这个更合理。。。

2016-11-15 02:06 UTC, pandamicro requested changes

2016-11-15 02:06 UTC, pandamicro commented on cocos2d/core/platform/CCAssetLibrary.js
> +                    _urlToUuid[finalUrl] = uuid;
本来设计上来说，Loader.load 不应该跟 AssetLibrary 有关系，这是一个原始的加载，loadRes 才会去查找索引，这个设计我觉得是正常的。

现在造成问题的主要原因是 Loader 的 cache 是按照 uuid 保存而不是按照 raw url，如果用 raw url 保存，应该就可以解决这个问题了。之前用 uuid 保存是为了方便，如果要改成 raw url 作为 cache 的 key，那么每个 uuid 都还需要请求 AssetLibrary 获取到 url 之后，才能够判断是否存在缓存

2016-11-15 02:15 UTC, VisualSJ commented
https://github.com/cocos-creator/engine/issues/1284

2016-11-15 02:18 UTC, closed without merging