Lightmap UI
cocos/cocos-engine pull request #13181
Opened 2022-10-28 08:56 UTC by AFeiYA

Re: #

### Changelog

* Add generate lightmap uv UI.

-------

### Continuous Integration

This pull request:

* [ ] needs automatic test cases check.
  > Manual trigger with `@cocos-robot run test cases` afterward.
* [ ] does not change any runtime related code or build configuration
  > If any reviewer thinks the CI checks are needed, please uncheck this option, then close and reopen the issue.

-------

### Compatibility Check

This pull request:

* [ ] changes public API, and have ensured backward compatibility with [deprecated features](https://github.com/cocos/cocos-engine/blob/v3.5.0/docs/contribution/deprecated-features.md).
* [ ] affects platform compatibility, e.g. system version, browser version, platform sdk version, platform toolchain, language version, hardware compatibility etc.
* [ ] affects file structure of the build package or build configuration which requires user project upgrade.
* [ ] **introduces breaking changes**, please list all changes, affected features and the scope of violation.

2022-11-07 08:33 UTC, arsen2010 requested changes
develop 有一个比较大的 PR 合并了，这个 PR 需要重新拉取下 develop 后调整
无效和只读，改用了这个模式
![企业微信截图_16678099372487](https://user-images.githubusercontent.com/13517177/200262952-ec5c2c92-d051-4563-b235-038561b7fa60.png)

2022-11-07 09:45 UTC, arsen2010 approved these changes

2022-11-14 02:36 UTC, shrinktofit approved these changes

2022-11-14 09:55 UTC, jk20012001 approved these changes

2022-11-14 09:56 UTC, merged