Support mesh of DragonBones in WebGL.
cocos/cocos-engine pull request #1343
Opened 2016-12-07 09:12 UTC by natural-law

Re: cocos-creator/fireball#4416

Changes proposed in this pull request:
 * Support mesh of DragonBones in WebGL.

@cocos-creator/engine-admins

2016-12-07 10:13 UTC, pandamicro requested changes

2016-12-07 10:13 UTC, pandamicro commented on cocos2d/core/renderer/RendererWebGL.js
> +            // TODO increase index data of custom cmd ??
用跟下面一样的逻辑处理就好

2016-12-07 10:13 UTC, pandamicro commented on cocos2d/core/sprites/CCScale9Sprite.js
> +        var l, r, b, t;
l b 可以初始化为 Infinity，b t 初始化为 -Infinity，下面就不需要判断 undefined 了

2016-12-07 10:13 UTC, pandamicro commented on cocos2d/core/sprites/CCScale9Sprite.js
> +    setMeshPolygonInfo: function (polygonInfo) {
这里也需要设置 renderingType 吧？

2016-12-07 10:13 UTC, pandamicro commented on extensions/dragonbones/CCFactory.js
> +                        cc.warn('Canvas is not support mesh slot!');
Canvas doesn't support mesh slot

2016-12-07 10:13 UTC, pandamicro commented on cocos2d/core/sprites/CCScale9Sprite.js
> +         * polygonInfo in format:
需要确认下这个格式是否兼容 Spine 和 TextureCache 的 mesh

2016-12-07 10:19 UTC, natural-law commented on cocos2d/core/renderer/RendererWebGL.js
> +            // TODO increase index data of custom cmd ??
下面的逻辑使用了 cmd，而这个函数没有 cmd 所以没法做相同处理。

2016-12-07 10:31 UTC, natural-law commented on cocos2d/core/sprites/CCScale9Sprite.js
> +         * polygonInfo in format:
这个格式我是照着 native 的 PolygonInfo 这个类的结构来设计的。

Spine 有自己的 WebGL Render Cmd。要改成使用 Scale9Sprite 需要重构 Spine 的实现吧。
TextureCache 的 mesh 是什么样的呢？有示例资源吗？

2016-12-07 10:35 UTC, natural-law commented on cocos2d/core/sprites/CCScale9Sprite.js
> +    setMeshPolygonInfo: function (polygonInfo) {
现在 _meshPolygonInfo 和 _renderingType 没有耦合在一起。要想使用 _meshPolygonInfo 需要手动设置 _renderingType 为 Mesh。
如果要设置也没什么原则性的问题。

2016-12-08 02:14 UTC, pandamicro commented on cocos2d/core/sprites/CCScale9Sprite.js
> +    setMeshPolygonInfo: function (polygonInfo) {
这里做个判断吧，如果不是 mesh rendering type，就不允许设置

2016-12-08 02:20 UTC, natural-law commented on cocos2d/core/sprites/CCScale9Sprite.js
> +    setMeshPolygonInfo: function (polygonInfo) {
已经修改为设置 PolygonInfo 的时候，自动修改为 Mesh 类型。

2016-12-08 02:21 UTC, pandamicro approved these changes

2016-12-08 02:28 UTC, jareguo commented on extensions/dragonbones/CCFactory.js
> +        slot._meshDisplay = new cc.Scale9Sprite();
为什么 rawDisplay 和 meshDisplay 不合并成一个字段？

2016-12-09 01:42 UTC, merged