2d math
cocos/cocos-engine pull request #1385
Opened 2016-12-22 02:17 UTC by dabingnn

Re: cocos-creator/fireball#

Changes proposed in this pull request:
 * DO NOT MERGE IT, given two issues need to be fixed: move property 'x/y/z/w' to prototype(it is much more fast), and fix serialize issue after merge it @jareguo .
 * for issue cocos-creator/fireball#4950
 * for issue cocos-creator/fireball#4951
> Makes sure these boxes are checked before submitting your PR - thank you!
>
- [X] If your pull request has gone "stale", you should **rebase** your work on top of the latest version of the upstream branch.
- [X] If your commit history is full of small, unimportant commits (such as "fix pep8" or "update tests"), **squash** your commits down to a few, or one, discreet changesets before submitting a pull request.
- To official teams:
  - [X] Check that your javascript is following our [style guide](https://github.com/cocos-creator/fireball/blob/dev/.github/CONTRIBUTING.md) and end files with a newline
  - [X] Document new code with comments in source code based on [API Docs](https://github.com/cocos-creator/fireball#api-docs)
  - [X] Make sure any log information in `cc.log` , `cc.error`, `cc.warn` or `cc.assert` has been moved into `DebugInfos.js` with an ID

@cocos-creator/engine-admins

2016-12-22 02:31 UTC, jareguo commented
麻烦移除 kazmath 中相同的 Matrix3/4, Vec3/4, Quaternion, cc.math
替换成新的 value-types 实现
并且对原来的变量做一个 deprecated 警告

2016-12-22 02:31 UTC, jareguo requested changes

2016-12-22 02:31 UTC, jareguo commented on cocos2d/core/value-types/CCVec2v2.js
> +cc.Vec2v2 = module.exports = Vec2;
这个 Vec2v2好像没有必要加进来吧？Vec2本身也是支持链式调用的

2016-12-22 02:31 UTC, jareguo commented on cocos2d/core/value-types/CCColorF.js
> +var ColorF = function () {
麻烦补充下 API 文档

2016-12-22 02:31 UTC, jareguo commented on cocos2d/core/value-types/CCMat3.js
> +var Mat3 = function () {
麻烦补充下 API 文档

2016-12-22 02:31 UTC, jareguo commented on cocos2d/core/value-types/CCMath.js
> +cc.math = math;
cc.math 已经有了吧，在 kazmath 里

2016-12-22 06:06 UTC, pandamicro commented on cocos2d/core/value-types/CCMat3.js
> +CCClass.fastDefine('cc.Mat3', Mat3, {m:[1,0,0,0,1,0,0,0,1]});
设置 m 属性是什么意思？其他地方没有声明啊。如果是要设置 data 的默认值，@jareguo 这样设置 default 应该会把 Float32Array 洗成普通 array 把。

2016-12-22 06:06 UTC, pandamicro commented on cocos2d/core/value-types/CCMat4.js
> +CCClass.fastDefine('cc.Mat4', Mat4, {m:[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]});
同上，不理解这个 m 属性是什么意思

2016-12-22 06:24 UTC, jareguo commented on cocos2d/core/value-types/CCMat3.js
> +CCClass.fastDefine('cc.Mat3', Mat3, {m:[1,0,0,0,1,0,0,0,1]});
其实这里没用到…… 因为序列化和反序列化都是自己处理的

2016-12-22 06:29 UTC, pandamicro commented on cocos2d/core/value-types/CCMat3.js
> +CCClass.fastDefine('cc.Mat3', Mat3, {m:[1,0,0,0,1,0,0,0,1]});
那不应在这里调用 fastDefine

2016-12-22 06:33 UTC, jareguo commented on cocos2d/core/value-types/CCMat3.js
> +CCClass.fastDefine('cc.Mat3', Mat3, {m:[1,0,0,0,1,0,0,0,1]});
m 没有用到，fastDefine 有用到

2016-12-23 07:41 UTC, jareguo requested changes

2016-12-23 07:41 UTC, jareguo commented on cocos2d/core/value-types/CCVec3.js
> +
建议统一用 defineProperties，包体会少点
例如这里
```
Object.defineProperties(Vec3.prototype, {
    x: {
        get: function () {
            return this.data[0];
        },
        set: function (value) {
            this.data[0] = value;
        }
    },
    y: {
        get: function () {
            return this.data[1];
        },
        set: function (value) {
            this.data[1] = value;
        }
    },
    z: {
        get: function () {
            return this.data[2];
        },
        set: function (value) {
            this.data[2] = value;
        }
    }
});
```

2016-12-23 08:13 UTC, dabingnn commented
这个pull request只是为了把3D需要的数学库内容导入到引擎中
> 麻烦移除 kazmath 中相同的 Matrix3/4, Vec3/4, Quaternion, cc.math
kazmath这套数学库在webGL模式下的使用遍布整个引擎，这一阶段无法做到兼容，只能抽单独人力去处理

> 关于API部分
这部分的代码API到最后还需要调整到和cocos代码风格兼容的习惯，目前未做调整的原因在于改动3D渲染器部分工作量巨大，只能等3D能跑起来再重构。现阶段加上类级别的API还可以，函数级别的API没有必要加入。

2016-12-23 08:13 UTC, closed without merging

2016-12-23 08:21 UTC, jareguo commented
>> 麻烦移除 kazmath 中相同的 Matrix3/4, Vec3/4, Quaternion, cc.math
>
> kazmath这套数学库在webGL模式下的使用遍布整个引擎，这一阶段无法做到兼容，只能抽单独人力去处理

现在 2d 已经有用户层面的数学库，还有渲染层的 kazmath 了。如果要再加上 3D 的又不合并，引擎就越来越杂了…… 既然没有人力的话，就合并到 3D 分支上就好了。以后 3D 要合到 2D 版本再说