add labelatlas support
cocos/cocos-engine pull request #1392
Opened 2016-12-23 09:44 UTC by zilongshanren

Re: https://github.com/cocos-creator/fireball/issues/4606

Changes proposed in this pull request:
 * 
@cocos-creator/engine-admins

2016-12-23 10:24 UTC, jareguo requested changes

2016-12-23 10:24 UTC, jareguo commented on cocos2d/core/assets/CCLabelAtlas.js
> + * @extends Asset
文档写错了

2016-12-23 10:25 UTC, jareguo requested changes

2016-12-23 10:25 UTC, jareguo commented on cocos2d/core/assets/CCLabelAtlas.js
> +var LabelAtlas = cc.Class({
LabelAtlas 实际上是通过 BitmapFont 进行渲染的是吗？那应该继承自 BitmapFont 才对吧？也就是说要传入 BMFont 的地方，都允许传入一个 LabelAtlas

2016-12-23 10:28 UTC, jareguo commented on cocos2d/core/components/CCLabel.js
> +                    if ((this.font instanceof cc.BitmapFont) || (this.font instanceof cc.LabelAtlas)) {
如果继承关系修改后，这里就不用增加这些判断了

2016-12-23 10:28 UTC, zilongshanren commented on cocos2d/core/assets/CCLabelAtlas.js
> +var LabelAtlas = cc.Class({
@jareguo  继承可能不太好，目前的实现有些取巧。后面可能会修改 LabelAtlas 的 asset 定义以及底层的渲染实现。

2016-12-23 10:29 UTC, zilongshanren commented on cocos2d/core/components/CCLabel.js
> +        if (this.font instanceof cc.BitmapFont) {
而且这里，只针对 cc.BitmapFont 生效，如果改成继承，这里会出错。

2016-12-23 10:29 UTC, jareguo commented on cocos2d/core/assets/CCLabelAtlas.js
> +var LabelAtlas = cc.Class({
取巧不好吗？难道你要维护两套渲染机制？

2016-12-23 10:29 UTC, zilongshanren commented on cocos2d/core/components/CCLabel.js
> +                    if ((this.font instanceof cc.BitmapFont) || (this.font instanceof cc.LabelAtlas)) {
@jareguo 下面有些判断是只针对 cc.BitmapFont 的，如果改成继承，有些逻辑就也对 cc.LabelAtlas 生效了。。你还是要再判断。。

2016-12-23 10:30 UTC, zilongshanren commented on cocos2d/core/assets/CCLabelAtlas.js
> +var LabelAtlas = cc.Class({
@jareguo 我当然只想维护一套渲染，问题是后面的逻辑不允许继承，继承 = evil...

2016-12-23 10:31 UTC, zilongshanren commented on cocos2d/core/components/CCLabel.js
> +        if (this.font instanceof cc.BitmapFont) {
@jareguo  这里有一些只针对 cc.BitmapFont 生效的逻辑。

2016-12-23 10:31 UTC, jareguo commented on cocos2d/core/components/CCLabel.js
> +        if (this.font instanceof cc.BitmapFont) {
为什么这里只针对 cc.BitmapFont 生效，艺术数字不也有 fontSize？

2016-12-23 10:32 UTC, zilongshanren commented on cocos2d/core/components/CCLabel.js
> +        if (this.font instanceof cc.BitmapFont) {
@jareguo  艺术数字没有 fontSize，只有一个 fake font size。而且 inspector 显示是 bitmapOriginalFontSize

2016-12-23 10:33 UTC, zilongshanren commented on cocos2d/core/components/CCLabel.js
> +        if (this.font instanceof cc.BitmapFont) {
@jareguo  这里继承除了省一点代码，没有任何好处。。。

2016-12-23 10:34 UTC, jareguo commented on cocos2d/core/components/CCLabel.js
> +                    if ((this.font instanceof cc.BitmapFont) || (this.font instanceof cc.LabelAtlas)) {
也只有 _bmFontOriginalSize 的两处是只针对 cc.BitmapFont 的，这部分逻辑共享给 LabelAtlas 也好啊

2016-12-23 10:35 UTC, zilongshanren commented on cocos2d/core/components/CCLabel.js
> +                    if ((this.font instanceof cc.BitmapFont) || (this.font instanceof cc.LabelAtlas)) {
@jareguo  不能共享给 LabelAtlas， 因为 LabelAtlas 不需要显示 一个 BMF ontOriginalSize

2016-12-23 10:37 UTC, jareguo commented on cocos2d/core/assets/CCLabelAtlas.js
> +var LabelAtlas = cc.Class({
哪里不允许？就事论事

2016-12-23 10:37 UTC, jareguo commented on cocos2d/core/components/CCLabel.js
> +        if (this.font instanceof cc.BitmapFont) {
我从你的代码，还有资源的 import 流程，还有渲染流程来看，没看出为什么艺术数字没有 fontSize。
至于 inspector 显示的名字，很容易切换

2016-12-23 13:19 UTC, zilongshanren commented
@jareguo  done

2016-12-24 14:12 UTC, jareguo approved these changes

2016-12-26 02:20 UTC, merged