[WIP] 重新实现组件生命周期调用，支持脚本优先级
cocos/cocos-engine pull request #1523
Opened 2017-03-01 02:40 UTC by jareguo

Re: cocos-creator/fireball#2691

Changes proposed in this pull request:
 * 重新实现组件生命周期调用，支持脚本优先级

@cocos-creator/engine-admins

2017-03-01 02:43 UTC, jareguo commented on cocos2d/core/component-scheduler.js
> +var LifeCycleInvoker = cc.Class({
生命周期调用类，负责维护调用队列

2017-03-01 02:44 UTC, jareguo commented on cocos2d/core/component-scheduler.js
> +    extends: LifeCycleInvoker,
一次性使用的调用队列，调用时才排优先级

2017-03-01 02:45 UTC, jareguo commented on cocos2d/core/component-scheduler.js
> +    extends: LifeCycleInvoker,
重复使用的调用队列，使用（二分法）插入排序

2017-03-01 02:46 UTC, jareguo commented on cocos2d/core/component-scheduler.js
> +function ActivatingContext (node, active, preload, onLoad, onEnable) {
激活队列的栈帧信息，每一次激活都会入栈

2017-03-01 02:48 UTC, jareguo commented on cocos2d/core/component-scheduler.js
> +        var stack = this._activatingStack;
激活和反激活操作是有可能递归进行的，因为用户脚本有可能在 onLoad 过程中激活或反激活其它节点甚至自身节点。
所以这里利用栈来保证递归调用的子激活结果不会被之前的父激活队列覆盖。

2017-03-01 02:49 UTC, jareguo commented on cocos2d/core/component-scheduler.js
> +        var stack = this._activatingStack;
之前的实现因为没有激活队列，所以用一些标志位勉强解决了这个问题，现在有了激活队列就需要对队列进行维护。

2017-03-03 02:09 UTC, jareguo commented on cocos2d/core/platform/CCObject.js
>      Activating: Activating,
使用这个标志位来标识节点是否正在激活或反激活。对象同节点而言，如果正在激活或者反激活时，进行了相反的撤销激活或者重新激活操作，都会报错。但是由于激活操作只是生成激活队列，所以不会调用用户代码，就不存在任何问题。只有反激活时会调用用户代码，反激活的过程中如果重新激活就会报错。这样对调用者来说能保证反激活操作都能成功，而且也能防止反激活 - 激活 - 反激活的死循环发生。

2017-03-08 02:35 UTC, pandamicro commented on cocos2d/core/CCNode.js
> +function _searchMaskInParent (node) {
如果要命名更准确，应该是 _searchMaskInParents，之前的意思是找到包含 mask 的 parent

2017-03-08 02:42 UTC, jareguo commented on cocos2d/core/CCNode.js
> +function _searchMaskInParent (node) {
这个 API 是参考 Unity 公开 API 改名的…… 它就是单数……

2017-03-08 04:05 UTC, pandamicro requested changes

2017-03-08 04:05 UTC, pandamicro commented on cocos2d/core/CCScene.js
> +                cc.error('Should deactivate ActionManager and EventManager by default');
不理解这里的 log 和条件的关系，没有 init 但是又 activeInHierarchy 这个状态是怎么产生的？

2017-03-08 04:05 UTC, pandamicro commented on cocos2d/core/component-scheduler.js
> +        this.compsNeg = new JsArray.MutableForwardIterator([]);
为啥要分三个？都是按照从小到大排序的话，没必要分开啊

2017-03-08 04:05 UTC, pandamicro commented on cocos2d/core/component-scheduler.js
> +        this._invoke = invokeFunc;
最好先检查 invokeFunc 是否有效，后面也没有对 _invoke 的调用做任何保护，所以至少在创建的时候验证一下

2017-03-08 04:05 UTC, pandamicro commented on cocos2d/core/component-scheduler.js
> +            comp._objFlags |= IsStartCalled;
为什么不把 comp._objFlags 放到 callStartInTryCatch 中，然后传递 callStartInTryCatch 给 OneOffInvoker，在 invoker 中做 iterator 操作。下面 update, lateUpdate 同理

2017-03-08 04:05 UTC, pandamicro commented on cocos2d/core/component-scheduler.js
> +        this._activatingStack.push(context);
在哪里管理 _activatingStack 的？貌似递归也是直接 push 进去，没有检查 stack 中存不存在，而且每次调用 pushActivatingContext 都会创建新的 context，并没有一个池子管理 node 到 context 的对应关系

2017-03-08 04:05 UTC, pandamicro commented on cocos2d/core/CCScene.js
> -            cc.eventManager.pauseTarget(this);
这段逻辑我没看到迁移到哪里了

2017-03-08 04:06 UTC, pandamicro commented on cocos2d/core/CCNode.js
> +function _searchMaskInParent (node) {
Unity API 也不一定都对啊，单数从英语来说是有问题的

2017-03-08 04:54 UTC, pandamicro requested changes

2017-03-08 04:54 UTC, pandamicro commented on cocos2d/core/component-scheduler.js
> +        this._neg = new Iterator([]);
为啥要分三个？都是按照从小到大排序的话，没必要分开啊

2017-03-08 04:54 UTC, pandamicro commented on cocos2d/core/component-scheduler.js
> +        this._invoke = invokeFunc;
最好先检查 invokeFunc 是否有效，后面也没有对 _invoke 的调用做任何保护，所以至少在创建的时候验证一下

2017-03-08 04:54 UTC, pandamicro commented on cocos2d/core/component-scheduler.js
> +    return useDt ? new Function('it', 'dt', body) : new Function('it', body);
为什么不放在 invoke 里面实现循环？

2017-03-08 04:54 UTC, pandamicro commented on cocos2d/core/component-scheduler.js
> +            cc.errorID(3816, node.name);
用 warnID 把，相对友好一些

2017-03-08 05:58 UTC, jareguo commented on cocos2d/core/CCNode.js
> +function _searchMaskInParent (node) {
parent 在这里应该是做定语，而不是做名词，所以应该不存在复数的用法。完整写法应该是是 search mask in parent nodes

2017-03-08 06:00 UTC, jareguo commented on cocos2d/core/CCScene.js
> -            cc.eventManager.pauseTarget(this);
因为继承了 CCNode，所以这段逻辑由 CCNode 的 _onBatchCreated 实现

2017-03-08 06:04 UTC, jareguo commented on cocos2d/core/CCScene.js
> +                cc.error('Should deactivate ActionManager and EventManager by default');
这个状态正常情况下不会有，是我重构时加的断言，我把它修改一下

2017-03-08 06:07 UTC, jareguo commented on cocos2d/core/component-scheduler.js
> +            comp._objFlags |= IsStartCalled;
好主意！

2017-03-08 06:08 UTC, jareguo commented on cocos2d/core/component-scheduler.js
> +        this._neg = new Iterator([]);
因为默认顺序（zero）是最常用的，所有脚本一般都是 zero，没必要参与排序。只有那些用户特殊指定了优先级的组件，才应该有排序的开销。

2017-03-08 06:09 UTC, jareguo commented on cocos2d/core/component-scheduler.js
> +        this._invoke = invokeFunc;
这几个类是私有的，只有这个文件里面能 new，所以应该不需要验证吧

2017-03-08 06:09 UTC, jareguo commented on cocos2d/core/component-scheduler.js
> +    return useDt ? new Function('it', 'dt', body) : new Function('it', body);
不懂？？

2017-03-08 06:10 UTC, jareguo commented on cocos2d/core/component-scheduler.js
> +            cc.errorID(3816, node.name);
这个操作会导致用户逻辑无法正常执行，组件也不能完全初始化，用户是必须修改的，所以用了报错。

2017-03-08 06:13 UTC, jareguo commented on cocos2d/core/component-scheduler.js
> +        this._activatingStack.push(context);
在 activateNode 中进行的 push/pop 操作。因为只有一个地方会进行 push 和 pop，所以不需要检查 stack 存不存在吧（私有变量）

> 每次调用 pushActivatingContext 都会创建新的 context，并没有一个池子管理 node 到 context 的对应关系

后面的提交有加入池子

2017-03-08 06:16 UTC, jareguo commented on cocos2d/core/component-scheduler.js
> +            cc.errorID(3816, node.name);
PS: 如果用户不通过节点激活操作，直接链式触发了 onEnable 和 onDisable 循环调用，是会进入死循环的，引擎不负责报错。Unity 也不处理这种情况。

2017-03-09 01:49 UTC, pandamicro commented on cocos2d/core/CCNode.js
> +function _searchMaskInParent (node) {
算了，私有函数名无所谓，开心就好

2017-03-09 01:51 UTC, pandamicro commented on cocos2d/core/component-scheduler.js
> +        this._invoke = invokeFunc;
那就添加一个一个单元测试来确保所有通过这个函数创建的可访问变量都存在 _invoke 函数吧

2017-03-09 01:54 UTC, jareguo commented on cocos2d/core/component-scheduler.js
> +        this._invoke = invokeFunc;
这个是构造函数，这个字段又是私有的，好像没办法单元测试？我加个断言吧

2017-03-09 02:07 UTC, pandamicro commented on cocos2d/core/component-scheduler.js
> +            cc.errorID(3816, node.name);
了解

2017-03-09 02:59 UTC, pandamicro commented on cocos2d/core/component-scheduler.js
> +            return new Function('it', body);
我的想法是这样

```
function createInvokeImpl (impl, useDt) {
    if (useDt) {
        return function (iterator) {
            var array = iterator.array;
            for (iterator.i = 0; iterator.i < array.length; ++iterator.i) {
                var comp = array[iterator.i];
                impl.call(comp);
            }
        };
    }
    else {
        return function (iterator, dt) {
            var array = iterator.array;
            for (iterator.i = 0; iterator.i < array.length; ++iterator.i) {
                var comp = array[iterator.i];
                impl.call(comp, dt);
            }
        };
    }
}
```

然后所有差异都应该放在 impl 函数中，而 start 和 onLoad 这种比较特殊的逻辑，不依赖这个函数，单独写出来也行

2017-03-09 03:29 UTC, jareguo commented on cocos2d/core/component-scheduler.js
> +            return new Function('it', body);
在运行时，impl 是虚方法，只能写 `comp[impl].call(comp)`，多了 call 以后函数调用开销就一下子大了，还不如像现在这样直接内联？

2017-03-09 03:48 UTC, pandamicro commented on cocos2d/core/component-scheduler.js
> +            return new Function('it', body);
这里放在后面在思考怎么优化吧，可能我对 new Function 比较抵触

2017-03-09 03:48 UTC, pandamicro approved these changes

2017-03-09 03:50 UTC, pandamicro commented on cocos2d/core/component-scheduler.js
> +            return new Function('it', body);
其实我想要的是一个性能基线测试，保障这样做的性能更好就行，针对关键模块需要写性能测试用例

2017-03-09 04:00 UTC, jareguo commented on cocos2d/core/component-scheduler.js
> +            return new Function('it', body);
> 这里放在后面在思考怎么优化吧，可能我对 new Function 比较抵触

new Function 很多库都在用…… regl 就是完全依靠这个实现了 webgl 封装的

> 其实我想要的是一个性能基线测试，保障这样做的性能更好就行，针对关键模块需要写性能测试用例

new Function vs eval vs HardCode 的性能我都有测试过，没有区别。在优化 instantiate 和对象构建时都用了很多动态代码生成了，性能只会快不会慢。

call vs 非 call 我也有测试过，性能差距在 10 倍左右。之前跑 benchmark 时就用了非 call 的方式进行过优化，不会有性能问题。

不过单就这里，性能测试用例现在还缺少框架……

2017-03-09 04:56 UTC, merged