fix bmfont parser cache
cocos/cocos-engine pull request #1553
Opened 2017-03-15 11:59 UTC by zilongshanren

Re: https://github.com/cocos-creator/fireball/issues/5410

Changes proposed in this pull request:
 *  add bmfont config cache

@cocos-creator/engine-admins

2017-03-15 12:09 UTC, pandamicro requested changes

2017-03-15 12:09 UTC, pandamicro commented on cocos2d/core/components/CCLabel.js
> +                    sgNode = this._sgNode = new _ccsg.Label(this.string, this.font.fntDataStr, this.font.spriteFrame);
JSB 的 Label 有缓存嘛？还是说也是每次都解析？如果跟 web 一样的话，建议修改 JS 层 Label 的构造函数

2017-03-15 15:07 UTC, zilongshanren commented on cocos2d/core/components/CCLabel.js
> +                    sgNode = this._sgNode = new _ccsg.Label(this.string, this.font.fntDataStr, this.font.spriteFrame);
@pandamicro  jsb 有 cache 的，不过有一个小 bug，我提交一下。

2017-03-15 15:27 UTC, zilongshanren commented on cocos2d/core/components/CCLabel.js
> +                    sgNode = this._sgNode = new _ccsg.Label(this.string, this.font.fntDataStr, this.font.spriteFrame);
https://github.com/cocos-creator/cocos2d-x-lite/pull/572 @pandamicro  这个影响不大，放在 develop 分支了。

2017-03-15 16:17 UTC, jareguo commented on cocos2d/core/label/CCSGLabel.js
> +    ctor: function(string, fontHandle, spriteFrame, bmfontUUID) {
建议把这个参数改成 bmFontAsset，缓存放在 Asset 对象里。好处是 loader 自动确保全局 Asset 对象唯一，所以缓存也唯一。而 BMFont 释放后缓存也会跟着释放。

2017-03-16 01:32 UTC, zilongshanren commented on cocos2d/core/label/CCSGLabel.js
> +    ctor: function(string, fontHandle, spriteFrame, bmfontUUID) {
缓存在 Asset 对象里面，然后靠 loader 保证全局惟一，貌似耦合有点多。另外 BMFont 释放，其实缓存可以不用释放吧，比如从一个场景切换到另一个场景，如果 bmfont 释放了，那下次进场景又要重新 parser。

2017-03-16 01:36 UTC, zilongshanren commented on cocos2d/core/components/CCLabel.js
> +                    sgNode = this._sgNode = new _ccsg.Label(this.string, this.font.fntDataStr, this.font.spriteFrame);
@pandamicro   
https://github.com/cocos-creator/cocos2d-x-lite/pull/572/files#diff-2a2688ddbccc880a37d1f8473a2f3da8L97   缓存地址

2017-03-16 01:49 UTC, pandamicro commented on cocos2d/core/label/CCSGLabel.js
> +    ctor: function(string, fontHandle, spriteFrame, bmfontUUID) {
我同意 jare 的看法。这个不能算耦合，恰恰是保障自治。
下一个场景依赖同样的 asset 的话，是不会被释放的

2017-03-16 01:53 UTC, zilongshanren commented on cocos2d/core/label/CCSGLabel.js
> +    ctor: function(string, fontHandle, spriteFrame, bmfontUUID) {
@pandamicro  可以，我改一下。

2017-03-16 02:04 UTC, zilongshanren commented
@jareguo  @pandamicro   修改完了，麻烦再 review 一下

2017-03-16 02:12 UTC, jareguo approved these changes

2017-03-16 02:20 UTC, pandamicro commented on cocos2d/core/label/CCSGLabel.js
> +                    this._fontAsset._fntConfig = self._config;
其实你已经不再需要 this._config 了，用的地方都用 this._fontAsset._fntConfig 就可以了

2017-03-16 02:20 UTC, pandamicro approved these changes

2017-03-16 02:22 UTC, zilongshanren commented on cocos2d/core/label/CCSGLabel.js
> +                    this._fontAsset._fntConfig = self._config;
@pandamicro  ok, 我改一下

2017-03-16 03:28 UTC, zilongshanren commented on cocos2d/core/label/CCSGLabel.js
> +                    this._fontAsset._fntConfig = self._config;
@pandamicro   暂时不改吧，改动的地方有点多，怕出 bug。

2017-03-16 03:28 UTC, zilongshanren commented
@pandamicro  我建了一个 issue  https://github.com/cocos-creator/fireball/issues/5412

2017-03-16 03:29 UTC, merged