add camera
cocos/cocos-engine pull request #1568
Opened 2017-03-24 07:40 UTC by 2youyou2

Re: cocos-creator/fireball#2137

@cocos-creator/engine-admins

2017-03-24 07:46 UTC, jareguo commented on cocos2d/core/camera/CCCamera.js
> +_ccsg.CameraNode = CameraNode;
建议统一，把这行代码放到 jsb-etc.js 的 window._ccsg = { ... } 里面

2017-03-24 07:51 UTC, jareguo commented on cocos2d/core/camera/CCCamera.js
> +_ccsg.CameraNode = CameraNode;
然后这里就只要
let CameraNode = CC_JSB ? _ccsg.CameraNode : require('./CCSGCameraNode');

2017-03-24 07:52 UTC, jareguo commented on cocos2d/core/camera/CCCamera.js
> +            default: function () {
直接 `default: []` 就行了，不会有问题

2017-03-24 08:03 UTC, jareguo commented on cocos2d/core/camera/CCSGCameraNode.js
> +        target.visit = info.originVisit;
不建议这样做，这样会永久性的在 target 上增加一个成员变量

2017-03-24 08:05 UTC, jareguo commented on cocos2d/core/camera/CCSGCameraNode.js
> +        target.__cameraInfo = {
建议叫 _cameraInfo 就好。因为 target 是 Node，Node 是不会被继承的，不用担心和用户的私有变量重名。同时建议在 Node 的构造函数中初始化这个字段，和 _widget 放在一起初始化。

2017-03-24 08:08 UTC, jareguo commented on cocos2d/core/camera/CCCamera.js
> +        let pos = this.node.convertToWorldSpaceAR(cc.Vec2.ZERO);
把这个 zero 缓存起来吧

2017-03-24 08:11 UTC, jareguo commented on cocos2d/core/camera/CCSGCameraNode.js
> +        mat.multiply(tempMatrix);
摄像机不支持旋转？

2017-03-24 08:12 UTC, jareguo commented on cocos2d/core/camera/CCSGCameraNode.js
> +        tempMatrix.identity();
tempMatrix 不需要 identity 吧

2017-03-24 08:13 UTC, jareguo commented on cocos2d/core/camera/CCSGCameraNode.js
> +        mat.identity();
mat 先 identity 再 multiply，感觉和直接拷贝值没什么区别？

2017-03-24 08:14 UTC, jareguo commented on cocos2d/core/camera/CCCamera.js
> +        else if (target instanceof _ccsg.Node) {
什么情况下会直接 add 一个 sgNode？

2017-03-24 08:15 UTC, jareguo commented on cocos2d/core/camera/CCCamera.js
> +    onEnable: function () {
请加入多 camera 冲突时的检测，否则这里必定会存在重复 add/remove 的情况

2017-03-24 08:17 UTC, jareguo commented on cocos2d/core/camera/CCSGCameraNode.js
> +        let afterVisitCmd = new cc.CustomRenderCmd(sgCameraNode, sgCameraNode._onAfterVisit);
不应该每次 visit 都 new 一次 render cmd，建议缓存

2017-03-24 08:18 UTC, 2youyou2 commented on cocos2d/core/camera/CCSGCameraNode.js
> +        mat.identity();
en，这里算法改了下，现在不用 tempMatrix 了

2017-03-24 08:18 UTC, 2youyou2 commented on cocos2d/core/camera/CCCamera.js
> +        else if (target instanceof _ccsg.Node) {
PhysicsManager 里面的 debug draw 这种

2017-03-24 08:19 UTC, 2youyou2 commented on cocos2d/core/camera/CCSGCameraNode.js
> +        let afterVisitCmd = new cc.CustomRenderCmd(sgCameraNode, sgCameraNode._onAfterVisit);
可以放在 cameraInfo 里

2017-03-24 08:19 UTC, 2youyou2 commented on cocos2d/core/camera/CCSGCameraNode.js
> +        mat.multiply(tempMatrix);
issue 只要支持 position 和 zoom

2017-03-24 08:20 UTC, 2youyou2 commented on cocos2d/core/camera/CCSGCameraNode.js
> +        target.visit = info.originVisit;
你指哪个，cameraInfo ? 这个是消耗最小吧

2017-03-24 08:23 UTC, 2youyou2 commented on cocos2d/core/camera/CCCamera.js
> +    onEnable: function () {
不允许多个 camera 的吧，可以加个标记判断是否有 camera 了？

2017-03-24 08:25 UTC, jareguo commented on cocos2d/core/camera/CCSGCameraNode.js
> +            originVisit: target.visit
不建议保存 originVisit，要还原时，直接 target.visit = target.constructor.prototype.visit ？

2017-03-24 08:30 UTC, 2youyou2 commented on cocos2d/core/camera/CCSGCameraNode.js
> +        mat.multiply(tempMatrix);
不过屏幕抖动这种是需要旋转来做的额
@nantas 不如用 camera node 的 world 矩阵来做 camera 矩阵？

2017-03-24 08:31 UTC, nantas commented on cocos2d/core/camera/CCSGCameraNode.js
> +        mat.multiply(tempMatrix);
可以，好做的话就支持一下吧

2017-03-24 08:51 UTC, jareguo commented on cocos2d/core/camera/CCSGCameraNode.js
> +        mat.multiply(tempMatrix);
用 world 矩阵的话，记得不要有缩放

2017-03-24 08:51 UTC, jareguo commented on cocos2d/core/camera/CCSGCameraNode.js
> +        target.visit = info.originVisit;
我指的是 visit

2017-03-24 08:52 UTC, jareguo commented on cocos2d/core/camera/CCSGCameraNode.js
> +        let afterVisitCmd = new cc.CustomRenderCmd(sgCameraNode, sgCameraNode._onAfterVisit);
放在 sgCameraNode 就好了吧，不需要每个节点都有一份

2017-03-24 08:53 UTC, jareguo commented on cocos2d/core/camera/CCCamera.js
> +    onEnable: function () {
是不允许的，可以用标记判断下~~

2017-03-24 09:02 UTC, 2youyou2 commented on cocos2d/core/camera/CCSGCameraNode.js
> +        let afterVisitCmd = new cc.CustomRenderCmd(sgCameraNode, sgCameraNode._onAfterVisit);
不行，renderer 不允许一个 command 使用多次

2017-03-24 09:03 UTC, jareguo commented on cocos2d/core/camera/CCSGCameraNode.js
> +        let afterVisitCmd = new cc.CustomRenderCmd(sgCameraNode, sgCameraNode._onAfterVisit);
好吧，这就有点 SB 了...

2017-03-24 09:05 UTC, 2youyou2 commented on cocos2d/core/camera/CCSGCameraNode.js
> +        mat.multiply(tempMatrix);
@nantas  用 world 矩阵，就不用 zoom 了吧，直接用 scale 了吧?

2017-03-24 09:08 UTC, jareguo commented on cocos2d/core/camera/CCSGCameraNode.js
> +            originVisit: target.visit
哦，我看到了，你还需要 originVisit.call，那就留着吧...

2017-03-24 09:12 UTC, jareguo commented on cocos2d/core/camera/CCSGCameraNode.js
> +        let afterVisitCmd = new cc.CustomRenderCmd(sgCameraNode, sgCameraNode._onAfterVisit);
![image](https://cloud.githubusercontent.com/assets/1503156/24287545/18d13794-10b5-11e7-99e8-69a6a1607963.png)

2017-03-27 02:01 UTC, pandamicro requested changes

2017-03-27 02:01 UTC, pandamicro commented on cocos2d/core/camera/CCSGCameraNode.js
> +        target.visit = info.originVisit;
这里貌似没办法，也不能修改 prototype 的 visit

2017-03-27 02:01 UTC, pandamicro commented on cocos2d/core/camera/CCSGCameraNode.js
> +        cc.current_stack.pop();
这里也需要 break batch，否则可能和后面的 render command 批处理，导致 projection 错误

2017-03-27 02:01 UTC, pandamicro commented on cocos2d/core/sprites/CCScale9Sprite.js
>                  this._renderCmd._needDraw = true;
也不需要设置为 true

2017-03-27 02:01 UTC, pandamicro commented on cocos2d/core/camera/CCSGCameraNode.js
> +    setTransform: function (vec, zoom) {
目前的版本不建议叫 setTransform，因为只能设置 pos, zoom，建议改为接受完整 3*2 transform 数据，a, b, c, d, tx, ty

2017-03-27 02:01 UTC, pandamicro commented on cocos2d/core/camera/CCCamera.js
> +        this._sgNode.setTransform(pos, zoomRatio);
这里最好能支持不同的策略，让用户可以修改 camera 行为，比如替换为

```
// transform 是一个常驻对象，用来填充结果，避免重复创建
this.calculateCameraTransformIn(transform);
this._sgNode.setTransform(transform);
```

默认实现在 calculateCameraTransform 中，用户如果改写这个函数就可以得到自己的 camera 行为了

2017-03-27 02:40 UTC, jareguo commented on cocos2d/core/camera/CCCamera.js
> +        cameraExists = false;
要不增加一个 cc.Camera.main 变量吧？取代 cameraExists
这个变量逻辑上和 cc.Canvas.instance 一样
@pandamicro @2youyou2

2017-03-27 02:42 UTC, jareguo commented on cocos2d/core/camera/CCCamera.js
> +            rotation += parent.rotation;
直接用 `_rotationX` 和 `_parent` 吧

2017-03-27 03:01 UTC, 2youyou2 commented on cocos2d/core/camera/CCCamera.js
> +        cameraExists = false;
目前来看 Camera.main 没有哪里会要获取这个参数吧，没有的话感觉没有必要了

2017-03-27 03:07 UTC, jareguo commented on cocos2d/core/camera/CCCamera.js
> +        let pos = node.convertToWorldSpaceAR(cc.Vec2.ZERO);
干脆直接 getNodeToWorldTransform ，然后从里面提取  pos 和 rotation 就好啦

2017-03-27 03:08 UTC, 2youyou2 commented on cocos2d/core/camera/CCCamera.js
> +        let pos = node.convertToWorldSpaceAR(cc.Vec2.ZERO);
rotation 怎么提取，已经和 scale 混合了

2017-03-27 03:12 UTC, jareguo commented on cocos2d/core/camera/CCCamera.js
> +        let pos = node.convertToWorldSpaceAR(cc.Vec2.ZERO);
```
(Math.atan2(this.b, this.a) + Math.atan2(-this.c, this.d)) * 0.5;
```

2017-03-27 03:13 UTC, jareguo commented on cocos2d/core/camera/CCCamera.js
> +        cameraExists = false;
方便用户获取全局 Camera 用的

2017-03-27 03:21 UTC, 2youyou2 commented on cocos2d/core/camera/CCCamera.js
> +        let pos = node.convertToWorldSpaceAR(cc.Vec2.ZERO);
ok

2017-03-27 03:32 UTC, jareguo commented on cocos2d/core/camera/CCCamera.js
> +        Camera.main = null;
这里的逻辑可能有点问题。A camera 已经存在，B 是新增的，这时报了警告，然后 main camera 变成了 B
然后如果 A disabled， main camera 就为空了…… 实际上 B 还在

2017-03-27 03:35 UTC, 2youyou2 commented on cocos2d/core/camera/CCCamera.js
> +        Camera.main = null;
B 新增的时候报警告并且 return 了，main 还是 A
不过 B disabled 的时候会把 main 置为 null..

2017-03-27 03:36 UTC, 2youyou2 commented on cocos2d/core/camera/CCCamera.js
> +        Camera.main = null;
像  canvas 那样再加个判断就好？
```javascript
if (Canvas.instance === this) {
            Canvas.instance = null;
        }
```

2017-03-27 03:37 UTC, jareguo commented on cocos2d/core/camera/CCCamera.js
> +        Camera.main = null;
可以~

2017-03-27 04:04 UTC, jareguo approved these changes

2017-03-27 06:28 UTC, pandamicro commented on cocos2d/core/camera/CCCamera.js
> +            cc.errorID(8300);
这样会导致编辑器中，用户一旦添加第二个 Camera 脚本层就崩溃了吧？你可以试试看会怎么样，看需不需要改成 warning

2017-03-27 06:30 UTC, jareguo commented on cocos2d/core/camera/CCCamera.js
> +            cc.errorID(8300);
编辑器里是不是应该设置 executeInEditMode: false?

2017-03-27 06:32 UTC, 2youyou2 commented on cocos2d/core/camera/CCCamera.js
> +            cc.errorID(8300);
默认就是 false 吧，camera 里没设置这个值

2017-03-27 06:34 UTC, 2youyou2 commented on cocos2d/core/camera/CCCamera.js
> +            cc.errorID(8300);
> 这样会导致编辑器中，用户一旦添加第二个 Camera 脚本层就崩溃了吧？你可以试试看会怎么样，看需不需要改成 warning

会报错，不会崩溃，用 error 比较明显地告诉他不能添加两个 camera

2017-03-27 06:37 UTC, 2youyou2 commented on cocos2d/core/camera/CCCamera.js
> +            cc.errorID(8300);
CCSgComponent 有设置 executeInEditMode 为 true...
Camera 要重新设置 executeInEditMode 为 false ...

2017-03-27 06:45 UTC, pandamicro approved these changes

2017-03-27 07:31 UTC, 2youyou2 commented on cocos2d/kazmath/gl/mat4stack.js
> +proto.update = function () {
@pandamicro 加个了 update 函数来更新 lastUpdated

2017-03-29 09:29 UTC, merged