过去一下代码
cocos/cocos-engine pull request #1580
Opened 2017-04-12 01:52 UTC by GameMidlet

Re: cocos-creator/fireball#

Changes proposed in this pull request:
 * 

> Makes sure these boxes are checked before submitting your PR - thank you!
>
- [ ] If your pull request has gone "stale", you should **rebase** your work on top of the latest version of the upstream branch.
- [ ] If your commit history is full of small, unimportant commits (such as "fix pep8" or "update tests"), **squash** your commits down to a few, or one, discreet changesets before submitting a pull request.
- To official teams:
  - [ ] Check that your javascript is following our [style guide](https://github.com/cocos-creator/fireball/blob/dev/.github/CONTRIBUTING.md) and end files with a newline
  - [ ] Document new code with comments in source code based on [API Docs](https://github.com/cocos-creator/fireball#api-docs)
  - [ ] Make sure any runtime log information in `cc.log` , `cc.error`, `cc.warn` or `cc.assert` has been moved into `DebugInfos.js` with an ID

@cocos-creator/engine-admins

2017-04-12 02:02 UTC, jareguo requested changes

2017-04-12 02:02 UTC, jareguo commented on cocos2d/core/value-types/CCRect.js
> + * @property origin
去掉 `@property origin`，保留 `@property {Vec2} origin` 就行

2017-04-12 02:02 UTC, jareguo commented on cocos2d/core/value-types/CCRect.js
> +/**
上面空一行

2017-04-12 02:06 UTC, jareguo requested changes
你的仓库已经太久没更新了，请拉取我们最新的代码，做一次 rebase 操作再提交
![image](https://cloud.githubusercontent.com/assets/1503156/24938082/978e1104-1f67-11e7-8502-15218a4e13f8.png)

2017-04-13 02:44 UTC, jareguo requested changes

2017-04-13 02:44 UTC, jareguo commented on cocos2d/core/CCGame.js
> +            cc.warn(' getPersistRootNode key==null');
Make sure any runtime log information in cc.log , cc.error, cc.warn or cc.assert has been moved into DebugInfos.js with an ID

2017-04-13 02:44 UTC, jareguo commented on cocos2d/core/CCGame.js
> +    setPersistRootNode: function (key,node) {
请补充 API 注释

2017-04-13 02:44 UTC, jareguo commented on cocos2d/core/CCGame.js
> +     * @return {key} 返回创建使用的key -1失败 其它成功
`@return {String} key`
另外请用英文注释，注意空格

2017-04-13 02:44 UTC, jareguo commented on cocos2d/core/CCGame.js
> +    getPersistRootNode:function(key){
请补充 API 注释

2017-04-13 02:44 UTC, jareguo commented on cocos2d/core/CCGame.js
> +     * @return {Boolean} false 失败 true 成功
请不要在 API 中出现中文

2017-04-13 02:44 UTC, jareguo commented on cocos2d/core/CCGame.js
> +            if(nodeOrKey instanceof cc.Node){
注意空格：Check that your javascript is following our [style guide](https://github.com/cocos-creator/fireball/blob/dev/.github/CONTRIBUTING.md) and end files with a newline

2017-04-13 02:44 UTC, jareguo commented on cocos2d/core/CCGame.js
> +     * @return {key} 返回创建使用的key -1失败 其它成功
为什么要有一个 KEY？

2017-04-13 02:44 UTC, jareguo commented on cocos2d/core/CCGame.js
> +     * @param {Node|Number} nodeOrKey - The node to be removed from persistent node list
node.uuid 是 String，不是 Number

2017-04-13 02:44 UTC, jareguo commented on cocos2d/core/CCGame.js
> +            }else if(typeof(nodeOrKey) == 'number'){
node.uuid 是 String，不是 Number

2017-04-13 02:44 UTC, jareguo commented on cocos2d/core/CCGame.js
> +        if (nodeOrKey !== this._ignoreRemovePersistNode) {
这个 if 判断仅在 nodeOrKey instanceof cc.Node 时有效，放在这里不合适

2017-04-15 01:42 UTC, GameMidlet commented on cocos2d/core/CCGame.js
> +     * @return {key} 返回创建使用的key -1失败 其它成功
就是不知道怎么获取常驻节点！才加key

2017-04-15 09:27 UTC, jareguo commented
感觉好像没必要给常驻节点加 key，因为常驻节点本来就能用 cc.find 之类的 API 查到啊？或者你调用 cc.game.addPersistRootNode 时，就能顺便存到你的变量里了？

2017-04-26 09:45 UTC, jareguo commented
太久没下文，本 PR 关闭，部分代码已人工摘录到 #1617，谢谢！

2017-04-26 09:45 UTC, closed without merging