一些小修复
cocos/cocos-engine pull request #1583
Opened 2017-04-13 06:19 UTC by jareguo

Re: cocos-creator/fireball#5135

Changes proposed in this pull request:
 * 修复 cc.errorID 经常报 func 找不到的 bug
 * 修复启用 uglify 后的单元测试例

@cocos-creator/engine-admins

2017-04-13 06:21 UTC, jareguo commented on CCDebugger.js
> -cc.warnID = genLogFunc(cc.warn, 'Warning');
之前放在这里时，_initDebugSetting 就都还没执行到，所以 cc.xxxID 其实获取不到正确的输出函数…… 有可能 cc.warn 是 undefine，运行时就会报 func undefined

2017-04-13 07:28 UTC, jareguo commented on CCDebugger.js
> -    if (CC_DEV) {
之前这里不管 assert 成败都会拷贝数组，很影响性能

2017-04-13 07:29 UTC, jareguo commented on CCDebugger.js
> +    var assertFailed = genLogFunc(function () {
消除 assertID 和 logID 的重复代码

2017-04-13 11:45 UTC, pandamicro requested changes

2017-04-13 11:45 UTC, pandamicro commented on CCDebugger.js
> +        var argsArr = [].slice.call(arguments);
这样会泄漏 arguments 的

https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#32-leaking-arguments

对于 arguments 的操作尽量不要追求简洁的代码

2017-04-13 11:45 UTC, pandamicro commented on CCDebugger.js
> -    if (CC_DEV) {
assert 失败是很少的情况吧？更有效的做法是把 cc.assert 的代码內联进来

2017-04-13 11:45 UTC, pandamicro commented on cocos2d/core/CCNode.js
> +        else if (CC_TEST ? (/* make CC_JSB mockable*/ Function('return CC_JSB'))() : CC_JSB) {
给你想出这种招我也是醉了

2017-04-13 16:03 UTC, jareguo commented on CCDebugger.js
> -    if (CC_DEV) {
嗯，失败的情况是很少的，正常项目不应该失败，所以这里就不用考虑失败时的性能了

2017-04-13 16:04 UTC, jareguo commented on CCDebugger.js
> +        var argsArr = [].slice.call(arguments);
assert 失败的情况是很少的，正常项目不应该失败，所以这里就不用考虑失败时的内存了。实际上这里应该不是内存泄露，只是这样传入了 arguments 到其它地方会导致代码无法被 optimize。

2017-04-14 01:35 UTC, pandamicro commented on CCDebugger.js
> +        var argsArr = [].slice.call(arguments);
文章里说的很清楚是泄漏啊

2017-04-14 01:35 UTC, pandamicro commented on CCDebugger.js
> -    if (CC_DEV) {
还是內联吧，逻辑也更直接

2017-04-14 01:48 UTC, jareguo commented on CCDebugger.js
> +        var argsArr = [].slice.call(arguments);
我觉得文章说错了，实际上也不仅仅是我这么认为。泄露应该是指的是将 arguments 传入了其它方法体这种行为，这种行为不会引起内存泄露，但会引起 optimize 失败。

2017-04-14 01:49 UTC, jareguo commented on CCDebugger.js
> -    if (CC_DEV) {
cc.assert 代码有两份，没办法内联，也不值得内联吧？这里没有优化性能的价值吧？

2017-04-14 02:01 UTC, pandamicro commented on CCDebugger.js
> -    if (CC_DEV) {
那一开始做这个修改就没什么意义啊

2017-04-14 02:02 UTC, pandamicro commented on CCDebugger.js
> +        var argsArr = [].slice.call(arguments);
汗。。。你是凭什么觉得的？有证据么？

2017-04-14 02:09 UTC, jareguo commented on CCDebugger.js
> +        var argsArr = [].slice.call(arguments);
然后执行到这个方法时，已经是 assert failed 的情况了，所以也没有必要考虑性能问题了，代码简炼点比较省包体。

2017-04-14 02:15 UTC, jareguo commented on CCDebugger.js
> +        var argsArr = [].slice.call(arguments);
> 汗。。。你是凭什么觉得的？有证据么？

你给出的文章，全文是搜不到 memory 这个单词的，实际上他说的是：

> There are numerous ways to use arguments in a way that causes the function to be unoptimizable. One must be extremely careful when using arguments.

注意这里的单词 unoptimizable

再看看网友们的评论：

![image](https://cloud.githubusercontent.com/assets/1503156/25030876/e2472e76-20fa-11e7-8e9c-66b39e1d2b3c.png)
![image](https://cloud.githubusercontent.com/assets/1503156/25030906/27027fd4-20fb-11e7-8853-09fa5f766ed0.png)

2017-04-14 02:16 UTC, jareguo commented on CCDebugger.js
> -    if (CC_DEV) {
这个修改的意义是消除重复代码，之前 assertID 和 genLogFunc 里面代码重复了

2017-04-14 02:19 UTC, pandamicro commented on CCDebugger.js
> +        var argsArr = [].slice.call(arguments);
普遍的意义上 leak 就是 memory leak，这个是通用的说法，你说的评论在哪里看到的

2017-04-14 02:19 UTC, pandamicro commented on CCDebugger.js
> +        var argsArr = [].slice.call(arguments);
普遍的意义上 leak 就是 memory leak，这个是通用的说法，你说的评论在哪里看到的

2017-04-14 02:22 UTC, jareguo commented on CCDebugger.js
> +        var argsArr = [].slice.call(arguments);
我觉得这里可能是你想太多了…… 这里的 leak 应该指的是语法分析里面的"变量逃逸"这个概念。而不是内存的泄露。
如果说某个版本的 SpiderMonkey 会因此内存泄漏还好说，V8 会蠢到这份上吗？真有这种 bug 分分钟都要被喷死的。

这里看到的
http://stackoverflow.com/questions/33162534/javascript-arguments-leak-var-array-slice-call

2017-04-14 02:33 UTC, pandamicro commented on CCDebugger.js
> -    if (CC_DEV) {
消除重复代码我没意见，我介意的是这段代码的坏味道太重了

```
var argsArr = [].slice.call(arguments);
argsArr.unshift(false);
cc.assert.apply(null, argsArr)
```

谁知道有没有用户或者我们未来的引擎维护人员写出类似的代码说，引擎里面就是这么写的啊，我们在代码中应该始终如一提倡一些好的 JS 编码风格，比如內联，比如尽量不使用 apply，比如 arguments 谨慎使用

2017-04-14 02:34 UTC, pandamicro commented on CCDebugger.js
> +        var argsArr = [].slice.call(arguments);
我倾向于谨慎得对待这类问题，所以尽量在代码中避免类似的使用方式，基本还是我上面提到的思路，就是始终如一提倡更好的代码风格

2017-04-14 02:57 UTC, pandamicro commented on CCDebugger.js
> +        // actually no need to protect arguments leak here in case of an error...
😂 服

2017-04-14 02:58 UTC, pandamicro approved these changes

2017-04-14 03:54 UTC, merged