fix cocos-creator/fireball/issues/5585
cocos/cocos-engine pull request #1598
Opened 2017-04-18 09:40 UTC by knoxHuang

Re: cocos-creator/fireball#5585

Changes proposed in this pull request:
 * 修复粒子系统自动释放粒子时出现错误信息 

@cocos-creator/engine-admins

2017-04-18 09:59 UTC, jareguo requested changes

2017-04-18 09:59 UTC, jareguo commented on cocos2d/particle/CCParticleSystem.js
> +        this._originOnExit = _ccsg.Node.prototype.onExit;
这里应该是初始化为 null 才对吧

2017-04-18 09:59 UTC, jareguo commented on cocos2d/particle/CCParticleSystem.js
> +        this._originOnExit = _ccsg.Node.prototype.onExit;
否则你直接给个全局变量不就完了

2017-04-19 01:28 UTC, jareguo commented on cocos2d/particle/CCParticleSystem.js
> +            this._originOnExit = _ccsg.Node.prototype.onExit;
这里应该是 this._originOnExit = sgNode.onExit;

2017-04-19 01:31 UTC, jareguo commented
你确认下这里逻辑有没有错误，就是先 autoRemove, 再取消，再 autoRemove 的话，是否能成功 remove？

2017-04-19 01:44 UTC, knoxHuang commented
你是说通过代码控制？

2017-04-19 02:21 UTC, merged