Add dom image pool to reduce memory footprint
cocos/cocos-engine pull request #1609
Opened 2017-04-22 09:02 UTC by pandamicro

Re: cocos-creator/fireball#5543

Changes proposed in this pull request:
 * Add dom image pool to reduce memory footprint

> Makes sure these boxes are checked before submitting your PR - thank you!
>
- [x] If your pull request has gone "stale", you should **rebase** your work on top of the latest version of the upstream branch.
- [x] If your commit history is full of small, unimportant commits (such as "fix pep8" or "update tests"), **squash** your commits down to a few, or one, discreet changesets before submitting a pull request.
- To official teams:
  - [x] Check that your javascript is following our [style guide](https://github.com/cocos-creator/fireball/blob/dev/.github/CONTRIBUTING.md) and end files with a newline
  - [x] Document new code with comments in source code based on [API Docs](https://github.com/cocos-creator/fireball#api-docs)
  - [x] Make sure any runtime log information in `cc.log` , `cc.error`, `cc.warn` or `cc.assert` has been moved into `DebugInfos.js` with an ID

@cocos-creator/engine-admins

2017-04-22 16:03 UTC, jareguo requested changes

2017-04-22 16:03 UTC, jareguo commented on cocos2d/core/textures/CCTexture2D.js
> -                    self.initWithElement(tex._htmlElementObj);
为什么不调用 initWithElement 了？不调用的话 _webTextureObj 都没赋值吧

2017-04-23 14:28 UTC, pandamicro commented on cocos2d/core/textures/CCTexture2D.js
> -                    self.initWithElement(tex._htmlElementObj);
这整个判断都没用了，因为 _htmlElementObj 在 handleLoadedTexture 之后就会被删除，所以重复调用 handleLoadedTexture 的情况下，_htmlElementObj 一定不存在，而 loader 中现在保存的是 texture 对象，不是 dom image 对象，所以从 loader 也取不到，这里的逻辑也就没意义了。

本来这段逻辑是为了容错，但是完全是画蛇添足，给这个函数添加了本不应该有的功能，包容了其他逻辑可能导致的错误。

2017-04-24 01:47 UTC, jareguo commented on cocos2d/core/textures/CCTexture2D.js
> -                    self.initWithElement(tex._htmlElementObj);
明白

2017-04-24 01:49 UTC, jwu commented on cocos2d/core/utils/misc.js
> +        return this._pool.pop() || new Image();
pool 内部是不是应该尽可能避免 pop 和 push 操作?

2017-04-24 01:53 UTC, jareguo approved these changes

2017-04-24 04:13 UTC, pandamicro commented on cocos2d/core/utils/misc.js
> +        return this._pool.pop() || new Image();
JS 的 pop 和 push 操作的是数组尾部，损耗很小

2017-04-24 05:36 UTC, jwu commented on cocos2d/core/utils/misc.js
> +        return this._pool.pop() || new Image();
我做了一个简单的测试: https://jsperf.com/array-push-vs-index-set ，貌似性能还是有差距，另外，push, pop 应该会导致额外的 heap 分配吧 ?

2017-04-24 05:38 UTC, jareguo commented on cocos2d/core/utils/misc.js
> +        return this._pool.pop() || new Image();
push 分配的内存一般会大大超过实际需要的值。pop 到使用内存低于保留内存一半时就会重新分配。不过在我看来这些比起 new Image 和 GC 这种操作来说都是可以忽略不计的，毕竟 VM 本身还有内存池呢。

2017-04-24 05:54 UTC, pandamicro commented on cocos2d/core/utils/misc.js
> +        return this._pool.pop() || new Image();
这里需要的池子大小是确定的，我优化一下

2017-04-24 06:43 UTC, merged