Add SGLabel pool
cocos/cocos-engine pull request #1665
Opened 2017-05-19 09:49 UTC by pandamicro

Re: cocos-creator/fireball#5784

Changes proposed in this pull request:
 * Add SGLabel pool

> Makes sure these boxes are checked before submitting your PR - thank you!
>
- [x] If your pull request has gone "stale", you should **rebase** your work on top of the latest version of the upstream branch.
- [x] If your commit history is full of small, unimportant commits (such as "fix pep8" or "update tests"), **squash** your commits down to a few, or one, discreet changesets before submitting a pull request.
- To official teams:
  - [x] Check that your javascript is following our [style guide](https://github.com/cocos-creator/fireball/blob/dev/.github/CONTRIBUTING.md) and end files with a newline
  - [x] Document new code with comments in source code based on [API Docs](https://github.com/cocos-creator/fireball#api-docs)
  - [x] Make sure any runtime log information in `cc.log` , `cc.error`, `cc.warn` or `cc.assert` has been moved into `DebugInfos.js` with an ID

@cocos-creator/engine-admins

2017-05-19 09:57 UTC, jareguo requested changes

2017-05-19 09:57 UTC, jareguo commented on cocos2d/core/platform/js.js
> +        this._pool.length = length;
如果 length > count，这里应该刷新一下 count

2017-05-19 09:58 UTC, jareguo commented on jsb/jsb-label.js
> +jsbLabel.pool = new JS.Pool(0);
jsb 上不缓存吗？

2017-05-21 04:16 UTC, pandamicro commented on jsb/jsb-label.js
> +jsbLabel.pool = new JS.Pool(0);
JSB 的适配还没做，之后再加

2017-05-21 04:16 UTC, pandamicro commented on cocos2d/core/platform/js.js
> +        this._pool.length = length;
OK

2017-06-27 14:32 UTC, pandamicro commented
尝试了一下实现 JSB 的 label 缓冲池，但是由于 label 状态过于复杂，缓冲池在回收对象过程中的重置操作有太多 JSB 函数调用，性能并没有优势，所以可以略过了

2017-06-27 14:39 UTC, jareguo approved these changes

2017-06-27 14:39 UTC, jareguo commented
最后场景加载速度提升了多少？

2017-06-28 02:03 UTC, pandamicro commented
没测试场景加载，这个取决于场景中有多少 label 以及是不是重复进入场景（池子中有没有 label），主要是减少 memory footprint，降低垃圾回收的频率，在游戏项目那边验证了

2017-06-28 03:21 UTC, merged

2017-06-28 07:44 UTC, zilongshanren commented
@nantas  这个 PR 在编辑器上面有 bug，建议 revert。。。。 @jareguo

2017-06-28 07:44 UTC, zilongshanren commented
@pandamicro 我刚刚发现运行时也可能有 bug。。。

2017-06-28 07:45 UTC, jareguo commented
这个 @pandamicro 看看好不好修吧，好修就直接修了，不好修再 revert