fixed rigidbody _onNodeScaleChanged
cocos/cocos-engine pull request #1697
Opened 2017-06-05 02:55 UTC by 2youyou2

Re: cocos-creator/fireball#5849

Changes proposed in this pull request:
 * fixed rigidbody _onNodeScaleChanged

@cocos-creator/engine-admins

2017-06-05 03:03 UTC, jareguo requested changes
cc.PhysicsCollider 为什么不定义成 CCClass

2017-06-05 03:15 UTC, jareguo commented on cocos2d/core/physics/CCRigidBody.js
> +                if (collider.apply) {
我觉得会出现这个 bug 的原因应该是类型定义有点坏味道，我不确定这样改写会不会更好：
cc.Collider.Box
(cc.Collider mixin cc.Collider.Box) -> cc.BoxCollider
cc.Collider -> cc.PhysicsCollder
(cc.PhysicsCollder mixin cc.Collider.Box) -> cc.PhysicsBoxCollider

然后这里只要 getComponents(cc.PhysicsCollider)

2017-06-05 03:19 UTC, jareguo commented on cocos2d/core/physics/CCRigidBody.js
> +                if (collider.apply) {
从逻辑上来看，这样也更清晰一些，cc.Collider -> cc.PhysicsCollder -> cc.PhysicsBoxCollider

2017-06-05 03:23 UTC, 2youyou2 commented on cocos2d/core/physics/CCRigidBody.js
> +                if (collider.apply) {
感觉这样会好点

2017-06-06 06:57 UTC, jareguo commented on cocos2d/core/collider/CCBoxCollider.js
> +});
这样看起来好爽的说~

2017-06-06 07:01 UTC, jareguo approved these changes

2017-06-06 07:02 UTC, jareguo commented
感觉这个 PR 是本月最佳

2017-06-06 07:07 UTC, merged