create new buffer when graphics verts number is bigger than 65535
cocos/cocos-engine pull request #1742
Opened 2017-06-20 10:18 UTC by 2youyou2

Re: cocos-creator/fireball#3958

Changes proposed in this pull request:
 * create new buffer when graphics verts number is bigger than 65535

@cocos-creator/engine-admins

2017-06-21 05:03 UTC, pandamicro requested changes

2017-06-21 05:03 UTC, pandamicro commented on cocos2d/core/graphics/graphics-webgl-cmd.js
> +            cc.g_NumberOfDraws++;
感觉没必要一个个 cmd 单独画啊，以 buffer 为单位画不就好了？

2017-06-21 05:03 UTC, pandamicro commented on cocos2d/core/graphics/graphics-webgl-cmd.js
>          this._pushCmd({
建议对这里的 command 对象进行复用

2017-06-21 05:03 UTC, pandamicro commented on cocos2d/core/graphics/graphics-webgl-cmd.js
>  _p._vget = function (index) {
这个函数的使用很浪费啊，创建出来的对象在 vset 中使用完就废弃了，要么改成这样：

```
// 函数外的常驻对象
var v0 = {x: 0, y: 0};
var v1 = {x: 0, y: 0};
...

if (loop) {
    this._vget(offset, v0);
    this._vget(offset + 1, v1);
    // Loop it
    this._vset(v0.x, v0.y);
    this._vset(v1.x, v1.y);
}
```

要不就不要用函数，直接內联去取也没什么问题

2017-06-21 05:37 UTC, 2youyou2 commented on cocos2d/core/graphics/graphics-webgl-cmd.js
> +            cc.g_NumberOfDraws++;
每个 command 要单独设置 color 啊

2017-06-21 05:40 UTC, 2youyou2 commented on cocos2d/core/graphics/graphics-webgl-cmd.js
>  _p._vget = function (index) {
这个可以优化下

2017-06-21 05:52 UTC, pandamicro commented on cocos2d/core/graphics/graphics-webgl-cmd.js
> +            cc.g_NumberOfDraws++;
color 也可以当数据存起来啊，color 并不会打断批处理

2017-06-21 05:54 UTC, pandamicro commented on cocos2d/core/graphics/graphics-webgl-cmd.js
> +            cc.g_NumberOfDraws++;
看到你的 uniform 了，每个顶点数据里面多存一个 float32 就可以存储 color 了，这也跟引擎的其他shader 用法一致

2017-06-21 06:01 UTC, 2youyou2 commented on cocos2d/core/graphics/graphics-webgl-cmd.js
> +            cc.g_NumberOfDraws++;
那要多传很多一样的数据了，这里很容易就达到几万个顶点

2017-06-21 06:36 UTC, pandamicro commented on cocos2d/core/graphics/graphics-webgl-cmd.js
> +            cc.g_NumberOfDraws++;
数据量的增加是从两个 float 变成三个 float，不过渲染效率会提升，一万个 float 大概是 40 kb 内存，你觉得大多数 graphics 用例会用到什么量级？几万个顶点？十万顶点？百万顶点？

另外，graphics 是因为精度高所以顶点数这么多么？

2017-06-21 06:46 UTC, 2youyou2 commented on cocos2d/core/graphics/graphics-webgl-cmd.js
> +            cc.g_NumberOfDraws++;
画弧线这种会产生很多顶点，多少量级不知道，看用户怎么用吧。
如果数据量增加而渲染效率会提升的话可以接受

2017-06-21 06:49 UTC, jwu commented on cocos2d/core/graphics/graphics-webgl-cmd.js
> +            cc.g_NumberOfDraws++;
绘制效率上，把 color 放顶点上一次性渲染一批数据是远高于将 color 放在 uniform 上分批渲染。拿点顶点数据的吞吐量到不了带宽极限的。

2017-06-21 06:52 UTC, 2youyou2 commented on cocos2d/core/graphics/graphics-webgl-cmd.js
> +            cc.g_NumberOfDraws++;
那我改改~

2017-06-22 08:58 UTC, 2youyou2 commented
@pandamicro 重新优化了

2017-06-22 09:05 UTC, pandamicro approved these changes

2017-06-23 02:12 UTC, merged