Fix pipeline issue
cocos/cocos-engine pull request #1795
Opened 2017-07-10 09:45 UTC by zilongshanren

Re: cocos-creator/fireball#

Changes proposed in this pull request:
 *  Fix a bug in `insertPipe` API
 * add an API `insertPipeAfter`

@cocos-creator/engine-admins

2017-07-10 09:56 UTC, jareguo requested changes

2017-07-10 09:56 UTC, jareguo commented on cocos2d/core/load-pipeline/pipeline.js
> + * @param {Object} oldPipe The existing pipe in the pipeline.
叫做 oldPipe 感觉是一个会被修改为 new 的操作。建议叫 refPipe 或者 reference 或者 previousPipe

2017-07-10 09:56 UTC, jareguo commented on cocos2d/core/load-pipeline/pipeline.js
> +    var pipeAfterOldPipe = null;
这是 pipeAfterNewPipe 才对吧

2017-07-10 09:59 UTC, zilongshanren commented on cocos2d/core/load-pipeline/pipeline.js
> +    var pipeAfterOldPipe = null;
@jareguo 这里的 oldPipe 指的是参数里面的 oldPipe...有歧义，哈哈

2017-07-10 09:59 UTC, zilongshanren commented on cocos2d/core/load-pipeline/pipeline.js
> + * @param {Object} oldPipe The existing pipe in the pipeline.
@jareguo 这个名字是 @pandamicro 给的建议，我都可以。

2017-07-10 10:00 UTC, jareguo commented on cocos2d/core/load-pipeline/pipeline.js
> +    var pipeAfterOldPipe = null;
感觉这边不管怎么改，都不如直接调用 this.insertPipe(index + 1, newPipe); 来的清晰

2017-07-10 10:01 UTC, zilongshanren commented on cocos2d/core/load-pipeline/pipeline.js
> +    var pipeAfterOldPipe = null;
@jareguo 恩，是的，我改一下。

2017-07-10 10:03 UTC, jareguo commented on cocos2d/core/load-pipeline/pipeline.js
> +    var pipeAfterOldPipe = null;
然后前面就不需要判断 newPipe.handle 和 id 了

2017-07-11 01:37 UTC, pandamicro commented on cocos2d/core/load-pipeline/pipeline.js
> + * @param {Object} oldPipe The existing pipe in the pipeline.
insertPipeAfter(pipe, newPipe) 这样就好了吧

2017-07-11 01:38 UTC, pandamicro commented on cocos2d/core/load-pipeline/pipeline.js
> +    var pipeAfterOldPipe = null;
这里同意 jare 的说法调用 insertPipe 来完成实际的工作

2017-07-11 01:39 UTC, zilongshanren commented on cocos2d/core/load-pipeline/pipeline.js
> +    var pipeAfterOldPipe = null;
@pandamicro  原来的 insertPipe 还有 bug，我一会儿提交修复。

2017-07-11 01:41 UTC, zilongshanren commented
@jareguo @pandamicro 重构了以前的 insertPipe，请 review。

2017-07-11 01:49 UTC, zilongshanren commented
之前的 insertPipe 有个 bug，如果 pipes 里面有 2 个元素，这时候调用 insertPipe(new Pipe(), 5),
会导致最后 push 的这个 pipe 没有 previous pipe。

这里我做了一个判断，如果 pipe 的位置大于 this._pipe.length，则直接返回。
另外，已经有一个 appendPipe 了，所以，我觉得没必要支持 insertPipe 的 index > this._pipes.length 的情况。

2017-07-11 01:50 UTC, pandamicro requested changes

2017-07-11 01:50 UTC, pandamicro commented on cocos2d/core/load-pipeline/pipeline.js
> +    if (!pipe.handle || !pipe.id || index > this._pipes.length) {
index 比较大的时候不是应该直接 append 么，如果不允许那就加一个 warning 在这边

2017-07-11 01:50 UTC, pandamicro commented on cocos2d/core/load-pipeline/pipeline.js
> +    this.insertPipe(newPipe, index+1);
这样会遇到如果 refPipe 是最后一个 pipe，insert 失败的情况

2017-07-11 01:54 UTC, pandamicro approved these changes

2017-07-11 01:55 UTC, pandamicro commented on cocos2d/core/load-pipeline/pipeline.js
> +    this.insertPipe(newPipe, index+1);
哦对，是兼容的，没事，上面可以考虑加一个 warning

2017-07-11 02:06 UTC, jareguo commented on cocos2d/core/load-pipeline/pipeline.js
> +        nextPipe = this._pipes[index];
你这里还是没修复 insertPipe(new Pipe(), ...) 的问题啊？

2017-07-11 02:07 UTC, jareguo commented on cocos2d/core/load-pipeline/pipeline.js
> +        nextPipe = this._pipes[index];
哦，看错了，我还以为是 insertPipeBefore(refPipe)

2017-07-11 02:08 UTC, jareguo commented on cocos2d/core/load-pipeline/pipeline.js
> +    if (!pipe.handle || !pipe.id || index > this._pipes.length) {
index 比较大的时候不是应该直接 append 么，如果不允许那就报个错吧

2017-07-11 02:13 UTC, zilongshanren commented on cocos2d/core/load-pipeline/pipeline.js
> +    if (!pipe.handle || !pipe.id || index > this._pipes.length) {
@jareguo 报错加上了。

2017-07-11 02:17 UTC, pandamicro requested changes

2017-07-11 02:17 UTC, pandamicro commented on cocos2d/core/load-pipeline/pipeline.js
> +        cc.warn('The pipe to be inserted is already in the pipeline!');
麻烦用 warnID，把信息写在 DebugInfo 里面

2017-07-11 02:31 UTC, jareguo commented on DebugInfos.js
> +        "8303": "The pipe to be inserted is already in the pipeline!", //pipeline.insertPipe
这个 id 是 camera 的…… 这个 id 虽然没什么意义但是会影响导出的 markdown 文档中的索引，最好放到 loader 相关的 id 那边

2017-07-11 02:40 UTC, jareguo approved these changes

2017-07-11 03:06 UTC, pandamicro approved these changes

2017-07-11 03:07 UTC, merged