Extend the RichText <img> tag's attributes to support height and width
cocos/cocos-engine pull request #1904
Opened 2017-08-16 02:19 UTC by RazgrizHsu

follow the original principle: the image line height must not exceed the RichText line height

Changes proposed in this pull request:
 * 扩充RichText组件，使<img>标签支持设定height及width，但维持基础原则"图像高不超过设定高行"

这是之前有提过的需求，你们看看是否可行

@cocos-creator/engine-admins

2017-08-16 02:35 UTC, knoxHuang commented
这个为啥不去直接修改原图的大小呢？还要去规定他的宽高，能否举个例子

2017-08-16 03:54 UTC, RazgrizHsu commented
例如资源图示的图集，显示在道具栏(Sprite)的时候，它是标准大小 (假设是128px)
当我要用在说明栏位( 多行的RichText )里的时候，它应该是比文字小一些
( 假设RichText行高设定 30，文字是 26 )
原本的设定里，这个时候你的图示却会是30的大小，这样第一行跟第二行之间的间距就不见了

再假设你有一个表情符号的图集，
这些表情会用在战斗中做为弹窗显示，也想要用在聊天介面的时候，并不会去缩小这个图集

我目前遇到的情况是这两种，

当然啦，你们评估看看，我是现在已经这样使用了

2017-08-16 06:13 UTC, knoxHuang commented
嗯，我知道你的意思了，我们会评估看看，如果没问题会加入

2017-08-17 02:10 UTC, knoxHuang commented on cocos2d/core/components/CCRichText.js
> +            if(expectHeight && expectHeight > 0 && expectHeight < this.lineHeight )
这里写 if (expectHeight > 0 && expectHeight < this.lineHeight ) 就行了

2017-08-17 02:10 UTC, knoxHuang commented on cocos2d/core/components/CCRichText.js
> +            else if(spriteRect.height > this.lineHeight) {
else if (spriteHeight  > this.lineHeight) {

2017-08-17 02:10 UTC, knoxHuang commented on cocos2d/core/components/CCRichText.js
> +                scaleFactor = expectHeight / spriteRect.height;
scaleFactor = expectHeight / spriteHeight;

2017-08-17 02:10 UTC, knoxHuang commented on cocos2d/core/components/CCRichText.js
>                  scaleFactor = this.lineHeight / spriteRect.height;
scaleFactor = this.lineHeight / spriteHeight;

2017-08-17 02:10 UTC, knoxHuang commented on cocos2d/core/components/CCRichText.js
> +            if(expectWidht && expectWidht > 0) spriteWidth = expectWidht;
if(expectWidth > 0) spriteWidth = expectWidth;

2017-08-17 02:10 UTC, knoxHuang commented on cocos2d/core/components/CCRichText.js
> +            var expectWidht = richTextElement.style.imageWidth;
expectWidht  -> expectWidth

2017-08-17 02:12 UTC, knoxHuang commented
@jareguo 我没啥问题了
@RazgrizHsu 等 jare review 完，你修改后，在测试一下就可以合并了
非常感谢 👍 💯

2017-08-17 02:24 UTC, jareguo requested changes

2017-08-17 02:24 UTC, jareguo commented on cocos2d/core/components/CCRichText.js
> +            if(expectHeight && expectHeight > 0 && expectHeight < this.lineHeight )
这里是不是漏了一种情况，如果 expectHeight > lineHeight, 并且 spriteHeight < lineHeight，那应该把图片放大到和 lineHeight 一致才对，照目前的代码来看，似乎不会放大

2017-08-17 02:24 UTC, jareguo commented on cocos2d/core/label/CCHtmlTextParser.js
> +                var imageAttrReg = /(\s)*src(\s)*=|(\s)*height(\s)*=|(\s)*width(\s)*=|(\s)*click(\s)*=/;
把这个正则缓存一下， 不要每次调用 _attributeToObject 都重新编译

2017-08-17 02:24 UTC, jareguo commented on cocos2d/core/label/CCHtmlTextParser.js
> +                    header = attribute.match(imageAttrReg);
正则使用全局模式是否就能不用重复匹配？

2017-08-17 03:49 UTC, RazgrizHsu commented on cocos2d/core/label/CCHtmlTextParser.js
> +                var imageAttrReg = /(\s)*src(\s)*=|(\s)*height(\s)*=|(\s)*width(\s)*=|(\s)*click(\s)*=/;
目前的写法大多是照抄下方匹配outline attribute的方式，
outline那个部份也没有做缓存，

如果要缓存的话，我是觉得拉到档案头部，也就是跟25行的
```js
:25 var eventRegx = /^(click)(\s)*=/;
```
就是变成
``` js
:25 var eventRegx = /^(click)(\s)*=/; //line:25
:26 var imageAttrReg = /(\s)*src(\s)*=|(\s)*height(\s)*=|(\s)*width(\s)*=|(\s)*click(\s)*=/; //line:26
```
放在一起，这样如何？

2017-08-17 03:55 UTC, RazgrizHsu commented on cocos2d/core/label/CCHtmlTextParser.js
> +                    header = attribute.match(imageAttrReg);
这边看来是不能省略的，省略了的话，它就取不到下一个attribute的值，会变成死循环

如上面那则回覆，
因为这边使用regular expression来匹配每一个attriubte的方式
我是照抄下方匹配outline的方式，
之所以会照抄，是因为我以为这种写法是你们认可的，所以才这么写

否则的话，我应该会使用
1. 直接用regular的group来匹配每一个attribute
2. 或者第一次使用regex匹配，接着每个子attribute仅使用string index+substring来匹配
    ( 由于我不晓得在现在的js引擎里，是否substring效率高于regex，所以这两种写法会考虑下 )

2017-08-17 03:58 UTC, RazgrizHsu commented on cocos2d/core/components/CCRichText.js
> +            if(expectHeight && expectHeight > 0 && expectHeight < this.lineHeight )
不好意思，的确是漏了这种情况，
因为在我的使用情境里，我只有考虑到原图缩小
看了一下旧的代码里，的确是会将原图放大到lineHeight的比例
下次的commit我会补上

2017-08-17 03:59 UTC, jareguo commented on cocos2d/core/label/CCHtmlTextParser.js
> +                var imageAttrReg = /(\s)*src(\s)*=|(\s)*height(\s)*=|(\s)*width(\s)*=|(\s)*click(\s)*=/;
可以~

2017-08-17 04:01 UTC, jareguo commented on cocos2d/core/label/CCHtmlTextParser.js
> +                    header = attribute.match(imageAttrReg);
之前子龙的实现其实我没怎么细看，所以会现在才提出这个疑问。那就先按你现在这样的实现吧，之后有需要再优化。

2017-08-17 04:26 UTC, RazgrizHsu commented on cocos2d/core/label/CCHtmlTextParser.js
> +                    header = attribute.match(imageAttrReg);
好的，謝謝 :)

2017-08-17 04:52 UTC, jareguo commented on cocos2d/core/components/CCRichText.js
> +            } else {
这样一来是不是会导致未定义 expectHeight 时，图片也会被拉伸到行高？

2017-08-17 04:59 UTC, RazgrizHsu commented on cocos2d/core/components/CCRichText.js
> +            } else {
是的，我以为你要的效果是跟随原本的方式，
最初的版本里，任何图片都会缩放至与行高相同，

现在是变成，
1. 仅在你有定义image height，并且值小于行高，才替你缩小
2. 其余的情况，与最初的版本相同，会缩放到与行高相同

当然，我是觉得如果该图片原本的大小，就小于行高的话，应该是维持原本的大小比较合理，

看您怎么决定，我再修改

2017-08-17 05:01 UTC, RazgrizHsu commented on cocos2d/core/components/CCRichText.js
> +            } else {
另外，
其实我原本是打算连：当图片设定的值大于line height时，就调整该行行高
不过因为这样改动有些大，怕你们不能接受，所以就先跟随原本的基础原则

2017-08-17 06:09 UTC, jareguo commented on cocos2d/core/components/CCRichText.js
> +            } else {
> 最初的版本里，任何图片都会缩放至与行高相同，
> 当然，我是觉得如果该图片原本的大小，就小于行高的话，应该是维持原本的大小比较合理，

之前的实现我也不太清楚， @knoxHuang 怎么看？要不要保持和原有一致？

2017-08-17 06:17 UTC, knoxHuang commented on cocos2d/core/components/CCRichText.js
> +            } else {
我觉得这样就可以了，有设置 image height 才会变动，其余的跟原来的版本一样就行

2017-08-17 06:22 UTC, jareguo commented on cocos2d/core/components/CCRichText.js
> +            } else {
OK，那就这样

2017-08-17 06:24 UTC, jareguo approved these changes

2017-08-17 06:24 UTC, merged

2017-08-17 06:25 UTC, jareguo commented
感谢提供，引擎如果有实现得不够好的地方，欢迎继续提出 PR

2017-08-17 06:28 UTC, RazgrizHsu commented
thanks for accept,
你们很棒了, 每个大神都身兼数职，很辛苦，
非常感谢你们

能力所及且你们不嫌弃的话，我会尽量提供有建设性的修改，谢谢 👍