V1.6
cocos/cocos-engine pull request #1918
Opened 2017-08-21 14:05 UTC by jareguo

Re: cocos-creator/fireball#6291

Changes proposed in this pull request:
 * 修复加载远程贴图时，url 中带有 query 的话将引起贴图互相覆盖的 bug。

@cocos-creator/engine-admins

2017-08-21 14:08 UTC, jareguo commented on cocos2d/core/load-pipeline/asset-loader.js
> +            item.url = item.rawUrl = url;
这里仍然重新赋值 rawUrl，因为这里拿到的 url 应该是用户脚本中会用到的，并且这里其实应该是 url 和 rawUrl 的第一次赋值
cc @knoxHuang 

但是目前 CCLoader 本身已经整合了 asset-loader 这个 pipe 里的一些逻辑，导致 item 的 url 和 rawUrl 已经提前初始化好了。那这样的话我建议后续移除整个 asset-loader @pandamicro

2017-08-21 14:08 UTC, jareguo commented on cocos2d/core/load-pipeline/loading-items.js
> -var _parseUrl = function (url) {
改成对传入的 result 进行处理，避免返回临时对象

2017-08-21 14:09 UTC, jareguo commented on cocos2d/core/load-pipeline/loading-items.js
> -            rawUrl: urlItem.url, // url used in scripts
合并两个 result 的初始化代码…… 我不觉得分成两份会带来阅读上的清晰，反而让人忍不住想要”找不同“

2017-08-21 14:23 UTC, jareguo commented on cocos2d/core/load-pipeline/loading-items.js
> -            id.type = Path.extname(id.url).toLowerCase().substr(1);
不应该修改传入参数本身，这样的副作用并未在方法名或者参数名上体现，那就应该避免

2017-08-22 01:30 UTC, pandamicro requested changes

2017-08-22 01:30 UTC, pandamicro commented on cocos2d/core/load-pipeline/loading-items.js
> +    result.rawUrl = result.url;
这里应该等于 url 把，result.url 是 parseUrl 处理后的，你的测试可以通过是因为这个值在 asset loader 中被覆盖了

2017-08-22 01:34 UTC, jareguo commented on cocos2d/core/load-pipeline/loading-items.js
> +    result.rawUrl = result.url;
我觉得应该用的是 result.url，不论前面怎么处理，既然 result.url 可以直接用于下载，那就应该是符合用户预期的。
比如对 audio clip 来说，显然用户获取的  rawUrl 也不希望里面出现 `?useDom=1` 之类的字符串吧？

2017-08-22 01:36 UTC, pandamicro commented on cocos2d/core/load-pipeline/loading-items.js
> +    result.rawUrl = result.url;
rawUrl 的意思应该是原始的 url，而不是处理后的，从名字上来说也应该保持用户传递的样子才对

2017-08-22 01:37 UTC, jareguo commented on cocos2d/core/load-pipeline/loading-items.js
> +    result.rawUrl = result.url;
如果用户有传递的是 { url: 'xxx' } 的话，这里 result.url 就会是用户传递的样子，因为有 mixin

2017-08-22 01:38 UTC, pandamicro commented on cocos2d/core/load-pipeline/loading-items.js
> +    result.rawUrl = result.url;
我的意思是如果用传递 "host.com/audio.mp3?useDom=1" 的话，rawUrl 也应该忠实保持原有的 url

2017-08-22 01:41 UTC, jareguo commented on cocos2d/core/load-pipeline/loading-items.js
> +    result.rawUrl = result.url;
> 你的测试可以通过是因为这个值在 asset loader 中被覆盖了

这里的测试例不会走到 asset loader，会通过是因为这里 mixin 了用户传入的 url

2017-08-22 01:55 UTC, pandamicro approved these changes

2017-08-22 01:56 UTC, pandamicro commented
不小心点错了。。。

2017-08-22 02:05 UTC, jareguo commented
已修改，统一保留下载的 url query，连 audio 的 `?useDom=1` 都保留

2017-08-22 03:52 UTC, merged