separate culling and transform step
cocos/cocos-engine pull request #1945
Opened 2017-08-30 07:39 UTC by 2youyou2

Re: cocos-creator/fireball#6322

Changes proposed in this pull request:
 * separate culling and transform step

@cocos-creator/engine-admins

2017-08-30 07:44 UTC, 2youyou2 commented on cocos2d/core/base-nodes/CCSGNodeBaseRenderCmd.js
> +            this.transform(parentCmd, true);
如果 transform dirty 了则必然也要进行 culling，而如果只是 culling dirty 了则只需要重新计算 culling 值

2017-08-30 07:44 UTC, 2youyou2 commented on cocos2d/core/base-nodes/CCSGNodeBaseRenderCmd.js
> +/****************************************************************************
从 CCSGNodeCanvasRenderCmd.js 里分离出 base render cmd 的逻辑到 CCSGNodeBaseRenderCmd.js，否则逻辑看起来太乱

2017-08-30 07:44 UTC, 2youyou2 commented on cocos2d/core/base-nodes/CCSGNodeBaseRenderCmd.js
> +    cullingDirty:   1 << 10,
添加一个 cullingDirty 标志位

2017-08-30 07:44 UTC, 2youyou2 commented on cocos2d/core/base-nodes/CCSGNodeBaseRenderCmd.js
> +    culling: function (parentCmd, recursive) {
添加一个 culling 阶段

2017-08-30 07:45 UTC, 2youyou2 commented on cocos2d/core/camera/CCCamera.js
> +    cullingDirtyFlag = _ccsg.Node._dirtyFlags.cullingDirty;
camera transform 变了的话只需要重新计算 culling

2017-08-30 07:46 UTC, 2youyou2 commented on cocos2d/core/platform/CCMacro.js
> +    ENABLE_CULLING: true,
添加一个 ENABLE_CULLING 宏

2017-08-30 08:08 UTC, jareguo commented on cocos2d/core/base-nodes/CCSGNodeBaseRenderCmd.js
> +/****************************************************************************
好棒

2017-08-30 08:10 UTC, jareguo commented on cocos2d/core/base-nodes/CCSGNodeBaseRenderCmd.js
> +/****************************************************************************
但这个 license 和 CCSGNodeCanvasRenderCmd 的都不一样啊

2017-08-30 08:14 UTC, jareguo commented on cocos2d/core/platform/CCMacro.js
> +     * 是否开启自动裁减功能，开启裁减功能将会把在屏幕外的物体从渲染队列中去除掉
注释建议加上句号，否则要用 <br> 硬分行，否则文档中会 join 到一行。

2017-08-30 08:21 UTC, jareguo commented on cocos2d/core/sprites/CCScale9SpriteCanvasRenderCmd.js
> +        this._needDraw = false;
我不确定这个代码是否会被 uglify 优化，（如果这里是 return false / true 是会优化）
还是手动写成 this._needDraw = (r < vl || l > vr || t < vb || b > vt); 比较保险

2017-08-30 08:22 UTC, jareguo commented
单元测试没过

2017-08-30 10:08 UTC, jareguo commented
LGTM， @pandamicro  怎么看？

2017-08-30 10:15 UTC, pandamicro requested changes

2017-08-30 10:15 UTC, pandamicro commented on cocos2d/core/renderer/RendererWebGL.js
> +            if (enableCulling && !cmd._needDraw) continue;
这里不应该有 enableCulling 的判断，enableCulling 的结果应该直接反应在 _needDraw 标记上

2017-08-30 10:15 UTC, pandamicro commented on cocos2d/core/sprites/CCScale9Sprite.js
> +    fastSetSpriteFrameOnWeb: function (spriteFrame) {
这个干吗用的？

2017-08-30 10:15 UTC, pandamicro commented on cocos2d/core/base-nodes/CCSGNodeBaseRenderCmd.js
> +                child._renderCmd[funcName](parentCmd);
这个就比较慢了，实在不行，干脆复制一份实现也不是不能接受

2017-08-30 10:25 UTC, 2youyou2 commented on cocos2d/core/sprites/CCScale9Sprite.js
> +    fastSetSpriteFrameOnWeb: function (spriteFrame) {
给快速设置 sprite 用的，还是删掉放到另一个 pr 吧

2017-08-30 10:27 UTC, pandamicro commented on cocos2d/core/renderer/RendererWebGL.js
> +            if (enableCulling && !cmd._needDraw) continue;
应该将 ENABLE_CULLING 改为 setter，在值被修改的时候，重置 scene 的 culling dirty 标记，让 render command 的 _needDraw 得到更新。在这里这个几乎是引擎最高调用频度的 for 循环中去做检查不太合理，更何况 enableCulling 的信息在 doCulling 的时候本来就是要判断的

2017-08-30 10:34 UTC, pandamicro commented on cocos2d/core/base-nodes/CCSGNodeBaseRenderCmd.js
> +                child._renderCmd[funcName](parentCmd);
好吧，并没有找到确切的证据，jsperf 的结果来看，差别不大，忽略这条

https://jsperf.com/function-calls-direct-vs-apply-vs-call-vs-bind/6

2017-08-30 10:48 UTC, jareguo commented on cocos2d/core/renderer/RendererWebGL.js
> +            if (enableCulling && !cmd._needDraw) continue;
我觉得就直接在文档里说明 ENABLE_CULLING 不允许动态修改，否则原先渲染的场景可能出异常。用户有需要的话自己 hack。

2017-08-30 10:51 UTC, jareguo commented on cocos2d/core/base-nodes/CCSGNodeBaseRenderCmd.js
> +                child._renderCmd[funcName](parentCmd);
我想不到的是，这种方式调用时，怎么能确保 this 会是 child._renderCmd？

2017-08-31 01:45 UTC, 2youyou2 commented on cocos2d/core/base-nodes/CCSGNodeBaseRenderCmd.js
> +                child._renderCmd[funcName](parentCmd);
因为是 child._renderCm 调用的这个 function ...

2017-08-31 07:36 UTC, 2youyou2 commented on cocos2d/core/renderer/RendererWebGL.js
> +            if (enableCulling && !cmd._needDraw) continue;
将 ENABLE_CULLING 从这里删掉了，动态切换在 example_cases 会给示范

2017-08-31 09:22 UTC, pandamicro approved these changes

2017-09-01 07:40 UTC, merged