释放被依赖的资源时给警告
cocos/cocos-engine pull request #1949
Opened 2017-08-31 16:16 UTC by jareguo

Re: cocos-creator/fireball#6237

Changes proposed in this pull request:
 * 在用户错误释放了仍可能被用到的资源时给出详细提示

@cocos-creator/engine-admins

2017-08-31 16:18 UTC, jareguo commented on cocos2d/core/load-pipeline/CCLoader.js
> +            self._releasedAssetChecker_DEBUG.checkCouldRelease(self._cache);
注册帧事件，每一帧检查一次是否有错误的释放操作（有标志位，不会做无效检测）

2017-08-31 16:19 UTC, jareguo commented on cocos2d/core/load-pipeline/asset-table.js
> +proto.getInfo_DEBUG = CC_DEBUG && function (uuid) {
尝试从 uuid 获取 resources 下的 Asset 信息

2017-08-31 16:22 UTC, jareguo commented on cocos2d/core/load-pipeline/released-asset-checker.js
> +    if (!loadedAgain) {
资源有可能正确释放后，被其它依赖的新资源又连带加载回来，这里要判断下是否有加载回来否则就会误报

2017-08-31 16:28 UTC, jareguo commented on cocos2d/core/load-pipeline/CCLoader.js
> +            self._releasedAssetChecker_DEBUG.checkCouldRelease(self._cache);
延迟到每一帧结束时检测是为了避免误报。
（比如 loader.release(['bg.png', bgSpriteFrame]) 时就会误报）

2017-08-31 16:36 UTC, jareguo commented on cocos2d/core/platform/js.js
> +        delete map[INVALID_IDENTIFIER_1];
ensure to use hash properties rather than in object property (or map chain)

2017-09-01 03:18 UTC, pandamicro requested changes

2017-09-01 03:18 UTC, pandamicro commented on cocos2d/core/load-pipeline/asset-table.js
> +                    return { path: path, type: entry.type };
避免产生新的内存垃圾

2017-09-01 03:19 UTC, jareguo commented on cocos2d/core/load-pipeline/asset-table.js
> +                    return { path: path, type: entry.type };
这个是有警告时才会产生的…… 这个警告产生的几率不大

2017-09-01 03:34 UTC, pandamicro commented on cocos2d/core/load-pipeline/asset-table.js
> +                    return { path: path, type: entry.type };
你就写个临时对象复用，没啥复杂的，这个函数也不会嵌套

2017-09-01 03:59 UTC, jareguo commented on cocos2d/core/load-pipeline/asset-table.js
> +                    return { path: path, type: entry.type };
改好啦

2017-09-01 04:01 UTC, pandamicro approved these changes

2017-09-01 07:37 UTC, merged