fix mask clipping area does not match
cocos/cocos-engine pull request #1970
Opened 2017-09-08 08:05 UTC by knoxHuang

Re: cocos-creator/fireball#

Changes proposed in this pull request:
 * 修复 Mask 矩形类型，不匹配，多出几个像素

@cocos-creator/engine-admins

2017-09-08 08:09 UTC, pandamicro commented on cocos2d/core/components/CCMask.js
> +const OFFSET = 0.5;
不如叫 RECT_INSET，叫 OFFSET 太宽泛了

2017-09-08 08:14 UTC, pandamicro approved these changes

2017-09-08 08:15 UTC, jareguo commented
为什么只有 rect 需要偏移 0.5 像素？
这个 PR 会影响到 JSB 实现吗？

2017-09-08 08:16 UTC, knoxHuang commented
这样刚刚好可以符合 DrawNode 的 0.5 像素

2017-09-08 08:17 UTC, jareguo commented
为什么 _calculateCircle 就不用改？

2017-09-08 08:17 UTC, pandamicro commented
@knoxHuang 验证一下 JSB

DrawNode 在绘制的时候会外扩 0.5 个像素，导致切出来的区域也大一点点

2017-09-08 08:31 UTC, jareguo commented on cocos2d/core/components/CCMask.js
>              else if (this._type === MaskType.ELLIPSE) {
麻烦验证下 ellipse 模式是否也有相同 bug

2017-09-08 08:31 UTC, jareguo requested changes

2017-09-08 08:31 UTC, jareguo commented on cocos2d/core/components/CCMask.js
> +const RECT_INSET = 0.5;
麻烦验证一下 JSB 是否有相同 bug

2017-09-08 09:01 UTC, knoxHuang commented on cocos2d/core/components/CCMask.js
> +const RECT_INSET = 0.5;
JSB 没有该 bug

2017-09-08 09:24 UTC, knoxHuang commented
经过测试 JSB 和 ellipse 不会出现该问题

2017-09-08 09:35 UTC, jareguo requested changes

2017-09-08 09:35 UTC, jareguo commented on cocos2d/shape-nodes/CCDrawNode.js
> +            var vertices = [cc.p(origin.x + RECT_INSET , origin.y + RECT_INSET),
这里应该定义这样一个局部变量，用来取代 RECT_INSET
const MIN_LINE_WIDTH = 1;
const fixLineWidth = Math.max(MIN_LINE_WIDTH - lineWidth, 0) / 2;

2017-09-08 09:43 UTC, jareguo commented on cocos2d/shape-nodes/CCDrawNode.js
> +            var vertices = [cc.p(origin.x + RECT_INSET , origin.y + RECT_INSET),
不对，drawPoly 内部已经修复了这个 lineWidth 问题了，你应该看一下为什么它的修复是无效的。否则将来如果它的 bug fix 了，你这边的 hack 就反而会变成 bug。

2017-09-08 09:44 UTC, knoxHuang commented on cocos2d/shape-nodes/CCDrawNode.js
> +            var vertices = [cc.p(origin.x + RECT_INSET , origin.y + RECT_INSET),
嗯，我先看看

2017-09-11 08:36 UTC, jareguo commented
这样清晰多了！最开始不知道哪个傻逼实现的，非要把 canvas 的逻辑往 webgl 上套，效果还不对，后面整个节奏带歪，浪费时间……

2017-09-11 08:37 UTC, jareguo approved these changes

2017-09-11 08:37 UTC, merged