Add began and ended event to CCScrollview
cocos/cocos-engine pull request #1978
Opened 2017-09-13 07:25 UTC by feijing566

sync from https://github.com/cocos2d/cocos2d-x/pull/18054

@cocos-creator/engine-admins

2017-09-13 07:43 UTC, knoxHuang commented on cocos2d/core/components/CCScrollView.js
> +     * @method getContentPosition
@method getContentPosition -> @method isScrolling

2017-09-13 07:44 UTC, knoxHuang commented
其他的我没啥问题了，你在看看 @Jare

2017-09-13 07:49 UTC, jareguo requested changes

2017-09-13 07:49 UTC, jareguo commented on cocos2d/core/components/CCScrollView.js
> +    'auto-scroll-ended' : EventType.AUTOSCROLL_ENDED,
这是否会导致 API 不兼容？

2017-09-13 07:50 UTC, knoxHuang commented on cocos2d/core/components/CCScrollView.js
> +    'auto-scroll-ended' : EventType.AUTOSCROLL_ENDED,
除非用户用的是字符串 ‘scroll-ended’

2017-09-13 07:51 UTC, jareguo commented on cocos2d/core/components/CCScrollView.js
> +    'scroll-ended': EventType.SCROLLING_ENDED
请把新增的事件补充到 event 注释区域中，在这个文件的最下面，你搜索 `@event touch-up` 就能看到

2017-09-13 07:52 UTC, feijing566 commented on cocos2d/core/components/CCScrollView.js
> +    'auto-scroll-ended' : EventType.AUTOSCROLL_ENDED,
用户不会用到的，因为事件传递出来的是EventType.AUTOSCROLL_ENDED，是数字

2017-09-13 07:53 UTC, jareguo commented on cocos2d/core/components/CCScrollView.js
> +	SCROLLING_ENDED: 13
请问什么时候需要区分 AUTOSCROLL_ENDED 和 SCROLLING_ENDED？

2017-09-13 07:57 UTC, feijing566 commented on cocos2d/core/components/CCScrollView.js
> +	SCROLLING_ENDED: 13
在没有触发惯性滚动的时候 就需要用SCROLLING_ENDED来通知滚动结束

2017-09-13 08:00 UTC, feijing566 commented on cocos2d/core/components/CCScrollView.js
> +    'scroll-ended': EventType.SCROLLING_ENDED
加了

2017-09-13 08:03 UTC, feijing566 commented on cocos2d/core/components/CCScrollView.js
> +	SCROLLING_ENDED: 13
滚动有2种结束方式，1种是立即结束1种就是需要惯性滚动一段距离后结束，这里的2个时间就是用来对应这2种操作

2017-09-13 08:05 UTC, jareguo commented on cocos2d/core/components/CCScrollView.js
> +	SCROLLING_ENDED: 13
那把这两个事件合并为一个 `SCROLL_ENDED` 就行了吧？

2017-09-13 08:07 UTC, feijing566 commented on cocos2d/core/components/CCScrollView.js
> +	SCROLLING_ENDED: 13
这个就要看具体需求了。毕竟这里是2种状态，分成2个事件也是有他的价值的

2017-09-13 08:09 UTC, feijing566 commented on cocos2d/core/components/CCScrollView.js
> +	SCROLLING_ENDED: 13
从引擎的角度来说，还是区分开来会合理一些吧，能满足尽量多的需求

2017-09-13 08:12 UTC, jareguo commented on cocos2d/core/components/CCScrollView.js
> +	SCROLLING_ENDED: 13
我对 UI 不是很熟悉，你能否提供一个案例，说说什么情况下用户会希望区分这两个事件？

2017-09-13 08:26 UTC, feijing566 commented on cocos2d/core/components/CCScrollView.js
> +	SCROLLING_ENDED: 13
在分批次加载scrollview内容的时候可以用上，end的时候可以判断是否需要继续加载内容

2017-09-13 08:37 UTC, jareguo commented on cocos2d/core/components/CCScrollView.js
> +	SCROLLING_ENDED: 13
好像不对啊，判断是否要继续加载，应该是监听 scrolling 事件吧？因为只要有在滚动，不论是用户手指在拖拽还是自动滚动，都需要继续加载内容。

2017-09-14 03:13 UTC, jareguo commented on cocos2d/core/components/CCScrollView.js
> +	SCROLLING_ENDED: 13
就先合并这两个事件吧，统一叫 `SCROLL_ENDED` 就好，之后要是有遇到合理的需求再拆分。事件名称保持不变，还是叫做 `scroll-ended`，只不过之前是自动滚动停止时才触发，现在是不自动滚动的话，手动停止滚动也触发。

2017-09-14 03:14 UTC, feijing566 commented on cocos2d/core/components/CCScrollView.js
> +	SCROLLING_ENDED: 13
这样会带来一个问题就是跟jsb的表现不一致，需要同步修改jsb的代码

2017-09-14 03:16 UTC, knoxHuang commented on cocos2d/core/components/CCScrollView.js
> +	SCROLLING_ENDED: 13
这个只有 JS 层，C++ 那边不需要同步的

2017-09-14 03:54 UTC, feijing566 commented on cocos2d/core/components/CCScrollView.js
> +	SCROLLING_ENDED: 13
合并了，麻烦看下

2017-09-14 03:59 UTC, jareguo approved these changes

2017-09-14 04:00 UTC, merged

2017-09-14 04:00 UTC, jareguo commented
已合并，感谢帮忙！