Refactor Texture2D API to adopt new renderer design
cocos/cocos-engine pull request #1983
Opened 2017-09-14 08:31 UTC by pandamicro

Re: cocos-creator/fireball#6119

Texture2D changes proposed in this pull request:
 * Add Texture2D.Filter and Texture2D.PixelFormat to replace some constants
 * Use width and height to replace pixelWidth/pixelHeight and contentSize
 * Expose loaded, width, height directly
 * Removed getName, generateMipmap, stringForFormat, bitsPerPixelForFormat
 * Removed Texture2D::initWithImage, TextureCache::addUIImage
 * Add update to support setting texture parameters (wrap, filter, premultiplyAlpha, mipmap)

> Makes sure these boxes are checked before submitting your PR - thank you!
>
- [x] If your pull request has gone "stale", you should **rebase** your work on top of the latest version of the upstream branch.
- [x] If your commit history is full of small, unimportant commits (such as "fix pep8" or "update tests"), **squash** your commits down to a few, or one, discreet changesets before submitting a pull request.
- To official teams:
  - [x] Check that your javascript is following our [style guide](https://github.com/cocos-creator/fireball/blob/dev/.github/CONTRIBUTING.md) and end files with a newline
  - [x] Document new code with comments in source code based on [API Docs](https://github.com/cocos-creator/fireball#api-docs)
  - [x] Make sure any runtime log information in `cc.log` , `cc.error`, `cc.warn` or `cc.assert` has been moved into `DebugInfos.js` with an ID

@cocos-creator/engine-admins

2017-09-14 08:33 UTC, jareguo commented on DebugInfos.js
> -        "3110": "bitsPerPixelForFormat: %s, cannot give useful result, it's a illegal pixel format", //bitsPerPixelForFormat
这个不应该删掉，否则旧版本的用户就查不到文档了

2017-09-14 08:35 UTC, pandamicro commented on DebugInfos.js
> -        "3110": "bitsPerPixelForFormat: %s, cannot give useful result, it's a illegal pixel format", //bitsPerPixelForFormat
我保留 EngineErrorMap.md 里面的吧

2017-09-14 08:43 UTC, jareguo requested changes
麻烦同步到 JSB

2017-09-14 08:43 UTC, jareguo commented on DebugInfos.js
> -        "3110": "bitsPerPixelForFormat: %s, cannot give useful result, it's a illegal pixel format", //bitsPerPixelForFormat
那个文件是自动生成的，你保留了也还是会被覆盖

2017-09-15 02:26 UTC, pandamicro commented
done

2017-09-15 02:29 UTC, jareguo approved these changes

2017-09-15 02:29 UTC, jareguo commented
LGTM

2017-09-15 10:30 UTC, merged