[WIP] Refactoring Texture2D to Asset
cocos/cocos-engine pull request #1987
Opened 2017-09-18 09:40 UTC by jareguo

Re: cocos-creator/fireball#6082

Changes proposed in this pull request:
 * 将 Texture 重构为 Asset

@cocos-creator/engine-admins

2017-09-18 09:51 UTC, jareguo commented on cocos2d/core/load-pipeline/loader.js
> +        return image;
Texture2D 变成 Asset 后，loadImage 变成了需要同时支持两种类型。一种是用户直接写 cc.loader.load('xxxx.png')，需要返回的是 Texture2D，另一种新增的是 uuid-loader 在反序列化 Texture2D 后，由 uuid-loader 进一步 flowInDeps 去请求实际的 Image，这时 loadImage 返回的应该是 Image 而不是 Texture2D。所以这里需要判断一下 `item._owner`

2017-09-18 09:54 UTC, jareguo commented on cocos2d/core/load-pipeline/uuid-loader.js
> -function loadDepends (pipeline, item, asset, tdInfo, deferredLoadRawAssetsInRuntime, callback) {
将原先的 loadDepends 拆分成了 parseDepends 和 loadDepends, 否则太大了

2017-09-18 09:57 UTC, jareguo commented on cocos2d/core/load-pipeline/uuid-loader.js
> +                    _stillUseUrl: stillUseUrl[i]
去掉了 objList 和 propList 数组，直接把这两部分数据加到 depends 里面。这样一来，tdInfo 就不需要长期持有了，可以当帧立刻释放。

2017-09-18 09:59 UTC, jareguo commented on cocos2d/core/load-pipeline/uuid-loader.js
> +    var stillUseUrl = tdInfo._stillUseUrl;
这是一个哈希字典，用来区分 url: cc.Texture2D 还是 type: cc.Texture2D，2.0 以后可以干掉

2017-09-18 10:00 UTC, jareguo commented on cocos2d/core/load-pipeline/uuid-loader.js
> +            _ownerProp: '_nativeAsset',
增加 Image 依赖，用于加载 cc.Texture2D 中实际依赖的 Image，加载成功后会触发 _nativeAsset 的 setter

2017-09-18 10:02 UTC, jareguo commented on cocos2d/core/load-pipeline/uuid-loader.js
> +                var thisOfLoadCallback = dep;
因为这里不用创建临时对象了，直接复用 depends 中的 _owner 即可

2017-09-18 10:05 UTC, jareguo commented on cocos2d/core/sprites/CCSpriteFrame.js
> +        return this._texture && this._texture.isLoaded();
移除了 spriteFrame._textureLoaded，统一使用 textureLoaded()

2017-09-18 10:07 UTC, jareguo commented on cocos2d/core/textures/CCTexture2D.js
> +    getWebGLTexture: function () {
name / getName 和 Asset 的 API 冲突了，修改成 getWebGLTexture

2017-09-19 16:59 UTC, pandamicro requested changes

2017-09-19 16:59 UTC, pandamicro commented on cocos2d/core/assets/CCAsset.js
> +        nativeUrl: {
raw 改为 native 感觉更有歧义啊，creator 的很多文档和概念中，都会用到 native 指代原生平台，这里可能会让人误解为原生 url 之类的意思，改为 native 有什么特别的意义么？

2017-09-19 16:59 UTC, pandamicro commented on cocos2d/core/assets/CCAsset.js
>           * 而是每个 asset 都能指定自己的 raw file url。这些 url 就存在 _rawFiles 字段中。
_rawFiles 已经被删除了

2017-09-19 16:59 UTC, pandamicro commented on cocos2d/core/assets/CCAsset.js
> +        this._native = filename || "";
如果 filename 为 undefined，应该要保留原来的 _native 值把

2017-09-19 16:59 UTC, pandamicro commented on cocos2d/core/load-pipeline/CCLoader.js
>                  cc.textureCache.removeTextureForKey(item.url);
直接给 texture 实现一个 release 函数把，将 textureCache 的移除也放在 release 函数中

2017-09-19 16:59 UTC, pandamicro commented on cocos2d/core/load-pipeline/CCLoader.js
>                  cc.textureCache.removeTextureForKey(item.url);
将 Texture2D 的 releaseTexture deprecated 掉，内部实现直接调用 release

2017-09-19 16:59 UTC, pandamicro commented on cocos2d/core/load-pipeline/loader.js
> +        return image;
我在 new renderer 分支里面的做法你看一下，我不确定哪种方式更好，提供另一种思路

反序列化时，可以添加一个 texture 属性给 loading item

https://github.com/pandamicro/fire-engine/commit/c0879ef311cc50ebd5d1f0e6e5afb8d4a89828be#diff-7d02486dd8e371850c5cdd562d7a4525R54

在加载完成后，主动给 texture 初始化

https://github.com/pandamicro/fire-engine/commit/c0879ef311cc50ebd5d1f0e6e5afb8d4a89828be#diff-6a34551b57697d355e4b8124ac12b756L55

不知道用这样的方法能不能避免多加载一层 depends

2017-09-19 16:59 UTC, pandamicro commented on cocos2d/core/textures/CCTexture2D.js
> +JS.get(_p, "pixelFormat", _p.getPixelFormat);
这三个属性我觉得可以 deprecated 了，pixelWidth 和 pixelHeight 已经被取代，pixelFormat 也可以用 getPixelFormat 来获取，我觉得足够了，所以不建议添加注释

2017-09-19 17:09 UTC, jareguo commented on cocos2d/core/load-pipeline/loader.js
> +        return image;
depends 应该是一样的。之后还有 audio 什么的也要重构，所以字段就没叫做 texture。

2017-09-19 17:11 UTC, jareguo commented on cocos2d/core/assets/CCAsset.js
> +        nativeUrl: {
改为 nativeUrl 主要是为了避免和 item.rawUrl 重名，否则查找什么的都很蛋疼。另外 native 这个命名也更符合一般引擎的命名规律，一般引擎 raw 是用于 raw data，很少有 raw object 这种叫法。

2017-09-19 17:11 UTC, jareguo commented on cocos2d/core/assets/CCAsset.js
> +        this._native = filename || "";
不应该吧，否则就清空不了了

2017-09-19 17:15 UTC, jareguo commented on cocos2d/core/load-pipeline/CCLoader.js
>                  cc.textureCache.removeTextureForKey(item.url);
叫做 dispose 或者 cleanup 吧？否则 release 和以前的 retain / release 重名了

2017-09-19 17:27 UTC, jareguo commented on cocos2d/core/textures/CCTexture2D.js
> +JS.get(_p, "pixelFormat", _p.getPixelFormat);
好

2017-09-19 17:27 UTC, jareguo commented on cocos2d/core/assets/CCAsset.js
>           * 而是每个 asset 都能指定自己的 raw file url。这些 url 就存在 _rawFiles 字段中。
好

2017-09-20 01:36 UTC, pandamicro commented on cocos2d/core/assets/CCAsset.js
> +        this._native = filename || "";
清空应该直接传递 "" 把，undefined 应该是属于用错 API

2017-09-20 01:37 UTC, pandamicro commented on cocos2d/core/load-pipeline/CCLoader.js
>                  cc.textureCache.removeTextureForKey(item.url);
因为我看你下面的 cc.Asset 判断里面用的是 release，对我来说统一就好

2017-09-20 01:43 UTC, jareguo commented on cocos2d/core/assets/CCAsset.js
> +        this._native = filename || "";
用错 API 也应该清空，否则可能就不能及时发现

2017-09-20 01:49 UTC, pandamicro commented on cocos2d/core/assets/CCAsset.js
> +        nativeUrl: {
照这个描述，API 描述应该要改一下，我怎么觉得直接用 url 也可以呢，配合 API 说明。主要是 native 使用的地方太多了，我看到 native 就想到原生平台

2017-09-20 01:50 UTC, pandamicro commented on cocos2d/core/load-pipeline/CCLoader.js
>                  cc.textureCache.removeTextureForKey(item.url);
destroy 好了，3d engine 的 asset 用的是这个，也跟 Object 一致

2017-09-20 01:53 UTC, pandamicro commented on cocos2d/core/assets/CCAsset.js
> +        this._native = filename || "";
那也可以，这个不纠结

2017-09-20 01:56 UTC, pandamicro commented on cocos2d/core/load-pipeline/loader.js
> +        return image;
如果是这样的话，咱们就不应该删除 image 对象，否则也没有复用 image item 的价值了，这个我最近重构的时候也在思考，删除 image 对象，感觉弊大于利，虽然可以节省 image cache 缓存，但是实际上内存占用更高的是 gl texture，如果用户想要动态删除和重新加载 gl texture，没有 image 对象会很不方便。

2017-09-20 02:06 UTC, jareguo commented on cocos2d/core/assets/CCAsset.js
> +        nativeUrl: {
好

2017-09-20 02:10 UTC, jareguo commented on cocos2d/core/load-pipeline/CCLoader.js
>                  cc.textureCache.removeTextureForKey(item.url);
OK

2017-09-20 02:12 UTC, jareguo commented on cocos2d/core/load-pipeline/loader.js
> +        return image;
这里没有删除啊？

2017-09-20 02:13 UTC, jareguo commented
> 这个 _owner 是所有需要 loadDepends 的资源公用的，不仅仅是 Texture。

我是说每个 asset 都会写入 item._owner，但是 item._owner 并不是复用的。

2017-09-20 02:34 UTC, pandamicro commented on cocos2d/core/load-pipeline/loader.js
> +        return image;
在 _nativeAsset 的 setter 里面有用 misc.imagePool.put，那个 put 完其实 image 就无效了

https://github.com/cocos-creator/engine/pull/1987/files#diff-749f94091e7f746ca203a219bbf263eaR265

2017-09-23 01:27 UTC, jareguo commented on cocos2d/core/load-pipeline/loader.js
> +    return tex;
还原了 H5 平台的 imageLoader

2017-09-23 01:28 UTC, jareguo commented on cocos2d/core/load-pipeline/uuid-loader.js
> +            skips: [ loader.id ],
改在 loadDepends 时通过指定 skips loader 来避免 image 被加载成新 texture

2017-09-23 01:29 UTC, jareguo commented on jsb/jsb-loader.js
> +    'image' : loadImage,
由于 loader 被 skips 了，所以这里改在 downloader 里加载 native 平台的 image

2017-09-23 01:30 UTC, jareguo commented on jsb/jsb-loader.js
> +            cc.textureCache.initImageAsync(item._owner, url, function (tex) {
增加了两个绑定 API，你说的 cc.textureCache.initImageAsync 和 jsb.initRemoteImg

2017-09-23 01:32 UTC, jareguo commented on jsb/jsb-tex-sprite-frame.js
> +    cc.Texture2D[key] = WebTexture[key];
去掉了 JSB 上的冗余代码，直接用 H5 平台的 Texture 定义来初始化 cc.Texture

2017-09-23 01:33 UTC, jareguo commented on jsb/jsb-tex-sprite-frame.js
> +cc.js.addon(prototype, WebTexture.prototype);
同上，直接用 H5 平台的 Texture prototype 来初始化 cc.Texture

2017-09-23 01:34 UTC, jareguo commented on jsb/jsb-tex-sprite-frame.js
>  };
原生平台 cc.Texture 需要调用 JS 父构造函数

2017-09-23 01:35 UTC, jareguo commented on jsb/jsb-tex-sprite-frame.js
> +cc.js.addon(prototype, WebSpriteFrame.prototype);
采用同样方法同步 SpriteFrame 的 H5 实现

2017-09-29 10:17 UTC, pandamicro commented
你这个 PR 的 commit 列表不对啊，咋回事？

具体内容我晚点看下

2017-09-29 10:18 UTC, jareguo commented
合并了 master 了，否则冲突太多

2017-09-29 10:24 UTC, pandamicro commented
我才注意到是 asset branch，这个 asset 用来做哪些内容？持续到什么时候？

2017-09-29 13:59 UTC, jareguo commented
用来完成 RawAsset 移除相关工作的，估计要持续到 1.7

2017-09-30 07:56 UTC, pandamicro commented on cocos2d/core/assets/CCAsset.js
> +        nativeUrl: {
这里没改啊？

2017-09-30 07:58 UTC, jareguo commented on cocos2d/core/assets/CCAsset.js
> +        nativeUrl: {
要改成什么…… 现在 API 没错啊

2017-09-30 16:53 UTC, pandamicro commented on cocos2d/core/assets/CCAsset.js
> +        _nativeAsset: {
其实如果 _native 和 _nativeAsset 完全是私有变量，倒也没什么关系，但是现在这两个变量都有文档，用户可见，我也解释过我觉得 native 不妥的原因，我之前是建议把 _native 改成 _url，如果觉得不够清晰，把 native 换成 actual，target 我都可以接受，只要不和现有引擎中大量使用的 native 语境相冲突即可

2017-09-30 16:53 UTC, pandamicro commented on jsb/jsb-loader.js
> +        var loader = isRemote ? jsb.initRemoteImg : jsb.initTextureAsync;
没有找到 jsb.initRemoteImg 和 jsb.initTextureAsync 的定义啊

2017-09-30 16:53 UTC, pandamicro commented on cocos2d/core/platform/js.js
> +    var extractPropName = /([^.]+)$/;
当成常量放在外面把，不用每次调用的时候都创建固定的 RegularExpression 对象

2017-09-30 16:53 UTC, pandamicro commented on jsb/jsb-tex-sprite-frame.js
> +// });
这段注释写清楚一点把，提示一下 addon 所注入的实现是哪些即可，这么看还以为是漏删除的什么多余代码

2017-09-30 16:53 UTC, pandamicro commented on jsb/jsb-tex-sprite-frame.js
> +        // }
这里的问题是什么？

2017-10-01 04:50 UTC, jareguo commented on cocos2d/core/platform/js.js
> +    var extractPropName = /([^.]+)$/;
这个接口初始化时才会调用，而且是调试模式是调，放在外面的话就浪费内存了

2017-10-01 04:51 UTC, jareguo commented on jsb/jsb-tex-sprite-frame.js
> +        // }
没什么…… 漏了删掉了

2017-10-01 04:51 UTC, jareguo commented on jsb/jsb-tex-sprite-frame.js
> +// });
我删掉注释吧，用处不大了

2017-10-01 04:51 UTC, jareguo commented on jsb/jsb-loader.js
> +        var loader = isRemote ? jsb.initRemoteImg : jsb.initTextureAsync;
在 lite 仓库啊

2017-10-01 04:52 UTC, jareguo commented on jsb/jsb-tex-sprite-frame.js
> +        // }
这里的问题是，jsb 上初始化 texture 是在 C++ 进行的，所以这里没有什么可以做的

2017-10-01 04:56 UTC, jareguo commented on cocos2d/core/assets/CCAsset.js
> +        _nativeAsset: {
这两个现在是私有变量，文档中显示不出来的，加了 `@private` 标记

2017-10-01 12:21 UTC, pandamicro commented on cocos2d/core/assets/CCAsset.js
> +        _nativeAsset: {
算了，你那么坚持就用 native 把，希望不会引起用户误解

2017-10-01 12:21 UTC, pandamicro approved these changes

2017-10-07 08:02 UTC, merged