[dragonBones] Determine whether there is a new armature
cocos/cocos-engine pull request #2002
Opened 2017-09-26 06:36 UTC by feijing566

修复加载相同龙骨名，不同骨骼数据时无法正确加载的BUG
@cocos-creator/engine-admins

2017-09-26 06:41 UTC, jareguo commented on extensions/dragonbones/ArmatureDisplay.js
> +                                dragonBonesData = this._factory._dataParser.parseDragonBonesData(this.dragonAsset.dragonBonesJson);
_dataParser 好像没有导出到 jsb，在原生平台上可能没有这个字段吧？麻烦测试一下模拟器或者真机

2017-09-26 06:50 UTC, jareguo commented on extensions/dragonbones/ArmatureDisplay.js
> +                        data.addArmature(dragonBonesData.armatures[armature.name]);
感谢你的提交。请问下如果 DragonBonesData 相同，还要合并 armatures data，是出于什么目的？为什么 armatures data 会存在多个 DragonBonesData 之中？

2017-09-26 06:53 UTC, feijing566 commented on extensions/dragonbones/ArmatureDisplay.js
> +                        data.addArmature(dragonBonesData.armatures[armature.name]);
DragonBonesData是不同的，只是在同一个龙骨工程里面导出来的多个动画，他们共用相同的龙骨资源，但是是不同的动画

2017-09-26 06:54 UTC, feijing566 commented on extensions/dragonbones/ArmatureDisplay.js
> +                        data.addArmature(dragonBonesData.armatures[armature.name]);
所以需要判断是否有新的armature，如果有，则添加到DragonBonesData中

2017-09-26 07:08 UTC, jareguo commented on extensions/dragonbones/ArmatureDisplay.js
> +                        data.addArmature(dragonBonesData.armatures[armature.name]);
好的。不过这里 armatures 很可能没有导出到 JSB，原生平台上不一定能用。建议改成  getArmature(armature.name)，并且在原生平台上测看看。

2017-09-26 07:09 UTC, jareguo requested changes
需要验证原生平台

2017-09-26 07:31 UTC, feijing566 commented on extensions/dragonbones/ArmatureDisplay.js
> +                                dragonBonesData = this._factory._dataParser.parseDragonBonesData(this.dragonAsset.dragonBonesJson);
dragonBones.ObjectDataParser.getInstance() 用这个？

2017-09-26 08:04 UTC, feijing566 commented
原生平台应该是无效的，要绑定_dataParser，对原生不熟悉，只能交给引擎组来处理了

2017-09-26 08:19 UTC, jareguo commented on extensions/dragonbones/ArmatureDisplay.js
> +                                dragonBonesData = this._factory._dataParser.parseDragonBonesData(this.dragonAsset.dragonBonesJson);
原生平台用不了这个，算了，这个我们再处理

2017-09-26 08:22 UTC, jareguo commented
好的，晚点我再研究下怎么做比较好，先谢谢！

2017-09-27 08:03 UTC, jareguo commented
关闭这个 PR，放到 https://github.com/cocos-creator/engine/pull/2005 继续完善 JSB

2017-09-27 08:03 UTC, closed without merging

2017-12-30 18:14 UTC, jareguo commented on extensions/dragonbones/ArmatureDisplay.js
> +                        data.addArmature(dragonBonesData.armatures[armature.name]);
你好，我最近重新在验证这一块的设计。我觉得复用相同的 DragonBonesData 似乎不太好。因为这样一来，假设其中一个需要释放，我们执行
factory.removeDragonBonesData(dragonBonesData.name)
这样就会导致其它 armature 也跟着释放掉。
我这么理解对吗？