working on texture asset
cocos/cocos-engine pull request #2025
Opened 2017-10-08 05:31 UTC by jareguo

Re: cocos-creator/fireball#6082

Changes proposed in this pull request:
 * update texture in property
 * support scene deferred loading

@cocos-creator/engine-admins

2017-10-08 05:40 UTC, jareguo commented on cocos2d/core/sprites/CCSpriteFrame.js
> +                this._refreshTexture(this._texture);
如果 texture 还没加载，则强制 _refreshTexture，确保监听纹理的 load 事件

2017-10-08 05:42 UTC, jareguo commented on cocos2d/core/textures/CCTexture2D.js
> +        cc.loader.load({
如果 image 未加载，则手动加载并赋值

2017-10-09 06:07 UTC, pandamicro requested changes

2017-10-09 06:07 UTC, pandamicro commented on cocos2d/core/sprites/CCSpriteFrame.js
> +            texture.once("load", textureLoadedCallback);
这里应该避免重复注册监听器，有两个方法可以做到这点：

1. 将 textureLoadedCallback 函数拿出去，这里用 texture.on("load", textureLoadedCallback, this); 在回调中 off 即可，EventTarget 不会 add type callback target 完全一样的监听器（once 会创建新的匿名函数用来 off，所以无法避免重复添加）

2. 添加一个 loadEventObserved 标记位

2017-10-09 06:07 UTC, pandamicro commented on cocos2d/core/sprites/CCSpriteFrame.js
> +                this._refreshTexture(this._texture);
这里有可能造成重复监听，所以最好在 _refreshTexture 中做好保障

2017-10-09 06:07 UTC, pandamicro commented on cocos2d/core/textures/CCTexture2D.js
> +        cc.loader.load({
这里有可能正在加载过程中把？去 load 正在加载的资源虽然只会添加回调，但是感觉并没有必要，什么情况下 texture 创建出来但是没有启动加载呢？

2017-10-09 06:36 UTC, jareguo commented on cocos2d/core/textures/CCTexture2D.js
> +        cc.loader.load({
场景资源延迟加载的话，就会创建出 texture，但是没有加载实际 image。这里不太可能会重复加载，就算重复加载也没事，回调里有二次确认，如果已经 loaded 了就什么也不做

2017-10-09 06:37 UTC, jareguo commented on cocos2d/core/sprites/CCSpriteFrame.js
> +            texture.once("load", textureLoadedCallback);
好的

2017-10-09 17:15 UTC, jareguo commented on cocos2d/core/sprites/CCSpriteFrame.js
> +            texture.once("load", textureLoadedCallback);
没有添加一个 loadEventObserved 标记，改成在 https://github.com/cocos-creator/engine/pull/2031 中避免 once 重复监听

2017-10-09 17:16 UTC, jareguo commented on cocos2d/core/sprites/CCSpriteFrame.js
> +            texture.once("load", textureLoadedCallback);
textureLoadedCallback 函数已拿出去

2017-10-10 01:42 UTC, pandamicro approved these changes

2017-10-10 01:43 UTC, merged