fallback function if not support Function
cocos/cocos-engine pull request #2055
Opened 2017-10-19 09:34 UTC by 2youyou2

Re: cocos-creator/fireball#6476

Changes proposed in this pull request:
 * fallback function if not support Function

@cocos-creator/engine-admins

2017-10-19 09:35 UTC, 2youyou2 commented
我强制设置 `cc.supportJit = false;` 跑起来没发现什么问题

2017-10-19 09:36 UTC, 2youyou2 commented on cocos2d/core/platform/CCClass.js
> -    if (type === cc.Mat3 || type === cc.Mat4) {
cc.Mat3，cc.Mat4 没看到这两个类，删掉了

2017-10-19 14:00 UTC, jareguo commented on index.js
> +cc.supportJit = Function('') !== undefined;
麻烦改成 `cc.supportJit = typeof Function('') === 'function';`

2017-10-19 14:02 UTC, jareguo commented on index.js
> +    return typeof window[name] == 'object';
厉害了哥哥

2017-10-19 14:25 UTC, jareguo requested changes

2017-10-19 14:25 UTC, jareguo commented on cocos2d/core/node-activator.js
> +    c._objFlags|= IsOnLoadCalled;
麻烦加个空格

2017-10-19 14:25 UTC, jareguo commented on cocos2d/core/platform/CCClass.js
> +        function init () {
不要在构造函数里生成新的函数对象

2017-10-19 14:26 UTC, jareguo commented on cocos2d/core/platform/CCClass.js
> -    if (type === cc.Mat3 || type === cc.Mat4) {
这两个之前是给 engine-3d 用的，先删掉吧

2017-10-20 06:46 UTC, 2youyou2 commented on index.js
> +var _global = typeof window === 'undefined' ? global : window;
不知道为什么命令行启动 creator 第一次加载会找不到 window

2017-10-20 12:34 UTC, jareguo commented on index.js
> +var _global = typeof window === 'undefined' ? global : window;
那加个注释吧……

2017-10-23 07:17 UTC, merged