fixed RenderTarget
cocos/cocos-engine pull request #2099
Opened 2017-11-06 09:53 UTC by 2youyou2

Re: cocos-creator/fireball#6576

Changes proposed in this pull request:
 * fixed RenderTarget

@cocos-creator/engine-admins

2017-11-06 09:54 UTC, 2youyou2 commented on cocos2d/core/base-nodes/CCSGNodeBaseRenderCmd.js
> -        parentCmd = parentCmd || this.getParentRenderCmd();
parentCmd 会从外部传进来，不应该自己在里面获取，否则 RenderTexture 渲染单个节点的时候还会从父亲那计算矩阵

2017-11-06 09:55 UTC, 2youyou2 commented on cocos2d/render-texture/CCRenderTextureWebGLRenderCmd.js
> +    this._fullViewport = new cc.Rect(0,0, powW, powH);
应该用修改后的大小来做 viewport

2017-11-06 09:55 UTC, 2youyou2 commented on cocos2d/render-texture/CCRenderTextureWebGLRenderCmd.js
> +    cc.math.glMatrixMode(cc.math.KM_GL_PROJECTION);
应该计算到 projection 上

2017-11-06 11:27 UTC, pandamicro requested changes

2017-11-06 11:27 UTC, pandamicro commented on cocos2d/render-texture/CCRenderTextureWebGLRenderCmd.js
> +    cc.math.glMatrixMode(cc.math.KM_GL_PROJECTION);
还应该在改变 matrix mode 之后 load 单元矩阵

math.glLoadIdentity();

否则会乘到旧的 projection 上去

2017-11-06 12:47 UTC, 2youyou2 commented on cocos2d/render-texture/CCRenderTextureWebGLRenderCmd.js
> +    cc.math.glMatrixMode(cc.math.KM_GL_PROJECTION);
这个就是要乘到旧的矩阵上的啊，这是一个缩放比例的矩阵

2017-11-06 12:49 UTC, pandamicro commented on cocos2d/render-texture/CCRenderTextureWebGLRenderCmd.js
> +    cc.math.glMatrixMode(cc.math.KM_GL_PROJECTION);
那没看到恢复的逻辑啊，PROJECTION matrix 之后不就错了？

2017-11-07 02:28 UTC, 2youyou2 commented on cocos2d/render-texture/CCRenderTextureWebGLRenderCmd.js
> +    cc.math.glMatrixMode(cc.math.KM_GL_PROJECTION);
恢复的逻辑之前就有的，在 end 里面(这不是你自己写的代码么。。)

2017-11-15 02:30 UTC, pandamicro approved these changes

2017-11-15 02:30 UTC, merged