gradually remove eventManager and inputManager for fireball/issues/6240
cocos/cocos-engine pull request #2112
Opened 2017-11-15 09:03 UTC by knoxHuang

Re: cocos-creator/fireball#6240

Changelog:
 *  添加 eventManager and inputManager warn tips
 *  并移除 cc.eventManager 和 cc.inputManager 都是使用 require 的方式进行

2017-11-15 11:51 UTC, jareguo requested changes

2017-11-15 11:51 UTC, jareguo commented on cocos2d/core/event-manager/CCEventManager.js
> +    eventManager = require('./CCEventManagerImpl');
要不把这段判断的代码放在 event-manager/index.js，其它模块直接 var eventManager = require('../event-manager'); 即可
然后就不需要单独一个 Impl 文件了

2017-11-15 11:51 UTC, jareguo commented on cocos2d/core/event-manager/CCSystemEvent.js
> +var inputManger =require('../platform/CCInputManager');
注意编码规范

2017-11-15 11:51 UTC, jareguo commented on cocos2d/core/event-manager/CCEventManagerImpl.js
> +    cc.warnID(1405, 'cc.eventManager', 'cc.systemEvent');
cc.systemEvent -> cc.EventTarget or cc.systemEvent

2017-11-15 11:51 UTC, jareguo commented on cocos2d/core/event-manager/CCEventManagerImpl.js
> +cc.eventManager = module.exports = eventManager;
不再需要给 cc.eventManager 赋值了吧？cc.inputManager 也是一样

2017-11-16 01:24 UTC, knoxHuang commented on cocos2d/core/event-manager/CCEventManagerImpl.js
> +cc.eventManager = module.exports = eventManager;
为什么不给？这个不是 2.0 才移除的吗？用户还是可以用的

2017-11-16 02:36 UTC, jareguo commented on cocos2d/core/event-manager/CCEventManagerImpl.js
> +cc.eventManager = module.exports = eventManager;
是可以用啊，你不是已经定义了一个 getter 了吗

2017-11-17 03:08 UTC, pandamicro requested changes

2017-11-17 03:08 UTC, pandamicro commented on cocos2d/core/videoplayer/CCSGVideoPlayer.js
> +var eventManager = require('../event-manager/CCEventManager');
require 都放在开头

2017-11-17 03:08 UTC, pandamicro commented on cocos2d/core/platform/CCInputManager.js
> +    cc.warnID(1405, 'cc.inputManager', 'cc.EventTarget or cc.systemEvent');
没有看到 debugInfo 的 1405 是什么信息，另外，inputManager 是没有替代的，用户以前也用不到这个

2017-11-17 03:08 UTC, pandamicro commented on cocos2d/core/event-manager/CCEventManager.js
> +    eventManager = require('./CCEventManagerImpl');
嗯，这样更好些，改变文件会让记录更难跟踪

2017-11-17 03:30 UTC, jareguo approved these changes

2017-11-17 03:33 UTC, jareguo commented on cocos2d/core/platform/CCInputManager.js
> +    cc.warnID(1405, 'cc.inputManager', 'cc.EventTarget or cc.systemEvent');
![image](https://user-images.githubusercontent.com/1503156/32928018-e0e9675c-cb8a-11e7-876e-58eb67ed32cc.png)
这个记得要做 @knoxHuang

2017-11-17 03:34 UTC, knoxHuang commented on cocos2d/core/platform/CCInputManager.js
> +    cc.warnID(1405, 'cc.inputManager', 'cc.EventTarget or cc.systemEvent');
做了啊，你看看 systemEvent

2017-11-17 03:37 UTC, knoxHuang commented on cocos2d/core/platform/CCInputManager.js
> +    cc.warnID(1405, 'cc.inputManager', 'cc.EventTarget or cc.systemEvent');
"1405": "The '%s' will be removed in v2.0, please use '%s' instead. \uD83D\uDE30",

2017-11-17 03:38 UTC, knoxHuang commented on cocos2d/core/platform/CCInputManager.js
> +    cc.warnID(1405, 'cc.inputManager', 'cc.EventTarget or cc.systemEvent');
如果没替代的就不加警告？还是单独做 setAccelerometerEnabled 的警告？

2017-11-17 04:06 UTC, pandamicro commented on cocos2d/core/platform/CCInputManager.js
> +    cc.warnID(1405, 'cc.inputManager', 'cc.EventTarget or cc.systemEvent');
嗯，单独做 API 的警告

2017-11-17 06:56 UTC, jareguo commented on cocos2d/core/platform/CCInputManager.js
> +    return function (interval) {
干嘛不直接 return cc.systemEvent.setAccelerometerInterval

2017-11-17 06:56 UTC, jareguo commented on cocos2d/core/platform/CCInputManager.js
>      return inputManager;
你这个 get 显得毫无意义啊

2017-11-17 06:57 UTC, knoxHuang commented on cocos2d/core/platform/CCInputManager.js
>      return inputManager;
为了用户用 cc.inputManager 能调用得到

2017-11-17 07:15 UTC, pandamicro commented on cocos2d/core/platform/CCInputManager.js
>      return inputManager;
不需要啊，就不让用啊

2017-11-17 07:17 UTC, knoxHuang commented on cocos2d/core/platform/CCInputManager.js
>      return inputManager;
那你告诉我如果不写， js.get(cc, 'inputManager', function () {})，要怎么写，才能让用户调用 cc.inputManager.setAccelerometerEnabled 报警告？

2017-11-17 07:19 UTC, pandamicro commented on cocos2d/core/platform/CCInputManager.js
>      return inputManager;
还真是，我觉得直接去掉吧，那两个函数的警告也不要了，基本没有人用 accelerometer 功能，有的话，看文档就是了

2017-11-17 07:20 UTC, knoxHuang commented on cocos2d/core/platform/CCInputManager.js
>      return inputManager;
不行吧，只要是有重力的，都要开启，不然会被吐槽的，需要先警告到 2.0 然后在去掉比较好一点

2017-11-30 03:55 UTC, pandamicro approved these changes

2017-11-30 03:56 UTC, merged