remove error info from the engine release for fireball/issues/6721
cocos/cocos-engine pull request #2189
Opened 2017-12-15 09:22 UTC by knoxHuang

Re: cocos-creator/fireball#6721

Changelog:
 * 从引擎发布版中剔除异常报错信息

> Makes sure these boxes are checked before submitting your PR - thank you!
>
- [ ] If your pull request has gone "stale", you should **rebase** your work on top of the latest version of the upstream branch.
- [ ] If your commit history is full of small, unimportant commits (such as "fix pep8" or "update tests"), **squash** your commits down to a few, or one, discreet changesets before submitting a pull request.
- To official teams:
  - [ ] Check that your javascript is following our [style guide](https://github.com/cocos-creator/fireball/blob/dev/.github/CONTRIBUTING.md) and end files with a newline
  - [ ] Document new code with comments in source code based on [API Docs](https://github.com/cocos-creator/fireball#api-docs)
  - [ ] Make sure any runtime log information in `cc.log` , `cc.error`, `cc.warn` or `cc.assert` has been moved into `DebugInfos.js` with an ID

2017-12-15 17:34 UTC, jareguo requested changes

2017-12-15 17:34 UTC, jareguo commented on DebugInfos.js
> +        "1102": "Please load the resource first : %s", // loadConfigFile
1102 和 1101 重复

2017-12-15 17:34 UTC, jareguo commented on DebugInfos.js
> +        "7237": "_ccsg.TMXLayer.getTileAt(): pos should be non-null",//CCSGTMXLayer getTileAt
上面两条重复了

2017-12-15 17:34 UTC, jareguo commented on DebugInfos.js
> +            return cc._LogInfos[id].concat(argsArr);
别忘了 cc.js.formatStr 啊操

2017-12-15 17:35 UTC, jareguo commented
这个新的 format 接口未能和旧接口很好的关联在一起，而且定义两遍 errorMapUrl 你能忍？

建议定义两个新的 _LogInfos 接口

```js
function raw (id, type) {
    return CC_DEBUG ? cc._LogInfos[id] : `${type} ${id}, please go to ${errorMapUrl}#${id} to see details.`;   // 引擎可以用 template string
}

function format (msg, argsArray) {
    return CC_DEBUG ? cc.js.formatStr.apply(null, [msg].concat(argsArray)) : msg + ' Arguments: ' + argsArray.join(', ');
}
```

原先 genLogFunc 内部实现就可以简化为

```js
        'use strict';   // 不可省略
        var msg = cc._LogInfos.raw(id, type);
        if (arguments.length === 1) {
            func(msg);
        }
        else if (arguments.length === 2) {    // 新增分支，用于优化性能
            func(CC_DEBUG ? cc.js.formatStr(msg, arguments[1]) : msg + ' Arguments: ' + arguments[1]);
        }
        else {
            func(cc._LogInfos.format(msg, cc.js.shiftArguments.apply(null, arguments)));
        }
```

所以原来调用 cc._LogInfos.format 的地方要改成调用 cc._LogInfos.e (这个名字来自 `catch (e)`)，e 的实现只需要依赖 format

```
function e () {
        var msg = raw(arguments[0], 'ERROR');   // type 大写，方便和 errorID 区分
        if (arguments.length === 1) {
            return msg;
        }
        else {
            return format(msg, cc.js.shiftArguments.apply(null, arguments)); 
        }
}
```

这样虽然代码量可能省不了多少，但是可读性会好一些。

2017-12-15 17:39 UTC, jareguo commented
上面的方法我没测试过，你测看看

2017-12-18 03:03 UTC, jareguo commented on DebugInfos.js
> +        return false ? cc._LogInfos[id] : `${type} ${id}, please go to ${errorMapUrl}#${id} to see details.`;
false？

2017-12-18 03:04 UTC, knoxHuang commented on DebugInfos.js
> +        return false ? cc._LogInfos[id] : `${type} ${id}, please go to ${errorMapUrl}#${id} to see details.`;
无视，我提错了

2017-12-18 03:05 UTC, jareguo approved these changes

2017-12-18 03:11 UTC, knoxHuang commented
好了

2017-12-18 03:15 UTC, jareguo requested changes

2017-12-18 03:15 UTC, jareguo commented on cocos2d/core/components/CCRendererInSG.js
> +            throw new Error(cc._LogInfos.e(1636));
麻烦把这个报错去掉，这个是调试用的，本来就不会进入到非 CC_DEBUG 版本

2017-12-18 03:26 UTC, jareguo approved these changes

2017-12-21 02:01 UTC, merged