fix getWinSizeInPixels value for fireball/issues/6717
cocos/cocos-engine pull request #2193
Opened 2017-12-18 06:51 UTC by knoxHuang

Re: cocos-creator/fireball#6717

Changelog:
 * 修正 getWinSizeInPixels 数值

@pandamicro

2017-12-18 07:01 UTC, jareguo commented
原生平台需要改吗？

2017-12-18 08:08 UTC, knoxHuang commented
https://github.com/cocos-creator/cocos2d-x-lite/pull/1035 改了但是看他们觉得是否 OK

2017-12-19 07:33 UTC, dumganhar commented
他们。。。

2017-12-19 07:38 UTC, jareguo requested changes

2017-12-19 07:38 UTC, jareguo commented on cocos2d/core/CCDirector.js
> +        return cc.size(this._winSizeInPoints.width * cc.view.getScaleX(), this._winSizeInPoints.height * cc.view.getScaleY());
这里会不会有点舍近求远了？窗口像素，从设计分辨率 * 缩放比例去算，很奇怪啊。本身缩放比例就是根据窗口像素算出来的吧？应该能直接拿到窗口像素才对。

2017-12-19 07:44 UTC, dumganhar commented
@knoxHuang ，“他们”否决了lite的提交。具体看我的comment。

2017-12-19 07:45 UTC, dumganhar commented on cocos2d/core/CCDirector.js
> +        return cc.size(this._winSizeInPoints.width * cc.view.getScaleX(), this._winSizeInPoints.height * cc.view.getScaleY());
@jareguo ,看我lite仓库的回复吧。
这里这样改是有问题的。

2017-12-19 07:53 UTC, jareguo commented
那就麻烦 @knoxHuang 把这个 API 注释补充下吧。这里要澄清一下像素指的是资源分辨率。如果要获取屏幕物理分辨率，需要用 cc.view.getFrameSize()

2017-12-19 08:04 UTC, knoxHuang commented
那我就先补充 API 吧，等 panda 2.0 渲染出来再修改

2017-12-19 08:29 UTC, jareguo approved these changes

2017-12-19 08:52 UTC, pandamicro commented on cocos2d/core/CCDirector.js
> +        return cc.size(this._winSizeInPoints.width * cc.view.getScaleX(), this._winSizeInPoints.height * cc.view.getScaleY());
我解释一下 creator 中建议这样修改的原因，在 Creator 中不支持 content scale factor，所以可以将这个 API 的实现和 API 名统一起来，而在 -x 中，建华也解释了历史的原因。

既然现在顾及 web 和 native 兼容的问题，我的建议是在 Creator 中直接把这个 API deprecated 掉，因为这个 API 的 native 实现在现阶段无法跟 API 名统一，只有 web 修改，又会造成平台间的差异。而这个 API 的期望功能可以用别的方式来获取到：

winSize.width * cc.view.getScaleX()

所以并不是必要的，在未来的 2.0 中，director 来提供类似的 API 我觉得都是错误的，director 不管理 camera 也不管理 view，它只是负责驱动主循环。

2017-12-19 08:59 UTC, jareguo commented on cocos2d/core/CCDirector.js
> +        return cc.size(this._winSizeInPoints.width * cc.view.getScaleX(), this._winSizeInPoints.height * cc.view.getScaleY());
同意

2017-12-21 01:55 UTC, pandamicro commented
@knoxHuang 麻烦在 API 上加一个 @deprecated

2017-12-21 02:13 UTC, merged