Delete  the calls for object.retain() and object.release()
cocos/cocos-engine pull request #2218
Opened 2017-12-27 10:39 UTC by cyy641278529

2017-12-28 01:37 UTC, knoxHuang commented
@pandamicro @jareguo 你们看测试用例需不需要移除吧，之前修改的只改单元测，-x 移植过来的测试都没改过

2017-12-28 01:43 UTC, jareguo commented
测试用例不用移除了，2.0 开始那些测试用例就全废掉了

2017-12-28 02:41 UTC, jareguo requested changes

2017-12-28 02:41 UTC, jareguo commented on cocos2d/core/CCNode.js
> -            if (!cc.macro.ENABLE_GC_FOR_NATIVE_OBJECTS) {
@pandamicro ENABLE_GC_FOR_NATIVE_OBJECTS 的所有相关代码是不是也应该删掉？

2017-12-28 02:41 UTC, jareguo commented on cocos2d/core/CCNode.js
> -            this._retainedActions.push(action);
_retainedActions 其它相关代码也应该删掉

2018-01-02 02:39 UTC, pandamicro submitted a review, later dismissed

2018-01-02 02:42 UTC, pandamicro commented on cocos2d/core/CCNode.js
> -            if (!cc.macro.ENABLE_GC_FOR_NATIVE_OBJECTS) {
if (!cc.macro.ENABLE_GC_FOR_NATIVE_OBJECTS) 的可以删掉
if (cc.macro.ENABLE_GC_FOR_NATIVE_OBJECTS) 的要保留

2018-01-04 09:10 UTC, pandamicro approved these changes

2018-01-06 13:38 UTC, merged