Adds empty implementation of cc.Device.getBatteryLevel/getNetworkType for web.
cocos/cocos-engine pull request #2263
Opened 2018-01-17 05:40 UTC by dumganhar

2018-01-17 05:52 UTC, jareguo requested changes

2018-01-17 05:52 UTC, jareguo commented on cocos2d/core/platform/CCDevice.js
> +var cc = cc || {};
不用定义 cc~

2018-01-17 05:52 UTC, jareguo commented on cocos2d/core/platform/CCDevice.js
> +cc.NetworkType = {
加下注释，以便生成 API 文档
```
/**
 * !#en
 * blabla
 * !#zh
 * 巴拉巴拉
 *
 * @enum NetworkType
 */
```

2018-01-17 05:52 UTC, jareguo commented on cocos2d/core/platform/CCDevice.js
> +    NONE: 0,
```
/**
 * !#en
 * blabla
 * !#zh
 * 巴拉巴拉
 *
 * @property {Number} NONE
 */
```

2018-01-17 05:52 UTC, jareguo commented on cocos2d/core/platform/CCDevice.js
> +cc.Device = {
```
/**
 * !#en
 * blabla
 * !#zh
 * 巴拉巴拉
 *
 * @class Device
 */
```

2018-01-17 05:52 UTC, jareguo commented on cocos2d/core/platform/CCDevice.js
> +    getBatteryLevel: function() {
```
/**
 * !#en
 * blabla
 * !#zh
 * 巴拉巴拉
 *
 * @method getBatteryLevel
 * @return {Number} - The blabla
 * @static
 */
```

2018-01-17 05:52 UTC, jareguo commented on cocos2d/core/platform/CCDevice.js
> +    getNetworkType: function() {
```
/**
 * !#en
 * blabla
 * !#zh
 * 巴拉巴拉
 *
 * @method getNetworkType
 * @return {NetworkType} - The blabla
 * @static
 */
```

2018-01-17 06:27 UTC, jareguo requested changes

2018-01-17 06:27 UTC, jareguo commented on cocos2d/core/platform/CCDevice.js
> +     * 获取当前设备的电池电量
麻烦注明下，如果电量无法获取，默认将返回 1

2018-01-17 06:27 UTC, jareguo commented on cocos2d/core/platform/CCDevice.js
> +     * 获取当前设备的网络类型
麻烦注明下，如果网络类型无法获取，默认将返回 cc.NetworkType.LAN

2018-01-17 06:45 UTC, pandamicro requested changes

2018-01-17 06:45 UTC, pandamicro commented on cocos2d/core/platform/CCDevice.js
> +cc.NetworkType = {
枚举类型不要放在 cc 命名空间下，放在直属的类下面，作为 static 对象

device.NetworkType

2018-01-17 06:45 UTC, pandamicro commented on cocos2d/core/platform/CCDevice.js
> +cc.Device = {
Device 不是一个 class，是一个对象，不应该使用类命名法。同时，我们也希望尽可能减少 cc 下面的变量，所以建议作为

cc.sys.device 来引入

2018-01-17 06:47 UTC, jareguo commented on cocos2d/core/platform/CCDevice.js
> +cc.Device = {
是一个对象的话，枚举又在对象下面，很奇怪，变成 `cc.sys.device.NetworkType` ??

2018-01-17 06:49 UTC, dumganhar commented on cocos2d/core/platform/CCDevice.js
> +cc.Device = {
cc.sys.device 太奇怪了吧。 那还不如放在 cc.sys 下。
哎，提交一个空实现代码咋这么繁琐嘞。

2018-01-17 06:49 UTC, jareguo commented on cocos2d/core/platform/CCDevice.js
> +cc.Device = {
用户在项目里变成要写
`if (cc.sys.device.getNetworkType() === cc.sys.device.NetworkType.LAN)`
感觉有点难看啊

2018-01-17 06:51 UTC, dumganhar commented
二位大佬，给个定案吧。
Native 上的绑定 是直接绑定 Device 这个c++类，绑定代码生成后就是 cc.Device.getXXX 这样用。
至于 web 或者 engine 层想绑定成什么样子，可以wrap一下。

2018-01-17 06:53 UTC, jareguo commented
华彬定吧，最终怎样我都行，API 文档记得同步就好

2018-01-17 08:35 UTC, pandamicro commented
规则就是这样啊，尽可能减少 cc 下的一级模块，那么适合放置 device 的就是 sys 下面，要么就直接把函数放在 cc.sys 下，要么就用 cc.sys.device

2018-01-17 08:36 UTC, pandamicro commented on cocos2d/core/platform/CCDevice.js
> +cc.Device = {
没什么难看的啊

2018-01-22 10:02 UTC, pandamicro commented
@dumganhar 改一下白

2018-01-29 06:14 UTC, dumganhar commented
DONE

2018-01-29 06:20 UTC, pandamicro commented on cocos2d/core/platform/CCSys.js
> +    WWAN: 2
要不要加一个 UNKNOWN ？web 上直接返回 LAN 也不对，毕竟大多数情况下 mobile web 是 WWAN

2018-01-29 06:27 UTC, dumganhar commented on cocos2d/core/platform/CCSys.js
> +    WWAN: 2
已经有 NONE 了。不可能有网络但是你UNKNOWN，要么就是没网络，是NONE

2018-01-29 06:35 UTC, pandamicro commented on cocos2d/core/platform/CCSys.js
> +    WWAN: 2
为啥？Web 获取不了不就是 UNKNOWN，有网络，但是不知道是啥网络的情况不是很正常么？

2018-01-29 06:53 UTC, dumganhar commented on cocos2d/core/platform/CCSys.js
> +    WWAN: 2
什么情况是：有网络，但是不知道是啥的情况？ 如果是这样，那么就是你接口漏考虑类型了。

2018-01-29 07:22 UTC, pandamicro commented on cocos2d/core/platform/CCSys.js
> +    WWAN: 2
不是啊，你虽然下面写了 TODO，但是 WEB 环境就是无法获取网络环境的，浏览器根本没有这样的接口。。。这就是一个根本不可知的状态，不适用于目前的 NONE，LAN，WWAN

2018-01-29 07:42 UTC, jareguo commented on cocos2d/core/platform/CCSys.js
> +    WWAN: 2
我们对标的某个引擎，他们在 unknown 的情况下，返回的就是 LAN 的。这里我建议不要给用户增加选择困难了。我举个例子，如果你有 unknown，我需要这么写代码：
```
if (type == unknown) {
  if (cc.sys.isBrowser) {
    // maybe wifi or 4G
  }
  else {
    if (CC_JSB) {
      // desktop, should be wifi
    }
    else {
      if (cc.sys.isMobile) {
         // wechat game???
      }
      else {
        // wtf ?
      }
    }
  }
}
```

如果你没有提供 unknown，后果是什么呢？后果是 4G 环境下，引擎会以为是 LAN，白白消耗流量。但是玩家用浏览器玩游戏，本来就是预期会消耗流量的，这个不用担心。而如果你用 Windows / Mac 玩游戏，一般都是内网，所以引擎返回 LAN 本来就是对的。

2018-01-29 07:45 UTC, jareguo commented on cocos2d/core/platform/CCSys.js
> +    WWAN: 2
> 什么情况是：有网络，但是不知道是啥的情况？ 如果是这样，那么就是你接口漏考虑类型了。

除了 iOS/Android 原生平台，都是不知道啥的情况。这种时候默认返回 LAN 就行了。理由同上。

2018-01-29 07:57 UTC, pandamicro commented on cocos2d/core/platform/CCSys.js
> +    WWAN: 2
你这个理论我也是服，把文档写清楚吧，用户要是较真起来我就甩锅给你们

2018-01-29 08:00 UTC, jareguo commented on cocos2d/core/platform/CCSys.js
> +    WWAN: 2
文档有写清楚，你看下 getNetworkType 的 API

2018-01-29 08:01 UTC, pandamicro approved these changes

2018-01-29 08:11 UTC, merged