add destroy for fireball/issues/6888
cocos/cocos-engine pull request #2294
Opened 2018-01-30 07:45 UTC by knoxHuang

Re: cocos-creator/fireball#6888

Changelog:
 * 当 audio stop 的时候，destroy 掉 _element（InnerAudioContext）避免内存泄漏

2018-01-30 08:09 UTC, jareguo commented on cocos2d/audio/CCAudio.js
> +        if (cc.sys.platform === cc.sys.WECHAT_GAME) {
不是有宏吗

2018-01-30 08:09 UTC, pandamicro requested changes

2018-01-30 08:09 UTC, pandamicro commented on cocos2d/audio/CCAudioEngine.js
> +        audio.destroy();
为啥还有这个 destroy，应该在 loader 中做 uncache 操作

2018-01-30 08:10 UTC, pandamicro commented
验证有效之后再合并

2018-02-11 07:42 UTC, knoxHuang commented
@pandamicro 你在看看修改的

2018-02-11 13:26 UTC, pandamicro commented
还缺少 CCLoader 的 release 中的 uncache / destroy 逻辑

2018-02-22 07:47 UTC, pandamicro approved these changes

2018-02-22 07:48 UTC, pandamicro requested changes

2018-02-22 07:48 UTC, pandamicro commented on cocos2d/core/load-pipeline/CCLoader.js
> +            if (AUDIO_TYPES.indexOf(item.type) !== -1) {
应该放在 asset instanceof cc.Asset 的判断之后，未来 Audio 和 Texture 都应该直接通过 asset.release 来释放

2018-02-22 13:40 UTC, pandamicro approved these changes

2018-02-22 13:40 UTC, merged