Next
cocos/cocos-engine pull request #2314
Opened 2018-02-07 03:53 UTC by 2youyou2

Re: cocos-creator/fireball#6908

Changelog:
 * support camera

2018-02-07 10:28 UTC, pandamicro commented
需要适配 https://github.com/cocos-creator/engine/pull/2318

2018-02-08 10:10 UTC, 2youyou2 commented on cocos2d/core/camera/CCCamera.js
> +        this.cullingMask = 1 << _static_culling_mask++;
目前先这样，下个版本希望改成 unity 这样

![image](https://user-images.githubusercontent.com/1862402/35967288-6159d76c-0cfb-11e8-92f9-4997cc3f0f8f.png)

2018-02-08 10:38 UTC, 2youyou2 commented on cocos2d/core/camera/CCCamera.js
> +        out = out || cc.v2();
还没算对，先别合

2018-02-08 16:58 UTC, pandamicro requested changes

2018-02-08 16:58 UTC, pandamicro commented on cocos2d/core/CCNode.js
> +        this._viewMask = 1;
_viewID 改为 _cullingMask，_viewMask 改为 _inheritMask，表示一个是拥有 culling mask，一个是继承自父节点的 culling mask，现在用 viewID 太影响阅读了，很容易误以为是 view 的唯一 id

2018-02-08 16:58 UTC, pandamicro commented on cocos2d/core/renderer/render-component-walker.js
> +    viewID: -1,
_cullingMask

2018-02-08 16:58 UTC, pandamicro commented on cocos2d/core/camera/CCCamera.js
> +        cameras: _cameras
cameras 只在 editor 中的话，浏览器运行时 hitTest 中对 cc.Camera.cameras 的访问有问题把？

2018-02-08 16:58 UTC, pandamicro commented on cocos2d/core/renderer/render-component-walker.js
> +            node._viewMask = this._curCameraNode._viewID;
为什么不干脆在 camera.addTarget 的时候遍历 target 的子节点呢？可以用

```
target.walk(function (node) {
    node._inheritMask = target._cullingMask;
});
```

这样可以避免每帧都做重复的操作

2018-02-08 16:58 UTC, pandamicro commented on cocos2d/core/CCNode.js
> +            testPt = Camera.cameras[this._viewMask].getCameraToWorldPoint(point);
cameras 是数组，一个一个 camera push 进去的，我不理解为什么 Camera.cameras[viewMask] 可以正确获取到 camera。同时 cameras 也不能是一个对象，因为不同 view 的 culling mask 可能是一样的，view 倒是有一个唯一标示 _id，你可以考虑用

2018-02-09 01:30 UTC, 2youyou2 commented on cocos2d/core/renderer/render-component-walker.js
> +            node._viewMask = this._curCameraNode._viewID;
target 如果动态添加了子节点，新加的子节点就不能正确设置了

2018-02-09 01:30 UTC, 2youyou2 commented on cocos2d/core/CCNode.js
> +            testPt = Camera.cameras[this._viewMask].getCameraToWorldPoint(point);
这个是我的修改还没提交

2018-02-09 01:32 UTC, 2youyou2 commented on cocos2d/core/camera/CCCamera.js
> +        cameras: _cameras
你看错了。。。这个是在 statics 里面的，editor 是上一分段的代码

2018-02-09 01:59 UTC, pandamicro commented on cocos2d/core/camera/CCCamera.js
> +        cameras: _cameras
🤣

2018-02-09 01:59 UTC, pandamicro commented on cocos2d/core/renderer/render-component-walker.js
> +            node._viewMask = this._curCameraNode._viewID;
那建议去掉 viewMask (inheritMask)，在 batchQueue 逻辑中，对一个全局堆栈 push culling mask，遍历到 toPostHandle 的时候 pop，中间全部用栈顶的 culling mask 就好，这样可以省去一个 node 属性

2018-02-09 03:43 UTC, pandamicro approved these changes

2018-02-09 03:45 UTC, merged