Initial fix node Hierarchy change when it is deactivating issue
cocos/cocos-engine pull request #2374
Opened 2018-02-27 10:42 UTC by CocosAss

Re: #2359

Changelog:
 1.add a new judgement in base-node.js setParent function 
2.add a new errorID number //Game 3000 part '3821'

2018-02-27 10:43 UTC, CocosAss commented
only add a simply judgement on the setParent function and did not pause the whole engine.

2018-02-27 11:53 UTC, pandamicro requested changes

2018-02-27 11:53 UTC, pandamicro commented on cocos2d/core/utils/base-node.js
> +        if (CC_DEBUG && !this._activeInHierarchy){
应该使用 _objFlags 来进行判断

2018-02-28 02:00 UTC, CocosAss commented
add a new variable named Deactivating in base-node.js in order to judge the node._objFlags

2018-02-28 02:31 UTC, CocosAss commented
the new change remove the return part from the judgement it will make another error '_activeHierarchy' undefinded

2018-02-28 02:55 UTC, pandamicro commented on cocos2d/core/utils/base-node.js
> +        if (CC_DEBUG && (this._objFlags & Deactivating)) {
你可以想一下，在做 setParent 的时候，改变了 children 数组内容的是哪些对象？是 this 吗？

2018-02-28 03:08 UTC, CocosAss commented on cocos2d/core/utils/base-node.js
> +        if (CC_DEBUG && (this._objFlags & Deactivating)) {
那我就还是在昨天那个循环的位置进行修改,循环内容增加对数组变化的处理

2018-02-28 03:10 UTC, CocosAss commented on cocos2d/core/utils/base-node.js
> +        if (CC_DEBUG && (this._objFlags & Deactivating)) {
Deactivating判断下面的的数组变化的部分还是要保留,jare哥说要保证原先内容的正常运行,只是在需要报错的地方给个报错,那这样讲error部分的需要修改的部分就是从循环长度那边做了

2018-02-28 03:18 UTC, pandamicro commented on cocos2d/core/utils/base-node.js
> +        if (CC_DEBUG && (this._objFlags & Deactivating)) {
不是这个意思，setParent 是将 this 从 old parent 的 children 列表移除，再加入到 value（new parent）的 children 列表中，你这里应该判断的是 old 和 new parent 是否在 desactivating

2018-02-28 03:58 UTC, CocosAss commented
change two judgement in setParent function in order to get the error message

2018-02-28 07:42 UTC, jareguo commented on cocos2d/core/utils/base-node.js
> +        }
上面两个 if 合并成一个吧。既然情况这么复杂，请把单元测试加上。单元测试里 spy 一下 cc.errorID

2018-02-28 07:55 UTC, pandamicro commented on cocos2d/core/utils/base-node.js
> +        if (CC_DEBUG && (oldParent._objFlags & Deactivating)) {
我又想了一下，判断 this._objFlags 已经包含了对 oldParent 的判断了，因为 this._objFlags 一定是通过 deactivateNodeRecursively 传递过来的，所以不需要判断 oldParent，保留 this 和 value 的判断即可

2018-02-28 07:58 UTC, CocosAss commented on cocos2d/core/utils/base-node.js
> +        if (CC_DEBUG && (oldParent._objFlags & Deactivating)) {
这里的this,指的是最后一种单独调节当前node 的情况啊,如果是从oldParent传递过来的,会检测不到这种情况

2018-02-28 08:00 UTC, pandamicro commented on cocos2d/core/utils/base-node.js
> +        if (CC_DEBUG && (oldParent._objFlags & Deactivating)) {
oldParent 传递过来的时候，this._objFlags & Deactivating 也一定是 true

2018-02-28 08:02 UTC, jareguo commented on cocos2d/core/utils/base-node.js
> +        if (CC_DEBUG && (oldParent._objFlags & Deactivating)) {
来来来，改成测试驱动开发

2018-02-28 08:15 UTC, jareguo commented on cocos2d/core/utils/base-node.js
> +        if (CC_DEBUG && (oldParent._objFlags & Deactivating)) {
搜一下 "disable component during onEnable"，加一个 "change parent during onDisable"

2018-02-28 10:29 UTC, pandamicro approved these changes

2018-02-28 10:30 UTC, pandamicro commented
👍 把单元测试例补上就可以了

2018-02-28 10:30 UTC, CocosAss commented
oh yeah ~ thx

2018-03-01 10:11 UTC, CocosAss commented
测试了三个情况:
1.当自身节点处于deactivating 状态时不能改变自身层级关系
2.不能更改节点层级关系,以自身正处于deactivating状态的节点为父节点
3.传递关系下,父节点处于deactivating 不允许子节点改变层级关系.

2018-03-01 10:25 UTC, pandamicro requested changes

2018-03-01 10:25 UTC, pandamicro commented on test/qunit/unit-es5/test-component-scheduler.js
> +    cc.errorID.once('Should not change owned Hierarchy during deactivating');
Should report error when changing target node's parent during its deactivation

2018-03-01 10:25 UTC, pandamicro commented on test/qunit/unit-es5/test-component-scheduler.js
> +    cc.errorID.once('Should not change the others\' Hierarchy to any deactivating node');
Should report error when append new child to a target node during its deactivation

2018-03-01 10:25 UTC, pandamicro commented on test/qunit/unit-es5/test-component-scheduler.js
> +        child.parent = preNode;
应该是在 nodes1 deactivating 的过程中，在 testNode 的 comp.onDisable 中让 child.parent = nodes1。

现在这样测试的情况其实和第一种本质是一样

2018-03-01 10:26 UTC, jareguo commented
请增加一个测试例，父节点处于 deactivating 状态时，不允许通过 node.setSiblingIndex 修改子节点的排序

2018-03-01 10:28 UTC, CocosAss commented on test/qunit/unit-es5/test-component-scheduler.js
> +        child.parent = preNode;
emmm,可是两个情况中间有添加一个递归的因素啊,用户不了解咋办啊....?

2018-03-01 10:35 UTC, pandamicro commented on test/qunit/unit-es5/test-component-scheduler.js
> +        child.parent = preNode;
我建议你把第一个改成通过 node1.active = false 来触发，就够了

2018-03-01 10:40 UTC, CocosAss commented on test/qunit/unit-es5/test-component-scheduler.js
> +        child.parent = preNode;
修正,第一第二测试的时候声明内容为:
1.deactivating 状态下节点不允许更改node层级
2.deactivating 状态下的节点不允许更改为其他node的父节点
这样的话,更改的第三种测试内容和第二种本质上就是一样了

2018-03-02 03:26 UTC, pandamicro requested changes

2018-03-02 03:26 UTC, pandamicro commented on test/qunit/unit-es5/test-component-scheduler.js
> +    cc.errorID.once('Should not change owned Hierarchy during deactivating');
Should report error when changing target node's parent during its deactivation

2018-03-02 03:26 UTC, pandamicro commented on test/qunit/unit-es5/test-component-scheduler.js
> +    cc.errorID.once('Should not change the others\' Hierarchy to any deactivating node');
Should report error when append new child to a target node during its deactivation

2018-03-02 03:26 UTC, pandamicro commented on test/qunit/unit-es5/test-component-scheduler.js
> +    cc.errorID.once('Should not use setSilingIndex to change\' Hierarchy during deactivating');
Should report error when setting node's sibling index during its parent's deactivation

2018-03-02 03:55 UTC, pandamicro approved these changes

2018-03-02 03:56 UTC, merged

2018-03-02 03:57 UTC, pandamicro commented
Congrats for your first PR ~ 🎉