V1.8
cocos/cocos-engine pull request #2381
Opened 2018-02-28 10:56 UTC by umbrellaPP

Re: #2358

convert leteralMap into flatMap

2018-02-28 16:14 UTC, jareguo requested changes

2018-02-28 16:14 UTC, jareguo commented on cocos2d/audio/CCAudioEngine.js
> +var url2id = cc.js.createMap(true);
请在最上面 require 一下 JS，避免直接访问 cc.js。其它脚本也一样

2018-02-28 16:14 UTC, jareguo commented on cocos2d/core/collider/CCCollisionManager.js
> +            var world = collider.world = cc.js.createMap();
这里 world 只是用于声明对象，没有用作字典，就不用这么优化了。

2018-02-28 16:14 UTC, jareguo commented on cocos2d/core/event-manager/CCEventManager.js
> +        this._nodePriorityMap = cc.js.createMap();
这里可以传入一个 true。因为后面会有 delete 操作。需要 delete 的话提前强制设为字典的话就能够避免后续重建大字典。

2018-02-28 16:14 UTC, jareguo commented on cocos2d/core/load-pipeline/loading-items.js
> +var _queues = cc.js.createMap(true);
这个脚本上面已经 require JS 了，所以直接写 JS.createMap(true) 即可。其它脚本同理。

2018-02-28 16:14 UTC, jareguo commented on cocos2d/core/platform/CCClass.js
> +    options = options || cc.js.createMap(true);
这里 options 只是作为临时对象用问题不大。可以不改。

2018-02-28 16:14 UTC, jareguo commented on cocos2d/core/platform/CCScreen.js
> +        this._fn = cc.js.createMap(true);
这里 _fn 只是作为小型对象使用，可以不创建为字典，性能反而比较快

2018-02-28 16:14 UTC, jareguo commented on cocos2d/core/platform/CCSys.js
> +cc.sys = cc.js.createMap();
这里只是声明对象，可以不用改。

2018-02-28 16:14 UTC, jareguo commented on cocos2d/core/platform/deserialize.js
> +    options = options || cc.js.createMap(true);
同理，不改这里

2018-02-28 16:14 UTC, jareguo commented on cocos2d/core/platform/js.js
> +    var _nameToClass = cc.js.createMap();
这两行代码执行时，createMap 还没注册到 js 上吧？

2018-02-28 16:14 UTC, jareguo commented on cocos2d/core/platform/url.js
> +var _mounts = cc.js.createMap(true);
这里只是作为小型对象使用，就不改了吧，改了反而更慢

2018-02-28 16:14 UTC, jareguo commented on cocos2d/core/renderer/RendererWebGL.js
> +        this._extensions = this._extensions || cc.js.createMap();
同样是小型对象，不改

2018-02-28 16:14 UTC, jareguo commented on cocos2d/core/textures/CCTextureCache.js
> +        this._textures = cc.js.createMap();
同理，多传一个 true

2018-02-28 16:14 UTC, jareguo commented on cocos2d/core/textures/CCTextureCache.js
> +        this._textures = cc.js.createMap();
你搜一下 ": {}"，可能漏改了不少

2018-02-28 16:14 UTC, jareguo commented on cocos2d/core/videoplayer/CCSGVideoPlayer.js
> +        this._EventList = cc.js.createMap(true);
SG 节点的不改了，下同，避免冲突

2018-02-28 16:14 UTC, jareguo commented on cocos2d/kazmath/utility.js
> +cc.math = cc.math || cc.js.createMap();
同理，创建对象不改

2018-02-28 16:14 UTC, jareguo commented on cocos2d/particle/CCPNGReader.js
> +        this.transparency = cc.js.createMap(true);
同理，不改

2018-02-28 16:14 UTC, jareguo commented on cocos2d/particle/CCPNGReader.js
> +        this.text = cc.js.createMap(true);
同理，不改

2018-02-28 16:14 UTC, jareguo commented on cocos2d/shaders/CCGLProgram.js
> +        this._uniforms = cc.js.createMap(true);
_uniforms 是小型固定对象，不改

2018-02-28 16:14 UTC, jareguo commented on cocos2d/tilemap/CCSGTMXLayer.js
> +        this._spriteTiles = cc.js.createMap(true);
SG 不改了

2018-02-28 16:14 UTC, jareguo commented on extensions/anysdk/jsb_anysdk.js
> +var anysdk = anysdk || cc.js.createMap();
创建固定对象，不改了

2018-02-28 16:14 UTC, jareguo commented on extensions/spine/index.js
> +sp = CC_JSB ? sp : cc.js.createMap();
创建固定对象，不改了

2018-02-28 16:14 UTC, jareguo commented on extensions/ccpool/CCPool.js
> +        this._pool = cc.js.createMap(true);
这里元素数量有限，只增不减，不用传 true

2018-02-28 16:14 UTC, jareguo commented on gulp/util/utils.js
> +    var res = cc.js.createMap();
gulp 命令执行时是访问不到 cc 的，不用改这里

2018-02-28 16:14 UTC, jareguo commented on jsb/jsb-tex-sprite-frame.js
> +cc.textureCache._textures = cc.js.createMap();
下面有 delete 操作，应该传 true

2018-02-28 16:14 UTC, jareguo commented on jsb/jsb-audio.js
> +    this._eventList = cc.js.createMap(true);
元素数量有限，只增不减，这里还是不改了

2018-03-01 06:51 UTC, pandamicro commented
这个改动不建议在 1.8 做，会跟目前 2.0 分支造成很大的冲突，解决起来不好说会不会引入新 bug，在 2.0 上做会比较保险

2018-03-01 06:52 UTC, pandamicro commented
另外 PR 的命名需要注意一下，写有意义的 title

2018-03-01 06:54 UTC, jareguo commented
好吧，那就麻烦关闭这个 PR，重新在 2.0 上面做一次。不冲突的话是不会有 bug 的。

2018-03-01 06:56 UTC, jareguo commented
这里不单单是为了性能，主要也是要杜绝潜在的 bug。以前如果有 id 、类名什么的叫做 toString/toValue 什么的话时都会跪。

2018-03-01 06:59 UTC, closed without merging