2.0, 整理优化 literalMap 和 flatMap
cocos/cocos-engine pull request #2387
Opened 2018-03-01 09:46 UTC by umbrellaPP

Re: cocos-creator/fireball#

Changelog:
 *

2018-03-01 10:08 UTC, jareguo requested changes

2018-03-01 10:08 UTC, jareguo commented on cocos2d/actions/CCActionManager.js
> +
不要把代码添加到 license 上面，保持 license 在最开头

2018-03-01 10:08 UTC, jareguo commented on cocos2d/actions/CCActionManager.js
> +
你不应该重复定义 ctor，cc.ActionManager 本身已经是一个构造函数了。请检查一下你提交的差异，去掉不小心产生的改动。

2018-03-01 10:08 UTC, jareguo commented on cocos2d/core/CCScheduler.js
> +
请检查一下提交差异，不要增加无用的空行，也不要删掉有用的空行

2018-03-01 10:08 UTC, jareguo commented on cocos2d/core/platform/CCScreen.js
> +
请关掉 IDE 自动移除行尾空格的功能，把这些空格还原。
原则上，你改动到的代码，行尾空格随你处置。没改到的话这种大面积的格式化就不要了。

2018-03-02 13:10 UTC, jareguo commented on cocos2d/core/renderer/render-engine.js
> +      this._attr2el = JS.createMap(true);
这个不改吧，这里元素数量有限的话原来那样会更快。

2018-03-05 03:03 UTC, jareguo requested changes

2018-03-05 03:03 UTC, jareguo commented on jsb/jsb-tex-sprite-frame.js
> +cc.textureCache._textures = JS.createMap(true);
这里 JS 没定义吧

2018-03-05 03:20 UTC, umbrellaPP commented on jsb/jsb-tex-sprite-frame.js
> +cc.textureCache._textures = JS.createMap(true);
已经修复

2018-03-05 03:24 UTC, merged

2018-03-05 03:24 UTC, pandamicro commented
有问题啊。。。

2018-03-05 03:24 UTC, pandamicro commented on cocos2d/actions/CCActionManager.js
> +var JS = require('../core/platform/js');
js 是对象，请用小写，跟原始文件中的命名方式一致。

只有类名用大写开头，CONSTANT 用全大写加 _ 分隔单词。

其他的 JS 代码规范可以参考：

1. Airbnb: https://github.com/airbnb/javascript
2. Mozilla: https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Coding_Style
3. Google: https://google.github.io/styleguide/jsguide.html

2018-03-05 03:24 UTC, pandamicro commented on cocos2d/audio/CCAudioEngine.js
> +var url2id = JS.createMap(true);
没有看到 delete url2id[...] 的内容

2018-03-05 03:24 UTC, pandamicro commented on cocos2d/core/CCScheduler.js
> +var JS = require('./platform/js');
同上

2018-03-05 03:24 UTC, pandamicro commented on cocos2d/audio/CCAudioEngine.js
> +var JS = require('../core/platform/js');
同上

2018-03-05 03:24 UTC, pandamicro commented on cocos2d/core/load-pipeline/loading-items.js
>  var JS = require('../platform/js');
这里也改一下，改成小写命名

2018-03-05 03:24 UTC, pandamicro commented on cocos2d/core/load-pipeline/pack-downloader.js
> +var globalUnpackers = JS.createMap(true);
以上三个对象都没有看到有做 delete 操作

2018-03-05 03:24 UTC, pandamicro commented on cocos2d/core/platform/CCAssetLibrary.js
> +var _uuidToRawAsset = JS.createMap(true);
同样没有 delete 操作

2018-03-05 03:24 UTC, pandamicro commented on cocos2d/core/renderer/assemblers/spine-assembler.js
> +let _sharedMaterials = js.createMap();
没有必要

2018-03-05 03:24 UTC, pandamicro commented on cocos2d/core/renderer/render-engine.js
> + var JS = cc.js;
这个文件不要做任何改动

2018-03-05 03:24 UTC, pandamicro commented on jsb/jsb-tex-sprite-frame.js
> +cc.textureCache._textures = JS.createMap(true);
jsb 文件夹下的文件会失效，不需要做任何改动了

2018-03-05 03:31 UTC, jareguo commented on cocos2d/core/load-pipeline/loading-items.js
>  var JS = require('../platform/js');
这个 out of topic 了吧。类似的写法项目里有 50 多个，要再一起批量改吧

2018-03-05 03:31 UTC, umbrellaPP commented on cocos2d/core/load-pipeline/pack-downloader.js
> +var globalUnpackers = JS.createMap(true);
好的，我改下

2018-03-05 03:32 UTC, jareguo commented on cocos2d/core/load-pipeline/loading-items.js
>  var JS = require('../platform/js');
反而是用小写的 js，只有 10 多个……

2018-03-05 03:33 UTC, jareguo commented on cocos2d/core/load-pipeline/pack-downloader.js
> +var globalUnpackers = JS.createMap(true);
这些将来也是应该 delete 的。uuid 这种东西数量肯定超过 fast properties，所以用 hash mode 是更优的。

2018-03-05 03:38 UTC, pandamicro commented
@umbrellaPP 麻烦调整一下再重新提交一个 PR

2018-03-05 04:08 UTC, pandamicro commented on cocos2d/core/load-pipeline/loading-items.js
>  var JS = require('../platform/js');
因为这个 PR 里面将原本正确的 js 改成了大写，那就麻烦 @umbrellaPP 分成两个 PR 提交，先提交一个 PR 来修复没必要的 createMap 操作。再提交一个 PR 来修正大写 JS 改为小写 js

2018-03-05 04:09 UTC, pandamicro commented on cocos2d/core/load-pipeline/pack-downloader.js
> +var globalUnpackers = JS.createMap(true);
将来 delete 你是说将来的实现？unpacker 的 uuid 数量没那么多吧，我的理解是有多少个 packed json 就有多少个 global unpacker，如果是这样的话，数量并不大。至于 delete 操作，等添加了 delete 操作再使用 createMap 也不迟

2018-03-05 04:10 UTC, pandamicro commented on cocos2d/core/platform/CCAssetLibrary.js
> +var _uuidToRawAsset = JS.createMap(true);
这里的数量可能比较多，可以保留 createMap

2018-03-05 04:42 UTC, umbrellaPP commented on cocos2d/core/load-pipeline/loading-items.js
>  var JS = require('../platform/js');
好的