修复fnt 文件，字符串解析问题
cocos/cocos-engine pull request #2396
Opened 2018-03-05 03:48 UTC by umbrellaPP

Re: #2386 

Changelog:
 *

2018-03-05 06:19 UTC, pandamicro commented on cocos2d/core/label/CCSGLabel.js
> +            letterDefinition._v = parseInt(tempRect.y) + this._imageOffset.y;
u v 是以像素为单位？不是归一化的小数？

2018-03-05 06:21 UTC, PPpro commented on cocos2d/core/label/CCSGLabel.js
> +            letterDefinition._v = parseInt(tempRect.y) + this._imageOffset.y;
那我应该把他parseFloat 比较好对吧

2018-03-05 06:35 UTC, pandamicro commented on cocos2d/core/label/CCSGLabel.js
> +            letterDefinition._v = parseInt(tempRect.y) + this._imageOffset.y;
呃，取决于上面那个问题的答案，如果是归一化的，你用 parseInt 得出的 uv 结果肯定是错的，渲染按理说也不会正确。既然你测试没问题，说明可能是像素为单位。这个要看一下 fnt 格式的定义，你可以搜索一下，我也不了解

2018-03-05 06:35 UTC, pandamicro commented on cocos2d/core/label/CCSGLabel.js
> +            letterDefinition._v = parseInt(tempRect.y) + this._imageOffset.y;
其他的属性也是一样，如果有可能出现浮点数，那就应该用 parseFloat，如果肯定是整型，那用 parseInt 没关系

2018-03-05 06:36 UTC, umbrellaPP commented on cocos2d/core/label/CCSGLabel.js
> +            letterDefinition._v = parseInt(tempRect.y) + this._imageOffset.y;
嗯嗯，我测试是没问题的。我待会了解下fnt 的格式定义，有必要的话我把他改过来

2018-03-05 08:51 UTC, umbrellaPP commented on cocos2d/core/label/CCSGLabel.js
> +            letterDefinition._v = parseInt(tempRect.y) + this._imageOffset.y;
已经用BMFont 工具测试过，不会出现小数的情况

2018-03-05 08:58 UTC, jareguo requested changes

2018-03-05 08:58 UTC, jareguo commented on cocos2d/core/label/CCSGLabel.js
> +            letterDefinition._v = parseInt(tempRect.y) + this._imageOffset.y;
我不明白这里用 parseInt 的意义，对 JS 来说，number 都是无类型的，因此解析数据时总是调用 parseFloat 不是更好吗？

2018-03-05 09:09 UTC, umbrellaPP commented on cocos2d/core/label/CCSGLabel.js
> +            letterDefinition._v = parseInt(tempRect.y) + this._imageOffset.y;
如果不存在浮点数，考虑parseInt 是不是稍微更快一点？！虽然差别可能很微小

2018-03-05 09:10 UTC, jareguo approved these changes

2018-03-05 09:11 UTC, jareguo commented on cocos2d/core/label/CCSGLabel.js
> +            letterDefinition._v = parseInt(tempRect.y) + this._imageOffset.y;
好吧，可能会快一点，至少不用纠结科学记数法那堆东西。好吧，不纠结了，parseInt 也可以的~！

2018-03-06 02:15 UTC, pandamicro approved these changes

2018-03-06 02:15 UTC, merged