widget组件，align属性增加ONCE_WINDOW_RESIZED选项
cocos/cocos-engine pull request #2405
Opened 2018-03-07 02:10 UTC by umbrellaPP

Re: #2395 

Changelog:
 *

2018-03-07 02:53 UTC, jareguo requested changes

2018-03-07 02:53 UTC, jareguo commented on cocos2d/core/base-ui/CCWidgetManager.js
> +    ONCE_WINDOW_RESIZED: 2,
ALIGN_ONCE -> ONCE
ONCE_WINDOW_RESIZED -> ON_WINDOW_RESIZED
另外顺序调整下，ALWAYS 放到最后

2018-03-07 02:53 UTC, jareguo commented on cocos2d/core/components/CCWidget.js
> +           default: WidgetManager.AlignMode.ALIGN_ONCE,
默认值请用 ON_WINDOW_RESIZED

2018-03-07 02:53 UTC, jareguo commented on cocos2d/core/base-ui/CCWidgetManager.js
> +    AlignMode: AlignMode,
请参考 CCSprite.js 中的
`var SpriteType = cc.Scale9Sprite.RenderingType;` 以及
`Type: SpriteType,`
，将 AlignMode 的 API 定义在 CCWidget 内，并且暴露到 cc.Widget.AlignMode

2018-03-07 02:53 UTC, jareguo commented on cocos2d/core/components/CCWidget.js
> +                return this._isAlignOnce;
return this.alignMode === ONCE

2018-03-07 02:53 UTC, jareguo commented on cocos2d/core/components/CCWidget.js
> +            displayName: "AlignOnce",
移除 displayName 和 tooltip

2018-03-07 02:53 UTC, jareguo commented on cocos2d/core/components/CCWidget.js
> +                this._isAlignOnce = value;
this.alignMode = value ? ONCE : ALWAYS

2018-03-07 02:53 UTC, jareguo commented on cocos2d/core/base-ui/CCWidgetManager.js
> +                    if (widget.alignMode === AlignMode.ALWAYS){
这里不用加这个判断，因为在 activeWidgets 里的 widget 总会是需要 align 的

2018-03-07 02:53 UTC, jareguo commented on cocos2d/core/base-ui/CCWidgetManager.js
> +        if ((!CC_EDITOR || animationState.animatedSinceLastFrame) && widget.alignMode === AlignMode.ALIGN_ONCE) {
widget.alignMode === AlignMode.ALIGN_ONCE 改为
widget.alignMode !== AlignMode.ALWAY，把 ON_WINDOW_RESIZED 也包含进来

2018-03-07 03:17 UTC, umbrellaPP commented on cocos2d/core/base-ui/CCWidgetManager.js
> +                    if (widget.alignMode === AlignMode.ALWAYS){
ON_WINDOW_RESIZED 的widget 应该也算是activeWidgets 哦

2018-03-07 03:19 UTC, jareguo commented on cocos2d/core/base-ui/CCWidgetManager.js
> +                    if (widget.alignMode === AlignMode.ALWAYS){
这个部分待会我会再回复

2018-03-07 03:31 UTC, jareguo commented on cocos2d/core/base-ui/CCWidgetManager.js
> +        }
@pandamicro 有没有跨平台的监听 canvas resize 的接口？

2018-03-07 04:42 UTC, jareguo requested changes

2018-03-07 04:42 UTC, jareguo commented on cocos2d/core/base-ui/CCWidgetManager.js
> +            widgetManager.isAligning = true;
这里不需要在 resize 时立刻进行 align。而是应该更新 widget 的 enabled 状态，待 refreshScene 在下一帧调用时自然就会刷新到。

2018-03-07 16:37 UTC, jareguo requested changes

2018-03-07 16:37 UTC, jareguo commented on cocos2d/core/base-ui/CCWidgetManager.js
> -});
抱歉，我前面没说清楚，AlignMode 的枚举仍然在这里。CCWidget 中通过 require 去获得。
但是要将 AlignMode API 注释写在 CCWidget 内，以便生成 API 文档。对用户来说，这个 API 需要暴露到 cc.Widget.AlignMode。对引擎来说，用原有的方式访问就好。

2018-03-07 16:37 UTC, jareguo commented on cocos2d/core/components/CCWidget.js
> +        AlignMode: AlignMode,
👍

2018-03-07 16:37 UTC, jareguo commented on cocos2d/core/components/CCWidget.js
> +                this.alignMode = value? AlignMode.ONCE: AlignMode.ALWAYS;
三元运算符左右两边请都保留一个空格（刚刚已补充到编码规范）

2018-03-07 16:37 UTC, jareguo commented on cocos2d/core/components/CCWidget.js
> +           type: AlignMode,
请增加帮忙 `tooltip: CC_DEV && 'i18n:COMPONENT.widget.align_mode',`
align_mode 我会另外定义

2018-03-07 16:37 UTC, jareguo commented on cocos2d/core/base-ui/CCWidgetManager.js
> +        }
这里漏了 JSB 的情形

2018-03-07 16:37 UTC, jareguo commented on cocos2d/core/base-ui/CCWidgetManager.js
> +    onResized() {
`()` 左右两边请保留一个空格（刚刚已补充到编码规范）

2018-03-07 16:37 UTC, jareguo commented on cocos2d/core/base-ui/CCWidgetManager.js
> +    visitNodeOnResized(node){
这个方法名未能准确表达该方法的实现意图，建议改叫 “refreshWidgetOnResized”

2018-03-07 16:37 UTC, jareguo commented on cocos2d/core/base-ui/CCWidgetManager.js
> +        var widget = !(node instanceof cc.Scene) && node.getComponent(cc.Widget);
var widget = cc.Node.isNode(node) && node.getComponent(cc.Widget);

2018-03-07 16:37 UTC, jareguo commented on cocos2d/core/base-ui/CCWidgetManager.js
> +            if (CC_DEV) {
这里不需要重复做这个检测了，这个检测之前第一次对齐时已经进行过了

2018-03-07 16:37 UTC, jareguo commented on cocos2d/core/base-ui/CCWidgetManager.js
> +            if ((!CC_EDITOR || animationState.animatedSinceLastFrame) && widget.alignMode === cc.Widget.AlignMode.ON_WINDOW_RESIZED) {
不管是否动画编辑模式都需要重新激活，因此 `(!CC_EDITOR || animationState.animatedSinceLastFrame) && ` 去掉

2018-03-07 16:37 UTC, jareguo commented on cocos2d/core/base-ui/CCWidgetManager.js
> +            if (child._active) {
就算 child 未激活，也要重新 enable 它们的 widget，因为目前 child 未激活，所以 enable widget 实际上不会有任何改变。不过当下次 child 被重新激活时，里面的 widget 就能够再生效一次，这应该更加符合用户的预期。

2018-03-08 08:37 UTC, jareguo commented
请参考 CCSprite.js 中的
`var SpriteType = cc.Scale9Sprite.RenderingType;`，将 AlignMode 的 **API 注释** 写到 CCWidget.js
请在原 isAlignOnce 的 API 注释中添加 `@deprecated` 标记

2018-03-08 09:29 UTC, merged