Remove old deprecations
cocos/cocos-engine pull request #2429
Opened 2018-03-12 10:35 UTC by pandamicro

Re: cocos-creator/fireball#7055

2018-03-12 16:18 UTC, jareguo requested changes

2018-03-12 16:18 UTC, jareguo commented on cocos2d/core/CCNode.js
> - */
这些 API 1.x 里面还用着呢，文档就留着吧，否则老用户查文档就查不到了。可以写上 `@deprecated Deprecated since 2.0. Please use ...`

2018-03-12 16:18 UTC, jareguo commented on cocos2d/deprecated.js
> -    function deprecateEnum (obj, oldPath, newPath, hasTypePrefixBefore) {
这个方法先留着吧，反正构建时会自动剔除

2018-03-13 02:31 UTC, pandamicro commented
Updated

2018-03-13 02:32 UTC, merged