support RenderTexture
cocos/cocos-engine pull request #2441
Opened 2018-03-15 08:56 UTC by 2youyou2

Re: cocos-creator/fireball#7021

Changelog:
 * support RenderTexture

2018-03-20 16:23 UTC, pandamicro reviewed
建议以 RenderTexture 为入口来设计 API，而不是以 Camera 为入口。

renderTexture.capture(camera, root);

同时，这样可以将 Camera 中的 targetTexture 相关的逻辑（_updateTargetTexture 和 render）隔离在 RenderTexture 中，功能划分会更清晰。

2018-03-20 16:23 UTC, pandamicro commented on cocos2d/core/assets/CCRenderTexture.js
> +        this._framebuffer = new renderEngine.gfx.FrameBuffer(renderer.device, width, height, opts);
需要管理 framebuffer 内存，destroy 之前的 framebuffer，以及在 onDestroy 时销毁当前的 framebuffer

2018-03-20 16:23 UTC, pandamicro commented on cocos2d/core/assets/CCRenderTexture.js
> +     * 从 render texture 读取像素数据
解释一下 data 的类型和规范

2018-03-20 16:23 UTC, pandamicro commented on cocos2d/core/camera/CCCamera.js
> +        let width = cc.visibleRect.width;
好像没有用到 width

2018-03-21 09:31 UTC, 2youyou2 commented
> 建议以 RenderTexture 为入口来设计 API，而不是以 Camera 为入口。
> 
> renderTexture.capture(camera, root);

如果 render texture 只是设计为用来 capture 的话是可以，但是这个设计是还要给其他的 render 使用，比如后期屏幕特效

2018-03-21 09:43 UTC, pandamicro commented
那就添加一个 RenderTexture.capture，里面调用 render

2018-03-21 10:02 UTC, jareguo commented
> 建议以 RenderTexture 为入口来设计 API，而不是以 Camera 为入口。
> 
> renderTexture.capture(camera, root);

这个我觉得不太好……
一方面是一个 render texture 可能对应多个 camera，这些 camera 可能根据情况会依次激活。
另一个方面是 render texture 应该是一种 asset，asset 可以直接拖到场景的任意一个相机上。然后这个 asset 的 sub spriteframe 可以被拖到场景中的任意一个 Sprite 上。
也就是说，render texture 是可以在编辑器里直接拖拖拉拉就搞定的东西，不一定要写代码。

2018-03-21 10:04 UTC, pandamicro commented
> render texture 是可以在编辑器里直接拖拖拉拉就搞定的东西，不一定要写代码。

那你的意思是 RenderTexture 要挂到 Camera 底下，但是用户截图的行为一般是一次性的。

2018-03-21 10:06 UTC, 2youyou2 commented
> 另一个方面是 render texture 应该是一种 asset，asset 可以直接拖到场景的任意一个相机上。然后这个 asset 的 sub spriteframe 可以被拖到场景中的任意一个 Sprite 上。
> 也就是说，render texture 是可以在编辑器里直接拖拖拉拉就搞定的东西，不一定要写代码。

对的，我现在也是参考 unity 来设计的，不过还没做到可以在编辑器中创建 render texture

2018-03-21 10:09 UTC, jareguo commented
> 那你的意思是 RenderTexture 要挂到 Camera 底下，但是用户截图的行为一般是一次性的。

嗯，这个确实也是的。可能用户要多写一点代码。或者我们可以封装一个 camera.render(renderTexture)？

2018-03-21 10:20 UTC, pandamicro commented
那就先按照现在提案的 API 把

2018-03-21 10:26 UTC, pandamicro requested changes

2018-03-21 10:26 UTC, pandamicro commented on cocos2d/core/assets/CCTexture2D.js
> +        _getSharedOptions: _getSharedOptions
这个不需要暴露的，使用 update 的话，会自动覆盖到 shared options 里面，别暴露这种 API 了

2018-03-21 10:37 UTC, pandamicro approved these changes

2018-03-21 10:41 UTC, merged