add wechatgame subdomian
cocos/cocos-engine pull request #2453
Opened 2018-03-17 04:48 UTC by knoxHuang

Re: cocos-creator/fireball#6838

Changelog:
 * 添加微信子域

2018-03-17 06:31 UTC, jareguo requested changes

2018-03-17 06:31 UTC, jareguo commented on cocos2d/core/CCGame.js
> +            if (isWeChatGameSub) {
这个变量是多余的，直接在这里面判断就好了

2018-03-17 06:31 UTC, jareguo commented on cocos2d/core/platform/CCSys.js
> +                browserType = sys.BROWSER_TYPE_WECHAT_GAME_SUB;
sys.browserType 上面不是赋值过了吗？

2018-03-17 06:31 UTC, jareguo commented on cocos2d/core/platform/CCView.js
> +    }
else {
__BrowserGetter.adaptationType = cc.sys.BROWSER_TYPE_WECHAT_GAME;
}

2018-03-17 06:31 UTC, jareguo commented on cocos2d/core/platform/CCView.js
> +            return sharedCanvas.height;
直接用 wx.getSharedCanvas().height; 吧，保险一点

2018-03-17 06:31 UTC, jareguo commented on cocos2d/core/platform/CCView.js
> +                message: "changedShareCanvasSize"
shar`ed`CanvasResized

2018-03-17 06:31 UTC, jareguo commented on cocos2d/core/platform/CCView.js
> +        if (cc.sys.browserType === cc.sys.BROWSER_TYPE_WECHAT_GAME_SUB) {
if （CC_WECHATGAME && ...

2018-03-17 06:31 UTC, jareguo commented on cocos2d/core/platform/CCView.js
> +        }
感觉这里写在 resizeWithBrowserSize 里面会比较好？

2018-03-17 13:53 UTC, pandamicro commented on cocos2d/core/platform/CCView.js
> +                message: "changedShareCanvasSize"
@knoxHuang 这里是不是循环调用了？你的事件回调里面又调用了 _resizeEvent

2018-03-17 14:11 UTC, pandamicro commented on cocos2d/core/platform/CCInputManager.js
> +                for (var eventName in _touchEventsMap) _loop2(eventName);
推荐这样的写法，_loop2，_wxSubdomainLoop2 这种命名尽量避免，会引起其他人的阅读障碍

```
var registerTouchEvent;
if (cc.sys.browserType === cc.sys.BROWSER_TYPE_WECHAT_GAME_SUB) {
    _touchEventsMap = {
        onTouchStart: _touchEventsMap.touchstart,
        onTouchMove: _touchEventsMap.touchmove,
        onTouchEnd: _touchEventsMap.touchend,
        onTouchCancel: _touchEventsMap.touchcancel,
    };
    registerTouchEvent = function(eventName) {
        wx[eventName](function(event) {
            if (!event.changedTouches) return;
            var pos = selfPointer.getHTMLElementPosition(element);
            var body = document.body;
            pos.left -= body.scrollLeft || 0;
            pos.top -= body.scrollTop || 0;
            handler(selfPointer.getTouchesByEvent(event, pos));
        });
    };
}
else {
    registerTouchEvent = function(eventName) {
        var handler = _touchEventsMap[eventName];
        element.addEventListener(eventName, (function(event) {
            if (!event.changedTouches) return;
            var pos = selfPointer.getHTMLElementPosition(element);
            var body = document.body;
            pos.left -= body.scrollLeft || 0;
            pos.top -= body.scrollTop || 0;
            handler(selfPointer.getTouchesByEvent(event, pos));
            event.stopPropagation();
            event.preventDefault();
        }), false);
    };
}
for (var eventName in _touchEventsMap) {
    registerTouchEvent(eventName);
}
```

2018-03-18 16:00 UTC, pandamicro requested changes

2018-03-18 16:00 UTC, pandamicro commented on cocos2d/core/platform/CCView.js
> +            wx.postMessage({
我这边尝试 postMessage 是没效果的，如果用 Canvas 组件的轮询，这里实现改成和下面 setupContainer 中一样就好了

2018-03-19 06:29 UTC, knoxHuang commented
这个还有啥问题吗？

2018-03-19 06:31 UTC, jareguo approved these changes

2018-03-19 06:35 UTC, pandamicro approved these changes

2018-03-19 06:47 UTC, merged