reimplement debugInfos workflow
cocos/cocos-engine pull request #2470
Opened 2018-03-23 10:41 UTC by umbrellaPP

Re: #2384 

Changelog:
 *

2018-03-24 07:06 UTC, jareguo requested changes

2018-03-24 07:06 UTC, jareguo commented on EngineErrorMap.md
> +
3655 漏了...

2018-03-24 07:06 UTC, jareguo commented on gulp/tasks/engine.js
> +};
这个 task 单独放在一个 js 中吧

2018-03-24 07:06 UTC, jareguo commented on gulp/tasks/engine.js
> +    let writeContent = `${JSON.stringify(debugInfos, null, 4)}`;
这个模板字符串用的好像没意义啊

2018-03-24 07:06 UTC, jareguo commented on DebugInfos.json
> +{
这个文件不需要提交到 repo，加到 .gitignore 吧

2018-03-24 07:06 UTC, jareguo commented on gulpfile.js
> +    Engine.buildDebugInfos();
应该是改成 gulp.task('build-html5-preview',  'build-debug-infos', function...
还有其它 build-xx 也需要依赖 build-debug-infos

2018-03-26 06:39 UTC, jareguo commented
这些都没问题了。但是关于现在的工作流，还缺乏一份文档介绍。请在 README 中补充一下，如何定义这些 log。

2018-03-26 07:42 UTC, jareguo requested changes

2018-03-26 07:42 UTC, jareguo commented on README.md
> +2. Define deprecated log
讲一下什么时候需要标记为 deprecated

2018-03-26 07:42 UTC, jareguo commented on README.md
> +1. Define log
Define log in EngineErrorMap.md

2018-03-26 07:42 UTC, jareguo commented on README.md
> +    You cannot leave blank line at the end-of-file
这是为什么呀？

2018-03-26 07:52 UTC, umbrellaPP commented on README.md
> +    You cannot leave blank line at the end-of-file
因为解析的时候， 文件尾那一句 我是截取到文件尾的
如果有空行，可能空行也会被解析进去哦，比如：
"8400": "Wrong type arguments, 'filePath' must be a String.\n\n",

这里好像也没什么好的办法判断最后一句的结尾位置在哪，所以我就截取到文件尾了
或者要再md 的文件尾 做个标记吗
<!-- END-OF-FILE -->

2018-03-26 07:53 UTC, umbrellaPP commented on README.md
> +    You cannot leave blank line at the end-of-file
<!- - END-OF-FILE -- >

2018-03-26 07:58 UTC, jareguo commented on README.md
> +    You cannot leave blank line at the end-of-file
trimRight

2018-03-26 08:51 UTC, pandamicro commented on README.md
> +All the debug infos are defined in file EngineErrorMap.md.
给 EngineErrorMap.md 加个链接

2018-03-26 08:51 UTC, pandamicro commented on EngineErrorMap.md
> +<!-- DEPRECATED -->
这些 DEPRECATED 是怎么出来的？人工判断？

2018-03-26 08:51 UTC, pandamicro commented on CCDebugger.js
> +const debugInfos = require('./DebugInfos.json') || {};
可以直接 require json ？？？

2018-03-26 08:53 UTC, umbrellaPP commented on EngineErrorMap.md
> +<!-- DEPRECATED -->
对的，纯人工复查

2018-03-26 08:54 UTC, jareguo commented on EngineErrorMap.md
> +<!-- DEPRECATED -->
就是存档用的，给旧版本用户查文档的时候看的。新版本用不到这些 log 了

2018-03-26 08:54 UTC, jareguo commented on CCDebugger.js
> +const debugInfos = require('./DebugInfos.json') || {};
可以

2018-03-26 09:04 UTC, jareguo approved these changes

2018-03-26 09:08 UTC, 2youyou2 commented on CCDebugger.js
> +const debugInfos = require('./DebugInfos.json') || {};
指定 .json 2.0会有问题的额，2.0 会把 .json 转成 .js

2018-03-26 09:09 UTC, jareguo commented on CCDebugger.js
> +const debugInfos = require('./DebugInfos.json') || {};
json 的支持好加吗？

2018-03-26 09:10 UTC, 2youyou2 commented on CCDebugger.js
> +const debugInfos = require('./DebugInfos.json') || {};
不用加 .json 后缀，`require('./DebugInfos')` 就好

2018-03-26 09:12 UTC, jareguo commented on CCDebugger.js
> +const debugInfos = require('./DebugInfos.json') || {};
转成 js 后，2.0 会自动加上 module.exports = JSON 吗？

2018-03-26 09:12 UTC, 2youyou2 commented on CCDebugger.js
> +const debugInfos = require('./DebugInfos.json') || {};
对的

2018-03-26 09:15 UTC, umbrellaPP commented on CCDebugger.js
> +const debugInfos = require('./DebugInfos.json') || {};
已经提交修改

2018-03-26 09:19 UTC, jareguo commented
不知道这样在主分支的编辑器里会不会有问题，麻烦 PP 部署好开发环境后验证下。

2018-04-11 02:00 UTC, jareguo commented
另外，master 最近演进比较大，麻烦对比你本地的版本和远程版本的差异，更新一下 debug info 的内容

2018-04-11 02:02 UTC, umbrellaPP commented
好的

2018-04-11 07:22 UTC, PPpro commented
对比debugInfos.js 文件，新增了8401  errorId。
已经在主分支的编辑器界面测试了几个error，log信息可以正常打印出来

2018-04-11 07:56 UTC, merged