Native new renderer adaption
cocos/cocos-engine pull request #2476
Opened 2018-03-28 01:18 UTC by minggo

2018-03-28 01:19 UTC, minggo commented
@pandamicro 
@dumganhar 
Please help to review it.

2018-03-28 02:05 UTC, pandamicro requested changes

2018-03-28 02:05 UTC, pandamicro commented on cocos2d/core/CCDirector.js
> +const renderer = require('./renderer/index');
@dumganhar 不能支持一下不带 index 的写法吗？

2018-03-28 02:05 UTC, pandamicro commented on cocos2d/core/platform/CCSys.js
> +        sys.isMobile = false; //FIXME:
目前不好判断吗？

2018-03-28 02:05 UTC, pandamicro commented on cocos2d/core/platform/CCSys.js
> +        sys.platform = sys.WECHAT_GAME;
这个应该指定为对应操作系统，可以放在下面 OS 的判断里面

```
if (env.platform === "android") {
    sys.os = sys.OS_ANDROID;
    sys.platform = sys.ANDROID;
}
else if (env.platform === "ios") {
    sys.os = sys.OS_IOS;
    sys.platform = sys.IPHONE; // 看看是否能识别 IPAD
}
else if (env.platform === 'mac') {
    sys.os = sys.OS_OSX;
    sys.platform = sys.MACOS
}
else if (env.platform === 'windows') {
    sys.os = sys.OS_WINDOWS;
    sys.platform = sys.WIN32; // WIN10 ？
}
```

2018-03-28 02:05 UTC, pandamicro commented on cocos2d/core/platform/CCSys.js
> +        sys.isMobile = false; //FIXME:
还需要 sys.isNative = true

2018-03-28 02:05 UTC, pandamicro commented on cocos2d/core/platform/CCSys.js
> +        sys.browserType = sys.BROWSER_TYPE_WECHAT_GAME;
browser 相关的就不用管了

2018-03-28 02:05 UTC, pandamicro commented on cocos2d/core/platform/CCSys.js
> +            "canvas": true,
"canvas": false

2018-03-28 02:05 UTC, pandamicro commented on cocos2d/core/platform/js.js
> +        return dunderProto && dunderProto.constructor;
第一个判断不应该去掉吧？去掉 CC_JSB 就可以了

2018-03-28 02:05 UTC, pandamicro commented on index.js
> +}
上面的修改已经被迁移到 predefine.js 中，要从这里删除，然后在 predefine 的 CC_SUPPORT_JIT 那里修改

2018-03-28 02:05 UTC, pandamicro commented on jsb/builtin/dist/jsb.js
> +(function(){function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");t
这个 dist/jsb.js 是从哪里来的？

2018-03-28 02:26 UTC, 2youyou2 commented on cocos2d/core/physics/CCPhysicsContact.js
> -    if (CC_JSB) {
jsbbinding 都没用了吗，这样 box2d 会慢蛮多的吧，还是有新的绑定？

2018-03-28 02:33 UTC, jareguo requested changes

2018-03-28 02:33 UTC, jareguo commented on cocos2d/core/load-pipeline/binary-downloader.js
> +if (CC_JSB || CC_JSB) {
这里多了一个判断

2018-03-28 02:33 UTC, jareguo commented on cocos2d/core/utils/index.js
> +if (!CC_EDITOR && !CC_JSB && !CC_JSB && !CC_WECHATGAME && !CC_QQPLAY) {
这里判断重复了

2018-03-28 02:33 UTC, jareguo commented on jsb/jsb-audio.js
> + Chukong Aipu reserves all rights not expressly granted to you.
版权声明别覆盖了

2018-03-28 02:33 UTC, jareguo commented on jsb/index.js
> - ****************************************************************************/
版权声明留着吧

2018-03-28 02:33 UTC, jareguo commented on jsb/jsb-loader.js
> + Chukong Aipu reserves all rights not expressly granted to you.
版权声明~

2018-03-28 02:33 UTC, jareguo commented on package.json
> +    "babel-preset-es2015": "^6.24.1",
复用 babel-preset-env 就好了，不用 es2015

2018-03-28 02:34 UTC, jareguo commented
新增的脚本都别漏了版权声明啦~

2018-03-28 02:35 UTC, jareguo commented
jsb/builtin/dist/jsb.js 是构建出来的吗？那不应该提交上来吧。把构建过程插入到现有的 gulpfile 中就好啦

2018-03-28 03:13 UTC, pandamicro commented on cocos2d/core/physics/CCPhysicsContact.js
> -    if (CC_JSB) {
以后再添加，先把基础功能搭好

2018-03-28 03:26 UTC, 2youyou2 commented on cocos2d/core/physics/CCPhysicsContact.js
> -    if (CC_JSB) {
以后添加会差很大吗，差不大的话就不要删掉了吧，再加回来很难测试

2018-03-28 03:35 UTC, pandamicro commented on cocos2d/core/physics/CCPhysicsContact.js
> -    if (CC_JSB) {
@minggo 应该不是删除把，是不是这个版本的 jsb runtime 一开始就没有？

2018-03-28 03:38 UTC, jareguo commented on index.js
> +    defineMacro('CC_SUPPORT_JIT', true); //FIXME: cjh close it since safety issues.
这个注释我看不太懂，明明是设为 true，为什么说是 close it

2018-03-28 03:40 UTC, jareguo commented on index.js
> +if (CC_JSB) {
JSB 怎么会读这个文件呢？JSB 读的是 jsb-index.js 才对

2018-03-28 06:26 UTC, minggo commented on cocos2d/core/CCDirector.js
> +const renderer = require('./renderer/index');
这是我之前测试时遇到的问题，可以在这里先写个 TODO: fix，否则每次可能都会漏掉这个。

2018-03-28 06:26 UTC, minggo commented on cocos2d/core/platform/CCSys.js
> +        sys.isMobile = false; //FIXME:
@dumganhar

2018-03-28 06:27 UTC, minggo commented on cocos2d/core/platform/CCSys.js
> +        sys.platform = sys.WECHAT_GAME;
这块是同步 runtime 过来的代码，@dumganhar

2018-03-28 06:27 UTC, minggo commented on cocos2d/core/platform/CCSys.js
> +        sys.browserType = sys.BROWSER_TYPE_WECHAT_GAME;
这块是同步 runtime 过来的代码，@dumganhar

2018-03-28 06:27 UTC, minggo commented on cocos2d/core/platform/CCSys.js
> +            "canvas": true,
这块是同步 runtime 过来的代码，@dumganhar

2018-03-28 06:27 UTC, minggo commented on cocos2d/core/platform/js.js
> +        return dunderProto && dunderProto.constructor;
这块是同步 runtime 过来的代码，@dumganhar

2018-03-28 06:30 UTC, minggo commented
> jsb/builtin/dist/jsb.js 是构建出来的吗？那不应该提交上来吧。把构建过程插入到现有的 gulpfile 中就好啦

听建华说是为了适配不同引擎，所以 jsb.js 没有被集成到现有的打包流程。 @dumganhar 

> 新增的脚本都别漏了版权声明啦~

嗯，我加一下。

2018-03-28 06:31 UTC, minggo commented on cocos2d/core/load-pipeline/binary-downloader.js
> +if (CC_JSB || CC_JSB) {
嗯，我修改一下。

2018-03-28 06:33 UTC, minggo commented on cocos2d/core/physics/CCPhysicsContact.js
> -    if (CC_JSB) {
嗯，现在的 runtime 都没有这块绑定。那这样吧，先把代码注释掉，如果以后要加回来的话方便些。

2018-03-28 06:34 UTC, minggo commented on cocos2d/core/utils/index.js
> +if (!CC_EDITOR && !CC_JSB && !CC_JSB && !CC_WECHATGAME && !CC_QQPLAY) {
嗯，改一下。

2018-03-28 06:35 UTC, minggo commented on index.js
> +    defineMacro('CC_SUPPORT_JIT', true); //FIXME: cjh close it since safety issues.
@dumganhar 建华解释一下吧

2018-03-28 06:36 UTC, minggo commented on index.js
> +}
Ok，可能是自动 merge 出的问题，我看一下。

2018-03-28 06:36 UTC, minggo commented on index.js
> +if (CC_JSB) {
@dumganhar

2018-03-28 08:58 UTC, minggo commented on cocos2d/core/physics/CCPhysicsContact.js
> -    if (CC_JSB) {
只能是以后加回来，现在如果加回来的话，物理这块没法跑。有历史记录，以后加回来也很方便。

2018-03-28 09:53 UTC, jareguo commented on jsb/jsb-audio.js
> + Xiamen Yaji Software Co., Ltd. reserves all rights not expressly granted to you.
上面 Chukong 的也要改~ 加上 2017-2018 雅基

2018-03-30 01:31 UTC, dumganhar commented on cocos2d/core/CCDirector.js
> +const renderer = require('./renderer/index');
这个现在是编译成单个文件的方式，应该可以去掉index了，之前是多个文件分开加载，在c++层模拟commonjs的方式，可能实现有些问题，才这样改的。

2018-03-30 01:32 UTC, dumganhar commented on cocos2d/core/platform/CCSys.js
> +        sys.isMobile = false; //FIXME:
所以很多FIXME啊，还有合并前，不能用wx API啦

2018-03-30 01:32 UTC, dumganhar commented on cocos2d/core/platform/CCSys.js
> +        sys.platform = sys.WECHAT_GAME;
FIXME要解决的。

2018-03-30 01:33 UTC, dumganhar commented on cocos2d/core/platform/CCSys.js
> +        sys.browserType = sys.BROWSER_TYPE_WECHAT_GAME;
sys相关的，细节需要好好整理一次的。之前为了最快的速度适配，参考了wx的api。

2018-03-30 01:34 UTC, dumganhar commented on cocos2d/core/platform/CCSys.js
> +            "canvas": true,
这里是的，要改为false。

2018-03-30 01:38 UTC, dumganhar commented on cocos2d/core/platform/js.js
> +        return dunderProto && dunderProto.constructor;
这块跟 @jareguo  确认过，直接走浏览器的逻辑，因为这块是解决 js 层继承 c++ 绑定类的问题。
判断去掉后，就是跟浏览器一样的逻辑了。因为新的架构，我们不会去在js层继承了，保持跟浏览器一致的流程比较好。

2018-03-30 01:39 UTC, dumganhar commented on package.json
> +    "babel-preset-es2015": "^6.24.1",
babel-preset-env 是 es5 么？好乱。。

2018-03-30 01:40 UTC, jareguo commented on package.json
> +    "babel-preset-es2015": "^6.24.1",
相当于是 es-latest-stable

2018-03-30 01:40 UTC, dumganhar commented on index.js
> +    defineMacro('CC_SUPPORT_JIT', true); //FIXME: cjh close it since safety issues.
是否要考虑安全问题禁用 JIT？所以有这个FIXME

2018-03-30 01:42 UTC, dumganhar commented on index.js
> +if (CC_JSB) {
jsb/index.js 是 jsb的入口，但是jsb/index.js  会require 上层 Web 的入口 index.js ，因为现在主要逻辑都是跑web的。

2018-03-30 01:44 UTC, dumganhar commented
> 听建华说是为了适配不同引擎，所以 jsb.js 没有被集成到现有的打包流程。

是的，jsb/builtin 下的文件，都是与creator 引擎无关的，生成jsb_polyfill 也不需要把jsb/builtin 目录下的js打进去，就是说，jsb/builtin/dist/jsb.js 是每个引擎适配runtime需要的共有内嵌模块。不应该放在creator的构建流程中。目前没有另外一个仓库专门放这个，所以先放在了 jsb/builtin/ 目录下了。

2018-03-30 01:47 UTC, jareguo commented
那就改个名字吧？例如 jsb/builtin/lib/runtime.js ？

2018-03-30 02:06 UTC, dumganhar commented
> 那就改个名字吧？例如 jsb/builtin/lib/runtime.js ？
jsb更大，runtime更小，现在 new renderer 的代码基于 jsb，你不能说 new renderer 代码基于 runtime吧。
所以我们还是延用 CC_JSB 这个宏啊，不然的话，应该是 CC_RUNTIME了。
我觉得 jsb.js 属于整个 jsb的内嵌脚本，直接叫这个名字稳妥一点。而且之前所有的creator版本中，都有内嵌脚本，名字也是 jsb.js，我不理解为什么这里要改成runtime.js 呢。

2018-03-30 02:08 UTC, minggo commented on cocos2d/core/platform/CCSys.js
> +        sys.isMobile = false; //FIXME:
那这个要怎么改？

2018-03-30 02:08 UTC, minggo commented on cocos2d/core/platform/CCSys.js
> +        sys.platform = sys.WECHAT_GAME;
嗯，先合并过去，这个也只影响到目前的 native，对 web 不影响。这个 PR 如果不合并，后续都没法同步。

2018-03-30 02:09 UTC, minggo commented on cocos2d/core/platform/CCSys.js
> +        sys.browserType = sys.BROWSER_TYPE_WECHAT_GAME;
等这个 PR 合并后再整。

2018-03-30 02:16 UTC, jareguo commented
我只是举个例子，名字可以换的。只要不要让人家感觉是从同一个 repo build 出来的就行

2018-03-30 02:30 UTC, minggo commented
不过我觉得 jsb.js 这部分的内容是需要放到 creator 里的。虽然 jsb.js 可以适配到别的 js 引擎，但是既然现在没有独立的仓库，那么就需要和 creator 的engine 放到一起，是作为 engine 的一部分。

2018-03-30 02:34 UTC, pandamicro commented on cocos2d/core/CCDirector.js
> +const renderer = require('./renderer/index');
我的意思就是 commonjs 的模拟实现可以优化一下

2018-03-30 02:40 UTC, minggo commented
@jareguo @pandamicro 看看还有什么问题，有些改动可能暂时不是最优的，但是需要先合并，否则 native 这边会很难同步 engine 的改动。该 PR 的改动大部分是针对 JSB 的，对 web 基本没影响。

2018-03-30 02:52 UTC, jareguo approved these changes
我这边没问题了。不过 P 大和凯乐关心的问题我也比较关心。

2018-03-30 02:52 UTC, minggo commented on cocos2d/core/platform/CCSys.js
> +        sys.isMobile = false; //FIXME:
目前先快速适配，后面还需要调整。这个 PR 先不包含这块的调整。

2018-03-30 02:54 UTC, minggo commented
什么问题？物理吗？物理之前讨论的情况就是先用 web 版本，等有效率问题再看怎么优化。

2018-03-30 03:06 UTC, jareguo requested changes

2018-03-30 03:06 UTC, jareguo commented on index.js
> +
上面这些代码记得要放到 predeifne.js

2018-03-30 03:06 UTC, jareguo commented on jsb/builtin/.babelrc
> +    "presets":["es2015"]
建议用 ["env"], 代替，用法不变

2018-03-30 05:44 UTC, minggo commented on jsb/builtin/.babelrc
> +    "presets":["es2015"]
builtin 目前是单独编译到 jsb.js 里，这个后续我会调整。

2018-03-30 05:52 UTC, minggo commented on index.js
> +
predefine.js 已经有了这些代码了，现在这些是重复代码，我删除掉。

2018-03-30 08:46 UTC, jareguo approved these changes

2018-04-01 14:23 UTC, pandamicro approved these changes

2018-04-01 14:26 UTC, pandamicro commented
@minggo 我先合并了，麻烦尽快把 fix me，sys 相关的配置，还有 build 相关的内容整理好

2018-04-01 14:26 UTC, merged