destroy audio element when stop
cocos/cocos-engine pull request #2480
Opened 2018-03-29 02:03 UTC by umbrellaPP

Re: #2409 

Changelog:
 * 
音频再设置setMaxAudioInstance(1) 的时候，频繁播放，
会频繁调用  stop  play，，，stop的时候没有 destroy掉，导致内存泄漏
多次play 之后就无法播放了

2018-03-29 02:14 UTC, jareguo commented on cocos2d/audio/CCAudio.js
> +        this._element.destroy();
如果 stop 完又想要 play 怎么办？支持这种操作吗 @VisualSJ

2018-03-29 02:20 UTC, pandamicro commented on cocos2d/audio/CCAudio.js
> +        this._element.destroy();
注意 API 兼容性检查，可能需要限定环境

2018-03-29 02:30 UTC, umbrellaPP commented on cocos2d/audio/CCAudio.js
> +        this._element.destroy();
好的，我做下环境判断

2018-03-29 02:31 UTC, umbrellaPP commented on cocos2d/audio/CCAudio.js
> +        this._element.destroy();
这个我可能要测试下

2018-03-29 03:02 UTC, umbrellaPP commented
destroy 完之后可能还会引起其他地方的引用问题，我尝试修复下

2018-03-29 08:44 UTC, umbrellaPP commented on cocos2d/audio/CCAudio.js
> +        this.destroy();
cc.AudioEngine.play 会创建多一个Audio，我觉得不存在 destroy 之后不能play 的问题
@jareguo

2018-03-31 01:53 UTC, VisualSJ commented on cocos2d/audio/CCAudioEngine.js
> +        audio.destroy();
这里 destroy 可能会引起问题。 getAudioFromPath 内获取的是缓存，每一个音频，都会缓存 _maxAudioInstance 个实例，之后都是复用这些实例。

所以这里 destroy 后，会不会影响到之后的播放？

2018-03-31 01:53 UTC, VisualSJ commented on cocos2d/audio/CCAudioEngine.js
> +                audio.destroy();
同上

2018-04-01 14:11 UTC, pandamicro commented on cocos2d/audio/CCAudioEngine.js
> +        audio.destroy();
而且这种不 destroy 导致的内存泄漏目前应该是只在微信小游戏环境下出现把？你需要测试一下浏览器环境中的泄漏情况。

2018-04-01 14:15 UTC, pandamicro requested changes

2018-04-01 14:15 UTC, pandamicro commented on cocos2d/audio/CCAudioEngine.js
> +        audio.destroy();
而且这种不 destroy 导致的内存泄漏目前应该是只在微信小游戏环境下出现把？你需要测试一下浏览器环境中的泄漏情况。

2018-04-11 06:04 UTC, umbrellaPP commented on cocos2d/audio/CCAudioEngine.js
> +        audio.destroy();
每次destroy 之前，都有调用 stop() 触发 'stop' 事件，将audio 从 url2id   id2audio 中移除，所以不会有缓存问题
浏览器中暂时没有发现内存泄漏情况。或者不知有有没有什么测试方法可以检测内存泄漏呢

2018-04-16 02:42 UTC, umbrellaPP commented on cocos2d/audio/CCAudioEngine.js
> +        audio.destroy();
浏览器环境中，记录了下play stop  的memory 情况，基本都会被GC回收 @pandamicro

2018-04-16 06:03 UTC, pandamicro approved these changes

2018-04-16 06:07 UTC, merged