support canvas label
cocos/cocos-engine pull request #2482
Opened 2018-03-29 10:02 UTC by 2youyou2

Re: cocos-creator/fireball#6995

Changelog:
 * support canvas label

2018-04-01 16:00 UTC, pandamicro commented on cocos2d/core/components/CCLabel.js
> +            assemblerData._canvas = document.createElement("canvas");
Label 创建的 canvas 非常多，所以需要管理 Canvas 的回收和复用。可以看看当前版本 renderer/canvas/renderers/utils.js 里面的 canvasMgr 能否满足需求

2018-04-02 03:12 UTC, 2youyou2 commented on cocos2d/core/components/CCLabel.js
> +            assemblerData._canvas = document.createElement("canvas");
给 label 加了个专门的 canvas pool

2018-04-02 03:15 UTC, 2youyou2 commented on cocos2d/core/renderer/canvas/renderers/label/ttf.js
> +        utils.dropImage(comp._texture, comp.node.color);
每次 ttf 更新了 texture 后，需要强制更新 pool 里的缓存

2018-04-02 03:18 UTC, 2youyou2 commented on cocos2d/core/renderer/index.js
> +        require('./assemblers');
渲染模式为 webgl 的情况下才加载 webgl 的 assemblers，否则两种模式的 comp.constructor._assembler 会冲突

2018-04-02 05:31 UTC, pandamicro requested changes

2018-04-02 05:31 UTC, pandamicro commented on cocos2d/core/renderer/canvas/renderers/utils.js
> +    dropImage (texture, color) {
不同情况 key 的计算方式不同，在 canvasMgr 只接受 key 来直接完成 drop 的操作，在 exports 里面添加 dropColorizedImage 来计算应该要 drop 的 key

2018-04-02 10:11 UTC, pandamicro approved these changes

2018-04-02 10:11 UTC, merged