fixed WeChat playform can't identify the ttf font format problem
cocos/cocos-engine pull request #2495
Opened 2018-04-03 06:11 UTC by CocosAss

fixed WeChat playform can't identify the ttf font format problem 

fixed WeChat playform can't identify the ttf font format problem

Re: cocos-creator/fireball#

Changelog:
 *

2018-04-03 06:17 UTC, jareguo requested changes

2018-04-03 06:17 UTC, jareguo commented on cocos2d/core/label/CCSGLabel.js
> +            if (fontFamilyName == null) {
你确定你这边要用的是两个等号吗？两个等号的意思是 fontFamilyName === null || fontFamilyName === undefined。而这种情况下，一般用 if (!fontFameilyName) 会更没歧义一点。

2018-04-03 06:17 UTC, jareguo commented on cocos2d/core/label/CCSGLabel.js
> +            if (!fontHandle in cc.CustomFontLoader._fontFamilyCache) {
in 运算符的优先级是小于取反运算的，所以这里肯定不能这么写

2018-04-03 06:17 UTC, jareguo commented on cocos2d/core/label/CCTextUtils.js
> +    _fontFamilyCache:{},
为什么要 cache 呢？冒号后加个空格哈

2018-04-03 06:17 UTC, jareguo commented on cocos2d/core/label/CCTextUtils.js
> +            }
else 的话会怎样？

2018-04-03 06:31 UTC, CocosAss commented
这个 Cache 是用来记录解析的 loadFont 返回的 familyName 的，因为每一次loadFont 相同的文件返回的FamilyName 也是不相同的

2018-04-03 06:33 UTC, jareguo commented on cocos2d/core/label/CCSGLabel.js
> +                return cc.CustomFontLoader._getFontFamily(fontHandle);
为什么这里 return 了，其它分支没 return？

2018-04-03 06:33 UTC, jareguo commented on cocos2d/core/label/CCSGLabel.js
> +                cc.CustomFontLoader._fontFamilyCache[fontHandle] = fontFamilyName;
为什么只有 微信需要用 cache？

2018-04-03 06:34 UTC, jareguo commented
> 每一次loadFont 相同的文件返回的FamilyName 也是不相同的

1，是否应该先访问 cache 再 loadFont？
2，familyName 不同会有什么后果？
3，如果后果严重，请调整下变量名，或者加点注释，表明 cache 的必要性

2018-04-03 07:08 UTC, jareguo commented on cocos2d/core/label/CCSGLabel.js
> +            if (!(fontHandle in cc.CustomFontLoader._fontFamilyCache)) {
走到这里后，下面还是会执行到 CustomFontLoader.loadTTF，从代码上看，load 了两次字体啊。太奇怪了，加点注释？

2018-04-03 15:50 UTC, pandamicro requested changes

2018-04-03 15:50 UTC, pandamicro commented on cocos2d/core/label/CCSGLabel.js
> +                return cc.CustomFontLoader._getFontFamily(fontHandle);
下面的 callback 还是需要执行的，需要做 font 加载完成后的通知和处理

2018-04-03 15:50 UTC, pandamicro commented on cocos2d/core/label/CCTextUtils.js
> +                fontFamilyName = this._getFontFamily(url);
这个分支有意义吗？肯定是无法加载成功的把？

2018-04-03 15:51 UTC, pandamicro requested changes

2018-04-03 15:51 UTC, pandamicro commented on cocos2d/core/label/CCTextUtils.js
> +    _fontFamilyCache: {},
这是只有微信小游戏平台才需要的，在命名上表现出来

2018-04-08 05:45 UTC, pandamicro approved these changes

2018-04-08 10:26 UTC, jareguo requested changes
还是有点问题

2018-04-08 10:30 UTC, jareguo commented on cocos2d/core/label/CCSGLabel.js
> +            //avoid the error in wechat editor platform
wechat devtools

2018-04-09 02:39 UTC, jareguo approved these changes

2018-04-09 02:39 UTC, merged