support mesh sprite
cocos/cocos-engine pull request #2512
Opened 2018-04-09 06:26 UTC by 2youyou2

Re: cocos-creator/fireball#6492

Changelog:
 * support mesh sprite

2018-04-09 08:24 UTC, pandamicro commented
效率这么高？？？

2018-04-09 09:27 UTC, jareguo commented on cocos2d/core/components/CCSprite.js
> +                this._applySpriteSize();
为什么 texture 相等的话，还是需要 applySpriteSize 呢？

2018-04-09 10:01 UTC, 2youyou2 commented on cocos2d/core/components/CCSprite.js
> +                this._applySpriteSize();
切换了 spriteFrame，spriteFrame 的 rect 可能会不一样

2018-04-09 10:05 UTC, jareguo commented on cocos2d/core/components/CCSprite.js
> +                this._applySpriteSize();
哦明白了，能在 v1.9 上也修复下吗

2018-04-09 10:27 UTC, 2youyou2 commented on cocos2d/core/components/CCSprite.js
> +                this._applySpriteSize();
1.9 没这个问题，2.0 才会判断 texture 不一样的时候调用 _onTextureLoaded，因为重新 _activateMaterial 消耗比较大

2018-04-09 13:18 UTC, pandamicro approved these changes

2018-04-09 13:27 UTC, jareguo requested changes

2018-04-09 13:27 UTC, jareguo commented on cocos2d/core/renderer/assemblers/sprite/mesh.js
> +            if (!sprite.trim) {
把这个 if 放到 for 循环外面吧？拆分成两个 for 循环

2018-04-09 13:27 UTC, jareguo commented on cocos2d/core/renderer/assemblers/sprite/mesh.js
> +            ibuf[indiceOffset++] = vertexId + parseInt(triangles[i]);
在 meta import 的过程中就进行 parseInt 比较好吧？运行时就少一些计算了。

2018-04-09 13:27 UTC, jareguo commented on cocos2d/core/renderer/assemblers/sprite/mesh.js
> +            vertice.v = verticesUV[i].y / texh;
texture 加载后，就把 uv 都计算好放到 spriteFrame 中比较好吧？（例如 vertices.u = spriteFrame._u[i]）
这样运行时切换 SpriteFrame 的时候不用每次都重新计算。

2018-04-09 13:27 UTC, jareguo commented on cocos2d/core/assets/CCSpriteFrame.js
> +        this.vertices = [];
建议直接拆分成 verticesX, verticesY 两个数组。在 meta 导入时进行设置。这样序列化后的 json 也会小很多，不用写那么多 x: 0, y: 0 的字典

2018-04-09 13:27 UTC, jareguo commented on cocos2d/core/assets/CCSpriteFrame.js
> +        this.verticesUV = [];
同上

2018-04-10 01:46 UTC, 2youyou2 commented on cocos2d/core/assets/CCSpriteFrame.js
> +        this.vertices = [];
存成 [x, y, x, y] 就可以了，也不用分开

2018-04-10 01:48 UTC, jareguo commented on cocos2d/core/assets/CCSpriteFrame.js
> +        this.vertices = [];
看你了…… 我是觉得那样遍历起来比较麻烦

2018-04-10 05:53 UTC, jareguo commented on cocos2d/core/assets/CCSpriteFrame.js
> +            this.once('load', this._normalizeUV, this);
如果贴图有动态修改，也应该再执行一次 _normalizeUV 是不？

2018-04-10 06:01 UTC, jareguo approved these changes

2018-04-10 06:30 UTC, merged