Optimize
cocos/cocos-engine pull request #2541
Opened 2018-04-16 06:43 UTC by 2youyou2

Changelog:
 * support dynamic atlas packer

2018-04-17 02:03 UTC, pandamicro commented on cocos2d/core/renderer/utils/dynamic-atlas/atlas.js
> +        this._texture.handleLoadedTexture();
应该根据 spriteFrame 的 texture 是否已经被加进 atlas 来处理，如果已经添加就不用了。现在应该是对一个 atlas 的每个 sprite frame 都会重复添加贴图。

2018-04-17 02:05 UTC, 2youyou2 commented on cocos2d/core/renderer/utils/dynamic-atlas/atlas.js
> +        this._texture.handleLoadedTexture();
不是按照 spriteFrame 的 texture 来整体添加的，而是截取 spriteFrame 的 rect 来添加的

2018-04-17 02:19 UTC, pandamicro reviewed
这套方案我主要担心的是：

1. 对内存不友好，比如一套动画用完之后，不再使用了，会一直存在于 atlas 中，造成无效内存 double，并且没有 dispose 机制
2. 如果渲染过程中贴图频繁变动，可能会导致频繁的 texSubImage2d，对运行时性能也有损耗

2018-04-17 02:19 UTC, pandamicro commented on cocos2d/core/renderer/utils/dynamic-atlas/atlas.js
> +        );
要用 webgl 接口来创建贴图，用 texSubImage2D 更新

2018-04-17 02:19 UTC, pandamicro commented on cocos2d/core/renderer/utils/dynamic-atlas/atlas.js
> +        this._texture.handleLoadedTexture();
哦，了解

2018-04-17 16:30 UTC, pandamicro commented
https://github.com/cocos-creator/fireball/issues/7131

2018-04-17 16:45 UTC, pandamicro requested changes

2018-04-17 16:45 UTC, pandamicro commented on cocos2d/core/assets/CCSpriteFrame.js
> +        this._oriInfo = null;
改为 _original 吧

2018-04-17 16:45 UTC, pandamicro commented on cocos2d/core/renderer/assemblers/sprite/bar-filled.js
> +        dynamicAtlasManager.insertSpriteFrame(sprite.spriteFrame);
建议的实现：

```
// 避免用户使用自定义 material 的情况下覆盖用户设置，不过这里还应该加一个 TODO，未来设计 material 的序列化和用户接口时，应该会有改动
if (!sprite._material) {
    // 尽可能避免函数调用的开销
    if (!sprite.spriteFrame._original) {
        dynamicAtlasManager.insertSpriteFrame(sprite.spriteFrame);
    }
    sprite._activateMaterial();
}
```

下面的其他 assembler 也是一样

2018-04-17 16:45 UTC, pandamicro commented on cocos2d/core/renderer/utils/dynamic-atlas/atlas.js
> +        texture.handleLoadedTexture();
用 update 函数，handleLoadedTexture 是为了保持兼容性留下来的

2018-04-17 16:45 UTC, pandamicro commented on cocos2d/core/renderer/utils/dynamic-atlas/manager.js
> +let _maxFrameSize = 512;
这个需要用野蛮人测试一下，个人感觉 256 比较好，到 512 的大图，一般不需要再批处理了

2018-04-18 04:35 UTC, pandamicro approved these changes

2018-04-18 04:35 UTC, merged