TiledMapAsset: reimplement RawAsset to Asset
cocos/cocos-engine pull request #2575
Opened 2018-04-20 09:33 UTC by umbrellaPP

Re: #6914

2018-04-20 09:35 UTC, umbrellaPP commented on cocos2d/tilemap/CCTMXXMLParser.js
> -
这里废弃了errorID 7220， 可能要更新下  EngineErrorMap.md 文件

2018-04-20 09:38 UTC, jareguo commented on cocos2d/tilemap/CCTMXXMLParser.js
> -
没用到就更新下

2018-04-20 09:46 UTC, umbrellaPP commented on cocos2d/tilemap/CCTMXXMLParser.js
> -
已经做了提交

2018-04-21 16:25 UTC, jareguo requested changes

2018-04-21 16:25 UTC, jareguo commented on cocos2d/tilemap/CCTMXXMLParser.js
> +    _tsxFiles: [cc.TextAsset],
上面这里不是 CCClass，不能这么声明，直接默认设置成 `[]` 就好

2018-04-21 16:25 UTC, jareguo commented on cocos2d/tilemap/CCSGTMXTiledMap.js
> +     * @param {String} tsxFiles
类型错了，应该是 `{String[]}`，数组

2018-04-21 16:25 UTC, jareguo commented on cocos2d/tilemap/CCTMXXMLParser.js
> +                var index = this._tsxFileNames.indexOf(tsxName);
index 会不会 === -1 呢？

2018-04-21 16:25 UTC, jareguo commented on cocos2d/tilemap/CCTiledMapAsset.js
> -        tmxFolderPath: '',
全局搜索下 tmxFolderPath（含编辑器代码），把用到的部分都更新下

2018-04-21 16:25 UTC, jareguo commented on cocos2d/tilemap/editor/tiled-map.js
> +    asset.tsxFiles = this._tsxFiles.map(p =>{
`=>{` 改成 `=> {`

2018-04-21 16:25 UTC, jareguo commented on cocos2d/tilemap/editor/tiled-map.js
> +        var tsxFileName = Path.basename(p);
建议判断下 Path.dirname(p) 是否等于 Path.dirname(fspath)，如果不在同一个目录下就报错。否则这里就不能只存 basename

2018-04-21 16:25 UTC, jareguo commented on cocos2d/tilemap/editor/tiled-map.js
> +        }
读不到 uuid 就报个错，说找不到文件 p

2018-04-21 16:25 UTC, jareguo commented on cocos2d/tilemap/editor/tiled-map.js
> +            return Editor.serialize.asAsset(uuid);
这里面才 asset.tsxFileNames.push(tsxFileName); 如果读不到 uuid，则 asset.tsxFileNames.push("");

2018-04-23 02:41 UTC, umbrellaPP commented on cocos2d/tilemap/CCTMXXMLParser.js
> +                var index = this._tsxFileNames.indexOf(tsxName);
是会的，我加个判断

2018-04-23 03:27 UTC, umbrellaPP commented on cocos2d/tilemap/editor/tiled-map.js
> +        var tsxFileName = Path.basename(p);
这一块，应该报什么错呢，
不存basename 应该存  p  和fspath  的相对路径吗

2018-04-23 06:38 UTC, jareguo requested changes

2018-04-23 06:38 UTC, jareguo commented on cocos2d/tilemap/editor/tiled-map.js
> +            cc.error(`Can not find file ${tsxPath}`);
编辑器内的报错，请用 Editor.error

2018-04-23 06:38 UTC, jareguo commented on cocos2d/tilemap/editor/tiled-map.js
> +        var tsxPath = Path.normalize(Path.join(Path.dirname(fspath), p));
join 完的路径本身就是 normalize 的，所以不需要额外 normalize 了。如果上面有这样的用法麻烦顺便改一下。

2018-04-23 06:51 UTC, jareguo approved these changes
没问题了。测试下原生平台（lite 仓库），如果原生平台也能正常编译、加载的话就合并

2018-04-24 15:29 UTC, jareguo requested changes

2018-04-24 15:29 UTC, jareguo commented on cocos2d/tilemap/CCTMXXMLParser.js
> +                if (this._tsxMap[tsxName]) {
为了减少重复查找的开销，建议 var tsx = this._tsxMap[tsxName];

2018-04-25 11:10 UTC, jareguo approved these changes

2018-04-26 13:50 UTC, merged