fix layout newChildWidth bug for cocos-creator/engine/issues/2383
cocos/cocos-engine pull request #2622
Opened 2018-05-02 09:46 UTC by knoxHuang

Re: cocos-creator/engine/issues/2383

Changelog:
 * 修复 layout 布局错误

2018-05-02 09:49 UTC, pandamicro requested changes

2018-05-02 09:49 UTC, pandamicro commented on cocos2d/core/components/CCLayout.js
> +        children.forEach(function(child) {
简单的 for 逻辑用 for 循环，不要用 forEach

2018-05-02 09:49 UTC, pandamicro commented on cocos2d/core/components/CCLayout.js
> +        children.forEach(function(child) {
同上

2018-05-03 01:25 UTC, knoxHuang commented on cocos2d/core/components/CCLayout.js
> +        children.forEach(function(child) {
这个不是修改 children 的数组，用 forEach 不太消耗

2018-05-03 01:45 UTC, knoxHuang commented
已修改，把所有 forEach 的都改成 for

2018-05-04 01:52 UTC, pandamicro commented on cocos2d/core/components/CCLayout.js
> +            activeChildCount++;
能不用 continue，break 的情况下不要用
```
if (child.activeInHierarchy) {
    activeChildCount++;
}
```

2018-05-04 02:09 UTC, pandamicro approved these changes

2018-05-04 02:09 UTC, merged