optimization label memory
cocos/cocos-engine pull request #2693
Opened 2018-05-16 02:53 UTC by knoxHuang

Re: cocos-creator/fireball#

Changelog:
 * 同步之前子龙优化 label 的代码

2018-05-16 02:58 UTC, 2youyou2 commented on cocos2d/core/components/CCLabel.js
>  let _canvasPool = {
那这个 pool 就不需要了，你创建一个 static 的 _assemblerData 复用就可以了

2018-05-16 03:07 UTC, 2youyou2 commented
把 CCLabel assembler data 删掉吧，canvas 和 context 的创建放到 `renderer/utils/ttf.js ` 里，然后通过一个方法可以让外界获取到，CCLabel 创建 texture 的时候就可以从 this._assembler 里获取了

2018-05-16 03:10 UTC, pandamicro commented
@2youyou2 在 label 实现中存不存在这种可能性：更新了 canvas 贴图之后，不立即使用结果而是隔一段时间再使用？还是说，都是更新贴图以后立即上传 GPU，之后就不需要了

2018-05-16 03:14 UTC, 2youyou2 commented
更新后是立刻上传的，现在没有其他使用

2018-05-16 05:39 UTC, 2youyou2 approved these changes

2018-05-16 08:39 UTC, pandamicro requested changes

2018-05-16 08:39 UTC, pandamicro commented on cocos2d/core/renderer/utils/label/ttf.js
> +let sharedLabelData;
外部变量使用 _ 开头：_sharedLabelData

这样在函数内部使用的时候就不会和局部变量混淆

2018-05-16 08:39 UTC, pandamicro commented on cocos2d/core/renderer/utils/label/ttf.js
> +        return sharedLabelData
分号

2018-05-17 01:55 UTC, pandamicro approved these changes

2018-05-17 01:56 UTC, merged