fix audio bug in wxgame for fireball/issues/7325
cocos/cocos-engine pull request #2709
Opened 2018-05-21 10:07 UTC by knoxHuang

Re: cocos-creator/fireball#7325

Changelog:
 * 修复 audio 
 * 完善 CC_WECHATGAME and CC_QQPLAY 宏的数值

2018-05-21 11:00 UTC, jareguo requested changes

2018-05-21 11:00 UTC, jareguo commented on cocos2d/audio/CCAudio.js
> +        var item;
这是为何？

2018-05-21 11:00 UTC, jareguo commented on cocos2d/audio/CCAudio.js
> +        if ((CC_QQPLAY || CC_WECHATGAME) && elem instanceof HTMLElement) {
elem instanceof HTMLElement 的判断是多余的

2018-05-22 01:34 UTC, knoxHuang commented on cocos2d/audio/CCAudio.js
> +        var item;
如果在 while 里面每次去 var item 不会消耗的话，也就无所谓

2018-05-22 01:36 UTC, jareguo commented on cocos2d/audio/CCAudio.js
> +        var item;
大哥，js 是有 hoisting 的

2018-05-22 01:52 UTC, jareguo approved these changes

2018-05-22 02:20 UTC, merged