fix EditorBox unable to input Chinese for fireball/issues/7286
cocos/cocos-engine pull request #2732
Opened 2018-05-24 09:32 UTC by knoxHuang

Re: cocos-creator/fireball#7286

Changelog:
 * 解决 EditorBox 无法输入中文的 bug
 * 看了一下 EditorBox 的注册事件，发现很相似所以就统一了

2018-05-24 11:14 UTC, pandamicro requested changes

2018-05-24 11:14 UTC, pandamicro commented on cocos2d/core/components/editbox/CCEditBoxImpl.js
> -            self._endEditing();
对于 textarea 和 input 的 keypress 事件区别很大，建议在 registrationInputEventListener 函数加一个类型参数，针对类型做不同的 keypress 处理

2018-05-25 06:32 UTC, pandamicro requested changes

2018-05-25 06:32 UTC, pandamicro commented on cocos2d/core/components/editbox/CCEditBoxImpl.js
> +                cc.game.canvas.focus();
还有 _endEditing 调用和 _text 设置被你吃了吗？

2018-05-25 07:10 UTC, pandamicro commented
冲突了

2018-05-25 07:11 UTC, knoxHuang commented
稍等，我修复一下

2018-05-25 07:17 UTC, pandamicro requested changes

2018-05-25 07:17 UTC, pandamicro commented on cocos2d/core/components/editbox/CCEditBoxImpl.js
> +        }
这是另一个 PR 删除的代码，不要加回来

2018-05-25 07:30 UTC, pandamicro approved these changes

2018-05-25 07:30 UTC, merged