sync showLabels and resize view on input blur on mobile platform
cocos/cocos-engine pull request #2742
Opened 2018-05-25 10:00 UTC by umbrellaPP

Re: cocos-creator/fireball#

Changelog:
 *

2018-05-27 15:33 UTC, pandamicro requested changes

2018-05-27 15:33 UTC, pandamicro commented on cocos2d/core/components/editbox/CCEditBoxImpl.js
> -        }
上面的 keypress 里面也有这段代码，但是对于 text area 该如何判断什么时候应该给 delegate editBoxEditingReturn 麻烦跟 @2youyou2 @knoxHuang 讨论一下

2018-05-28 03:17 UTC, umbrellaPP commented on cocos2d/core/components/editbox/CCEditBoxImpl.js
> -        }
这里并没有把这段代码删掉，只是把他挪到上边的showLabel  里边去调用了

2018-05-28 10:14 UTC, pandamicro commented on cocos2d/core/components/editbox/CCEditBoxImpl.js
> -        }
我知道，我是说要统一代码逻辑，keypress 中会有可能出现重复逻辑，重复调用 editBoxEditingDidEnded

2018-05-29 03:27 UTC, umbrellaPP commented on cocos2d/core/components/editbox/CCEditBoxImpl.js
> -        }
这里边，不存在重复逻辑。keypress 注册的是editBoxEditingReturn 
textArea 的编辑器属性面板 还是会暴露给用户定义 keyReturn 事件，所以还是需要保留给 textArea 注册input 事件，这样才会回调用户定义的keyReturn 事件

2018-05-29 09:26 UTC, pandamicro commented on cocos2d/core/components/editbox/CCEditBoxImpl.js
> +                showLabel();
hideLabel

2018-05-29 09:33 UTC, pandamicro commented on cocos2d/core/components/editbox/CCEditBoxImpl.js
> -        }
哦哦，我看错了，不过检查了一下逻辑，上面 keypress 里面，应该要调整一下顺序，editBoxEditingReturn 应该在 editBoxEditingDidEnded 之前派发

2018-05-29 10:24 UTC, PPpro commented on cocos2d/core/components/editbox/CCEditBoxImpl.js
> -        }
已经修改

2018-05-29 11:04 UTC, pandamicro approved these changes

2018-05-29 11:05 UTC, merged