fix Label + LabelOutline display error for fireball/issues/7398
cocos/cocos-engine pull request #2748
Opened 2018-05-28 09:55 UTC by knoxHuang

Re: cocos-creator/fireball#7398

Changelog:
 * 修复 label + 描边显示错误
 * 调整一下组件更新 color 的代码
 * 完善代码

2018-05-28 10:04 UTC, pandamicro requested changes

2018-05-28 10:04 UTC, pandamicro commented on cocos2d/core/components/CCLabel.js
> +    updateColor () {
改成下划线私有 API 吧

2018-05-28 10:04 UTC, pandamicro commented on cocos2d/core/renderer/render-flow.js
> +    comp.updateColor();
要检查 comp 组件是否存在

2018-05-28 10:04 UTC, pandamicro commented on cocos2d/core/renderer/utils/label/ttf.js
> +    _updateVerts() {
这个修改什么鬼，你用来自动格式化代码的工具设置是不是有问题

2018-05-28 10:04 UTC, pandamicro commented on cocos2d/core/renderer/utils/label/ttf.js
> +                    this._measureText(_context));
这里格式化后更难读

2018-05-28 10:04 UTC, pandamicro commented on cocos2d/core/renderer/utils/label/ttf.js
> +                            this._measureText(_context));
同上

2018-05-28 10:04 UTC, pandamicro commented on cocos2d/core/renderer/webgl/assemblers/label/ttf.js
> +        comp._material.color = cc.Color.WHITE;
不需要了，在 updateColor 里面不更新 material 就行了

2018-05-28 10:04 UTC, pandamicro commented on cocos2d/core/components/CCLabel.js
> +        this._super();
不要调用 super

2018-05-29 02:04 UTC, pandamicro approved these changes

2018-05-29 02:09 UTC, 2youyou2 commented on cocos2d/core/components/CCLabel.js
> +const COLOR = 1 << 3;
不要自己定义 RenderFlow 的 flag 值，RenderFlow 增加 flag 的时候这里就可能挂掉

2018-05-29 02:10 UTC, 2youyou2 commented on cocos2d/core/components/CCLabel.js
> +        this.node._renderFlag &= ~COLOR;
用 RenderFlow.FLAG_COLOR

2018-05-29 02:10 UTC, 2youyou2 commented on cocos2d/core/components/CCRenderComponent.js
> +            this.node._renderFlag &= ~COLOR;
一样

2018-05-29 02:42 UTC, pandamicro requested changes
改完自己验证一下

2018-05-29 02:42 UTC, pandamicro commented on cocos2d/core/components/CCRenderComponent.js
> +            this.node._renderFlag &= RenderFlow.FLAG_COLOR;
草。。。改的时候小心点啊，差点又被你埋坑。。。 ~ 被你吃了吗？？？

2018-05-29 02:42 UTC, pandamicro commented on cocos2d/core/components/CCLabel.js
> +        this.node._renderFlag &= RenderFlow.FLAG_COLOR;
一样

2018-05-29 02:53 UTC, pandamicro approved these changes

2018-05-29 02:53 UTC, knoxHuang commented
已验证

2018-05-29 02:57 UTC, merged