remove platform-related code in editBoxImpl
cocos/cocos-engine pull request #2813
Opened 2018-06-06 11:09 UTC by umbrellaPP

Re: cocos-creator/fireball#7481

2018-06-07 05:04 UTC, pandamicro requested changes

2018-06-07 05:04 UTC, pandamicro commented on cocos2d/core/components/editbox/CCEditBoxImpl.js
> +            this.createInput();
JSB 也需要走 createInput

2018-06-07 05:04 UTC, pandamicro commented on jsb/builtin/jsb_editbox.js
> +    let KeyboardReturnType = cc.EditBox.KeyboardReturnType;
可以放在函数体外

2018-06-07 05:05 UTC, umbrellaPP commented on cocos2d/core/components/editbox/CCEditBoxImpl.js
> +            this.createInput();
JSB 没有focus 事件，所以JSB 的调用方式是放在 下面的 _onTouchBegin 这里

2018-06-07 05:09 UTC, umbrellaPP commented on cocos2d/core/components/editbox/CCEditBoxImpl.js
> +            this.createInput();
@minggo 我们在每次调用 _onTouchBegin 的时候都去注册onConfirm  onInput onComplete 回调，这样没问题吗

2018-06-07 07:04 UTC, minggo commented on cocos2d/core/components/editbox/CCEditBoxImpl.js
> +            this.createInput();
没问题。弹出输入框后，引擎无法处理触摸事件。
为什么是 `!CC_JSB` 呢？应该是  `CC_JSB` 吧。

2018-06-07 07:05 UTC, umbrellaPP commented on cocos2d/core/components/editbox/CCEditBoxImpl.js
> +            this.createInput();
哦，这里是在 setInputMode 时候调用的，所以是 !CC_JSB

2018-06-07 07:11 UTC, minggo commented on cocos2d/core/components/editbox/CCEditBoxImpl.js
> +            this.createInput();
为什么在要在 setInputMode 调用呢？

2018-06-07 07:15 UTC, umbrellaPP commented on cocos2d/core/components/editbox/CCEditBoxImpl.js
> +            this.createInput();
这里主要是适配 web 和 下游戏的时候调用的，在这里创建和初始化 input dom 节点。
onTouchBegin 那里如果是 jsb环境, 也会调用

2018-06-07 07:28 UTC, minggo commented on cocos2d/core/components/editbox/CCEditBoxImpl.js
> +            this.createInput();
这样在设置 input mode 的时候就会弹出输入框了，这个场景不对吧。

2018-06-07 07:33 UTC, umbrellaPP commented on cocos2d/core/components/editbox/CCEditBoxImpl.js
> +            this.createInput();
web、下游戏跟 jsb 的实现有点不同，他们有 focus 事件，所以只会在focus 的时候弹出输入框。。。所以在这里createInput 就是创建 input节点，还有注册 focus等事件。。。相当于初始化工作

2018-06-07 07:51 UTC, minggo commented on cocos2d/core/components/editbox/CCEditBoxImpl.js
> +            this.createInput();
但是 createInput 的逻辑包含了弹出输入框的操作，如果要做到你说的逻辑得改代码。

2018-06-07 07:51 UTC, pandamicro commented on cocos2d/core/components/editbox/CCEditBoxImpl.js
> +            this.createInput();
感觉有点怪，你仔细看下原来的逻辑，如果是 JSB，实惠走 this._createDomInput 的

2018-06-07 07:53 UTC, minggo commented on cocos2d/core/components/editbox/CCEditBoxImpl.js
> +            this.createInput();
哦，你这个是 impl 的 createInput，那没问题。

2018-06-07 07:56 UTC, umbrellaPP commented on cocos2d/core/components/editbox/CCEditBoxImpl.js
> +            this.createInput();
> 感觉有点怪，你仔细看下原来的逻辑，如果是 JSB，实惠走 this._createDomInput 的
jsb 的话，已经在 jsb_editbox.js 里重写了createInput， 所以不会走到 this._createDomInput

2018-06-07 08:04 UTC, umbrellaPP commented on cocos2d/core/components/editbox/CCEditBoxImpl.js
> +            this.createInput();
其实这样子重写，可能是会让代码有点难阅读

2018-06-07 10:09 UTC, pandamicro approved these changes

2018-06-07 10:11 UTC, merged

2018-06-08 01:33 UTC, minggo commented on jsb/builtin/jsb_editbox.js
> +let KeyboardReturnType = cc.EditBox.KeyboardReturnType;
这时候 cc.EditBox 是没有定义的，运行会导致直接崩溃。