fixed opacity bug for fireball/issues/7555
cocos/cocos-engine pull request #2847
Opened 2018-06-11 07:39 UTC by knoxHuang

Re: cocos-creator/fireball#

Changelog:
 * 修复如果设置透明度为 0，后在设置为 255 后，节点无法显示

2018-06-11 09:34 UTC, pandamicro requested changes

2018-06-11 09:34 UTC, pandamicro commented on cocos2d/core/renderer/render-flow.js
> +    let opacityLevel = (node._opacity <= 255) ? 1 : 0;
这样改就没意义了，opacity 即便保持默认的 255 不变，也会导致所有子节点的 color dirty 以及重新计算，损耗太高了

2018-06-12 04:43 UTC, pandamicro commented on cocos2d/core/renderer/render-flow.js
> +    let opacityLevel = (node._opacity <= 255) ? 1 : 0;
@2youyou2 看下有什么建议

2018-06-12 05:55 UTC, 2youyou2 commented on cocos2d/core/renderer/render-flow.js
> +    let opacityLevel = (node._opacity <= 255) ? 1 : 0;
要不 node 里加个 opacityDirty ?

2018-06-12 07:42 UTC, pandamicro commented on cocos2d/core/renderer/render-flow.js
> +    let opacityLevel = (node._opacity <= 255) ? 1 : 0;
是不是加个 flag 更好，以后还要独立 opacity 和 color

2018-06-12 08:36 UTC, 2youyou2 commented on cocos2d/core/renderer/render-flow.js
> +    let opacityLevel = (node._opacity <= 255) ? 1 : 0;
可以

2018-06-12 15:14 UTC, pandamicro commented on cocos2d/core/renderer/render-flow.js
> +    let opacityLevel = (node._opacity <= 255) ? 1 : 0;
那你跟 knox 说下具体怎么做，knox 也可以更了解 render flag 机制

2018-06-13 09:08 UTC, 2youyou2 commented on cocos2d/core/CCNode.js
> +                    this._renderFlag |= RenderFlow.FLAG_OPACITY;
改了 opacity 也要影响 FLAG_COLOR

2018-06-13 09:08 UTC, 2youyou2 commented on cocos2d/core/renderer/render-flow.js
> +const OPACITY = 1 << 4;
OPACITY 应该在 COLOR 前

2018-06-13 09:09 UTC, 2youyou2 commented on cocos2d/core/renderer/render-flow.js
> +    let opacityLevel = (node._opacity <= 255) ? 1 : 0;
这就不用判断 opacityLevel 了，直接 _walker.parentOpacityDirty ++

2018-06-13 09:19 UTC, 2youyou2 commented on cocos2d/core/CCNode.js
> +                    this._renderFlag |= RenderFlow.FLAG_OPACITY;
this._renderFlag |= RenderFlow.FLAG_OPACITY | RenderFlow.FLAG_COLOR;

2018-06-13 09:20 UTC, 2youyou2 approved these changes

2018-06-13 10:45 UTC, pandamicro approved these changes

2018-06-13 10:47 UTC, merged