modify the engine identify function about UCbrowser
cocos/cocos-engine pull request #2881
Opened 2018-06-21 03:10 UTC by ColinCollins

Re: cocos-creator/engine#2866

Changelog:
1. 开启引擎对 UC 11 版本以上的开放 Webgl 功能
2. 修改特殊的 ucbs 版本识别内容

2018-06-21 03:15 UTC, ColinCollins commented
![image](https://user-images.githubusercontent.com/35832931/41696003-5a94c020-7544-11e8-9951-02e89256e80a.png)

2018-06-21 04:11 UTC, pandamicro commented
麻烦用 ccsys 中的逻辑跑一下 issue 中的 ua，验证

sys.browserType, sys.browserVersion 的值分别是什么

2018-06-21 07:18 UTC, ColinCollins commented
![image](https://user-images.githubusercontent.com/35832931/41703527-3433cb48-7566-11e8-81d6-e7e18a682cd4.png)
上面的是 ua
下面的是 Type 和 Version
没有获取到

2018-06-21 07:40 UTC, ColinCollins commented
![image](https://user-images.githubusercontent.com/35832931/41704612-4cf6a79c-7569-11e8-9d68-9fca34701661.png)
![image](https://user-images.githubusercontent.com/35832931/41704624-5685b7bc-7569-11e8-979c-7bf6d7809f9d.png)
我将 nav 的内容替换成 issue 中的 string 之后是正常识别 browserType 的

2018-06-21 07:43 UTC, ColinCollins commented
这个是未调整 nav 直接通过 window.navigator.userAgent 获取信息在 Android uc 浏览器上测试的结果
![image](https://user-images.githubusercontent.com/35832931/41704820-df3ca340-7569-11e8-88c3-96ba06305c8f.png)

2018-06-21 08:28 UTC, pandamicro commented
看了一下版本号，ucbs 的版本号和 uc 不同，这样在 ucbs 上还是无法支持 webgl 渲染，给 browser type 加一个新的吧 BROWSER_TYPE_UCBS，注释用 uc third party integration，然后在 browser type 的正则表达式中添加 ucbs 的识别（优先级高于 ucbrowser），这样在下面的 webgl 判断中，就不会被 uc 的版本判断给禁用了

2018-06-21 09:45 UTC, ColinCollins commented
![image](https://user-images.githubusercontent.com/35832931/41711300-65a15fb0-757a-11e8-9d0e-1346d8ee3ce8.png)

2018-06-21 10:56 UTC, pandamicro requested changes

2018-06-21 10:56 UTC, pandamicro commented on cocos2d/core/platform/CCSys.js
> +        var typeReg2 = /qqbrowser|chrome|safari|firefox|trident|opera|opr\/|oupeng|ucbrowser/i;
也不用把 ucbrowser 移到最后啦，这样会识别出 safari 之类的很奇怪的，ucbrowser 的优先级低于 ucbs 就可以了。改完以后试试看普通 uc 浏览器有没有问题

2018-06-22 09:51 UTC, ColinCollins commented
最后修改部分：
修改了针对“猎豹浏览器”两个平台的识别，以及针对当前浏览器识别方案进行了修改

2018-06-22 09:59 UTC, pandamicro requested changes

2018-06-22 09:59 UTC, pandamicro commented on cocos2d/core/platform/CCSys.js
> +        var typeReg1 = /(mqqbrowser|micromessenger|qq|sogou|qzone|liebao|maxthon|ubrowser|ucbrowser|ucbs|lb|360 aphone|360|baiduboxapp|baidu|maxthon|mxbrowser|miui)+(mobile)?(browser)?(fast)?\/?([\d.
lb, 360 这种太容易命中，别加，而且这里的 type 对应的是上面的 type 常量，没有常量判断出来用户也没法跟我们的预设做对比。
ubrowser 这种桌面的也不用加。
mobile 和 browser 如果这样写的话，你还要对应 type 常量做收敛。是有哪几种情况让你决定这样写？
fast 不清楚什么意义

这里你是希望用逐个找 match 来让顺序优先级有效果吧？但是你没改正则的使用方式没意义啊，这样 ucbrowser 在 ucbs 之前仍然会被识别成 ucbrowser 的

2018-06-22 10:05 UTC, ColinCollins commented on cocos2d/core/platform/CCSys.js
> +        var typeReg1 = /(mqqbrowser|micromessenger|qq|sogou|qzone|liebao|maxthon|ubrowser|ucbrowser|ucbs|lb|360 aphone|360|baiduboxapp|baidu|maxthon|mxbrowser|miui)+(mobile)?(browser)?(fast)?\/?([\d.
emmm,这样改是一个简便的改法，lb 去掉是 ok 的 360 是原本就有的，上面的修改提示应该是按照符号修改的来了。
最后那个部分我刚才改错了，应该去掉问号是正确的，现在的修改方案是按照大部分的浏览器内核显示模式 browserType/browserVersion 这样的格式修改的，lbbrowser 这个是猎豹桌面浏览器太特殊了，他没有版本号，最后会被识别为 chrome

2018-06-22 10:09 UTC, ColinCollins commented on cocos2d/core/platform/CCSys.js
> +        var typeReg1 = /(mqqbrowser|micromessenger|qq|sogou|qzone|liebao|maxthon|ubrowser|ucbrowser|ucbs|lb|360 aphone|360|baiduboxapp|baidu|maxthon|mxbrowser|miui)+(mobile)?(browser)?(fast)?\/?([\d.
fast 是为了适配手机端的猎豹浏览器 browser 和 mobile 是适配遨游好像

2018-06-22 10:58 UTC, pandamicro commented on cocos2d/core/platform/CCSys.js
> +        var typeReg1 = /mqqbrowser|micromessenger|qq|sogou|qzone|liebao|maxthon|ucbs|360 aphone|360|baiduboxapp|baidu|maxthon|mxbrowser|miui/i;
360browser 被你改成 360 了，还有 baidubrowser，miuibrowser

2018-06-22 11:25 UTC, pandamicro approved these changes

2018-06-22 11:25 UTC, merged