support compress texture
cocos/cocos-engine pull request #3039
Opened 2018-08-01 06:46 UTC by 2youyou2

Re: cocos-creator/fireball#7906

Changelog:
 * support compress texture

2018-08-02 02:04 UTC, 2youyou2 commented on cocos2d/core/assets/CCTexture2D.js
> +                    (this._premultiplyAlpha ? 1 : 0) + ',' + this.width + ',' + this.height;
压缩纹理后大小会被改变，需要记录之前 texture 的大小

2018-08-02 09:05 UTC, jareguo requested changes

2018-08-02 09:05 UTC, jareguo commented on cocos2d/core/assets/CCTexture2D.js
> +        this._compressed = false;
感觉有 _format 就行了，没必要专门存一个 _compressed

2018-08-02 09:05 UTC, jareguo commented on cocos2d/core/assets/CCTexture2D.js
> +        this._compressed = false;
要方便判断的话，考虑封装一个静态方法，cc.Texture2D._isCompressed(texture) ?

2018-08-02 09:05 UTC, jareguo commented on cocos2d/core/platform/CCMacro.js
> +        SupportTextureFormats = ['.pvr'].join(SupportTextureFormats);
这个 join 是不是写错了？这样得到的值也只是 '.pvr'

2018-08-02 09:05 UTC, jareguo commented on cocos2d/core/platform/CCMacro.js
> +cc.macro.SupportTextureFormats = SupportTextureFormats;
要不要统一用 SUPPORT_TEXTURE_FORMATS

2018-08-02 09:05 UTC, jareguo commented on cocos2d/core/renderer/render-engine.js
> +          this$1._extensions[name] = ext;
这里加一个 break; 会好点

2018-08-02 09:05 UTC, jareguo commented on cocos2d/core/assets/CCTexture2D.js
> +        if (fields.length === 8) {
感觉这个判断是多余的。如果这个判断有必要留着，那就应该兼容 .length === 6 和 8 两种情况

2018-08-02 09:05 UTC, jareguo commented on cocos2d/core/assets/CCTexture2D.js
> +            if (!Array.isArray(natives)) {
这里拿的是 ext，不会是 arrary 吧？下面 `this._setRawAsset(ext);` 时，传入的也不是 array

2018-08-02 09:05 UTC, jareguo commented on cocos2d/core/assets/CCTexture2D.js
> +                tmpExt = Texture2D.extnames[tmpExt];
需要判断一下 tmpExt 拿不到的情况，例如 `tmpExt = Texture2D.extnames[tmpExt] || extFormat;`。如果后缀是其它类型（比如 gif？），就没办法从 extnames 数组里拿到。

2018-08-02 09:05 UTC, jareguo commented on cocos2d/core/assets/CCTexture2D.js
> +                    let extFormat = ext.split('@');
这个 native 里面的 @，是在哪里生成的呢？

2018-08-03 06:43 UTC, 2youyou2 commented on cocos2d/core/assets/CCTexture2D.js
> +                    let extFormat = ext.split('@');
压缩纹理的时候生成的

2018-08-03 07:13 UTC, dumganhar commented on cocos2d/core/load-pipeline/loader.js
etc怎么也用loadpvr？

2018-08-03 07:23 UTC, 2youyou2 commented on cocos2d/core/load-pipeline/loader.js
https://github.com/toji/texture-tester/blob/master/js/webgl-texture-util.js#L457

web 上判断的逻辑是一样的

2018-08-04 05:58 UTC, jareguo approved these changes

2018-08-05 04:03 UTC, pandamicro requested changes

2018-08-05 04:03 UTC, pandamicro commented on cocos2d/core/assets/CCTexture2D.js
> +     * @property RGB_PVRTC_2BPPV1
RGBA_PVRTC_2BPPV1

2018-08-05 04:03 UTC, pandamicro commented on cocos2d/core/assets/CCTexture2D.js
> +     * @property RGB_PVRTC_2BPPV1
RGB_PVRTC_4BPPV1

2018-08-05 04:03 UTC, pandamicro commented on cocos2d/core/assets/CCTexture2D.js
> +     * @property RGB_PVRTC_2BPPV1
RGBA_PVRTC_4BPPV1

2018-08-05 04:03 UTC, pandamicro commented on cocos2d/core/assets/CCTexture2D.js
> +            set (asset) {
不应该叫 asset 吧，这个对象不是 asset 类型，是一个 raw data 类型，直接用 data 吧

2018-08-05 04:03 UTC, pandamicro commented on cocos2d/core/assets/CCTexture2D.js
> +        this._exportedExts = null;
用 CC_EDITOR 限定一下吧

2018-08-05 04:03 UTC, pandamicro commented on cocos2d/core/assets/CCTexture2D.js
> +        opts.images = [opts.image];
还需要添加 hasMipmap, premultiplyAlpha, flipY, filter 和 wrap option

2018-08-05 04:03 UTC, pandamicro commented on cocos2d/core/assets/CCTexture2D.js
> +            exportedExts = exportedExts.map(function (ext) {
这个 function 独立出来吧，否则每次进入 serialize 都会创建 function

2018-08-05 04:03 UTC, pandamicro commented on cocos2d/core/load-pipeline/loader.js
> +function loadPVR (item) {
改为 loadCompressedTex 吧，清晰一些比较好

2018-08-05 04:03 UTC, pandamicro commented on cocos2d/core/load-pipeline/loader.js
> +const COMPRESSED_RGB_ETC1_WEBGL = 0x8D64;
上面这几个加上 GL_ 前缀

2018-08-05 04:03 UTC, pandamicro commented on cocos2d/core/load-pipeline/loader.js
> +        break;
这些 internalFormat 好像没有用啊？是不是只是用来判断支持格式的？如果是的话，不需要 internalFormat 参数吧？只要把 case 连起来，保证这些 case 不走 errorCallback 就好了把

2018-08-05 04:03 UTC, pandamicro commented on cocos2d/core/platform/CCMacro.js
> +cc.macro.SUPPORT_TEXTURE_FORMATS = SUPPORT_TEXTURE_FORMATS;
加一下 API 注释，说明目前的格式和平台支持情况

2018-08-05 04:03 UTC, pandamicro commented on cocos2d/core/renderer/render-engine.js
> +    var vendorPrefixes = ["", "WEBKIT_", "MOZ_"];
哪些情况会出现这些前缀？目前格式还不统一？

2018-08-05 04:03 UTC, pandamicro commented on cocos2d/core/renderer/render-engine.js
> +    var vendorPrefixes = ["", "WEBKIT_", "MOZ_"];
哪些情况会出现这些前缀？目前格式还不统一？

2018-08-06 02:36 UTC, 2youyou2 commented on cocos2d/core/renderer/render-engine.js
> +    var vendorPrefixes = ["", "WEBKIT_", "MOZ_"];
ios safari 是 `WEBKIT_ ` 前缀，`MOZ_ ` 还不知道，ios 的火狐？

https://github.com/toji/texture-tester/blob/master/js/webgl-texture-util.js#L337

2018-08-06 06:22 UTC, pandamicro approved these changes

2018-08-06 06:22 UTC, merged