adaptive 1.9-release to runtime add CC_RUNTIME macro
cocos/cocos-engine pull request #3103
Opened 2018-08-16 09:08 UTC by W-MTZing

2018-08-28 06:24 UTC, pandamicro requested changes

2018-08-28 06:24 UTC, pandamicro commented on cocos2d/core/CCGame.js
> +            jsb.onHide = onHidden;
1.x JSB 可能不包含这个 API，需要限定在 Runtime 环境

2018-08-28 06:24 UTC, pandamicro commented on cocos2d/core/CCGame.js
> +        if (isWeChatGame || CC_JSB) {
这里需要细分 1.x JSB 和 runtime 环境，1.x JSB 没有 __cccanvas, __ccgl 这些变量

2018-08-28 06:24 UTC, pandamicro commented on cocos2d/core/editbox/CCSGEditBox.js
> +        var text = (CC_WECHATGAME || CC_QQPLAY || CC_JSB) ? this._editBox._text : this._edTxt.value;
用 CC_RUNTIME

2018-08-28 06:24 UTC, pandamicro commented on cocos2d/core/editbox/CCSGEditBox.js
> +            sys.platform !== sys.QQ_PLAY && !CC_JSB && sys.isMobile && this._editingMode) {
同上

2018-08-28 06:24 UTC, pandamicro commented on cocos2d/core/editbox/CCSGEditBox.js
> +    proto._createJSBInput = function () {
这是 runtime 专有的，JSB 并不是走这个逻辑

2018-08-28 06:24 UTC, pandamicro commented on cocos2d/core/platform/CCSys.js
> +if (cc.sys && !CC_RUNTIME) return;
为什么需要这个修改？

2018-08-28 06:24 UTC, pandamicro commented on cocos2d/core/platform/CCSys.js
> +sys.isNative = CC_JSB;
JSB sys 会在 jsb_boot.js 中处理，这里只需要处理 Runtime 环境

2018-08-28 06:24 UTC, pandamicro commented on cocos2d/core/platform/CCSys.js
> +sys.isBrowser = typeof window === 'object' && typeof document === 'object' && !CC_WECHATGAME && !CC_QQPLAY && !CC_JSB;
同上

2018-08-28 06:24 UTC, pandamicro commented on cocos2d/core/platform/CCSys.js
> +} else if (CC_JSB) {
同上

2018-08-28 06:24 UTC, pandamicro commented on cocos2d/core/platform/CCSys.js
> +    if (CC_JSB) {
同上

2018-08-28 06:24 UTC, pandamicro commented on cocos2d/core/platform/CCSys.js
> +    if (CC_JSB) {
以上全部都是

2018-08-28 06:24 UTC, pandamicro commented on cocos2d/core/platform/CCView.js
> +        if (this._isAdjustViewPort && !CC_WECHATGAME && !CC_QQPLAY && !CC_JSB) {
JSB CCView 实现也在 native 端，这里只需要判断 RUNTIME 环境

2018-08-28 06:24 UTC, pandamicro commented on gulp/tasks/engine.js
> +// ];
这里对 JSB 很关键，不能这么改，你只能添加一个 Runtime 特有的 skip modules，并且只有在构建 Runtime 的时候使用。

2018-08-28 06:24 UTC, pandamicro commented on gulp/util/utils.js
> +    res['CC_SUPPORT_JIT'] = !(res['CC_WECHATGAME'] || res['CC_QQPLAY'] || res['CC_JSB']);
1.x JSB 是支持的，只是 Runtime 环境不支持而已

2018-08-28 06:24 UTC, pandamicro commented on index.js
> +    require('./jsb/jsb-loader.js');
Runtime 需求

2018-08-28 06:24 UTC, pandamicro commented on jsb/jsb-loader.js
> +function downloadImage(item, callback) {
放在 RUNTIME 条件中

2018-08-28 09:54 UTC, pandamicro commented on gulp/tasks/engine.js
> +if(CC_RUNTIME) {
这个有测试过吗？

2018-08-28 09:54 UTC, pandamicro commented on jsb/jsb-loader.js
> +    jsb.fileUtils = {
为什么要把 fileUtils 的内容放在 jsb-loader 中？

2018-08-28 09:56 UTC, W-MTZing commented on gulp/tasks/engine.js
> +if(CC_RUNTIME) {
还没有 我正在测试 gulp的时候编译不过

2018-08-28 09:58 UTC, W-MTZing commented on jsb/jsb-loader.js
> +    jsb.fileUtils = {
是这样考虑的，runtime平台里面的FileUtils没有注册了 我为了匹配旧的游戏嵌套了一套实现，至于放这里是我是想加载的统一放置

2018-08-28 10:50 UTC, W-MTZing commented on gulp/tasks/engine.js
> +// ];
和 jare 讨论过了一下，1.9.3版本没有runtime的平台,用户需要手获取v1.9-release-runtime 分支并且手动打包。所以这里只需要考虑runtime的情况就可以了

2018-08-29 06:13 UTC, pandamicro approved these changes

2018-08-29 06:13 UTC, merged