修复粒子系统的两个问题。
cocos/cocos-engine pull request #3143
Opened 2018-08-24 08:08 UTC by xianyinchen

1. 配置粒子的属性如下 duration=-1，emissionRate=1，totalParticles=1，粒子错误的只会发射一次。
2. 编辑器粒子消亡后存在残影问题，因为时间有残余，粒子的表现没有计算到最后，就消亡了，而导致顶点数据没有被刷新。

2018-08-24 08:13 UTC, xianyinchen commented on cocos2d/particle/particle-simulator.js
> +            // life
这里是修复残影问题，必须尽可能完全计算完粒子的顶点值。

2018-08-24 08:28 UTC, jareguo commented
这些代码应该都是从 -x 抄的，-x 有这些问题吗？

2018-08-24 08:33 UTC, xianyinchen commented
没比对过-x，是发现的问题，可测试！问题1，浏览器可验证问题2，通过编辑器测试，可验证。

2018-08-27 07:48 UTC, pandamicro requested changes

2018-08-27 07:48 UTC, pandamicro commented on cocos2d/particle/particle-simulator.js
> +        }
不需要在这里添加，只要在 Step 末尾修改为

```
if (particles.length > 0) {
        buffer.uploadData();
        psys._ia._count = particles.length * 6;
    }
    else if (!this.active) {
        this.finished = true;
        psys._finishedSimulation();
    }
```

2018-08-27 07:49 UTC, pandamicro commented on cocos2d/particle/particle-simulator.js
>              }
这个判断直接删除

2018-08-27 11:46 UTC, closed without merging

2018-08-27 11:46 UTC, pandamicro commented
已合并