add is3DNode property
cocos/cocos-engine pull request #3151
Opened 2018-08-28 03:16 UTC by 2youyou2

Re: cocos-creator/fireball#7907

Changelog:
 * add is3DNode property

2018-08-28 04:03 UTC, jareguo commented on cocos2d/core/CCNode.js
> +        /**
不进入文档的话就用 `/*` 而不是 `/**` 吧，不然万一哪个人把 `@property is3DNode` 加上了就会跑到文档中了

2018-08-28 04:17 UTC, jareguo commented on cocos2d/core/CCNode.js
> +        is3DNode: {
建议设置成私有变量，防止用户误用，或者以为可以在游戏中把节点“变成 3D”。

2018-08-28 04:17 UTC, jareguo commented on cocos2d/core/CCNode.js
> +        is3DNode: {
这个变量是否运行时也要用到呢？比如 2D 就用 affine transform 就够了，所以运行时可以根据这个属性快速判断所需要的计算方式。
如果运行时用不到，建议也调整下变量名，is3DNode 体现的是数据结构上的差异，但是深层次的差异在于（编辑器）操作上，所以叫做 _in3DMode 可能会好点。

2018-08-29 07:06 UTC, 2youyou2 commented on cocos2d/core/platform/CCMacro.js
> -js.getset(cc.macro, 'ENABLE_3D', function () {
干掉了 `cc.macro. ENABLE_3D`, 改成用模块定义区分。
在模块选项中添加了 3d 选项，勾选了后会将 Node 的方法注册为 3d 方法

2018-08-29 07:07 UTC, 2youyou2 commented on cocos2d/core/utils/polyfill-3d.js
> +cc.js.getset(proto, 'is3DNode', function () {
is3DNode 可以在运行时切换，3d 的节点才会用 3d  的矩阵计算

2018-08-29 07:09 UTC, 2youyou2 commented on cocos2d/core/CCNode.js
> +js.getset(_p, 'position', _p.getPosition, _p.setPosition, false, true);
需要在 polyfill-3d 里重写这两个属性，需要定义属性为 configurable

2018-08-29 07:44 UTC, jareguo commented on cocos2d/core/components/CCSkinMeshRenderer.js
> +cc.SkinMeshRenderer = module.exports = SkinMeshRenderer;
应该是叫做 SkinnedMeshRenderer 才对吧？

2018-08-29 07:45 UTC, jareguo commented on modules.json
> +      "./cocos2d/core/utils/polyfill-3d.js"
建议对所有 3D 相关代码进行裁剪，避免影响原有项目的包体。
另外，3D 项目，也可以考虑就 SkinnedMesh + SkeletonAnimation 单独拆一个则子模块。

2018-08-29 08:57 UTC, 2youyou2 commented on cocos2d/core/3d/index.js
> +require('./CCSkinnedMeshRenderer');
3d 模块都挪到了 3d 文件夹下

2018-08-29 09:25 UTC, jareguo commented on cocos2d/core/3d/polyfill-3d.js
> + * 切换 2D/3D 节点，2D 节点会有更高的运行效率
这个 polyfill.js 是不进入 api 的，应该定义在 Node 上面。

2018-08-29 09:30 UTC, jareguo commented on cocos2d/core/renderer/render-engine.js
> +  MeshMaterial: MeshMaterial,
这个文件增加的代码太多了，会影响到 2D 项目。可以放到 3d 目录下，动态注入到 render-engine 中吗？所有渲染都要放到一起也很奇怪。

2018-08-29 09:46 UTC, 2youyou2 commented on cocos2d/core/renderer/render-engine.js
> +  MeshMaterial: MeshMaterial,
MeshMaterial 要挪过去的话, mesh shader 也应该挪过去，不过 engine 还没有集成 shader 的编译，可以后面优化下

2018-08-29 09:50 UTC, jareguo commented on cocos2d/core/renderer/render-engine.js
> +  MeshMaterial: MeshMaterial,
对，这个文件是外部仓库的…… 好蛋疼，早点合并 renderer.js 吧

2018-08-30 05:57 UTC, jareguo approved these changes

2018-08-30 06:12 UTC, pandamicro requested changes

2018-08-30 06:12 UTC, pandamicro commented on cocos2d/core/3d/CCSkeletonAnimationClip.js
> +            handle.result.push(this, '_modelSetter', this._modelUuid);
不太理解这个操作是什么意义

2018-08-30 06:12 UTC, pandamicro commented on cocos2d/core/3d/CCSkinnedMeshRenderer.js
> +        this.updateMatrices();
不能用被动更新吗？当 joint 修改的时候更新 matrices，然后 commit data

2018-08-30 06:12 UTC, pandamicro commented on cocos2d/core/CCNode.js
>  misc.propertyDefine(Node, SameNameGetSets);
不要用 propertyDefine 了，都在下面列清楚吧

2018-08-30 06:12 UTC, pandamicro commented on cocos2d/core/renderer/render-engine.js
> +  if (!uniform || (uniform.isArray && uniform.value.length < value.length)) {
Array 长度变化的情况仍然是属于改动，不是创建，在 uniform 存在的分支里面，使用正确的数组长度更新，并且修改 oldValue 数组的长度比较好

2018-08-30 06:12 UTC, pandamicro commented on cocos2d/core/renderer/render-engine.js
> +  MeshMaterial: MeshMaterial,
做 Material API 设计的时候，开放 ProgramLib，这样就可以由上层模块自己添加 shader 和 material 定义了

2018-08-30 06:23 UTC, 2youyou2 commented on cocos2d/core/3d/CCSkinnedMeshRenderer.js
> +        this.updateMatrices();
不行，node 现在没有世界矩阵更新通知的机制

2018-08-30 06:31 UTC, pandamicro commented on cocos2d/core/3d/CCSkinnedMeshRenderer.js
> +        this.updateMatrices();
了解，我思考一下，目前就这么处理

2018-08-30 06:54 UTC, pandamicro approved these changes

2018-08-30 06:56 UTC, merged

2018-08-30 07:00 UTC, jareguo commented on cocos2d/core/3d/CCSkeletonAnimationClip.js
> +            handle.result.push(this, '_modelSetter', this._modelUuid);
不这样的话，loader 并不知道要加载依赖的 this._modelUuid

2018-08-31 07:34 UTC, dumganhar commented on cocos2d/core/3d/CCSkeletonAnimationClip.js
> + * !#zh 网格资源。
网络资源是什么？