improve mesh usage
cocos/cocos-engine pull request #3190
Opened 2018-09-04 06:22 UTC by 2youyou2

Re: cocos-creator/fireball#7907

Changelog:
 * support show mesh wireframe
 * support change vertexes in mesh

2018-09-04 06:54 UTC, jareguo commented
建议做好 2D/3D 需求的隔离，尽量不要增大 2D 包体。

2018-09-04 07:09 UTC, 2youyou2 commented
mesh 也添加一个模块就好了

2018-09-04 08:16 UTC, pandamicro requested changes

2018-09-04 08:16 UTC, pandamicro commented on cocos2d/core/3d/CCModel.js
> +        vb.data = vbData;
vbData 和 ibData 都应该是在 subMeshes 中可以索引到的，同时避免动态修改 VertexBuffer 和 IndexBuffer 的结构，建议 subMeshes 条目改为

```
{
    ia,
    vbData,
    ibData
}
```

2018-09-04 08:16 UTC, pandamicro commented on cocos2d/core/3d/CCModel.js
> +            let vb = this._createVB(bin, gltf, accessors, primitive.attributes);
应该先创建 
```
subMesh = {
    ibData: null,
    vbData: null,
    ia: new renderEngine.InputAssembler()
}
```

传入对象给 createVB，在 createVB 中直接设置结果

2018-09-04 08:16 UTC, pandamicro commented on cocos2d/core/renderer/webgl/assemblers/mesh-renderer.js
> +                    renderDatas.push( this.createWireFrameData(data.ia, data.material, renderer) );
这里应该传入 submeshes[i]，这样就可以比较方便获取 ia, vbData 和 ibData 了。

2018-09-05 01:35 UTC, jareguo commented on cocos2d/core/platform/CCMacro.js
> +    SHOW_MESH_WIREFRAME: false,
2.2 版本开始，这个变量需要能动态调整，编辑器需要用到

2018-09-05 01:37 UTC, jareguo commented on modules.json
> +      "./cocos2d/core/renderer/mesh-renderer.js"
mesh sprite 也属于该模块是吧？

2018-09-06 07:04 UTC, 2youyou2 commented on cocos2d/core/platform/CCMacro.js
> +    SHOW_MESH_WIREFRAME: false,
现在就支持

2018-09-06 07:05 UTC, 2youyou2 commented on modules.json
> +      "./cocos2d/core/renderer/mesh-renderer.js"
mesh sprite 的渲染依靠 sprite ，算 sprite 模块

2018-09-06 07:31 UTC, 2youyou2 commented on cocos2d/core/mesh/CCMesh.js
> +        this._vbs[0] = {
@pandamicro ibData 改为保存 在 `this. _vbs` 中

2018-09-06 07:32 UTC, 2youyou2 commented on cocos2d/core/mesh/CCMesh.js
> +            this._ibs[index] = {
ibData 保存在 `this._ibs` 中

2018-09-06 07:34 UTC, 2youyou2 commented on cocos2d/core/mesh/index.js
> +require('./CCMesh');
mesh 模块挪到一起了

2018-09-06 07:36 UTC, pandamicro approved these changes

2018-09-06 07:38 UTC, merged