modify the systemEvent note
cocos/cocos-engine pull request #3303
Opened 2018-09-25 03:28 UTC by ColinCollins

Re: https://github.com/cocos-creator/creator-api-docs/issues/89

因为 class 开头的模板不支持 example 的数据内容，所以暂时以这个形式描述。
如果一个需要一个 example 的展示内容，我去改一下模板。
![image](https://user-images.githubusercontent.com/35832931/45991162-2e68c880-c0b6-11e8-81c8-1fa573df4eb8.png)

2018-09-25 04:23 UTC, jareguo commented on cocos2d/core/event/system-event.js
> + * 如果你需要执行 SystemEvent 的属性方法，建议直接调用 cc.systemEvent 或者通过创建一个新的实例。<br>
不用假设人家需要执行 SystemEvent，你直接告诉人家怎么获取这个实例就好。另外在什么情况下需要创建实例，而不是使用 cc.systemEvent？

2018-09-25 09:17 UTC, ColinCollins commented on cocos2d/core/event/system-event.js
> + * 如果你需要执行 SystemEvent 的属性方法，建议直接调用 cc.systemEvent 或者通过创建一个新的实例。<br>
我想不出来。。。什么情况下需要创建新的系统事件实例，有一个不就足够了吗。。。。

2018-09-26 03:03 UTC, jareguo commented on cocos2d/core/event/system-event.js
> + * 执行 SystemEvent 的属性方法，需要通过调用单例对象 cc.systemEvent。
你可以通过 `cc.systemEvent` 获取到全局的 SystemEvent 实例。

```
@example
cc.systemEvent.on(xxx...
cc.systemEvent.off(xxx...
```

2018-09-26 03:14 UTC, ColinCollins commented on cocos2d/core/event/system-event.js
> + * 执行 SystemEvent 的属性方法，需要通过调用单例对象 cc.systemEvent。
这个开头模板格式没有 example 的数据内容展示，我调整一下吧

2018-09-26 07:07 UTC, ColinCollins commented
![image](https://user-images.githubusercontent.com/35832931/46062959-e9b85c80-c19d-11e8-9307-2d4bbaae5919.png)

2018-09-26 09:30 UTC, jareguo commented on cocos2d/core/event/system-event.js
> + *  ```
留一个空格就行，不需要两个吧……

2018-09-26 09:30 UTC, jareguo commented on cocos2d/core/event/system-event.js
> + * 参考示例: <br>
注意标点符号的全角半角。而且这里应该不用换行的，因为 ``` 就代表了分段了

2018-09-26 09:46 UTC, ColinCollins commented
![image](https://user-images.githubusercontent.com/35832931/46072106-19725f00-c1b4-11e8-8ecc-4bf2033a179a.png)

2018-09-28 09:02 UTC, pandamicro requested changes

2018-09-28 09:02 UTC, pandamicro commented on cocos2d/core/event/system-event.js
> + * The System event, it currently supports the key events and accelerometer events.<br>
it currently supports keyboard events and accelerometer events.

2018-09-28 09:02 UTC, pandamicro commented on cocos2d/core/event/system-event.js
> + * You can get the SystemEvent instance through by cc.systemEvent.<br>
You can get the SystemEvent instance with cc.systemEvent

2018-09-28 09:42 UTC, pandamicro approved these changes

2018-09-28 09:42 UTC, merged