changes to run in editor
cocos/cocos-engine pull request #3311
Opened 2018-09-26 06:47 UTC by shrinktofit

2018-09-30 08:32 UTC, pandamicro commented
修改没什么问题，冲突了，我最近处理资源的时候顺便帮你解决一下好了

2018-10-08 02:41 UTC, shrinktofit commented
> 修改没什么问题，冲突了，我最近处理资源的时候顺便帮你解决一下好了

冲突解决了

2018-10-08 02:49 UTC, pandamicro requested changes
解决冲突过程中对 node 的 transform API 修改有问题

2018-10-08 02:49 UTC, pandamicro commented on cocos/3d/assets/utils/gltf-utils.js
> +            node.setLocalPos(
这里冲突解决的有问题，看这个 issue https://github.com/cocos-creator/3d-tasks/issues/100

2018-10-08 03:52 UTC, pandamicro approved these changes

2018-10-08 03:52 UTC, merged