support 3d raycast
cocos/cocos-engine pull request #3326
Opened 2018-09-27 06:03 UTC by 2youyou2

Changes:
 * support 3d raycast

2018-09-27 06:42 UTC, YunHsiao requested changes

2018-09-27 06:42 UTC, YunHsiao commented on cocos2d/core/3d/CCModel.js
> +            float32Data: new Float32Array(vbData.buffer),
这么写有问题, 一个是没有一起传byteLength, byteOffset进去, 一个是float32array以4字节为单位去view, buffer结尾可能会truncate掉几个字节, 详细可参考[官方文档](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays).
应该改为用dataview去做extraction, 可参考#3323.

2018-09-27 11:05 UTC, 2youyou2 commented on cocos2d/core/3d/CCModel.js
> +            float32Data: new Float32Array(vbData.buffer),
是的，现在改为读顶点的时候用 DataView

2018-09-30 04:10 UTC, pandamicro requested changes

2018-09-30 04:10 UTC, pandamicro commented on cocos2d/core/3d/geom-utils/intersect.js
> +let Intersection3D = {};
应该用小写开头命名对象

2018-09-30 04:10 UTC, pandamicro commented on cocos2d/core/3d/geom-utils/intersect.js
> +cc.Intersection3D = module.exports = Intersection3D;
不要暴露在 cc 空间下，用 cc.geomUtils.intersect，这样和 3d 的融合就没有迁移成本了

2018-09-30 04:10 UTC, pandamicro commented on cocos2d/core/3d/geom-utils/ray.js
> +cc.Ray = module.exports = ray;
同上，用 cc.geomUtils.Ray

2018-09-30 04:10 UTC, pandamicro commented on cocos2d/core/3d/geom-utils/triangle.js
> +cc.Triangle3D = module.exports = triangle;
cc.geomUtils.Triangle

2018-09-30 06:44 UTC, pandamicro approved these changes

2018-09-30 06:44 UTC, merged