fix the MaxScrollOffset return error Size back
cocos/cocos-engine pull request #3331
Opened 2018-09-27 08:40 UTC by ColinCollins

Re: http://forum.cocos.com/t/2-0-2-scorllview-getscrolloffset/66840

因为现在 Content 的对齐对象为 View 所以对应的最大滑动尺寸应该是由 content.height - view.contentSize.height (伪码) 才对。

2018-09-28 02:00 UTC, pandamicro requested changes

2018-09-28 02:00 UTC, pandamicro commented on cocos2d/core/components/CCScrollView.js
> +        let viewSize = this.content.parent.getContentSize();
content 的 parent 在 ScrollView 中的作用比较重要，建议独立一个属性 _view，使用的时候统一使用 view，不要每次从 content.parent 获取，代码阅读起来很奇怪

2018-09-28 02:15 UTC, ColinCollins commented on cocos2d/core/components/CCScrollView.js
> +        let viewSize = this.content.parent.getContentSize();
ok

2018-09-28 03:34 UTC, ColinCollins commented
新增 _view 用于记录 scrollView 下 View 对象，不小心将两个 commit 合并了。
getMaxScrollOffset 函数修改是单独内容，其他部分修改是关联新增 _view 属性

2018-09-28 09:12 UTC, pandamicro requested changes

2018-09-28 09:12 UTC, pandamicro commented on cocos2d/core/components/CCScrollView.js
> +            this._view = this.content.parent;
1. 不需要判断 this._view 是否存在
2. content 改变的时候也应该修改 this._view

2018-09-29 04:43 UTC, pandamicro requested changes

2018-09-29 04:43 UTC, pandamicro commented on cocos2d/core/components/CCScrollView.js
> +    initView () {
改为私有接口

2018-09-29 04:43 UTC, pandamicro commented on cocos2d/core/components/CCScrollView.js
> +                this.initView();
这样是 ok 的

2018-09-29 06:08 UTC, ColinCollins commented
修改完成

2018-09-29 06:28 UTC, pandamicro approved these changes

2018-09-29 06:28 UTC, merged