call jsb.device.setMotion when set setAccelerometer on native
cocos/cocos-engine pull request #3332
Opened 2018-09-27 10:30 UTC by drelaptop

修复：https://github.com/cocos-creator/2d-tasks/issues/351

配合：https://github.com/cocos-creator/cocos2d-x-lite/pull/1523

重力感应的方法已经在 jsb-adapter 中实现过，只是没被调用。修复在文件：cocos2d/core/event/system-event.js

> PR 的额外工作，同步分支的小差异。

2018-09-27 11:43 UTC, jareguo commented on cocos2d/core/event/system-event.js
> +        }
是不是应该在 inputManger 里面调用 jsb.device.setMotionEnabled 比较好？

2018-09-28 01:55 UTC, pandamicro requested changes

2018-09-28 01:55 UTC, pandamicro commented on cocos2d/core/event/system-event.js
> +        }
嗯，是的，平台相关应该在 InputManager 中

2018-09-28 02:07 UTC, drelaptop commented on cocos2d/core/event/system-event.js
> +        }
好的，我改一下

2018-09-28 02:12 UTC, drelaptop commented
改动了，改动后有验证，在 iOS 上 DeviceMotion 测试例开启重力感应后，金币正常移动。重力感应关闭后，静止。

2018-09-28 02:45 UTC, pandamicro approved these changes

2018-09-28 02:45 UTC, merged