Optimize batch rendering of Sprites in case of color changes
cocos/cocos-engine pull request #3368
Opened 2018-10-11 05:50 UTC by caryliu1999

Re: cocos-creator/2d-tasks#381

Changes:
For batch rendering of sprite in case of color changes, update the color only when useColor is set to true.

2018-10-11 05:57 UTC, pandamicro requested changes

2018-10-11 05:57 UTC, pandamicro commented on cocos2d/core/renderer/webgl/assemblers/sprite/bar-filled.js
> +        let buffer = renderer.getBuffer('quad', vfmtPosUvColor),
将 render component walker 中的 defaultVertexFormat 改为 vfmtPosUvColor

2018-10-11 05:57 UTC, pandamicro commented on cocos2d/core/renderer/webgl/assemblers/sprite/bar-filled.js
> +        let buffer = renderer.getBuffer('quad', vfmtPosUvColor),
还要检查所有使用 _quadBuffer 和 _meshBuffer 的地方，如果没有 color attribute，要更改获取 buffer 的方式

2018-10-11 07:30 UTC, caryliu1999 commented
The defaultVertexFormat in render-component-walker has been changed to vfmtPosUvColor to reduce duplicate definitions.

2018-10-11 08:38 UTC, pandamicro requested changes

2018-10-11 08:38 UTC, pandamicro commented on cocos2d/core/renderer/webgl/assemblers/label/bmfont.js
> +        let buffer = renderer.getBuffer('quad', vfmtPosUv),
bmfont 也需要带上 color，这是最容易产生变色的渲染组件

2018-10-11 08:38 UTC, pandamicro commented on cocos2d/core/renderer/webgl/assemblers/label/ttf.js
> +        let buffer = renderer.getBuffer('quad', vfmtPosUv),
同上

2018-10-11 12:24 UTC, caryliu1999 commented
Label's color settings have been modified, now BMFont can be batch render when the color changes.

2018-10-12 01:53 UTC, pandamicro approved these changes

2018-10-12 01:56 UTC, merged