add a new API to judge the spriteFrame texture if it insert to dynamic
cocos/cocos-engine pull request #3410
Opened 2018-10-23 02:44 UTC by ColinCollins

Re: https://github.com/cocos-creator/2d-tasks/issues/696
为 setRect 增加新的纹理计算
![1](https://user-images.githubusercontent.com/35832931/47331989-7e847c00-d6b0-11e8-9282-bfa79a3cc0c3.gif)

现在超出 atlas 尺寸的 Texture 也能够设置剪裁显示区域

2018-10-23 03:35 UTC, pandamicro requested changes

2018-10-23 03:35 UTC, pandamicro commented on cocos2d/core/assets/CCSpriteFrame.js
> +            this._calculateUV();
这个操作在 _textureLoadedCallback 中会和后续的操作重复，需要检查内部 setRect 函数的调用，改为 this._rect = rect 避免重复计算。

2018-10-23 03:35 UTC, pandamicro commented on cocos2d/core/assets/CCSpriteFrame.js
> +        if (!CC_EDITOR && this._texture) {
为什么编辑器不需要？

2018-10-23 03:38 UTC, pandamicro commented
PR 标题错了，改一下

2018-10-23 03:38 UTC, pandamicro commented
commit message 也不对

2018-10-23 07:42 UTC, ColinCollins commented on cocos2d/core/assets/CCSpriteFrame.js
> +        if (!CC_EDITOR && this._texture) {
因为序列化操作的时候有调用到 setRect 我增加了一个关于 texture 的检测，但是为了以防万一又添加了关于编辑器的检测。
事实证明是我想多了.... 编辑器环境下若是编辑器编辑或者拓展插件的话应该是允许操作的。

2018-10-23 07:44 UTC, ColinCollins commented
修改了 textureLoadingCallback 对 setRect 调用减少计算
setTexture 同理

2018-10-24 01:53 UTC, pandamicro commented
1. 在 deserialize 中的 setRect 也要改
2. setRotated 中也需要调用 calculateUV
3. 可以检查一下是否还有 UV 计算相关的属性 setter 没有做重计算处理的

2018-10-24 02:01 UTC, ColinCollins commented
![image](https://user-images.githubusercontent.com/35832931/47401334-77727200-d773-11e8-9e29-a809fc294424.png)
deserialize 部分的内容我故意没有改动，他在引擎启动时触发针对场景资源做加载，但是 texture 是在设定好 rect 之后付的值，因此在我加了个 texture 的判断之后是不会有 UV 计算的。
如果要修改这个部分的话，setRect 上针对 texture 的判断我会去掉。

2018-10-24 02:19 UTC, ColinCollins commented
![image](https://user-images.githubusercontent.com/35832931/47401873-9245e600-d775-11e8-994a-87f671bd3fd8.png)
目前 setRotate 似乎只是一个 boolean 并没有实际修改的作用

2018-10-24 03:13 UTC, ColinCollins commented
新问题： originalSize 和 Offset 针对较大图片不生效。。。应该和顶点刷新有关，我会分成两个 commit 进行修复。

2018-10-24 03:35 UTC, ColinCollins commented
originalSize 和 Offset 重新检测了一下，没问题了，setRotated 已修复，没有其他引用

2018-10-24 04:08 UTC, pandamicro approved these changes

2018-10-24 04:08 UTC, merged

2018-10-28 07:48 UTC, jareguo commented
修复 SpriteFrame 调用 `setRect()` 后效果不对的问题