Optimize the render flow of renderComponent when the active state of …
cocos/cocos-engine pull request #3431
Opened 2018-10-25 13:05 UTC by caryliu1999

…the node is false.

Re: cocos-creator/2d-tasks#

Changes:
When the node is activated, it will execute onEnable and the render-flag will also be reset. So it's not have to update the render-flag when the node is not active.

2018-10-28 02:00 UTC, pandamicro requested changes

2018-10-28 02:00 UTC, pandamicro commented on cocos2d/core/components/CCRenderComponent.js
> +        if (enable && this._canRender() && this.node._activeInHierarchy) {
把这个判断移到 _canRender 中，也就是

canRender = _enabled && node._activeInHierarchy

2018-10-29 03:41 UTC, pandamicro approved these changes

2018-10-29 03:42 UTC, merged

2018-10-29 08:31 UTC, caryliu1999 commented
修复2.0版本中RenderComponent在节点未激活时依然会进行渲染的问题。