fix button.target is null
cocos/cocos-engine pull request #3458
Opened 2018-11-01 07:19 UTC by umbrellaPP

修复问题：
button.target 为空时，button 会报错。需要做一层判断

2018-11-04 02:23 UTC, pandamicro requested changes

2018-11-04 02:23 UTC, pandamicro commented on cocos2d/core/components/CCButton.js
> +        if (!target) return;
不要做这样的合并，加上大括号之后代码更清晰，而且 uglify 也会将最终的发布代码修饰正确

2018-11-05 11:44 UTC, pandamicro approved these changes

2018-11-05 11:44 UTC, merged

2018-11-09 10:16 UTC, jareguo commented
target 为空时，难道不是应该自动拿当前节点上的 Sprite 吗？

2018-11-09 10:21 UTC, umbrellaPP commented
> target 为空时，难道不是应该自动拿当前节点上的 Sprite 吗
那就每次访问 target 都要判断 node 上有没有 sprite，没有就创建一个，再绑定上去

2018-11-09 10:22 UTC, umbrellaPP commented
哦，是直接绑定 node，不是 Sprite

2018-11-09 10:26 UTC, jareguo commented
没有 Sprite 不创建，直接跳过

2018-11-09 11:06 UTC, umbrellaPP commented
关联 pr: https://github.com/cocos-creator/engine/pull/3491