node, light, texture-cube
cocos/cocos-engine pull request #3460
Opened 2018-11-02 10:33 UTC by YunHsiao

2018-11-04 03:09 UTC, pandamicro requested changes

2018-11-04 03:09 UTC, pandamicro commented on cocos/3d/assets/texture-cube.js
> +    initWithElement(element) {
其实没必要跟 Texture2D 用一样的函数名，比如改为 initWithElements，强制接收数组类型，避免函数多态性

2018-11-04 03:09 UTC, pandamicro commented on cocos/3d/assets/texture-cube.js
> +        this._image = element[0];
貌似是不需要保存这个 _image 的吧？

2018-11-04 03:09 UTC, pandamicro commented on cocos/3d/assets/texture-cube.js
> +        ));
这两个检测建议先缓存结果到一个数组，然后在 imageMipmaps 都回调结束之后再调用 handleLoadedTextures 或者是报错

2018-11-05 01:46 UTC, YunHsiao commented on cocos/3d/assets/texture-cube.js
> +        ));
为什么呢, 现在是回调都结束后才加载, 或中途有任何哪个出错都会直接提示, 这个行为有问题吗?

2018-11-05 01:47 UTC, YunHsiao commented on cocos/3d/assets/texture-cube.js
> +        this._image = element[0];
这是很纠结的地方, TextureCube 到底要不要继承 Texture2D? 现在是继承的, 因为有接口暴露了 _image 这个成员, 所以不得不给个对应的东西.

2018-11-05 01:49 UTC, YunHsiao commented on cocos/3d/assets/texture-cube.js
> +    initWithElement(element) {
也是继承的问题, 父类有这个接口子类也有, 如果再单独写个 initWithElements, 用户可能不知道要用哪个, 函数意义也比较模糊

2018-11-05 09:55 UTC, pandamicro commented on cocos/3d/assets/texture-cube.js
> +        ));
一般用户想做错误处理的时候，是尽量把正确的都加载成功，单独处理错误的

2018-11-05 10:51 UTC, merged

2018-11-05 10:51 UTC, pandamicro commented
Texture Cube 部分的修改后续再做调整

2018-11-05 11:07 UTC, pandamicro commented
https://github.com/cocos-creator/3d-tasks/issues/146