simplify option in EditBox component
cocos/cocos-engine pull request #3475
Opened 2018-11-08 05:57 UTC by umbrellaPP

Re: https://github.com/cocos-creator/2d-tasks/issues/372

Changes:
 - 简化 Editbox 选项，由 label 子节点更灵活地控制字体效果
- 修复每次加载场景，都会重新 resize EditBox 子节点
相关问题反馈：https://forum.cocos.com/t/cocos-creator-editbox-bug/68783

修改：
- 废弃旧属性 backgroundImage, fontColor, fontSize, lineHeight, placeholderFontSize, placeholderColor
- 增加 background, textLabel, placeholderLabel 属性
- 旧数据地兼容处理 ( _upgradeComponent )
- _syncSize 替代之前的 _resizeChildNodes， _init 里边不去调用 _syncSize

说明：
- 现在引擎不会动态地去创建 label 和 background 子节点，textLabel, placeholderLabel, background 属性允许为空。所以每次访问这些节点属性时，需要判断节点是否存在。
- editbox UI 控件默认会帮用户绑定好对应节点
- 由于需要给旧属性增加 get set 方法，增加了 get set 之后造成反序列化失败，所以多声明了一个属性用来获取旧控件的数据，例如 fontSize 对应 _fontSize。

关联pr：

效果图：
<img width="334" alt="wechatimg6" src="https://user-images.githubusercontent.com/17872773/48180306-067bae80-e35e-11e8-93da-73341bfabeb8.png">

2018-11-09 02:15 UTC, jareguo commented on cocos2d/core/components/editbox/CCEditBox.js
> +    }
是不是应该加警告呢？

2018-11-09 02:15 UTC, jareguo commented on cocos2d/core/components/editbox/CCEditBox.js
> +        textLabel: {
text 和 Label 感觉组合起来挺奇怪的……

2018-11-09 03:09 UTC, umbrellaPP commented on cocos2d/core/components/editbox/CCEditBox.js
> +    }
这个意见有点出入  @pandamicro

2018-11-09 03:11 UTC, umbrellaPP commented on cocos2d/core/components/editbox/CCEditBox.js
> +        textLabel: {
子节点默认就叫 TEXT_LABEL ，所以这里也对应叫 textLabel 了

2018-11-19 04:59 UTC, pandamicro requested changes

2018-11-19 04:59 UTC, pandamicro commented on cocos2d/core/components/editbox/CCEditBox.js
> +    }
先在文档中说明让大家知道我们要废弃这几个 API，等到下一个版本再加警告吧

2018-11-19 04:59 UTC, pandamicro commented on cocos2d/core/components/editbox/CCEditBox.js
> +        this._upgradeComponent();
限定在 EDITOR 环境下吧，只要 EDITOR 的数据迁移保障正确，打包出来之后就不需要做 upgrade 了

2018-11-19 04:59 UTC, pandamicro commented on cocos2d/core/components/editbox/CCEditBox.js
> +        this.node.on(cc.Node.EventType.SIZE_CHANGED, this._syncSize, this);
事件注册放在属性初始化和设置之后

2018-11-19 04:59 UTC, pandamicro commented on cocos2d/core/components/editbox/CCEditBox.js
> +            }
每帧都做这些操作不合理啊，可以判断是否有变化

2018-12-26 06:06 UTC, umbrellaPP commented
更新完毕，可以开始合并这个 pr

2019-01-03 09:47 UTC, pandamicro commented on cocos2d/core/components/editbox/CCEditBox.js
> +        _textLabelString: {
在 ctor 中写上这个属性就可以了

2019-01-03 09:47 UTC, pandamicro commented on cocos2d/core/components/editbox/CCEditBox.js
> +    _createLabelNode (name) {
用 _updateLabelNode 更贴切吧

2019-01-03 09:47 UTC, pandamicro commented on cocos2d/core/components/editbox/CCEditBox.js
> +        if (this._backgroundImage) {
为什么会有这个判断，假设因为某种原因这个判断没通过，那么  background 不会被创建，后续当 backgroundImage 被赋值的时候，background 节点也是不存在的。

如果background, textLabel, placeholderLabel 这三个节点是必要的，不需要根据这些条件做判断吧？

2019-01-03 09:47 UTC, pandamicro commented on cocos2d/core/components/editbox/CCEditBox.js
>                      this._impl.setPlaceholderText(this.placeholder);
在上面的 this.placeholderLabel.string = this.placeholder; 中会触发事件，并且调用 impl.setPlaceholderText
这里应该不需要再做，但是问题是 placeholderLabel 不存在的情况是什么？这种情况应该发生吗？

2019-01-03 09:47 UTC, pandamicro commented on cocos2d/core/components/editbox/CCEditBox.js
> +            textLabel.node.on('string-changed', function () {
这里使用函数的话，对于每次 initLabelEvent 的调用，都会产生新的函数对象，这里应该把函数放在外部（甚至不需要放在 prototype 中），然后这里写

`textLabel.node.on('string-changed', _onTextChanged, this);`

2019-01-03 09:47 UTC, pandamicro commented on cocos2d/core/components/editbox/CCEditBoxImpl.js
> +let styleSheetIndex = 0;
为什么叫 style sheet index，跟 css 貌似没关系啊，只是 dom 节点数量？domId ？

2019-01-03 12:59 UTC, umbrellaPP commented on cocos2d/core/components/editbox/CCEditBox.js
> +    _createLabelNode (name) {
这个主要是通过 name 创建 label 节点，不是更新

2019-01-03 13:02 UTC, umbrellaPP commented on cocos2d/core/components/editbox/CCEditBox.js
> +        if (this._backgroundImage) {
以前的做法是在 init 里动态创建 background, textLabel, placeholderLabel
现在不需要里，background, textLabel, placeholderLabel 不是必要的，用户可以把它设置为空的

2019-01-03 13:18 UTC, umbrellaPP commented on cocos2d/core/components/editbox/CCEditBoxImpl.js
> +let styleSheetIndex = 0;
嗯嗯，这个是记录 dom 节点数量的，实力化 一个 editboxImpl ，styleSheetIndex 就自增1
用来给每个 css 分配独有的 domId

2019-01-03 13:21 UTC, umbrellaPP commented on cocos2d/core/components/editbox/CCEditBox.js
>                      this._impl.setPlaceholderText(this.placeholder);
background, textLabel, placeholderLabel  都是允许为空的

2019-01-04 02:48 UTC, pandamicro commented on cocos2d/core/components/editbox/CCEditBox.js
> +    _createLabelNode (name) {
如果节点存在，就不是创建了，而是更新，你这个函数的逻辑包含了名字所不能涵盖的意义

2019-01-04 02:49 UTC, pandamicro commented on cocos2d/core/components/editbox/CCEditBox.js
> +        if (this._backgroundImage) {
如果允许是空的，那么在创建这些节点的时候都要执行 update / init / 监听 逻辑，目前的逻辑在这方面有缺失

2019-01-04 02:50 UTC, pandamicro commented on cocos2d/core/components/editbox/CCEditBoxImpl.js
> +let styleSheetIndex = 0;
我的意思是命名不准确

2019-01-04 03:52 UTC, umbrellaPP commented on cocos2d/core/components/editbox/CCEditBoxImpl.js
> +let styleSheetIndex = 0;
嗯，这里改成 sytleSheetCount 吧

2019-01-04 10:59 UTC, umbrellaPP commented
pr 先关闭，https://github.com/cocos-creator/2d-tasks/issues/1021 完成之后再做更新

2019-01-04 10:59 UTC, closed without merging