effect improvements
cocos/cocos-engine pull request #3480
Opened 2018-11-08 07:30 UTC by YunHsiao

Functionalities as specified in [Wiki](https://github.com/cocos-creator/3d-tasks/wiki/Writing-Custom-Effects).

2018-11-08 11:33 UTC, 2youyou2 commented on cocos/renderer/core/effect.js
> +            props[prop] = getInstanceCtor(prop.type)(prop.value);
`props[prop]` 这里 prop 是 object 吧，用这个做 key?

2018-11-12 17:45 UTC, pandamicro requested changes

2018-11-12 17:45 UTC, pandamicro commented on cocos/3d/assets/material.js
> +        handle.result.push(depend, 'asset', uuid);
这个做法有点创意 😄

2018-11-12 17:45 UTC, pandamicro commented on cocos/3d/assets/material.js
> +                loadAsset(handle, this, name, prop.uuid);
什么情况下 prop 是一个 asset ？除了 texture uniform 还有别的可能吗？

2018-11-12 17:45 UTC, pandamicro commented on cocos/3d/builtin/init.js
> -        // builtin meshes
貌似看不到 builtin mesh 去哪了

2018-11-12 17:45 UTC, pandamicro commented on cocos/3d/builtin/init.js
> +        this.loadEffects('../engine/cocos/3d/builtin/effects/index.json', effects => {
builtin effect 的默认位置建议由上层传入，不要写死在这里

2018-11-12 17:45 UTC, pandamicro commented on cocos/3d/builtin/init.js
> +        downloadText({ url }, (status, responseText) => {
不经过 loader 直接调用 downloadText 目前是违反引擎的设计规范的

2018-11-12 17:45 UTC, pandamicro commented on cocos/core/CCGame.js
> +        });
不建议将 initEngine 改为异步逻辑，很多引擎内部或者游戏的初始化逻辑依赖于 engine 的 init，如果 engine init 是异步的，就带来了用户脚本和引擎脚本中的事件监听，建议拆分 engine init 和 builtin res 的 loading，engine init 完成之后，再来做 builtin res loading，分步加载，分步派发事件

2018-11-13 01:42 UTC, YunHsiao commented on cocos/3d/assets/material.js
> +        handle.result.push(depend, 'asset', uuid);
credits goes to @2youyou2

2018-11-13 01:59 UTC, YunHsiao commented on cocos/3d/assets/material.js
> +                loadAsset(handle, this, name, prop.uuid);
就是两种texture, 其他应该就没了

2018-11-13 01:59 UTC, YunHsiao commented on cocos/3d/builtin/init.js
> -        // builtin meshes
在李楠改成那边读取fbx文件了

2018-11-13 01:59 UTC, YunHsiao commented on cocos/3d/builtin/init.js
> +        downloadText({ url }, (status, responseText) => {
这个是一个巨hack, 等通过uuid读取文件的接口写好再改 @2youyou2 ...

2018-11-13 05:45 UTC, 2youyou2 commented on cocos/3d/builtin/init.js
> +        downloadText({ url }, (status, responseText) => {
在这里: https://github.com/cocos-creator/engine/pull/3485

2018-11-13 07:06 UTC, pandamicro commented on cocos/core/CCGame.js
> +        this.emit(this.EVENT_ENGINE_INITED);
这个事件的位置别改，放到这个函数的末尾

2018-11-13 07:11 UTC, pandamicro approved these changes

2018-11-13 07:12 UTC, merged