Add some interfaces to load internal resources
cocos/cocos-engine pull request #3485
Opened 2018-11-09 04:30 UTC by holycanvas

Re: cocos-creator/2d-tasks#

Changes:
 * 加入接口在编辑器或者运行时加载资源。
AssetLibrary._loadAssetFromDB和AssetLibrary._loadAssetsFromDB在编辑器下可以加载任一资源，无论是internal还是assets下的任意目录中，运行时下只能加载resources目录中的资源

ccloader._loadBuiltin和cc.loader._loadBuiltinDir只能在运行时下用，只能加载internal/resources下的资源

尽量统一使用AssetLibrary._loadAssetFromDB和AssetLibrary._loadAssetsFromDB，运行时和编辑器都能使用

2018-11-09 06:39 UTC, jareguo commented on cocos2d/core/load-pipeline/CCLoader.js
> +var built_in = new AssetTable();
builtin 其实已经成为一个单词了，不建议加下划线
![image](https://user-images.githubusercontent.com/1503156/48247127-21692400-e42d-11e8-8739-8b9f20d95ac2.png)

2018-11-09 06:40 UTC, jareguo commented
这个 PR 有相关 issue 或讨论吗？是为了解决插件的资源加载问题？看起来似乎直接在编辑器里实现会比较好点。

2018-11-09 07:06 UTC, holycanvas commented
这个PR主要是为材质系统那边提供的接口， @2youyou2 需要在编辑器和运行时下加载internal文件夹下面的材质等内置资源，打包的时候也会将internal/resources文件夹下的东西一起打包。现在编辑器里面加载资源基本上也是用的cc.AssetLibrary.loadAsset这个接口，所以就统一实现在AssetLibrary里面了

2018-11-09 09:14 UTC, holycanvas commented
@jareguo ，关于内部资源是否需要导出的问题，要不和凯乐讨论一下看下他的需求，看最终结论是什么，我个人的倾向是认为，编辑器下加载资源的接口应该是需要的，运行时的话，我觉得导出了内部资源放在res目录下，H5下影响应该也不是很大，用户只要不用的时候，是不会被加载的，native的话可能会影响包体大小，但是unity在打包的时候确实也是导出了一些内置资源

![image](https://user-images.githubusercontent.com/15109777/48253633-b9253d00-e442-11e8-96af-2757bd3b246a.png)

这块看怎么抉择了

2018-11-09 09:48 UTC, jareguo commented
可以，我晚点回复下

2018-11-12 07:56 UTC, jareguo commented on cocos2d/core/load-pipeline/CCLoader.js
> +proto._loadBuiltin = function (url, type, progressCallback, completeCallback) {
API 名字也加个 Res 后缀吧

2018-11-12 07:56 UTC, jareguo commented on cocos2d/core/load-pipeline/CCLoader.js
> +proto._loadBuiltinDir = function (url, type ,progressCallback, completeCallback) {
_loadBuiltinResDir

2018-11-12 07:56 UTC, jareguo commented on cocos2d/core/platform/CCAssetLibrary.js
> +                    } else {
这里要判断一下 mountPoint 是不是 internals，因为其它插件有可能加入其它 mount 进来的目录

2018-11-12 07:56 UTC, jareguo commented on cocos2d/core/load-pipeline/CCLoader.js
> +proto._getBuiltinUuid = function (url, type, quiet) {
这个函数有点冗余，和 _getResUuid 完全一样啊，扩展一下 _getResUuid 吧，在 quiet 前面加一个 mount: string 参数吧？mount === 'internal' 时使用 builtin，默认为 resources

2018-11-12 07:56 UTC, jareguo commented on cocos2d/core/load-pipeline/CCLoader.js
> +    var args = this._parseLoadResArgs(type, progressCallback, completeCallback);
这里的实现和 loadRes 完全一样啊，同样扩展一下 loadRes 吧，支持在所有参数都给出的情况下，在 type 后面再传入一个 mount: string。这个参数我们内部用就好，API 注释不用改。然后这个方法内部就调用 loadRes 即可。

2018-11-12 07:56 UTC, jareguo commented on cocos2d/core/load-pipeline/CCLoader.js
> +    var args = this._parseLoadResArgs(type, progressCallback, completeCallback);
同上，建议扩展并内部调用 loadResDir。

2018-11-12 08:30 UTC, jareguo commented
不建议增加 _loadAssetFromDB 和 _loadAssetsFromDB 接口。这两个接口是私有的，而且传入的 url 其实对游戏开发者来说会比较陌生，通用性不够强。建议直接在编辑器下，polyfill 一下 loadRes 和 _loadBuiltinRes。polyfill 代码可以放在 fireball/editor/page/scene-utils/engine-extends/loader.js
这样也能避免往引擎内加入太多编辑器代码，更模块化一些。

2018-11-14 08:01 UTC, holycanvas commented
跟loadRes相关的函数基本都加入了mount参数，实现在运行时加载其他mount下的resource

2018-11-14 09:32 UTC, jareguo requested changes

2018-11-14 09:32 UTC, jareguo commented on cocos2d/core/load-pipeline/CCLoader.js
> +proto._resources = assetTables.assets;              // Backward compatibility
私有变量不需要为了做兼容而保留的，直接把我们用到的地方全部替换成 _assetTables 就好

2018-11-14 09:32 UTC, jareguo commented on cocos2d/core/load-pipeline/CCLoader.js
> +proto._getResUuid = function (url, type, quiet, mount) {
把 quiet 参数放到最后吧，不重要的参数放后面

2018-11-14 09:32 UTC, jareguo commented on cocos2d/core/load-pipeline/CCLoader.js
> +proto.loadRes = function (url, type, progressCallback, completeCallback, mount) {
mount 放在 callback 前面吧，callback 一般都是最后的

2018-11-14 09:32 UTC, jareguo commented on cocos2d/core/load-pipeline/CCLoader.js
> +proto._getReferenceKey = function (assetOrUrlOrUuid, mount) {
这个 API 就不要加入 mount 的支持了。因为对资源管理来说，要让调用者记住这是哪个 mount 的资源是不现实的。这里应该也没有通过路径来访问 internal 资源 uuid 的必要吧？

2018-11-14 09:32 UTC, jareguo commented on cocos2d/core/load-pipeline/CCLoader.js
> +proto.getDependsRecursively = function (owner, mount) {
同上，这里应该也没有指定 mount 的必要

2018-11-14 09:32 UTC, jareguo commented on cocos2d/core/load-pipeline/CCLoader.js
> +proto.getDependsRecursively = function (owner, mount) {
同上，这里应该也没有指定 mount 的必要

2018-11-14 09:32 UTC, jareguo commented on cocos2d/core/load-pipeline/CCLoader.js
> +proto.release = function (asset, mount) {
同上，这里应该也没有指定 mount 的必要

2018-11-14 09:32 UTC, jareguo commented on cocos2d/core/load-pipeline/CCLoader.js
> +proto.setAutoRelease = function (assetOrUrlOrUuid, autoRelease, mount) {
同上，这里应该也没有指定 mount 的必要

2018-11-14 09:32 UTC, jareguo commented on cocos2d/core/load-pipeline/CCLoader.js
> +proto.setAutoReleaseRecursively = function (assetOrUrlOrUuid, autoRelease, mount) {
同上，这里应该也没有指定 mount 的必要

2018-11-14 09:32 UTC, jareguo commented on cocos2d/core/load-pipeline/CCLoader.js
> +proto.isAutoRelease = function (assetOrUrl, mount) {
同上，这里应该也没有指定 mount 的必要

2018-11-14 09:32 UTC, jareguo commented on cocos2d/core/platform/CCAssetLibrary.js
> +                    }
`assetTables[mountPoint].add(url, uuid, type, !isSubAsset);` 统一放到这个 if 之后就行

2018-11-14 09:42 UTC, holycanvas commented on cocos2d/core/load-pipeline/CCLoader.js
> +proto._getReferenceKey = function (assetOrUrlOrUuid, mount) {
关键他这个接口支持用url，参数都叫做assetOrUrlOrUuid，虽然说基本不用

2018-11-14 14:52 UTC, jareguo approved these changes

2018-11-18 14:32 UTC, pandamicro approved these changes

2018-11-18 14:33 UTC, pandamicro commented
需要 cherry pick 到 3d 分支，@YunHsiao 会需要

2018-11-18 14:33 UTC, merged