impl texture2d using imageasset
cocos/cocos-engine pull request #3488
Opened 2018-11-09 07:18 UTC by shrinktofit

2018-11-09 07:50 UTC, 2youyou2 commented on cocos/assets/CCTexture2D.js
> +        this._image = null;
不是已经定义了一个 _image 的 property 了吗

2018-11-09 07:50 UTC, 2youyou2 commented on cocos/assets/CCTexture2D.js
> +        this._image.data = element;
如果 `this._image` 是个公用的资源，修改他的 data 是不是就有问题了

2018-11-09 07:50 UTC, 2youyou2 commented on cocos/load-pipeline/loader.js
> +    var tex = item.texture || new ImageAsset();
注释和变量名也要改一下

2018-11-09 07:50 UTC, 2youyou2 commented on cocos/renderer/gfx/texture-2d.js
> + * @typedef {import("../../assets/texture-base").TextureUpdateOpts} TextureUpdateOpts
gfx 去引用外部的东西不好吧？

2018-11-09 07:50 UTC, 2youyou2 commented on cocos/assets/CCTexture2D.js
> +            attributes: asset,
这里计算的纹理压缩的 extId 也要放到 ImageAsset 中去，不过涉及到纹理压缩相关的东西还是挺多的

2018-11-09 07:50 UTC, 2youyou2 commented on cocos/assets/CCTexture2D.js
> +        return "<cc.Texture2D | Name = " + this.url + " | Dimensions = " + super.width + " x " + super.height + ">";
this.width/this.height 获取不到吗？

2018-11-09 08:20 UTC, jareguo commented
有 issue 都尽量关联一下吧

2018-11-12 09:18 UTC, jareguo commented on cocos/assets/CCTexture2D.js
> +            handle.result.push(this, '_imageSetter', imageUuid);
这里直接 `handle.result.push(this, 'imageAsset', imageUuid);` 就行了

2018-11-12 09:19 UTC, jareguo commented on cocos/renderer/gfx/texture-2d.js
> +   * @param {TextureUpdateOpts} options
TextureUpdateOpts 在哪里定义的，API 文档能生成吗？

2018-11-12 17:26 UTC, pandamicro commented on cocos/assets/image-asset.js
> +        this._data = null;
对于 ArrayBufferView，还应该包含数据格式（PixelFormat）信息

2018-11-12 17:26 UTC, pandamicro commented on cocos/assets/CCTexture2D.js
> +        this._image.data = element;
我觉得不应该再提供 initWithElement / initWithData 方法了，只应该接受新的 ImageAsset

2018-11-13 02:00 UTC, shrinktofit commented on cocos/assets/CCTexture2D.js
> +        this._image = null;
已修改

2018-11-13 02:01 UTC, shrinktofit commented on cocos/assets/CCTexture2D.js
> +        this._image.data = element;
@pandamicro 这么做是为了兼容性考虑，这是之前的API

2018-11-13 02:06 UTC, shrinktofit commented on cocos/assets/CCTexture2D.js
> +        return "<cc.Texture2D | Name = " + this.url + " | Dimensions = " + super.width + " x " + super.height + ">";
已修改，这里之前考虑的是VS提示问题

2018-11-13 02:06 UTC, shrinktofit commented on cocos/load-pipeline/loader.js
> +    var tex = item.texture || new ImageAsset();
已修改

2018-11-13 02:06 UTC, shrinktofit commented on cocos/assets/CCTexture2D.js
> +            handle.result.push(this, '_imageSetter', imageUuid);
已修改，换了新实现方式，这里你再review一下

2018-11-13 02:24 UTC, shrinktofit commented on cocos/assets/CCTexture2D.js
> +        this._image.data = element;
@2youyou2 已修改

2018-11-13 03:50 UTC, jareguo requested changes

2018-11-13 03:50 UTC, jareguo commented on cocos/assets/CCTexture2D.js
> +        data.mipmaps.forEach((mipmapUUID, index) => {
从性能考虑，建议不要在反序列化 texture 过程中用 forEach，改用更简单的 for 循环。如果需要创造闭包，可以在 for 循环中定义 let counter。

2018-11-13 03:50 UTC, jareguo commented on cocos/assets/CCTexture2D.js
> +        const thiz = this;
个人不太建议用 thiz…… 我们一般都用的是 self，哪怕用 that 都好过 thiz，看的晕

2018-11-13 03:50 UTC, jareguo commented on cocos/assets/CCTexture2D.js
>                  }
感觉这里的做法还是太复杂了。建议在 for 循环中
handle.result.push(this.mipmaps, '' + index, mipmapUUID);

2018-11-13 05:40 UTC, shrinktofit commented on cocos/assets/CCTexture2D.js
>                  }
这里的this.mipmaps是数组，mipmapUUID需要传什么？

2018-11-13 05:57 UTC, shrinktofit commented on cocos/assets/CCTexture2D.js
> +        data.mipmaps.forEach((mipmapUUID, index) => {
已修改

2018-11-13 05:58 UTC, shrinktofit commented on cocos/assets/CCTexture2D.js
> +        const thiz = this;
已修改

2018-11-13 05:59 UTC, shrinktofit commented on cocos/assets/image-asset.js
> +        this._data = null;
修改了，但是这里有个问题，压缩纹理会传format过来吗？

2018-11-13 06:00 UTC, shrinktofit commented on cocos/assets/CCTexture2D.js
> +        this._image.data = element;
@pandamicro 已经移除，并且改了engine里的所有引用

2018-11-13 06:01 UTC, shrinktofit commented on cocos/assets/CCTexture2D.js
> +            attributes: asset,
改了，看看

2018-11-13 06:04 UTC, shrinktofit commented on cocos/renderer/gfx/texture-2d.js
> + * @typedef {import("../../assets/texture-base").TextureUpdateOpts} TextureUpdateOpts
调整了一下引用关系

2018-11-13 06:06 UTC, shrinktofit commented on cocos/renderer/gfx/texture-2d.js
> + * @typedef {import("../../assets/texture-base").TextureUpdateOpts} TextureUpdateOpts
6525f5f

2018-11-13 06:06 UTC, shrinktofit commented on cocos/assets/CCTexture2D.js
> +        const thiz = this;
c1e505d

2018-11-13 06:06 UTC, shrinktofit commented on cocos/assets/CCTexture2D.js
> +        data.mipmaps.forEach((mipmapUUID, index) => {
c1e505d

2018-11-13 06:07 UTC, jareguo commented on cocos/assets/CCTexture2D.js
>                  }
传每个 index 对应的 uuid

2018-11-13 06:07 UTC, shrinktofit commented on cocos/assets/CCTexture2D.js
> +        this._image.data = element;
@pandamicro c1e505d

2018-11-13 06:38 UTC, shrinktofit commented on cocos/assets/CCTexture2D.js
>                  }
哦我明白你意思了

2018-11-13 16:32 UTC, pandamicro commented on cocos/2d/label/CCLabel.js
> +                this._ttfTexture.image = new ImageAsset(this._assemblerData.canvas);
如果 image 已经存在，就应该做 image. _nativeAsset = htmlElement，否则对内存很不友好，可以将这个操作封装为一个 TextureBase 的函数，比如 

this._ttfTexture.updateImageWithElement(this._assemblerData.canvas);

其他 new ImageAsset 的位置同理

2018-11-13 16:33 UTC, pandamicro commented
现在清晰多了

2018-11-13 16:37 UTC, pandamicro requested changes

2018-11-13 16:37 UTC, pandamicro commented on cocos/assets/image-asset.js
> +         * @type {HTMLCanvasElement | HTMLImageElement | RawImageData}
type 是 Object

2018-11-13 16:37 UTC, pandamicro commented on cocos/assets/image-asset.js
> +            _data: null,
这个和 _data 重复了吧

2018-11-13 16:37 UTC, pandamicro commented on cocos/assets/image-asset.js
> +        this._nativeData = value;
不应该直接使用外部的对象来赋值，应该单独设置属性

this._nativeData.width = value.width;
this._nativeData.height = value.height;
...

这里同时也应该忽略 _data，而是在下面的 data setter 中设置

2018-11-14 01:55 UTC, shrinktofit commented on cocos/assets/image-asset.js
> +         * @type {HTMLCanvasElement | HTMLImageElement | RawImageData}
HTMLCanvasElement和HTMLImageElement都是本身都包含了width和height的

2018-11-14 03:52 UTC, shrinktofit commented on cocos/2d/label/CCLabel.js
> +                this._ttfTexture.image = new ImageAsset(this._assemblerData.canvas);
审核了一下本次提交所有的ImageAsset，修改了一些为update

2018-11-14 03:53 UTC, shrinktofit commented on cocos/assets/image-asset.js
> +        this._nativeData = value;
99dde7c

2018-11-14 03:53 UTC, shrinktofit commented on cocos/assets/image-asset.js
> +            _data: null,
99dde7c

2018-11-14 03:54 UTC, shrinktofit commented on cocos/assets/image-asset.js
> +         * @type {HTMLCanvasElement | HTMLImageElement | RawImageData}
现在的设计是_nativeData要么是`HTMLCanvasElement` 要么是`HTMLImageElement` 要么是`{_data, width......}`

2018-11-14 04:01 UTC, shrinktofit commented on cocos/assets/CCTexture2D.js
>                  }
f1b2da3 现在移除hack了，用了`onLoaded`

2018-11-14 04:38 UTC, pandamicro approved these changes

2018-11-14 14:28 UTC, jareguo approved these changes

2018-11-14 14:29 UTC, merged

2018-11-14 14:30 UTC, pandamicro commented
🎉