fix video play fullscreen bug for 2d-tasks/issues/749/421/337
cocos/cocos-engine pull request #3496
Opened 2018-11-12 10:18 UTC by knoxHuang

Re: cocos-creator/2d-tasks#749 cocos-creator/2d-tasks#421 cocos-creator/2d-tasks#337

Changes:
 * 修复 fullscreenVideo 全屏播放错误的 bug

2018-11-12 11:44 UTC, pandamicro requested changes

2018-11-12 11:44 UTC, pandamicro commented on cocos2d/videoplayer/video-player-impl.js
> +        video.setAttribute("x5-video-player-fullscreen", enable ? "true" : "false");
这些实现（iOS 平台判断和 x5 的特殊代码）都应该封装在平台层，也就是 Screen 实现中，不要在这里处理

2018-11-14 07:36 UTC, jareguo commented on cocos2d/core/platform/CCScreen.js
> +            else {
你能肯定除了 iOS 用的都是 X5？？

2018-11-15 01:21 UTC, knoxHuang commented on cocos2d/core/platform/CCScreen.js
> +            else {
如果不是 x5 的话，用了也无效，然后会直接继续往下调用

2018-11-15 05:38 UTC, pandamicro commented on cocos2d/core/platform/CCScreen.js
> +        if (element.className = "cocosVideo") {
应该用 tagName 为 video 来判断，不应该用 className 这种未来可能被修改的参数

2018-11-15 05:48 UTC, pandamicro approved these changes

2018-11-15 05:48 UTC, merged