fix label bmfont delay load bug
cocos/cocos-engine pull request #3499
Opened 2018-11-13 11:10 UTC by umbrellaPP

Changes:
- 修复 label bmfont 延时加载不显示问题

2018-11-13 17:06 UTC, pandamicro requested changes

2018-11-13 17:06 UTC, pandamicro commented on cocos2d/core/components/CCLabel.js
> +                this._assembler && this._assembler.updateRenderData(this);
应该放在 material 的处理之后，也就是回调函数末尾

2018-11-13 17:06 UTC, pandamicro commented on cocos2d/core/components/CCLabel.js
> +        }.bind(this));
bind 在很多情况下都不是好的 js code practice，建议将 activateMaterial 改为两个接口：

1. _activateMaterial () {} // 只做回调函数中的 material 处理，不管贴图资源
2. _applyFontTexture (force) {} // 尝试下载贴图，并在成功时主动调用 this._activateMaterial，如果 force 为 true，则最后再执行 this._assembler.updateRenderData(this)

2018-11-14 02:42 UTC, umbrellaPP commented
已更新 pr

2018-11-14 14:35 UTC, pandamicro requested changes

2018-11-14 14:35 UTC, pandamicro commented on cocos2d/core/components/CCLabel.js
> +        }
不要透传到 activateMaterial 中，updateRenderData 和 material 没关联，而且让这个接口混合了 force 参数，没有必要，这句代码应该在 onBMFontTextureLoaded 末尾

2018-11-15 08:38 UTC, pandamicro approved these changes

2018-11-15 08:38 UTC, merged