fix spine texture leakage and material may be invalid when reload spine resource
cocos/cocos-engine pull request #3502
Opened 2018-11-13 13:33 UTC by sunnylanwanjun

Re: https://github.com/cocos-creator/2d-tasks/issues/789

2018-11-13 16:53 UTC, pandamicro requested changes

2018-11-13 16:53 UTC, pandamicro commented on extensions/spine/Skeleton.js
> +        this._materialList = {};
直接删除 this._material，改为 this._materials

2018-11-13 16:53 UTC, pandamicro commented on extensions/spine/spine-assembler.js
> +        let materialList = comp._materialList
原始代码中每一行末尾一定要加分号

2018-11-13 16:53 UTC, pandamicro commented on extensions/spine/Skeleton.js
> +        this._materialList = {};
还需要重写 RenderComponent 的 getMaterial 接口，保障有效性

2018-11-13 16:55 UTC, pandamicro commented
另外，只需要修改 2.0 分支的 pr 就可以了，这些 PR 可以被 merge 到 2.1 和 master 分支

2018-11-14 07:41 UTC, sunnylanwanjun commented
好的，修改中

2018-11-14 13:59 UTC, sunnylanwanjun commented
2.0 和 2.1 的assembler稍微有些不同
还有就是2.0的license用的是http，2.1用的是https,所以还是分开提交了

2018-11-14 14:03 UTC, sunnylanwanjun commented
material还是保留了，如果整个渲染只需要用一种材质，那么就把material存到materials中。否则就从material 克隆一个新的存放在materils中，然后重写了updateMaterial方法，当传入一个新的material 的时个，把materials清空，当渲染的时候就会使用新的material了，这样顺带把之前用户反馈spine材质会被覆盖的问题解决了，一举两得。

2018-11-14 14:51 UTC, pandamicro reviewed
我还是建议将 _material 改造为 getter 方法获取

2018-11-14 14:51 UTC, pandamicro commented on extensions/spine/Skeleton.js
> +	        this._material = new SpriteMaterial();
indent issue

2018-11-14 14:51 UTC, pandamicro commented on extensions/spine/spine-assembler.js
> +    let materials = comp._materials;
Spine 中用 materials 数组并不是因为其他 material 是 _material 的拷贝，他们本身就是不同的，实际上对应的可能是不同的 render data，因为 Spine 中有不同的骨骼，可能是用的是不同的贴图和 blend function，不建议代码表述中用 _material 来作为 template

2018-11-15 09:00 UTC, pandamicro approved these changes

2018-11-15 09:00 UTC, merged