support 3d sprite&label
cocos/cocos-engine pull request #3509
Opened 2018-11-14 08:46 UTC by 2youyou2

Re: cocos-creator/2d-tasks#784

Changes:
 * support 3d sprite&label

2018-11-14 08:52 UTC, 2youyou2 commented
尽可能没有增加 2d 的计算量

2018-11-15 16:13 UTC, pandamicro commented
建议用下面的方式：

1. 拆分 3D 和 2D 节点
2. 增加构建宏 3D，如果节点树中包含 3D 节点即开启
3. 通过 3D 宏给 Assembler 固化的函数实现（不是通过函数内部的 if 判断，而是完整的函数实现不同）
4. 当 3D 开启时，vertex format 固定使用 3D format，添加 z

2018-11-16 01:05 UTC, 2youyou2 commented
> 3\. Assembler 固化的函数实现（不是通过函数内部的 if 判断，而是完整的函数实现不同）

现在就是不同的函数实现啊，没有在做 if 判断了

2018-11-16 05:17 UTC, pandamicro commented on cocos2d/core/components/CCLabel.js
> +            material.use2DPos = false;
为什么默认是 false？

2018-11-16 05:17 UTC, pandamicro commented on cocos2d/core/3d/polyfill-3d.js
> +        this._renderComponent._on3DNodeChanged();
如果节点树是这样：

- A
    - B
        - C (Sprite)

当改变 B 为 3D Node 的时候，C 貌似无法得到更新

2018-11-16 05:17 UTC, pandamicro commented on cocos2d/core/3d/polyfill-3d.js
> +        this._renderComponent._on3DNodeChanged();
建议这样：不要增加 _on3DNodeChanged 接口，在这里执行一个递归函数遍历节点，对子节点中的 Sprite 和 Label 组件进行 updateAssembler 操作即可，一方面是不增加接口，另一方面保障子节点树都可以得到更新

2018-11-16 05:17 UTC, pandamicro commented on cocos2d/core/renderer/webgl/assemblers/label/3d/bmfont.js
> +            vec3.transformMat4(vec3_temp, vec3_temp, matrix);
我有个想法可以节省大量代码，

将 3D node 的判断和 world pos 的计算封装到一个 utils 函数中，只要保障函数足够简单，可以被 inline，对性能的影响可能不会很大，可以跟你的 PR 中的版本做一下对比

2018-11-18 02:11 UTC, 2youyou2 commented on cocos2d/core/components/CCLabel.js
> +            material.use2DPos = false;
已经干掉 use2DPos

2018-11-18 02:11 UTC, 2youyou2 commented on cocos2d/core/renderer/webgl/assemblers/label/3d/bmfont.js
> +            vec3.transformMat4(vec3_temp, vec3_temp, matrix);
抽了部分代码出来

2018-11-18 02:12 UTC, 2youyou2 commented on cocos2d/core/3d/polyfill-3d.js
> +        this._renderComponent._on3DNodeChanged();
原本修改节点的 2D/3D 就不会更改子节点的 2D/3D 的

2018-11-18 13:57 UTC, pandamicro requested changes

2018-11-18 13:57 UTC, pandamicro commented on cocos2d/core/renderer/webgl/assemblers/label/3d/bmfont.js
> +        fillVertices(node, renderer._quadBuffer3D, comp._renderData, node._color._val);
这里应该是 fillVertices3D 吧

2018-11-18 13:57 UTC, pandamicro commented on cocos2d/core/renderer/webgl/assemblers/utils.js
> +function fillVerticesWithoutCalc (node, buffer, renderData, color) {
重复了

2018-11-18 13:58 UTC, pandamicro commented
这个 pr 可以先合并，监控测试组的性能测试数据，如果有问题等到小版本再调整也可以

2018-11-18 14:16 UTC, pandamicro approved these changes

2018-11-18 14:16 UTC, merged