adapter wx.onShow params
cocos/cocos-engine pull request #3515
Opened 2018-11-15 07:54 UTC by ColinCollins

Re: https://github.com/cocos-creator/2d-tasks/issues/786
增加针对 微信小游戏平台 onShow 函数的参数适配

![image](https://user-images.githubusercontent.com/35832931/48526704-94f2b180-e8c3-11e8-99ab-bbf4a0d8daf1.png)

因为 shareTicket 以及 referrerInfo 需要分享之后才会有参数传递，因此无法进行测试。

2018-11-15 08:07 UTC, ColinCollins commented
![image](https://user-images.githubusercontent.com/35832931/48538856-853d9200-e8f0-11e8-9216-1c12121a5b44.png)

2018-11-16 04:05 UTC, pandamicro requested changes

2018-11-16 04:05 UTC, pandamicro commented on cocos2d/core/CCGame.js
> +        function onShown (res, shareTicket, referrerInfo) {
并不是所有平台都是这些参数，把参数改为：

arg0, arg1, arg2, arg3, arg4

最多支持五个参数

2018-11-19 04:34 UTC, pandamicro approved these changes

2018-11-19 04:34 UTC, merged

2018-11-20 13:51 UTC, jareguo commented
支持在微信小游戏上响应 cc.game.EVENT_SHOW 事件时，获取到平台传入的 res 和 referrerInfo 参数