Modify label texture to join dynamic atlas.
cocos/cocos-engine pull request #3525
Opened 2018-11-16 07:33 UTC by caryliu1999

### 当前方案：
还是用最简单的方式，把生成好的字体图片添加到动态图集的方式处理批次渲染，这样对于图片跟文字穿插的情况也能进行合批。
### 疑问：
1.用户角度考虑，大部分还是会把单个场景的所有纹理打成大图集，自定义的图集并不会加到动态图集中，这种情况下，对于图片与文字的穿插，比如Button，也不能进行合批。
2.之前的系统字体使用预乘，使图片上面的文字混合显示的颜色正常表现。如果依然使用预乘，BlendFunc的不同，与非预乘的图片之间合批也会无效。
这两种场景需要考虑吗？

[测试结果](https://docs.google.com/document/d/e/2PACX-1vSkQMTZMBNC8i-4eeh1dahgoBQ9zUmKpOQceK9yyCD53xHzFgYgdjN6IaLsvWPLthIz3ezLV3IG1zi-/pub)

2018-11-18 02:10 UTC, 2youyou2 commented
我觉得再定义一个基础类来描述碎图信息会更好

```js
class Frame {
    _rect: cc.Rect,
    _texture: cc.Texture,
    _original: null,
    uv: [],
    _calculateUV () {}
}

class SpriteFrame {
    mixins: [EventTarget, Frame]
}

class Label {
    _frames: [Frame]
}
```

这样就不需要添加 insertCompTexture 了，结构也会更清晰。
如果直接在 label 中加 _rect 和 _texture 字段的话，bitmap 类型没法适用，因为 bitmap 是相当于存了多个 sprite frame 信息的。而 _frames 来描述可以适配各种情况。

2018-12-12 06:34 UTC, pandamicro requested changes
还有一个问题，对于 Label 这种改动非常频繁的组件，在 onDisable 的时候应该将 DynamicAtlasFrame 给主动清理掉，如果不包含这个机制，目前这个功能的可用性很低，很快就会将 Atlas 填满。

2018-12-12 06:34 UTC, pandamicro commented on cocos2d/core/components/CCLabel.js
> +        this._original = null;
赞同 @2youyou2 提出的 Frame 的概念，抽象出一个标准的概念给 Label 和 Sprite 共享，而不是将这些数据分散得存储在 Label 中

2018-12-12 06:34 UTC, pandamicro commented on cocos2d/core/components/CCLabel.js
> +    /**
不用作为公开 API 注释，可以改成
```
/*
 *
 */
```

这样就不会被导出 API 了

2018-12-12 06:34 UTC, pandamicro commented on cocos2d/core/renderer/utils/label/ttf.js
> +        }
dynamicAtlasManager 的使用目前看来比较 Hack，建议改为 Manager 只负责写入 Texture，不修改 SpriteFrame 或者 component 的 rect，而是返回一个 DynamicAtlasFrame 的对象（如果插入失败，则返回 null），包含：

- atlas texture
- rect

由 Component 和 SpriteFrame 自己负责保存这些数据。这样架构上比较健康，Material 是否需要更新的判断也会比较清晰（判断 insert 是否成功即可）

2018-12-12 06:34 UTC, pandamicro commented on cocos2d/core/renderer/utils/label/ttf.js
> +        }
同时，需要清理 Frame 的时候，直接传入 DynamicAtlasFrame 对象给 Manager 就可以了

2018-12-17 11:40 UTC, caryliu1999 commented on cocos2d/core/components/CCLabel.js
> +    /**
优化了之前尝试修改的初始版本实现。CacheAsBitmap是想作为一个用户可选择的勾选项来使用，对引擎来说还是不希望把频繁修改的动态字体缓存为静态图片加进动态图集中，会造成动态图集空间浪费和不必要的性能损耗，Label禁用时的图集占用区域清除，我看下有没有合适的图集算法能够结合适用。

2018-12-18 07:26 UTC, pandamicro reviewed
现在还存在一个最核心问题，当开发者的文字量大且经常改变的时候，如何避免 Atlas 超出失效

2018-12-18 07:26 UTC, pandamicro commented on cocos2d/core/renderer/utils/dynamic-atlas/manager.js
> +        return frame;
这个函数前面的 return 要改为 return null

2018-12-18 08:19 UTC, pandamicro approved these changes

2018-12-18 08:31 UTC, pandamicro commented
https://github.com/cocos-creator/2d-tasks/issues/146

2018-12-18 08:33 UTC, merged