improve CCRichText code
cocos/cocos-engine pull request #3533
Opened 2018-11-19 09:55 UTC by knoxHuang

Re: cocos-creator/2d-tasks#

Changes:
 * 完善一下 CCRichText 代码

2018-11-19 10:21 UTC, pandamicro requested changes

2018-11-19 10:21 UTC, pandamicro commented on cocos2d/core/components/CCRichText.js
> +            let segment = {};
建议封装成一个 addSegment 函数，包含 segment 属性的设置和 push 到数组中

2018-11-19 10:21 UTC, pandamicro commented on cocos2d/core/components/CCRichText.js
> +            pool.put(segment.node);
Pool 直接变成 segment pool 吧，但是需要在 put 之前做清理

2018-11-19 10:21 UTC, pandamicro commented on cocos2d/core/components/CCRichText.js
>  pool.get = function (string, fontAsset, fontSize) {
pool 改名为 _pool，表明这是一个 module 内的全局私有变量

2018-11-19 10:21 UTC, pandamicro commented on cocos2d/core/components/CCRichText.js
> +            pool.put(segment.node);
get 的时候也要相应做调整

2018-11-19 10:23 UTC, pandamicro commented
链接一下之前的 issue

2018-11-20 01:13 UTC, knoxHuang commented
https://github.com/cocos-creator/engine/pull/3530

2018-11-28 03:49 UTC, pandamicro requested changes

2018-11-28 03:49 UTC, pandamicro commented on cocos2d/core/components/CCRichText.js
> +        segment.addLabelComponent = function (string, styleIndex, richText) {
不要挂在 segment 下面，这样每个对象都有重复的方法，你直接写成

function addLabelComponent (segment, string, styleIndex, richText)

2018-11-28 03:49 UTC, pandamicro commented on cocos2d/core/components/CCRichText.js
> +                segment = _segmentPool.get(self, RichTextChildName);
为啥这里不用 _addSegment ？而是显式从 pool 中获取？代码的分散会导致维护的困难

2018-11-28 04:00 UTC, pandamicro commented on cocos2d/core/components/CCRichText.js
>          this._labelSegmentsCache = [];
改为 _rulerLabel，用 addLabelComponent 工具函数固定创建一个 Label 组件，持续在 measureText 组件中复用，不需要在 _addLabelSegment 复用

2019-03-13 06:34 UTC, knoxHuang commented
先关闭，后续在提交新分支

2019-03-13 06:34 UTC, closed without merging