Deffered loading
cocos/cocos-engine pull request #3569
Opened 2018-11-27 11:41 UTC by holycanvas

Re: cocos-creator/2d-tasks#

Changes:
 * 
所有资源延迟加载，正确显示加载进度
解决https://github.com/cocos-creator/2d-tasks/issues/174
解决https://github.com/cocos-creator/2d-tasks/issues/80

2018-11-28 12:41 UTC, jareguo requested changes

2018-11-28 12:41 UTC, jareguo commented on cocos2d/core/platform/CCMacro.js
> +    DOWNLOAD_MAX_CONCURRENT: 6,
代码麻烦加个注释说明为什么默认是 6

2018-11-28 12:41 UTC, jareguo commented on cocos2d/core/load-pipeline/CCLoader.js
> +    // so no need to care about underlying process
👍

2018-11-28 12:41 UTC, jareguo commented on cocos2d/core/load-pipeline/deferred-pipe.js
> +    if (cc.game.isPaused()) return null;
这里为什么要考虑暂停的情况呢？

2018-11-28 12:41 UTC, jareguo commented on cocos2d/core/load-pipeline/deferred-pipe.js
> +const ID = 'DeferredPipe';
这个 pipe 是做什么的呢？麻烦加点注释

2018-11-28 12:41 UTC, jareguo commented on cocos2d/core/load-pipeline/downloader.js
> +const MAX_LAUNCH_A_FRAME = 2;
这个是做什么用的呢？麻烦加点注释（似乎是为了限制并发加载数）

2018-11-28 12:41 UTC, jareguo commented on cocos2d/core/load-pipeline/loading-items.js
> +        if (item.deps) {
这里的缩进似乎有点奇怪。而且如果已经提取了 deps 变量，这里直接 if (deps) 就行了

2018-11-29 08:31 UTC, pandamicro commented on cocos2d/core/load-pipeline/deferred-pipe.js
> +var finished = Object.create(null);
可以用 js.createMap(true) 来保障对象在 dictionary mode

2018-11-29 08:31 UTC, pandamicro commented on cocos2d/core/load-pipeline/downloader.js
> +        if (launchXHR >= MAX_LAUNCH_A_FRAME) {
这个功能好评

2018-11-29 08:31 UTC, pandamicro commented on cocos2d/core/load-pipeline/CCLoader.js
> +    var depends = this.depends;
我倾向于将 Loader 跟 AssetLibrary 解耦，一个完全用于加载流程控制，一个用于 library 访问和依赖查询

2018-11-29 08:31 UTC, pandamicro commented on cocos2d/core/load-pipeline/CCLoader.js
> +    var queue = LoadingItems.create(this, progress, function (errors, items) {
现在这样的设计下，每个资源的依赖加载只会调用一次 flowInDeps，其中包含所有的依赖资源列表，对吧？

2018-11-29 08:31 UTC, pandamicro commented on cocos2d/core/load-pipeline/deferred-pipe.js
> +var finished = Object.create(null);
如果用户同时加载多个 prefab 的时候，每个 prefab 都会进入这个管道，finished 判断应该会有问题，相当于把多个依赖列表合并到一起了，stalled 貌似没问题，但是也混在了一起

2018-11-29 08:31 UTC, pandamicro commented on cocos2d/core/load-pipeline/deferred-pipe.js
> +function deferredInvoke (item, callback) {
这里创建了太多的匿名函数，感觉性能上不太友好，建议抽象为数据结构和函数放在 LoadingItems 里面，比如每个 deferredInvoke 只负责资源自身状态的更新，然后通知到 root queue，LoadingItems 里面有一个函数负责检查是否所有的 deps 都完成了。

pipeline 这边继续的机制改为 item 监听 LoadingItems 的 finish 事件，回调中再去继续执行 item 的后续 pipe

2018-11-29 08:31 UTC, pandamicro commented on cocos2d/core/load-pipeline/loading-items.js
> +        downloadedDeps: null
deps 本来就是临时的存储，为了检查循环依赖的，downloadedDeps 其实不需要，可以直接在 deps download 的回调里面直接移除对应的 deps entry

2018-11-29 08:31 UTC, pandamicro commented on cocos2d/core/load-pipeline/loading-items.js
> +        if (owner.downloadedDeps.length === owner.deps.length) {
这里可以转变为统计 deps 的剩余

2018-11-29 08:31 UTC, pandamicro commented on cocos2d/core/load-pipeline/loading-items.js
> +                LoadingItems._ascend(item);
itemComplete 里面只要通知到 owners 的 deferredPipe 中，应该就可以实现 ascend 了吧？需要存储 owners 和这里分开的通知么？

2018-12-03 07:38 UTC, jareguo commented on cocos2d/core/load-pipeline/deferred-pipe.js
> +function deferredInvoke (item, callback) {
这是局部函数，对性能应该很友好的

2018-12-10 02:40 UTC, closed without merging

2018-12-10 02:55 UTC, holycanvas commented
需要重构，进行关闭