Maintain Node EulerAngles & Effect Asset interface
cocos/cocos-engine pull request #3574
Opened 2018-11-29 10:25 UTC by YunHsiao

2018-12-03 02:14 UTC, pandamicro commented
https://github.com/cocos-creator/3d-tasks/issues/163

2018-12-05 07:03 UTC, pandamicro requested changes

2018-12-05 07:03 UTC, pandamicro commented on cocos/3d/assets/effect-asset.js
> +            return effects[n];
这个 API 感觉太灵活了，不能限制只通过 name 获取 effect 吗？

2018-12-05 07:03 UTC, pandamicro commented on cocos/3d/assets/material.js
> +        this._setEffect(this.effectAsset || this.effectName);
太灵活了，如果只有 effectName，应该先通过 name 获取 effectAsset，然后再设置，这样可以避免 _setEffect 中的判断

2018-12-05 07:03 UTC, pandamicro commented
PR 名中体现出对 Effect 的修改，或者拆分为两个 PR

2018-12-05 08:21 UTC, YunHsiao commented on cocos/3d/assets/effect-asset.js
> +            return effects[n];
编辑器反序列化有需求, name 和 uuid 都会用到

2018-12-05 08:21 UTC, YunHsiao commented on cocos/3d/assets/material.js
> +        this._setEffect(this.effectAsset || this.effectName);
这是临时需要, 下一个版本不会保存 effectName, 还是我直接在这个 pr 里加入后面的修改? 那这个 pr 就要再等等

2018-12-05 08:33 UTC, YunHsiao commented on cocos/3d/assets/material.js
> +        this._setEffect(this.effectAsset || this.effectName);
_setEffect 就是个私有工具函数, 方便两种设置方法的

2018-12-05 09:29 UTC, pandamicro commented on cocos/3d/assets/material.js
> +        this._setEffect(this.effectAsset || this.effectName);
那就暂时把 effect 的改动从这个 PR 中移除，我先合并 EulerAngles 的修改，然后你再提交一个完整的 Effect 的修改

2018-12-05 09:29 UTC, pandamicro commented on cocos/3d/assets/material.js
> +        this._setEffect(this.effectAsset || this.effectName);
呃，看你的 commit，是已经改完了？

2018-12-05 09:43 UTC, pandamicro approved these changes

2018-12-05 09:52 UTC, merged