modify preloadScene API params
cocos/cocos-engine pull request #3583
Opened 2018-12-03 06:15 UTC by ColinCollins

Re: https://github.com/cocos-creator/engine/issues/3561
修复 preloadScene onComplete 回调函数 ts 脚本参数缺失
![image](https://user-images.githubusercontent.com/35832931/49356154-b77b2c00-f705-11e8-8fb2-cbbc3042d731.png)

2018-12-03 11:51 UTC, pandamicro requested changes

2018-12-03 11:51 UTC, pandamicro commented on cocos2d/core/CCDirector.js
> +     * @param {cc.SceneAsset} onLoaded.asset - An asset manager belong to the scene you are loaded.
The scene asset itself

2018-12-04 02:37 UTC, ColinCollins commented
修正完毕

2018-12-04 05:50 UTC, pandamicro approved these changes

2018-12-04 05:50 UTC, merged