fixed issue that error is empty array
cocos/cocos-engine pull request #3590
Opened 2018-12-04 08:55 UTC by holycanvas

Re: cocos-creator/2d-tasks#

Changes:
 * fix https://github.com/cocos-creator/engine/issues/3580
   修复返回err为空数组的情况，将errorUrl改为对象实现

2018-12-05 09:26 UTC, pandamicro requested changes

2018-12-05 09:26 UTC, pandamicro commented on cocos2d/core/load-pipeline/loading-items.js
> +    this._errorUrls = js.createMap(true);
遍历 delete 做清理吧，重复 createMap 就失去了复用的意义了

2018-12-05 09:26 UTC, pandamicro commented on cocos2d/core/load-pipeline/loading-items.js
> +    var errors = Object.keys(this._errorUrls).length === 0 ? null : this._errorUrls;
```
var errors = null;
for (let url in this._errorUrls) {
    errors = this._errorUrls;
    break;
}
```

2018-12-05 09:26 UTC, pandamicro commented on cocos2d/core/load-pipeline/loading-items.js
> +    this._errorUrls = js.createMap(true);
也可以在 js 中添加一个 clearMap 的函数

2018-12-05 09:26 UTC, pandamicro commented on test/qunit/unit-es5/test-pipeline.js
> +        ok(!(error instanceof Array), 'should return error object in onComplete when error happened');
这个判断可以删除了

2018-12-05 16:22 UTC, pandamicro commented on cocos2d/core/load-pipeline/loading-items.js
> +    else if (item.error) {
好像有可能产生误判，万一 item.error 是 string 呢，或者别的类型

2018-12-06 03:51 UTC, holycanvas commented on cocos2d/core/load-pipeline/loading-items.js
> +    else if (item.error) {
不是应该返回的错误都是Error类型么，现在unit test里面有个用例返回了字符串，其他地方暂时没发现返回字符串和其他类型，返回一个对象就当作错误的map进行mixin

2018-12-06 07:56 UTC, pandamicro approved these changes

2018-12-06 07:56 UTC, merged

2018-12-16 07:01 UTC, jareguo commented on cocos2d/core/platform/js.js
> +    isEmptyObject: function (obj) {
这个函数和 isPlainEmptyObj_DEV 功能重合了。isPlainEmptyObj_DEV 是面向编辑器用途的，建议 isPlainEmptyObj_DEV 内部也调用 isEmptyObject

2018-12-16 07:03 UTC, jareguo commented on cocos2d/core/platform/js.js
> +    isEmptyObject: function (obj) {
或者将 isPlainEmptyObj_DEV 简化成 isPlainObject_DEV，调用时改用 utils.isPlainObject_DEV(obj) && js.isEmptyObject(obj)。这样也挺清晰。

2018-12-16 07:04 UTC, jareguo commented on cocos2d/core/load-pipeline/loading-items.js
> +    var errors = js.isEmptyObject(this._errorUrls) === true ? null : this._errorUrls;
感觉这种地方，直接 `js.isEmptyObject(this._errorUrls)` ? null : this._errorUrls 就行了吧？我觉得用 === 判断 true 应该是没意义的，只有判断 === false 或者 !== false 才有意义（意义是为了区分 null / undefined）。