Master move renderer.js
cocos/cocos-engine pull request #3616
Opened 2018-12-11 02:58 UTC by 2youyou2

Changes:
 * move renderer.js to engine
 * remove render-engine.js
 * add opaque/shadowcast stages
 * add cc.LightComponent
 * add _setUniform/_setDefine to cc.RenderComponent

2018-12-12 03:24 UTC, jareguo commented
CI 挂了喔

2018-12-12 06:33 UTC, jareguo commented on cocos2d/core/mesh/CCMeshRenderer.js
> +    Off: 0,
引擎里所有枚举值都是 XXX_XXX 的写法，这边是不是也应该用全大写比较好？

2018-12-14 10:25 UTC, pandamicro requested changes

2018-12-14 10:25 UTC, pandamicro commented on cocos2d/core/3d/CCLightComponent.js
> +    Spot: 2,
Enum 内的 key 大写

2018-12-14 10:25 UTC, pandamicro commented on cocos2d/core/3d/CCLightComponent.js
> +    Hard: 2,
同上

2018-12-14 10:25 UTC, pandamicro commented on cocos2d/core/assets/CCRenderTexture.js
> +                opts.depthStencil = depthStencilBuffer;
depth 和 stencil 放在一个 gl call 里面设置可能会触发部分低端机器上驱动问题导致崩溃

2018-12-14 10:25 UTC, pandamicro commented on cocos2d/core/camera/CCCamera.js
> +import RCamera from '../../renderer/scene/camera';
RendererCamera 的意思？不是很清晰，建议改成 CameraImpl 或者全称

2018-12-14 10:25 UTC, pandamicro commented on cocos2d/core/camera/CCCamera.js
> -                    this._camera._sortDepth = value;
depth 属性名要改吗？否则用户总会问 depth 方向的问题

2018-12-14 10:25 UTC, pandamicro commented on cocos2d/core/components/CCLabel.js
> +                material.define('USE_TEXTURE', true);
注意下准备 API 文档的时候，这些默认的 material 和 define 也需要文档化

2018-12-14 10:25 UTC, pandamicro commented on cocos2d/core/components/CCMask.js
> +                material.define('USE_TEXTURE', true);
怎么看怎么怪。。。什么时候该用 _ 开头，什么时候不该用

2018-12-14 10:25 UTC, pandamicro commented on cocos2d/core/components/CCMask.js
> -                material.define('useColor', true);
这个是不是之前残留的错误代码？按理说不应该 useColor 是吧？

2018-12-14 10:25 UTC, pandamicro commented on cocos2d/core/components/CCSprite.js
> -                    material.define('useColor', true);
现在是不是所有 useColor 都是 false ？Attribute 中默认使用 color ？

2018-12-14 10:25 UTC, pandamicro commented on cocos2d/core/components/CCRenderComponent.js
> +        this._defines = null;
这两个部分写一个子类会更好吧

2018-12-14 10:25 UTC, pandamicro commented on cocos2d/core/mesh/CCMesh.js
> -            this._subMeshes[index] = new renderEngine.InputAssembler(vb.buffer, buffer);
以前在 renderEngine 中的接口，现在对外暴露是在 cc 下面？最好写一个 deprecation，将 renderEngine 的访问转发一下，同时警告用户修改

2018-12-14 10:25 UTC, pandamicro commented on cocos2d/core/components/CCSprite.js
> +                    material.define('USE_TEXTURE', true);
Uniform 改为大写的原因是？

2018-12-14 10:25 UTC, pandamicro commented on cocos2d/core/renderer/index.js
> +};
从 API 角度来说，renderEngine 不再是一个独立模块了，而是变成 gfx, vmath, renderer 等模块，可以把这些模块放在 cc 下面

2018-12-14 10:25 UTC, pandamicro commented on cocos2d/core/mesh/mesh-renderer.js
> +        comp._setUniform('_nodeColor', comp.node.color);
对象传进去之后，如果 node.color 改变了，uniform 会自动更新吗？

2018-12-14 10:25 UTC, pandamicro commented on cocos2d/core/renderer/webgl/model-batcher.js
> +        model._uniforms = this.uniforms;
没有处理 uniforms 差异导致的批处理打断，是因为目前没有 MeshRenderer 批处理吧？等到要加批处理了，还需要吧 component level uniforms 和 defines 作为打断批处理的依据，目前看起来这个设计挺坑的

2018-12-14 10:25 UTC, pandamicro commented on cocos2d/renderer/core/base-renderer.js
> +      if ((model._cullingMask & view._cullingMask) === 0) {
我看 View 里面已经没有 cullingMask 了这是从哪来的？

2018-12-14 10:25 UTC, pandamicro commented on gulp/tasks/engine.js
> +        // '(.*)render-engine(.js)?': require.resolve('../../cocos2d/core/renderer/render-engine.jsb')
后续还需要一个 PR 来解决原生平台的 skip 吧

2018-12-14 10:25 UTC, pandamicro commented on cocos2d/core/components/CCRenderComponent.js
> +        this._defines = null;
uniforms 每帧变化不能直接设置到 material 里面，是因为 3D 模型使用 getBuiltinMaterial 来获取共享 material 吧？为什么不 instantiate 出来呢？

理论上来说 Sprite Material 使用的也是 dynamic uniform，可以随时修改，只是因为用的是 material instance 所以不需要这些 uniforms。那么你这里添加 _uniforms 和 _defines 的理由就不对了，并不是因为 dynamic uniform 就必须添加，而是因为你想在共享 builtin material 基础上添加一层 uniforms variation

这个架构看上去很 hack，我想先搞明白为什么不能 instantiate。如果不行，那么在 component 层设置 uniforms 和 defines 也不太可取

2018-12-14 10:25 UTC, pandamicro commented on cocos2d/core/components/CCRenderComponent.js
> +        this._defines = null;
defines 会每帧都改变吗？会的话还挺恐怖的

2018-12-14 12:37 UTC, 2youyou2 commented on cocos2d/core/components/CCMask.js
> +                material.define('USE_TEXTURE', true);
内部控制的就用 _ 开头，这些不会显示在 inspector 上给用户控制

2018-12-14 12:37 UTC, 2youyou2 commented on cocos2d/core/components/CCMask.js
> -                material.define('useColor', true);
sprite material 的 useColor 都没用了，都是计算在 vertices 里了

2018-12-14 12:39 UTC, 2youyou2 commented on cocos2d/core/components/CCSprite.js
> +                    material.define('USE_TEXTURE', true);
是 define ，不是 uniform

2018-12-14 12:41 UTC, 2youyou2 commented on cocos2d/renderer/core/base-renderer.js
> +      if ((model._cullingMask & view._cullingMask) === 0) {
view._cullingMask 是在 camera.extractView 的时候更新的

2018-12-14 12:41 UTC, 2youyou2 commented on gulp/tasks/engine.js
> +        // '(.*)render-engine(.js)?': require.resolve('../../cocos2d/core/renderer/render-engine.jsb')
是的

2018-12-14 13:34 UTC, 2youyou2 commented on cocos2d/core/components/CCRenderComponent.js
> +        this._defines = null;
sprite 的 material 可以用 instance 是因为一般来说他只有 texture 属性需要设置，不需要使用其他的 material，如果 sprite 使用了材质系统的资源，也是不能够修改的。

一旦 instantiate 了新的 material，就会覆盖了原来真正的 material 资源，而 instantiate 的material 是不能保存的

2018-12-16 09:16 UTC, pandamicro commented on cocos2d/renderer/core/base-renderer.js
> +      if ((model._cullingMask & view._cullingMask) === 0) {
那 constructor 里面的 cullingMask 还是要保留

2018-12-16 10:09 UTC, 2youyou2 commented on cocos2d/core/assets/CCRenderTexture.js
> +                opts.depthStencil = depthStencilBuffer;
https://github.com/yoavweiss/RespImg-WebCore/blob/master/html/canvas/WebGLFramebuffer.cpp#L464

depth 和 stencil 不能同时分别开的，只能放到 depthStencil 中

2018-12-18 08:20 UTC, 2youyou2 commented on cocos2d/core/camera/CCCamera.js
> -                    this._camera._sortDepth = value;
先不改了

2018-12-18 08:52 UTC, pandamicro commented on cocos2d/core/mesh/shader-config.js
> +        this._hash = val || serializeDefines(this._defines) + '__ '+ serializeUniforms(this._uniforms);
这样也太长了吧，字符串长度严重影响对比效率啊

2018-12-18 09:11 UTC, pandamicro commented on cocos2d/core/renderer/render-flow.js
> +    if (comp && comp._updateColor) comp._updateColor();
。。。有点蛋疼。。。

2018-12-24 08:34 UTC, pandamicro commented
👍 这个新的思路我觉得很棒！晚点我仔细看下

2019-01-02 08:33 UTC, pandamicro approved these changes
这个 PR 会先合并，下面这些疑问和需要调整的地方可以放在后面再做，感谢 @2youyou2 在材质系统上的贡献！

2019-01-02 08:33 UTC, pandamicro commented on cocos2d/core/3d/CCSkinnedMeshRenderer.js
> +            customProperties.setProperty('_jointsTexture', texture.getImpl());
为什么不继续用 setUniform 接口？

2019-01-02 08:33 UTC, pandamicro commented on cocos2d/core/renderer/webgl/model-batcher.js
> +        if ((material && material.getHash() !== this.material.getHash()) ||
customProperties 也应该用来判断是否打断 batch 吧，如果存在 customProperties 就打断，或者 customProperties 的 hash 不同就打断

2019-01-02 08:33 UTC, pandamicro commented on cocos2d/core/mesh/mesh-renderer.js
> +        renderer.customProperties = comp._customProperties;
是不是加一个 setter 更好，可以在 renderer 的 customProperties 变化的时候 flush

2019-01-02 08:33 UTC, pandamicro commented on cocos2d/renderer/build/chunks/skinning.inc
> + }
上面几行缩进都有问题

2019-01-02 08:34 UTC, merged

2019-01-07 01:22 UTC, 2youyou2 commented on cocos2d/core/3d/CCSkinnedMeshRenderer.js
> +            customProperties.setProperty('_jointsTexture', texture.getImpl());
和 material 一致用 setProperty

2019-01-07 01:22 UTC, 2youyou2 commented on cocos2d/core/renderer/webgl/model-batcher.js
> +        if ((material && material.getHash() !== this.material.getHash()) ||
做 mesh 合并的时候再做考虑了

2019-01-07 01:24 UTC, 2youyou2 commented on cocos2d/core/mesh/mesh-renderer.js
> +        renderer.customProperties = comp._customProperties;
做 mesh 合并的时候再考虑一下