Don't merge , just for reviewing
cocos/cocos-engine pull request #3626
Opened 2018-12-12 15:37 UTC by holycanvas

Re: cocos-creator/2d-tasks#

Changes:
 * 不要合并，只是为了review
内容：
1.pipeline.js
         将与业务相关的内容移除pipeline.js
         取消pipe与pipeline的耦合
         pipe改为可基于任意函数构造匹配，不需要有handle方法
         封装了task，用于在pipeline中流动，相关数据回调都存放在task中，task从一个pipeline中流出还可以进入其他pipeline，可以用于只执行部分管道的需求，同时这样pipe与task也没有耦合了，同个pipe可以在多个pipeline中复用。
         增加了onError回调，报错时调用onError，不从onComplete走

2.asset-config.js
         将之前ccAssetLibrary中存储配置的部分迁移了过来，同时更彻底，包括md5配置，以及assetTable的配置全部存放在asset-config中，将原来各个地方查看配置的方法统一挪到了这个地方，作为统一接口。提供初始化函数。

3.ccloader.js
         cc.loader作为资源系统的对外接口，init函数是初始化入口，在init中初始化asset-config，ccloader不再继承pipeline，而是拥有多条pipeline，用于满足各类加载需求

4.handle-request.js
         处理资源请求，将之前的asset-loader和md5pipe中的内容合在了这个管道中，并增加add depends等步骤

5.asset-cache.js
         因为各个pipe都有可能会使用全局的cache，将之前在pipeline中的cache单独移出来作为一个单独的部分

2018-12-13 07:14 UTC, pandamicro commented
麻烦关联到 issue 中

2018-12-13 07:45 UTC, pandamicro commented
@shrinktofit @2youyou2 你们对资源系统都有一定的了解，麻烦审核一下给出你们的意见

重构讨论 issue https://github.com/cocos-creator/2d-tasks/issues/874

2019-01-06 15:30 UTC, pandamicro commented
现在的修改对包体影响很大，麻烦仔细斟酌一下，按理说我们往逻辑更清晰的方向去优化，代码应该是有所缩减的。

我注意到有一个 worker 的模块，可能是考虑多线程下载和解析？这种情况下如果可以做独立的模块剔除以及自动 fallback 方案，用户打包时自己选择用不用，我是不太介意的。但是除去那个模块仍然有三千多行的添加，就有点夸张了

2019-01-07 03:43 UTC, holycanvas commented
现在没有在之前的基础上改，之前的代码都没有删除的，理论上完成后，load-pipeline文件夹可以直接删除掉，现在load-pipeline都有4000多行，完成之后是会比现在的包体小的

2019-01-07 11:54 UTC, pandamicro commented
好的，收到～

2019-02-12 02:46 UTC, pandamicro reviewed
有两个全局的问题

1. 小的模块没有添加说明，要理清它的职责以及和其他模块的关系比较困难
2. 命名问题，只有类名应该首字母大写，函数、类实例对象都应该用首字母小写

2019-02-12 02:46 UTC, pandamicro commented on cocos2d/core/asset-manager/asset-manager.js
> +cc.AssetManager = new AssetManager();
对象不应该用大写开头，为了兼容旧版本，是不是 cc.assetManager 就是 cc.loader

2019-02-12 02:46 UTC, pandamicro commented on cocos2d/core/asset-manager/cache.js
> +        return Object.keys(this._map).length;
length 一般是一个属性，设计成方法很容易导致使用的时候写错，而且 JS 还不报错。
另外，建议跟踪记录一个 count 值，否则假设上层遍历 Cache，把 length 获取放在了 for 循环的条件里面，就容易导致创建很多垃圾数组

2019-02-12 02:46 UTC, pandamicro commented on cocos2d/core/asset-manager/depends.js
> +            if (json instanceof cc.Asset) {
这种情况下，用 asset 来代替 json 把，否则阅读代码有点障碍

let asset = json;

2019-02-12 02:46 UTC, pandamicro commented on cocos2d/core/asset-manager/depends.js
> +                    switch (json.constructor) {
貌似应该通过一个通用的接口获取到 nativeDep，否则扩展性比较差，比如

out.nativeDep = asset.constructor.createNativeDepInfo(asset, uuid)

2019-02-12 02:46 UTC, pandamicro commented on cocos2d/core/asset-manager/depends.js
> +                function parseProp (data, out) {
这个函数看起来只是递归解析出 uuid dependencies，命名有问题，没有体现递归，而且跟 property 没什么关系。

2019-02-12 02:46 UTC, pandamicro commented on cocos2d/core/asset-manager/depends.js
> +        parse: function (uuid, json) {
感觉这个 parse 支持的可能性太多了，不太好维护的感觉，有必要吗？

2019-02-12 02:46 UTC, pandamicro commented on cocos2d/core/asset-manager/depends.js
> +                    switch (type) {
同样的，应该用 ctor.createNativeDepInfo 之类的 API

2019-02-12 02:46 UTC, pandamicro commented on cocos2d/core/asset-manager/depends.js
> +var Depends = (function () {
添加一下类的功能描述，方便审阅和维护

2019-02-12 02:46 UTC, pandamicro commented on cocos2d/core/asset-manager/deserialization.js
> +module.exports = deserialize;
保持文件名和导出的函数名一致

2019-02-12 02:46 UTC, pandamicro commented on cocos2d/core/asset-manager/downloader.js
> +    var func = createImageBitmap && (window.location.protocol === 'file:' || !options.isCrossOrigin) ? Downloader.downloadBlob : Downloader.downloadDomImage;
createImageBitmap 没有见到这个函数的定义

2019-02-12 02:46 UTC, pandamicro commented on cocos2d/core/asset-manager/downloader.js
> +    var func = createImageBitmap && (window.location.protocol === 'file:' || !options.isCrossOrigin) ? Downloader.downloadBlob : Downloader.downloadDomImage;
downloadBlob 的方式比 dom Image 更高效吗？优势在哪里？

2019-02-12 02:46 UTC, pandamicro commented on cocos2d/core/asset-manager/helper.js
> +        if (array.length === 0) onComplete(null);
这里也要检查 onComplete 是否存在，总共漏了三处

2019-02-12 02:46 UTC, pandamicro commented on cocos2d/core/asset-manager/asset-manager.js
> +    this.Config = Config;
接口上看并不是 private 啊

2019-02-12 02:46 UTC, pandamicro commented on cocos2d/core/asset-manager/asset-manager.js
> + * @param {String|String[]|Object} resources - Url list in an array
options 的作用没有描述

2019-02-12 02:46 UTC, pandamicro commented on cocos2d/core/asset-manager/asset-manager.js
> +    this._loadPipeline = new Pipeline('normal load', [handleRequest, load]);
按理说 loadPipeline 应该是包含 handleRequest, fetching, load 才对啊

2019-02-12 02:46 UTC, pandamicro commented on cocos2d/core/asset-manager/asset-manager.js
> +proto.createByUrl = function (url, ctor, options, onProgress, onComplete) {
上面这四个函数是为了提供便利性？

2019-02-12 02:46 UTC, pandamicro commented on cocos2d/core/asset-manager/asset-manager.js
> +proto.releaseUnuseAsset = function () {
releaseUnusedAsset

2019-02-12 02:46 UTC, pandamicro commented on cocos2d/core/asset-manager/handle-request.js
> +            default:
default 是用来处理用户传递的自定义 option 的？如果有的话，一般有什么样的用例呢？

2019-02-12 02:46 UTC, pandamicro commented on cocos2d/core/asset-manager/load.js
> +                                        depend.owner[depend.prop] = assets[index];
没看到对 addRef 操作，按理说这里和 initialize 做的应该要一样吧？

2019-02-12 02:46 UTC, pandamicro commented on cocos2d/core/asset-manager/asset-manager.js
> +    var load = new Pipeline.Pipe('load asset', Load);
不同过程之间的关系比较混乱，这里面貌似是有包含关系的，需要描述得更清晰一些

2019-02-12 02:46 UTC, pandamicro commented on cocos2d/core/asset-manager/asset-manager.js
> +    var prefetch = new Pipeline.Pipe('prefetch', Prefetch);
prefetch 和 fetch 的区别在哪里？大致看了下都会用 Downloader，不是很理解

2019-03-31 14:45 UTC, jareguo commented on cocos2d/core/CCDirector.js
> +            finalizer._autoRelease(oldScene, scene, persistNodeList);
这里把逻辑都封装到 finalizer._autoRelease 里面了？

2019-03-31 14:45 UTC, jareguo commented on cocos2d/core/CCDirector.js
> +    loadScene: function (sceneName, onProgress, onLaunched, _onUnloaded) {
这里插入了一个参数会有兼容性问题，而且已经很难看出哪个是哪个了。
建议改为两种调用方式：
 - loadScene (sceneName, [options], [onLaunched]) - options, onLaunched 可选。onProgress, onUnloaded 放到 options。将来扩展 options 也简单。
 - loadScene (sceneName, onLaunched, _onUnloaded) - 兼容旧版本，给出警告让他升级

2019-03-31 14:45 UTC, jareguo commented on cocos2d/core/asset-manager/CCAssetManager.js
> +var assetManager = {
麻烦补充一下 API 注释，可参考 cc.js 的写法。

2019-03-31 14:45 UTC, jareguo commented on cocos2d/core/asset-manager/CCAssetManager.js
> +    _loadPipeline: new Pipeline('normal load', [preprocess, load]),
_loadPipeline 和 _loadPipe，字面区别感觉很小啊……

2019-03-31 14:45 UTC, jareguo commented on cocos2d/core/asset-manager/CCAssetManager.js
> +    _builtin: {},
字典请统一用 Object.create(null) 或 js.createMap(true)

2019-03-31 14:45 UTC, jareguo commented on cocos2d/core/asset-manager/CCAssetManager.js
> +     * @param {String|String[]|Object|Object[]|cc.assetManager.Task} requestsOrTask - The request should be loaded or a preloaded task
这里真的可以用 should be 吗？

2019-03-31 14:45 UTC, jareguo commented on cocos2d/core/asset-manager/CCAssetManager.js
> +     * cc.assetManager.load([{ directory: 'images', type: cc.SpriteFrame, mount: 'internal' }, '60sVXiTH1D/6Aft4MRt9VC'], (err, assets) => cc.log(assets));
建议 directory -> dir, 呼应之前的 loadResDir

2019-03-31 14:45 UTC, jareguo commented on cocos2d/core/asset-manager/CCAssetManager.js
> +     * var task = cc.assetManager.preload('0cbZa5Y71CTZAccaIFluuZ', (err) => cc.assetManager.load(task, (err, asset) => cc.log(asset)));
这里的 cc.assetManager.load 其实在 preload 还未完成时也可以直接调用的吧？如果是的话建议不要放到回调里，更清晰一些。

2019-03-31 14:45 UTC, jareguo commented on cocos2d/core/asset-manager/CCAssetManager.js
> +    preload: function (requests, options, onProgress, onComplete) {
API 注释记得哈

2019-03-31 14:45 UTC, jareguo commented on cocos2d/core/asset-manager/CCAssetManager.js
> +     * 从 v1.3 开始，这个方法不仅会从 assetManager 中删除资源的缓存引用，还会清理它的资源内容。
去掉”从 v1.3 开始“

2019-03-31 14:45 UTC, jareguo commented on cocos2d/core/asset-manager/caches.js
> +        this._length--;
这里可能要判断下，如果 key 不存在，就不用 length--

2019-03-31 14:45 UTC, jareguo commented on cocos2d/core/asset-manager/caches.js
> +        js.clear(this._map);
其实这里直接给 this._map 重新赋值会快一些（js.clear 是因为属性可能被外部缓存，所以不想改变引用）

2019-03-31 14:45 UTC, jareguo commented on cocos2d/core/asset-manager/caches.js
> +        if (typeof func !== 'function') return;
其实我觉得这个容错没啥意义，如果 func 不是函数，引擎自然报错就好了。

2019-03-31 14:45 UTC, jareguo commented on cocos2d/core/asset-manager/caches.js
> +    get length () {
其实我觉得用 count 是更合适的。对用户来说计数时，更关心的其实也是数量。
length 适合数组，不适合其它容器。

2019-03-31 14:45 UTC, jareguo commented on cocos2d/core/asset-manager/caches.js
> +    depends: new Cache()
以前这些信息应该都是在 loading-items 里面吧。把这些缓存都拆开后，会不会导致查询一个资源状态时，需要依次做好多次查询操作才行？

2019-03-31 14:45 UTC, jareguo commented on cocos2d/core/asset-manager/config.js
> +                if (assetInfos[uuid]) {
最近我接触到的最大的项目（问道）构建后已经有 20 万个资源了…… 因此建议这里缓存 assetInfos[uuid] 对象，避免重复查询

2019-03-31 14:45 UTC, jareguo commented on cocos2d/core/asset-manager/config.js
> +                if (condition(item, array[m]) < 0) {
缩进注意下

2019-03-31 14:45 UTC, jareguo commented on cocos2d/core/asset-manager/config.js
> +                            binarySearchInsert(temp, pack, compare);
为什么需要用二分法插入？packs 是一个排序后的数组？？

2019-03-31 16:47 UTC, jareguo commented on cocos2d/core/asset-manager/downloader.js
> +    return __audioSupport.WEB_AUDIO && context ? function (url, options, onComplete) {
__audioSupport.WEB_AUDIO 成立时，如果 context 这个变量一定要用到的话，为什么还要判断呢？如果不存在 context 直接设 __audioSupport.WEB_AUDIO 为 false 就好了吧

2019-03-31 16:47 UTC, jareguo commented on cocos2d/core/asset-manager/downloader.js
> +    maxLaunchPerframe: 6,
建议叫 maxRequest**s**Per**F**rame。这个参数有意义吗？不是本身就有 maxConcurrent 限制着。又不是 preload，肯定是加载越快越好啊？

2019-03-31 16:47 UTC, jareguo commented on cocos2d/core/asset-manager/downloader.js
> +    preloadMaxConcurrent: 4,
建议叫 maxPreloadConcurrent

2019-03-31 16:47 UTC, jareguo commented on cocos2d/core/asset-manager/downloader.js
> +    preloadMaxLaunchPerframe: 2,
建议叫 maxPreloadRequest**s**Per**F**rame

2019-03-31 16:47 UTC, jareguo commented on cocos2d/core/asset-manager/downloader.js
> +    retryTimes: 3,
建议用 maxRetryCount

2019-03-31 16:47 UTC, jareguo commented on cocos2d/core/asset-manager/downloader.js
> +     * The max number of retrys when fail
retrys -> retries

2019-03-31 16:47 UTC, jareguo commented on cocos2d/core/asset-manager/downloader.js
> +    downloadDomImage: function (url, options, onComplete) {
直接 downloadDomImage: downloadDomImage, 不就好了吗

2019-03-31 16:47 UTC, jareguo commented on cocos2d/core/asset-manager/downloader.js
> +     * @function downloadDomScript
API 注释应该是 `@method` 不是 `@function`

2019-03-31 16:47 UTC, jareguo commented on cocos2d/core/asset-manager/helper.js
> +                        setTimeout(next, wait(index));
建议直接 wait * index，wait 传入一个值

2019-03-31 16:47 UTC, jareguo commented on cocos2d/core/asset-manager/helper.js
> +        (function next () {
通常只有资源加载失败时才需要重试，因此这里不建议每次加载都创建这么一个立即函数，建议用
```
retry: function (process, maxRetry, wait, onComplete, times) {
  times = times || 0;
  process(times, function (err, result) {
    ...
    if (err) {
      setTimeout(function () {
        helper.retry(process, maxRetry, wait, onComplete, times + 1);
      }, ...);
    }
  }
}
```

2019-03-31 16:47 UTC, jareguo commented on cocos2d/core/asset-manager/finalizer.js
> +    if ( !excludeMap[key] ) {
感觉这个判断是多余的，直接赋值就行了吧

2019-03-31 16:47 UTC, jareguo commented on cocos2d/core/asset-manager/finalizer.js
> +            if (uuid in excludeMap) continue;
感觉这里直接统一赋值就行了，开销差不多

2019-03-31 16:47 UTC, jareguo commented on cocos2d/core/asset-manager/finalizer.js
> +        function free (asset, recursively, excludeMap, force) {
free 函数如果不需要成为闭包，并且 release 需要经常调用，建议放到外面。否则会有性能开销（参考 #4042 ）

2019-03-31 16:47 UTC, jareguo commented on cocos2d/core/asset-manager/helper.js
> +    getXMLHttpRequest: function () {
ActiveXObject 是 IE6 时代的产物了，从 IE7 开始就支持 XMLHttpRequest 了，去掉吧，直接 new XMLHttpRequest()

2019-03-31 16:47 UTC, jareguo commented on cocos2d/core/assets/CCAsset.js
> +            return Object.values(depends);
values 是 ES2017 才有的函数，不建议使用

2019-03-31 16:47 UTC, jareguo commented on cocos2d/core/assets/CCAsset.js
> +                else if (data.__uuid__) {
建议缓存 `data.__uuid__`

2019-03-31 16:47 UTC, jareguo commented on cocos2d/audio/CCAudioEngine.js
> +     * cc.assetManager.loadRes(url, {type: cc.AudioClip}, function (err, clip) {
这些 loadRes 的 example 都写错了吧？第二个参数应该是 type 本身，不是一个 object

2019-03-31 16:47 UTC, jareguo commented on package.json
> +    "gulp-cli": "^2.0.1"
这个是误加进来的吧？

2019-03-31 16:50 UTC, jareguo commented
之前的 CCAssetLibrary，CCLoader，MD5Pipe 等常用接口，请都在一个文件里集中做一下兼容。能兼容的 API 尽量兼容，不能兼容的 API 给出相应的修改范例。

2019-04-01 01:51 UTC, holycanvas commented on cocos2d/core/asset-manager/handle-request.js
> +            default:
现在load方法的一个机制就是把options的项复制到每个请求的request-item中，整个加载流程中每个能用上选项都可以在options制定，比如下载时用到的header，是否预加载，是否跨域，以及用户想自定义的方法

2019-04-01 01:53 UTC, holycanvas commented on cocos2d/core/asset-manager/asset-manager.js
> +    var prefetch = new Pipeline.Pipe('prefetch', Prefetch);
downloader在多个流水线或者用户都可以直接用，所以现在downloader是单独的模块，只负责下载资源，不管流程上的事了，流水线可以任何使用

2019-04-01 01:55 UTC, holycanvas commented on cocos2d/core/CCDirector.js
> +            finalizer._autoRelease(oldScene, scene, persistNodeList);
是的，主要觉得这里有做很多资源相关的查询，干脆封装到autoRelease里面去了

2019-04-01 01:56 UTC, holycanvas commented on cocos2d/core/asset-manager/CCAssetManager.js
> +var assetManager = {
api注释实在太多了，正在写

2019-04-01 01:57 UTC, holycanvas commented on cocos2d/core/asset-manager/CCAssetManager.js
> +    _loadPipeline: new Pipeline('normal load', [preprocess, load]),
我也不知道怎么命名好了，loadPipe是一个管道，loadPipeline是包含loadPipe的整个管线

2019-04-01 02:05 UTC, holycanvas commented on cocos2d/core/asset-manager/caches.js
> +    depends: new Cache()
并没有拆开，实际上以前都没有这些缓存的，以前只有一个asset的缓存，因为以前在加载的时候会先去查询当前是否在加载这个资源，复用这个item，但是现在因为有多个流程，流程的构造不一样的，比如load流水线不能复用preload的item，因为preload下载完就结束了，所以不能复用同样的item，为了不重新解析，所以把加载流程中产生的中间产物都缓存下来，不同的缓存现在逻辑也不一样，比如file缓存和parsed缓存在完成加载之后会被清除，因为之后用不上了，depends的缓存要在释放之后才会删除，因为可能会调用getDepends，所以现在用多个缓存

2019-04-01 02:07 UTC, holycanvas commented on cocos2d/core/asset-manager/config.js
> +                            binarySearchInsert(temp, pack, compare);
这里是参考之前的逻辑，packs里面由小到大排序，优先去取最小的pack来下载

2019-04-01 02:12 UTC, holycanvas commented on cocos2d/core/asset-manager/downloader.js
> +    maxLaunchPerframe: 6,
对load来说，这个值默认设置和maxConcurrent一样的，不影响load过程，这个参数也是为了统一preload和load的逻辑，同时，如果用户存在加载动画，希望加载也较为流畅，也是可以使用这个值的

2019-04-01 02:13 UTC, holycanvas commented on cocos2d/audio/CCAudioEngine.js
> +     * cc.assetManager.loadRes(url, {type: cc.AudioClip}, function (err, clip) {
最近一直在小优化，loadRes改成直接用type本身也是最近改的，这里还没改过来

2019-04-01 02:16 UTC, holycanvas commented
我上周才拉的最新版master，把新增的包括etc的特性的支持都加上了，这周又有这么多冲突了。。。

2019-04-01 03:22 UTC, jareguo commented
master 很久没更新了…… 上次更新的是去年的时候 ……

2019-04-01 03:23 UTC, jareguo commented on cocos2d/core/asset-manager/downloader.js
> +    maxLaunchPerframe: 6,
了解

2019-04-01 03:28 UTC, jareguo commented on cocos2d/core/asset-manager/caches.js
> +    depends: new Cache()
了解

2019-04-01 03:29 UTC, jareguo commented on cocos2d/core/CCDirector.js
> +            finalizer._autoRelease(oldScene, scene, persistNodeList);
了解

2019-04-01 04:32 UTC, jareguo commented on cocos2d/core/asset-manager/config.js
> +                if (assetInfos[packUuid]) {
这里不可能存在 assetInfos 里面吧？如果存在的话，那也不应该覆盖之前的数据才对，而是应该报错

2019-04-01 04:32 UTC, jareguo commented on cocos2d/core/asset-manager/config.js
> +                            binarySearchInsert(temp, pack, compare);
了解。其实之前的逻辑更简单，只判断 pack.packs.length === 1，是的话插入最前面。这样能覆盖半数以上的情况。
这里我觉得与其要做这么严谨的插入排序，不如在编辑器导出 settings.js 时就排好序。
目前编辑器的排序规则是按字母顺序，可以改成按照包的大小，从小到大排序。**大小相同时采用字母排序。**
这样引擎解析时只需要直接 push 就行，不用再次排序

2019-04-01 09:08 UTC, holycanvas commented on cocos2d/core/asset-manager/config.js
> +                if (assetInfos[packUuid]) {
有md5的情况下，可能存在这个情况，我可以把初始化顺序调一下，把pack放在前面，md5放在后面，这样就可以少判断一次了

2019-04-01 11:46 UTC, holycanvas commented
@jareguo 现在packAssets是以对象形式存的，packId是key，没有看到有对字母进行排序的地方呀

2019-04-02 05:47 UTC, jareguo commented
奇怪，我也没找到，可能是我记错了………………

2019-05-05 08:53 UTC, pandamicro requested changes

2019-05-05 08:53 UTC, pandamicro commented on cocos2d/core/CCDirector.js
> +        if (sceneName instanceof cc.assetManager.Task) {
为什么要兼容这种参数？

2019-05-05 08:53 UTC, pandamicro commented on cocos2d/core/CCDirector.js
> +            return cc.assetManager.preload(info.uuid, null,
更新一下 return value 的 api 注释，以及它的用途是什么

2019-05-05 08:53 UTC, pandamicro commented on cocos2d/core/CCDirector.js
> +        if (arguments.length !== 5) {
可以用 dontRunScene === undefined 来判断

2019-05-05 08:53 UTC, pandamicro commented on cocos2d/core/asset-manager/CCAssetManager.js
> +    _loadPipeline: new Pipeline('normal load', [preprocess, load]),
没毛病，实在看不习惯可以叫 _completePipeline

2019-05-05 08:53 UTC, pandamicro commented on cocos2d/core/asset-manager/CCAssetManager.js
> +        this._caches.depends.clear();
这些 cache 好像也不是跟 Pipe 关联的，如果强关联应该可以放在 Pipe 中，为什么要放在这里呢？

2019-05-05 08:53 UTC, pandamicro commented on cocos2d/core/asset-manager/CCAssetManager.js
> +     * cc.assetManager.load([{ path: 'images/a', type: cc.SpriteFrame }, '60sVXiTH1D/6Aft4MRt9VC'], (err, assets) => cc.log(assets));
url 和 path 的区别是什么？

2019-05-05 08:53 UTC, pandamicro commented on cocos2d/core/asset-manager/CCAssetManager.js
> +     * cc.assetManager.load(['image/a', 'image/b'], {key: 'path', type: cc.SpriteFrame}, null, (err, assets) => cc.log(assets));
key 是指示数组中的 url 类型吗？有必要吗？

2019-05-05 08:53 UTC, pandamicro commented on cocos2d/core/asset-manager/CCAssetManager.js
> +    createByUrl: function (url, ctor, options, onProgress, onComplete) {
createByUrl 和 loadByUrl 的区别在哪里？需要单独提供一个公开 API 吗？命名似乎也不合适，从命名看不出它的意义

2019-05-05 08:53 UTC, pandamicro commented on cocos2d/core/asset-manager/CCAssetManager.js
> +    _initBuiltins: function (cb) {
这个接口不应该在 loader 中，应该在 game 中

2019-05-05 08:53 UTC, pandamicro commented on cocos2d/core/asset-manager/CCAssetManager.js
> +    _getBuiltin: function (type, name) {
Loader 只负责加载，builtin 对他来说也只是其中一部分，上层接口放在上层模块中

2019-05-05 08:53 UTC, pandamicro commented on cocos2d/core/asset-manager/CCAssetManager.js
> +    _loadBuiltins: function (name, cb) {
实际上连 loadBuiltin 都应该放在上层模块中

2019-05-05 08:53 UTC, pandamicro commented on cocos2d/core/asset-manager/CCAssetManager.js
> +     * @param {String[]} completeCallback.urls - An array that lists all the URLs of loaded assets.
如果不考虑兼容问题，你觉得是不是应该改为
```
assets = {
    url0: asset0,
    ...
}
```
这种方式？

2019-05-05 08:53 UTC, pandamicro commented on cocos2d/core/asset-manager/CCAssetManager.js
> +    releaseResDir: function (directory, type, recursively, excludeMap, force) {
这种接口不需要提供了把，感觉用户用起来也很危险

2019-05-05 08:53 UTC, pandamicro commented on cocos2d/core/asset-manager/caches.js
> +    assets: new Cache(),
有两个问题，

1. Cache 定义的模块中不应该包含预创建的 Cache，应该是上层使用这个模块创建
2. 是否应该由使用的 Pipe 来自主创建 Cache，而不是一个统一无法适应新需求的预创建 Cache 列表

2019-05-05 08:53 UTC, pandamicro commented on cocos2d/core/asset-manager/config.js
> +var config = {
config 中的 info 从意义上来看和 caches 有重合，两者能否合并？会有什么问题？

2019-05-05 08:53 UTC, pandamicro commented on cocos2d/core/asset-manager/config.js
> +    init: function (options) {
这个函数过长了，优化一下

2019-05-05 08:53 UTC, pandamicro commented on cocos2d/core/asset-manager/config.js
> +        var infos = [];
尽量避免在 Loader 这种底层模块中创建任何临时内存，类似的需求可以在接口中添加 out 参数

2019-05-05 08:53 UTC, pandamicro commented on cocos2d/core/asset-manager/depend-util.js
> +    getDepend: function (uuid) {
getDeps

2019-05-05 08:53 UTC, pandamicro commented on cocos2d/core/asset-manager/depend-util.js
> +    getDepend: function (uuid) {
命名风格统一一下好了，depend 是动词，而且之前出现了 getNativeDep，所以统一都用 dep 作为 dependency 的缩写好了。

2019-05-05 08:53 UTC, pandamicro commented on cocos2d/core/asset-manager/depend-util.js
> +    getDependRecursively: function (uuid) {
getDepsRecursively

2019-05-05 08:53 UTC, pandamicro commented on cocos2d/core/asset-manager/downloader.js
> +const downloadDomScript = require('./download-dom-script');
目前决定是拆分出去还是留在 downloader 中实现的依据是什么？

2019-05-05 08:53 UTC, pandamicro commented on cocos2d/core/asset-manager/downloader.js
> +    maxLaunchPerframe: 6,
我看着着四个 Max 也很混乱，注释再清晰一些

2019-05-05 08:53 UTC, pandamicro commented on cocos2d/core/asset-manager/downloader.js
> +     * use handler to download file within limition
limition -> limitation

2019-05-05 08:53 UTC, pandamicro commented on cocos2d/core/asset-manager/fetch.js
> +    forEach(input, function (item, cb) {
这种写法看起来每次调用 fetch 都在创建不少匿名函数，对内存不友好，需要优化

2019-05-05 08:53 UTC, pandamicro commented on cocos2d/core/asset-manager/initializing.js
> +    forEach (input, function (item, cb) {
和 fetch 的问题一样，用更结构化的代码来避免直接创建和传递匿名函数

2019-05-05 08:53 UTC, pandamicro commented on cocos2d/core/asset-manager/preprocess.js
> +function preprocess (task, done) {
这个 pipe 的写法要比使用 forEach 的几个要干净不少

2019-05-05 08:53 UTC, pandamicro commented on cocos2d/core/asset-manager/tasking.js
> +        try {
不要在运行时使用 try catch，运行时 catch 住的错误大多数也是无法处理的，只要自然报错并提供 retry 机制就可以了。在编辑器环境下使用 try catch 避免编辑器挂掉没问题

2019-05-05 08:53 UTC, pandamicro commented on cocos2d/core/assets/CCAsset.js
> +        _nativeDepend: {
_nativeDep

2019-05-05 08:53 UTC, pandamicro commented on cocos2d/core/assets/CCAudioClip.js
> +        _parseDependsFromJson: function () {
_parseDepsFromJson

2019-05-05 08:53 UTC, pandamicro commented on cocos2d/core/assets/CCTTFFont.js
> +        _parseNativeDepFromJson: function (json) {
_parseNativeDepsFromJson

2019-05-06 10:46 UTC, jareguo commented on cocos2d/core/asset-manager/CCAssetManager.js
> +    _preprocesPipe: preprocess,
process，拼错了

2019-05-06 10:46 UTC, jareguo commented on cocos2d/core/asset-manager/CCAssetManager.js
> +    _loadPipeline: new Pipeline('normal load', [preprocess, load]),
_completePipeline 更乱了，等于 load 是一个步骤，complete 是一个步骤。
其实我觉得 pipe 和 pipeline 的差异还是不够大，除非有相关领域（如图形学、Streaming）的开发经验，否则很难 get 到英文上的差异。
建议这两个变量改为：
_loadPipe
_pipeline

2019-05-07 10:32 UTC, holycanvas commented on cocos2d/core/CCDirector.js
> +        if (sceneName instanceof cc.assetManager.Task) {
因为现在的预加载是使用preload函数加载，这个方法会返回一个task对象，等到需要用的时候再将这个task传到load方法中，就可以接着预加载的流程完成加载，所以需要loadScene方法里兼容task参数

2019-05-07 10:33 UTC, holycanvas commented on cocos2d/core/CCDirector.js
> +            return cc.assetManager.preload(info.uuid, null,
return的值是个task，为了能在之后进行继续加载

2019-05-07 10:36 UTC, holycanvas commented on cocos2d/core/asset-manager/CCAssetManager.js
> +        this._caches.depends.clear();
这些缓存除了packages之外，都有可能在各种不同的管道中访问，所以没有放在管道中

2019-05-07 10:37 UTC, holycanvas commented on cocos2d/core/asset-manager/preprocess.js
> +function preprocess (task, done) {
因为这个pipe是处理url的，同步的，所以比较简单，而其他管道都是异步的，所以封装了一个forEach的异步处理，类似Promise.All的效果

2019-05-07 10:44 UTC, holycanvas commented on cocos2d/core/asset-manager/tasking.js
> +        try {
加载过程包含了一个preprocess阶段，这个阶段是用来处理各种参数以及url的拼接的，因为参数很多，有可能会因为用户传入的参数发生各种异常，如果不用try catch捕获异常的话，那我无法在执行onComplete的时候，将错误信息返回给他

2019-05-08 02:11 UTC, holycanvas commented on cocos2d/core/asset-manager/CCAssetManager.js
> +     * cc.assetManager.load([{ path: 'images/a', type: cc.SpriteFrame }, '60sVXiTH1D/6Aft4MRt9VC'], (err, assets) => cc.log(assets));
url就是真实的url，比如http://cloud.com/a.png，path是指在resources下的相对路径，比如/images/a.jpg，loadRes时使用的就是path

2019-05-08 02:16 UTC, holycanvas commented on cocos2d/core/asset-manager/CCAssetManager.js
> +     * cc.assetManager.load(['image/a', 'image/b'], {key: 'path', type: cc.SpriteFrame}, null, (err, assets) => cc.log(assets));
key是指明load传入的第一个参数是什么类型的参数，这里主要考虑的是批量操作，如果指定了key，那么用户用load时的第一个参数可以传字符串的数组，整个数组中的字符串都会被指定为这个类型，如果没有key来批量指定的话，那么用户在load时只能传入[{path: 'image/a'}, {path: 'image/b'}]，每个资源都必须指定类型，会比较麻烦

2019-05-08 02:30 UTC, holycanvas commented on cocos2d/core/asset-manager/CCAssetManager.js
> +    createByUrl: function (url, ctor, options, onProgress, onComplete) {
loadByUrl实际上和cc.assetManager.load(['http://cloud.com/a.json'], {key: 'url'}, onProgress, onComplete)是一模一样的，因为load可选参数太多，不太适合新入坑的开发者，所以提供了一个loadByUrl，更少参数，只通过url来加载。
而createByUrl通过url来创建资源，因为现在的加载流程和之前的cc.loader有个不同的地方，cc.loader如果直接传图片的url进去，ccloader会默认返回一个新构造的Texture对象。这会造成很多时候不需要新建Texture的时候，必须用skip: [ loader ]，跳过loader来实现这个操作。所以现在为了统一流程，传入图片url的时候不会主动帮你新建Texture对象，只会按照图片的加载流程返回Image对象或者ImageBitmap对象。如果用户是想新建一个资源对象，那他可以调用createByUrl，这个时候返回的就是一个资源对象

2019-05-08 02:53 UTC, holycanvas commented on cocos2d/core/asset-manager/caches.js
> +    assets: new Cache(),
除了package的缓存只有在pack-manager中使用了，其他的包括assets，files,  depends, parsed, 都在多个pipe中有使用，不同加载管线都会使用这些缓存，如果在某个pipe中新建cache，那就复用不了在其他加载流程中可复用的一些东西，会造成重复加载，重复解析等工作

2019-05-08 03:01 UTC, holycanvas commented on cocos2d/core/asset-manager/config.js
> +var config = {
区别有几点：1.info是资源的配置信息，比如url，uuid，path，type，ext，subpackages，pack等信息，就是一堆字符串。而cache里面存的是资源对象，资源的文件，资源解析后的对象。存的不是一类东西。2.config里面存的配置信息，跟加载流程无关，是不变的，整个游戏运行期间极少变动，而caches中的东西随着加载流程不断增删变化。3.用户会有需求主动查询资源的配置信息，但很少有需求去动缓存中的内容，缓存中的内容也不建议用户直接操作

2019-05-08 03:10 UTC, holycanvas commented on cocos2d/core/asset-manager/downloader.js
> +const downloadDomScript = require('./download-dom-script');
拆分出去的下载操作都是原子操作，也就是说不能再细分了，都是独立的。这几个操作都是开放出去的，也方便我们在adapter中覆盖。留在downloader中的操作都是可以用这几个原子操作实现的操作，比如downloadArrayBuffer可以用downloadFile来实现，这些操作代码少，也不开放出去，只在downloader中有使用，所以就在downloader中实现了

2019-05-08 03:27 UTC, holycanvas commented on cocos2d/core/asset-manager/initializing.js
> +    forEach (input, function (item, cb) {
实际上性能问题其实不大，我测试过，数十万次匿名函数的调用才能造成毫秒级的区别，但是资源加载不频繁，资源一次加载的数目最多也就几百个，影响太小，而下载一个资源的时长就可能超过100ms以上，也就是说加载流程的主要瓶颈在io，从js执行层面能优化的性能连0.5%都不到。这里不用匿名函数的话，代码的可读性还要在降低一些，现在都已经不怎么好看了。这个还要权衡一下

2019-05-08 07:37 UTC, holycanvas commented on cocos2d/core/asset-manager/CCAssetManager.js
> +     * var task = cc.assetManager.preload('0cbZa5Y71CTZAccaIFluuZ', (err) => cc.assetManager.load(task, (err, asset) => cc.log(asset)));
可以调用是可以调用，但是load会用到preload完成之后的内容，如果不在回调里写的话，load出来的东西肯定是不对的

2019-05-08 08:23 UTC, holycanvas commented on cocos2d/core/asset-manager/downloader.js
> +    downloadDomImage: function (url, options, onComplete) {
![image](https://user-images.githubusercontent.com/15109777/57360716-6f2cd200-71ad-11e9-86f9-177cb655caa0.png)
这样写，注释里标注的参数类型识别不出来

2019-05-08 10:51 UTC, holycanvas commented on cocos2d/core/asset-manager/CCAssetManager.js
> +     * @param {String[]} completeCallback.urls - An array that lists all the URLs of loaded assets.
实际上如果从我的角度来说，我更希望返回的是数组，

1.当我调用load的时候，传入一个uuid，返回一个资源，传入一个uuid的数组，返回一个资源数组。这个过程是协调的，而且理解起来比较容易，返回值只会是asset或者asset的数组，如果返回一个对象，有时候还需要判断assets instanceof cc.Asset。

2.即使返回一个以url为key，asset为value的对象，使用起来依旧很不方便，因为用户传入的参数可能是path，uuid，dir等不同参数，最后返回的key是真实url，形如res/import/9a/9asdwe-dsda1-32341-dsaew.json，看到这种key实际上用户根本不知道哪个对应哪个资源，最后还是会用for遍历一次或者通过cc.assetManager.getRes传path来获取。

2019-05-09 02:22 UTC, holycanvas commented on cocos2d/core/assets/CCTTFFont.js
> +        _parseNativeDepFromJson: function (json) {
原生依赖只有一个呀，不存在多个的情况

2019-05-15 12:30 UTC, pandamicro commented on cocos2d/core/asset-manager/tasking.js
> +        try {
那就单独在那个阶段里面捕获吧，不要在通用的 task 里面加

2019-05-15 12:31 UTC, pandamicro commented on cocos2d/core/CCDirector.js
> +        if (sceneName instanceof cc.assetManager.Task) {
能不能用字典缓存，通过 sceneName 找到 Task？

2019-05-15 12:32 UTC, pandamicro commented on cocos2d/core/asset-manager/CCAssetManager.js
> +     * cc.assetManager.load([{ path: 'images/a', type: cc.SpriteFrame }, '60sVXiTH1D/6Aft4MRt9VC'], (err, assets) => cc.log(assets));
url 和 relativeUrl 可能比较清晰一些

2019-05-15 12:33 UTC, pandamicro commented on cocos2d/core/asset-manager/CCAssetManager.js
> +     * cc.assetManager.load([{ path: 'images/a', type: cc.SpriteFrame }, '60sVXiTH1D/6Aft4MRt9VC'], (err, assets) => cc.log(assets));
而且你的示例中，也有

url: 'a.jpg'

这样的示例

2019-05-15 12:38 UTC, pandamicro commented on cocos2d/core/asset-manager/CCAssetManager.js
> +     * cc.assetManager.load(['image/a', 'image/b'], {key: 'path', type: cc.SpriteFrame}, null, (err, assets) => cc.log(assets));
我感觉每个资源都指定没问题啊，否则这个接口太宽容了，学习成本比较高

2019-05-15 12:40 UTC, pandamicro commented on cocos2d/core/asset-manager/CCAssetManager.js
> +    createByUrl: function (url, ctor, options, onProgress, onComplete) {
createByUrl 这个规则太隐晦了，不是一个好的设计

2019-05-15 12:41 UTC, pandamicro commented on cocos2d/core/asset-manager/CCAssetManager.js
> +     * @param {String[]} completeCallback.urls - An array that lists all the URLs of loaded assets.
现在问题是排序会乱掉，除非你在最后做一次根据传入顺序的排序，这样做其实也可以

2019-05-15 12:47 UTC, pandamicro commented on cocos2d/core/asset-manager/caches.js
> +    assets: new Cache(),
还是建议将 Cache 类定义独立在一个文件中，上层负责创建 caches，集中化管理也可以

2019-06-06 05:39 UTC, holycanvas commented on cocos2d/core/asset-manager/CCAssetManager.js
> +    createByUrl: function (url, ctor, options, onProgress, onComplete) {
根据老的loader来看，这个需要主要是用在加载远程图片或者远程音频时用，比如微信头像。那我直接提供两个api，loadRemoteTexture，和loadRemoteAudio，就删除这个接口了，这样用户理解起来也简单吧？

2019-06-06 06:11 UTC, holycanvas commented on cocos2d/core/asset-manager/CCAssetManager.js
> +     * cc.assetManager.load([{ path: 'images/a', type: cc.SpriteFrame }, '60sVXiTH1D/6Aft4MRt9VC'], (err, assets) => cc.log(assets));
我觉得path和url还是必须得区分清楚的，工程目录中的路径是用户看到的路径，跟打包之后的真实url完全无关，用户是看不到资源的url的，如果把路径叫做relativeUrl，用户会和url搞混，因为名称太相近了，其次dir和path正好是一对，表明了工程目录中的单个资源和文件夹的关系，但是relativeUrl和dir就完全不搭了。而且，用户基本不会在load中使用path的，因为有loadRes和loadResDir给用户使用，load更偏内部使用一点

2019-06-06 06:22 UTC, holycanvas commented on cocos2d/core/asset-manager/CCAssetManager.js
> +     * cc.assetManager.load(['image/a', 'image/b'], {key: 'path', type: cc.SpriteFrame}, null, (err, assets) => cc.log(assets));
我的建议是，key就不开放出去，让用户就每个资源都指定，key在内部使用，在内部使用key会方便很多，比如

`
loadRes: function (path, type, onProgress, onComplete) {
        this.load(path, {key: 'path', type: type, mount: 'assets'}, onProgress, onComplete);
}
`
指定了key就行了，不然我还需要挨个遍历，构建对象，设置

2019-06-18 12:40 UTC, jareguo commented
@holycanvas 代码有点多，看不来了…… 麻烦看下上面的会话，将已经解决的标记为 resolve 吧
![image](https://user-images.githubusercontent.com/1503156/59682698-50d4e000-9209-11e9-8a8c-4bb16ccca896.png)

2019-06-18 13:11 UTC, holycanvas commented
简述一下bundle的实现原理，就如 @jareguo 所说，实际上能够把配置信息分块，在加载时能在不同的配置信息块上加载资源就可以理解为bundle，所以改动是把config从静态全局变量，改为了一个类，每一个bundle中都有一个config类的实例，这个config实例由bundle所在目录下的settings.json来初始化的, 同时利用assetManager中自定义参数的特性，在加载时将config作为自定义参数传入管线中，管线使用传入的config来拼接url，这样即可实现bundle.loadAsset。整个游戏默认起始时必须有一个bundle，这个bundle存的是resources中的资源，loadRes实际上是从这个bundle下载，其他的bundle可以动态使用c c.assetManager.loadBundle从远程服务器上下载(实际上是去下载对应目录下的settings.json来初始化config)。

2019-06-18 13:20 UTC, holycanvas commented
另外，bundle间的资源复用，因为使用uuid做key来缓存加载过程中的所有中间产物，只要提前加载bundle中的某个资源，其他bundle中依赖这个资源的资源也能正常的复用

2019-07-12 09:29 UTC, pandamicro approved these changes

2019-07-12 13:52 UTC, jareguo commented on cocos2d/core/asset-manager/deprecated.js
> +    }
这两个 API 的移除我还是比较担心的，director 承担的应该是场景的调度职责，特别是将来我们可能加回 push/pop Scene，或者引入 3D 的多场景管理机制，那么到时候显然这两个接口不能继续寄生在 assetManager 上了。因此感觉保留在 Director 中会比较好一点。
@pandamicro

2019-07-12 14:20 UTC, jareguo commented on cocos2d/core/asset-manager/deprecated.js
> +        cc.warn('url is not supported any more, you should use nativeUrl instead');
cc.url is ..., you should -> please

2019-07-12 14:20 UTC, jareguo commented on cocos2d/core/asset-manager/deprecated.js
> +        cc.warn('url is deprecated now, you should use nativeUrl instead');
cc.Asset.url

2019-07-12 14:20 UTC, jareguo commented on cocos2d/core/asset-manager/deprecated.js
> +        cc.warn('cc.AssetLibrary is not supported any more, you should backup your project and upgrade to new API cc.assetManager');
new API cc.assetManager -> cc.assetManager

2019-07-12 14:20 UTC, jareguo commented on cocos2d/core/asset-manager/deprecated.js
> +        cc.warn('cc.url.raw is not supported any more');
cc.url.raw is not supported any more, please use cc.assetManager.load(xxx) directly, or use Asset.nativeUrl instead.

2019-07-12 14:20 UTC, jareguo commented on cocos2d/core/asset-manager/deprecated.js
> +        cc.warn('cc.AssetLibrary.getLibUrlNoExt is not supported any more, if you want to transform url, you can see around cc.assetManager.helper.getUrlWithUuid');
对这种未能 polyfill 的，统一改用 cc.error 吧，毕竟行为肯定会出错了

2019-07-12 14:20 UTC, jareguo commented on cocos2d/core/asset-manager/deprecated.js
> +        cc.warn('getXMLHttpRequest is deprecated now, please use use XMLHttpRequest directly');
多了一个 use

2019-07-12 14:20 UTC, jareguo commented on cocos2d/core/asset-manager/helper.js
> +module.exports = helper;
这个模块叫做 utlls 可以吗？一方面是符合我们的命名习惯，另一方面是比较短…… assetManager 的 API 都已经挺长的了

2019-07-12 14:20 UTC, jareguo commented on cocos2d/core/asset-manager/index.js
> + Copyright (c) 2017-2019 Xiamen Yaji Software Co., Ltd.
新建的脚本文件，年份应该是 2019 就好

2019-07-12 14:20 UTC, jareguo commented on cocos2d/core/assets/CCAsset.js
> +            function parseDependRecursively (data, out) {
这个函数可以放到外面吗？以 js 的尿性，常用函数放在里面性能不如外面

2019-07-12 14:20 UTC, jareguo commented on package.json
> +    "gulp-cli": "^2.0.1"
这个应该去掉吧？因为 gulp-cli 是得全局安装的，不是安装在本地的

2019-07-12 14:24 UTC, jareguo commented on cocos2d/core/asset-manager/deprecated.js
> +        cc.warn('cc.loader.getResCount is not supported anymore , if you want some special effect, you can see around cc.assetManager._assets');
you can see around cc.assetManager._assets -> please use cc.assetManager._assets.count instead

2019-07-12 14:40 UTC, jareguo commented on cocos2d/core/asset-manager/bundle.js
> +     * @param {RequestItem} onProgress.item - The current request item
item 现在还有支持吗？没有就去掉吧

2019-07-12 15:50 UTC, holycanvas commented on cocos2d/core/asset-manager/deprecated.js
> +    }
这里我的考虑是这样的，1.细分起来，cc.director应该做的是runScene，而不是loadScene。用户完全可以先load 5-6个scene放着不运行，但是现在的结构是做不到的。2. bundle中是可以放scene的，现在的系统是基于bundle的，如果把loadScene放在director里面，那我每加载一个bundle，就要把bundle包含的scene列表添加到director里面，每释放一个scene，就要去director移除自己的scene。除了代码丑之外，对用户感知来说是很费解的。
比如用户

cc.director.loadScene('test');    // 失败，scene在其他bundle内                         

var bundle = await cc.assetManager.loadBundle('myBundle');
cc.director.loadScene('test');       // 加载成功                    

bundle.destroy();               // 移除bundle                              

cc.director.loadScene('test');        // 失败

这种做法是很不面向对象的，作为用户，如果不清楚内部机制的话，完全不知道bundle和scene之间的关系，为什么突然就行了，突然就不行了

2019-07-12 15:52 UTC, holycanvas commented on cocos2d/core/asset-manager/deprecated.js
> +        cc.warn('url is deprecated now, you should use nativeUrl instead');
现在的架构中nativeUrl已经没有用了，所以把当前版本的url移到了nativeUrl上

2019-07-12 15:53 UTC, holycanvas commented on cocos2d/core/asset-manager/helper.js
> +module.exports = helper;
已经有了一个utils, 是我们内部的帮助方法，而这个helper是开发给用户用的，用来解压一下uuid呀，

2019-07-12 15:55 UTC, holycanvas commented on cocos2d/core/asset-manager/deprecated.js
> +        cc.warn('cc.loader.getResCount is not supported anymore , if you want some special effect, you can see around cc.assetManager._assets');
关键是assets是私有的，我直接建议用户去用私有的东西感觉不太好，只能说让他自己去看看，自己确定要不要用

2019-07-12 15:58 UTC, holycanvas commented on cocos2d/core/asset-manager/bundle.js
> +     * @param {RequestItem} onProgress.item - The current request item
有支持，现在加载是用的RequestItem对象，每次onProgress的时候回调回来，这个item还可以注册onerror和onload方法，

2019-07-12 16:00 UTC, holycanvas commented
实际上代码量比以前少，注释比以前多太多了，我把每一个public的方法都加了中英文注释，example，以及typescript的调用方法，注释比以前多了上千行

2019-07-12 16:16 UTC, jareguo commented
> 实际上代码量比以前少，注释比以前多太多了，我把每一个public的方法都加了中英文注释，example，以及typescript的调用方法，注释比以前多了上千行

这个得好好膜拜了

2019-07-18 10:58 UTC, jareguo commented on cocos2d/core/asset-manager/deprecated.js
> +    }
我也认可你说的，这种类似 Unity 按名字索引场景而非资源的方案比较蛋疼。不过我也觉得有其合理性。

假设不按名字加载

1、从 bundle 中加载
```
var bundle = await cc.assetManager.loadBundle('url/to/myBundle');
bundle.mainAsset.runScene();  // mainAsset 是 scene
```
2、或者直接从 assetManager 加载
```
var scene = await cc.assetManager.loadScene('url/to/scene');
cc.director.runScene(scene);
```

不论哪种方法，存在的最大问题是，开发者切换场景时需要关心场景在哪个地方，需要关心到资源本身。这样就会导致场景之间存在资源上的耦合。

例子：我写了个组件，用来配置要跳转到哪个场景，原先只要在属性检查器里面填写场景名就好。现在变成要关心这个场景是否是在 bundle 里？如果是的话，bundle 是远程的 url 还是本地项目里的？

因此，统一使用名字切换场景。我觉得是有必要的。毕竟通常来说，加载场景的模块，跟最终要跳转的模块通常不是同一个模块。他们两者之间的耦合是没有必要的。

总之，这种不面向对象的做法，恰恰是为了让用户可以不要关心对象。

2019-07-18 11:31 UTC, holycanvas commented on cocos2d/core/asset-manager/deprecated.js
> +    }
现在也是按名字来加载啊，这点和以前一样的，现在的用法是
```
let bundle1 = await cc.assetManager.loadBundle('bundle1');
bundle1.loadScene('test');
```
我们主要讨论的点在于是在cc.director里面来loadScene，还是在bundle里来loadScene。



> 不论哪种方法，存在的最大问题是，开发者切换场景时需要关心场景在哪个地方，需要关心到资源本身。这样就会导致场景之间存在资源上的耦合。
> 
> 例子：我写了个组件，用来配置要跳转到哪个场景，原先只要在属性检查器里面填写场景名就好。现在变成要关心这个场景是否是在 bundle 里？如果是的话，bundle 是远程的 url 还是本地项目里的？

我的观点是，一旦我们引入了bundle，我们是没有办法做到让用户不关心资源本身的。因为bundle的加载完全是让用户来控制的，即使还是按照以前的做法还是用cc.director.loadScene，那用户使用的时候依然需要先加载有这个场景的bundle，再去加载场景，**所以用户还是得清楚场景在哪一个bundle里面**
```
await cc.assetManager.loadBundle('bundle1');  // 先加载bundle
cc.director.loadScene('test');
```
我们无法做到用户不关注资源本身，所以既然无法做到，那我就干脆全部面向对象，至少能让流程清晰，逻辑清楚，让用户清楚地知道scene是从哪个bundle出来的。

退一万步讲，就算我们还是用cc.director.loadScene来加载场景，那我们bundle内的普通资源呢，
我们还是得
```
let bundle1 = await cc.assetManager.loadBundle('bundle1');
bundle1.loadAsset('image/a', cc.Texture, () => {});
```
所以但凡引入了bundle，开发者就需要对自己的bundle规划清楚，这是基本条件。所以反正都要用户了解，那还不如把scene和其他资源统一起来，都用bundle来加载，scene的数量相对来说还少得多。

如果决定还是要用cc.director.loadScene来加载的话，那我觉得还有一个折中的方案是。bundle里面的loadScene，只load，不runScene，而cc.director.loadScene用以下方式实现
```
cc.director.loadScene = function  (name) {
        cc.assetManager.bundles.find(bundle => {
             const sceneInfo = bundle.getSceneInfo(name);
             if (sceneInfo)  {
                     var scene = await bundle.loadScene(name);
                     this.runScene(scene);
             }
       });
}

```
这样，留下Bundle.loadScene给高级开发者能够控制bundle内的场景加载，而萌新就用cc.director.loadScene来方便开发

2019-07-18 11:52 UTC, jareguo commented on cocos2d/core/asset-manager/deprecated.js
> +    }
> 细分起来，cc.director应该做的是runScene，而不是loadScene。用户完全可以先load 5-6个scene放着不运行，但是现在的结构是做不到的。

是可以允许 cc.director.runScene(scene); 
然后 assetManager 只负责场景加载，不负责场景切换

```
var scene = await cc.assetManager....;
cc.director.runScene(scene);
```

2019-07-18 11:52 UTC, jareguo commented on cocos2d/core/asset-manager/deprecated.js
> +    }
这样一来，AssetManager 和 director 保持现有的分工不变。API 也比较有延续性，将来要扩展场景管理的话也不影响到现有的 AssetManager。

2019-07-18 11:55 UTC, jareguo commented on cocos2d/core/asset-manager/deprecated.js
> +        cc.warn('url is deprecated now, you should use nativeUrl instead');
嗯，我的意思是，警告信息完整点，不然有时候单单看到一个 url 不能用，不一定会清楚是哪个（其实是所有 asset 的都不能用）

2019-07-18 11:57 UTC, jareguo commented on cocos2d/core/asset-manager/helper.js
> +module.exports = helper;
没问题的，我们内部的 utils 又没暴露出去，namespace 不同

2019-07-18 11:57 UTC, holycanvas commented on cocos2d/core/asset-manager/deprecated.js
> +    }
最后决定调整成什么形式？没看到有结论呀

2019-07-18 11:59 UTC, jareguo commented on cocos2d/core/asset-manager/deprecated.js
> +        cc.warn('cc.loader.getResCount is not supported anymore , if you want some special effect, you can see around cc.assetManager._assets');
嗯…… 明白。那其实可以告诉用户能暂时用 cc.assetManager._assets.count, but it could be removed in the future 之类的

2019-07-18 12:00 UTC, holycanvas commented on cocos2d/core/asset-manager/deprecated.js
> +        cc.warn('url is deprecated now, you should use nativeUrl instead');
我知道的，我已经完善了，我只是解释下为什么2.1.2才加url，现在又移除了

2019-07-18 12:08 UTC, jareguo commented on cocos2d/core/asset-manager/deprecated.js
> +        cc.warn('cc.macro.DOWNLOAD_MAX_CONCURRENT is deprecated now, please use cc.assetManager.downloader.limitations instead');
这个警告放到 set 吧，因为这个参数是 set 用的比较多，get 用的少

2019-07-18 12:08 UTC, jareguo commented on cocos2d/core/asset-manager/deprecated.js
> +        cc.error('cc.loader.setAutoRelease is not supported any more due to security issue, if you want to lock some asset, please use cc.assetManager.finalizer.lock instead');
setAutoRelease 相关 API 还是比较常用的。这里不能提供下 polyfill，先帮用户 lock 和 unlock 吗？

2019-07-18 12:08 UTC, jareguo commented on cocos2d/core/asset-manager/deprecated.js
> +        cc.error('cc.loader.md5Pipe is not supported anymore, assetLoader and md5Pipe were merged into cc.assetManager._transformPipeline');
这个 API 超级常用的…… polyfill 一下吧？让用户能继续转 md5

2019-07-18 12:08 UTC, jareguo commented on cocos2d/core/asset-manager/deprecated.js
> +        cc.error('cc.loader.onProgress is not supported anymore, please transfer onProgress to API as a parameter');
这也是一个很常用的 API，能 polyfill 一下吗？或者在 log 里更清楚地给出示例代码

2019-07-18 12:21 UTC, holycanvas commented on cocos2d/core/asset-manager/deprecated.js
> +        cc.error('cc.loader.md5Pipe is not supported anymore, assetLoader and md5Pipe were merged into cc.assetManager._transformPipeline');
这里倒是可以强行polyfill出来

2019-07-18 12:28 UTC, holycanvas commented on cocos2d/core/asset-manager/deprecated.js
> +        cc.error('cc.loader.setAutoRelease is not supported any more due to security issue, if you want to lock some asset, please use cc.assetManager.finalizer.lock instead');
lock和autoRelease功能不一样，autoRelease的作用其实是为了绕开以前释放资源容易释放错误的问题，但是autoRelease实际是很不安全的，每次切换场景都去自动释放一次，很容易释放错误，所以既然现在我们已经提供了静态的引用计数给用户用，用户不需要autoRelease了，而且autoRelease还不安全。基于这个考虑，我把这个模块移除了。
也可以polyfill让用户再用段时间。这系列api用的人真新不多，我在移除某个模块的时候，我都会先询问铮雄他们这个API在论坛的反馈数，他们接收到的问题数。铮雄说的是从来没收到过这个api的反馈，我这边这么久也只有一个人反馈过，所以我才考虑的移除。

2019-07-18 12:31 UTC, holycanvas commented on cocos2d/core/asset-manager/deprecated.js
> +        cc.error('cc.loader.onProgress is not supported anymore, please transfer onProgress to API as a parameter');
这里我真没想到好的polyfill方法，难道和以前一样，把所有的onProgress都带个默认值

2019-07-18 12:31 UTC, holycanvas commented on cocos2d/core/asset-manager/deprecated.js
> +        cc.error('cc.loader.onProgress is not supported anymore, please transfer onProgress to API as a parameter');
这样代码真的很丑

2019-07-19 06:39 UTC, jareguo commented on cocos2d/core/asset-manager/deprecated.js
> +        cc.error('cc.loader.onProgress is not supported anymore, please transfer onProgress to API as a parameter');
还好吧…… 所有 onProgress，如果用户未指定，你就指定成 cc.loader.onProgress 不就行了，好像也没几行代码

2019-07-19 06:42 UTC, jareguo commented on cocos2d/core/asset-manager/deprecated.js
> +        cc.error('cc.loader.setAutoRelease is not supported any more due to security issue, if you want to lock some asset, please use cc.assetManager.finalizer.lock instead');
论坛里讨论到的地方还挺多的：
https://forum.cocos.com/search?q=setAutoRelease%20category%3A27
虽然现在用户不需要了。但是对老的项目来说，调用这个 API 的目的不就是 lock 和 unlock 吗？我们底层实现原理变了没关系，只要确保结果是一样的就行。用户也不会 care 底层是什么情况。

2019-07-19 06:51 UTC, holycanvas commented on cocos2d/core/asset-manager/deprecated.js
> +        cc.error('cc.loader.setAutoRelease is not supported any more due to security issue, if you want to lock some asset, please use cc.assetManager.finalizer.lock instead');
setAutoRelease之后，会需要在场景切换的时候自动释放这个资源，lock是任何时候都不允许释放这个资源，unlock也仅仅只是解锁。从功能上来说，还是不同的，polyfill到lock上肯定是不行的，得重新实现一个方法

2019-07-23 01:52 UTC, pandamicro commented
昨天讨论了一下这个 PR，我们要保障下面几点

1. 公开 API 不产生任何行为变化
2. test case 和 unit test 不修改的情况下可以通过
3. 不对旧 loader API 做 warning，仅做适配
4. 整理出构建过程中和旧版本不兼容的具体问题有哪些，用户该如何修改插件（针对导出过程定制的插件）

@holycanvas

2019-07-23 02:26 UTC, holycanvas commented
2. 内部模块的测试不修改的话，够呛，比如像pack-downloader，这些都没了
3.不做warning的话，能引导用户做迁移么？

2019-07-26 13:01 UTC, jareguo commented on cocos2d/core/asset-manager/deprecated.js
> +        cc.error('cc.loader.setAutoRelease is not supported any more due to security issue, if you want to lock some asset, please use cc.assetManager.finalizer.lock instead');
setAutoRelease 如果传 true，就是相当于 unlock，如果传 false，就是相当于 lock。好像就可以了啊？

2019-07-26 15:08 UTC, holycanvas commented
我们的ci是什么环境呀，连Audio类都没有，判断instanceof Audio居然报没有Audio的错，晕了

2019-07-26 15:13 UTC, holycanvas commented
貌似xhr也是特别老的版本，新的用法根本不支持

2019-07-26 15:14 UTC, holycanvas commented
在网页上，老版本的单元测试已经跑通了，ci的环境太诡异了

2019-07-29 03:10 UTC, holycanvas commented
感人，老版本单元测试终于跑通了，考虑增加新功能的单元测试

2019-08-03 08:23 UTC, jareguo approved these changes

2019-08-03 08:32 UTC, jareguo approved these changes
我没其他问题了，很出色的一次重构！

2019-08-15 02:28 UTC, merged