texture cube serialization
cocos/cocos-engine pull request #3628
Opened 2018-12-13 06:10 UTC by shrinktofit

2018-12-13 06:13 UTC, YunHsiao requested changes

2018-12-13 06:13 UTC, YunHsiao commented on cocos/3d/assets/texture-cube.js
> -    static fromTexture2DArray(textures) {
这个不要删, 可以作为直接读取6张texture2D的入口

2018-12-14 02:41 UTC, YunHsiao commented
改动合进 https://github.com/cocos-creator/engine/pull/3627 里了, 这个PR可以关了
这样方便一些, sorry~

2018-12-14 06:19 UTC, pandamicro commented
Merged in #3627

2018-12-14 06:19 UTC, closed without merging