Fixed the rotation problem
cocos/cocos-engine pull request #3632
Opened 2018-12-14 06:18 UTC by ColinCollins

issue: https://github.com/cocos-creator/engine/issues/3579
1. remove all surplus space.
2. add the rotation calculation for the particle.
effect as a single node:
![gif](https://user-images.githubusercontent.com/35832931/49986446-f71a0180-ffaa-11e8-9297-8be27c0e4924.gif)
effect as the child node:
![gif2](https://user-images.githubusercontent.com/35832931/49986490-1add4780-ffab-11e8-8533-cd4ad6151a5f.gif)

2018-12-16 10:54 UTC, ColinCollins commented
这个部分仍然有问题，实际正确做法应该讲 Particle 的 position 和 rotation 完全分离，newPos 只负责 位置变化而不考虑旋转，现在错误点在于 newPos 影响到了 rotation 的变化。
![image](https://user-images.githubusercontent.com/35832931/50052751-df39ad80-0163-11e9-9e28-b4d9e74e6d50.png)
现在只能同步的调整 rotation。

现在还有一个错误的地方在于 position 的位移没有到位，确实是相对的变化，但是位移的实际长度与理论长度不相符。

2018-12-17 03:19 UTC, pandamicro requested changes

2018-12-17 03:19 UTC, pandamicro commented on cocos2d/particle/particle-simulator.js
> +    this.startEmitTrans = {tx: 0, ty: 0, cos: 0, sin: 0};
就不能好好创建一个 AffineTransform 对象吗？

2018-12-17 03:19 UTC, pandamicro commented on cocos2d/core/CCNode.js
> +
不要改不相干的文件

2018-12-17 03:19 UTC, pandamicro commented on cocos2d/particle/particle-simulator.js
> +// 粒子发射函数，设置粒子拥有的所有参数
代码中不要写中文注释

2019-01-07 01:54 UTC, closed without merging