fix button scale setting in Scale Mode
cocos/cocos-engine pull request #3636
Opened 2018-12-14 11:49 UTC by umbrellaPP

Re: https://github.com/cocos-creator/2d-tasks/issues/868

changeLog:
- 修复 button scale 模式下，scaleX 和 scaleY 不统一引起的问题

2018-12-17 03:46 UTC, knoxHuang approved these changes

2018-12-17 03:58 UTC, pandamicro requested changes

2018-12-17 03:58 UTC, pandamicro commented on cocos2d/core/components/CCButton.js
> +        this._originalScale = {};
不要使用无类型的对象，使用 vec2

2018-12-17 03:58 UTC, pandamicro commented on cocos2d/core/components/CCButton.js
> +         * 不建议 zoomScale 的值小于 1, 否则容易触发按钮 touchCancel 事件。
问题描述不清晰，是在按钮边缘特定区域点击释放开时不会触发点击事件

2018-12-17 03:58 UTC, pandamicro commented on cocos2d/core/components/CCButton.js
> +            this._setScale(target, this._originalScale);
_setScale 函数实现性能低下，应该直接进行 scaleX，scaleY 分量设置

2018-12-17 03:58 UTC, pandamicro commented on cocos2d/core/components/CCButton.js
> +            target.scaleY = misc.lerp(this._fromScale.y, this._toScale.y, ratio);
应该用 Vec2 的 lerp 函数

2018-12-17 03:58 UTC, pandamicro commented on cocos2d/core/components/CCButton.js
> +            this._setScale(this._originalScale, this.target);
直接设置分量

2018-12-17 03:58 UTC, pandamicro commented on cocos2d/core/components/CCButton.js
> +        }
这个函数实现直接去掉吧

2018-12-18 06:45 UTC, pandamicro approved these changes

2018-12-18 06:45 UTC, merged