fixed the findCamera problem
cocos/cocos-engine pull request #3642
Opened 2018-12-17 10:26 UTC by ColinCollins

issue: https://github.com/cocos-creator/2d-tasks/issues/878

fixed the findCamera can't get the correct Camera target when node prop still not init.
1. 首先保证了父节点的 cullingMask 会优先于 default group 状态下的子节点 cullingMask.
2. 不去修改 Node 是为了保证只有调用到这个 API 时才会进行遍历父节点。

2018-12-17 10:42 UTC, 2youyou2 commented on cocos2d/core/camera/CCCamera.js
> +            groupIndex = this._getGroupIndex(node.parent);
这样就是 node.hitTest 里性能消耗比较大，@pandamicro 有其他建议吗

2018-12-17 10:55 UTC, ColinCollins commented
二改，增加了 cullingMask 判断避免非 default 的多次遍历。
但若是 default 仍然会有性能问题。

2018-12-18 02:57 UTC, pandamicro commented on cocos2d/core/camera/CCCamera.js
> +            groupIndex = this._getGroupIndex(node.parent);
group 设置如果是一个非常低频的操作，建议直接在 group setter 中刷新子节点树

2018-12-18 03:30 UTC, 2youyou2 commented on cocos2d/core/camera/CCCamera.js
> +            groupIndex = this._getGroupIndex(node.parent);
如果在 group setter 中刷新子节点树，那 render flow 里就可以去掉 culling mask 的计算了

2018-12-18 03:49 UTC, pandamicro commented on cocos2d/core/camera/CCCamera.js
> +            groupIndex = this._getGroupIndex(node.parent);
可以啊，RenderFlow 的调用频率比 group setter, parent setter 高太多了

2018-12-18 09:05 UTC, ColinCollins commented
1. 在 _onBatchCreatred 进行序列化后的及时更新，之后用户在修改 group 的时候回同步的检测到 groupIndex.
2. 去除了 render-flow 中对 cullingMask 的遍历同步。

2018-12-18 09:09 UTC, 2youyou2 commented on cocos2d/core/CCNode.js
> +                this.groupIndex = this._getParentCullingMask(this);
这个获取的包括父节点的信息，不要修改到当前节点。。

2018-12-18 09:09 UTC, 2youyou2 commented on cocos2d/core/CCNode.js
> +    _getParentCullingMask (node) {
这个函数获取的是 groupIndex，不是 cullingmask

2018-12-18 09:11 UTC, ColinCollins commented on cocos2d/core/CCNode.js
> +    _getParentCullingMask (node) {
有道理，石乐志

2018-12-18 09:34 UTC, pandamicro requested changes

2018-12-18 09:34 UTC, pandamicro commented on cocos2d/core/CCNode.js
> +        this._cullingMask = 1 << this._getParentGroupIndex(this);;
onBatchRestored 里面也需要做同样的逻辑

2018-12-18 09:34 UTC, pandamicro commented on cocos2d/core/CCNode.js
> +    _getParentGroupIndex (node) {
_getActualGroupIndex

2018-12-18 09:47 UTC, pandamicro approved these changes

2018-12-18 09:47 UTC, merged

2018-12-19 06:07 UTC, jareguo commented on cocos2d/core/CCNode.js
> +            groupIndex = this._getActualGroupIndex(node.parent);
干嘛要传入参数啊，直接用 this 不就完事了吗？你都不用 this 的话，这个函数就改成局部函数呗