phy framework
cocos/cocos-engine pull request #3644
Opened 2018-12-18 02:08 UTC by shrinktofit

2018-12-18 03:56 UTC, YunHsiao commented on cocos/3d/assets/utils/gltf-utils.js
> -// @ts-check
这个不要了?

2018-12-18 03:58 UTC, YunHsiao commented
没有看到和场景树数据同步那部份代码?

2018-12-18 05:42 UTC, shrinktofit commented on cocos/3d/assets/utils/gltf-utils.js
> -// @ts-check
不要了，这个现在放到editor里了

2018-12-19 07:15 UTC, YunHsiao requested changes

2018-12-19 07:15 UTC, YunHsiao commented on cocos/3d/framework/physics/body.ts
> +        this._node.getWorldRotation(this._cannonBody.quaternion);
push 和 pull 的注释写反了, 用词上也注意下, 没有 entity 了
另外现在的 pull 和 push 的意义也和原来反过来了, 这个可以考虑一下: 
这两个动作是 body 发起的, 对于 body 来说, "推" 应当是把数据推到场景里, "拉" 应当是把数据拉到物理世界来

2018-12-19 07:15 UTC, YunHsiao commented on cocos/3d/framework/physics/body.ts
> +        console.log(`Collided: ${event.contact}`);
这的 collide 回调设计的是怎么让用户使用? 还有默认就别打 log 了

2018-12-19 07:15 UTC, YunHsiao commented on cocos/3d/framework/physics/body.ts
> +    public setworldPosition(position: Vec3) {
setWorldPosition

2018-12-19 07:15 UTC, YunHsiao commented on cocos/3d/framework/physics/body.ts
> +        this._cannonBody.updateMassProperties();
mass 控制着这个物体的类型, 这里需要根据数据更新 body 类型

2018-12-19 07:15 UTC, YunHsiao commented
缺失的接口:
useGravity, isKinematic, freezeRotation

2018-12-19 07:23 UTC, YunHsiao commented on cocos/3d/framework/physics/body.ts
> +        this._getCannonShape<CANNON.Box>().halfExtents = new CANNON.Vec3(value.x / 2, value.y / 2, value.z / 2);
这里这么赋值是完全不够的, 参考原实现, 一个是需要考虑节点 scale, 一个是设置完 halfExtents CANNON 里还需要更新 ConvexPolyhedron 和 BoundingSphere

2018-12-19 07:23 UTC, YunHsiao commented on cocos/3d/framework/physics/body.ts
> +
没有看到 _cannonShape 被赋给成员变量?

2018-12-19 07:23 UTC, YunHsiao commented on cocos/3d/framework/physics/body.ts
> +        this._getCannonShape<CANNON.Sphere>().radius = value;
同上

2018-12-19 07:39 UTC, YunHsiao commented on cocos/3d/framework/physics/body.ts
> +        this._node.setWorldRotation(q.x, q.y, q.z, q.w);
节点的 scale 也会影响 shape 的大小

2018-12-20 01:58 UTC, 2youyou2 commented on rollup/config.js
> +                //'./rollup/babel-plugin-mix-ts-js',
不开启吗？

2018-12-20 15:17 UTC, 2youyou2 commented
Re: https://github.com/cocos-creator/3d-tasks/issues/216

2018-12-21 05:02 UTC, shrinktofit commented on rollup/config.js
> +                //'./rollup/babel-plugin-mix-ts-js',
不开启，但是这里给了一个思路，我们可以自己写babel插件

2018-12-21 05:04 UTC, shrinktofit commented on cocos/3d/framework/physics/body.ts
> +
这是Typescript语法

2018-12-21 05:48 UTC, shrinktofit commented on cocos/3d/framework/physics/body.ts
> +        this._node.setWorldRotation(q.x, q.y, q.z, q.w);
已修改。

2018-12-21 05:48 UTC, shrinktofit commented on cocos/3d/framework/physics/body.ts
> +        this._getCannonShape<CANNON.Sphere>().radius = value;
已修改。

2018-12-21 05:48 UTC, shrinktofit commented on cocos/3d/framework/physics/body.ts
> +        this._getCannonShape<CANNON.Box>().halfExtents = new CANNON.Vec3(value.x / 2, value.y / 2, value.z / 2);
已修改。

2018-12-21 05:49 UTC, shrinktofit commented on cocos/3d/framework/physics/body.ts
> +    public setworldPosition(position: Vec3) {
已修改。

2018-12-21 05:49 UTC, shrinktofit commented on cocos/3d/framework/physics/body.ts
> +        this._node.getWorldRotation(this._cannonBody.quaternion);
已修改。

2018-12-21 06:03 UTC, shrinktofit commented on cocos/3d/framework/physics/body.ts
> +        this._cannonBody.updateMassProperties();
已修改。

2018-12-21 07:42 UTC, shrinktofit commented
> body 缺失的接口:
> useGravity, isKinematic, freezeRotation
> 以及 world 下所有的 raycast

这些已经移植

2018-12-24 01:54 UTC, YunHsiao requested changes

2018-12-24 01:54 UTC, YunHsiao commented on cocos/3d/framework/physics/body.ts
> +        }
cancel gravity 只能在整个 step 函数之前, 放在这是不行的

2018-12-24 02:03 UTC, YunHsiao commented on cocos/3d/framework/physics/body.ts
> +        const newHalfExtents = new CANNON.Vec3();
不要在 update 里创建临时变量, 这个函数可能是每帧执行的, 要尽量减小代价

2018-12-24 02:05 UTC, YunHsiao commented on cocos/3d/framework/physics/body.ts
> +        vec3.multiply(newHalfExtents, this._size, this.scale);
scale 是跟着 node 来的, shape 本身没有 scale

2018-12-24 02:11 UTC, YunHsiao commented on cocos/3d/framework/physics/collider-component.ts
> +    // @property(Number)
这不是需要改成 property({
  type: Number
}) 么

2018-12-24 02:16 UTC, YunHsiao commented on cocos/3d/framework/physics/body.ts
> +        shape.updateConvexPolyhedronRepresentation();
这里还得转调 body 的 updateBoundingRadius, 另外又看了下源码, 原来写得多了点, 其实 shape.updateBoundingSphereRadius 可以不调, 在 body 这个函数里有做

2018-12-24 02:16 UTC, YunHsiao commented on cocos/3d/framework/physics/body.ts
> +        shape.updateBoundingSphereRadius();
同 box

2018-12-24 02:28 UTC, YunHsiao commented on cocos/3d/framework/physics/world.ts
> +            result._update();
result 就别 update 了

2018-12-24 02:34 UTC, YunHsiao commented on cocos/3d/framework/physics/world.ts
> +        collisionFilterGroup: options.collisionFilterGroup === undefined ? -1 : options.collisionFilterGroup,
mask 和 group 在 cannon 里都有做判断, 这里就不用了

2018-12-26 05:47 UTC, shrinktofit commented on cocos/3d/framework/physics/body.ts
> +        vec3.multiply(newHalfExtents, this._size, this.scale);
shape是没有scale，这里scale只是Body传来的node的scale。

2018-12-26 05:48 UTC, shrinktofit commented on cocos/3d/framework/physics/body.ts
> +        shape.updateConvexPolyhedronRepresentation();
转调 body 的 updateBoundingRadius 在别的地方做了

2018-12-26 05:49 UTC, shrinktofit commented on cocos/3d/framework/physics/world.ts
> +        collisionFilterGroup: options.collisionFilterGroup === undefined ? -1 : options.collisionFilterGroup,
这里已经换了实现

2018-12-26 08:22 UTC, shrinktofit commented on cocos/3d/framework/physics/world.ts
> +            result._update();
去除了

2018-12-26 08:22 UTC, shrinktofit commented on cocos/3d/framework/physics/body.ts
> +        shape.updateBoundingSphereRadius();
注释掉了

2018-12-26 08:23 UTC, shrinktofit commented on cocos/3d/framework/physics/collider-component.ts
> +    // @property(Number)
测试过 这样写编辑器可以正常显示

2018-12-26 08:23 UTC, shrinktofit commented on cocos/3d/framework/physics/body.ts
> +        const newHalfExtents = new CANNON.Vec3();
已经修改

2018-12-26 08:23 UTC, shrinktofit commented on cocos/3d/framework/physics/body.ts
> +        }
放在beforeStep了

2018-12-26 08:45 UTC, YunHsiao requested changes

2018-12-26 08:45 UTC, YunHsiao commented on cocos/3d/framework/physics/body.ts
> +    set angularDamping(value) {
这几个接口 unity 里就叫 **Drag, 接口上还是尽量去 cannon 化

2018-12-26 08:45 UTC, YunHsiao commented on cocos/3d/framework/physics/body.ts
> +        this._cannonBody.world.addEventListener('beforeStep', this._onWorldBeforeStepListener);
beforeStep 是我加的事件, 需要在 step 前 emit, cannon 里虽然有 preStep 但 cancelGravity 用不了

2018-12-26 08:45 UTC, YunHsiao commented on cocos/3d/framework/physics/body.ts
> +            this._pull();
拉数据应该在 beforeStep, 并且有一个重要优化没加进来, 如果节点的 tranform 在这一帧没变(node.hasChanged = false), 可以直接 return.

2018-12-26 08:45 UTC, YunHsiao commented on cocos/3d/framework/physics/world.ts
> +        });
推数据应该在 postStep

2018-12-26 09:50 UTC, shrinktofit commented on cocos/3d/framework/physics/world.ts
> +        });
修改了

2018-12-26 09:50 UTC, shrinktofit commented on cocos/3d/framework/physics/body.ts
> +            this._pull();
修改了

2018-12-26 09:50 UTC, shrinktofit commented on cocos/3d/framework/physics/body.ts
> +        this._cannonBody.world.addEventListener('beforeStep', this._onWorldBeforeStepListener);
修改了

2018-12-26 09:51 UTC, YunHsiao commented
builtin 的系统先不做?

2018-12-26 09:54 UTC, YunHsiao commented on cocos/3d/framework/physics/body.ts
> +            if (!vec3.exactEquals(scale, shape.scale)) {
有了 hasChanged 这就不用判断了

2018-12-26 10:13 UTC, shrinktofit commented on cocos/3d/framework/physics/body.ts
> +            if (!vec3.exactEquals(scale, shape.scale)) {
> builtin 的系统先不做?

是的

2018-12-27 03:35 UTC, pandamicro commented
https://github.com/cocos-creator/3d-tasks/issues/195

2018-12-27 04:03 UTC, merged