Improve label vertical align for 2d-tasks/issues/886
cocos/cocos-engine pull request #3664
Opened 2018-12-21 05:47 UTC by knoxHuang

Re: cocos-creator/2d-tasks#886

Changes:
 * 完善 label 垂直对齐问题

2018-12-24 03:05 UTC, pandamicro requested changes

2018-12-24 03:05 UTC, pandamicro commented on cocos2d/core/renderer/utils/label/ttf.js
> +        console.log(firstLinelabelY);
删除调试注释

2018-12-24 03:05 UTC, pandamicro commented on cocos2d/core/renderer/utils/label/ttf.js
> +        _underlineWidth = _drawFontSize / 8;
是 height 吧？？？

2018-12-24 03:05 UTC, pandamicro commented on cocos2d/core/renderer/utils/label/ttf.js
> +            firstLinelabelY = (_canvasSize.height - drawStartY) * 0.5 + _drawFontSize * MIDDLE_RATIO;
这里貌似还要加上 _margin

2018-12-24 03:05 UTC, pandamicro commented on cocos2d/core/renderer/utils/label/ttf.js
> +        let underlineStartPosition = cc.v2();
能不能不创建临时对象

2018-12-24 03:05 UTC, pandamicro commented on cocos2d/core/renderer/utils/label/ttf.js
> +        let textPos = cc.v2();
同上

2018-12-24 03:44 UTC, knoxHuang commented on cocos2d/core/renderer/utils/label/ttf.js
> +            firstLinelabelY = (_canvasSize.height - drawStartY) * 0.5 + _drawFontSize * MIDDLE_RATIO;
计算 center 不需要加上 _margin

2018-12-24 06:42 UTC, pandamicro approved these changes

2018-12-24 06:42 UTC, merged

2018-12-25 06:03 UTC, jareguo commented on cocos2d/core/renderer/utils/label/ttf.js
> +        if(!comp.cacheAsBitmap) return;
这个错了吧？现在是 batchAsBitmap

2019-06-13 00:13 UTC, unace commented
Hello, I tested label vertical alignment with Cocos Creator 2.1.1 (contains this fix) and 2.0.9 (not contain it)
Below is the result.

2.0.9 Editor
![image](https://user-images.githubusercontent.com/7022750/59394066-2380c180-8d33-11e9-9afa-62fcd1871711.png)
2.0.9 Web (Mac + Chrome Version 74.0.3729.169)
![image](https://user-images.githubusercontent.com/7022750/59394184-a6098100-8d33-11e9-8006-1de1dd5db1e6.png)
2.0.9 Web (Mac + Safari Version 12.1.1)
![image](https://user-images.githubusercontent.com/7022750/59394250-c8030380-8d33-11e9-9010-ead0c30c6ecd.png)
2.0.9 Android (Pixel2 + Android version 9)
![image](https://user-images.githubusercontent.com/7022750/59394514-c554de00-8d34-11e9-91a1-ae31c5632739.png)
2.0.9 Sample project
[label_test_209.zip](https://github.com/cocos-creator/engine/files/3283589/label_test_209.zip)

2.1.1 Editor (Mac)
![image](https://user-images.githubusercontent.com/7022750/59393609-28447600-8d31-11e9-9d68-4eba13a9fd4d.png)
2.1.1 Web (Mac + Chrome Version 74.0.3729.169)
![image](https://user-images.githubusercontent.com/7022750/59393661-62157c80-8d31-11e9-80e9-39bf5829f2cb.png)
2.1.1 Web (Mac + Safari Version 12.1.1)
![image](https://user-images.githubusercontent.com/7022750/59394612-267cb180-8d35-11e9-90a3-faedbdf4286b.png)
2.1.1 Android (Pixel2 + Android version 9)
![image](https://user-images.githubusercontent.com/7022750/59393951-a6ede300-8d32-11e9-9061-b199a9b1d834.png)
2.1.1 Sample project
[label_test_211.zip](https://github.com/cocos-creator/engine/files/3283541/label_test_211.zip)

Web Chrome alignment issue has been fixed, but there is a new Android alignment issue.

2019-06-18 06:18 UTC, asimaruk commented
Also aligning was changed between 2.1.0 and 2.1.1. Looks like it was good and now broken. Here is an example https://github.com/asimaruk/cc-2.1.1-label-align-issue 1
Reproduces in editor and chrome at least on macos

2019-06-18 12:38 UTC, jareguo commented
Thanks guys. We will test your demos to ensure they did fixed in 2.1.2.

2019-06-18 16:41 UTC, unace commented
@jareguo Thanks!

2019-06-21 07:54 UTC, knoxHuang commented
hi, the bug fix to 2.2  

the engine pr: https://github.com/cocos-creator/engine/pull/4378
the cocos2d-lite pr : https://github.com/cocos-creator/cocos2d-x-lite/pull/1739

2019-06-21 17:52 UTC, unace commented
Thanks for the quick fix! Do you have a plan to apply this fix to v2.1.2?

2019-07-01 03:52 UTC, jareguo commented
Yes, we will sync to 2.1.2

2019-09-23 02:11 UTC, dumganhar commented on cocos2d/core/renderer/utils/label/ttf.js
> +        _context.textBaseline = 'alphabetic';
这个地方为什么写死 textBaseline 为 'alphabetic' ？

2019-09-23 02:36 UTC, dumganhar commented on cocos2d/core/renderer/utils/label/ttf.js
> +const MIDDLE_RATIO = (BASELINE_RATIO + 1) / 2 - BASELINE_RATIO;
Magic number?