V2.0 release merge2.1
cocos/cocos-engine pull request #3665
Opened 2018-12-21 07:34 UTC by caryliu1999

Changes:
 Merge #3368 #3381 #3607 #3525 #3658 to V2.0-release.

2018-12-21 07:56 UTC, pandamicro requested changes

2018-12-21 07:56 UTC, pandamicro commented on extensions/dragonbones/webgl-assembler.js
> +    fillBuffers (comp, renderer) {
有两个 fillBuffers，这里合并有问题，traverseArmature 汗里说不应该在 fillBuffer 里面做

2018-12-21 08:43 UTC, caryliu1999 commented on extensions/dragonbones/webgl-assembler.js
> +    fillBuffers (comp, renderer) {
已经还原了，是合并出来的问题。traverseArmature是在updateRenderData里执行的。

2018-12-23 13:32 UTC, pandamicro approved these changes

2018-12-23 13:33 UTC, merged