Vmath
cocos/cocos-engine pull request #3700
Opened 2019-01-02 08:42 UTC by shrinktofit

2019-01-02 11:47 UTC, pandamicro commented
能不能让 tslint 强制下面的格式：

function xxx () {
}

function () {
}

就是函数和括号之间有空格

2019-01-03 01:53 UTC, shrinktofit commented
> 能不能让 tslint 强制下面的格式：
> 
> function xxx () {
> }
> 
> function () {
> }
> 
> 就是函数和括号之间有空格

可以强制，但是现有代码基本都是无空格。纵观其他库的Js/Ts代码，无空格更广泛一点。

2019-01-03 04:39 UTC, pandamicro requested changes

2019-01-03 04:39 UTC, pandamicro commented on cocos/core/vmath/bits.ts
> +    return ((v > 0) as unknown as number) - ((v < 0) as unknown as number);
没搜到这种语法 as unknown as number，意义是什么？如果是生僻的用法需要注明来源

2019-01-03 04:39 UTC, pandamicro commented on cocos/core/vmath/quat.ts
> +        const { x: bx, y: by, z: bz, w: bw } = b;
从下面文章的 JS Generation 章节来看，destructuring assignment 会产生临时对象或数组，大多数情况下我都不反对用更简便易读的代码来书写，但是对于 vmath 这种 core level，维护频度相对较低，又极度性能敏感的模块来说，我更倾向于用最直接对内存友好的 JS 写法，而不是依赖于 TS 的编译器。

https://basarat.gitbooks.io/typescript/docs/destructuring.html

2019-01-03 04:40 UTC, pandamicro commented
> 可以强制，但是现有代码基本都是无空格。纵观其他库的Js/Ts代码，无空格更广泛一点。

我们的代码规范如此

2019-01-03 10:35 UTC, shrinktofit commented on cocos/core/vmath/bits.ts
> +    return ((v > 0) as unknown as number) - ((v < 0) as unknown as number);
`v > 0`会产生一个`boolean`，Typescript 里 `boolean` 不能直接进行加减乘除，所以需要显式转换为 number；又因为 Typescript认为 `boolean` 到 `unknown`的转换是危险的，所以要求你先转换为`unknown`。

2019-01-03 10:49 UTC, pandamicro commented on cocos/core/vmath/quat.ts
> +        const { x: bx, y: by, z: bz, w: bw } = b;
检查了一下最终生成的代码，不会产生新的对象，那么就没关系了

2019-01-03 10:50 UTC, pandamicro approved these changes

2019-01-03 10:50 UTC, merged