fix open data context resolution views display incorrectly
cocos/cocos-engine pull request #3718
Opened 2019-01-07 02:36 UTC by knoxHuang

Re: cocos-creator/2d-tasks#859

Changes:
 * 添加开放数据的新 api 让用户在切换不同分辨率的时候能自行重置

2019-01-07 04:39 UTC, pandamicro requested changes

2019-01-07 04:39 UTC, pandamicro commented on cocos2d/core/components/WXSubContextView.js
> +         * !#zh 重置开放数据域的数据
Reset open data context size and viewport
重置开放数据域的尺寸和视窗

2019-01-08 02:17 UTC, pandamicro approved these changes

2019-01-08 02:17 UTC, merged

2019-02-10 05:19 UTC, jareguo commented
在 cc.WXSubContextView 组件上增加了 reset 方法，让用户在切换子域视图的时候能通过调用这个 API 正确重置视图大小。