compatible vec3 prop methods
cocos/cocos-engine pull request #3746
Opened 2019-01-11 06:58 UTC by ColinCollins

Re: https://github.com/cocos-creator/2d-tasks/issues/1032

1. 补齐 vec2 相关的 API 到 vec3 用于兼容 2.0 工程
2. 之前测试的时候似乎出了问题，这次顺便修正过来...(我发四我测了两边都是算的出数据的)

2019-01-11 07:08 UTC, jareguo commented on cocos2d/core/value-types/vec3.js
> +proto.rotate = function (radians, out) {
这个不能直接用 vec2 的吗？

2019-01-14 06:13 UTC, pandamicro requested changes

2019-01-14 06:13 UTC, pandamicro commented on cocos2d/core/value-types/vec3.js
> +js.value(proto, 'signAngle', v2Proto.signAngle);
signAngle 在 Vec3 里面没意义，这样适配太 hack 了，最多改为

function () {
    cc.warn('Vec3 doesn't support signAngle, please use cc.v2(vector).signAngle() instead.')
}

2019-01-14 06:13 UTC, pandamicro commented on cocos2d/core/value-types/vec3.js
> +js.value(proto, 'signAngle', v2Proto.signAngle);
rotateSelf 同样的道理

2019-01-14 07:22 UTC, jareguo commented on cocos2d/core/value-types/vec3.js
> +js.value(proto, 'signAngle', v2Proto.signAngle);
这样的话，旧项目如果升级到 2.1，就会跑不了了喔，因为 position 都变成 vec3 了

2019-01-14 08:30 UTC, ColinCollins commented
修改：
1. 取消 vec3 对 vec2 的兼容
2. 修改 DebugInfo 增加关于兼容警告 1408

2019-01-15 02:25 UTC, pandamicro approved these changes

2019-01-15 02:25 UTC, pandamicro commented
添加单元测试例并保障通过，从这次的修改发现上次合并的代码就包含问题，比如 Vec2.project 和 Vec2.angle 是不存在的，因为之前引用的是 Vec2 类，而不是 prototype，这个问题没能被发现说明你写完代码根本没测试。所以现在要求补写测试例

2019-01-16 10:51 UTC, ColinCollins commented
Commit2 : 调整 engien-test 完善 vec3 测试
![image](https://user-images.githubusercontent.com/35832931/51244292-afc6cc80-19bf-11e9-837b-f4c07d6727cc.png)

2019-01-16 12:01 UTC, jareguo commented on cocos2d/core/value-types/vec3.js
> +js.value(proto, 'rotateSelf', function () {cc.warnID(1408, 'vec3.rotateSelf', 'v2.1', 'cc.v2(selfVector).rotateSelf(radians)');});
@pandamicro 感觉这边都这样写了的话，这几个接口直接帮他做兼容都可以了

2019-01-18 10:44 UTC, jareguo commented on cocos2d/core/value-types/vec3.js
> +    return vec1.cross(vec2) < 0 ? -angle : angle;
return vec1.signAngle(vec2) 不好吗？

2019-01-18 10:53 UTC, jareguo approved these changes

2019-01-20 16:24 UTC, pandamicro commented on cocos2d/core/renderer/canvas/renderers/sprite/index.js
> +let spriteAssembler = CC_TEST ? require('../../../webgl/assemblers/sprite/index.js') : {
不要改不想关的代码，这部分应该是不会破坏 test 的，先回退

2019-01-20 16:24 UTC, pandamicro commented on cocos2d/core/renderer/utils/utils.js
> +        if (frame && !CC_TEST) {
这里可以保留

2019-01-21 01:53 UTC, ColinCollins commented
已调整

2019-01-21 07:27 UTC, merged