implement WebEditBoxImpl
cocos/cocos-engine pull request #3755
Opened 2019-01-15 06:52 UTC by umbrellaPP

Re: https://github.com/cocos-creator/2d-tasks/issues/1021

changeLog：
- 优化 web 上 editBox 的使用体验
- 废弃 editBox 的 stayOnTop, setFocus 接口，增加 focus() blur() 接口
- 修复移动端进入全屏失败的问题

其他修改：
- 整理 WebEditBoxImpl 逻辑，使 domInput 能够更好的支持样式的更新，关联：https://github.com/cocos-creator/2d-tasks/issues/372
- 减少 WebEditBoxImpl 同步 EditBox 数据的操作

2019-01-16 06:11 UTC, pandamicro requested changes

2019-01-16 06:11 UTC, pandamicro commented on cocos2d/core/components/editbox/CCEditBox.js
> +         * Note: only available on Web at the moment, this property will be deprecated in the future.
应该是从 2.0.8 开始废弃，你需要在 2.0 分支补一个 deprecated 的文档 PR

2019-01-16 06:11 UTC, pandamicro commented on cocos2d/core/components/editbox/CCEditBox.js
> +        if (this._impl && !this._impl.isFocused()) {
showLabels 的行为应该在 impl lost focus 的时候做，不应该在 updateString 的时候做，会导致重复操作

2019-01-16 06:11 UTC, pandamicro commented on cocos2d/core/components/editbox/CCEditBox.js
> -        this._hideLabels();
hideLabels 和下面 showLabels 的操作看起来不应该删除

2019-01-16 06:11 UTC, pandamicro commented on cocos2d/core/components/editbox/CCEditBox.js
> +        // On Web platform, not begine editing here, in input.onFocus callback instead.
语法不对，语句不通顺

2019-01-16 06:11 UTC, pandamicro commented on cocos2d/core/components/editbox/CCEditBox.js
> +     * @deprecated since v2.1
deprecated 信息应该加载 2.0.8

2019-01-17 06:30 UTC, umbrellaPP commented on cocos2d/core/components/editbox/CCEditBox.js
> +        if (this._impl && !this._impl.isFocused()) {
嗯，这一步的操作应该是考虑到  直接给 editBox.string 赋值
其实 showLabels 的逻辑也包括了 upateLabels ，更新 textLabel 和 placeholderLabel 的显示
这里这样子实现可能会更加清晰一点
```
_hideLabels () {
  this._labelShown = false;
  ...
}

_showLabels () {
  this._labelShown = true;
  this._updateLabels();
}

_updateLabels () {
  if (this._labelShown) {
    // update labels
  }
}

```

2019-01-17 06:30 UTC, umbrellaPP commented on cocos2d/core/components/editbox/CCEditBox.js
> -        this._hideLabels();
hideLabels 和 showLabels 其实只是 web 平台的需求，其他平台不需要 hideLabels / showLabels
所以 将这个操作放到 impl 的实现里去调用了

2019-01-17 12:02 UTC, pandamicro commented on cocos2d/core/components/editbox/CCEditBox.js
> +        if (this._impl && !this._impl.isFocused()) {
可以不用每次都 squash 然后 force push 自己的 PR 分支，否则每次都得全盘重审，审核过后只需要附加修改的 Commit 就可以了，这样审核者可以只看新 commits

2019-01-17 16:22 UTC, umbrellaPP commented
目前的实现还存在些问题，请先不要合并 pr

2019-01-31 07:56 UTC, umbrellaPP commented
这个 pr 需要多个机型多个浏览器下测试兼容性之后再合并

2019-02-01 10:24 UTC, umbrellaPP commented
目前 开始编辑的处理是 退出全屏，滚动视图到可见区域
结束编辑之后又恢复全屏
频繁退出进入全屏还会造成浏览器崩溃

我觉得这样的实现不是很好，退出全屏主要是因为全屏模式不支持视图滚动
或者就不退出全屏，在 web移动端实现一套类似原生层的 inputBox
这样原生平台也可以用 js 实现的 inputBox，还方便调整样式
这个难点在于获取软键盘的高度

pr 就先不合并吧

2019-02-07 03:31 UTC, pandamicro commented
> 或者就不退出全屏，在 web移动端实现一套类似原生层的 inputBox
> 这样原生平台也可以用 js 实现的 inputBox，还方便调整样式

Web 端在全屏情况下没有可靠的办法唤起软键盘，所以还是死结，除非自己实现软键盘，那就太不划算了，可以试一下看看是不是请求全屏的元素问题，目前应该是 Canvas 请求全屏，如果是 body 请求全屏，可能可以唤起软键盘

2019-02-13 10:04 UTC, umbrellaPP commented
pr 已经整理到了 2.1-release 分支，这个 pr 关闭了吧

2019-02-13 10:04 UTC, closed without merging