fix set button.interactable as false before __preload
cocos/cocos-engine pull request #3764
Opened 2019-01-17 03:55 UTC by umbrellaPP

changeLog:
- 修复用户在 onLoad 之前设置 button.interactable = false 导致 scale 为 0 的问题

这里 originalScale 是在 __preload 之后获取到的，在这之前 originalScale 都是无效数据

2019-01-17 03:58 UTC, knoxHuang approved these changes

2019-01-17 05:52 UTC, pandamicro requested changes

2019-01-17 05:52 UTC, pandamicro commented on cocos2d/core/components/CCButton.js
> +            let target = this._getTarget();
如果 target 也不存在呢？

var label = new cc.Label();
label.interactable = false;

貌似会出问题的

2019-01-17 05:52 UTC, pandamicro commented on cocos2d/core/components/CCButton.js
> +            let originalScale = this._getOriginalScale();
originalScale 如果在设置前为 null，判断是否已经初始化，如果没有的话就不要去设置 target 应该可以。

2019-01-17 06:30 UTC, knoxHuang commented on cocos2d/core/components/CCButton.js
> +            let target = this._getTarget();
```
var btn = new cc.Button();
btn.transition = 3;
btn.interactable = false;
```
这个确实会报错

2019-01-18 08:08 UTC, jareguo commented on cocos2d/core/components/CCButton.js
> +            let target = this._getTarget();
组件怎么可能直接 new

2019-01-18 08:14 UTC, umbrellaPP commented on cocos2d/core/components/CCButton.js
> +            let target = this._getTarget();
所以组件都是 通过 node.addComponent() 的形式创建的，没有 target 不存在的情况

2019-01-20 06:19 UTC, pandamicro commented on cocos2d/core/components/CCButton.js
> +            let target = this._getTarget();
这样的代码也不会报错啊

2019-01-20 06:46 UTC, pandamicro commented on cocos2d/core/components/CCButton.js
> +            let target = this._getTarget();
引擎代码和 API 设计应该孤立得去看自己和自己依赖的模块，不应该设想更上层用户的使用方式

2019-01-28 02:50 UTC, jareguo commented on cocos2d/core/components/CCButton.js
> +            let target = this._getTarget();
会报错的，我们现在的组件都是假定 this.node 存在的。如果 this.node 不存在引擎肯定会出问题。

2019-01-29 10:38 UTC, pandamicro commented on cocos2d/core/components/CCButton.js
> +                this._toScale.y = originalScale.y * this.zoomScale;
其实这里的问题是 originalScale 在被 applyTarget 之前是无效的，但同时 _applyTarget 之前（_preload）之前，做 touchmove, zoomup, zoomback 的实际逻辑也没有意义
那么与其做这些保护保证逻辑可以运行，不如将 originalScale 的初始值设为 null，在 _applyTarget 中初始化，使用的地方判断是否已经为 null，为空就不做任何逻辑即可

2019-01-31 07:42 UTC, umbrellaPP commented
pr 更新
- 编辑器下，target scale 改动之后，更新 originalScale
- 整理优化 button target 事件注册

2019-02-07 03:28 UTC, pandamicro approved these changes
基本实现思路没问题了，有一些细节需要关注下 👍

2019-02-07 03:28 UTC, pandamicro commented on cocos2d/core/components/CCButton.js
> +            if (this.transition !== Transition.SCALE || this._transitionFinished) {
如果正在 scale transition 过程中，节点的 scale 改变了，这个信息什么时候会同步呢？还是会直接丢弃？

2019-02-07 03:28 UTC, pandamicro commented on cocos2d/core/components/CCButton.js
> +        this._originalScale = cc.Vec2.ZERO
尽量保持复用

```
if (!this._originalScale) {
    this._originalScale = cc.Vec2.ZERO;
}
```

2019-02-07 03:28 UTC, pandamicro commented on cocos2d/core/components/CCButton.js
> +    onDestroy () {
还需要把 _originalScale 置空

2019-02-11 01:28 UTC, umbrellaPP commented on cocos2d/core/components/CCButton.js
> +            if (this.transition !== Transition.SCALE || this._transitionFinished) {
这个过程没办法同步的，scale transition 的过程就是不断的在发射 scale-changed 事件，
这个过程中再改变scale， 引擎没办法区分这是用户行为还是引擎行为

2019-02-11 01:46 UTC, pandamicro commented on cocos2d/core/components/CCButton.js
> +        delete this._originalScale;
不要做任何 delete 操作，应该置空

2019-02-11 02:01 UTC, pandamicro approved these changes

2019-02-11 02:01 UTC, merged