Optimize db
cocos/cocos-engine pull request #3772
Opened 2019-01-20 14:27 UTC by sunnylanwanjun

issue:https://github.com/cocos-creator/2d-tasks/issues/1015
jsb-adapter:https://github.com/cocos-creator-packages/jsb-adapter/pull/107
another engine pr:https://github.com/cocos-creator/engine/pull/3773 (突破65535限制)

2019-01-21 02:39 UTC, 2youyou2 commented on extensions/dragonbones/webgl-assembler.js
> +                case 0x01:
这些 magic number 用名字来定义吧，不知道是用来干嘛的

2019-01-21 02:45 UTC, 2youyou2 commented on extensions/dragonbones/webgl-assembler.js
> +            let graphics = comp._debugDraw;
cache mode 没有 debug draw ?

2019-01-21 02:57 UTC, sunnylanwanjun commented on extensions/dragonbones/webgl-assembler.js
> +            let graphics = comp._debugDraw;
是的，如果需要debug的话，切换下模式就好了，编辑器里面提供了切换模式的功能。

2019-01-21 06:03 UTC, sunnylanwanjun commented on extensions/dragonbones/webgl-assembler.js
> +                case 0x01:
ok，已经使用const代替。

2019-01-23 09:31 UTC, pandamicro requested changes
整个 Cache 的思路还是很清晰的，赞！

2019-01-23 09:31 UTC, pandamicro commented on extensions/dragonbones/ArmatureCache.js
> +// Cache an animation all frame.
Cache all frames in an animation

2019-01-23 09:31 UTC, pandamicro commented on extensions/dragonbones/ArmatureCache.js
> +        return this.allFrame[index];
allFrame -> frames 比较自然，而且由于是公开接口，也不需要通过函数访问了，直接使用 cache.frames[index] 即可，代码阅读也没问题

2019-01-23 09:31 UTC, pandamicro commented on extensions/dragonbones/ArmatureCache.js
> +    ctor () {
归属的 armature 不应该记录下来吗？

2019-01-23 09:31 UTC, pandamicro commented on extensions/dragonbones/ArmatureCache.js
> +    _updateFrame (armature, index) {
如果我传递不同的 armature 给同一个 CacheItem 感觉很奇怪，但是 API 却允许这样的事情

2019-01-23 09:31 UTC, pandamicro commented on extensions/dragonbones/ArmatureCache.js
> +        let colors = this.colors = frame.colors;
需要用到的所有属性，都应该在 constructor 中声明，不过这两个属性挺奇怪的，他们应该是临时的，至少不应该是 public api

2019-01-23 09:31 UTC, pandamicro commented on extensions/dragonbones/ArmatureCache.js
> +                segments[_segOffset++] = {
_segOffset 和 _colorOffset 有可能不同步吗？如果不可能，应该用同一个变量做增长，如果可能，怎么匹配的？

2019-01-23 09:31 UTC, pandamicro commented on extensions/dragonbones/ArmatureCache.js
> +        this.dbCache = {};
该私有的 API 还是加一个 _

2019-01-23 09:31 UTC, pandamicro commented on extensions/dragonbones/ArmatureDisplay.js
> +         * Below properties will effect when render mode is sharedCache or privateCache.
不是 API 注释不要用 

```
/**
 *
 */
```

用 `//` 就可以了

2019-01-23 09:31 UTC, pandamicro commented on extensions/dragonbones/ArmatureDisplay.js
> +                this._eventObject = {}
不要省略分号

2019-01-23 09:31 UTC, pandamicro commented on extensions/dragonbones/ArmatureDisplay.js
> +            this.emit(dragonBones.EventObject.START, this._eventObject);
空对象？不使用 cache 的时候 DB 发送的是什么

2019-01-23 09:31 UTC, pandamicro commented on extensions/dragonbones/ArmatureCache.js
> +        } while (!animation.isCompleted);
以 animation 为单位一次计算所有帧的数据，计算量感觉有些太大了，能不能分布到第一次动画运行的时候，每帧生成当前帧的（如果找不到 cache）

2019-01-23 09:31 UTC, pandamicro commented on extensions/dragonbones/ArmatureDisplay.js
> +    updateCache (animName) {
给用户手动更新吗？如果是用户接口，要写 API 文档

2019-01-23 09:31 UTC, pandamicro commented on extensions/dragonbones/CCFactory.js
> +const dbDebug = dragonBones.DragonBones.debug;
这个用户好像不会设置，不在我们的 API 里面

2019-01-23 09:31 UTC, pandamicro commented on extensions/dragonbones/webgl-assembler.js
> +            let graphics = comp._debugDraw;
在运行时检查如果用户同时开启了 cache mode 和 debugDraw 的话，警告一下

2019-01-23 09:31 UTC, pandamicro commented on extensions/dragonbones/ArmatureCache.js
> +let CacheItem = cc.Class({
这个类名有点太笼统了

2019-01-24 08:57 UTC, sunnylanwanjun commented on extensions/dragonbones/webgl-assembler.js
> +            let graphics = comp._debugDraw;
嗯，加了

2019-01-24 08:59 UTC, sunnylanwanjun commented on extensions/dragonbones/ArmatureCache.js
> +    ctor () {
CacheItem现在更名为AnimationCache，由armatureCache进行管理，armature存在_armatureCache中，AnimationCache只是保存某个Armature的某个动画的内容，所以它不持有Armature。而整个AnimationCache保存在armatureCache中。

2019-01-24 09:00 UTC, sunnylanwanjun commented on extensions/dragonbones/ArmatureCache.js
> +    _updateFrame (armature, index) {
不会有这种事情发生，因为在updateAnimationCache方法中已经避免这种情况发生，它会先取得对应的armatureCache，再去更新对应armatureCache的animationCache

2019-01-24 09:01 UTC, sunnylanwanjun commented on extensions/dragonbones/ArmatureCache.js
> +        let colors = this.colors = frame.colors;
嗯，改了。

2019-01-24 09:03 UTC, sunnylanwanjun commented on extensions/dragonbones/ArmatureCache.js
> +        } while (!animation.isCompleted);
由于Armature对象共享，有可能多个地方使用， 它们play不同的animation，所以就不能在运行时填cache了。

2019-01-24 09:06 UTC, sunnylanwanjun commented on extensions/dragonbones/ArmatureDisplay.js
> +    updateCache (animName) {
写了。

2019-01-24 09:07 UTC, sunnylanwanjun commented on extensions/dragonbones/CCFactory.js
> +const dbDebug = dragonBones.DragonBones.debug;
删了，之前用来查看db日志的。

2019-01-24 09:07 UTC, sunnylanwanjun commented on extensions/dragonbones/ArmatureCache.js
> +let CacheItem = cc.Class({
改为AnimationCache了。

2019-01-29 09:47 UTC, pandamicro approved these changes

2019-01-29 09:57 UTC, merged