modify the warning
cocos/cocos-engine pull request #3825
Opened 2019-01-31 07:01 UTC by ColinCollins

修正 ts 1.10 之后的脚本警告问题。
稍后会附带的修正 ts 相关的文档

2019-02-07 02:22 UTC, pandamicro requested changes

2019-02-07 02:22 UTC, pandamicro commented on cocos2d/core/platform/preprocess-class.js
> +                        'Now in JS it should be changed to:\n' +
If you use JavaScript, it should be changed to:

2019-02-07 02:22 UTC, pandamicro commented on cocos2d/core/platform/preprocess-class.js
> +                        'Now in TS it should be changed to:\n' +
If you use TypeScript, it should be changed to:

2019-02-07 02:22 UTC, pandamicro commented on cocos2d/core/platform/preprocess-class.js
> +                                'Now in JS it should be changed to:\n' +
同上

2019-02-07 02:22 UTC, pandamicro commented on cocos2d/core/platform/CCClassDecorator.js
> +                // avoid the excess warning when the ts decorator format is error
Avoid excessive warning when the ts decorator format is wrong

2019-02-11 07:45 UTC, jareguo approved these changes

2019-02-12 06:33 UTC, pandamicro approved these changes

2019-02-12 06:34 UTC, merged