Buttonnot
cocos/cocos-engine pull request #3831
Opened 2019-02-01 10:46 UTC by ColinCollins

Re: https://github.com/cocos-creator/2d-tasks/issues/1060

1. 修改 button 注释
2. 增添监听事件注释

2019-02-07 02:39 UTC, pandamicro requested changes

2019-02-07 02:39 UTC, pandamicro commented on cocos2d/core/components/CCButton.js
> + * The user can get the current clicked object through the 'event.target' which is from the clickEvent callback function.
User can get the current clicked node with 'event.target' from event object which is passed as parameter in the callback function of click event.

2019-02-07 02:39 UTC, pandamicro commented on cocos2d/core/components/CCButton.js
> + * 用户可以通过获取 __点击事件__ 回调参数属性 event.target 获取当前点击对象。
用户可以通过获取 __点击事件__ 回调函数的参数 event 的 target 属性 event.target 获取当前点击对象。

2019-02-07 02:39 UTC, pandamicro commented on cocos2d/core/CCNode.js
> + * The position changing event, you can listen this event through the statement cc.node.on(cc.Node.EventType.POSITION_CHANGED, callback, this);
The position changing event, you can listen this event through the statement 

->

The position changing event, you can listen to this event through the statement

2019-02-12 06:35 UTC, pandamicro approved these changes

2019-02-12 06:35 UTC, merged

2019-02-12 06:52 UTC, jareguo commented on cocos2d/core/CCNode.js
> + * 自节点顺序变动监听事件，通过 cc.node.on(cc.Node.EventType.CHILD_REORDER, callback, this); 进行监听。
子节点顺序变动事件

2019-02-12 06:52 UTC, jareguo commented on cocos2d/core/CCNode.js
> + * 自节点顺序变动监听事件，通过 cc.node.on(cc.Node.EventType.CHILD_REORDER, callback, this); 进行监听。
cc.node 是什么鬼？