Fix the flash problem when the label plays the fadeIn action.
cocos/cocos-engine pull request #3837
Opened 2019-02-12 10:05 UTC by caryliu1999

Re: cocos-creator/2d-tasks#649

2019-02-12 10:53 UTC, pandamicro requested changes

2019-02-12 10:53 UTC, pandamicro commented on cocos2d/core/components/CCLabel.js
> +            this._srcBlendFactor = cc.macro.BlendFactor.SRC_ALPHA;
这里不需要修改了就，遵照用户设定的就 ok 了，不应该覆盖

2019-02-12 10:53 UTC, pandamicro commented on cocos2d/core/renderer/utils/label/ttf.js
> +        _context.fillRect(0, 0, _canvas.width, _canvas.height);
alpha test 还是需要做，在这个 PR 中完整解决问题吧

2019-02-13 01:58 UTC, pandamicro commented on cocos2d/core/renderer/render-engine.js
> +        { name: 'alphaTest', value: true },
默认值不应该修改，应该在 Label 中专门对 Label 的 material 修改

2019-02-13 02:22 UTC, caryliu1999 commented on cocos2d/core/components/CCLabel.js
> +            this._srcBlendFactor = cc.macro.BlendFactor.SRC_ALPHA;
已删除

2019-02-13 07:07 UTC, caryliu1999 commented on cocos2d/core/renderer/render-engine.js
> +        { name: 'alphaTest', value: true },
已修改，目前遗留两个问题需要再考虑下。
1.Label修改单独的alphaTest设置之后跟Sprite无法再进行合批。
2.fillBuffer里面完全使用节点颜色，文字绘制到canvas时使用white进行绘制，然后删除了CCLabel里的updateColor，这样在做文字颜色或者透明度变化之类的动画时，就不需要更新ttf中的updateRenderData，提高了这种使用场景的性能消耗。但是对于描边的颜色会有影响，深色文字在颜色叠加之后会加深描边的颜色。

2019-02-15 05:50 UTC, pandamicro approved these changes

2019-02-15 05:50 UTC, pandamicro commented on cocos2d/core/renderer/render-engine.js
> +        { name: 'alphaTest', value: true },
第二个问题目前可以忽略

2019-02-15 05:50 UTC, merged

2019-02-15 11:26 UTC, wang-yichun commented
我是用creator2.0.8. 项目中出现这个问题比较急。并按照这次的提交进行了修改。android和浏览器上的问题解决了，ios的label却变成了白色矩形。怎么解决?

2019-02-16 01:49 UTC, hao-ming commented
@pandamicro @caryliu1999 两位大神，能帮我们看一下上边的这个问题么？非常感谢

2019-02-18 03:20 UTC, caryliu1999 commented
> 我是用creator2.0.8. 项目中出现这个问题比较急。并按照这次的提交进行了修改。android和浏览器上的问题解决了，ios的label却变成了白色矩形。怎么解决?

CCLabel的Blend Function有修改为SRC_ALPHA吗？合并这个修改之后，之前的CCLabel Blend设置需要由ONE修改为SRC_ALPHA

2019-02-18 03:45 UTC, wang-yichun commented
android 确实按你说的这么改没有问题。但ios全部都是白色矩形，（而且还并不是全部遮挡的白色矩形。是半漏下面一部分文字的白色矩形)

2019-02-18 03:47 UTC, wang-yichun commented
而且另外一个问题就是：编辑器有时候会自动把label的 SRC_ALPHA 变成ONE。

2019-02-18 04:10 UTC, caryliu1999 commented
> 而且另外一个问题就是：编辑器有时候会自动把label的 SRC_ALPHA 变成ONE。

你的ios有问题是原生版本吗？编辑器自动把label修改为ONE是因为之前的CCLabel会强制把所有的文字属性全部修改为ONE了，确认下CCLabel有没有合并成功。

2019-02-18 06:25 UTC, wang-yichun commented
ios是原生版本有问题。
有关CCLabel,我只是更新到2.0.8的Creator后，照着 “Fix the flash problem when the label plays the fadeIn action.”这次提交进行了修改，是否之前还有修改我需要同步修改？

2019-02-18 06:32 UTC, caryliu1999 commented
> ios是原生版本有问题。
> 有关CCLabel,我只是更新到2.0.8的Creator后，照着 “Fix the flash problem when the label plays the fadeIn action.”这次提交进行了修改，是否之前还有修改我需要同步修改？

好，我测试下看看。

2019-02-18 14:08 UTC, caryliu1999 commented
> ios是原生版本有问题。
> 有关CCLabel,我只是更新到2.0.8的Creator后，照着 “Fix the flash problem when the label plays the fadeIn action.”这次提交进行了修改，是否之前还有修改我需要同步修改？

https://github.com/cocos-creator/engine/pull/3865 如果你那里急需修复的话可以先合并下这个修改测试看

2019-02-19 14:06 UTC, jareguo commented
修复 Label 在搭配 faceIn action 使用时可能会闪现的问题