improve full screen api, adjust editboxImpl
cocos/cocos-engine pull request #3840
Opened 2019-02-13 10:03 UTC by umbrellaPP

将之前的 pr https://github.com/cocos-creator/engine/pull/3755 提交到 2.1-release，
还做了一些调整：
- requestFullScreen 之后，如果触发 fullScreenError 事件，才去注册 touch事件
- 增加 cc.screen.diableAutoFullScreen 接口， 移除 touch 事件，防止进入全屏
- 调整了一下 android 上的输入体验，android web 端需要处理浏览器全屏和滚动视图， iOS 端不需要

2019-02-14 07:47 UTC, umbrellaPP commented
目前 web 端的 editBox 存在一坑解决不了的坑，总结一下：
- 频繁地进入退出全屏会导致浏览器崩溃，但是这个只是偶然
- chrome 进入全屏会拉升 canvas 的高度，正常退出全屏后，canvas 的高度会恢复。但是 editBox 在退出全屏同时会拉起软键盘，不知道算不算 chrome 的bug，这个时候 canvas 的高度不会恢复。。。canvas 高度变长了会导致编辑结束后，视图滚回原位会出错
![1](https://user-images.githubusercontent.com/17872773/52770783-fd8e2d80-306e-11e9-8e0a-b69399ec9b4c.jpeg)
![2](https://user-images.githubusercontent.com/17872773/52770789-01ba4b00-306f-11e9-94c2-79ee408eec8a.jpeg)
![3](https://user-images.githubusercontent.com/17872773/52770795-054dd200-306f-11e9-8aeb-109ebfcb0b8d.jpeg)

- editBox stayOnTop 的状态下，如果editBox 在屏幕外，拉宽 html 的布局，导致在 iOS 上编辑的时候，聚焦 editBox 会有点奇怪
<img width="250" alt="4" src="https://user-images.githubusercontent.com/17872773/52771003-a9d01400-306f-11e9-8e7e-4fe6c097379a.png">
![5](https://user-images.githubusercontent.com/17872773/52771009-ae94c800-306f-11e9-8af4-695cfd95f3fe.jpeg)

这些都是使用体验上的问题，暂时没什么比较好的解决方案，先做个记录吧

2019-02-15 11:07 UTC, pandamicro requested changes

2019-02-15 11:07 UTC, pandamicro commented on cocos2d/core/components/editbox/CCEditBox.js
> +
没有内容的话删除 notify

2019-02-15 11:07 UTC, pandamicro commented on cocos2d/core/components/editbox/CCEditBox.js
> +
同上

2019-02-15 11:07 UTC, pandamicro commented on cocos2d/core/components/editbox/CCEditBox.js
> +                cc.warn('editBox.stayOnTop is deprecated since v2.1.');
这个版本应该写 is removed

2019-02-15 11:07 UTC, pandamicro commented on cocos2d/core/components/editbox/CCEditBox.js
> +            this._updateLabels();
如果 _impl 不存在，也应该 updateLabels

2019-02-15 11:07 UTC, pandamicro commented on cocos2d/core/platform/CCScreen.js
> +        // Bug fix only for v2.1, don't merge into v2.0
这个注释不太清晰，应该写差异在哪里

2019-02-15 11:07 UTC, pandamicro commented on cocos2d/core/platform/CCScreen.js
>          this.requestFullScreen(element, onFullScreenChange);
ensureFullScreen 只应该在 autoFullScreen 接口中调用，如果用户调用 requestFullScreen 不是通过触摸调用的，就让浏览器报错或者忽略就好了。否则这两个接口就跟之前的行为不统一了

2019-02-15 11:07 UTC, pandamicro commented on cocos2d/core/components/editbox/EditBoxImplBase.js
> +    _onTouchEnded () {
不理解为什么要加这个接口，EditboxImpl 只包含行为是没问题的

2019-02-15 13:33 UTC, umbrellaPP commented on cocos2d/core/components/editbox/EditBoxImplBase.js
> +    _onTouchEnded () {
主要是因为 chrome 在上推软键盘的时候，偶尔会有些情况导致 editBox 跟 input 错位了
这时候，web 端其实还是有可能会触发 touchEnd 事件的，这里主要是为了 web 端做禁用 touchEnd 的处理

2019-02-18 06:22 UTC, pandamicro commented on cocos2d/core/components/editbox/CCEditBox.js
> -        }
还发现一个问题，目前的 CCEditbox 里面完全没有取消节点的事件注册，如果 disable 组件的话会有问题，需要在正确的时机 unregister

2019-02-18 06:22 UTC, pandamicro commented on cocos2d/core/components/editbox/EditBoxImplBase.js
> +    _onTouchEnded () {
其实这个问题的根源是不应该在 web 端注册节点事件，touch start 和 touch end 都不应该，所以应该是在 web 环境下 unregisterNodeEvent，可以在 EditBox 中判断环境处理，也可以在 WebEditBoxImpl 对 delegate 进行处理

2019-02-19 03:08 UTC, pandamicro commented on cocos2d/core/components/editbox/WebEditBoxImpl.js
> +                self._elem.scrollIntoView({block: "start", inline: "nearest", behavior: "smooth"});
这个格式有没有文档描述？

2019-02-19 03:13 UTC, pandamicro commented on cocos2d/core/components/editbox/WebEditBoxImpl.js
> +                self._elem.scrollIntoView({block: "start", inline: "nearest", behavior: "smooth"});
https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView

2019-02-19 03:13 UTC, pandamicro approved these changes

2019-02-19 03:14 UTC, merged