add the primitive module
cocos/cocos-engine pull request #3841
Opened 2019-02-13 10:08 UTC by ColinCollins

新增 primitive 对应 API 文档模块

2019-02-14 07:41 UTC, pandamicro requested changes

2019-02-14 07:41 UTC, pandamicro commented on cocos2d/core/3d/primitive/index.js
> -     */
你把这些提出去干啥？？？

2019-02-14 09:44 UTC, ColinCollins commented on cocos2d/core/3d/primitive/index.js
> -     */
注释不提出来，firedoc 扫描不到啊。。。。

2019-02-15 08:05 UTC, pandamicro approved these changes

2019-02-15 08:05 UTC, merged