Add cache mode of label.
cocos/cocos-engine pull request #3916
Opened 2019-02-26 07:54 UTC by caryliu1999

Re: cocos-creator/2d-tasks#

Changes:
 增加文本的字符缓存模式，适用于少量重复文本频繁更新的使用场景，优化微信平台的文本更新性能

2019-02-26 09:53 UTC, caryliu1999 commented
测试数据对比（测试机型-OPPO a57，测试平台-微信7.0.3）

- 包体（未压缩）
3330 kb -> 3398 kb, 增加68kb。

- 内存 
20.0MB -> 20.2MB, 增加0.2M。

- 性能
渲染耗时：130-150ms  -> 11-13ms
帧率：6-9帧 -> 59-60帧

2019-02-26 12:08 UTC, pandamicro requested changes

2019-02-26 12:08 UTC, pandamicro commented on cocos2d/core/assets/CCTexture2D.js
> +        this._reservedImage = false;
_reserveImage 更顺

2019-02-26 12:08 UTC, pandamicro commented on cocos2d/core/components/CCLabel.js
> +                this._ttfTexture = this._assembler._getAssemblerData();
这里会让 _ttfTexture 的类型不稳定，应该用不同的属性来保存 letter  atlas

2019-02-26 12:08 UTC, pandamicro commented on cocos2d/core/components/CCLabel.js
> +
spaces

2019-02-26 12:08 UTC, pandamicro commented on cocos2d/core/renderer/utils/label/letter-font.js
> +let _canvasPool = {
和 ttf texture 的 canvas pool 共享吧

2019-02-26 12:08 UTC, pandamicro commented on cocos2d/core/renderer/utils/label/letter-font.js
> +    this._lineIndex = 0;
用尽量简短的属性名，同时可以不需要使用 `_`，

posx / ox, etc
line / lid

2019-02-26 12:08 UTC, pandamicro commented on cocos2d/core/renderer/utils/label/letter-font.js
> +    this._xAdvance = 0;
同上

2019-02-26 12:08 UTC, pandamicro commented on cocos2d/core/renderer/utils/label/letter-font.js
> +        return cc.v2(labelX, firstLinelabelY);
不要创建新对象，内部过程要保障零垃圾

2019-02-26 12:08 UTC, pandamicro commented on cocos2d/core/renderer/utils/label/letter-font.js
> +        let hash = char.charCodeAt(0) + labelInfo._hash
分号

2019-02-26 12:08 UTC, pandamicro commented on cocos2d/core/renderer/utils/label/letter-font.js
> +            let temp = new LetterTexture(char, labelInfo);
其实可以不复用 Canvas，而是直接复用 LetterTexture，用 LetterTexturePool 优化内存使用

2019-02-26 12:08 UTC, pandamicro commented on cocos2d/core/components/CCLabel.js
> + * @property {Number} LETTER
说清楚 LETTER 模式的限制，比如是否支持 shrink 模式和换行等

2019-02-26 12:08 UTC, pandamicro commented on cocos2d/core/renderer/webgl/assemblers/label/letter-font.js
> +module.exports = js.addon({
这个 Assembler 和 bmfont assembler 差异在哪些地方？

2019-02-26 15:01 UTC, caryliu1999 commented on cocos2d/core/components/CCLabel.js
> + * @property {Number} LETTER
主要是自适应文本尺寸暂时不支持，因为预先已经保存了文本Size大小的字符到图集中，然后再直接获取进行渲染。排版结束之后再去自适应大小会不断写入新的Size字符进去，这个我考虑清楚之后补一下。

2019-02-26 15:09 UTC, caryliu1999 commented on cocos2d/core/renderer/webgl/assemblers/label/letter-font.js
> +module.exports = js.addon({
一开始是想复用一份的，结果判断越来越多就改为两份独立的了。
1.主要是letter assembler的字符不是唯一的，依据size跟字体加上字符进行区分，bmfont是相同大小的唯一字符集合，通过字符映射，获取时的映射值不同，并且bmfont可以同步进行缩放处理，letter就得重新绘制需要的size。
2.图集的指定和生成在更新属性时也不一致。letter assembler的资源是根据字符串内容实时绘制并添加进图集，BMFont的图集资源是预先生成好的，两边的处理不一致，图集也没办法共用。

2019-02-26 15:09 UTC, caryliu1999 commented on cocos2d/core/renderer/utils/label/letter-font.js
> +        let hash = char.charCodeAt(0) + labelInfo._hash
已修改

2019-02-26 15:10 UTC, caryliu1999 commented on cocos2d/core/assets/CCTexture2D.js
> +        this._reservedImage = false;
已修改

2019-02-26 15:16 UTC, caryliu1999 commented on cocos2d/core/renderer/utils/label/letter-font.js
> +        return cc.v2(labelX, firstLinelabelY);
已修改，计算比较简单，直接把方法删除放在获取的地方计算。

2019-02-27 01:36 UTC, caryliu1999 commented on cocos2d/core/components/CCLabel.js
> +                this._ttfTexture = this._assembler._getAssemblerData();
已修改

2019-02-27 01:53 UTC, caryliu1999 commented on cocos2d/core/renderer/utils/label/letter-font.js
> +            let temp = new LetterTexture(char, labelInfo);
这里LetterTexture作为局部变量，加到图集之后会直接销毁了内部的Texture，避免微信上面的内存占用，新增的图片资源相当于只有一个图集，这个做内存池也不是很需要。

2019-02-27 02:36 UTC, caryliu1999 commented on cocos2d/core/renderer/utils/label/letter-font.js
> +    this._lineIndex = 0;
已修改

2019-02-27 02:36 UTC, caryliu1999 commented on cocos2d/core/renderer/utils/label/letter-font.js
> +    this._xAdvance = 0;
已修改

2019-02-27 02:48 UTC, caryliu1999 commented on cocos2d/core/renderer/utils/label/letter-font.js
> +let _canvasPool = {
已修改

2019-02-27 03:36 UTC, pandamicro commented on cocos2d/core/assets/CCTexture2D.js
> +    _setReserved (state) {
为什么要加 reserveImage ？我检查了一下，没有任何地方用到 setReserved 呀

2019-02-27 07:24 UTC, jareguo requested changes

2019-02-27 07:24 UTC, jareguo commented on cocos2d/core/components/CCLabel.js
> + * @property {Number} LETTER
该模式是否会进入动态图集？补充一下

2019-02-27 07:24 UTC, jareguo commented on cocos2d/core/components/CCLabel.js
> + * !#en NONE.
英文注释完善下吧，NONE 等于没说……

2019-02-27 07:24 UTC, jareguo commented on cocos2d/core/components/CCLabel.js
> + * !#zh BITMAP 模式，将label缓存成静态图像并加入到动态图集。
中英文之间请用空格分隔，规范详见 https://github.com/cocos-creator/creator-docs/blob/master/zh/CONTRIBUTING.md

2019-02-27 07:24 UTC, jareguo commented on cocos2d/core/components/CCLabel.js
> + * @property {Number} LETTER
LETTER 是否会有歧义？LETTER 包含信、横幅这层意思。干嘛不直接用 CHAR，程序员秒懂

2019-02-27 07:24 UTC, jareguo commented on cocos2d/core/components/CCLabel.js
> +         * !#zh 文本缓存模式
请补充一下，这个模式仅对动态字体有效，对 BMFont 无效。

2019-02-27 07:24 UTC, jareguo commented on cocos2d/core/components/CCLabel.js
> -        _batchAsBitmap: false,
请保留这个属性（隐藏起来），用作对 2.0.7 工程的兼容。当读取到 _batchAsBitmap 为 true，并且 cacheMode 为 NONE 时，自动设置 cacheMode 为 1，然后设置 _batchAsBitmap 为 false。

2019-02-27 08:04 UTC, caryliu1999 commented on cocos2d/core/components/CCLabel.js
> + * @property {Number} LETTER
> 该模式是否会进入动态图集？补充一下

已添加注释

2019-02-27 08:06 UTC, caryliu1999 commented on cocos2d/core/components/CCLabel.js
> + * !#en NONE.
已补充

2019-02-27 08:07 UTC, caryliu1999 commented on cocos2d/core/components/CCLabel.js
> + * !#zh BITMAP 模式，将label缓存成静态图像并加入到动态图集。
已修改

2019-02-27 08:11 UTC, caryliu1999 commented on cocos2d/core/components/CCLabel.js
> +         * !#zh 文本缓存模式
已补充

2019-02-27 08:54 UTC, caryliu1999 commented on cocos2d/core/components/CCLabel.js
> -        _batchAsBitmap: false,
已修改

2019-02-27 08:59 UTC, caryliu1999 commented on cocos2d/core/components/CCLabel.js
> + * @property {Number} LETTER
> LETTER 是否会有歧义？LETTER 包含信、横幅这层意思。干嘛不直接用 CHAR，程序员秒懂

fnt的文件里面用了Letter这个单词作为单个字符的字段名，我们BMFont的文件也用的这个单词，就给保持一致了，类名文件名就都用了这个。

2019-02-28 01:44 UTC, jareguo commented on cocos2d/core/components/CCLabel.js
> + * @property {Number} LETTER
我查了一下，letter 特指字母，character 不单单是 26 个字母，而是包含了所有 **可用于书写** 的符号，如标点。所以这里用 char 作为基本类型是更准确的。
那为什么 BMFont 会用 letter，因为通常美术生产艺术字时确实就是依次书写 26 个字母，所以叫做 letter 会更加直观。
但是作为系统字体，更多是面向中文的，否则 BMFont 性能会更好，是吧？
关键问题就在于，对老外来说，中文没有 letter 的概念，中文只有 character。因此建议改成 CHAR，不太建议照顾到 BMFont。

cc @pandamicro

2019-02-28 01:44 UTC, jareguo commented on cocos2d/core/components/CCLabel.js
> +         * @deprecated
这些注释可以从文档去掉了，直接 `// For compatibility with v2.0.x temporary reservation` 就行

2019-02-28 01:44 UTC, jareguo commented on cocos2d/core/components/CCLabel.js
> +        if (this._batchAsBitmap && this.cacheMode == CacheMode.NONE) {
建议用 ===

2019-02-28 01:54 UTC, caryliu1999 commented on cocos2d/core/components/CCLabel.js
> + * @property {Number} LETTER
> 我查了一下，letter 特指字母，character 不单单是 26 个字母，而是包含了所有 **可用于书写** 的符号，如标点。所以这里用 char 作为基本类型是更准确的。
> 那为什么 BMFont 会用 letter，因为通常美术生产艺术字时确实就是依次书写 26 个字母，所以叫做 letter 会更加直观。
> 但是作为系统字体，更多是面向中文的，否则 BMFont 性能会更好，是吧？
> 关键问题就在于，对老外来说，中文没有 letter 的概念，中文只有 character。因此建议改成 CHAR，不太建议照顾到 BMFont。
> 
> cc @pandamicro

已修改

2019-02-28 02:02 UTC, caryliu1999 commented on cocos2d/core/components/CCLabel.js
> +        if (this._batchAsBitmap && this.cacheMode == CacheMode.NONE) {
已修改

2019-02-28 02:02 UTC, caryliu1999 commented on cocos2d/core/components/CCLabel.js
> +         * @deprecated
已修改

2019-02-28 02:34 UTC, pandamicro approved these changes

2019-02-28 02:35 UTC, merged