add Label Shadow for 2d-tasks/issues/138
cocos/cocos-engine pull request #4046
Opened 2019-03-15 06:11 UTC by knoxHuang

Re: cocos-creator/2d-tasks#138

Changes:
 * 添加 Shadow 

效果图：

![image](https://user-images.githubusercontent.com/7564028/54412003-1b14ec80-472c-11e9-82fc-6761ed9e0bcd.png)

2019-03-15 06:38 UTC, pandamicro commented
在不同平台的表现一致吗？麻烦将不同平台的表现都截图一下放在这里

2019-03-18 02:59 UTC, jareguo commented
Windows、百度小游戏、我们的 OVH Runtime 是否支持呢？麻烦对不支持的平台给出相关警告。

2019-03-18 07:27 UTC, jareguo commented on modules.json
> +    "name": "CCLabelShadow",
命名统一一下啊，outline 是 LabelOutline。建议 LabelOutline 和 LabelShadow 合并成 Label Effect，都没几行代码，拆成两个模块太琐碎了。

2019-03-18 07:27 UTC, jareguo commented on editor/i18n/zh/localization.js
> +            "blur": "阴影模糊效果的程度"
阴影的模糊程度

2019-03-18 07:27 UTC, jareguo commented on editor/i18n/en/localization.js
> +            "color": "The Shadow color",
S 小写

2019-03-18 07:27 UTC, jareguo commented on cocos2d/core/components/CCLabelShadow.js
> + Copyright (c) 2017-2018 Xiamen Yaji Software Co., Ltd.
2017 - 2019

2019-03-18 07:27 UTC, jareguo commented on cocos2d/core/components/CCLabelShadow.js
> + * !#en
API 注释别漏了

2019-03-18 07:27 UTC, jareguo commented on cocos2d/core/components/CCLabelShadow.js
> + * !#zh 阴影效果组件，用于字体阴影，只能用于系统字体
用于给 Label 组件添加阴影效果，只能用于系统字体或 ttf 字体。

2019-03-18 07:27 UTC, jareguo commented on cocos2d/core/components/CCLabelShadow.js
> +        _color: cc.color(0, 0, 0, 255),
默认透明度太黑了，改成 128

2019-03-18 07:27 UTC, jareguo commented on cocos2d/core/components/CCLabelShadow.js
> +        _offset: cc.v2(2, 4),
2, 2

2019-03-18 07:27 UTC, jareguo commented on cocos2d/core/components/CCLabelShadow.js
> +                this._color = cc.color(value);
不需要转一次 color 吧……

2019-03-18 07:27 UTC, jareguo commented on cocos2d/core/components/CCLabelShadow.js
> +         * labelShadow.color = new cc.Color(0.5, 0.3, 0.7, 1.0);
你确定不是 1 - 255？

2019-03-18 07:27 UTC, jareguo commented on cocos2d/core/components/CCLabelShadow.js
> + *  node.parent = this.node;
默认文本是啥？不用设置一下吗

2019-03-18 07:27 UTC, jareguo commented on cocos2d/core/components/CCLabelShadow.js
> +         * !#zh 字体与阴影的偏移距离
注意文档，这里哪里是 distance 啊……

2019-03-18 07:27 UTC, jareguo commented on cocos2d/core/components/CCLabelShadow.js
> +            range: [0, Number.MAX_VALUE],
你现在的逻辑，用 min 就行了。不过我在想最大值可能得加个上限，不能比 fontSize 的上限还大，否则会崩坏的。

2019-03-18 07:27 UTC, jareguo commented on cocos2d/core/renderer/utils/label/ttf.js
> +let _isShadow = false;
语法不对，hasShadow 或者 enableShadow 或者 isShadowEnabled

2019-03-18 07:27 UTC, jareguo commented on cocos2d/core/renderer/utils/label/ttf.js
> +let _drawUnderlinewidth = 0;
Width 首字母大写

2019-03-18 07:27 UTC, jareguo commented on cocos2d/core/renderer/utils/label/ttf.js
> +        _marginRect = cc.rect(x, y, width, height);
你既然这里都 new 了一个 rect 了，干嘛不直接 getMarginRect... 要不然你就更新 marginRect 就好，别 new

2019-03-18 07:27 UTC, jareguo commented on cocos2d/core/renderer/utils/label/ttf.js
> +            height = width = 2 * _outlineWidth;
_outlineWidth * 2 比较正常，干嘛要反过来写

2019-03-18 07:27 UTC, jareguo commented on cocos2d/core/renderer/utils/label/ttf.js
> +            width += Math.abs((_shadowOffset.x + _shadowBlur) * 2);
为什么宽度要取绝对值，xy 就不用？

2019-03-18 07:27 UTC, jareguo commented on cocos2d/core/renderer/utils/label/ttf.js
> +            let italicWidth = _drawFontSize * Math.tan(12 * 0.0174532925);
0.0174532925 是啥？

2019-03-18 07:27 UTC, jareguo commented on cocos2d/core/renderer/utils/label/ttf.js
> +            x += italicWidth;
斜体怎么会影响到 x？？

2019-03-18 07:27 UTC, jareguo commented on cocos2d/core/renderer/utils/label/ttf.js
> +const SHADOW_SUPPORTED = cc.js.isChildClassOf(LabelShadow, Component);
干嘛不直接 SHADOW_SUPPORTED = !!cc. LabelShadow

2019-03-18 07:27 UTC, jareguo commented on cocos2d/core/renderer/utils/label/ttf.js
> +            _shadowColor = null;
为什么这些参数要存到全局变量里？直接存这个组件不就好了，运行时直接去组件上获取 shadow._color。

2019-03-18 07:27 UTC, jareguo commented on cocos2d/core/renderer/utils/label/ttf.js
> +            _shadowColor = cc.color(shadow.color);
为什么这里要不用 shadow._color ？要复制对象建议统一用 shadow._color.clone()

2019-03-18 07:27 UTC, jareguo commented on cocos2d/core/renderer/utils/label/ttf.js
> +            _shadowColor = cc.color(shadow.color);
为什么要把 _isShadow 这些存全局变量呢？直接存 _shadowComp 不行吗？

2019-03-18 07:27 UTC, jareguo commented on cocos2d/core/renderer/utils/label/ttf.js
> +        let shadowColor = _shadowColor || BLACK;
有可能颜色为空吗？如果有可能，在 _shadowColor 赋值的时候给默认值不是更好吗？

2019-03-18 07:27 UTC, jareguo commented on cocos2d/core/renderer/utils/label/ttf.js
> +    _openShadow: function (text) {
什么叫做 openShadow……

2019-03-18 07:27 UTC, jareguo commented on cocos2d/core/renderer/utils/label/ttf.js
> +        _context.strokeStyle = `rgba(${_color.r}, ${_color.g}, ${_color.b}, ${_color.a / 255})`;
这里应该是 fillStyle 吧

2019-03-18 07:27 UTC, jareguo commented on cocos2d/core/renderer/utils/label/ttf.js
> +            _context.lineWidth = _outlineWidth * 2;
建议把上面三行代码放到单独的 setupOutline()

2019-03-18 07:27 UTC, jareguo commented on cocos2d/core/renderer/utils/label/ttf.js
> +        _context.lineWidth = _outlineWidth * 2;
建议把上面三行代码放到单独的 setupOutline()

2019-03-18 07:27 UTC, jareguo commented on cocos2d/core/renderer/utils/label/ttf.js
> +        if (!_isOutlined) {
为什么要有这个判断？

2019-03-18 07:27 UTC, jareguo commented on cocos2d/core/renderer/utils/label/ttf.js
> +                let scaleX = (_canvasSize.width - 2 * _marginRect.width) / maxLength;
这里为什么还要 * 2？

2019-03-19 03:18 UTC, jareguo commented on cocos2d/core/renderer/utils/label/ttf.js
> +        let _drawColor = _isOutlined ? _outlineColor : _color;
_drawColor -> _fillColor ，更准确一些

2019-03-19 03:18 UTC, jareguo commented on cocos2d/core/components/CCLabelShadow.js
> +            range: [0, Number.MAX_VALUE],
我之前是说你现在的逻辑用 min 就行了…… 因为你上限是 max。不过我觉得你应该像 FontSize 一样，限制最大值为 1024。所以还是用 range，把 max 换成 1024 就好了。其它会影响到 canvas size 的参数也是一样

2019-03-19 03:19 UTC, jareguo commented on cocos2d/core/components/CCLabelOutline.js
> +            range: [0, Number.MAX_VALUE],
我之前是说你现在的逻辑用 min 就行了…… 因为你上限是 max。不过我觉得你应该像 FontSize 一样，限制最大值为 1024。所以还是用 range，把 max 换成 1024 就好了。其它会影响到 canvas size 的参数也是一样

2019-03-19 03:37 UTC, jareguo commented on cocos2d/core/renderer/utils/label/ttf.js
> +                this._drawOutlineText(_splitedStrings[i]);
建议不封装 _drawOutlineText，就两行代码放进来更清晰，像画 shadow 那样

2019-03-19 03:37 UTC, jareguo commented on cocos2d/core/renderer/utils/label/ttf.js
> +            _canvasSize.height = parseFloat(canvasSizeY.toFixed(2)) + _marginRect.height;
看到这重构后的代码，心情好愉悦

2019-03-19 03:37 UTC, jareguo commented on modules.json
> +    "name": "Label Effect",
有个问题，旧项目升上来后，会继承这个 LabelOutline 属性吗？有类似 id 这样的东西，或者 formerlySerializedAs，或者 displayName 这样的东西来做向前兼容吗？

2019-03-20 01:17 UTC, knoxHuang commented on cocos2d/core/renderer/utils/label/ttf.js
> +            width += Math.abs((_shadowOffset.x + _shadowBlur) * 2);
宽度只是设置 canvs 的宽高，xy 不需要

2019-03-20 01:17 UTC, knoxHuang commented on cocos2d/core/renderer/utils/label/ttf.js
> +            let italicWidth = _drawFontSize * Math.tan(12 * 0.0174532925);
一个是保留之前的修改，我没动

2019-03-20 01:30 UTC, knoxHuang commented on cocos2d/core/renderer/utils/label/ttf.js
> +            width += Math.abs((_shadowOffset.x + _shadowBlur) * 2);
宽度只是设置 canvs 的宽高，xy 不需要

2019-03-21 03:54 UTC, jareguo commented on cocos2d/core/renderer/webgl/assemblers/label/2d/ttf.js
> +        let shadow = SHADOW_SUPPORTED && comp.getComponent(LabelShadow);
感觉 SHADOW_SUPPORTED 这个变量没啥意义啊？直接 let shadow = LabelShadow && comp.getComponent(LabelShadow); 不是更清晰吗？
（除非你是用其它办法来判断了当前系统是否支持绘制描边）

2019-03-21 09:23 UTC, jareguo commented on cocos2d/core/renderer/webgl/assemblers/label/2d/ttf.js
> +            if (shadow.blur > 0) {
blur = 0 不也有 offset 的需求吗？如果不是的话，上两个 if 合并一下吧，减少个缩进

2019-03-21 09:23 UTC, jareguo commented on cocos2d/core/renderer/webgl/assemblers/label/2d/ttf.js
> +                let offsetX = (comp._ttfTexture.width - node.width) / 2;
comp._ttfTexture.width 不就是 width 么？直接用 width 吧

2019-03-21 10:52 UTC, caryliu1999 commented on cocos2d/core/renderer/utils/label/ttf.js
> +            node._contentSize = cc.size(rawWidth + _contentSizeExtend.width, rawHeight);
设置节点的contentSize时需要加上_canvasPadding的width和height，只在设置canvasSize时叠加了，这样node的size就不会随着描边还有阴影的宽度增加动态变化。这个contentSize的设置还是通过setContentSize方法来修改吧，不要在外部去访问_contentSize.

2019-03-21 11:31 UTC, jareguo commented on cocos2d/core/renderer/utils/label/ttf.js
> +            node._contentSize = cc.size(rawWidth + _contentSizeExtend.width, rawHeight);
> 这样node的size就不会随着描边还有阴影的宽度增加动态变化

阴影这边其实是故意的，经过再三权衡，还是决定阴影完全不影响 node 的 size，比较有利于排版

2019-03-22 03:54 UTC, jareguo commented on cocos2d/core/renderer/utils/label/ttf.js
> +                _drawTextPos.x = startPosition.x;
_drawTextPos 没有放到全局变量的必要啊，完全是这个函数内部使用的，直接换成 var x, y 就好了

2019-03-22 03:55 UTC, jareguo approved these changes

2019-03-25 11:03 UTC, caryliu1999 commented on cocos2d/core/renderer/utils/label/ttf.js
> +    _drawUnderline: function (text, underlinewidth) {
text这个参数在方法里没有用到，删掉吧。

2019-03-25 11:04 UTC, caryliu1999 commented on cocos2d/core/renderer/utils/label/ttf.js
>          _context.clearRect(0, 0, _canvas.width, _canvas.height);
comp参数在方法里没有用到，删掉吧

2019-03-25 11:10 UTC, caryliu1999 commented on cocos2d/core/renderer/utils/label/ttf.js
> +
_context.save() 跟  _context.restore() 在某些平台的性能消耗还是比较大的，而且大部分情况下不使用描边跟阴影，还是会调用这两个api，这里看能不能尽量不使用这两个API，如果会把逻辑复杂化的化必须要使用的话，看能否在普通情况下不调用。

2019-03-25 11:14 UTC, caryliu1999 commented on cocos2d/core/renderer/utils/label/ttf.js
>              }
这里有问题吧？如果有描边的情况下判断使用strokeText，阴影只画了外框，没有再继续绘制文字了

2019-03-25 11:19 UTC, caryliu1999 commented on cocos2d/core/renderer/utils/label/ttf.js
这里的循环太多了，看能不能把一些相同的绘制合并一下，能共用canvas状态的尽量共用吧，现在文本的性能瓶颈主要是在首次绘制了，如果这里比较复杂的话，界面上的文本同一时间绘制，还是很耗性能的，可以用console.time测试一下这部分的耗时。

2019-03-25 14:58 UTC, jareguo commented on cocos2d/core/renderer/utils/label/ttf.js
> +
判断下如果没有阴影就不调用呗

2019-03-27 01:53 UTC, knoxHuang commented on cocos2d/core/renderer/utils/label/ttf.js
>              }
![image](https://user-images.githubusercontent.com/7564028/55044669-33630080-5076-11e9-9d43-06c23ea53380.png)

你看看效果是否正确

2019-03-28 02:30 UTC, caryliu1999 commented on cocos2d/core/renderer/utils/label/ttf.js
阴影的绘制其实只需要设置shadow相关的参数就好了，后续的fillRect, strokeText, fillText都会生成对应的阴影，不需要把所有的操作都绘制两次，所以只需要判断有无阴影来决定需不需要设置阴影的相关参数就好了，其他的绘制只需要绘制一次，也不需要context.save 和 context.restore的调用，初始的时候设置context.shadowColor = "transparent"，就可以取消阴影。

2019-03-28 06:16 UTC, caryliu1999 approved these changes
阴影单行绘制时可以不需要绘制两遍文字，多行时需要绘制两遍来避免阴影重叠到上一行文本。

2019-04-01 06:17 UTC, 2youyou2 commented on cocos2d/core/components/CCLabel.js
> +            range: [0, 1024],
fontSize 能到 1024 这么大？

2019-04-02 14:27 UTC, pandamicro requested changes

2019-04-02 14:27 UTC, pandamicro commented on cocos2d/core/renderer/utils/label/ttf.js
> +        _context.lineWidth = _outlineComp.width * 2;
为啥要乘以 2？

2019-04-02 14:27 UTC, pandamicro commented on cocos2d/core/renderer/utils/label/ttf.js
> +        for (let i = 0; i < _splitedStrings.length; ++i) {
原本 outline, underline, text 都是在同一个 for 循环中绘制的，比分散在三个 for 循环中要高效

2019-04-02 14:27 UTC, pandamicro commented on cocos2d/core/renderer/utils/label/ttf.js
> +                _context.fillText(_splitedStrings[i], drawTextPosX, drawTextPosY);
本来 canvas 2d context 就有 shadowColor, shadowBlur, shadowOffsetX, shadowOffsetY，为啥要再画一次？？？

就算是为了避免和 stroke 冲突，可以先 fillText，再 strokeText 就可以了呀

2019-04-02 14:48 UTC, caryliu1999 commented on cocos2d/core/renderer/utils/label/ttf.js
> +                _context.fillText(_splitedStrings[i], drawTextPosX, drawTextPosY);
文本只有单行的情况下所有的绘制只做一次就可以了，多行的时候由于fillText是多次调用，阴影向上偏移的情况下，后面绘制的阴影跟上一层的文本在层级上会有冲突，所以后面第二次绘制的文本相当于是在最上层又绘制一遍文字保证每一行都覆盖在阴影上面，对于文本只有单行的时候有点多余。

2019-04-03 06:09 UTC, pandamicro commented on cocos2d/core/renderer/utils/label/ttf.js
> +                    if (_outlineComp) {
和前面的 if 合并

2019-04-03 06:09 UTC, pandamicro commented on cocos2d/core/renderer/utils/label/ttf.js
>              _context.shadowColor = 'transparent';
如果不是 multiple，要在最后将 shadow 的设置清空，包含 color，blur，offset，这里也应该将 blue 清理掉，否则不确定是否会有额外开销

2019-04-03 06:11 UTC, pandamicro commented on cocos2d/core/renderer/utils/label/ttf.js
> +            this._setupOutline();
这就不止一个了，前面你不是设置过 outline 了么，貌似不应该放在 shadowComp 判断里面

2019-04-03 08:59 UTC, pandamicro approved these changes

2019-04-03 08:59 UTC, merged

2019-04-03 09:02 UTC, pandamicro commented
conversation 超过 50 的 PR 被合并是不是要庆祝一下。。。。 🤣