do not update when the opacity of label changed and limit max size of ttf.
cocos/cocos-engine pull request #4047
Opened 2019-03-15 07:09 UTC by caryliu1999

Re: cocos-creator/2d-tasks#1224

2019-03-15 07:29 UTC, pandamicro requested changes

2019-03-15 07:29 UTC, pandamicro commented on cocos2d/core/components/CCLabel.js
> +        else if (!(this.node._renderFlag & RenderFlow.FLAG_OPACITY)) {
如果判断是 opacity flag，要将 flag 重置，避免持续进入 updateColor 逻辑

2019-03-15 11:04 UTC, caryliu1999 commented on cocos2d/core/components/CCLabel.js
> +        else if (!(this.node._renderFlag & RenderFlow.FLAG_OPACITY)) {
已修改，之前的flag判定有问题。

2019-03-19 09:29 UTC, jareguo commented on cocos2d/core/components/CCLabel.js
> +                this.node._renderFlag &= ~opacityFlag;
如果有 FLAG_COLOR，这里就会去掉 FLAG_COLOR，貌似不对吧？

2019-03-25 10:13 UTC, caryliu1999 commented on cocos2d/core/components/CCLabel.js
> +                this.node._renderFlag &= ~opacityFlag;
是会把FLAG_COLOR给去掉，这里还是不动了，把节点透明度变化时的render flag设置改了。之前节点透明度变化也会加上COLOR的标记位，看修改记录是因为透明度变化时（设置为0，再设置回255）layout节点不显示，但是现在测试是没问题的，之前应该不是这个原因导致的。这样修改避免文本透明度动画时，不断的进行文本重绘。

2019-03-25 14:59 UTC, jareguo approved these changes

2019-03-26 14:32 UTC, pandamicro approved these changes

2019-03-26 14:32 UTC, merged