fixed component use last component's material when clone node
cocos/cocos-engine pull request #4061
Opened 2019-03-19 02:31 UTC by 2youyou2

Re: cocos-creator/2d-tasks#1226

Changes:
 * fixed component use last component's material when clone node

2019-03-19 02:37 UTC, 2youyou2 commented on cocos2d/core/components/CCSprite.js
> -            if (this._state === State.GRAY) {
用什么材质应该外部来设置，否则 sprite 很难判断用哪个材质

2019-03-19 02:48 UTC, 2youyou2 commented on cocos2d/core/components/CCLabel.js
> +                material = Material.getInstantiatedMaterial(material, this);
这些会设置自己属性的 render component 都应该创建出属于自己的材质实例

2019-03-27 03:09 UTC, pandamicro commented
看了一下原帖，问题应该就是 clone 的时候直接共享了 mateiral 引用，那么应该在 clone 的时候处理就可以了，现在这种处理方式无脑在 activateMateiral 调用的时候重新创建材质肯定是不合理的，应该更严谨得控制 instantiate material 的时机才对。

2019-03-27 03:09 UTC, pandamicro requested changes

2019-03-27 03:09 UTC, pandamicro commented on cocos2d/core/components/CCLabel.js
> +                material = Material.getInstantiatedMaterial(material, this);
这会导致重复创建吧，activateMaterial 的调用不是那么严谨，如果没次都重新创建可能导致垃圾比较多

2019-03-27 06:51 UTC, 2youyou2 commented on cocos2d/core/components/CCLabel.js
> +                material = Material.getInstantiatedMaterial(material, this);
不会无脑创建，创建一次之后 material.owner 就是自身了，只会创建一次

2019-04-01 11:42 UTC, pandamicro approved these changes

2019-04-01 11:42 UTC, merged