Add a warning by detecting  the maximum texture size in device
cocos/cocos-engine pull request #4121
Opened 2019-04-01 02:47 UTC by ColinCollins

Re: https://github.com/cocos-creator/2d-tasks/issues/1223

添加当前设备最大支持纹理尺寸检测与警告

2019-04-01 02:50 UTC, 2youyou2 commented on cocos2d/renderer/gfx/texture-2d.js
> +        console.warn('The current texture exceeds the maximum size supported on the device.');
把 maximum size 也打印出来吧

```js
console.warn(`The current texture exceeds the maximum size [${maxSize}] supported on the device.`);
```

2019-04-01 03:41 UTC, ColinCollins commented on cocos2d/renderer/gfx/texture-2d.js
> +        console.warn('The current texture exceeds the maximum size supported on the device.');
好

2019-04-01 06:14 UTC, 2youyou2 approved these changes

2019-04-02 08:02 UTC, pandamicro requested changes

2019-04-02 08:02 UTC, pandamicro commented on cocos2d/renderer/gfx/texture-2d.js
> +        console.warn(`The current texture size ${textureMaxSize} exceeds the maximum size [${maxSize}] supported on the device.`);
不应该写在 constructor 里面，应该写在 update 函数里面

2019-04-03 02:12 UTC, ColinCollins commented on cocos2d/renderer/gfx/texture-2d.js
> +        console.warn(`The current texture size ${textureMaxSize} exceeds the maximum size [${maxSize}] supported on the device.`);
已调整

2019-04-03 03:35 UTC, pandamicro requested changes

2019-04-03 03:35 UTC, pandamicro commented on cocos2d/renderer/gfx/texture-2d.js
> +    let textureMaxSize = Math.max(options.width, options.height);
options 不一定存在的，要写在 options 判断里面。。。

2019-04-03 03:37 UTC, ColinCollins commented on cocos2d/renderer/gfx/texture-2d.js
> +    let textureMaxSize = Math.max(options.width, options.height);
哦哦，看到了，没考虑到那几个特殊的

2019-04-03 11:11 UTC, ColinCollins commented
1. !options.width  skinJoint：
![image](https://user-images.githubusercontent.com/35832931/55467541-1c9f4980-5634-11e9-8477-a189fbdbc5be.png)
options 传入数据不对应格式
2.  webgl 2.0 don't have max_texture_size prop

2019-04-04 01:54 UTC, pandamicro requested changes

2019-04-04 01:54 UTC, pandamicro commented on cocos2d/renderer/gfx/texture-2d.js
> +      let maxSize = gl.MAX_TEXTURE_SIZE ? gl.getParameter(gl.MAX_TEXTURE_SIZE) : 2048;
如果获取不到 gl parameter，就不应该限制

2019-04-04 02:42 UTC, pandamicro approved these changes

2019-04-04 02:44 UTC, merged