refine mask implement
cocos/cocos-engine pull request #4126
Opened 2019-04-02 09:15 UTC by 2youyou2

Re: cocos-creator/2d-tasks#1277

Changes:
 * refine mask implement

2019-04-02 09:16 UTC, 2youyou2 commented on cocos2d/core/renderer/webgl/model-batcher.js
> +    _flushMaterial (material) {
添加 _flushMaterial 是为了只设置 gl state，不调用 gl draw

2019-04-02 11:42 UTC, pandamicro requested changes

2019-04-02 11:42 UTC, pandamicro commented on cocos2d/renderer/gfx/enums.js
> +  STENCIL_DISABLE: 2,             // disable stencil
disable 为 0，enable 为 1，inherit 为 2，这样和之前的版本值是兼容的

2019-04-02 11:42 UTC, pandamicro commented on cocos2d/core/renderer/webgl/assemblers/mask-assembler.js
> +function applyScreenMask (mask, renderer) {
applyClearMask

2019-04-03 03:32 UTC, pandamicro approved these changes

2019-04-03 03:34 UTC, merged