Optimize event manager.
cocos/cocos-engine pull request #4209
Opened 2019-04-12 09:20 UTC by caryliu1999

Re: cocos-creator/2d-tasks#1243

具体说明见task。

2019-04-19 02:30 UTC, 2youyou2 commented on cocos2d/core/CCNode.js
> +        _renderQueue: 0,
这是运行时属性，不用序列化吧，可以改到 constructor 中

2019-04-19 03:23 UTC, caryliu1999 commented on cocos2d/core/CCNode.js
> +        _renderQueue: 0,
不需要序列化，我改一下。

2019-05-05 10:54 UTC, pandamicro requested changes

2019-05-05 10:54 UTC, pandamicro commented on cocos2d/core/CCNode.js
> +        this._renderQueue = 0;
建议将 _renderQueue 控制在它的使用者 EventManager 层面。可以在 EventManager 中添加

1. _renderOrderMap 记录节点 uuid 到 renderOrder 的映射
2. updateRenderOrder 提供给渲染器更新 renderOrder 的方法（可以过滤没有注册监听器的节点）

这样跟事件相关的渲染顺序就可以完全被容纳在 EventManager 内部，不需要扩散到 Node 的属性上。在没有其他需求的情况下，我们尽量克制不要给 Node 添加属性

2019-05-06 06:58 UTC, caryliu1999 commented on cocos2d/core/CCNode.js
> +        this._renderQueue = 0;
已修改测试

2019-05-06 09:13 UTC, pandamicro approved these changes

2019-05-06 09:14 UTC, merged