fix add CanvasComponent undo bug
cocos/cocos-engine pull request #4260
Opened 2019-04-19 08:31 UTC by JoneLau

2019-04-19 08:46 UTC, pandamicro approved these changes

2019-04-19 08:47 UTC, pandamicro requested changes

2019-04-19 08:47 UTC, pandamicro commented on cocos/components/component.ts
> +                this._enabled = false;
这个不能改，这是用户属性，不能自动设置

2019-04-22 02:11 UTC, JoneLau commented on cocos/components/component.ts
> +                this._enabled = false;
现在是移除一个组件的时候不会走 _enabled = false，那这样 undo 的时候 enabled = true 也没有用，不可能让编辑器这样 _enabled = false, enabled = true 做吧

2019-04-22 08:32 UTC, pandamicro approved these changes

2019-04-22 08:32 UTC, merged