[WIP] remove CC_WECHATGAME
cocos/cocos-engine pull request #4287
Opened 2019-04-24 03:00 UTC by umbrellaPP

https://github.com/cocos-creator/2d-tasks/issues/1360

- [x] 移除 CC_WECHATGAME
- [ ] 移除 CC_QQPLAY
- [ ] 移除 isBaiduGame 的判断

2019-05-07 03:34 UTC, pandamicro requested changes

2019-05-07 03:34 UTC, pandamicro commented on cocos2d/audio/CCAudio.js
> +        });
将这一部分代码单独拆分出来作为一个函数：_touchToPlay，然后在小游戏平台中空实现。

这样做的好处是，正常的播放代码维护不会影响到所有小游戏平台的代码

2019-05-07 03:34 UTC, pandamicro commented on cocos2d/audio/CCAudio.js
> -        }
同上：_rebindEnded

2019-05-07 03:34 UTC, pandamicro commented on cocos2d/audio/CCAudio.js
> -                if (!(CC_QQPLAY || CC_WECHATGAME) && self._context.currentTime === 0) {
同上，这个函数主体的代码太多，如果在小游戏平台上都分别实现，会导致维护成本和潜在问题增加

2019-05-07 03:34 UTC, pandamicro commented on cocos2d/core/components/WXSubContextView.js
> -if (!CC_EDITOR && !CC_WECHATGAME) {
在构件流程中做模块剔除，思考一下不存在组件类型的情况下会不会有额外的问题

2019-05-07 03:34 UTC, pandamicro commented on cocos2d/core/platform/CCInputManager.js
>      getHTMLElementPosition (element) {
将这个函数的返回值控制为返回固定的缓存对象

2019-05-07 03:34 UTC, pandamicro commented on cocos2d/core/platform/CCView.js
> -            locContainer.style.height = locCanvas.style.height = h + 'px';
单独写一个 _setupStyle 把，这些代码在 web 端仍然是需要的，不应该删除，在小游戏平台空实现 _setupStyle 就好

2019-05-07 03:34 UTC, pandamicro commented on predefine.js
> +                    recommandedUsage = 'cc.sys.browserType === cc.sys.BROWSER_TYPE_WECHAT_GAME_SUB';
这个也应该是一个 platform

2019-05-07 05:43 UTC, umbrellaPP commented on predefine.js
> +                    recommandedUsage = 'cc.sys.browserType === cc.sys.BROWSER_TYPE_WECHAT_GAME_SUB';
这里我加多一个 platform 字段

2019-05-07 10:34 UTC, umbrellaPP commented on cocos2d/core/platform/CCView.js
> -            locContainer.style.height = locCanvas.style.height = h + 'px';
这部分应该是保留的，我误删了

2019-05-28 11:13 UTC, umbrellaPP commented on cocos2d/audio/CCAudio.js
> -        }
setCurrentTime 接口差异比较大，我整个直接适配了

2019-05-28 11:17 UTC, umbrellaPP commented on cocos2d/audio/CCAudio.js
> -                if (!(CC_QQPLAY || CC_WECHATGAME) && self._context.currentTime === 0) {
WebAudio 不需要适配，微信小游戏上直接用 innerAudioContext
可以看  Audio._createElement 接口

2019-05-28 11:18 UTC, umbrellaPP commented on cocos2d/core/platform/CCInputManager.js
>      getHTMLElementPosition (element) {
web 平台没办法做这个优化，因为需要考虑 body.scrollTop , 会修改 position 的原始数据，只能每次都创建一份拷贝

2019-05-29 05:09 UTC, pandamicro requested changes

2019-05-29 05:09 UTC, pandamicro commented on cocos2d/core/platform/CCInputManager.js
>      getHTMLElementPosition (element) {
那边再额外缓存一个不就好了，这个问题肯定可以解决，想想办法

2019-05-29 05:09 UTC, pandamicro commented on cocos2d/core/platform/CCView.js
> -            locContainer.style.height = locCanvas.style.height = h + 'px';
还是没还原啊

2019-05-29 05:09 UTC, pandamicro commented on predefine.js
> +                    recommandedUsage = 'cc.sys.browserType === cc.sys.BROWSER_TYPE_WECHAT_GAME_SUB';
没看到修改

2019-05-29 05:16 UTC, pandamicro commented on cocos2d/core/components/WXSubContextView.js
> +
增加了很多无意义的空行修改，回退掉

2019-05-30 04:06 UTC, pandamicro requested changes

2019-05-30 04:06 UTC, pandamicro commented on cocos2d/core/platform/CCView.js
> +    }
完全没必要放在 view 里面啊，就是 inputManager 里面存就好了，view 不关心触点转换的过程，而且这些结构在其他平台也是可以根据 InputManager 实现简化的，但是 view 是通用的。

另外这个结构可以简化为

```
boundingRect = {
    left: 0,
    top: 0,
    adjustedLeft: 0,
    adjustedTop: 0,
    width: 0,
    height: 0
}
```

2019-06-03 03:21 UTC, pandamicro approved these changes

2019-06-11 06:41 UTC, 2youyou2 commented on cocos2d/core/platform/CCView.js
> +        _cc.inputManager._updateCanvasBoundingRect();
_cc 是什么？

2019-06-13 02:37 UTC, 2youyou2 commented on cocos2d/core/platform/CCView.js
> +        _cc.inputManager._updateCanvasBoundingRect();
如果 cc.inputManager 对外废弃，只限引擎使用的话，应该是改为 cc._inputManager 标明是引擎的私有变量

2019-06-13 02:37 UTC, merged