update the 3d-docs build workflow
cocos/cocos-engine pull request #4300
Opened 2019-04-25 06:00 UTC by ColinCollins

Re: https://github.com/cocos-creator/3d-tasks/issues/531
修改了构建流程脚本，调整构建命令。

2019-04-25 06:03 UTC, ColinCollins commented
Re: https://github.com/cocos-creator/typedoc/pull/5
Re: https://github.com/cocos-creator/typedoc-plugin-localization/pull/1

2019-04-26 06:17 UTC, merged

2019-04-29 05:46 UTC, jareguo requested changes

2019-04-29 05:46 UTC, jareguo commented on gulpfile.js
> +const DocsBuilder = require('./gulp/util/docs-build');
这些 Docs 统一叫 API，免得和手册搞混

2019-04-29 05:46 UTC, jareguo commented on gulpfile.js
> +gulp.task('build-3d-json-file', function () {
build-api-json

2019-04-29 05:46 UTC, jareguo commented on gulpfile.js
> +    DocsBuilder.tempJsonGenerate();
generateJson

2019-04-29 05:46 UTC, jareguo commented on gulpfile.js
> +    DocsBuilder.docsGeneratorDefault();
为什么要加上 Default？直接 generateHtml 不就好了

2019-04-29 05:46 UTC, jareguo commented on gulp/util/docs-build.js
> +        .parse(process.argv);
这是在哪用到的？没看到呀。就这么一个参数，直接 process.argv[2] 就行了吧

2019-04-29 05:46 UTC, jareguo commented on gulp/util/docs-build.js
> +    en: `${process.cwd()}/docs-3d/en`
确定这个路径在 Windows 上不会出错？

2019-04-29 05:46 UTC, jareguo commented on gulp/util/docs-build.js
> +    let command = [
commands

2019-04-29 05:46 UTC, jareguo commented on gulp/util/docs-build.js
> +        shell: true,
为什么需要 shell 为 true？

2019-04-29 05:46 UTC, jareguo commented on gulp/util/docs-build.js
> +        env: process.env,
env 需要特殊指定？？

2019-04-29 05:46 UTC, jareguo commented on gulp/util/docs-build.js
> +function executeTypeDocCommand (child) {
这个函数哪有 execute？

2019-04-29 05:46 UTC, jareguo commented on gulp/util/docs-build.js
> +        console.warn(`Rendering is short of the relied file`);
具体点吧，Render 啥？rely 啥？

2019-04-29 05:46 UTC, jareguo commented on gulpfile.js
> +gulp.task('build-3d-json-file', function () {
这个步骤是干嘛用的？？？为啥要单独生成 json

2019-04-29 05:48 UTC, jareguo commented on gulp/util/docs-build.js
> +const outputPath = {
输出目录是写死的？难道不是应该可以配置吗？否则怎么上传到服务器的 svn