Some core code modify to TS ( core/data/... ) ( bug fixed )
cocos/cocos-engine pull request #4466
Opened 2019-05-21 08:18 UTC by LinYunMo

RE: https://github.com/cocos-creator/3d-tasks/issues/576
部分核心代码改写为 TypeScript ，包括 core/data 文件夹下的部分

2019-05-21 10:33 UTC, holycanvas commented on cocos/core/data/object.ts
>      prototype._serialize = null;
ts里这样定义函数好像会存在问题，我昨天测试的时候发现，子类比如SpriteFrame想要重写_serialize是不成功的，需要测试一下
![image](https://user-images.githubusercontent.com/15109777/58089164-b5931f80-7bf6-11e9-8ec6-6cd7e15362e3.png)

2019-05-21 11:25 UTC, LinYunMo commented on cocos/core/data/object.ts
>      prototype._serialize = null;
![image](https://user-images.githubusercontent.com/42071583/58092194-0a866400-7bfe-11e9-8adf-b1849d0be674.png)
这样应该是可以成功的吧？我刚刚测试了一下

2019-05-21 11:36 UTC, pandamicro requested changes

2019-05-21 11:36 UTC, pandamicro commented on cocos/2d/actions/CCActionManager.js
> -     * @method removeAction
不要改这个文件

2019-05-21 11:36 UTC, pandamicro commented on cocos/core/data/class.ts
> +CCClass.getNewValueTypeCode = (CC_SUPPORT_JIT && getNewValueTypeCodeJit) as ((value: any) => string);
(value: any) => string 是什么意思

2019-05-21 11:36 UTC, pandamicro commented on cocos/core/data/instantiate-jit.ts
> +        // tslint:disable-next-line: no-shadowed-variable
这里为啥需要忽略 shadow variable？

2019-05-21 11:36 UTC, pandamicro commented on cocos/core/data/object.ts
> +    // tslint:disable: max-line-length
这些能不能写到文件夹的 tsconfig 中？

2019-05-21 11:36 UTC, pandamicro commented on cocos/core/data/object.ts
> +    js.get(prototype, 'isRealValid', () => {
这个形式保留 function () {} 会有什么问题？

2019-05-21 11:36 UTC, pandamicro commented on cocos/core/data/object.ts
> +        return !(prototype._objFlags & RealDestroyed);
这里写 prototype 不对，实际上是对象本身的 _objFlags property

2019-05-21 11:36 UTC, pandamicro commented on cocos/core/data/object.ts
> +        if ( !(prototype._objFlags & Destroyed) ) {
同上，这么写是错误的

2019-05-22 06:57 UTC, LinYunMo commented on cocos/2d/actions/CCActionManager.js
> -     * @method removeAction
之前在更改 director 时用到 cc.ActionManager ，会报此类没有导出的错误，所以添加了导出，但这次恢复之后并没有报错，可能是类型检查的 Bug ，已将文件恢复。

2019-05-22 07:12 UTC, LinYunMo commented on cocos/core/data/class.ts
> +CCClass.getNewValueTypeCode = (CC_SUPPORT_JIT && getNewValueTypeCodeJit) as ((value: any) => string);
因为 CC_SUPPORT_JIT && getNewValueTypeCodeJit 的类型为 false | ((value: any) => string) ，这样 instantiate-jit.ts 在调用 CCClass.getNewValueTypeCode(obj);  时会报错 “无法调用类型缺少调用签名的表达式”，所以将其类型变为 getNewValueTypeCodeJit 的类型，也就是 (value: any) => string

2019-05-22 07:20 UTC, LinYunMo commented on cocos/core/data/object.ts
> +    js.get(prototype, 'isRealValid', () => {
![image](https://user-images.githubusercontent.com/42071583/58154761-f47fae80-7ca4-11e9-8560-e3ef543ff7a8.png)
会有一个 tslint 的警告

2019-05-26 14:12 UTC, pandamicro requested changes

2019-05-26 14:12 UTC, pandamicro commented on cocos/core/data/object.ts
> +        for (const key of propList) {
我不是很确定 for of 在 ES5 编译后的结果是什么，麻烦确认一下，如果是足够高性能的方式 ok。
对所有 ES5 不支持的语法都要注意，它们被编译后的结果是什么，并且关注它们的执行性能和可能存在的问题

2019-05-26 14:12 UTC, pandamicro commented on cocos/core/director.ts
> +import ActionManager from '../2d/actions/CCActionManager';
才想起来 3D 中没有 ActionManager 目前，都没有适配，麻烦删掉 require 和 director 中的 actionManager 执行逻辑

2019-05-26 14:12 UTC, pandamicro commented on cocos/load-pipeline/CCLoader.ts
> +        for (const id of Object.keys(this._cache)) {
这样改会导致临时数组的产生，注意代码中创建的一切临时对象，尽可能避免不必要的临时对象产生。所以不如直接用 for in

2019-05-28 03:54 UTC, pandamicro approved these changes

2019-05-28 03:55 UTC, merged