Fix builtin physic engine bug
cocos/cocos-engine pull request #4482
Opened 2019-05-22 12:12 UTC by JayceLai

Re: cocos-creator/3d-tasks#536

Changes:
 * fix bug of setWorld function in builtin physic engine

2019-05-23 06:46 UTC, shrinktofit requested changes

2019-05-23 06:46 UTC, shrinktofit commented on cocos/3d/physics/cocos/built-in-body.ts
> +            this._world!.removeBody(this);
else的时候this._world不是null吗？

2019-05-23 07:28 UTC, JayceLai commented on cocos/3d/physics/cocos/built-in-body.ts
> +            this._world!.removeBody(this);
> else的时候this._world不是null吗？

嗯嗯，少了判断this._world是不是为null

2019-05-24 02:22 UTC, shrinktofit approved these changes

2019-05-24 02:23 UTC, merged