adjust deferred loading
cocos/cocos-engine pull request #4521
Opened 2019-05-29 10:32 UTC by holycanvas

Re: cocos-creator/3d-tasks#

Changes:
 * 调整延迟加载，使上层不用关注资源加载过程，资源会先进行正常的初始化，在加载真正资源后进行替换或覆盖操作

2019-05-29 10:32 UTC, holycanvas commented
@pandamicro 麻烦panda看下

2019-05-30 01:13 UTC, jerrywwl requested changes

2019-05-30 01:13 UTC, jerrywwl commented on cocos/gfx/webgl/webgl-commands.ts
> +                            gl.compressedTexImage2D(WebGL2RenderingContext.TEXTURE_2D, 0, gpuTexture.glInternelFmt, 2, 2, 0, view);
这里是WebGLRenderingContext，不是WebGL2RenderingContext

2019-05-30 01:13 UTC, jerrywwl commented on cocos/gfx/webgl/webgl-commands.ts
> +                            gl.compressedTexImage2D(WebGL2RenderingContext.TEXTURE_CUBE_MAP_POSITIVE_X + f, 0, gpuTexture.glInternelFmt, 2, 2, 0, view);
这里也是WebGLRenderingContext

2019-05-30 01:32 UTC, holycanvas commented on cocos/gfx/webgl/webgl-commands.ts
> +                            gl.compressedTexImage2D(WebGL2RenderingContext.TEXTURE_CUBE_MAP_POSITIVE_X + f, 0, gpuTexture.glInternelFmt, 2, 2, 0, view);
嗯嗯

2019-05-30 03:30 UTC, pandamicro commented on cocos/3d/assets/mesh.ts
> +                        ib.set(new (getIndexStrideCtor(idxView.stride))(this.data!.buffer, idxView.offset, idxView.count));
这里没必要 new 一个把，能不能单独将 buffer set 到 ib 里面去

2019-05-30 03:30 UTC, pandamicro commented on cocos/3d/assets/mesh.ts
> +                    positions = new Float32Array(info.view.length / 4);
如果创建一个长度为0 的会怎么样？

2019-05-30 03:30 UTC, pandamicro commented on cocos/3d/assets/mesh.ts
> +                        positions!.set(new Float32Array(this.data!.buffer, info.view.offset, info.view.length / 4));
应该直接赋值把

2019-05-30 03:30 UTC, pandamicro commented on cocos/gfx/webgl/webgl-commands.ts
> +                            gl.compressedTexImage2D(WebGLRenderingContext.TEXTURE_2D, 0, gpuTexture.glInternelFmt, 2, 2, 0, view);
这段代码的意义是》？

2019-05-30 03:41 UTC, jerrywwl approved these changes

2019-05-30 07:03 UTC, holycanvas commented on cocos/3d/assets/mesh.ts
> +                        ib.set(new (getIndexStrideCtor(idxView.stride))(this.data!.buffer, idxView.offset, idxView.count));
我测了一下，不行，因为buffer太大，会报source is too large的错，set方法也没有count参数能用
![image](https://user-images.githubusercontent.com/15109777/58614597-65e5df80-82eb-11e9-912a-c98367b31d97.png)，所以需要用一个ArrayBufferView来控制要set的大小

2019-05-30 07:10 UTC, holycanvas commented on cocos/gfx/webgl/webgl-commands.ts
> +                            gl.compressedTexImage2D(WebGLRenderingContext.TEXTURE_2D, 0, gpuTexture.glInternelFmt, 2, 2, 0, view);
因为之前etc纹理在初始化时只创建了纹理，没有内容，在延迟加载时，会有很多帧渲染的都是这张没有内容的图，这段时间会报很多gl的错，所以这段代码的目的是初始化etc的时候先初始化为2x2的纯黑图片，保证在延迟加载时不会报错

2019-05-30 07:17 UTC, holycanvas commented on cocos/3d/assets/mesh.ts
> +                    positions = new Float32Array(info.view.length / 4);
同上，如果创建长度为0的ArrayBufferView，在set的时候也会报source is too large的错

2019-05-30 07:21 UTC, holycanvas commented on cocos/3d/assets/mesh.ts
> +                        positions!.set(new Float32Array(this.data!.buffer, info.view.offset, info.view.length / 4));
这里不赋值而使用set的原因主要是担心vb和ib可能会被某些地方引用，如果被引用了，除非去改引用的地方，否则会一直用老数据。用set的话，就不用管引用

2019-05-30 07:59 UTC, pandamicro commented
感觉这里面还是有不少内存浪费可以优化，不过需要底层的支持， @holycanvas 有时间跟伟亮讨论下

2019-05-30 08:00 UTC, merged