Add method to collider
cocos/cocos-engine pull request #4561
Opened 2019-06-06 06:15 UTC by JayceLai

Re: cocos-creator/3d-tasks#775

Changes:
 * Add on、off、once to collider component
 * All public component life cycle function to protected function
 * Modify collision event emit param

2019-06-06 11:24 UTC, YunHsiao requested changes

2019-06-06 11:24 UTC, YunHsiao commented on cocos/3d/framework/physics/collider/collider-component.ts
> +        this.node.on(type, callback, target, useCapture);
这个封装是不是意义不大，用户完全可以自己调 node 上的啊，而且 collider 能这么写而其他组件不行，是不是容易引起困惑

2019-06-07 07:04 UTC, JayceLai commented on cocos/3d/framework/physics/collider/collider-component.ts
> +        this.node.on(type, callback, target, useCapture);
这个是为了智能提示，调 node 上的没有智能提示，李楠  @shrinktofit   的建议是所有组件应该都封装一层，写上相应的类型声明，这样用 ts 敲起来就有智能提示了，并且可以强制规定事件可选的类型和传入的回调函数的函数签名，这样可以减少敲错的可能性，高阶玩家用 node 去监听也完全没有问题

2019-06-07 07:22 UTC, YunHsiao commented on cocos/3d/framework/physics/collider/collider-component.ts
> +        this.node.on(type, callback, target, useCapture);
类型提示的问题应该单独系统地解决，这个是一个通用需求；
我还是觉得直接把事件接口封装到 component 不是个好主意，对于绝大多数 component 来说都没什么意义：camera、sphere light、model 一类它们要发什么事件呢？封装得太顺手可能慢慢会引起歧义，以为 component 才是那个 event emitter，这就是个很严重的错误认识了。

2019-06-07 08:18 UTC, pandamicro commented on cocos/3d/framework/physics/collider/collider-component.ts
> +        this.node.on(type, callback, target, useCapture);
node.on 是有代码提示的，只是无法提示具体的 Collision 相关参数类型，这个我觉得没办法，如果只是为了代码提示上有，不应该改变实现，云潇说的 emitter 歧义我也是赞同的。

事件系统和消息系统都是比较松散的耦合，没有准确的提示我觉得是正常的，可以在 CollisionEventType 的  API 注释上写清楚该怎么使用的  example

2019-06-07 12:08 UTC, JayceLai commented on cocos/3d/framework/physics/collider/collider-component.ts
> +        this.node.on(type, callback, target, useCapture);
嗯嗯，哪我先屏蔽了这几个接口

2019-06-09 02:42 UTC, pandamicro commented
我和云潇的意思是如果由 Node 触发事件，这几个 API 不需要提供。
提供的话就应该由 Collider 来触发事件

2019-06-10 08:39 UTC, JayceLai commented
> 我和云潇的意思是如果由 Node 触发事件，这几个 API 不需要提供。
> 提供的话就应该由 Collider 来触发事件

嗯嗯，已经模仿 AnimationComponent 调整了事件由 Collider 来触发

2019-06-11 09:05 UTC, shrinktofit approved these changes

2019-06-11 09:32 UTC, jerrywwl approved these changes

2019-06-11 09:32 UTC, merged