add readOnly decorator
cocos/cocos-engine pull request #4626
Opened 2019-06-14 06:47 UTC by shrinktofit

Re: cocos-creator/2d-tasks#

Changes:
 *

2019-06-14 06:48 UTC, shrinktofit commented
depends on https://github.com/cocos-creator/editor-3d/pull/1564

2019-06-14 06:56 UTC, pandamicro requested changes

2019-06-14 06:56 UTC, pandamicro commented on cocos/core/data/utils/read-only.ts
> +export function readOnly (target: Object, propertyKey: string | symbol) {
习惯上 readonly 可以连写，不需要大写 O

2019-06-14 06:56 UTC, pandamicro commented on cocos/core/data/utils/read-only.ts
> +export function readOnly (target: Object, propertyKey: string | symbol) {
作为属性的修饰器，readonly 会被认为是属性只读的标记，只有 getter 没有 setter 的意思，我们这里提供的实际功能是保护 getter 获取的引用，可以用类似

@protectRef

2019-06-14 07:04 UTC, pandamicro commented on cocos/core/data/utils/read-only.ts
> +export function readOnly (target: Object, propertyKey: string | symbol) {
@YunHsiao 提议的 @immutableGetter 比较好

2019-06-14 07:16 UTC, shrinktofit commented on cocos/core/data/utils/read-only.ts
> +export function readOnly (target: Object, propertyKey: string | symbol) {
已改成 `constget`

2019-06-17 03:59 UTC, pandamicro approved these changes

2019-06-17 04:00 UTC, merged

2019-06-27 04:51 UTC, JoneLau commented
https://github.com/cocos-creator/3d-tasks/issues/515