merge 'refactor-minigame'
cocos/cocos-engine pull request #4640
Opened 2019-06-17 08:54 UTC by umbrellaPP

Re: https://github.com/cocos-creator/2d-tasks/issues/1360

2019-06-21 04:15 UTC, jareguo requested changes

2019-06-21 04:15 UTC, jareguo commented on cocos2d/audio/CCAudio.js
> +    proto._touchToPlay = function () {
我觉得用 _tapToPlay 比较好。touch 表示持续触摸，tap 表示轻触一下

2019-06-21 04:15 UTC, jareguo commented on cocos2d/core/CCGame.js
> +            if (CC_JSB || CC_RUNTIME) {
这个 if 不是上面就有了吗？重复了

2019-06-21 04:15 UTC, jareguo commented on cocos2d/core/physics/box2d-adapter.js
> +if (cc.sys.platform === cc.sys.QQ_PLAY) {
确定要这个判断吗？2.2 已经没有 QQPLAY 了，感觉可以去掉了

2019-06-21 04:15 UTC, jareguo commented on cocos2d/core/platform/CCSys.js
> +    sys.WECHAT_GAME_SUB = 105;
值就别改了吧？空着比较合理

2019-06-21 04:15 UTC, jareguo commented on modules.json
> +    ]
感觉这两个包不应该让用户自己选。应该根据构建的不同平台自动剔除才对

2019-06-21 04:15 UTC, jareguo commented on gulp/util/utils.js
> +const FLAGS = ['support_jit', 'jsb', 'runtime', 'debug', 'nativeRenderer', 'minigame'];
这文件里还是有 CC_QQPLAY 和 CC_WECHATGAME 啥的，不用删掉吗？

2019-06-21 04:15 UTC, jareguo commented on predefine.js
> +                }
这里是不是漏掉了 baidugame？？

2019-06-21 04:15 UTC, jareguo commented on predefine.js
> +    defineMacro('CC_SUPPORT_JIT', true);
为什么要改成 true？不是应该根据平台判断吗

2019-06-21 04:15 UTC, jareguo commented on predefine.js
> -    _global.CC_RUNTIME = CC_RUNTIME;
这里不是更简洁吗？为什么要改成下面的 defineMacro('CC_RUNTIME', 'function' === typeof loadRuntime);

2019-06-24 02:35 UTC, umbrellaPP commented on predefine.js
> +                }
百度没有 CC_BAIDUGAME 宏定义

2019-06-24 02:46 UTC, umbrellaPP commented on predefine.js
> +    defineMacro('CC_SUPPORT_JIT', true);
`CC_DEV CC_DEBUG CC_SUPPORT_JIT` 这些值只能在构建后确定，所以放在 CC_BUILD 的判断下
其他时候这些值默认都是 true 的

2019-06-24 02:46 UTC, umbrellaPP commented on predefine.js
> -    _global.CC_RUNTIME = CC_RUNTIME;
除了 `CC_DEV CC_DEBUG CC_SUPPORT_JIT` 只能在构建阶段确定
其他值目前都是可以运行时判断的，这里主要是做一下归类，区分

2019-06-24 02:49 UTC, umbrellaPP commented on cocos2d/audio/CCAudio.js
> +    proto._touchToPlay = function () {
我倒觉得 touch 比较好，表明是触发 touch 事件之后才能播放，是浏览器安全策略的限制

2019-06-24 03:23 UTC, PPpro commented on cocos2d/core/CCGame.js
> +            if (CC_JSB || CC_RUNTIME) {
这里确实要改下。。

2019-06-24 03:23 UTC, umbrellaPP commented on cocos2d/core/physics/box2d-adapter.js
> +if (cc.sys.platform === cc.sys.QQ_PLAY) {
嗯，之前不确定这里为什么这么改，就先保留了
现在可以去掉了

2019-06-24 03:38 UTC, umbrellaPP commented on modules.json
> +    ]
现在构建期间，已经没有 CC_WECHATGAME CC_QQPLAY 的平台剔除逻辑了

2019-06-24 15:20 UTC, pandamicro commented on cocos2d/core/components/WXSubContextView.js
> +if (!CC_EDITOR && !window.wx) {
微信浏览器环境中也存在 wx 变量，但是不支持子域

2019-06-24 15:43 UTC, umbrellaPP commented on cocos2d/core/components/WXSubContextView.js
> +if (!CC_EDITOR && !window.wx) {
![WechatIMG13](https://user-images.githubusercontent.com/17872773/60032802-e4128780-96d9-11e9-986b-f8367a55f196.jpeg)
不对吧，我看了下，微信浏览器中并没有 wx

2019-06-25 06:28 UTC, jareguo commented on predefine.js
> -    _global.CC_RUNTIME = CC_RUNTIME;
构建后 CC_BUILD 没定义，似乎是漏掉了？

2019-06-25 06:28 UTC, jareguo commented on predefine.js
> +defineDeprecatedMacroGetter('CC_WECHATGAME', WECHATGAME);
确定不让用户在代码里进行微信代码的剔除了吗？

2019-06-25 06:32 UTC, umbrellaPP commented on predefine.js
> +defineDeprecatedMacroGetter('CC_WECHATGAME', WECHATGAME);
代码剔除功能，其实没用正式地文档化，不算是正式的一个功能，所以移除了对用户来说应该是透明的才对
之前有建立了一个讨论性质地 issue，让用户自行配置要剔除哪部份地代码：https://github.com/cocos-creator/2d-tasks/issues/1567

2019-06-25 06:52 UTC, jareguo commented on predefine.js
> +defineDeprecatedMacroGetter('CC_WECHATGAME', WECHATGAME);
https://docs.cocos.com/creator/api/zh/modules/GLOBAL-MACROS.html

2019-06-25 07:13 UTC, umbrellaPP commented on predefine.js
> +defineDeprecatedMacroGetter('CC_WECHATGAME', WECHATGAME);
讨论了下，还是把文档移除了吧

2019-06-27 02:48 UTC, pandamicro approved these changes

2019-06-27 03:47 UTC, jareguo commented on predefine.js
> + * @deprecated since v2.2.0
直接删掉注释就好了吧？

2019-06-27 05:38 UTC, jareguo commented on modules.json
> +    ]
这个跟宏没关系，我是说这个模块别暴露给用户，看要不加个 hide: true 字段，然后构建时自动设置一下这两个模块的状态

2019-06-27 08:32 UTC, merged