Fix cannon add&remove mask method
cocos/cocos-engine pull request #4652
Opened 2019-06-19 02:47 UTC by JayceLai

Re: cocos-creator/3d-tasks#820

Changes:
 * Fix cannon add&remove mask method

2019-06-19 07:46 UTC, jerrywwl requested changes

2019-06-19 07:46 UTC, jerrywwl commented on cocos/3d/physics/cannon/cannon-body.ts
> +        }
直接this._body.collisionFilterMask |= v; 就完事了，不需要判断

2019-06-19 07:46 UTC, jerrywwl commented on cocos/3d/physics/cannon/cannon-body.ts
> +        }
this._body.collisionFilterMask &= ~v;

2019-06-20 02:52 UTC, JayceLai commented on cocos/3d/physics/cannon/cannon-body.ts
> +        }
好的，马上改过来

2019-06-20 03:39 UTC, jerrywwl approved these changes

2019-06-20 03:39 UTC, merged