bug fix
cocos/cocos-engine pull request #4674
Opened 2019-06-22 08:59 UTC by shrinktofit

Re: cocos-creator/2d-tasks#

Changes:
 *

2019-06-22 11:42 UTC, pandamicro requested changes

2019-06-22 11:42 UTC, pandamicro commented on cocos/components/animation-component.ts
> +        this._nameToState = Object.create(null);
不需要创建新对象，destroy 过程中会销毁所有引用，你如果想手动清空引用，可以设置

this._nameToState = null;

2019-06-23 16:03 UTC, JayceLai commented
cocos-creator/3d-tasks#875

2019-06-24 02:17 UTC, pandamicro approved these changes

2019-06-24 02:17 UTC, merged