fix particle lag
cocos/cocos-engine pull request #4718
Opened 2019-06-26 07:34 UTC by zxg0622

Re: cocos-creator/2d-tasks#

Changes:
 *

2019-06-26 08:16 UTC, jerrywwl commented on cocos/core/value-types/color.ts
> +        out._val = Math.floor(((a << 24) >>> 0) + (b << 16) + (g << 8) + r);
这个函数形式太不好了，public lerp()不如只作用于当前对象，不要给返回值了，也不用new Color()了

2019-06-26 08:18 UTC, zxg0622 commented on cocos/core/value-types/color.ts
> +        out._val = Math.floor(((a << 24) >>> 0) + (b << 16) + (g << 8) + r);
有时候外部的需求就是lerp的两个参数不变，结果赋给第三个参数

2019-06-26 08:48 UTC, jerrywwl commented on cocos/core/value-types/color.ts
> +        out._val = Math.floor(((a << 24) >>> 0) + (b << 16) + (g << 8) + r);
这种再来个static传out参数的接口吧，为了兼容多个参数要牺牲部分运行时性能，这种接口设计在cocos里太多了，我一直都想吐槽

2019-06-26 08:50 UTC, zxg0622 commented on cocos/core/value-types/color.ts
> +        out._val = Math.floor(((a << 24) >>> 0) + (b << 16) + (g << 8) + r);
那看下 @pandamicro 的意见？

2019-06-26 10:06 UTC, pandamicro commented on cocos/core/value-types/color.ts
> +        out._val = Math.floor(((a << 24) >>> 0) + (b << 16) + (g << 8) + r);
这些设计上的决策伟亮说了算

具体到这个问题，我也挺赞同的，面向对象的 API 作用于自身是合理的，不过我们目前有不少 API 有类似的做法，需要整理一下

2019-06-26 10:08 UTC, zxg0622 commented on cocos/core/value-types/color.ts
> +        out._val = Math.floor(((a << 24) >>> 0) + (b << 16) + (g << 8) + r);
那这个得统一整理下

2019-06-27 01:53 UTC, jerrywwl commented on cocos/core/value-types/color.ts
> +        out._val = Math.floor(((a << 24) >>> 0) + (b << 16) + (g << 8) + r);
 那先把眼前这个接口拆开吧

2019-06-27 06:20 UTC, jerrywwl requested changes

2019-06-27 06:20 UTC, jerrywwl commented on cocos/core/value-types/size.ts
> +
https://github.com/cocos-creator/3d-tasks/issues/912#issuecomment-506138575
请参考这个规范

只留这两种接口：
public lerp (to: Size, ratio: number);
public static lerpSize(out: Size, to: Size, ratio: number);

2019-06-28 02:18 UTC, jerrywwl approved these changes
pr先合并，接口规范部分回头请嘉宁一起整理 @LinYunMo

2019-06-28 02:18 UTC, merged