fix subContextView.update() bug
cocos/cocos-engine pull request #4721
Opened 2019-06-26 08:43 UTC by umbrellaPP

Re: https://github.com/cocos-creator/2d-tasks/issues/1504

changeLog:
- 修复 `subContextView.update()` 无法更新子域贴图的问题

每次 update 通知子域执行一次 `cc.game.step()`

2019-06-26 08:46 UTC, umbrellaPP commented on cocos2d/core/CCGame.js
> +        cc.director.resetLateUpdate();
之前加 startAnimation() 是为了更新 cc.direcotr._lateUpdate
但是不应该影响 cc.director.invalid，会造成 cc.game.step() 调用无效

2019-06-26 08:54 UTC, knoxHuang approved these changes

2019-06-28 02:53 UTC, pandamicro requested changes

2019-06-28 02:53 UTC, pandamicro commented on cocos2d/core/CCGame.js
> +        cc.director.resetLateUpdate();
stopAnimation 的意义就是停止 Director 的逻辑执行（主要就是影响游戏动画），以前就没有考虑过 step 的需求。

不过有了 pause 和 resume 是可以比较好得替代 stopAnimation，做下面几件事更合理：

1. 废弃 startAnimation & stopAnimation，直接在 deprecated 里面对接 resume 和 pause 接口
2. 不要增加 resetLateUpdate 接口，在 resume 中直接更新 _lastUpdate
3. 将 invalid 状态移除并废弃，简化逻辑，在 deprecated 中提示不会有任何效果

2019-06-28 02:53 UTC, pandamicro commented on cocos2d/core/CCGame.js
> +        cc.director.resetLateUpdate();
顺便说一下，这是 lastUpdate，并不是 lateUpdate，意义完全不一样

2019-06-28 02:53 UTC, pandamicro commented on cocos2d/core/components/SwanSubContextView.js
> +                }, DELAY_TO_UPDATE_TEXTURE);
这个 delay 太长了，而且这里也不适合使用 setTimeout，引擎里尽量不要新开任何 timer 计时器，这会跟引擎的主循环造成竞争关系，可能导致丢帧。postMessage 应该可以理解为同步操作（确认一下这点），如果是异步的话，其实我们不用考虑这一次 step 结果什么时候可以被更新到贴图上，step 按照 update 节奏来，渲染按照渲染帧率来，也就是 fps 属性的设置。

2019-06-28 02:53 UTC, pandamicro commented on cocos2d/core/components/SwanSubContextView.js
> +                }, DELAY_TO_UPDATE_TEXTURE);
哦，才发现是手动执行的操作，用户不应该手动执行组件的 update，你应该将这个逻辑拆分为一个独立函数让用户调用，否则混在一起 update 的语义可能造成混淆。

比如提供 step 函数执行子域的 step，然后用 scheduleOnce 来更新贴图。

2019-06-28 02:53 UTC, pandamicro commented on cocos2d/core/components/SwanSubContextView.js
> +                }, DELAY_TO_UPDATE_TEXTURE);
组件有自己的计时系统，应该更好地理解它的机制，而不是使用 setTimeout 这种接口，作为引擎开发人员这是基本的要求。

2019-06-28 03:57 UTC, umbrellaPP commented on cocos2d/core/components/SwanSubContextView.js
> +                }, DELAY_TO_UPDATE_TEXTURE);
> 哦，才发现是手动执行的操作，用户不应该手动执行组件的 update
有几个理由不建议新增 step 接口：
1. 我们文档是这么写的，通过 update 去更新贴图。。。
   已经有用户这么去做了，就算新增 step 接口，也得兼容旧项目的做法
2. 另外一个原因是平台剔除组件后，就没有 step 接口了，用户调用 step 之前还得做一层保护

2019-06-28 05:51 UTC, pandamicro commented on cocos2d/core/components/SwanSubContextView.js
> +                }, DELAY_TO_UPDATE_TEXTURE);
理解了，那么保留 update 函数中的这个实现，但是去除 setTimeout 的使用

2019-06-28 06:04 UTC, umbrellaPP commented on cocos2d/core/components/SwanSubContextView.js
> +                }, DELAY_TO_UPDATE_TEXTURE);
> stopAnimation 的意义就是停止 Director 的逻辑执行
我看之前的实现不是停止 Director 的逻辑
而是相当于 cc.game.pause(), 把逻辑、渲染和事件处理全都停止了

2019-06-28 10:01 UTC, PPpro commented on cocos2d/core/components/SwanSubContextView.js
> +                this._updateSubContextTexture();
安卓 iOS 上测试过，postMessage 都是同步操作

2019-06-28 10:01 UTC, PPpro commented on cocos2d/core/components/WXSubContextView.js
> +                this._context && this._context.postMessage({
安卓 iOS 上测试过，postMessage 都是同步操作

2019-06-28 10:50 UTC, pandamicro requested changes

2019-06-28 10:50 UTC, pandamicro commented on cocos2d/core/CCDirector.js
> +        cc.game.resume();
可以写在 deprecated 里面做代码隔离，这样 release 版本就不会带出去了

2019-06-28 11:56 UTC, pandamicro approved these changes

2019-06-28 11:56 UTC, merged