Vmath
cocos/cocos-engine pull request #4895
Opened 2019-07-17 06:48 UTC by LinYunMo

value-type change

2019-07-17 07:02 UTC, jerrywwl requested changes

2019-07-17 07:02 UTC, jerrywwl commented on cocos/core/value-types/mat4.ts
> +        return out;
这个好像不是translate的实现，是transform

2019-07-17 07:02 UTC, jerrywwl commented on cocos/core/vmath/mat3.ts
>      public static translate<Out extends mat3> (out: Out, a: mat3, v: vec3) {
这个translate理也是transform

2019-07-17 07:02 UTC, jerrywwl commented on cocos/core/value-types/mat3.ts
> +    }
不要调用Mat3.translate()，函数调用有开销，而且成员函数的实现还可以做一些优化，其它很多地方也请修改一下

2019-07-18 11:32 UTC, jerrywwl approved these changes

2019-07-18 11:32 UTC, merged

2019-07-19 06:29 UTC, LinYunMo commented
Re：https://github.com/cocos-creator/3d-tasks/issues/912