Vmath
cocos/cocos-engine pull request #4987
Opened 2019-07-26 04:41 UTC by LinYunMo

Re: https://github.com/cocos-creator/3d-tasks/issues/912

2019-07-26 08:51 UTC, pandamicro commented on cocos/3d/framework/particle/particle.ts
> +        this.size = Vec3.create(0, 0, 0);
不要保留 create 函数了，将所有 create 都改为 new

2019-07-26 08:51 UTC, pandamicro commented on cocos/3d/ui/components/label-component.ts
> +import { CCEnum } from '../../../core/value-types/enum';
这是一个包装函数，不是一个类，不要大写

2019-07-26 08:53 UTC, pandamicro commented
我还是希望 API 能够尽可能保持 KISS，在优化的设想不清晰之前，保持 API 风格的简单直接，一个功能不要给用户多个选择

2019-07-28 05:01 UTC, LinYunMo commented
RE:https://github.com/cocos-creator/3d-tasks/issues/1175

2019-07-28 07:40 UTC, pandamicro requested changes
vmath 应该要删除了

2019-07-28 07:40 UTC, pandamicro commented on cocos/3d/ui/components/scroll-view-component.ts
> +        if (position.equals(this.getContentPosition(), EPSILON)) {
这里逻辑并不等价

2019-07-28 07:40 UTC, pandamicro commented on cocos/core/index.ts
> +export { vmath };
vmath 为啥不删掉？

2019-07-28 07:40 UTC, pandamicro commented on cocos/core/math/color.ts
> +    public static set <Out extends IColorLike> (out: Out, r: number, g: number, b: number, a: number) {
为啥要用这个 IColorLike interface？

2019-07-28 07:40 UTC, pandamicro commented on cocos/core/math/color.ts
>      }
不需要提前判断啊，直接所有参数传给 constructor 就好了

2019-07-28 07:40 UTC, pandamicro commented on cocos/core/math/mat3.ts
> +cc.mat3 = mat3;
以前有这个接口吗？没有的就不要添加了

2019-07-28 07:40 UTC, pandamicro commented on cocos/core/math/mat4.ts
> +            out.x = (this.m01 +
不要添加这类额外的接口了，保留以前存在的就好

2019-07-28 07:40 UTC, pandamicro commented on cocos/core/math/enum.ts
> +export function Enum<T> (obj: T): T {
Enum, ValueType, 等和 math 无关的类不要放在 math 下，放在 value-types 目录下，模块之间的依赖关系是

math 依赖于 value-types

2019-07-28 07:40 UTC, pandamicro commented on cocos/core/utils/misc.ts
> +    radiansToDegrees,
这些为啥不放 math/utils 底下？

2019-07-28 07:40 UTC, pandamicro commented on cocos/core/vmath/color4.ts
> +        console.warn('Obsolete Vmath API');
deprecation 不是这样做的，嘉鑫会提供一个 cocos/deprecated.ts，里面可以提供 deprecated API 实现，参考

https://github.com/cocos-creator/engine/blob/v2.2.0/cocos2d/deprecated.js

2019-07-29 01:37 UTC, jerrywwl approved these changes

2019-07-29 03:27 UTC, LinYunMo commented on cocos/core/index.ts
> +export { vmath };
暂时保留，只有工具方法，以免不兼容，等 deprecated 做好之后做启用处理

2019-07-29 03:27 UTC, LinYunMo commented on cocos/core/math/color.ts
> +    public static set <Out extends IColorLike> (out: Out, r: number, g: number, b: number, a: number) {
兼容各类使用格式

2019-07-29 03:27 UTC, LinYunMo commented on cocos/core/math/mat4.ts
> +            out.x = (this.m01 +
以前就存在

2019-07-29 03:28 UTC, LinYunMo commented on cocos/core/utils/misc.ts
> +    radiansToDegrees,
兼容，之后做弃用处理

2019-07-29 03:45 UTC, pandamicro approved these changes

2019-07-29 03:50 UTC, merged