Fix call node targetOff func has not remove node from target.__eventTargets array
cocos/cocos-engine pull request #5052
Opened 2019-08-01 09:23 UTC by sunnylanwanjun

修复调用node的targetOff方法，但没有将节点从target node的_eventTarget数组中移除的bug
forum:https://forum.cocos.com/t/targetoff/81473

2019-08-01 09:30 UTC, pandamicro requested changes

2019-08-01 09:30 UTC, pandamicro commented on cocos2d/core/CCNode.js
> +            }
应该在 EventTarget 的 targetOff 中处理，因为添加的位置在 EventTarget 中

2019-08-01 09:39 UTC, sunnylanwanjun commented on cocos2d/core/CCNode.js
> +            }
不是的，是在CCNode的onDispatch里面添加的

2019-08-01 09:44 UTC, sunnylanwanjun commented on cocos2d/core/CCNode.js
> +            }
其实在CCNode的_offDispatch里面也有一样的代码，只是targetOff里面貌似忘记写了。

2019-08-02 04:01 UTC, pandamicro approved these changes

2019-08-02 04:01 UTC, merged