math function add
cocos/cocos-engine pull request #5076
Opened 2019-08-02 11:38 UTC by LinYunMo

RE:https://github.com/cocos-creator/3d-tasks/issues/1190
math function add

2019-08-04 02:36 UTC, pandamicro requested changes

2019-08-04 02:36 UTC, pandamicro commented on cocos/core/math/vec2.ts
> -    public static divide <Out extends IVec2Like> (out: Out, a: Out, b: Out) {
这个 divide 仍然是 divide，是 vector 之间的 divide，并不是除以标量

2019-08-04 02:36 UTC, pandamicro commented on cocos/core/math/vec2.ts
> -    public static divide <Out extends IVec2Like> (out: Out, a: Out, b: Out) {
我们不用提供 divideScalar， 这个通过 multiplyScalar 很容易实现，不需要额外提供 API

2019-08-04 02:36 UTC, pandamicro commented on cocos/core/math/deprecated.ts
> +        ['divide', 'divideScalar'],
既提供 divide 又提供 divideScalar 的话这里的废弃会导致正确的 divide 行为被覆盖。所以不能提供 divideScalar。行为的改变，我们只能尝试通过 ts 的类型校验处理

2019-08-05 01:44 UTC, merged

2019-08-05 01:44 UTC, jerrywwl commented
先合并了，我这边再调整