add new deprecated api & impl
cocos/cocos-engine pull request #5077
Opened 2019-08-02 11:57 UTC by JayceLai

2019-08-02 11:58 UTC, JayceLai commented
https://github.com/cocos-creator/3d-tasks/issues/1188

2019-08-05 02:58 UTC, pandamicro requested changes

2019-08-05 02:58 UTC, pandamicro commented on cocos/deprecated.ts
>  if (CC_DEBUG) {
把 debug 先去掉把

2019-08-05 02:58 UTC, pandamicro commented on cocos/vmath.ts
> +// ]);
目前框架实现有问题吗？为什么要注释掉？

2019-08-05 03:03 UTC, JayceLai commented on cocos/vmath.ts
> +// ]);
不是，这些之前佳宁已经加了，需要佳宁先按照新的改好，我这个只是示例

2019-08-05 03:03 UTC, JayceLai commented on cocos/deprecated.ts
>  if (CC_DEBUG) {
嗯嗯，好

2019-08-05 03:48 UTC, pandamicro approved these changes

2019-08-05 05:31 UTC, merged