add setDefaultLogTimes api to deprecated framework
cocos/cocos-engine pull request #5087
Opened 2019-08-05 07:58 UTC by JayceLai

2019-08-05 08:01 UTC, JayceLai commented
https://github.com/cocos-creator/3d-tasks/issues/1188

2019-08-16 06:12 UTC, pandamicro requested changes

2019-08-16 06:12 UTC, pandamicro commented on cocos/deprecated.ts
> +        messageMap.set(id, { id: id, count: 0, logTimes: item.logTimes != null ? item.logTimes : defaultLogTimes, });
不要用非严格比较，建议用 isNaN 来做准确判断

2019-08-16 06:18 UTC, JayceLai commented on cocos/deprecated.ts
> +        messageMap.set(id, { id: id, count: 0, logTimes: item.logTimes != null ? item.logTimes : defaultLogTimes, });
1

2019-08-16 06:37 UTC, pandamicro approved these changes

2019-08-16 06:37 UTC, merged