spriteframe is no a texture but a sprite container
cocos/cocos-engine pull request #5096
Opened 2019-08-05 11:53 UTC by JoneLau

2019-08-05 13:35 UTC, pandamicro requested changes

2019-08-05 13:35 UTC, pandamicro commented on cocos/3d/ui/assembler/label/bmfont.ts
> +        const texh = texture.height;
如果类型是 spriteFrame，对象名就不要用 texture，会引起阅读混乱

2019-08-05 13:35 UTC, pandamicro commented on cocos/assets/sprite-frame.ts
> +class SpriteFrameTexture extends SimpleTexture {
为什么不直接用 TextureBase ？

2019-08-05 13:35 UTC, pandamicro commented on cocos/assets/sprite-frame.ts
> +        this._spriteFrame = sp;
Texture  不应该依赖于 SpriteFrame

2019-08-05 13:35 UTC, pandamicro commented on cocos/assets/sprite-frame.ts
> +        const image = this._spriteFrame.image;
这个函数使用 Texture2D 的实现没问题，SpriteFrame 在 image 准备好之后就可以设置 texture 的 width 和 height

2019-08-05 13:35 UTC, pandamicro commented on cocos/assets/sprite-frame.ts
> +        this._texture.assignImage(this._image!);
同时设置 width 和 height，如果有必要的话

2019-08-06 01:57 UTC, JoneLau commented on cocos/assets/sprite-frame.ts
> +class SpriteFrameTexture extends SimpleTexture {
与 gl 交互的那部分都在 SimpleTexture 里

2019-08-06 02:38 UTC, pandamicro commented on cocos/assets/sprite-frame.ts
> +class SpriteFrameTexture extends SimpleTexture {
TextureBase 也有这部分功能啊

2019-08-06 02:58 UTC, pandamicro commented
1. 将 SpriteFrame 需要的功能抽象到 TextureBase 中
2. 在 RenderTexture 和 SimpleTexture 中实现

2019-08-07 04:01 UTC, JoneLau commented
editor pr:https://github.com/cocos-creator/editor-3d/pull/1967

2019-08-07 05:05 UTC, pandamicro requested changes

2019-08-07 05:05 UTC, pandamicro commented on cocos/3d/builtin/init.ts
> +        });
img setter 里面应该有事件派发，sprite frame 可以监听事件来更新自己的 size，rect

2019-08-07 05:05 UTC, pandamicro commented on cocos/3d/ui/components/label-component.ts
> +                this._ttfTexture.texture = tex;
这个 ttfTexture 是 spriteFrame 把？命名上优化一下

2019-08-07 05:05 UTC, pandamicro commented on cocos/assets/sprite-frame.ts
> + * 方法一：
example 代码中用注释写这类内容，并且用英文

// First way to use a SpriteFrame

2019-08-07 05:05 UTC, pandamicro commented on cocos/assets/sprite-frame.ts
> +     * @deprecated beta10 移除，新方案请参考头部。
v1.0.0 beta10

2019-08-07 05:05 UTC, pandamicro commented on cocos/assets/sprite-frame.ts
> +        // this._assignImage(this._image!, 0);
deprecated 的函数应该仍然是有效的，所以在提供原始实现的同时，给予用户警告，用嘉鑫的 deprecated 框架完成

2019-08-07 05:05 UTC, pandamicro commented on cocos/assets/sprite-frame.ts
> -        }
注意数据的变动带来的问题，是否需要数据迁移

2019-08-07 05:05 UTC, pandamicro commented on cocos/assets/sprite-frame.ts
> +        // }
ensureLoadTexture 逻辑迁移到 Texture2D 中

2019-08-07 05:34 UTC, JoneLau commented on cocos/assets/sprite-frame.ts
> +        // }
跟李楠那里商量过他那里不希望有这样的判定，Texture2D 在序列化的时候能确保这个数据是有的，这个外部赋值的话应该是外部设置

2019-08-07 05:36 UTC, JoneLau commented on cocos/assets/sprite-frame.ts
> -        }
需要的，编辑器重新导入资源可完成迁移

2019-08-07 07:10 UTC, pandamicro requested changes

2019-08-07 07:10 UTC, pandamicro commented on cocos/assets/sprite-frame.ts
> +        // }
这个并不能确保的，因为你们没试过 asyncLoadAsset 这个功能，这个功能就是在反序列化完成之后再加载 ImageAsset，所以需要监听 imageAsset 的 load 事件

2019-08-07 07:10 UTC, pandamicro commented on cocos/assets/sprite-frame.ts
> +    set _setImage(value: ImageAsset) {
set _imageSource

2019-08-07 07:10 UTC, pandamicro commented on cocos/assets/sprite-frame.ts
> +        this.emit('change-texture-view');
事件名尽量通用，不要暴露底层实现，这里可以用 texture-updated 或者更简单 updated

2019-08-07 07:10 UTC, pandamicro commented on cocos/assets/sprite-frame.ts
> +        this._texture.on('image-changed', this._imageChanged, this);
同样，用 updated 就好

2019-08-07 07:10 UTC, pandamicro commented on cocos/assets/sprite-frame.ts
> +        // }
```
public ensureLoadTexture () {
    if (this._texture) {
        this._texture.ensureImageLoad();
    }
}
```

2019-08-07 07:10 UTC, pandamicro commented on cocos/assets/sprite-frame.ts
> +            image.once('load', this.ensureLoadTexture, this);
这个函数应该在 texture 里面

2019-08-07 07:10 UTC, pandamicro commented on cocos/assets/sprite-frame.ts
> +    protected _imageChanged(image: ImageAsset){
_textureUpdated，sprite frame 不关心任何 image 相关的内容，它的 reset 信息也应该使用 texture 的 width 和 height

2019-08-07 07:10 UTC, pandamicro commented on cocos/assets/texture-2d.ts
> +        this.emit('image-changed', value);
应该先 ensureImageLoad，然后在确定 image loaded 的情况下，派发 updated 事件

2019-08-07 10:07 UTC, pandamicro approved these changes

2019-08-07 10:08 UTC, merged