md 2.1
cocos/cocos-engine pull request #5122
Opened 2019-08-08 07:05 UTC by shrinktofit

2019-08-08 07:05 UTC, shrinktofit commented
Request review from @yanOO1497

2019-08-09 02:46 UTC, jerrywwl requested changes
fix conflicts first

2019-08-09 05:36 UTC, yanOO1497 approved these changes

2019-08-09 05:37 UTC, yanOO1497 commented
https://github.com/cocos-creator/editor-3d/pull/1986 编辑器 pr

2019-08-09 05:58 UTC, merged