BitMask add, layers change ( don't marge, wait editor change )
cocos/cocos-engine pull request #5359
Opened 2019-09-10 05:49 UTC by LinYunMo

Re: https://github.com/cocos-creator/3d-tasks/issues/1257
don't marge, wait editor change
BitMask add, layers change

2019-09-10 06:39 UTC, VisualSJ commented
@gameu3d

2019-09-11 05:51 UTC, pandamicro requested changes

2019-09-11 05:51 UTC, pandamicro commented on cocos/core/scene-graph/layers.ts
> +const BitMaskList = BitMask({
为什么要有两个？

2019-09-11 05:51 UTC, pandamicro commented on cocos/core/scene-graph/node.ts
> +    // }
这种公开 API 不能随意删除，现在有什么问题？

2019-09-11 05:51 UTC, pandamicro commented on cocos/core/scene-graph/layers.ts
> +const LayersEnum = Enum({
应该用
```
enum LayersEnum {
...
}
ccbitmask(LayersEnum)
```

2019-09-11 08:01 UTC, LinYunMo commented on cocos/core/scene-graph/layers.ts
> +const BitMaskList = BitMask({
> 为什么要有两个？

因为 layer 持有的两个枚举，一个是可以多选的枚举 BitMaskList（给camera 的 visibility 使用），另一个是正常的单选枚举 layerlist（给 node 的 layer 使用）

2019-09-11 08:02 UTC, LinYunMo commented on cocos/core/scene-graph/node.ts
> +    // }
> 这种公开 API 不能随意删除，现在有什么问题？

addLayer 和removeLayer 不是单个节点应该具有的功能，node 只拥有一个 layer 值就可以了，不需要 add 和 remove

2019-09-11 08:04 UTC, LinYunMo commented on cocos/core/scene-graph/layers.ts
> +const LayersEnum = Enum({
> 应该用
> 
> ```
> enum LayersEnum {
> ...
> }
> ccbitmask(LayersEnum)
> ```

这样下面取引用的时候获取到的类型就是普通的 enum 而不是 我们的 ccenum 了

2019-09-11 09:47 UTC, pandamicro commented on cocos/core/scene-graph/layers.ts
> +  Default : (1 << 30),
命名应该用全大写 + 下划线

2019-09-11 09:47 UTC, pandamicro commented on cocos/core/scene-graph/layers.ts
> +  public static BitMaskList = BitMaskList;
Enum
BitMask

2019-09-11 09:47 UTC, pandamicro commented on cocos/core/scene-graph/layers.ts
> +  // public static addLayer (name: string): number | undefined {
这个 API 需要写到废弃中去

2019-09-11 09:47 UTC, pandamicro commented on cocos/core/scene-graph/node.ts
> +    // }
这两个 API 的移除和前面 API 的废弃放在一个单独的 PR 中，注明有 API 改动

2019-09-12 02:14 UTC, pandamicro requested changes

2019-09-12 02:14 UTC, pandamicro commented on cocos/core/scene-graph/deprecated.ts
> +        newName: 'Enum.DEFAULT'
这样似乎无法获取到，要求是 deprecated 的 API 使用原来的 API 可以直接访问到新 API

比如 Layers.Default 可以直接获取到 Layers.Enum.DEFAULT

2019-09-12 02:14 UTC, pandamicro commented on cocos/core/scene-graph/layers.ts
> +  DEFAULT : (1 << 30),
还是不要写成两份，维护不好维护，写一个对象，然后

Enum(obj)
BitMask(clone(obj))

2019-09-12 02:14 UTC, pandamicro commented on cocos/core/value-types/bitmask.ts
> +    });
为什么要有这个？哪里用到了 _TestBitMask

2019-09-12 07:48 UTC, pandamicro approved these changes

2019-09-12 07:49 UTC, merged