add splash image
cocos/cocos-engine pull request #5363
Opened 2019-09-10 08:01 UTC by JayceLai

2019-09-10 08:03 UTC, JayceLai commented
https://github.com/cocos-creator/3d-tasks/issues/1408

2019-09-10 08:17 UTC, pandamicro requested changes

2019-09-10 08:17 UTC, pandamicro commented on cocos/core/game.ts
> +        if (!CC_EDITOR && CC_WECHATGAME/* && !CC_PREVIEW*/) {
Web 端也可以开启

2019-09-10 08:17 UTC, pandamicro commented on cocos/core/game.ts
> +        if (!CC_EDITOR && CC_WECHATGAME/* && !CC_PREVIEW*/) {
Web 端也可以开启

2019-09-10 08:17 UTC, pandamicro commented on cocos/core/game.ts
> +            cc.splashImage.main(this._gfxDevice as any, () => { this.prepare(cc.game.onStart && cc.game.onStart.bind(cc.game)); });
不要把 splashImage 放在 cc 下，这里 import splash-image，然后 new 一个出来感觉比较好

2019-09-10 08:17 UTC, pandamicro commented on cocos/core/splash-image.ts
> +cc.splashImage = new SplashImage();
不用给 cc 添加这些内容，cc 空间下的对象目前主要是为了兼容旧版本的使用方式，新的 API 不应该再手动添加到 cc 下

2019-09-10 08:18 UTC, pandamicro commented
@jerrywwl 渲染方式上伟亮看看是否合规

2019-09-10 08:21 UTC, JayceLai commented on cocos/core/game.ts
> +            cc.splashImage.main(this._gfxDevice as any, () => { this.prepare(cc.game.onStart && cc.game.onStart.bind(cc.game)); });
imoprt 会导致循环引用，所以才这样子的

2019-09-10 08:30 UTC, pandamicro requested changes

2019-09-10 08:30 UTC, pandamicro commented on cocos/core/game.ts
> +            cc.splashImage.main(this._gfxDevice as any, () => { this.prepare(cc.game.onStart && cc.game.onStart.bind(cc.game)); });
还有个问题，onStart 里面的场景加载应该和 SplashImage 并行，否则太浪费时间，会导致加载过程的黑屏。并行的处理应该是在 SplashImage 动画播完之前都不要开始 renderer 的渲染流程即可

2019-09-10 11:32 UTC, pandamicro approved these changes

2019-09-12 08:00 UTC, pandamicro commented on cocos/core/splash-image.ts
> +    public onFinish (cb: Function) {
这个 API 很奇怪，要么 onFinish 是一个属性，直接作为 callback 使用，要么就写成 setOnFinish 之类的函数名。否则很容易误以为是这个函数在动画结束 时会被调用

2019-09-12 08:00 UTC, pandamicro commented on cocos/core/splash-image.ts
> +            "name": "util/splash-image",
不能直接用 unlit 吗？

2019-09-12 08:46 UTC, merged