improve bitmap font warn tips for 2d-tasks/issues/1751
cocos/cocos-engine pull request #5379
Opened 2019-09-11 10:39 UTC by knoxHuang

Re: cocos-creator/2d-tasks#1751

Changes:
 * 完善 BitmapFont，当不满足要求应该报警告而不是报错，导致无法创建节点

2019-09-12 02:21 UTC, caryliu1999 approved these changes

2019-09-12 02:24 UTC, SantyWang requested changes

2019-09-12 02:24 UTC, holycanvas commented on EngineErrorMap.md
> +Warning: there is no font configuration in '%s' bitmap font.
感觉这样提示有些奇怪，因为我们的 configuration 是根据用户设置的参数生成的，用户其实是不知道这个东西的存在的，这样提示的话，用户会以为还差什么文件。我觉得可以直接提示他需要设置哪些参数吧

2019-09-12 03:57 UTC, 2youyou2 commented on cocos2d/core/renderer/utils/label/bmfont.js
> +        if (_comp === comp || !fontAsset || !fontAsset.spriteFrame || !fontAsset._fntConfig) return;
不要在这加，在 label 里的 _canRender 里面判断就好

2019-09-12 06:03 UTC, knoxHuang commented on cocos2d/core/renderer/utils/label/bmfont.js
> +        if (_comp === comp || !fontAsset || !fontAsset.spriteFrame || !fontAsset._fntConfig) return;
_canRender 为 false 还是会走 updateRenderData

2019-09-12 06:37 UTC, knoxHuang commented on cocos2d/core/renderer/utils/label/bmfont.js
> +        if (_comp === comp || !fontAsset || !fontAsset.spriteFrame || !fontAsset._fntConfig) return;
目前暂时先这样，等凯乐重构后在完善

2019-09-12 06:41 UTC, SantyWang approved these changes

2019-09-12 06:44 UTC, merged

2019-09-16 13:43 UTC, jareguo commented on EngineErrorMap.md
> +Warning: Render failed, there is no information in '%s', please set in '%s' inspector panel.
Warning 是多余的，因为本身用户就能区分出是不是警告，毕竟是 cc.warn
另外，引擎去叫用户检查 inspector 是很奇怪的，编辑器才应该有这种提示，何况我们对外都是使用 Properties panel 这个叫法。
还有就是，你确定构建后，能拿到 this.name?
还有就是，你是不是少传了一个 this.name？因为你有两个 %s