impl physics raycast
cocos/cocos-engine pull request #5403
Opened 2019-09-17 06:36 UTC by JayceLai

2019-09-17 08:02 UTC, JayceLai commented
https://github.com/cocos-creator/3d-tasks/issues/1415

2019-09-26 05:49 UTC, YunHsiao approved these changes

2019-10-21 02:34 UTC, pandamicro requested changes

2019-10-21 02:34 UTC, pandamicro commented on cocos/physics/api.ts
> +    raycastAny (worldRay: ray, options: IRaycastOptions, out: PhysicsRayResult): boolean;
这个 API 的意义是什么？什么情况下需要用到？

2019-10-21 02:34 UTC, pandamicro commented on cocos/physics/api.ts
> +    raycastAll (worldRay: ray, options: IRaycastOptions, pool: RecyclePool<PhysicsRayResult>, resultes: PhysicsRayResult[]): boolean
建议简化 API 为 raycast，我觉得两个 API 应该够了

- raycast
- raycastClosest

2019-10-21 06:59 UTC, pandamicro approved these changes

2019-10-21 07:25 UTC, merged