fix component event type can't be find
cocos/cocos-engine pull request #5473
Opened 2019-09-26 03:48 UTC by JoneLau

2019-09-26 06:44 UTC, pandamicro approved these changes

2019-09-26 06:44 UTC, pandamicro requested changes

2019-09-26 06:44 UTC, pandamicro commented on cocos/ui/components/scroll-view-component.ts
> +        type: ComponentEventHandler,
应该是数组？你确定改完以后你尝试了？

2019-09-26 06:52 UTC, JoneLau commented on cocos/ui/components/scroll-view-component.ts
> +        type: ComponentEventHandler,
对的，我 button 里也是这么写的

2019-09-26 07:12 UTC, pandamicro commented on cocos/ui/components/scroll-view-component.ts
> +        type: ComponentEventHandler,
还是按照规范改掉

2019-09-27 02:37 UTC, JoneLau commented
updated

2019-09-27 09:01 UTC, pandamicro approved these changes

2019-09-27 09:01 UTC, merged