add stayOnBottom to video player
cocos/cocos-engine pull request #5510
Opened 2019-10-10 08:53 UTC by knoxHuang

Re: cocos-creator/2d-tasks#1870

Changes:
 * VideoPlayer 支持 AVG 层级设定功能

2019-10-10 15:04 UTC, SantyWang reviewed
感觉这种只有web支持，都不是支持得很好的功能，添加到引擎里面不太合适，能不能直接在avg那边hack算了

2019-10-11 07:56 UTC, jareguo commented
这个需求不单单是 avg 要用啊，做交互式视频游戏也需要。类似甜蜜糖果屋这种。

2019-10-12 01:50 UTC, holycanvas commented
ok，那咱们先不考虑各个平台支持得怎么样，statOnBottom感觉也不够啊，如果他想要一直浮在最上，还有种情况是多个视频播放，某个视频在另一个视频上面，这些情况需要考虑么

2019-10-12 07:42 UTC, knoxHuang commented
如果考虑到 某个视频在另一个视频上面，这些情况到话
这里可以考虑加一个 z-index 属性给用户使用设置

2019-10-12 14:55 UTC, holycanvas commented
用zindex可能不太好，因为ui已经有了个zindex了，会有一点冲突，如果给视频组件增加一个depth的属性，视频间的排序就按depth的大小来排序，并且depth大于0，就渲染在游戏界面前，如果小于0，就渲染在游戏界面后面，这样一个属性就能将两个功能涵盖了。这个功能我觉得可以大家再讨论一下

2019-10-14 03:46 UTC, jareguo commented
视频和视频重叠这个就不考虑吧…… 很少有游戏会有需要

2019-10-14 03:50 UTC, holycanvas commented
OK，没问题

2019-10-14 03:50 UTC, SantyWang approved these changes

2019-10-14 03:53 UTC, SantyWang requested changes

2019-10-14 03:53 UTC, holycanvas commented on cocos2d/videoplayer/CCVideoPlayer.js
> +         * !zh 永远在游戏视图最底层（这个属性只有在 Web 平台上有效果。注意：具体效果无法保证一致，跟各个浏览器是否支持与限制有关）
!#zh ，还有英文的标点符号注意一下

2019-10-14 03:53 UTC, holycanvas commented on editor/i18n/en/localization.js
> +            "stayOnBottom": "Always below the game view (only useful on Web。Note: The specific effects are not guaranteed to be consistent, depending on whether each browser supports or restricts)."
标点符号注意下

2019-10-15 01:49 UTC, holycanvas commented
localization.js 里面的标点符号还没改

2019-10-15 02:20 UTC, SantyWang approved these changes

2019-10-16 05:03 UTC, merged