unify animation clips
cocos/cocos-engine pull request #5517
Opened 2019-10-11 04:57 UTC by YunHsiao

Re: cocos-creator/fireball#

Changelog:
 *

2019-10-11 08:25 UTC, shrinktofit commented on cocos/core/animation/skeletal-animation-data-hub.ts
> +            new HierachyModifier(''),
如果操纵的就是当前结点，可以不要 `new HierachyModifier('')`

2019-10-11 08:25 UTC, shrinktofit commented on cocos/core/animation/skeletal-animation-data-hub.ts
> +            new ComponentModifier('cc.SkeletalAnimationComponent'),
建议 `new ComponentModifier(js.getClassName(SkeletalAnimationComponent))`

2019-10-12 01:43 UTC, pandamicro requested changes

2019-10-12 01:43 UTC, pandamicro commented on cocos/core/animation/animation-clip.ts
> +    get duration () {
你的 VSCode 代码格式化配置带来的修改对审核干扰太大了，要么推广一下你的配置，大家讨论确定规范后，确保所有人开发的时候就遵守一样的规范。

2019-10-12 01:43 UTC, pandamicro commented on cocos/core/animation/animation-clip.ts
> -    private _getDeprecatedCurveDatas () {
为什么改变了 hash 的计算方法？

2019-10-12 01:43 UTC, pandamicro commented on cocos/core/animation/skeletal-animation-clip.ts
> -export class SkeletalAnimationClip extends AnimationClip {
这样删除后，用户的场景数据和 prefab 数据会受到影响吗？

2019-10-12 01:43 UTC, pandamicro commented on cocos/core/scene-graph/node.ts
> +import { eventManager } from '../platform/event-manager/event-manager';
你这个排序的规则到底是啥，建议从格式化规则里面去掉，根本没意义啊

2019-10-12 01:43 UTC, pandamicro commented on cocos/core/animation/skeletal-animation-data-hub.ts
> +export class SkelAnimDataHub {
从内存上来说，有比之前更优吗？

能否拆分为两个 PR，一个解决 #1590 的 issue，但是不要做重构。
另一个合并 AnimationClip，提交到 1.0.1。

这么大的重构，并且是所有项目都会用到的核心动画模块，我不希望现在这个阶段合并。这会导致很多不确定性，同时也会造成测试组资源的浪费（上一个版本等于白测了，还得重新完整测一次）。如果有必要的合并理由，请充分说明

2019-10-12 02:06 UTC, YunHsiao commented on cocos/core/animation/animation-clip.ts
> +    get duration () {
就是原来 tslint 的配置，我一直在沿用

2019-10-12 02:07 UTC, YunHsiao commented on cocos/core/animation/animation-clip.ts
> -    private _getDeprecatedCurveDatas () {
没必要专门为了 hash 再把旧数据捋一遍，新格式也能一样算

2019-10-12 02:07 UTC, YunHsiao commented on cocos/core/animation/skeletal-animation-clip.ts
> -export class SkeletalAnimationClip extends AnimationClip {
我在编辑器仓库升了版本号，不会受影响

2019-10-12 02:07 UTC, YunHsiao commented on cocos/core/scene-graph/node.ts
> +import { eventManager } from '../platform/event-manager/event-manager';
原来 tslint 的默认规则，反正能自动修正，我觉得挺好

2019-10-12 02:09 UTC, YunHsiao commented on cocos/core/animation/skeletal-animation-data-hub.ts
> +export class SkelAnimDataHub {
合并 animation clip 就是为了解决这次的问题，不好拆，但可以回退到再之前的策略，就是强制生成 skeletal animation clip

2019-10-12 02:11 UTC, YunHsiao commented on cocos/core/animation/skeletal-animation-data-hub.ts
> +            new HierachyModifier(''),
好像删掉就不行了

2019-10-12 02:39 UTC, closed without merging