fix director lateUpdate time in wechat platform
cocos/cocos-engine pull request #5535
Opened 2019-10-14 02:50 UTC by JayceLai

Re: cocos-creator/3d-tasks#

Changes:
 * fix director lateUpdate time in wechat platform

2019-10-14 05:19 UTC, JayceLai commented
![fix-director-lateupdate](https://user-images.githubusercontent.com/23555101/66730547-0a288700-ee85-11e9-83f8-ce7cb9291607.gif)

因为微信上渲染logo会占用一些时间，会导致 director 的 _lateUpdate 不正确，所以在 game inited 事件上把 _lateUpdate 更新了一下

2019-10-14 15:00 UTC, pandamicro requested changes

2019-10-14 15:00 UTC, pandamicro commented on cocos/core/director.ts
> +        });
不要在这里处理，这相当于让 director 意识到 logo 动画的影响，不合逻辑。

应该在 splash screen 里面监听时间并处理 director 的 lastUpdate

2019-10-15 04:41 UTC, JayceLai commented on cocos/core/director.ts
> +        });
改到了 splash screen 里面
![image](https://user-images.githubusercontent.com/23555101/66800777-1fff8000-ef49-11e9-88ee-757ae44ea9fe.png)

2019-10-16 10:17 UTC, pandamicro commented on cocos/core/splash-image.ts
> +        if (window._CCSettings && window._CCSettings.SplashScreen) {
没有在编辑器有对应的修改吗？这种涉及到编辑器的内容一定要关联

2019-10-16 11:21 UTC, JayceLai commented on cocos/core/splash-image.ts
> +        if (window._CCSettings && window._CCSettings.SplashScreen) {
嗯嗯，知道的

因为这个编辑器还没有相应的修改接口，所以引擎端先预留出配置属性了

2019-10-17 01:56 UTC, pandamicro approved these changes

2019-10-17 01:56 UTC, merged