fix detect iPad device on IOS 13.1.1+
cocos/cocos-engine pull request #5542
Opened 2019-10-14 12:04 UTC by krapnikkk

修复更新ios13.1.1+版本后iPad设备的UA信息的识别=>
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko)"
参考资料：https://stackoverflow.com/questions/58019463

Re: cocos-creator/2d-tasks#

Changes:
 *

2019-10-14 14:55 UTC, pandamicro requested changes

2019-10-14 14:55 UTC, pandamicro commented on cocos2d/core/platform/CCSys.js
> -        else if (/(iPhone|iPad|iPod)/.exec(nav.platform)) {
感谢发现这个问题，麻烦 按照原始的方式来检测

/(iPhone|iPad|iPod|MacIntel)/.exec(nav.platform)

2019-10-16 02:23 UTC, pandamicro approved these changes

2019-10-16 02:23 UTC, merged

2019-10-28 10:36 UTC, jareguo commented
非常感谢，这个修复将会进入到 2.1.4 和 2.2.1

2021-08-12 10:39 UTC, baibai2013 commented
sys.isMobile = /mobile|android|iphone|ipad/.test(ua); 
这个判断是不是需要改一下。不然ipad iOS13上判断 有误。
目前版本2.4.3 mousedown，mouseup，touchstart，touchmove都会走两遍handleTouchesBegin，handleTouchesMove

2021-08-12 10:45 UTC, baibai2013 commented
browser or runtime 中 sys.isMobile = /mobile|android|iphone|ipad/.test(ua);这个判断需要改一下。不然ipad iOS13上判断 有误。
目前使用版本2.4.3 mousedown，mouseup，touchstart，touchmove都会走两遍handleTouchesBegin，handleTouchesMove
如cc.button或者注册的touch事件node会走两遍handleTouchesBegin，handleTouchesMove，排查了半天才找到这个希望修复


修改如下  sys.isMobile = /mobile|android|iphone|ipad/.test(ua) || nav.platform === 'MacIntel';

2021-08-16 03:27 UTC, PPpro commented
> 修改如下 sys.isMobile = /mobile|android|iphone|ipad/.test(ua) || nav.platform === 'MacIntel';

@baibai2013 意思是 在 ipad iOS13 上，sys.isMobile 被判断为 false 了吗，
但是看逻辑应该即使是 sys.isMobile 被判断为 false 也只会走 mouse 事件，不会走 touch 事件才对呢
为什么会执行两次 handleTouchesBegin 呢

2021-08-23 16:45 UTC, baibai2013 commented
是我们的问题，问题找到了。我们有多层div，在游戏的div上面还有一层div，同事想在上层div中用mouse事件做一个画笔的功能 把 touch事件里
                   //event.stopPropagation();
                   // event.preventDefault();
注释掉了。然后在game的div就会出现先执行touch然后执行mouse，导致handle走两遍的问题。然后改回去就好了，并支持touch没有问题了。

iPad 上监听mouse事件我觉得没有问题，毕竟iPad用无线鼠标的也是有可能的。但是isMobile是为false判断是有否有问题？

2021-08-24 02:09 UTC, PPpro commented
> iPad 上监听mouse事件我觉得没有问题，毕竟iPad用无线鼠标的也是有可能的。但是isMobile是为false判断是有否有问题？

嗯，这个我们之后会支持下 iPad 鼠标事件