Fixed a problem that the Letter Font showed a white border.
cocos/cocos-engine pull request #5551
Opened 2019-10-15 12:51 UTC by caryliu1999

Re: cocos-creator/2d-tasks#1905

2019-10-16 03:48 UTC, SantyWang requested changes

2019-10-16 03:48 UTC, SantyWang commented on cocos2d/core/renderer/utils/label/letter-font.js
> +        this._height = (1 + textUtils.BASELINE_RATIO) * this._labelInfo.fontSize + this._labelInfo.margin * 2 + bleed;
_updateProperties 执行频率挺高呀。要不把 ```this._labelInfo.margin * 2 + bleed``` 缓存一下，少算一次

2019-10-16 03:48 UTC, SantyWang commented on cocos2d/core/renderer/utils/label/letter-font.js
> +        letter.xAdvance = letterTexture._width - bleed;
直接等于letter.w呢

2019-10-16 03:48 UTC, SantyWang commented on cocos2d/core/renderer/utils/label/letter-font.js
> +        letter.u = this._x + bleed/2;
缓存下bleed / 2吧

2019-10-16 03:48 UTC, SantyWang commented on cocos2d/core/renderer/utils/label/letter-font.js
> +const bleed = 2;
这里的意思是向外扩展两个像素，让两个字符贴图合在大图里的时候不相交，这样就能清除白边么

2019-10-16 06:24 UTC, holycanvas commented on cocos2d/core/renderer/utils/label/letter-font.js
> +        letter.u = this._x + bleed/2;
这个不用改了，js build之后会自动替换为1

2019-10-16 08:29 UTC, 2youyou2 commented on cocos2d/core/renderer/utils/label/letter-font.js
> +const bleed = 2;
这里bleed 和 space 有什么区别，正常 bleed 应该是指用渲染的像素向外扩展再渲染几个像素

2019-10-16 08:54 UTC, caryliu1999 commented on cocos2d/core/renderer/utils/label/letter-font.js
> +const bleed = 2;
space是图集中碎图之间的间隔，加上这个间隔避免采样的相邻碎图的像素。bleed是在绘制字符图片时给canvas周围加了一个像素，绘制了字符的底色，其实跟动态图集那里drawAt的5次是一样的作用，只不过绘制5次在这里性能上代价太大，用这种方式更优一些。

现在遇到的bug是使用线性插值的时候字符图片边缘采样到了白色的背景像素，做不了帧调试，所以不太确定是写入图集的时候产生的还是采样大图纹理的时候space不是透明导致的。这样加了bleed之后，依据uv跟宽高取纹理的时候就偏移bleed/2的像素，取内部的实际图片，相当于图片边缘部分不会受到space区间内的像素影响，只会插值到bleed的那一个像素。

2019-10-16 09:02 UTC, caryliu1999 commented on cocos2d/core/renderer/utils/label/letter-font.js
> +        this._height = (1 + textUtils.BASELINE_RATIO) * this._labelInfo.fontSize + this._labelInfo.margin * 2 + bleed;
修改了，_updateProperties只会在数据有变化的时候执行一次

2019-10-16 09:02 UTC, caryliu1999 commented on cocos2d/core/renderer/utils/label/letter-font.js
> +        letter.xAdvance = letterTexture._width - bleed;
修改了

2019-10-16 09:38 UTC, caryliu1999 commented on cocos2d/core/renderer/utils/label/letter-font.js
> +const bleed = 2;
> 这里bleed 和 space 有什么区别？正常 bleed 应该是指用渲染的像素向外扩展再渲染几个像素

加了bleed之后，space可以不要了，删掉了

2019-10-16 09:58 UTC, 2youyou2 commented on cocos2d/core/renderer/utils/label/letter-font.js
> +        let blank = this._labelInfo.margin * 2 + bleed;
有个问题，如果有 outline 或者 shadow，这里 safeMeasureText 的 width 是对的吗？

2019-10-16 11:38 UTC, caryliu1999 commented on cocos2d/core/renderer/utils/label/letter-font.js
> +        let blank = this._labelInfo.margin * 2 + bleed;
shadow在letter这里没支持，因为偏移太不固定了，outline的宽度是我们自己画的外框，用margin来做叠加了。

2019-10-16 11:41 UTC, SantyWang approved these changes

2019-10-16 12:00 UTC, 2youyou2 approved these changes

2019-10-16 14:50 UTC, jareguo commented on cocos2d/core/renderer/utils/label/letter-font.js
> +        let blank = this._labelInfo.margin * 2 + bleed;
this._labelInfo.margin 就包含了 outline 信息了，shadow 信息忘记有没有

2019-10-16 14:57 UTC, jareguo approved these changes

2019-10-17 02:33 UTC, caryliu1999 commented on cocos2d/core/renderer/utils/label/letter-font.js
> +const bleed = 2;
> > 这里bleed 和 space 有什么区别？正常 bleed 应该是指用渲染的像素向外扩展再渲染几个像素
> 
> 加了bleed之后，space可以不要了，删掉了

把space还原了，偶现了文字边缘被裁切的情况，但是没有复现，保险起见还是加上了

2019-10-18 06:03 UTC, jareguo commented on cocos2d/core/renderer/utils/label/letter-font.js
> +const bleed = 2;
我觉得没必要，文字边缘被裁剪可能原因挺多的，也有可能是用户自己的问题。如果我们加上了这个问题可能就永远搞不清楚了。去掉 space，之后我们还有可能能找到重现方法。

2019-10-21 13:23 UTC, jareguo approved these changes

2019-10-21 13:34 UTC, dumganhar commented on cocos2d/core/renderer/utils/label/letter-font.js
> +const bleed = 2;
为啥子取名字叫 bleed 呢？

2019-10-21 15:43 UTC, jareguo commented on cocos2d/core/renderer/utils/label/letter-font.js
> +const bleed = 2;
出血位呗

2019-10-24 03:40 UTC, closed without merging