misc pipeline fix
cocos/cocos-engine pull request #5558
Opened 2019-10-16 10:10 UTC by YunHsiao

Re: cocos-creator/fireball#

Changelog:
 *

2019-10-16 10:22 UTC, pandamicro requested changes

2019-10-16 10:22 UTC, pandamicro commented on cocos/core/3d/framework/model-component.ts
> +        if (this._model) { this._model.enabled = false; } // don't enable before onEnable
enabled 是用户属性，引擎逻辑不应该修改它，设想如果用户自己的 ModelComponent 设置就是 false 呢，那引擎会不会在后面 onEnable 过程中自动把它启用。

这里代码组织还有一个问题，_updateModels 表明它就是对 model 进行处理的函数，model 相关逻辑应该放在那里。

2019-10-16 10:22 UTC, pandamicro commented on cocos/core/3d/framework/model-component.ts
> +        if (this._model) { this._model.enabled = false; } // don't enable before onEnable
这里出现问题的根本原因可能还没找到，为什么 enabled 为 true 会有问题？

2019-10-16 10:22 UTC, pandamicro commented on cocos/core/renderer/scene/planar-shadows.ts
> +        else { cb = device.createCommandBuffer(info); }
这代码阅读困难，求不要省行数

2019-10-16 14:11 UTC, YunHsiao commented on cocos/core/3d/framework/model-component.ts
> +        if (this._model) { this._model.enabled = false; } // don't enable before onEnable
问题来自 https://forum.cocos.com/t/creator3d-executeineditmode-node/84541/4，用户脚本的 onEnable 里调了 removeAllChildren，但由于此时 children（带有 ModelComponent） 的 onEnable 都还没调，所以不会调用它们的 onDisable，导致这些 children 节点删掉了，但它们的 model 还是可见状态。
这里的修改的确只是一个非常粗糙的 hack，因为 ModelComponent 的内部实现太混乱了，我不敢轻易动。这块建议重构，见 https://github.com/cocos-creator/3d-tasks/issues/1636，目前为了解决问题我觉得这样也 ok

2019-10-18 06:00 UTC, pandamicro commented on cocos/core/3d/framework/model-component.ts
> +        if (this._model) { this._model.enabled = false; } // don't enable before onEnable
onEnable 和 onDisable 中不能修改子节点的 parent（设为空或者修改都不行），因为我们的 Node activator 是在 activate 阶段收集节点树列表，然后再根据列表去做 onEnable / onDisable 的操作的。

2019-10-18 06:08 UTC, YunHsiao commented on cocos/core/3d/framework/model-component.ts
> +        if (this._model) { this._model.enabled = false; } // don't enable before onEnable
这改的是自己持有的 Model，不是子节点

2019-10-18 06:34 UTC, pandamicro commented on cocos/core/3d/framework/model-component.ts
> +        if (this._model) { this._model.enabled = false; } // don't enable before onEnable
@zxg0622 看下这里应该怎么处理比较好

2019-10-18 07:13 UTC, zxg0622 commented on cocos/core/3d/framework/model-component.ts
> +        if (this._model) { this._model.enabled = false; } // don't enable before onEnable
如果children的onEnable都没调为什么_model.enabled会是true?

2019-10-21 02:05 UTC, YunHsiao commented on cocos/core/3d/framework/model-component.ts
> +        if (this._model) { this._model.enabled = false; } // don't enable before onEnable
onLoad 里调了

2019-10-21 02:15 UTC, zxg0622 commented on cocos/core/3d/framework/model-component.ts
> +        if (this._model) { this._model.enabled = false; } // don't enable before onEnable
那是因为这个节点的enabledInHierarchy是true所以这个时候设置_model.enabled并没有问题

2019-10-21 02:35 UTC, pandamicro commented on cocos/core/3d/framework/model-component.ts
> +        if (this._model) { this._model.enabled = false; } // don't enable before onEnable
主要问题是我们不允许在 onEnable 的时候 remove children，这个我加了一个保护，这里的修改先去掉吧

2019-10-21 02:39 UTC, pandamicro commented on cocos/core/3d/framework/model-component.ts
> +        if (this._model) { this._model.enabled = false; } // don't enable before onEnable
修改在这里
https://github.com/cocos-creator/engine/pull/5569

2019-10-21 03:03 UTC, YunHsiao commented on cocos/core/3d/framework/model-component.ts
> +        if (this._model) { this._model.enabled = false; } // don't enable before onEnable
已去掉

2019-10-21 03:06 UTC, pandamicro approved these changes

2019-10-21 03:06 UTC, merged