widgetcomponent adjustment
cocos/cocos-engine pull request #5578
Opened 2019-10-22 03:15 UTC by LinYunMo

Re: https://github.com/cocos-creator/3d-tasks/issues/1595

2019-10-23 08:47 UTC, pandamicro requested changes

2019-10-23 08:47 UTC, pandamicro commented on cocos/ui/components/widget-component.ts
> +    set runtimeTop (value) {
没必要搞这么多属性啊，实际的值存放在 _top, _bottom, _left, _right 中就可以了

2019-10-23 08:47 UTC, pandamicro commented on cocos/ui/components/widget-component.ts
> +    set runtimeTop (value) {
而且暴露 setter 给用户很奇怪，到底使用 top 还是 runtimeTop？

2019-10-23 08:47 UTC, pandamicro commented on cocos/ui/components/widget-component.ts
> +        return this.isAbsoluteTop ? this.runtimeTop : this.runtimeTop * 100 / size!.height;
这里直接用 _top 算就行了呀

return this.isAbsoluteTop ? this._top : this._top * 100 / size!.height;

2019-10-23 08:47 UTC, pandamicro commented on cocos/ui/components/widget-component.ts
> +    private _runtimeVerticalCenter = 0;
这直接多加了 12 个属性，对于 WIdget 复杂度增加太多了

2019-10-23 08:47 UTC, pandamicro commented on cocos/ui/components/widget-component.ts
> +            self.runtimeTop -= delta.y * inverseScale.y;
内部函数逻辑，最好不用 setter，有隐含的性能损耗和逻辑，对维护不友好。这里可以写成

self._top -= (self.isAbsoluteTop ? delta.y : deltaInPercent.y) * inverseScale.y;

然后在所有设置完成之后再执行 

this._recursiveDirty();

这样不论是代码清晰度还是效率都会更高

2019-10-24 06:25 UTC, pandamicro commented
要求：
1. 不要增加属性
2. 去除内部函数的 setter / getter 调用

2019-10-25 02:46 UTC, LinYunMo commented
- 如果不添加属性，那么 isAbsolute... 就需要参与到计算中，因为保存值与计算值始终为同一个值，那计算时和保存时就都需要判断 isAbsolute ，但似乎添加属性的代价要更高一些。
 - 去除内部函数的 setter / getter 调用，可以统一内部的赋值操作，去除隐含逻辑。

2019-10-29 06:55 UTC, pandamicro approved these changes

2019-10-29 06:55 UTC, pandamicro commented on cocos/ui/components/widget-manager.ts
> +                widget.horizontalCenter : widget.horizontalCenter / 100 * targetWidth;
同一句代码换行不要顶边，要有缩进

2019-10-29 06:56 UTC, merged