particle frame update optimize
cocos/cocos-engine pull request #5593
Opened 2019-10-23 08:57 UTC by Jno1995

https://github.com/cocos-creator/2d-tasks/issues/1919

2019-10-23 10:03 UTC, SantyWang requested changes

2019-10-23 10:03 UTC, holycanvas commented on cocos2d/particle/particle-simulator.js
> +    if(!this.lastFrameTime) {
这种找两帧最小值的方式还是不够灵活，要不直接限制个最大dt吧，比如 2000 / fps ,最大dt可以在ccgame初始化的时候就计算好了，超过这个值就用最大dt好了，简单一些

2019-10-23 10:14 UTC, Jno1995 commented on cocos2d/particle/particle-simulator.js
> +    if(!this.lastFrameTime) {
如果要限制最大dt的话，会不会有风险？

2019-10-23 10:15 UTC, holycanvas commented on cocos2d/particle/particle-simulator.js
> +    if(!this.lastFrameTime) {
什么风险？

2019-10-23 10:20 UTC, Jno1995 commented on cocos2d/particle/particle-simulator.js
> +    if(!this.lastFrameTime) {
暂时想不出可能性较高的问题，我先试试看。

2019-10-23 11:10 UTC, holycanvas commented on cocos2d/particle/particle-simulator.js
> +    var maxFrameTime = cc.game._frameTime / 1000;
maxFrameTime是阈值，应该要乘以一个倍数，而且不用每帧都算吧，直接把这个变量加到ccgame里面作为一个属性吧

2019-10-23 11:43 UTC, Jno1995 commented on cocos2d/particle/particle-simulator.js
> +    var maxFrameTime = cc.game._frameTime / 1000;
嗯

2019-10-23 11:47 UTC, holycanvas commented on cocos2d/core/CCGame.js
> +        this._maxFrameTime = this._frameTime / 1000;
兄弟，你这里要乘个倍数，比如 * 2，不然怎么是max呢

2019-10-23 12:05 UTC, Jno1995 commented on cocos2d/core/CCGame.js
> +        this._maxFrameTime = this._frameTime / 1000;
>.<

2019-10-23 12:05 UTC, SantyWang approved these changes

2019-10-25 02:40 UTC, jareguo commented on cocos2d/core/CCGame.js
> +        this._maxFrameTime = this._frameTime / 1000 * 1.5;
这里很奇怪，单位跟 frameTime 不一样。frameTime 是 ms，maxFrameTime 是 s……

2019-10-25 02:47 UTC, Jno1995 commented on cocos2d/core/CCGame.js
> +        this._maxFrameTime = this._frameTime / 1000 * 1.5;
嗯，我改下。

2019-10-25 04:06 UTC, jareguo commented on cocos2d/core/CCGame.js
> +    _maxDeltaTime: null,
感觉定义在 director 比较好

2019-10-25 04:07 UTC, Jno1995 commented on cocos2d/core/CCGame.js
> +    _maxDeltaTime: null,
嗯

2019-10-25 11:12 UTC, jareguo commented on cocos2d/core/CCDirector.js
> +        if (this._maxParticleDeltaTime === 0) {
这里不需要每一帧都判断吧，应该可以在引擎初始化的时候直接赋值一次就好，后续在 setFrameRate 的时候再更新

2019-10-25 11:12 UTC, jareguo commented on cocos2d/core/CCGame.js
> +
这个文件没动到就都还原掉吧

2019-10-25 11:12 UTC, jareguo commented on cocos2d/particle/particle-simulator.js
> +    dt = dt > cc.director._maxParticleDeltaTime ? cc.director._maxParticleDeltaTime : dt;
这样处理对原生平台也有效吗？

2019-10-25 12:26 UTC, Jno1995 commented on cocos2d/core/CCDirector.js
> +        if (this._maxParticleDeltaTime === 0) {
嗯  搬到 director 之后没有考虑到这点，我改下。

2019-10-25 12:26 UTC, Jno1995 commented on cocos2d/particle/particle-simulator.js
> +    dt = dt > cc.director._maxParticleDeltaTime ? cc.director._maxParticleDeltaTime : dt;
原生平台有另外对 win32.cpp 的修改

2019-10-25 14:10 UTC, Jno1995 commented
不懂为什么 web 端的 github 过了一端时间 pr 就不能修改文件了。所以我就重新提了一个，
https://github.com/cocos-creator/engine/pull/5625 ，
以后不在 web 端 github 修改 pr 应该就没事了。

2019-10-25 14:10 UTC, closed without merging