add getTotalTime api to CCDirector
cocos/cocos-engine pull request #5598
Opened 2019-10-23 09:56 UTC by Marssssssss

Re: cocos-creator/2d-tasks#1978
新增一个变量来记录游戏开始时间，然后通过用当前时间减去游戏开始时间获得游戏运行到现在总共经过的时间。这个流程已经被封装进了函数 getTotalTime().
Add a new variable to record game's start time, the passed time can be got by using current time minus the variable. And this progress has been packaged into a new function named getTotalTime in this pr.

2019-10-24 01:49 UTC, SantyWang requested changes

2019-10-24 01:49 UTC, holycanvas commented on cocos2d/core/CCDirector.js
> +     * !#zh 获取从游戏开始到现在总共经过的时间
说下单位吧

2019-10-24 01:53 UTC, Marssssssss commented on cocos2d/core/CCDirector.js
> +     * !#zh 获取从游戏开始到现在总共经过的时间
单位为 ms，在注释里面加上了

2019-10-24 02:30 UTC, SantyWang approved these changes

2019-10-25 02:58 UTC, jareguo commented on cocos2d/core/CCDirector.js
> +        this._startTime = performance.now();
这里没必要调用两次 .now 吧，这是 jsb 调用会比较久，this._startTime = this._lastUpdate;

2019-10-25 03:08 UTC, merged