add ui static batch
cocos/cocos-engine pull request #5644
Opened 2019-10-29 13:08 UTC by JoneLau

2019-10-30 03:20 UTC, pandamicro requested changes

2019-10-30 03:20 UTC, pandamicro commented on cocos/core/renderer/ui/ui.ts
> +    public commitStaticComp (comp: UIStaticBatchComponent) {
commitStaticBatch

2019-10-30 03:20 UTC, pandamicro commented on cocos/core/scene-graph/node.ts
> +    public _isStaticUI = false;
像 @YunHsiao 的建议，改为 _static 属性，为未来 3D 也预留好

2019-10-30 03:20 UTC, pandamicro commented on cocos/core/scene-graph/node.ts
> +    public static isNode (obj: object | null): obj is Node {
为什么要这个接口？另外，目前 Scene 已经不继承自 Node 了，所以不需要额外的判断，只需要

obj instanceof Node 

即可

2019-10-30 03:20 UTC, pandamicro commented on cocos/ui/components/ui-static-batch-component.ts
> +export class UIStaticBatchComponent extends UIRenderComponent {
API 说明，尽量写详细一些

2019-10-30 03:21 UTC, pandamicro commented
@zxg0622 审核时多关注内存的管理，尽量不产生垃圾，也不要有泄漏的可能

2019-10-30 05:39 UTC, JoneLau commented on cocos/core/scene-graph/node.ts
> +    public static isNode (obj: object | null): obj is Node {
这个不是新增的，是因为现在的检测规则调整的顺序

2019-10-30 06:54 UTC, zxg0622 commented on cocos/core/renderer/ui/ui.ts
> +    private _defaultBuffer: MeshBuffer | null = null;
_defaultBuffer是什么作用

2019-10-30 06:54 UTC, zxg0622 commented on cocos/core/renderer/ui/ui.ts
> +        this._batches.append(comp.drawBatchList);
这里提交的batch不是空的吗？

2019-10-30 06:54 UTC, zxg0622 commented on cocos/core/renderer/ui/ui.ts
>          this._batches.push(curDrawBatch);
上面提交过一次，这里又提交一次？

2019-10-30 08:45 UTC, JoneLau commented on cocos/core/renderer/ui/ui.ts
> +    private _defaultBuffer: MeshBuffer | null = null;
default 是动态填充的 buffer

2019-10-30 08:46 UTC, JoneLau commented on cocos/core/renderer/ui/ui.ts
> +        this._batches.append(comp.drawBatchList);
不会是空的呀，如果 collect 完之后就有数据了，除非这个静态组件节点下没有子节点

2019-10-30 09:10 UTC, JoneLau commented on cocos/core/renderer/ui/ui.ts
>          this._batches.push(curDrawBatch);
这是第一次收集时候走动态 batch 的数据，肯定第一次要提交，第二次直接给缓存后的数据走的是 commitStaticBatch

2019-10-30 09:54 UTC, zxg0622 commented on cocos/core/renderer/ui/ui.ts
> +    private _defaultBuffer: MeshBuffer | null = null;
所以_currMeshBuffer是用于静态合批，_defaultBuffer用于动态合批？

2019-10-30 09:54 UTC, zxg0622 commented on cocos/core/renderer/ui/ui.ts
>          this._batches.push(curDrawBatch);
静态的DrawBatch也用动态的DrawBatch池来分配，管理起来会不会混乱？

2019-10-30 12:12 UTC, JoneLau commented on cocos/core/renderer/ui/ui.ts
> +    private _defaultBuffer: MeshBuffer | null = null;
不是，一般情况下当前合批的 _currMeshBuffer 使用的都是 _defaultBuffer，在静态合批采集数据的过程中我会把 _currMeshBuffer 设置为静态合批的 buffer，采集结束之后再设置回来

2019-10-30 12:21 UTC, JoneLau commented on cocos/core/renderer/ui/ui.ts
>          this._batches.push(curDrawBatch);
我个人感觉还好，因为原来动态管理上每帧这里使用出去的池数据都会回收，有了静态之后，静态部分的池不回收，由静态组件来控制回收时机，如果不幸遇到池没有退回来的 bug，那静态和动态所面临的结果都是一样。你看看设计上是不是分开比较合理一点，是的话，我也可以做成分开的动静态池。

2019-10-31 05:45 UTC, zxg0622 commented on cocos/core/renderer/ui/ui.ts
>          this._batches.push(curDrawBatch);
我感觉混乱的是meshbuffer，meshbuffer看功能是专门为动态合批提供的，静态合批因为ia是不变的所以可以用model封装，提交时可以走commitModel的逻辑。

2019-10-31 07:48 UTC, zxg0622 requested changes
UI中的_defaultBuffer可以删掉
每个UIStaticBatchComponent应当自己存有drawBatch数组

2019-10-31 09:33 UTC, zxg0622 approved these changes

2019-11-01 08:37 UTC, pandamicro approved these changes

2019-11-01 08:37 UTC, merged