add editorExtends for node and component
cocos/cocos-engine pull request #5659
Opened 2019-10-31 06:54 UTC by gameall3d

Re: cocos-creator/2d-tasks#

Changes:
 * add editorExtends for node and component

2019-10-31 09:11 UTC, pandamicro requested changes

2019-10-31 09:11 UTC, pandamicro commented on cocos/core/scene-graph/base-node.ts
> +    protected _registerIfAttached = !(CC_EDITOR || CC_TEST) ? undefined : function (this: BaseNode, register) {
判断 CC_EDITOR 就行了，不要做 CC_TEST 判断

2019-10-31 09:14 UTC, pandamicro commented on cocos/core/scene-graph/base-node.ts
> +            child._registerIfAttached!(register);
我看了一下 _registerIfAttached 在 onHierarchyChanged 和 _onPreDestroyBase 中触发，但是 _onPreDestroyBase 在 destroy 一个节点的时候会对所有子节点重复调用这个接口，重复触发是否会有问题

2019-10-31 09:18 UTC, gameall3d commented on cocos/core/scene-graph/base-node.ts
> +            child._registerIfAttached!(register);
编辑器有些地方可能需要调整，原来是只有父节点的消息，然后要自己遍历子节点，现在就相当于每个子节点都有消息了，不用自己遍历了，但带来的是添加/删除一个带有很多子节点的节点，就发出很多消息，这边编辑器需要进一步处理~

2019-10-31 09:19 UTC, gameall3d commented on cocos/core/scene-graph/base-node.ts
> +    protected _registerIfAttached = !(CC_EDITOR || CC_TEST) ? undefined : function (this: BaseNode, register) {
creator那边是有的，这边不需要了吗？

2019-10-31 09:20 UTC, pandamicro commented on cocos/core/scene-graph/base-node.ts
> +    protected _registerIfAttached = !(CC_EDITOR || CC_TEST) ? undefined : function (this: BaseNode, register) {
这里不需要了

2019-11-01 02:43 UTC, pandamicro approved these changes

2019-11-01 02:43 UTC, merged