Optimize the performance of zIndex when there are a large number of nodes.
cocos/cocos-engine pull request #5701
Opened 2019-11-07 11:54 UTC by caryliu1999

相关issue Re: cocos-creator/2d-tasks#1186

Changes:

1.延迟localZOrder的更新到sortAllChildren之前。
2.删除之前的childArrivalZOrder的字段，改为使用节点在children里的索引。

问题说明：

测试例：
[testdemo 3.zip](https://github.com/cocos-creator/engine/files/3819390/testdemo.3.zip)

在子节点数量较多时，每帧对所有子节点的zIndex更新时会性能消耗较高，测试1600个节点每帧更新zIndex的性能在Web端，耗时140ms左右，帧率只有7帧。

![image](https://user-images.githubusercontent.com/39078800/68386025-1ce95f80-0196-11ea-9b5e-4be846d7cd9c.png)

耗时主要是在zIndex更新时，会立即同步更新所有子节点的localZOrder，这样在同一时间对所有子节点进行zIndex修改时，这部分的消耗就比较明显。

![image](https://user-images.githubusercontent.com/39078800/68386174-70f44400-0196-11ea-9527-650340d56f5a.png)

优化之后，在web端的表现基本没有性能消耗，Logic的耗时只有2ms左右，帧率也能达到57-60帧。

![image](https://user-images.githubusercontent.com/39078800/68386270-a6009680-0196-11ea-9920-b129321529f2.png)

2019-11-07 13:04 UTC, holycanvas commented on cocos2d/core/CCNode.js
> -                    this._proxy.updateZOrder();
这里删除的原因是？

2019-11-07 13:04 UTC, holycanvas commented on cocos2d/core/CCNode.js
> +        this._parent._delaySort();
一行代码，没必要做成函数了吧

2019-11-07 14:38 UTC, jareguo commented on cocos2d/core/CCNode.js
> +                child._updateOrderOfArrival(i + 1);
我记得以前 _childArrivalOrder 是用来标记节点的激活顺序的，确保节点之间的排序是稳定的。不过看了下现有代码似乎不是这么回事。如果这样的话，这个变量似乎之前就不应该存在呀 @pandamicro 
我能看到的一个问题是，这样一来只要一个节点改变平级顺序，所有同级节点的 SIBLING_ORDER_CHANGED 事件都会触发，这应该是不需要的。

2019-11-07 15:08 UTC, holycanvas commented on cocos2d/core/CCNode.js
> +                child._updateOrderOfArrival(i + 1);
> 我记得以前 _childArrivalOrder 是用来标记节点的激活顺序的，确保节点之间的排序是稳定的。不过看了下现有代码似乎不是这么回事。如果这样的话，这个变量似乎之前就不应该存在呀
 
这个 childArrivalOrder 是我加的，事情是这样的，最开始的时候是没有childArrivalOrder的，当时有一个globalArrivalOrder，全局使用这个变量，而且只增不减，后面斗地主他们那边反馈，他们的节点太多了，随随便便这个globalArrivalOrder就超过 ffff 爆了，后面就增加了一个childArrivalOrder 由父节点维护，就没那么容易溢出，并且加了重新分配的机制，即使溢出了也没事。当时就和刘航讨论过用 children 数组里的 index 来代替这个数值的可能性，但当时不熟，就没敢这么改。然后后面刘航又调整过几次这个arrivalOrder的事，这个arrivalOrder就越来越没用了，现在就想着干脆移除好了，直接用index来代替。

> 我能看到的一个问题是，这样一来只要一个节点改变平级顺序，所有同级节点的 SIBLING_ORDER_CHANGED 事件都会触发，这应该是不需要的。

这个结果和现在的行为是一样的，现在也是一个节点的zIndex变了，会导致全部兄弟节点触发事件。感觉没有必要，但是不太确定优化之后会不会有隐藏问题。

2019-11-07 15:19 UTC, holycanvas commented on cocos2d/core/CCNode.js
> +                child._updateOrderOfArrival(i + 1);
当时的pr，https://github.com/cocos-creator/engine/pull/3720

2019-11-08 01:36 UTC, caryliu1999 commented on cocos2d/core/CCNode.js
> -                    this._proxy.updateZOrder();
> 这里删除的原因是？

adapter层节点init的时候会同步一次ZOrder，然后后续的修改全部通过 SIBLING_ORDER_CHANGED 事件进行同步。

2019-11-08 01:38 UTC, caryliu1999 commented on cocos2d/core/CCNode.js
> +        this._parent._delaySort();
把外部的parent判定移进来了

2019-11-08 01:41 UTC, caryliu1999 commented on cocos2d/core/CCNode.js
> +                child._updateOrderOfArrival(i + 1);
> 我能看到的一个问题是，这样一来只要一个节点改变平级顺序，所有同级节点的 SIBLING_ORDER_CHANGED 事件都会触发，这应该是不需要的。

一个节点修改了zIndex之后，其他平级节点在children中的顺序就不一样了，需要同步更新一下最新的index次序也就是arrivalOrder，现在延迟之后跟排序一样只会执行一次，也还好。

2019-11-08 02:30 UTC, SantyWang requested changes

2019-11-08 02:30 UTC, holycanvas commented on cocos2d/core/CCNode.js
> +        var arrivalOrder = index || (this._parent ? this._parent.children.length + 1 : 1);
这里貌似有点隐患，当 index 传入 0 的时候，arrivalOrder会是1，当 index 传入1的时候，还是1

2019-11-08 02:33 UTC, SantyWang approved these changes

2019-11-08 02:33 UTC, holycanvas commented on cocos2d/core/CCNode.js
> +        var arrivalOrder = index || (this._parent ? this._parent.children.length + 1 : 1);
哦，没有传0

2019-11-08 02:33 UTC, caryliu1999 commented on cocos2d/core/CCNode.js
> +        var arrivalOrder = index || (this._parent ? this._parent.children.length + 1 : 1);
> 这里貌似有点隐患，当 index 传入 0 的时候，arrivalOrder会是 length + 1

这个次序都是从1开始，传进来的最小值是1

2019-11-08 04:23 UTC, jareguo commented on cocos2d/core/CCNode.js
>          this.emit(EventType.SIBLING_ORDER_CHANGED);
目前调用到 _updateOrderOfArrival 的地方好像都不需要触发这个事件了。主要是 sortAllChildren、_onHierarchyChanged（也会调用 sortAllChildren）、_onBatchCreated（场景加载过程中不需要触发事件）。所以建议在 sortAllChildren 的过程中再触发 SIBLING_ORDER_CHANGED

2019-11-08 04:23 UTC, jareguo commented on cocos2d/core/CCNode.js
>          }
这里的改动可能会导致 setSiblingIndex 不会同步触发 SIBLING_ORDER_CHANGED 事件。感觉这个事件的调用还是重新理一理吧。

2019-11-08 08:15 UTC, pandamicro commented on cocos2d/core/CCNode.js
> +        var arrivalOrder = index || (this._parent ? this._parent.children.length + 1 : 1);
如果重复调用这个方法（不传参），可能会导致结果错误吧，因为大家都是使用 length+1 作为 arrival order，那就没意义了

2019-11-08 08:15 UTC, pandamicro commented on cocos2d/core/CCNode.js
>          this.emit(EventType.SIBLING_ORDER_CHANGED);
赞同

2019-11-08 08:15 UTC, pandamicro commented on cocos2d/core/CCNode.js
> +                child._updateOrderOfArrival(i + 1);
我说一下原始的逻辑

在任何节点新增、插入的过程中都会对 arrivalOrder 做更新，这样就可以保障节点按照用户加入的顺序是稳定的，而不会导致每次排序后可能调换位置的可能。js sort 对相同的 value 是不稳定排序

现在的逻辑变成了保障当前顺序不变，结合 insertChild，addChild，setSiblingIndex 的使用，看上去没有问题

2019-11-08 08:16 UTC, pandamicro commented on cocos2d/core/CCNode.js
> +        var arrivalOrder = index || (this._parent ? this._parent.children.length + 1 : 1);
目前引擎中没有这样的调用，不过这算是一个隐患

2019-11-15 08:29 UTC, jareguo commented on cocos2d/core/CCNode.js
> +        var arrivalOrder = index || (this._parent ? this._parent.children.length + 1 : 1);
目前在 _onBatchCreated 调用的时候，由于 parent.children 长度是固定的，所以这里会导致 arrivalOrder 的值都相等。这是不是就有问题了？

2019-11-22 11:36 UTC, caryliu1999 commented on cocos2d/core/CCNode.js
> +        var arrivalOrder = index || (this._parent ? this._parent.children.length + 1 : 1);
> 目前在 _onBatchCreated 调用的时候，由于 parent.children 长度是固定的，所以这里会导致 arrivalOrder 的值都相等。这是不是就有问题了？

_onBatchCreated 里触发节点的 _updateOrderOfArrival 最终产生的zOrder是全部相等的，不过在节点的node-active里会去重置并更新为最新的顺序，但是未激活的情况下就不正确了。这里为了消除这个隐患还是保留了 _childArrivalOrder 字段。

**修改说明：**

1. 保留 _childArrivalOrder ，但是还是删除了 _childArrivalOrder 溢出时的判定，在sortAllChildren里面，进行更新之前重置 _childArrivalOrder 为 1，这样不再传递index，也不需要在每个 _updateOrderOfArrival 里面去做是否溢出的判定。

**补充：**

现在的ArrivalOrder更新行为其实就跟之前保持一致了，只不过改变了重置的时机，保证不会溢出。从最早的globalArrivalOrder到现在的 _childArrivalOrder都没有保证所有状态下的次序稳定，按道理这个 ArrivalOrder 应该是在添加到某个节点下时，设置 1 次，记录添加到其父节点的时机。但是一直以来这个值都会在重排所有子节点时_updateOrderOfArrival里进行全局ArrivalOrder的自增并更新为最新的children顺序，所以目前这个并不是绝对稳定。

举个例子：比如场景创建时子节点 A01, B02, C03, D04 （01，代表zIndex为0，arrival为1），设置C的zIndex为1之后，所有子节点的arrivalOrder重排，次序变为 A01, B02, D03, C14，再重新设置C的zIndex为0之后，最终的顺序就是 A01, B02, D03, C04。虽然这种情况没想到有什么具体的使用场景，但是目前的 ArrivalOrder 只是保证了大部分状态下的次序稳定。

2019-11-22 11:44 UTC, caryliu1999 commented on cocos2d/core/CCNode.js
>          }
> SIBLING_ORDER_CHANGED

![image](https://user-images.githubusercontent.com/39078800/69422817-a2a50780-0d5f-11ea-8ff7-f35894c49681.png)

SIBLING_ORDER_CHANGED 这个事件目前引擎中只有在两个地方派发，一个是设置节点zIndex时，设置的目标节点会立即派发一次该事件，然后就是重排更新所有子节点的localZOrder 时在_updateOrderOfArrival里全部触发子节点的该事件。相比之前全部都是立即触发的，现在在事件的处理上是不会同步。

目前引擎中，JS层没有监听该事件，js-adapter层有监听该事件，保证原生平台能同步localZOrder的更新，然后需要考虑下用户层面监听该事件的使用场景，得保证版本一致。

2019-11-22 11:47 UTC, caryliu1999 commented
@holycanvas 这个PR里面是合并了其他需要在2.2.2更新的几个PR修改吗？

2019-11-22 11:49 UTC, holycanvas commented
不是，rebase的时候带上的，你清理一下

2019-12-12 09:54 UTC, holycanvas commented
应该是合了material的pr冲突了。。。

2019-12-13 10:33 UTC, caryliu1999 commented
已重新提交 https://github.com/cocos-creator/engine/pull/5899，关闭该PR

2019-12-13 10:33 UTC, closed without merging

2019-12-13 12:43 UTC, jareguo commented on cocos2d/core/CCNode.js
>          }
在 2.3 版本更新说明里明确一下吧