add component what 3d node convert to 2d, similar to perspective came…
cocos/cocos-engine pull request #5771
Opened 2019-11-21 08:28 UTC by JoneLau

https://github.com/cocos-creator/3d-tasks/issues/1866

2019-11-25 04:57 UTC, pandamicro requested changes

2019-11-25 04:57 UTC, pandamicro commented on cocos/core/components/map-to-ui-component.ts
> +  @property({
我们用的是四个空格的缩进

2019-11-25 04:57 UTC, pandamicro commented on cocos/core/components/map-to-ui-component.ts
> +      this.node.emit(this._callback, this._transformPos, this._distance / Math.abs(_tempVec3.z));
逻辑上很奇怪，calculateScale 就做计算就好了，为什么由他来调用回调函数

2019-11-25 04:57 UTC, pandamicro commented on cocos/core/components/map-to-ui-component.ts
> +      this.node.emit(this._callback, this._transformPos, this._distance / Math.abs(_tempVec3.z));
另外，回调形式是事件通知，但是属性名 funcName 和 _callback 都不符合事件名的习惯

2019-11-25 04:57 UTC, pandamicro commented on cocos/core/components/map-to-ui-component.ts
> +export class MapToUIComponent extends Component {
MapToUI 听上去不够表意，建议叫 UICoordinateTracker。另外，这个功能的文档需要详细写一下，适合哪种情况，以及案例

2019-11-25 08:41 UTC, JoneLau commented on cocos/core/components/map-to-ui-component.ts
> +  @property({
这个问题要统一上传一下配置，我这里会出现和云潇类似的代码提示问题，代码提示有的时候正常，有的时候过多无用警告，应该是在于 eslint 和 tslint 冲突

2019-11-25 08:43 UTC, JoneLau commented on cocos/core/components/map-to-ui-component.ts
> +export class MapToUIComponent extends Component {
案例已经有了，上方有一个 demo-ui 的更新，文档稍后会补充一份

2019-11-25 16:16 UTC, JoneLau commented on cocos/core/components/map-to-ui-component.ts
> +      this.node.emit(this._callback, this._transformPos, this._distance / Math.abs(_tempVec3.z));
回调方式现在改为组件事件，去掉了 calculateScale 跟坐标转换一起都在 update 里做。这里为什么要做回调说明一下，原因在于自由度问题，我不想知道用户需要操作的对象是谁以及不想强制用户必须用缩放的方式来处理，只想通过一个事件的方式让他自己决定。

2019-11-26 03:48 UTC, pandamicro requested changes

2019-11-26 03:48 UTC, pandamicro commented on cocos/core/components/ui-coodinate-tracker-component.ts
> +    public coodinateDataEvents: EventHandler[] = [];
syncEvents

2019-11-26 03:48 UTC, pandamicro commented on cocos/core/components/ui-coodinate-tracker-component.ts
> +            this.node.emit('coordinate-data', this._transformPos, data);
有了 syncEvents 就不需要 emit 事件了，有一个用法就行

2019-11-26 03:52 UTC, JoneLau commented on cocos/core/components/ui-coodinate-tracker-component.ts
> +            this.node.emit('coordinate-data', this._transformPos, data);
buttoncomponent 也用了同样的方式，是不是也只要一个就够了

2019-11-26 03:56 UTC, pandamicro approved these changes

2019-11-26 03:57 UTC, merged