Typo correctness for some UI files
cocos/cocos-engine pull request #5821
Opened 2019-12-02 10:50 UTC by shrinktofit

2019-12-02 10:50 UTC, shrinktofit commented
Request review from @JoneLau

2019-12-03 02:33 UTC, shrinktofit commented
Close this since delayed to 1.1. @JoneLau

2019-12-03 02:33 UTC, closed without merging

2019-12-03 02:39 UTC, JoneLau requested changes

2019-12-03 02:39 UTC, JoneLau commented on cocos/ui/assembler/label/ttf.ts
> +        // fill index data
indices 吧

2019-12-03 02:39 UTC, JoneLau commented on cocos/ui/assembler/sprite/simple.ts
> +        // fill index data
indices

2019-12-03 02:39 UTC, JoneLau commented on cocos/ui/assembler/utils.ts
> +    // fill index data
indices