Kill INode & IBaseNode
cocos/cocos-engine pull request #5893
Opened 2019-12-13 07:33 UTC by shrinktofit

Commit https://github.com/cocos-creator/engine/commit/2a1b299839e5b31f91e67702cf7c3b0185f30c78 remove INode and IBaseNode, as v1.1 planed;

Commit https://github.com/cocos-creator/engine/commit/00c6e7cde58ae0d5e380af6bfa87a5198724d96e Fix some types error;

Commit https://github.com/cocos-creator/engine/commit/63501587c7d3b6e40fcf9e19c202f211a41769df Fix some .d.ts emit error.

2019-12-18 12:11 UTC, JoneLau approved these changes

2019-12-19 03:32 UTC, pandamicro requested changes

2019-12-19 03:32 UTC, pandamicro commented on cocos/core/platform/view.ts
> +        if (this.setDesignResolutionSize) {
这段不用修改，否则会导致 ci 错误，因为 _resizeEvent 会被注册到 window 事件上，作为回调的 this 不是 view。由于 view 是一个单例，目前不需要做这种判断，直接使用 cc.view 也没问题

2019-12-19 06:17 UTC, pandamicro approved these changes

2019-12-19 06:17 UTC, merged