add compeventtype in component
cocos/cocos-engine pull request #5894
Opened 2019-12-13 08:10 UTC by JoneLau

2019-12-18 13:45 UTC, pandamicro requested changes

2019-12-18 13:45 UTC, pandamicro commented on cocos/ui/components/page-view-component.ts
> +    public static CompEventType = extendsEnum(CompEventType, ScrollCompEventType);
我觉得之前的版本更好啊，为什么要改名为 CompEventType？

2019-12-18 13:45 UTC, pandamicro commented on cocos/ui/components/scroll-view-component.ts
> +    public static CompEventType = CompEventType;
同上 EventType 比 CompEventType 更清晰

2019-12-19 06:03 UTC, JoneLau commented on cocos/ui/components/scroll-view-component.ts
> +    public static CompEventType = CompEventType;
防止用户使用混乱，因为 node 身上有 eventtype，组件身上就统一 compEventType

2019-12-19 06:22 UTC, pandamicro commented on cocos/ui/components/scroll-view-component.ts
> +    public static CompEventType = CompEventType;
不会混乱啊，EventType 是归属于类的，使用的时候不可能脱离本体使用

Node.EventType 和 ScrollView.EventType 都是很清晰的，不用画蛇添足

2019-12-19 06:59 UTC, pandamicro approved these changes

2019-12-19 07:00 UTC, merged