refactor material instance
cocos/cocos-engine pull request #5910
Opened 2019-12-16 10:47 UTC by zxg0622

Re: cocos-creator/2d-tasks#

Changes:
 *

2019-12-16 11:49 UTC, zxg0622 commented
cocos-creator/editor-3d#2807

2019-12-18 01:52 UTC, zxg0622 commented
cocos-creator/3d-tasks#623

2019-12-18 04:10 UTC, pandamicro commented
请修复 ci

2019-12-18 06:27 UTC, zxg0622 commented
这个ci报错不是我的改动引起的

2019-12-18 07:10 UTC, pandamicro commented
rebase 一下就可以了

2019-12-18 08:00 UTC, YunHsiao requested changes

2019-12-18 08:00 UTC, YunHsiao commented on cocos/core/3d/framework/renderable-component.ts
> +    public setMaterial (index: number, material: Material | null) {
这么改有兼容问题啊，参数顺序变了原来代码都跑不了了

2019-12-18 11:32 UTC, zxg0622 commented on cocos/core/3d/framework/renderable-component.ts
> +    public setMaterial (index: number, material: Material | null) {
编辑器支持api升级吗？ @pandamicro

2019-12-18 13:28 UTC, pandamicro commented on cocos/core/3d/framework/renderable-component.ts
> +    public setMaterial (index: number, material: Material | null) {
不支持用户层 API 升级，引擎侧需要做兼容，保留原有 API

2019-12-20 07:36 UTC, pandamicro commented
还需要再 rebase 一下

2019-12-23 08:01 UTC, YunHsiao commented on cocos/core/renderer/core/pass-instance.ts
> +                dest[j] = source[j];
为啥要直接把 view 赋值过来？这样父子 pass UBO 就分不开了啊

2019-12-23 08:01 UTC, YunHsiao commented on cocos/core/renderer/core/pass.ts
>          if (saveOverrides) { this._shader = res.shader; this._bindings = res.bindings; }
这个函数就不用接受任何参数了吧

2019-12-23 08:14 UTC, zxg0622 commented on cocos/core/renderer/core/pass-instance.ts
> +                dest[j] = source[j];
这是复制Float32Array里的元素，不是赋引用

2019-12-23 08:17 UTC, zxg0622 commented on cocos/core/renderer/core/pass.ts
>          if (saveOverrides) { this._shader = res.shader; this._bindings = res.bindings; }
这里写得是有些问题，还需要再改下

2019-12-23 08:24 UTC, YunHsiao commented on cocos/core/renderer/core/material-instance.ts
> +export class MaterialInstance implements IMaterial {
这个类其实可以直接继承 Material

2019-12-23 08:29 UTC, YunHsiao commented on cocos/core/assets/material.ts
> -        this._onPassesChange();
这俩函数可能需要在 material 层就报错了

2019-12-23 08:29 UTC, YunHsiao commented on cocos/core/assets/material.ts
> -        this._onPassesChange();
这俩函数可能需要在 material 层就报错了

2019-12-23 08:33 UTC, zxg0622 commented on cocos/core/renderer/core/material-instance.ts
> +export class MaterialInstance implements IMaterial {
不直接继承Material的原因：
MaterialInstance不是一个Asset
MaterialInstance一部分属性是引用Material的，一部分属性是新建的

2019-12-23 08:34 UTC, YunHsiao commented
又看了下，其实 pass-instance 里也没复用多少数据，基本都是重建的，不如干脆都改继承了

2019-12-23 08:35 UTC, YunHsiao commented
不行就我来改这俩类，你改其他地方的引用

2019-12-23 08:44 UTC, YunHsiao commented on cocos/core/renderer/core/material-instance.ts
> +export class MaterialInstance implements IMaterial {
Asset 那头只要不走基类的生命周函数，应该是没啥消耗的
我看了，material-instance 引用父类的只有一个 effect asset，这个只是个引用，再生成一份也完全没问题，其他新建的属性如果继承的话可以完全沿用父类的机制

2019-12-23 09:34 UTC, zxg0622 commented
model里面createPSO调用tryCompile的地方我用注释// warning:标注了，这个你回头改下 @YunHsiao

2019-12-25 08:18 UTC, YunHsiao approved these changes

2019-12-25 09:17 UTC, pandamicro requested changes

2019-12-25 09:17 UTC, pandamicro commented on cocos/core/3d/framework/model-component.ts
> -    get receiveShadows () {
涉及到对外 API 改动，必须写 deprecated 代码来确保兼容性，并做好必要的数据迁移

2019-12-25 09:17 UTC, pandamicro commented on cocos/core/3d/framework/model-component.ts
> -    set enableDynamicBatching (enable: boolean) {
同上

2019-12-25 09:40 UTC, pandamicro approved these changes

2019-12-25 09:41 UTC, merged