add file of additional properties and transparency downward
cocos/cocos-engine pull request #5948
Opened 2019-12-23 09:16 UTC by JoneLau

closed pr：https://github.com/cocos-creator/engine/pull/5937

2019-12-23 10:00 UTC, pandamicro requested changes

2019-12-23 10:00 UTC, pandamicro commented on cocos/core/renderer/ui/ui.ts
> +        this._lastByteOffset = value;
不应该依赖组件 assembler 中的手动设置，太不可靠了，而且一旦出问题可能导致很严重的问题。应该在 MeshBuffer request 之后自动在 MeshBuffer 中记录，不应该记录在 ui 中

2019-12-23 15:46 UTC, pandamicro approved these changes

2019-12-23 15:47 UTC, merged

2019-12-25 03:37 UTC, pandamicro commented
cocos-creator/3d-tasks#1907
cocos-creator/3d-tasks#2071

2019-12-25 03:59 UTC, JoneLau commented
2071 错了，是关联这个，https://github.com/cocos-creator/engine/pull/5925