Ammo-Wrapper
cocos/cocos-engine pull request #5954
Opened 2019-12-24 07:15 UTC by JayceLai

2019-12-24 08:28 UTC, pandamicro requested changes

2019-12-24 08:28 UTC, pandamicro commented on cocos/physics/ammo/ammo-debugger.ts
> +// import { IGeometry } from '../../core/primitive/define';
这个文件什么情况？全是注释

2019-12-24 08:28 UTC, pandamicro commented on cocos/physics/ammo/ammo-util.ts
> +export function Cocos2AmmoVec3 (out: Ammo.btVector3, v: IVec3Like): Ammo.btVector3 {
这些函数不符合命名规范，小写开头的驼峰式

2019-12-24 08:28 UTC, pandamicro commented on cocos/physics/ammo/shapes/ammo-shape.ts
> +    UP (n: Node) {
不符合命名规范

2019-12-24 08:28 UTC, pandamicro commented on rollup/src/build-engine.ts
> +                '@cocos/ammo': ['Ammo'],
我感觉我们是不是不应该叫 ammo，我们是直接从 bullet 编译的把，按理说跟 ammo 已经没有关系了

2019-12-24 08:28 UTC, pandamicro commented on scripts/module-division/division-config.json
> +                    "text": "ammo.js(beta)",
让编辑器那边把这个功能作为实验功能

2019-12-25 03:10 UTC, JayceLai commented on cocos/physics/ammo/ammo-debugger.ts
> +// import { IGeometry } from '../../core/primitive/define';
这个可能是没合并好，这个文件本来是要删除的

2019-12-25 03:13 UTC, JayceLai commented on rollup/src/build-engine.ts
> +                '@cocos/ammo': ['Ammo'],
> 我感觉我们是不是不应该叫 ammo，我们是直接从 bullet 编译的把，按理说跟 ammo 已经没有关系了

用的是 ammo.js 的编译工具链，直接编译没有ammo.js 的好，很多功能都缺少，特别是暴露接口什么的，ammo.js 可以像写声明文件一样导出接口，直接编译的，接口还要自己写一层封装，特别啰嗦

2019-12-25 03:13 UTC, JayceLai commented on scripts/module-division/division-config.json
> +                    "text": "ammo.js(beta)",
1

2019-12-25 05:53 UTC, JayceLai commented on scripts/module-division/division-config.json
> +                    "text": "ammo.js(beta)",
@VisualSJ  这个怎么加啊?

2019-12-25 09:34 UTC, pandamicro approved these changes

2019-12-25 09:34 UTC, merged