impl window.devicePixelRatio
cocos/cocos-engine pull request #5987
Opened 2019-12-27 10:33 UTC by PatriceJiang

ref https://github.com/cocos-creator/cocos2d-x-lite/pull/2026

2019-12-27 10:53 UTC, pandamicro requested changes

2019-12-27 10:53 UTC, pandamicro commented on cocos2d/core/platform/CCView.js
> -    _t._maxPixelRatio = 2;
这里不要改为 4，我们使用 2 是为了避免性能问题，比如当缩放 3 倍会造成九倍的像素填充

2019-12-30 01:41 UTC, PatriceJiang commented on cocos2d/core/platform/CCView.js
> -    _t._maxPixelRatio = 2;
在 iphone6+ 上,  devicePixelRatio 是 3, 截取这个值会导致屏幕事件的位置计算错误

2019-12-30 01:48 UTC, PatriceJiang commented on cocos2d/core/platform/CCView.js
> -    _t._maxPixelRatio = 2;
可以在 非native 的环境下 限制为2 ?

2019-12-30 08:07 UTC, pandamicro commented on cocos2d/core/platform/CCView.js
> -    _t._maxPixelRatio = 2;
好吧，那可以加一个 CC_JSB 限定条件

2019-12-31 04:04 UTC, pandamicro approved these changes

2020-01-10 03:52 UTC, jareguo approved these changes

2020-01-10 05:57 UTC, merged