fix anim curve generation
cocos/cocos-engine pull request #6077
Opened 2020-01-10 10:03 UTC by YunHsiao

Re: cocos-creator/3d-tasks#

Changelog:
 *

2020-01-10 13:54 UTC, pandamicro requested changes

2020-01-10 13:54 UTC, pandamicro commented on cocos/core/game.ts
> +            } else if (cb) { cb(); }
这种代码别再改来改去了，规范上要求是要换行的

2020-01-11 02:10 UTC, YunHsiao commented on cocos/core/game.ts
> +            } else if (cb) { cb(); }
主要 tslint 会报错，我加了换行

2020-01-12 06:53 UTC, pandamicro approved these changes

2020-01-12 06:54 UTC, merged