lint
cocos/cocos-engine pull request #6122
Opened 2020-01-19 03:16 UTC by shrinktofit

2020-02-08 15:47 UTC, pandamicro requested changes

2020-02-08 15:47 UTC, pandamicro commented on .eslintrc.json
> +                "static-method",
static-method 和 static field 应该提前到跟其他 static 在一起

2020-02-10 06:13 UTC, shrinktofit commented on .eslintrc.json
> +                "static-method",
https://github.com/cocos-creator/engine/pull/6122/commits/d94247d1982679404a57314a2975e0a428e8f6c5

2020-02-11 15:24 UTC, pandamicro approved these changes

2020-02-11 15:24 UTC, merged