disable GL2 on UC
cocos/cocos-engine pull request #6126
Opened 2020-01-19 08:52 UTC by YunHsiao

Re: cocos-creator/3d-tasks#

Changelog:
 *

2020-02-08 15:52 UTC, pandamicro requested changes

2020-02-08 15:52 UTC, pandamicro commented on cocos/core/game.ts
> +                || sys.browserType === sys.BROWSER_TYPE_UC // UC browser implementation doesn't not conform to WebGL2 standard
实际上只要在 iOS 平台上，就可以关闭 useWebGL2，或者任意平台的 UC 浏览器

2020-02-10 02:11 UTC, YunHsiao commented on cocos/core/game.ts
> +                || sys.browserType === sys.BROWSER_TYPE_UC // UC browser implementation doesn't not conform to WebGL2 standard
这就是任意平台的 uc 啊

2020-02-10 02:38 UTC, YunHsiao commented on cocos/core/game.ts
> +                || sys.browserType === sys.BROWSER_TYPE_UC // UC browser implementation doesn't not conform to WebGL2 standard
上面一行的判断是伟亮加的，好像是 mac 的 safari 不能开

2020-02-10 03:02 UTC, pandamicro commented on cocos/core/game.ts
> +                || sys.browserType === sys.BROWSER_TYPE_UC // UC browser implementation doesn't not conform to WebGL2 standard
哦，我以为是判断 iOS safari

2020-02-10 03:02 UTC, pandamicro approved these changes

2020-02-10 03:02 UTC, merged