flexible skinning model
cocos/cocos-engine pull request #6131
Opened 2020-01-21 03:50 UTC by YunHsiao

Re: cocos-creator/3d-tasks#

Changelog:
 *

2020-01-28 05:11 UTC, shrinktofit approved these changes

2020-02-25 12:17 UTC, pandamicro requested changes

2020-02-25 12:17 UTC, pandamicro commented on cocos/core/3d/framework/batched-skinning-model-component.ts
> +        let dataView: DataView;
这个函数已经两百多行了，建议优化拆分一下

2020-02-25 12:17 UTC, pandamicro commented on cocos/core/3d/framework/skinning-model-component.ts
> +    public updateAnimatingMode (baked = true) {
建议这里通过 _modelType 和 this._model 的类型是否匹配来判断，而不是传递一个布尔型参数，语义上不够明确。

或者设计为 updateModelType(mode: ModelType)
通过这种方式对 _modelType 设置的同时更新 model

2020-02-25 12:17 UTC, pandamicro commented on cocos/core/animation/skeletal-animation-component.ts
> +     * @en Transform ouput node.
output node

2020-02-25 12:17 UTC, pandamicro commented on cocos/core/animation/skeletal-animation-component.ts
> + * @zh 骨骼动画组件，控制蒙皮模型的骨骼动画，并提供显式指定的骨骼挂点功能
这个还是比较笼统，建议用列表的形式把这个类的职责列一下

2020-02-25 12:17 UTC, pandamicro commented on cocos/core/animation/skeletal-animation-component.ts
> +     * The joint sockets this animation component maintains.<br>
The joint sockets which this animation component maintains.

2020-02-25 12:17 UTC, pandamicro commented on cocos/core/animation/skeletal-animation-component.ts
> +     * Sockets have to be registered before attaching custom nodes to animated joints.
register where ? need some specification

2020-02-25 12:17 UTC, pandamicro commented on cocos/core/animation/skeletal-animation-component.ts
> +     * 是否使用预烘焙动画，默认启用，可以大幅提高运行效时率，但所有动画效果会被彻底固定，不支持任何形式的编辑。
不支持任何形式的编辑和混合

2020-02-25 12:17 UTC, pandamicro commented on cocos/core/animation/skeletal-animation-component.ts
> +    get bakeAnimations () {
这个属性名看上去容易理解为动作，建议改为 doBakeAnimations 或者 animationsBaked，比较像布尔值属性名

2020-02-25 12:17 UTC, pandamicro commented on cocos/core/animation/skeletal-animation-state.ts
> +        const comps = root.getComponentsInChildren(SkinningModelComponent);
节点树有可能存在动态变化吗？

2020-02-25 12:17 UTC, pandamicro commented on cocos/core/renderer/models/baked-skinning-model.ts
> +        this._type = 'baked-skinning';
建议用一个枚举类型，在 SkinningModel 和 BakedSkinningModel 之间共享，modelType 也可以使用这个类型，而不是类

2020-02-25 12:17 UTC, pandamicro commented on cocos/core/renderer/models/baked-skinning-model.ts
> +        super.destroy();
destroy 过程应该是先销毁自身，最后销毁 super，数据往往是累加关系

2020-02-25 12:17 UTC, pandamicro commented on cocos/core/renderer/models/skeletal-animation-utils.ts
> +    public get (nodeID = '-1') {
不要用 get 这种保留字，getValue、getData 之类的都可以

2020-02-25 12:17 UTC, pandamicro commented on cocos/core/renderer/scene/render-scene.ts
> +        if (m._type === 'default') {
运行时尽量避免字符串比较，这也是为什么推荐用枚举

2020-02-25 13:44 UTC, YunHsiao commented on cocos/core/animation/skeletal-animation-component.ts
> +     * The joint sockets this animation component maintains.<br>
和 the god we trust 一样，这要用 which 还少个介词

2020-02-25 13:47 UTC, YunHsiao commented on cocos/core/animation/skeletal-animation-state.ts
> +        const comps = root.getComponentsInChildren(SkinningModelComponent);
一般这个层级不会有变化

2020-02-26 02:30 UTC, YunHsiao commented on cocos/core/3d/framework/skinning-model-component.ts
> +    public updateAnimatingMode (baked = true) {
动画组件就是一个布尔，这也应该传一个布尔，函数名可以更明确一下

2020-02-26 02:38 UTC, pandamicro commented on cocos/core/3d/framework/skinning-model-component.ts
> +    public updateAnimatingMode (baked = true) {
那可以跟动画组件用一个属性名

2020-02-26 02:44 UTC, pandamicro commented on cocos/core/animation/skeletal-animation-component.ts
> + * @zh 骨骼动画组件，控制蒙皮模型的骨骼动画，并提供显式指定的骨骼挂点功能
骨骼动画组件，他提供的功能包括：

- 控制蒙皮模型的骨骼动画运行
- 提供骨骼挂点功能：通过在动画根节点下挂载挂点节点，并在骨骼动画组件上配置 sockets 列表即可保障挂点节点的 Transform 与骨骼保持同步。

建议的原因有两点：
1. 列表比长句要清晰，更适合文档
2. 显式指定之类的描述在不了解使用方法的开发者阅读的时候是没有任何意义的，文档应该提供更明确的描述，确保初学者能够理解，或者引导到外部使用文档中。

2020-02-26 03:31 UTC, pandamicro approved these changes

2020-02-26 03:32 UTC, merged