complement the 3D UI API
cocos/cocos-engine pull request #6172
Opened 2020-02-14 10:55 UTC by JoneLau

2020-02-25 01:23 UTC, slackmoehrle commented on cocos/core/components/ui-base/canvas-component.ts
> +     * The clearing flags of builtin camera.
The flags to clear the built in camera.

2020-02-25 01:23 UTC, slackmoehrle commented on cocos/core/components/ui-base/canvas-component.ts
> +     * The color clearing value of builtin camera.
The color clearing value of the builtin camera.

2020-02-25 01:23 UTC, slackmoehrle commented on cocos/core/components/ui-base/canvas-component.ts
> +     * When you choose the RenderModel is INTERSPERSE, specifies the render order with other cameras.
When you choose the RenderModel of INTERSPERSE

2020-02-25 01:23 UTC, slackmoehrle commented on cocos/core/components/ui-base/canvas-component.ts
> +     * When you choose the RenderModel is OVERLAY, specifies sorting with the rest of the Canvas.
When you choose the RenderModel of OVERLAY

2020-02-25 01:23 UTC, slackmoehrle commented on cocos/core/components/ui-base/ui-render-component.ts
> + * The shader property type of the material after the instance.
after the instance. --> after instantiation.

what do you think @JoneLau?

2020-02-25 01:23 UTC, slackmoehrle commented on cocos/core/components/ui-base/ui-render-component.ts
> +     * The shader only have color properties.
have -> has

2020-02-25 01:23 UTC, slackmoehrle commented on cocos/core/components/ui-base/ui-render-component.ts
> +     * The shader have color and texture properties.
have -> has

2020-02-25 01:23 UTC, slackmoehrle commented on cocos/core/components/ui-base/ui-render-component.ts
> +     * The shader have color and texture properties and use grayscale mode.
have -> has
use --> uses

2020-02-25 01:23 UTC, slackmoehrle commented on cocos/core/components/ui-base/ui-transform-component.ts
> +     * The contentSize remains the same no matter the node is scaled or rotated.<br/>
no matter -> no matter if

2020-02-25 01:23 UTC, slackmoehrle commented on cocos/core/components/ui-base/ui-transform-component.ts
> +     * All nodes has a size. Layer and Scene has the same size of the screen.
has -> have (both places in this sentence.

2020-02-25 01:23 UTC, slackmoehrle commented on cocos/ui/components/graphics-component.ts
> +     * Adds an circle to the path.
an -> a

2020-02-25 01:23 UTC, slackmoehrle commented on cocos/ui/components/graphics-component.ts
> +     * Adds an rectangle to the path.
an -> a

2020-02-25 01:23 UTC, slackmoehrle commented on cocos/ui/components/graphics-component.ts
> +     * Adds an round corner rectangle to the path.
an -> a

2020-02-25 01:23 UTC, slackmoehrle commented on cocos/ui/components/layout-component.ts
> +     * @en Don't do any scale.
Don't scale

2020-02-25 01:23 UTC, slackmoehrle commented on cocos/ui/components/widget-component.ts
> +     * Vertical aligns the midpoint offset value,
Vertical -> Vertically

2020-02-25 01:23 UTC, slackmoehrle commented on cocos/ui/components/widget-component.ts
> +     * Horizontal aligns the midpoint offset value,
Horizontal -> Horizontally

2020-02-25 01:23 UTC, slackmoehrle commented on cocos/ui/components/widget-component.ts
> +     * Whether the stretched vertically, when enable the left and right alignment will be stretched vertically,
Whether the stretched vertically, when enable the left and right alignment will be stretched vertically,
-->
Whether to stretch vertically, when enabled the left and right alignment will be stretched vertically,

2020-02-25 01:23 UTC, slackmoehrle commented on cocos/ui/components/widget-component.ts
> +     * Whether the stretched horizontally, when enable the left and right alignment will be stretched horizontally,
Whether the stretched horizontally, when enable the left and right alignment will be stretched horizontally,
-->
Whether to stretch horizontally, when enabled the left and right alignment will be stretched horizontally,

2020-02-25 01:23 UTC, slackmoehrle commented on cocos/ui/components/widget-component.ts
> +     * Whether to align the horizontal.
Whether to align the horizontal.
->
Whether to align horizontally.

2020-02-25 01:23 UTC, slackmoehrle commented on cocos/ui/components/widget-component.ts
> +     * Whether to align the vertical.
Whether to align the vertical.
->
Whether to align vertically.

2020-02-25 01:23 UTC, slackmoehrle commented on cocos/ui/components/widget-component.ts
> +     * Whether to align the right.
Whether to align the right.
->
Whether to align to the right.

2020-02-25 01:23 UTC, slackmoehrle commented on cocos/ui/components/widget-component.ts
> +     * Whether to align the left.
Whether to align the left.
->
Whether to align to the left.

2020-02-25 01:23 UTC, slackmoehrle commented on cocos/ui/components/widget-component.ts
> +     * Whether to align the bottom.
Whether to align the bottom.
->
Whether to align to the bottom.

2020-02-25 01:23 UTC, slackmoehrle commented on cocos/ui/components/widget-component.ts
> +     * Whether to align the top.
Whether to align the top.
->
Whether to align to the top.

2020-02-25 01:23 UTC, slackmoehrle commented on cocos/ui/components/widget-component.ts
> +     * @en Alignment vertical.
Align

2020-02-25 01:23 UTC, slackmoehrle commented on cocos/ui/components/widget-component.ts
> +     * @en Alignment horizontal.
Align

2020-02-25 01:23 UTC, slackmoehrle commented on cocos/ui/components/widget-component.ts
> +     * @en Alignment right.
Align

2020-02-25 01:23 UTC, slackmoehrle commented on cocos/ui/components/widget-component.ts
> +     * @en Alignment center.
Align

2020-02-25 01:23 UTC, slackmoehrle commented on cocos/ui/components/widget-component.ts
> +     * @en Alignment left.
Align

2020-02-25 01:23 UTC, slackmoehrle commented on cocos/ui/components/widget-component.ts
> +     * @en Alignment bottom.
Align

2020-02-25 01:23 UTC, slackmoehrle commented on cocos/ui/components/widget-component.ts
> +     * @en Alignment middle.
Align

2020-02-25 01:23 UTC, slackmoehrle commented on cocos/ui/components/widget-component.ts
> +     * @en Alignment top.
Align

2020-02-25 01:24 UTC, slackmoehrle requested changes
See notes for each change.

2020-02-26 06:58 UTC, JoneLau commented on cocos/core/components/ui-base/ui-render-component.ts
> + * The shader property type of the material after the instance.
get it

2020-02-26 07:23 UTC, JoneLau commented
I've updated all the comments，please review them. Thanks. @slackmoehrle

2020-02-28 00:31 UTC, slackmoehrle approved these changes

2020-02-28 04:39 UTC, merged