API docs
cocos/cocos-engine pull request #6174
Opened 2020-02-17 02:34 UTC by YunHsiao

Re: cocos-creator/3d-tasks#

Changelog:
 *

2020-02-17 03:11 UTC, pandamicro commented
@YunHsiao Please do not remove Chinese tooltips yet, we will support i18n localization for them, so that you can move both English and Chinese tooltips into the i18n file

2020-02-17 03:13 UTC, pandamicro commented
@gameall3d will send a PR to create the i18n file, you can then rebase and fill up in this PR

2020-02-17 03:16 UTC, VisualSJ commented on cocos/audio/audio-source-component.ts
> +        tooltip: 'The default AudioClip to play',
这个可以放到 editor/i18n 文件夹里
然后这里用 i18n:xxxx.xxxx
编辑器这里稍后支持。直接删了中文的话，后面弄回来又要蛋疼一次了

2020-02-17 08:41 UTC, CocosLuke reviewed
Here are some changes, most are new wordings, but some include the question of if there should be English in that comment. Thanks.

2020-02-17 08:41 UTC, CocosLuke commented on cocos/audio/assets/clip.ts
> + * The audio clip asset. Every clip handles the low-level affairs itself.
* The audio clip asset. Every clip is handled as a low-level event.

2020-02-17 08:41 UTC, CocosLuke commented on cocos/audio/audio-source-component.ts
> +        tooltip: 'The default AudioClip to play',
Set the default AudioClip to play

2020-02-17 08:41 UTC, CocosLuke commented on cocos/audio/audio-source-component.ts
>       * 是否循环播放音频？
Do you want audio looping of AudioSource?

2020-02-17 08:41 UTC, CocosLuke commented on cocos/audio/audio-source-component.ts
> +     * The default AudioClip to play.
The default AudioClip plays.

2020-02-17 08:41 UTC, CocosLuke commented on cocos/core/3d/framework/batched-skinning-model-component.ts
> +     * @en Convevient setter, copying all the necessary information from target skinning model component.
@en Convenient setter, copying all necessary information from target SkinningModelComponent.

2020-02-17 08:41 UTC, CocosLuke commented on cocos/core/3d/framework/batched-skinning-model-component.ts
> +        tooltip: '',
tooltip: 'The texture attributes that actually participate in the texture of the material, the attributes that are not involved use the texture of the first unit uniformly,'

2020-02-17 08:41 UTC, CocosLuke commented on cocos/core/3d/framework/camera-component.ts
> +     * @en Render priority of the camera, should be statically set in editor. Dynamically changing this property at runtime won't work.
* @en Render priority of the camera, should be statically set in editor. You cannot dynamically change this property at runtime.

2020-02-17 08:41 UTC, CocosLuke commented on cocos/core/3d/framework/camera-component.ts
> +     * @en Screen viewport of the camera wrt. sceen size.
* @en Screen viewport of the camera wrt. The screen size.

2020-02-17 08:41 UTC, CocosLuke commented on cocos/core/3d/framework/camera-component.ts
> +     * @en Scale of the interal buffer size,
* @en Scale of the internal buffer size,

2020-02-17 08:41 UTC, CocosLuke commented on cocos/core/3d/framework/renderable-component.ts
> +     * @en Get material instance of the specified sub-model.
* @en Get the material instance of the specified sub-model.

2020-02-17 08:41 UTC, CocosLuke commented on cocos/core/3d/framework/renderable-component.ts
> +     * @en Set material instance of the specified sub-model.
* @en Set the material instance of the specified sub-model.

2020-02-17 08:41 UTC, CocosLuke commented on cocos/core/3d/framework/sphere-light-component.ts
> +        tooltip: 'The photometric term currently using',
tooltip: 'The photometric term currently being used',

2020-02-17 08:41 UTC, CocosLuke commented on cocos/core/3d/framework/spot-light-component.ts
> +        tooltip: 'The light source size, used for spot and point light',
tooltip: 'The light source size, used for spot and point lights',

2020-02-17 08:41 UTC, CocosLuke commented on cocos/core/3d/framework/spot-light-component.ts
> +        tooltip: 'The light source range, used for spot and point light',
tooltip: 'The light source range, used for spot and point lights',

2020-02-17 08:41 UTC, CocosLuke commented on cocos/core/gfx/buffer.ts
> + * @zh GFX buffer.
* @en GFX buffer.

2020-02-17 08:41 UTC, CocosLuke commented on cocos/core/gfx/device.ts
> +     * @param texture GFX 纹理。
English???

2020-02-17 08:41 UTC, CocosLuke commented on cocos/core/gfx/device.ts
> +     * @param texture GFX 纹理。
English??

2020-02-17 08:41 UTC, CocosLuke commented on cocos/core/gfx/device.ts
> +     * @param regions GFX 缓冲纹理拷贝区域信息。
English??

2020-02-17 08:41 UTC, CocosLuke commented on cocos/core/renderer/models/skinning-model.ts
> + * Skinning model using baked animation.
* The skinning model that is using baked animation.

2020-02-17 10:49 UTC, pandamicro requested changes

2020-02-17 10:49 UTC, pandamicro commented on cocos/core/gfx/binding-layout.ts
> +     * @param buffer GFX 缓冲。
please use English in param, the tool doesn't support localization for @param

2020-02-19 07:53 UTC, YunHsiao commented on cocos/audio/audio-source-component.ts
> +        tooltip: 'The default AudioClip to play',
These comments are for both getter & setter, so I think only the names should be specified.

2020-02-19 09:46 UTC, YunHsiao commented
Sorry for the late update. Fixed aforementioned english parameter, i18n tooltip and wordings.

2020-02-21 02:20 UTC, pandamicro approved these changes

2020-02-21 02:20 UTC, merged