integrate trimesh shape of ammo & cannon
cocos/cocos-engine pull request #6232
Opened 2020-02-26 07:43 UTC by JayceLai

2020-02-26 08:01 UTC, JayceLai commented
初步完成了 ammo 和 cannon 的 trimesh 整合
https://github.com/cocos-creator/3d-tasks/issues/2417

2020-02-26 08:07 UTC, JayceLai commented
相关测试例
https://github.com/cocos-creator/test-cases-3d/pull/181

2020-03-04 02:34 UTC, GengineJS approved these changes

2020-03-04 02:37 UTC, GengineJS approved these changes

2020-03-05 07:34 UTC, JayceLai commented
https://github.com/cocos-creator/3d-tasks/issues/1008

2020-03-11 07:54 UTC, pandamicro requested changes

2020-03-11 07:54 UTC, pandamicro commented on cocos/physics/ammo/ammo-const.ts
> +    emptyShape = new Ammo.btEmptyShape();
Constant 中为啥要一个 emptyShape，不太规范

2020-03-11 07:54 UTC, pandamicro commented on cocos/physics/ammo/ammo-world.ts
> +                    // const shape1 = shared1.wrappedShapes[sIndex1];
不要做这种注释，这代码到底还有没有用？

2020-03-11 07:54 UTC, pandamicro commented on cocos/physics/framework/Physics-selector.ts
> +    trimeshShape?: typeof TrimeshShape
未来会越来越多的，改用一个 config 对象会比较好一些，IPhysicsConfig 类型

2020-03-11 07:54 UTC, pandamicro commented on cocos/physics/framework/components/collider/mesh-collider-component.ts
> +    get trimeshShape (): ITrimeshShape {
叫 shape 不就好了？

2020-03-11 07:54 UTC, pandamicro commented on cocos/physics/framework/instance.ts
> +        warn('[Physics]: Currently builtin unsupport mesh collider');
用 warnID，具体警告信息：

[Physics]: builtin physics system doesn't support mesh collider

2020-03-11 07:54 UTC, pandamicro commented on cocos/physics/framework/instance.ts
> +        warn('[Physics]: Currently cannon.js unsupport capsule collider');
用 warnID，具体警告信息：

[Physics]: cannon.js physics system doesn't support capsule collider

2020-03-11 07:54 UTC, pandamicro commented on cocos/physics/ammo/shapes/ammo-shape.ts
>      __preload (com: ColliderComponent) {
这个 preload 接口命名和组件声明周期函数重名了，虽然确实是在 __preload 阶段调用的，但是它的接口包含参数，和原始接口规范有出入。所以为了避免混淆，应该使用真实的功能来命名，比如 initialize

2020-03-11 07:54 UTC, pandamicro commented on cocos/physics/ammo/shapes/ammo-bvh-triangle-mesh-shape.ts
> +    public get meshCollider () {
我觉得简单的 collider 更好用。目前的使用是 shape.meshCollider 和 shape.sphereCollider 意味着我需要知道 shape 是什么类型，如果统一为 collider 就可以有下面的代码

shape.collider instanceOf SphereColliderComponent

或者用户不需要关心 collider 类型，也可以做一些基本操作，比如 shape.collider.getMask()

2020-03-11 07:54 UTC, pandamicro commented on cocos/physics/ammo/shapes/ammo-bvh-triangle-mesh-shape.ts
> +    public get bvhTriangleMesh () {
建议改为 mesh

和上面的理由同样，概念的抽象应该更通用一些，也应该避免重复。AmmoBvhTriangleMeshShape 类名中已经包含了 BvhTriangleMesh，那么这个属性名中的 bvhTriangle 就比较重复了，同时也破坏了不同 shape 类型之间的代码通用性。

2020-03-11 07:54 UTC, pandamicro commented on cocos/physics/ammo/shapes/ammo-bvh-triangle-mesh-shape.ts
> +    set mesh (v: Mesh | null) {
而且你 setter 命名为 mesh 为啥 getter 不匹配？

2020-03-11 07:54 UTC, pandamicro commented on cocos/physics/cannon/shapes/cannon-trimesh-shape.ts
> +    get trimesh () {
这就很扯了，如果用户切换了物理后端，意味着获取 mesh 的代码还要改

```
shape.trimesh // cannon
shape.bvhTriangleMesh // ammo

2020-03-11 07:54 UTC, pandamicro commented on cocos/physics/cannon/shapes/cannon-trimesh-shape.ts
> +export class CannonTrimeshShape extends CannonShape implements ITrimeshShape {
统一命名，要么 CannonTriangleMeshShape 和 AmmoBvhTriangleMeshShape
要么 CannonTrimeshShape 和 AmmoTrimeshShape

2020-03-11 07:54 UTC, pandamicro commented on cocos/physics/cannon/shapes/cannon-trimesh-shape.ts
> +         */
为啥要在这里加注释，会被解析为 CannonTrimeshShape 的属性的

2020-03-11 07:54 UTC, pandamicro commented on cocos/physics/cannon/shapes/cannon-trimesh-shape.ts
> +         */
如果需要的话，应该把 trimesh 声明为一个类型，在那个类型中声明所有属性

2020-03-11 08:02 UTC, JayceLai commented on cocos/physics/framework/components/collider/mesh-collider-component.ts
> +    get trimeshShape (): ITrimeshShape {
shape 是父类的

2020-03-11 08:11 UTC, JayceLai commented on cocos/physics/ammo/shapes/ammo-bvh-triangle-mesh-shape.ts
> +    set mesh (v: Mesh | null) {
setter 是给组件层调用的，托管执行设置的方法

boxShape，sphereShape, bvhTriangleMesh 这些 getter 是获取底层的实际对象

2020-03-11 08:12 UTC, JayceLai commented on cocos/physics/ammo/shapes/ammo-shape.ts
>      __preload (com: ColliderComponent) {
赞同

2020-03-11 08:18 UTC, JayceLai commented on cocos/physics/cannon/shapes/cannon-trimesh-shape.ts
> +export class CannonTrimeshShape extends CannonShape implements ITrimeshShape {
都是按照底层对象来命名的，Ammo 目前封装的是 btBvhTriangleMeshShape ，所以名称是 AmmoBvhTriangleMeshShape

2020-03-11 08:20 UTC, JayceLai commented on cocos/physics/cannon/shapes/cannon-trimesh-shape.ts
> +    get trimesh () {
这一层是实际的物理底层了，用了这些接口就不能切换的，物理引擎层暴露的接口和类型全都不一样的

2020-03-11 12:43 UTC, JayceLai commented on cocos/physics/ammo/ammo-const.ts
> +    emptyShape = new Ammo.btEmptyShape();
这个是为了用于复用的，Ammo的模块现在还不能定义静态变量，只能是成员变量才行，不知道是不是和模块相关的原因，这个不太清楚该怎么改

2020-03-13 06:39 UTC, pandamicro requested changes

2020-03-13 06:39 UTC, pandamicro commented on cocos/physics/ammo/ammo-const.ts
> +    emptyShape = new Ammo.btEmptyShape();
empty shape 如果不可变作为 const 也可以，但是它的命名应该遵循 const 规范：EMPTY_SHAPE

2020-03-13 06:39 UTC, pandamicro commented on cocos/physics/ammo/ammo-rigid-body.ts
> +    }
isSleepy 和 isSleeping 这两个状态有点迷，很难区分，为什么不直接暴露 state 属性？

2020-03-13 06:39 UTC, pandamicro commented on EngineErrorMap.md
> +[Physics][Ammo]: Currently, changing the mesh is not supported if the initialization is complete
changing the mesh is not supported after the initialization is completed

2020-03-13 06:39 UTC, pandamicro commented on cocos/physics/cannon/shapes/cannon-shape.ts
> +        this.setIsTrigger(this._collider.isTrigger);
setAsTrigger

2020-03-13 06:39 UTC, pandamicro commented on cocos/physics/cannon/shapes/cannon-trimesh-shape.ts
> +    private updateInternalMesh (vertices: Float32Array, indices: Uint16Array) {
private 函数以下划线开头

2020-03-13 06:39 UTC, pandamicro commented on cocos/physics/framework/components/rigid-body-component.ts
> +            this._body.setFixedRotation(value);
fixRotation 即可

2020-03-13 06:39 UTC, pandamicro commented on cocos/physics/framework/components/rigid-body-component.ts
> +            this._body.setUseGravity(value);
useGravity 这种动词开头转换成函数就行了，不需要加 set

2020-03-13 08:26 UTC, JayceLai commented on cocos/physics/ammo/ammo-rigid-body.ts
> +    }
这个状态是物理引擎底层定义的，是有点难区分

不暴露 state 主要是因为物理底层的 State 属性的定义不一样，
cannon 是 [0, 1, 2] => [awake, sleepy, sleeping] 
ammo 是 [0, 1, 2] => [awake, sleeping, sleepy] 

而且 ammo 的 state 类型更多
```
#define ACTIVE_TAG 1
#define ISLAND_SLEEPING 2
#define WANTS_DEACTIVATION 3
#define DISABLE_DEACTIVATION 4
#define DISABLE_SIMULATION 5
```

感觉目前这样是比较好的方式

2020-03-15 11:40 UTC, pandamicro approved these changes

2020-03-15 11:41 UTC, merged