Catch common target initialization error
cocos/cocos-engine pull request #6246
Opened 2020-02-27 10:24 UTC by shrinktofit

Re: cocos-creator/2d-tasks#

Changes:
 * This should fix that engine would hang up if there is an error thrown during initialization of animation common target.

2020-02-28 04:36 UTC, pandamicro requested changes

2020-02-28 04:36 UTC, pandamicro commented on cocos/core/animation/animation-state.ts
> +                return null;
try catch 逻辑限定在编辑器下，运行时不要有任何 try catch 逻辑

2020-02-28 04:36 UTC, pandamicro commented on cocos/core/animation/animation-state.ts
>              try {
同上

2020-02-28 10:19 UTC, shrinktofit commented on cocos/core/animation/animation-state.ts
> +                return null;
已修改

2020-02-28 10:19 UTC, shrinktofit commented on cocos/core/animation/animation-state.ts
>              try {
已修改

2020-03-01 15:18 UTC, pandamicro commented
ci 挂了哦

2020-03-02 11:31 UTC, pandamicro requested changes

2020-03-02 11:31 UTC, pandamicro commented on cocos/core/animation/bound-target.ts
> +export function BoundTarget (target: any, modifiers: TargetPath[], valueAdapter?: IValueProxyFactory): null | IBoundTarget {
函数命名有问题，BoundTarget 会让人误认为是 class，如果是这种工具函数，应该使用 createBoundTarget 之类的名字，并且保证首字母小写

2020-03-02 11:31 UTC, pandamicro commented on cocos/core/animation/bound-target.ts
> +export function BufferedTarget (target: any, modifiers: TargetPath[], valueAdapter?: IValueProxyFactory): null | IBufferedTarget {
同上

2020-03-03 05:19 UTC, pandamicro approved these changes

2020-03-03 05:19 UTC, merged