add hit normal to ray result
cocos/cocos-engine pull request #6258
Opened 2020-03-02 07:25 UTC by JayceLai

2020-03-02 07:26 UTC, JayceLai commented
https://github.com/cocos-creator/3d-tasks/issues/2594

2020-03-05 06:19 UTC, gameall3d requested changes

2020-03-05 06:19 UTC, gameall3d commented on cocos/physics/framework/physics-ray-result.ts
>          return this._collidier!;
这个collider拼错了。。。

2020-03-10 06:32 UTC, gameall3d approved these changes
LGTM

2020-03-11 07:59 UTC, merged