Small fixes
cocos/cocos-engine pull request #6272
Opened 2020-03-03 06:13 UTC by shrinktofit

Re: cocos-creator/3d-tasks#

Changelog:
 * Some small fixes.

2020-03-05 06:11 UTC, pandamicro requested changes

2020-03-05 06:11 UTC, pandamicro commented on cocos/core/animation/animation-state.ts
> +        toRatio: number;
这不对把，这又不是一个类

2020-03-05 06:11 UTC, pandamicro commented on cocos/core/animation/value-proxy-factories/uniform.ts
> +                warn(`Illegal texture default value: ${texName}.`);
添加到 ErrorMap 里面

2020-03-16 03:41 UTC, shrinktofit commented on cocos/core/animation/animation-state.ts
> +        toRatio: number;
interface 也要用分号的

2020-03-16 03:43 UTC, shrinktofit commented on cocos/core/animation/value-proxy-factories/uniform.ts
> +                warn(`Illegal texture default value: ${texName}.`);
这个先通过下，然后让 @YunHsiao  来改，它加的内容。

2020-03-16 03:57 UTC, pandamicro approved these changes

2020-03-16 03:58 UTC, merged