Retina issue
cocos/cocos-engine pull request #6276
Opened 2020-03-03 11:08 UTC by Mee-gu

基于@PatriceJiang 修改的[PR](https://github.com/cocos-creator/cocos2d-x-lite/pull/2081)

2020-03-06 14:14 UTC, pandamicro requested changes

2020-03-06 14:14 UTC, pandamicro commented on cocos/core/platform/view.ts
> +            devicePixelRatio = _view._devicePixelRatio = Math.min(_view._maxPixelRatio, window.devicePixelRatio || 1);
既然修改了 _maxPixelRatio 应该就不需要在这里做分支了

2020-03-06 14:14 UTC, pandamicro commented on cocos/core/platform/view.ts
> -            locFrameSize.height = w;
这里不能这么改，首先我们应该遵循始终使用 view._devicePixelRatio，另外，这样修改在 web 端会有兼容性问题，web 端的 frame 是不考虑 devicePixelRatio 的，是 dom 节点下的尺度，如果 JSB 需要处理应该定制 __BrowserGetter.availWidth 和 availHeight

2020-03-06 14:14 UTC, pandamicro commented on cocos/core/platform/view.ts
> -            this._setupContainer(_view, _view._frameSize.width, _view._frameSize.height);
这里同样不应该做除法

2020-03-11 09:42 UTC, Mee-gu commented on cocos/core/platform/view.ts
> -            locFrameSize.height = w;
由于 frame 和 canvas 都是在 JSB 下是同一个对象，需要考虑 dpr

2020-03-11 09:42 UTC, Mee-gu commented on cocos/core/platform/view.ts
> -            this._setupContainer(_view, _view._frameSize.width, _view._frameSize.height);
同上

2020-03-16 10:32 UTC, pandamicro commented on cocos/core/platform/view.ts
> +        if (!_view._orientationChanging && _view._isRotated === prevRotated && _view._prevCanvasSize.width === curCanvasW && _view._prevCanvasSize.height === curCanvasH) {
依赖 setCanvasSize 好像没有保障，setCanvasSize 引擎是没有调用的，是 jsb adapter 调用吗？

2020-03-17 01:51 UTC, pandamicro approved these changes

2020-03-17 01:51 UTC, merged