fix reset of array collision matrix
cocos/cocos-engine pull request #6299
Opened 2020-03-06 15:15 UTC by JayceLai

2020-03-07 14:59 UTC, pandamicro requested changes

2020-03-07 14:59 UTC, pandamicro commented on cocos/physics/utils/array-collision-matrix.ts
> +        for (let i in this.matrix) {
对数组的遍历不要改为 for in

2020-03-07 14:59 UTC, pandamicro commented on cocos/physics/cocos/builtin-world.ts
> +        this._collisionMatrix.matrix = [];
用类似 ring buffer 的形式，在两个数组之间切换，不要重复创建数组对象

```
let mat = this._collisionMatrixPrev.matrix;
mat.length = 0;
this._collisionMatrixPrev.matrix = this._collisionMatrix.matrix;
this._collisionMatrix.matrix = mat;
```

2020-03-09 07:03 UTC, JayceLai commented on cocos/physics/cocos/builtin-world.ts
> +        this._collisionMatrix.matrix = [];
嗯嗯，用 ring buffer 的形式把结构改了，两个对象分别指向一段内存的上下部分，每帧只是交换位置

2020-03-10 15:44 UTC, pandamicro reviewed
从框架设计角度来说，有两种方案：

1. 保持简单，因为这里只需要 prev 和 curr，那么用两个对象互相切换即可，切换时之前的 prev 被 reset，prev 指向当前 curr，一个简单的 switch，这样对 CollisionMatrix 不需要任何改动，代码逻辑也清晰明了。
2. 抽象通用 RingBuffer，ringbuffer 是可以指定尺寸的，也可以支持各种不同的 buffer 对象，只要这些 buffer 对象实现了 IRingBufferItem 的 interface（指定存取接口），RingBuffer 的职责只是做 buffer 轮转，不需要关心 item 里面的存取方法。而这个结构应该存在 memop 模块中

一种简单直接，另一种通用性好

2020-03-10 15:44 UTC, pandamicro commented on cocos/physics/utils/array-collision-matrix.ts
> +    public getFromSwap (i: number, j: number): number {
swap 的语义容易被理解为不被使用的一段，因为被 swap off 了，用这个单词看起来很奇怪。

2020-03-10 15:44 UTC, pandamicro commented on cocos/physics/utils/array-collision-matrix.ts
> + * 以无符号整型为索引的数组碰撞矩阵，存储值范围为 Uint8，使用 ring-buffer 结构，以两倍的大小自动增长；
目前整个类的设计感觉很奇怪是因为本来这个类只是一段包含 collision matrix 的 buffer，现在把 ringbuffer 给融到了里面，总体设计上来说有几个问题：

1. 目的不够单一，一段 buffer 融合了多 buffer 切换和访问的需求
2. 扩展性不够好，目前的设计只支持两段 buffer 切换
3. 两段 buffer 的存取方法不统一，创造了两套方法来做存取，swap 之后使用者还需要记着应该使用 get 还是 getFromSwap，很不方便

2020-03-10 15:44 UTC, pandamicro commented on cocos/physics/cocos/builtin-world.ts
> +        this._collisionMatrix.swap();
我本来的意思是这里简单做两个 CollisionMatrix 的切换即可，不用创建，没想到变成这么复杂的实现

2020-03-11 06:31 UTC, pandamicro approved these changes

2020-03-11 06:31 UTC, merged