en api docs for primitives
cocos/cocos-engine pull request #6306
Opened 2020-03-09 10:56 UTC by JayceLai

2020-03-09 10:56 UTC, JayceLai commented
https://github.com/cocos-creator/3d-tasks/issues/2506

2020-03-10 17:21 UTC, slackmoehrle requested changes

2020-03-10 17:21 UTC, slackmoehrle commented on cocos/core/primitive/box.ts
> + * but may be repositioned through `center` option.
through the `center`

2020-03-10 17:21 UTC, slackmoehrle commented on cocos/core/primitive/capsule.ts
> + * but may be repositioned through `center` option).
through the `center`

2020-03-10 17:21 UTC, slackmoehrle commented on cocos/core/primitive/circle.ts
> + * but may be repositioned through `center` option.
through the `center`

2020-03-10 17:21 UTC, slackmoehrle commented on cocos/core/primitive/cone.ts
> + * but may be repositioned through `center` option.
through the `center`

2020-03-10 17:21 UTC, slackmoehrle commented on cocos/core/primitive/cylinder.ts
> + * but may be repositioned through `center` option.
through the `center`

2020-03-11 23:45 UTC, slackmoehrle approved these changes

2020-03-15 12:14 UTC, merged