[Not marge now] Sprite Frame change
cocos/cocos-engine pull request #6336
Opened 2020-03-16 04:11 UTC by LinYunMo

Re: https://github.com/cocos-creator/3d-tasks/issues/2621
Re：https://github.com/cocos-creator/3d-tasks/issues/2127

2020-03-16 04:16 UTC, LinYunMo commented
RE: https://github.com/cocos-creator/editor-3d/pull/3200

2020-03-18 12:15 UTC, LinYunMo commented
@pandamicro @JoneLau please review this PR

2020-03-19 06:46 UTC, pandamicro requested changes

2020-03-19 06:46 UTC, pandamicro commented on cocos/core/assets/sprite-frame.ts
> +        if(data.texture){
注意代码规范，有问题的地方不少，检查一下

if (data.texture) {

2020-03-19 06:46 UTC, pandamicro commented on cocos/core/assets/sprite-frame.ts
> -            this.onLoaded();
难保上层有没有监听 SpriteFrame load 事件的，如果现在 texture 不需要等待，就要在 SpriteFrame 创建后主动派发一次 load 事件

2020-03-19 06:46 UTC, pandamicro commented on cocos/core/assets/sprite-frame.ts
> +    public getGFXSampler (){
直接用 getSampler 就好

2020-03-19 06:46 UTC, pandamicro commented on cocos/core/assets/texture-base.ts
> +        if(this._getGFXDevice()) {
两次调用 _getGFXDevice 很没必要，先调用函数获取 device，然后重复使用即可

2020-03-19 06:46 UTC, pandamicro commented on cocos/core/assets/texture-base.ts
> +           this._gfxSampler = samplerLib.getSampler(this._getGFXDevice()!, this._samplerHash);
这里又没有先判断 device 是否存在，samplerLib.getSampler 有没有做容错？

2020-03-19 06:46 UTC, pandamicro commented on cocos/ui/components/sprite-component.ts
> +        if (!spriteFrame || !spriteFrame.texture) {
这个判断和之前并不完全等价，texture 只能代表 JS 对象存在，textureLoaded() 判断的是 GPU 贴图是否存在

2020-03-19 06:46 UTC, pandamicro commented on cocos/core/assets/sprite-frame.ts
> -            this.onLoaded();
同时，因为 load 不再能表示 texture 是否已经加载好并上传 GPU，要确保 textureLoaded 接口返回的状态是正确的

2020-03-19 06:46 UTC, pandamicro commented on cocos/ui/components/label-component.ts
> +            if (!spriteFrame || !spriteFrame.texture) {
这两个判断不等价，texture 存在只代表 js 对象存在，textureLoaded 表示的是 texture 已加载到 GPU

2020-03-19 11:43 UTC, LinYunMo commented on cocos/core/assets/sprite-frame.ts
> +    public getGFXSampler (){
此处函数名需为 getGFXSampler ，由于在label component中的texture类型可能为 spriteframe或者为 LetterRenderTexture，在 commitComp 中获取参数时如果函数名不同的话则需要分别处理

2020-03-19 11:43 UTC, LinYunMo commented on cocos/core/assets/texture-base.ts
> +           this._gfxSampler = samplerLib.getSampler(this._getGFXDevice()!, this._samplerHash);
在所有的引擎运行环境中，device 都是存在的，之前的防护是由于在 DB 中会有赋值操作，所以对进行了防护，所以理论上来讲这里并不需要容错，但保险起见添加了容错

2020-03-19 11:43 UTC, LinYunMo commented on cocos/core/assets/sprite-frame.ts
> -            this.onLoaded();
load 事件在 onLoaded 函数中会派发，这时的 spriteframe 已经加载完毕，是正常派发 load 事件的。

2020-03-19 11:43 UTC, LinYunMo commented on cocos/core/assets/sprite-frame.ts
> -            this.onLoaded();
load 始终表示的是资源加载完毕，只是之前的 textureLoaded 的函数返回的是sprite frame 的本身是否加载完毕，在现有结构下， sprite frame 能否渲染其实是由其持有的 texture 决定的，所以应该改为 spf 持有的 texture 的 loaded 参数。

2020-03-19 11:43 UTC, LinYunMo commented on cocos/core/assets/sprite-frame.ts
> +        if(data.texture){
已更正

2020-03-19 15:28 UTC, JoneLau requested changes

2020-03-19 15:28 UTC, JoneLau commented on cocos/core/assets/sprite-atlas.ts
> +            return spriteFrame && spriteFrame.texture.image;
现在返回的应该是 texture 才对

2020-03-19 15:28 UTC, JoneLau commented on cocos/ui/components/sprite-component.ts
> +                    material.setProperty('mainTexture', spriteFrame.texture);
这里没必要设置了，整句可以去掉

2020-03-19 15:28 UTC, JoneLau commented on cocos/core/assets/sprite-frame.ts
> +    public getGFXSampler (){
为啥 SpriteFrame 要 getSampler？

2020-03-20 02:44 UTC, JoneLau approved these changes

2020-03-20 05:02 UTC, pandamicro requested changes
我还是觉得延迟加载过程中会有问题。如果 SpriteFrame 没有任何等待 Texture 的机制，那么延迟加载 Texture 的情况下，SpriteFrame 不会更新它的 UV 信息，那么即便贴图上传上去，也会是错误的。
当然我们反序列化的时候会有 UV 信息，但是这并不是永远可靠的

2020-03-20 05:02 UTC, pandamicro commented on cocos/core/assets/texture-base.ts
> +                console.error('Can`t getGFXSampler with out device!')
用 errorID

2020-03-20 05:02 UTC, pandamicro commented on cocos/ui/components/sprite-component.ts
> +                    // material.setProperty('mainTexture', spriteFrame.texture);
为什么不需要更新了？

2020-03-20 06:08 UTC, LinYunMo commented on cocos/ui/components/sprite-component.ts
> +                    // material.setProperty('mainTexture', spriteFrame.texture);
由于 UI  的合批设置，对单个材质的 setProperty 实际是无效的，最终上传的还是当前的 textureView

2020-03-20 11:25 UTC, pandamicro requested changes
建议改一下 linter

2020-03-20 11:25 UTC, pandamicro commented on cocos/core/assets/sprite-frame.ts
> +        this._texture = value;
这样代码多余了

2020-03-20 11:25 UTC, pandamicro commented on cocos/core/assets/sprite-frame.ts
> +            handle.result.push(this, '_textureSource',data.texture);
, 后面少了一个空格

2020-03-20 11:25 UTC, pandamicro commented on cocos/core/assets/sprite-frame.ts
> +        if(texture.loaded) {
格式

2020-03-20 11:25 UTC, pandamicro commented on cocos/core/assets/sprite-frame.ts
> +            texture.once('load',this._textureLoaded,this);
格式

2020-03-20 11:37 UTC, pandamicro approved these changes

2020-03-20 11:37 UTC, merged