En api physics
cocos/cocos-engine pull request #6467
Opened 2020-04-01 06:40 UTC by JayceLai

Re: cocos-creator/3d-tasks#2506

Changes:
 *

2020-04-01 19:02 UTC, slackmoehrle requested changes
Just a few changes. Nice work.

只是一些更改。 辛苦了

2020-04-01 19:02 UTC, slackmoehrle commented on cocos/physics/framework/assets/physic-material.ts
> +     * Gets all physical material instances.
physical or physics?

2020-04-01 19:02 UTC, slackmoehrle commented on cocos/physics/framework/components/collider/box-collider-component.ts
> +     * Gets or set the size of the box, in local space.
It should be either:
Gets or sets
__or__
Get or set

2020-04-01 19:02 UTC, slackmoehrle commented on cocos/physics/framework/components/collider/capsule-collider-component.ts
> +     * Gets or set the radius of the sphere on the capsule body, in local space.
It should be either:
Gets or sets
__or__
Get or set

2020-04-01 19:02 UTC, slackmoehrle commented on cocos/physics/framework/components/collider/capsule-collider-component.ts
> +     * Gets or set the capsule body is at the corresponding axial height, in local space.
It should be either:
Gets or sets
__or__
Get or set

2020-04-01 19:02 UTC, slackmoehrle commented on cocos/physics/framework/components/collider/capsule-collider-component.ts
> +     * Gets or set the capsule direction, in local space.
It should be either:
Gets or sets
__or__
Get or set

2020-04-01 19:02 UTC, slackmoehrle commented on cocos/physics/framework/components/collider/collider-component.ts
> +     * Gets or set the collider is trigger, this will be always trigger if using builtin.
It should be either:
Gets or sets
__or__
Get or set

2020-04-01 19:02 UTC, slackmoehrle commented on cocos/physics/framework/components/collider/collider-component.ts
> +     * Gets or set the center of the collider, in local space.
It should be either:
Gets or sets
__or__
Get or set

2020-04-01 19:02 UTC, slackmoehrle commented on cocos/physics/framework/components/rigid-body-component.ts
> +     * Apply force to a world point. This could for example be a point on the Body surface.
could for example --> could, for example,

2020-04-01 19:02 UTC, slackmoehrle commented on cocos/physics/framework/components/rigid-body-component.ts
> +     * Apply force to a local point. This could for example be a point on the Body surface.
could for example --> could, for example,

2020-04-01 19:02 UTC, slackmoehrle commented on cocos/physics/framework/physics-interface.ts
> +     * The aother collider component instance in the event.
The aother collider component instance in the event.
-->
Trigger another collider in event.

2020-04-01 19:02 UTC, slackmoehrle commented on cocos/physics/framework/physics-interface.ts
> +     * The aother collider component instance in the event.
The aother collider component instance in the event.
-->
Another collider in collision.

2020-04-01 19:02 UTC, slackmoehrle commented on cocos/physics/framework/physics-ray-result.ts
> + * Used to store physical ray test results.
physical or physics?

2020-04-02 07:36 UTC, JayceLai commented
> Just a few changes. Nice work.
> 
> 只是一些更改。 辛苦了

thank you.

2020-04-02 17:26 UTC, slackmoehrle commented on cocos/physics/framework/components/collider/collider-component.ts
> +     * Gets or set the collider is trigger, this will be always trigger if using builtin.
no, sorry. singular for both or plural for both.
Gets or sets
__or__
Get or set

两个词都必须是单数或两个词都必须是复数.

2020-04-02 17:27 UTC, slackmoehrle commented on cocos/physics/framework/components/collider/collider-component.ts
> +     * Gets or set the center of the collider, in local space.
no, sorry. singular for both or plural for both.
Gets or sets
__or__
Get or set

两个词都必须是单数或两个词都必须是复数.

2020-04-02 17:27 UTC, slackmoehrle requested changes
just 2 changes left. I think we may have had a communication snafu.

2020-04-03 07:32 UTC, JayceLai commented
> just 2 changes left. I think we may have had a communication snafu.

Sorry, I missed these two changes.

2020-04-03 07:41 UTC, JayceLai commented on cocos/physics/framework/components/collider/collider-component.ts
> +     * Gets or set the center of the collider, in local space.
this is outdated, please review newest commits.

2020-04-03 07:41 UTC, JayceLai commented on cocos/physics/framework/components/collider/collider-component.ts
> +     * Gets or set the collider is trigger, this will be always trigger if using builtin.
this is outdated, please review newest commits.

2020-04-03 22:47 UTC, slackmoehrle approved these changes
Nice work. Thank you for your effort.

辛苦了 感谢你的付出。

2020-04-03 22:47 UTC, slackmoehrle commented
@pandamicro this is ready for merge.

2020-04-05 08:20 UTC, pandamicro commented
Thank you both for the great translation and review

2020-04-05 08:20 UTC, merged