capsule collider refactor
cocos/cocos-engine pull request #6484
Opened 2020-04-03 07:10 UTC by JayceLai

Re: cocos-creator/3d-tasks#2909

Changes:
 * capsule collider refactor, using cylinder height.

2020-04-05 08:28 UTC, pandamicro requested changes
还需要 rebase

2020-04-05 08:28 UTC, pandamicro commented on cocos/physics/ammo/shapes/ammo-capsule-shape.ts
> +    setCylinderHeight (v: number) {
没有看到 API 迁移

2020-04-07 02:30 UTC, JayceLai commented on cocos/physics/ammo/shapes/ammo-capsule-shape.ts
> +    setCylinderHeight (v: number) {
setHeight API 保留了，这里只是提供了一个新的

2020-04-07 03:42 UTC, pandamicro approved these changes

2020-04-07 03:42 UTC, merged