math lib api translate
cocos/cocos-engine pull request #6495
Opened 2020-04-06 07:01 UTC by LinYunMo

Re: https://github.com/cocos-creator/3d-tasks/issues/2506

2020-04-07 03:36 UTC, pandamicro commented
由于 Jason 最近翻译工作量太大，需要我们帮他分担一下审核任务 @YunHsiao

2020-04-07 05:29 UTC, YunHsiao commented on cocos/core/math/affine-transform.ts
> +     * @en Create a identity transformation matrix.
an identity

2020-04-07 05:29 UTC, YunHsiao commented on cocos/core/math/affine-transform.ts
> +     * @en Clone a AffineTransform object from the specified transform.
an affinetransform

2020-04-07 05:29 UTC, YunHsiao commented on cocos/core/math/affine-transform.ts
> +     * @en Concatenate a transform matrix to another.The results are reflected in the out affine transform.
英文标点后面要加空格

2020-04-07 05:29 UTC, YunHsiao commented on cocos/core/math/affine-transform.ts
> +     * This function is memory free, you should create the output vectors by yourself and manage their memory.
does not allocate any memory

2020-04-07 05:29 UTC, YunHsiao commented on cocos/core/math/size.ts
> + * @en new a Size object.
create，new 不是动词

2020-04-09 10:02 UTC, shrinktofit commented on cocos/core/math/affine-transform.ts
> +     * @en Clone a AffineTransform object from the specified transform.
"Clone an affine-transform from" or "Clone an `AffineTransform` object from "

2020-04-09 10:03 UTC, shrinktofit commented on cocos/core/math/size.ts
> + * @en new a Size object.
"Constructs a size object" / "Constructs a `Size` object"

2020-04-12 11:24 UTC, pandamicro commented
@YunHsiao @shrinktofit please check the update and approve if ok

2020-04-13 14:07 UTC, pandamicro requested changes
看了一下，问题还很大，很多句子不符合英语语法，你可以直接用 2.x engine 的翻译，如果有缺失可以暂时空缺，可以由其他人来补

2020-04-13 14:07 UTC, pandamicro commented on cocos/core/math/affine-transform.ts
> +     * @en Apply the `AffineTransform` on a 2D vectors.
on a 2D vector

2020-04-13 14:07 UTC, pandamicro commented on cocos/core/math/affine-transform.ts
> +     * @en Apply the `AffineTransform` on a 2D vectors.
同上，单数

2020-04-14 07:42 UTC, pandamicro requested changes

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/mat3.ts
> +     * @en Matrix transpose array
Transform a matrix object to a flat array

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/mat3.ts
> +     * @en Transfer matrix array
Generates or sets a matrix with a flat array

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/mat3.ts
> +     * @en Transfer matrix array
缺少 out param 注释

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/color.ts
> +     * @en Scales a color by a number.
Multiply all channels in a color with the given scale factor

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/color.ts
> +     * @en Turn an array of colors
Convert a color object to a RGBA array

缺少 out 参数注释

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/color.ts
> +     * @en An array of colors turn
Sets the given color with RGBA values in an array

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/color.ts
> +     * @en Analyzing the equivalent color
Check whether the two given colors are identical

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/color.ts
> +     * @en Negative floating point error is approximately equivalent to determining a color
Check whether the two given colors are approximately equivalent. Difference of each channel is smaller that the epsilon

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/color.ts
> +     * @en convert Color to value.
Convert the given color to a hex color value.

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/color.ts
> +     * @en constructor a color from the specified color.
Construct a same color from the given color

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/color.ts
> +     * @en constructor a color from the hexString.
Construct a color form the hex color string

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/color.ts
> +     * @en constructor a color by the channel value.
Construct a color

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/color.ts
> +     * @en Analyzing the equivalent color
Check whether the current color is identical with the given color

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/color.ts
> +     * @en Transform to string with color informations
Transform -> Convert

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/mat3.ts
> +     * @en Clone a matrix.
最好增加 out 的参数说明

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/mat3.ts
> +     * @en Inverts a matrix.When matrix is not invertible will return a matrix of all zeros.
注意句子之间要有空格

When matrix is not invertible it will return a matrix of all zeros. 或者是
When matrix is not invertible a matrix of all zeros will be returned.

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/mat3.ts
> +     * @en Multiply a matrix with a translation matrix given by a translation offset.
translation vector

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/mat3.ts
>      public static transform <Out extends IMat3Like, VecLike extends IVec3Like> (out: Out, a: Out, v: VecLike) {
这个函数和前面的函数定义重复了

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/mat3.ts
> +     * @en Rotates a matrix by the given angle.
Rotates the transform by the given angle and save the results into a matrix

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/mat3.ts
> +     * @en Copies the upper-left 3x3 values of a 4x4 matrix into a 3x3 matrix.
Copies the first third order matrix of a fourth order matrix to the out third order matrix

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/mat3.ts
> +     * @en Calculates a 3x3 matrix from view direction and up direction.
Sets a third order matrix with view direction and up direction

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/mat3.ts
> +     * @en Creates a matrix from a translation offset.
这些 fromXXX 函数都没有创建对象，所以不要用 create, construct 之类的单词

Sets the given matrix with a translation vector

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/mat3.ts
> +     * @en Creates a matrix from a translation offset.
检查下面其他的

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/mat3.ts
> +     * @en Subtracts matrix b from matrix a.
Subtracts matrix b from matrix a and save the results to out matrix

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/mat3.ts
> +     * @en Subtracts matrix b from matrix a.
很多 API 说明都忽略了 out 参数的作用，会有误导性，可能是因为原始的 API 注释在 2D 分支上没有 out 参数导致的，注意需要调整

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/mat3.ts
> +     * @en Value assigned to element at column 0 row 0.
Value at column 0 row 0 of the matrix.

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/mat3.ts
> +     * @en Set the matrix with value.
Set the matrix with values of all elements

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/mat3.ts
> +     * @en Calculates the current matrix from the given quaternion.
Calculates -> Resets

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/rect.ts
>       * @returns 目标矩形。
参数应该使用英文注释，下同

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/rect.ts
> +     * @en Width and height of the rectangle.
Returns a new {{Size}} object represents the width and height of the rectangle

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/rect.ts
> +     * @en Width and height of the rectangle.
这里的意义是清晰展示内存创建

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/rect.ts
>          return new cc.Vec2(this.x, this.y);
不要用 cc. 引用了，全部转换为导入

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/rect.ts
> +     * @en The X and Y position of the rectangle.
Returns a new {{Vec2}} object represents the position of the rectangle

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/rect.ts
> +     * @en Constructor a Rect from another one.
Constructor 是名词，不是动词，用 Constructs 或者 Creates，下同

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/rect.ts
> + * @en The convenience method to create a new Rect.
convenience 是名词不是形容词，形容词是 convenient

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/size.ts
> + * @en Size
Two dimensional size type representing the width and height.

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/size.ts
> +     * @en width
如果和变量名一样就不需要注释了

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/vec2.ts
> +     * @en Obtaining copy vectors designated
不要用进行时，Obtains a clone of the given vector object

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/vec2.ts
> +     * @en Set to value
Sets the out vector with the given x and y values

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/vec2.ts
> +     * @en Rounding up by elements of the vector
Rounds

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/vec2.ts
> +     * @en The maximum value of the element-wise vector
The maximum value of all elements in the vector

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/vec2.ts
> +     * @en The minimum by-element vector
The minimum value of all elements in the vector

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/vec2.ts
> +     * @en Element-wise vector of rounding to whole
Rounds all elements in the vector to integer

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/vec2.ts
> +     * @en Element-wise vector multiply add: A + B * scale
Element-wise multiplication and addition with the equation: a + b * scale

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/vec2.ts
> +     * @en Seeking two vectors Euclidean distance
Calculates the euclidean distance of two vectors

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/vec2.ts
> +     * @en Euclidean distance squared seeking two vectors
Calculates the squared euclidean distance of two vectors

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/vec2.ts
> +     * @en Seeking vector length
Calculates the length of the vector

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/vec2.ts
> +     * @en Seeking squared vector length
Calculates the squared length of the vector

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/vec2.ts
> +     * @en By taking the negative elements of the vector
Sets each element to its negative value

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/vec2.ts
> +     * @en Element vector by taking the inverse, return near 0 Infinity
Sets each element to its inverse value, zero value will become Infinity

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/vec2.ts
> +     * @en Element vector by taking the inverse, return 0 near 0
Sets each element to its inverse value, zero value will remain zero

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/vec2.ts
> +     * @en Normalized vector
Sets the normalized vector to the out vector

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/vec2.ts
> +     * @en Vector dot product (scalar product)
Calculates the dot product of the vector

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/vec2.ts
> +     * @en Vector cross product (vector product)
Calculates the cross product of the vector

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/vec2.ts
> +     * @en Vector element by element linear interpolation: A + t * (B - A)
Calculates the linear interpolation between two vectors with a given ratio

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/vec2.ts
> +     * @en Generates a uniformly distributed random vectors on the unit sphere
Generates a uniformly distributed random vector points from center to the surface of the unit sphere

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/vec2.ts
> +     * @en vector and matrix multiplication, the default vectors third one.
Vector and third order matrix multiplication, will complete the vector with a third value as one

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/vec2.ts
> +     * @en vector and matrix multiplication, vector third default is 0, vector fourth default is 1.
Vector and third order matrix multiplication, will complete the vector with a third and a fourth element as one

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/vec2.ts
> +     * @en Transform to string with vector informations.
Gets the string representation of the given vector

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/vec2.ts
> +     * @en Vector transfer array
Converts the given vector to an array

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/vec2.ts
> +     * @en Array steering amount
Converts the given array to a vector

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/vec2.ts
> +     * @en Equivalent vectors Analyzing
Check the equality of the two given vectors

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/vec2.ts
> +     * @en Negative error vector floating point approximately equivalent Analyzing
Check whether the two given vectors are approximately equivalent

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/vec2.ts
> +     * @en Radian angle between two vectors seek
Calculates the radian angle between two vectors

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/vec2.ts
> +     * @en clone a Vec3 value
Vec2

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/vec2.ts
> +     * @en Check whether the vector equals another one.
Check whether the vector approximately equals another one.

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/vec2.ts
> +     * @en Check whether the vector equals another one
同上，说明两者参数上的差异

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/vec2.ts
> +     * @en Check whether strict equals other Vec2.
Check whether the current vector strictly equals another Vec2.

strict 是形容词，在动词前应该用副词形式

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/vec2.ts
> +     * @en Check whether strict equals other Vec2.
同上

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/vec2.ts
> +     * @en Adds this vector and returns this.
Adds the current vector with another one and return this

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/vec2.ts
> +     * @en Multiplies two vectors, and returns this.
Multiplies the current vector with another one and return this

这样表述包含了当前 vector 是主体，计算结果会直接保存在当前 vector 中

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/vec2.ts
> +     * @en Divides this vectors element by element, and return this.
Element-wisely divides this vector with another one, and return this.

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/vec2.ts
> +     * @en Negates the components.
Sets each component of this vector with its negative value

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/vec2.ts
> +     * @en Dot product.
Calculates the dot product with another vector

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/vec2.ts
> +     * @en Radian angle between two vectors seek
Calculates radian angle between two vectors

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/vec2.ts
> +     * @en Make the length of this vector to 1.
Normalize the current vector

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/vec2.ts
> +     * @en rotate
Rotates the current vector by an angle in radian value

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/vec2.ts
> +     * @en Projection vector calculated in the vector designated
Projects the current vector on another one

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/quat.ts
> +     * @en Obtaining copy specified quaternion
Obtain a copy of the given quaternion

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/quat.ts
> +     * @en Copy quaternion target
Copy the given quaternion to the out quaternion

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/quat.ts
> +     * @en Provided Quaternion Value
Sets the out quaternion with values of each component

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/quat.ts
> +     * @en The target of an assignment as a unit quaternion
Sets the out quaternion to an identity quaternion

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/quat.ts
> +     * @en Set quaternion rotation is the shortest path between two vectors, the default two vectors are normalized
Sets the out quaternion with the shortest path orientation between two vectors, considering both vectors normalized

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/quat.ts
> +     * @en Get the rotary shaft and the arc of rotation quaternion
Gets the rotation axis and the arc of rotation from the quaternion

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/quat.ts
> +     * @en About the X axis specified quaternion
Sets the out quaternion to represent a radian rotation around x axis

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/quat.ts
> +     * @en Rotation about the Y axis designated quaternion
Sets the out quaternion to represent a radian rotation around y axis

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/quat.ts
> +     * @en Around the Z axis specified quaternion
Sets the out quaternion to represent a radian rotation around z axis

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/quat.ts
> +     * @en Space around the world at a given axis of rotation quaternion
Sets the out quaternion to represent a radian rotation around a given rotation axis in world space

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/quat.ts
> +     * @en Local space around the specified axis rotation quaternion
Sets the out quaternion to represent a radian rotation around a given rotation axis in local space

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/quat.ts
> +     * @en The component w xyz components calculated, normalized by default
Calculates the w component with xyz components, considering the given quaternion normalized

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/quat.ts
> +     * @en Quaternion with two spherical interpolation control points
Spherical quaternion interpolation with two control points

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/quat.ts
> +     * @en Quaternion inverse
Sets the inverse of the given quaternion to out quaternion

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/quat.ts
> +     * @en Conjugating a quaternion, and the unit quaternion equivalent to inversion, but more efficient
Conjugating a quaternion, it's equivalent to the inverse of the unit quaternion, but more efficient

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/quat.ts
> +     * @en Seek length quaternion
Calculates the length of the quaternion

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/quat.ts
> +     * @en Seeking quaternion square of the length
Calculates the squared length of the quaternion

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/quat.ts
> +     * @en Normalized quaternions
Normalize the given quaternion

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/quat.ts
> +     * @en Calculated according to the local orientation quaternion coordinate axis, the default three vectors are normalized and mutually perpendicular
Calculated the quaternion represents the given coordinates, considering all given vectors are normalized and mutually perpendicular

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/quat.ts
> +     * @en The forward direction and the direction of the viewport computing quaternion
Calculates the quaternion with the up direction and the direction of the viewport

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/quat.ts
> +     * @en The quaternion calculated and the arc of rotation of the rotary shaft
Calculates the quaternion from a given rotary shaft and a radian rotation around it.

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/quat.ts
> +     * @en Calculating the three-dimensional quaternion matrix information, default zoom information input matrix does not contain
Calculates the quaternion with the three-dimensional transform matrix, considering no scale included in the matrix

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/quat.ts
> +     * @en The quaternion calculated Euler angle information, rotation order YZX
Calculates the quaternion with Euler angles, the rotation order is XYZ

中文也要修改下

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/quat.ts
> +     * @en This returns the result of the quaternion coordinate system X-axis vector
This returns the X-axis vector of the quaternion

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/quat.ts
> +     * @en This returns the result of the quaternion coordinate system Y axis vector
参考上面

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/quat.ts
> +     * @en This returns the result of the quaternion coordinate system the Z-axis vector
参考上面

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/quat.ts
> +     * @en Quaternion rotation array
Converts quaternion to an array

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/quat.ts
> +     * @en The quaternion calculated Euler angles, return angle x, y in the [-180, 180] interval, z default the range [-90, 90] interval, the rotation order YZX
Converts the quaternion to angles, result angle x, y in the range of [-180, 180], z in the range of [-90, 90] interval, the rotation order is YZX

确认下旋转顺序

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/quat.ts
> +     * @en Analyzing quaternion equivalent
Check whether two quaternions are equal

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/quat.ts
> +     * @en Negative floating point error quaternion approximately equivalent Analyzing
Check whether two quaternions are approximately equal

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/quat.ts
> +     * @en Check whether the quaternion equals another one
Check whether the quaternion approximately equals another one

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/quat.ts
> +     * @en Check whether strict equals other quaternion。
Check whether the current quaternion strictly equals other quaternion

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/quat.ts
> +     * @en Seek length quaternion
Calculates the length of the quaternion

2020-04-14 07:42 UTC, pandamicro commented on cocos/core/math/quat.ts
> +     * @en Seeking quaternion square of the length
Calculates the squared length of the quaternion

2020-04-14 07:43 UTC, pandamicro commented
我没有看 mat4, vec3, vec4，需要自己类比下

2020-04-14 15:52 UTC, LinYunMo commented on cocos/core/math/mat3.ts
>      public static transform <Out extends IMat3Like, VecLike extends IVec3Like> (out: Out, a: Out, v: VecLike) {
没有，上面那个是有拼写错误的函数名，下面这个是对的

2020-05-07 14:01 UTC, pandamicro requested changes

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/affine-transform.ts
>       * @param mat 四维矩阵。
所有 param 注释都需要改成英文

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/affine-transform.ts
> +     * @zh 应用二维仿射变换矩阵到矩形上, 并转换为有向包围盒。
需要增加 param 注释

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/color.ts
> + * Each color component is a floating point value with a range from 0 to 255.<br/>
a floating point value -> an integer value

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/color.ts
> +     * @en Add components of two colors, respectively. And save the results to out color.
Add components of two colors, respectively.
Add two colors by components.

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/color.ts
> +     * @en Subtract components of color b from components of color a, respectively. And save the results to out color.
Subtract each components of color b from each components of color a

感觉 respectively 这样用不是很合适，有没有英文文章或者文档里面类似的用法？

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/color.ts
> +     * @en en Read hex string and store color data into the current color object, the hex string must be formated as rgba or rgb.
多了 en

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/color.ts
> +     * @en en Read hex string and store color data into the current color object, the hex string must be formated as rgba or rgb.
formated -> formatted

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/mat3.ts
> +     * @en Sets the elements of a matrix to the given values and save the results to out matrix
Sets the elements of a matrix with the given values

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/mat3.ts
> +     * @en return an identity matrix.
Reset the out matrix to an identity matrix

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/mat3.ts
> +     * @en Calculates the determinant of a matrix and save the results to out matrix
Calculates the determinant of a matrix

这个函数只是计算出 Determinant，不会修改原始矩阵，这里的 Out 实际上不是结果，按理说应该可以直接用 IMat3Like 作为参数类型

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/mat3.ts
>      public static transform <Out extends IMat3Like, VecLike extends IVec3Like> (out: Out, a: Out, v: VecLike) {
应该用 deprecated 框架来做废弃，否则用户不会注意到 API 文档中的 deprecated 信息的

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/mat3.ts
> +     * @en calculation the upper-left 3x3 values of a 4x4 matrix inverse transpose matrix
Calculates the upper-left 3x3 matrix of a 4x4 matrix's inverse transpose

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/mat3.ts
> +     * @en Inverts the current matrix. When matrix is not invertible a matrix of all zeros will be returned.
When matrix is not invertible the matrix will be set to zeros.

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/rect.ts
> +     * @en Output rect informations to string
Return the information of the current rect in string

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/rect.ts
> +     * @en Returns true if the other rect totally inside this rectangle.
totally -> entirely

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/size.ts
> +     * @en Output size informations to string
Return the information of the current size in string

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/vec2.ts
> +     * @en Obtains a clone of the given vector object and save the results to out vector object
行为上返回的是新的 vector，这里没有 out vector

Obtains a clone of the given vector object

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/vec3.ts
> +     * @en Obtains a clone of the given vector object and save the results to out vector object
Obtains a clone of the given vector object

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/vec3.ts
> +     * @en Element vector by rounding down and save the results to out vector object
不通，仿照其他来写

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/vec3.ts
> +     * @en The minimum by-element vector and save the results to out vector object
Calculates element-wise minimum values and save to the out vector

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/vec3.ts
> +     * @en The maximum value of the element-wise vector and save the results to out vector object
仿照上面

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/vec3.ts
> +     * @en Element-wise vector of rounding to whole and save the results to out vector object
Calculates element-wise round results and save to the out vector

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/vec3.ts
> +     * @en To scale -> rotation -> transformation vector sequence translation
Transforms the current vector with given scale, rotation and translation in order

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/vec3.ts
> +     * @en Translational -> rotation -> Zoom inverse transformation vector sequence
Transforms the current vector with given scale, rotation and translation in reverse order

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/vec3.ts
> +     * @en Rotation vector specified angle about the X axis
Rotates the vector with specified angle around X axis

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/vec3.ts
> +     * @en Rotation vector specified angle around the Y axis
Rotates the vector with specified angle around Y axis

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/vec3.ts
> +     * @en Around the Z axis specified angle vector
Rotates the vector with specified angle around Z axis

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/vec3.ts
> +     * @en Calculating a projection vector in the specified plane
Calculates the projection vector on the specified plane

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/vec3.ts
> +     * @en Projection vector calculated in the vector designated
Calculates the projection on the specified vector

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/vec4.ts
> +     * @en Obtains a clone of the given vector object and save the results to out vector object
Obtains a clone of the given vector object

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/vec4.ts
> +     * @en Rounding up by elements of the vector and save the results to out vector object
Rounding -> Rounds

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/vec4.ts
> +     * @en Element vector by rounding down and save the results to out vector object
Element-wise rounds down of the current vector and save the results to the out vector

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/vec4.ts
> +     * @en The minimum by-element vector and save the results to out vector object
Calculates the minimum values by elements of the vector and save the results to the out vector

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/vec4.ts
> +     * @en The maximum value of the element-wise vector and save the results to out vector object
Calculates the maximum values by elements of the vector and save the results to the out vector

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/vec4.ts
> +     * @en Element-wise vector of rounding to whole and save the results to out vector object
Calculates element-wise round results and save to the out vector

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/vec4.ts
> +     * @en Vector and fourth order matrix multiplication, will complete the vector with a fourth value as one
Vector and fourth order matrix multiplication

Vec4 不需要在补充位了

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/vec4.ts
> +     * @zh 向量与四维矩阵乘法，默认向量第四位为 1。
中文同样有问题

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/vec4.ts
> +     * @en Affine transformation vector
Transform the vector with the given affine transformation

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/vec4.ts
> +     * @en Transform to string with vector informations.
Return the informations of the vector in string

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/vec4.ts
> +     * @en Transforms the vec4 with a mat4. 4th vector component is implicitly '1'
Transforms the vec4 with a mat4

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/mat4.ts
> +     * @en Copy content of a matrix into another and save the results to out matrix
Copy a matrix into the out matrix

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/mat4.ts
> +     * @en Sets the elements of a matrix to the given values and save the results to out matrix
Sets a matrix with the given values

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/mat4.ts
> +     * @en Calculates the determinant of a matrix and save the results to out matrix
Calculates the determinant of a matrix

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/mat4.ts
> +     * @en Multiply two matrices explicitly Calculates the determinant of a matrix and save the results to out matrix
Multiply two matrices and save the results to out matrix

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/mat4.ts
> +     * @en Multiply a matrix with a translation vector given by a translation offset.
Transform a matrix with the given vector and save results to the out matrix

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/mat4.ts
> +     * @en Add new displacement transducer in a matrix transformation on the basis of a given
Transform a matrix with the given translation vector and save results to the out matrix

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/mat4.ts
> +     * @en Add rotational transformation around the X axis at a given matrix transformation on the basis of
Transform a matrix with a given angle around X axis and save the results to the out matrix

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/mat4.ts
> +     * @en Add about the Y axis rotation transformation in a given matrix transformation on the basis of
Transform a matrix with a given angle around Y axis and save the results to the out matrix

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/mat4.ts
> +     * @en Added about the Z axis at a given rotational transformation matrix transformation on the basis of
Transform a matrix with a given angle around Z axis and save the results to the out matrix

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/mat4.ts
> +     * @en Sets the given matrix with a translation vector and save the results to out matrix
Sets the out matrix with a translation vector

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/mat4.ts
> +     * @en Sets the given matrix with a scale vector and save the results to out matrix
Sets the out matrix with a scale vector

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/mat4.ts
> +     * @en Calculating rotation matrix about the Y axis
Calculates the matrix representing a rotation around the Y axis

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/mat4.ts
> +     * @en Calculating rotation matrix about the Z axis
Calculates the matrix representing a rotation around the Z axis

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/mat4.ts
> +     * @en The rotation and displacement information calculating matrix
Calculates the transform representing the combination of a rotation and a translation

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/mat4.ts
> +     * @en Extracting displacement information of the matrix, the matrix transform to the default sequential application S-> R-> T is
Extracts the translation from the matrix, assuming it's composed in order of scale, rotation, translation

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/mat4.ts
> +     * @en Scaling information extraction matrix, the matrix transform to the default sequential application S-> R-> T is
Extracts the scale vector from the matrix, assuming it's composed in order of scale, rotation, translation

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/mat4.ts
> +     * @en Rotation information extraction matrix, the matrix containing no default input scaling information, such as the use of `toRTS` should consider the scaling function.
Extracts the rotation from the matrix, assuming it's composed in order of scale, rotation, translation

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/mat4.ts
> +     * @en en Extracting rotational displacement, zoom information, the default matrix transformation in order S-> R-> T applications
Extracts the scale, rotation and translation from the matrix, assuming it's composed in order of scale, rotation, translation

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/mat4.ts
> +     * @en The rotary displacement, the scaling matrix calculation information, the order S-> R-> T applications
Compose a matrix from scale, rotation and translation, applied in order.

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/mat4.ts
> +     * @en According to the specified rotation, displacement, and scale conversion matrix calculation information center, order S-> R-> T applications
Compose a matrix from scale, rotation and translation, applied in order, from a given origin

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/mat4.ts
> +     * @en Sets the given matrix with the given quaternion and save the results to out matrix
Sets the out matrix with the given quaternion

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/mat4.ts
> +     * @en The matrix calculation information specified frustum
Calculates the matrix representing the given frustum

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/mat4.ts
> +     * @en Perspective projection matrix calculation
Calculates perspective projection matrix

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/mat4.ts
> +     * @en Computing orthogonal projection matrix
Calculates orthogonal projection matrix

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/mat4.ts
> +     * @en `Up` parallel vector or vector center` not be zero - the matrix calculation according to the viewpoint, note` eye
Calculates the matrix with the view point information, given by eye position, target center and the up vector. Note that center to eye vector can't be zero or parallel to the up vector

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/mat4.ts
> +     * @en Reversal matrix calculation and save the results to out matrix
Calculates the inverse transpose of a matrix and save the results to out matrix

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/mat4.ts
> +     * @en Add new displacement transducer in the current matrix transformation on the basis of a given
Translate the current matrix by the given vector

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/mat4.ts
> +     * @en Multiply the current matrix with a scale matrix given by a scale vector.
Multiply the current matrix with a scale vector.

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/mat4.ts
> +     * @en Rotates the current matrix by the given angle.
Rotates the current matrix by the given angle around the given axis

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/mat4.ts
> +     * @en Restore the matrix values from a quaternion rotation, vector translation and vector scale
Resets the matrix values by the given rotation quaternion, translation vector and scale vector

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/quat.ts
> +     * @en Obtain a copy of the given quaternion and save the results to out quaternion
Obtain a copy of the given quaternion

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/quat.ts
> +     * @en Convert quaternion to euler
Convert quaternion to Euler angles

2020-05-07 14:01 UTC, pandamicro commented on cocos/core/math/quat.ts
> +     * @en Seeking quaternion squCalculates the squared length of the quaternion
Calculates the squared length of the quaternion

2020-05-09 04:47 UTC, pandamicro approved these changes

2020-05-09 04:47 UTC, merged