fix skinning model type when not enabled immediately
cocos/cocos-engine pull request #6542
Opened 2020-04-13 09:27 UTC by YunHsiao

Re: cocos-creator/3d-tasks#

Changelog:
 *

2020-04-13 11:16 UTC, pandamicro requested changes

2020-04-13 11:16 UTC, pandamicro commented on cocos/core/3d/framework/skinning-model-component.ts
> +        super.onLoad();
onLoad, init, onEnable 这类初始化函数应该先调用 super 函数，再执行自身逻辑

2020-04-13 11:16 UTC, pandamicro commented on cocos/core/3d/framework/skinning-model-component.ts
> +        this._modelType = modelType;
应该是在全部逻辑执行成功之后，再设置状态会比较好，否则如果中间出现问题中断，会出现状态被错误设置的问题，如果延后设置，出现问题后至少可以再次尝试

2020-04-13 14:43 UTC, YunHsiao commented on cocos/core/3d/framework/skinning-model-component.ts
> +        super.onLoad();
不行，这个是要改 model type，有了 type 才能初始化 model

2020-04-13 14:51 UTC, pandamicro commented on cocos/core/3d/framework/skinning-model-component.ts
> +        super.onLoad();
那是不是应该写在 __preload 中

2020-04-13 15:05 UTC, YunHsiao commented on cocos/core/3d/framework/skinning-model-component.ts
> +        super.onLoad();
__preload 时所有节点和资源都加载完成了吗？

2020-04-14 03:19 UTC, pandamicro commented on cocos/core/3d/framework/skinning-model-component.ts
> +        super.onLoad();
onLoad 和 __preload 都没有全部完成，start 和 onEnable 是全部完成了

2020-04-14 04:04 UTC, pandamicro approved these changes

2020-04-14 04:47 UTC, merged