add forward-pipeline for lighting
cocos/cocos-engine pull request #6596
Opened 2020-04-22 10:24 UTC by troublemaker52025

https://github.com/cocos-creator/3d-tasks/issues/2395
https://github.com/cocos-creator/3d-tasks/pull/3149

2020-04-22 10:49 UTC, YunHsiao requested changes

2020-04-22 10:49 UTC, YunHsiao commented on cocos/core/pipeline/forward/forward-flow.ts
> +        this._rootPipeline = forwardpipeline;
这个有现成的，不需要传

2020-04-22 10:49 UTC, YunHsiao commented on cocos/core/pipeline/forward/forward-stage.ts
> +            this.getFlow().getPipeline().getLightIndices().length;
不要重复调用

2020-04-23 03:32 UTC, minggo commented on cocos/core/pipeline/forward/forward-pipeline.ts
> +     * 获取灯光索引偏移量数组。
这是个数组吗？怎么变量名是 _lightIndexOffset

2020-04-23 03:34 UTC, troublemaker52025 commented on cocos/core/pipeline/forward/forward-pipeline.ts
> +     * 获取灯光索引偏移量数组。
我修改一下

2020-04-23 03:34 UTC, minggo commented on cocos/core/pipeline/forward/forward-stage.ts
> +        this._lightBatchedQueue.forEach(this.lightBatchedQueueClearFunc);
_lightBatchedQueue 本身是一个 queue，不是 queues，为什么会调用 forEach 呢？

2020-04-23 03:35 UTC, troublemaker52025 commented on cocos/core/pipeline/forward/forward-flow.ts
> +        this._rootPipeline = forwardpipeline;
收到

2020-04-23 03:35 UTC, troublemaker52025 commented on cocos/core/pipeline/forward/forward-stage.ts
> +            this.getFlow().getPipeline().getLightIndices().length;
收到

2020-04-23 03:35 UTC, minggo commented on cocos/core/pipeline/forward/forward-stage.ts
> +        this._lightBatchedQueue.forEach(this.lightBatchedQueueClearFunc);
或者是变量名没取好？

2020-04-23 03:36 UTC, troublemaker52025 commented on cocos/core/pipeline/forward/forward-stage.ts
> +        this._lightBatchedQueue.forEach(this.lightBatchedQueueClearFunc);
本身是一个renderQueue[],给每盏灯光分配一个队列

2020-04-23 03:39 UTC, minggo commented on cocos/core/pipeline/forward/forward-stage.ts
> +        }
我不太清楚 ts 是否是动态扩展数组的。我没有看到 _lightBatchedQueue 数组大小初始化的逻辑。

2020-04-23 03:39 UTC, troublemaker52025 commented on cocos/core/pipeline/forward/forward-stage.ts
> +        this._lightBatchedQueue.forEach(this.lightBatchedQueueClearFunc);
> 
> 
> 或者是变量名没取好？

我本来是沿用,前作者的变量名的

2020-04-23 03:42 UTC, minggo commented on cocos/core/pipeline/forward/forward-stage.ts
> +    private _rootFlow: ForwardFlow;
为什么叫 _rootFlow？不能直接叫 _flow ？

2020-04-23 03:42 UTC, troublemaker52025 commented on cocos/core/pipeline/forward/forward-stage.ts
> +        }
这个写法是按照render-stage.ts中构造_renderQueues: RenderQueue[] = [];来实现的,具体是否支持,我再进一步验证

2020-04-23 03:43 UTC, minggo commented on cocos/core/pipeline/forward/forward-stage.ts
> +                            this._lightBatchedQueue[this.getFlow().getPipeline().getLightIndices()[l]].insertRenderPass(ro, m, p);
this.getFlow().getPipeline().getLightIndices() 不需要多次调用，可以先缓存。上面的逻辑也是一样，应该都可以公用。

2020-04-23 03:45 UTC, minggo commented on cocos/core/pipeline/forward/forward-stage.ts
> +import {getPhaseID} from '../pass-phase'
格式最好一致。比如 {} 两边有空格。

2020-04-23 03:49 UTC, troublemaker52025 commented on cocos/core/pipeline/forward/forward-stage.ts
> +import {getPhaseID} from '../pass-phase'
收到

2020-04-23 03:49 UTC, troublemaker52025 commented on cocos/core/pipeline/forward/forward-stage.ts
> +                            this._lightBatchedQueue[this.getFlow().getPipeline().getLightIndices()[l]].insertRenderPass(ro, m, p);
收到

2020-04-23 03:50 UTC, troublemaker52025 commented on cocos/core/pipeline/forward/forward-stage.ts
> +    private _rootFlow: ForwardFlow;
这个写的有问题  已经在改了

2020-04-23 03:51 UTC, minggo commented on cocos/core/pipeline/forward/forward-stage.ts
> +                        //Organization light-batched-queues
Organization 是个 名词

2020-04-23 03:52 UTC, troublemaker52025 commented on cocos/core/pipeline/forward/forward-stage.ts
> +                        //Organization light-batched-queues
确实  我马上改

2020-04-23 04:01 UTC, minggo commented on cocos/core/pipeline/forward/forward-stage.ts
> +        this._lightBatchedQueue.forEach(this.lightBatchedQueueClearFunc);
改成 _lightBatchedQueues？

2020-04-30 06:14 UTC, YunHsiao commented on cocos/core/pipeline/forward/forward-pipeline.ts
> +            this._lightBuffers?.push(lightBuffer);
应该不需要 "?"

2020-04-30 06:14 UTC, YunHsiao commented on cocos/core/pipeline/forward/forward-stage.ts
> +                                    this._lightBatchQueues[lightIndices[l]].add(pass, ro, m, myForward_Light_Sport_Patches);
index 记得 cache

2020-04-30 06:14 UTC, YunHsiao commented on cocos/core/pipeline/render-light-batched-queue.ts
> +                this._psos.push(renderObj.model.createPipelineState(pass, modelIdx, patches));
每个 model 的 pso 都不一样，不能这样复用

2020-04-30 06:14 UTC, YunHsiao commented on cocos/core/pipeline/forward/forward-stage.ts
> +            this._lightBatchQueues[l].updateLightBuffer(lightBuffers[l]);
还是感觉 light pass queue 只需要一个总管理器就行，不需要一个光一个；在 queue 里维护 light buffer 数组和 pso map

2020-05-07 07:35 UTC, pandamicro commented
修改到 3d 分支

2020-05-18 03:28 UTC, pandamicro requested changes

2020-05-18 03:28 UTC, pandamicro commented on cocos/core/pipeline/forward/forward-pipeline.ts
> +            let lightBuffer : GFXBuffer = this._device.createBuffer({
这部分工作应该在 Scene Culling 的时候做就可以了，initialize 的时候应该是没有 validLight 的

2020-05-18 03:28 UTC, pandamicro commented on cocos/core/pipeline/forward/forward-pipeline.ts
> +            if(!this._lightBuffers[l])
这个 buffer 创建的工作也应该在 Scene Culling 的时候做更合适，那个时候是真正处理光源增删的过程

2020-05-18 03:28 UTC, pandamicro commented on cocos/core/pipeline/forward/forward-pipeline.ts
> +    protected lightBufferDestory (lb: GFXBuffer){
protected 和 private 函数名应该加下划线开头，我觉得这个接口比较危险，因为它没有判断这个 buffer 是不是自己创建的 light buffer，如果上层传入任何 GFXBuffer，都会无差别 destroy。

建议在使用的地方直接展开，不要额外加一个遍历函数，简单 for 循环也比 foreach 高效

```
this._lightBuffers.forEach(this.lightBufferDestory);
->
for ( let i = 0; i < this._lightBuffers.length; ++i ) {
    this._lightBuffers[i].destroy();
}
```

2020-05-18 03:28 UTC, pandamicro commented on cocos/core/pipeline/forward/forward-pipeline.ts
> +    public getValidLights () {
建议参考 lightsUBO 属性的设计，用 readonly getter 而不是一个 getXXX 函数。

注意 public 属性放置的位置，应该接在 lightsUBO 后面。

后面几个也同样，lightIndexOffset, lightIndices, lightBuffers

2020-05-18 03:28 UTC, pandamicro commented on cocos/core/pipeline/forward/forward-stage.ts
> +            this._lightBatchQueues.forEach(this.lightBatchQueueClearFunc);
这么简单的实现没必要给这个类增加一个函数，从 forEach 改为简单 for 循环，减少函数调用

2020-05-18 03:28 UTC, pandamicro commented on cocos/core/pipeline/forward/forward-stage.ts
> +        this._lightBatchQueues.forEach(this.lightBatchQueueClearFunc);
同上

2020-05-18 03:28 UTC, pandamicro commented on cocos/core/pipeline/forward/forward-stage.ts
> +            if (!this._lightBatchQueues[l]) {
任何每帧调用的 render, update 等函数中，都应该尽可能简化逻辑，不要有不必要的判断和任何内存创建。考虑将 RenderLightBatchedQueue 的创建移动到 validLights 管理阶段。比如由 forward-pipeline 中的 sceneCulling 调用 forwardStage 中的接口来实现

2020-05-18 03:28 UTC, pandamicro commented on cocos/core/pipeline/render-light-batched-queue.ts
> +        {
我们的代码规范中建议这么写

```
if (pass.phase === this._passDesc.phases) {
```

2020-05-18 03:28 UTC, pandamicro commented on cocos/core/pipeline/render-light-batched-queue.ts
> +        {
一个刚开始写 TS 的人可能容易忽略的问题，不要使用 == 非严格比较，一定要使用 === 和 !==

2020-05-18 03:28 UTC, pandamicro commented on cocos/core/pipeline/render-pipeline.ts
> +    public abstract getLightBuffers() : GFXBuffer[];
同样的都可以改为 readonly getter 属性，返回空数组 []

2020-05-18 06:04 UTC, troublemaker52025 commented on cocos/core/pipeline/forward/forward-stage.ts
> +            this._lightBatchQueues[l].updateLightBuffer(lightBuffers[l]);
多个queue里维护并创建了PSO，如果合成一个队列的话，pso就得一直创建

2020-05-25 09:32 UTC, closed without merging