Update CCEventManager.js
cocos/cocos-engine pull request #6638
Opened 2020-04-30 09:40 UTC by shpz

合并引擎关闭多点触控部分代码时，发现 getCode === EventTouch.BEGAN 成立时，会 return 掉所有后续同为 EventTouch.BEGAN 的事件，处理方式是加上 && eventManager._currentTouch !== selTouch

Re: cocos-creator/2d-tasks#

Changes:
 *

2020-04-30 10:35 UTC, caryliu1999 commented
> && eventManager._currentTouch !== selTouch

关闭多点触控在有点击触发的情况下，本来就是要return掉所有后续的 EventTouch.BEGAN 事件，你这里遇到问题的条件能不能具体说明一下？

2020-04-30 22:28 UTC, shpz commented
> > && eventManager._currentTouch !== selTouch
> 
> 感谢代码贡献
> 
> 关闭多点触控在有点击触发的情况下，本来是要 return 掉所有后续的 EventTouch.BEGAN 事件，你这里遇到问题的条件能不能具体说明一下？是某种条件下，点击释放之后，没有清空 currentTouch 的记录，导致后续的点击事件无法触发吗？

仅在 EventTouch.BEGAN 事件里出现这个问题，我们的项目是个老项目，里边有很早以前的 cc.eventManager.addListener 这种方式注册事件，我发现只要先触发了这个事件，BEGAN 类型的其他监听器都会被 return 掉，我追了下代码，可能其他 CCNode.on 注册的事件也会受影响

2020-05-07 12:21 UTC, caryliu1999 approved these changes

2020-05-08 02:55 UTC, caryliu1999 commented
> > > && eventManager._currentTouch !== selTouch
> > 
> > 
> > 感谢代码贡献
> > 关闭多点触控在有点击触发的情况下，本来是要 return 掉所有后续的 EventTouch.BEGAN 事件，你这里遇到问题的条件能不能具体说明一下？是某种条件下，点击释放之后，没有清空 currentTouch 的记录，导致后续的点击事件无法触发吗？
> 
> 仅在 EventTouch.BEGAN 事件里出现这个问题，我们的项目是个老项目，里边有很早以前的 cc.eventManager.addListener 这种方式注册事件，我发现只要先触发了这个事件，BEGAN 类型的其他监听器都会被 return 掉，我追了下代码，可能其他 CCNode.on 注册的事件也会受影响

你这里加的这个条件只是多了一个当前记录的 touch 信息跟新的事件 touch 是否一致的判断，如果是后续其他的触摸事件都无效了，那跟这个条件判断应该是没什么关系，因为新的touch信息跟旧的肯定是不一致的。

https://github.com/cocos-creator/engine/pull/6551 你看下这个 pr 是否能修复你的问题。

2020-05-08 03:02 UTC, caryliu1999 requested changes

2020-05-08 03:02 UTC, caryliu1999 commented on cocos2d/core/event-manager/CCEventManager.js
>                  let node = eventManager._currentTouchListener._node;
加上这个条件会导致在关闭多点触摸的情况下，同时点击同一个按钮，多次触发该按钮的 TOUCH BEGAN 事件，跟单点触摸的需求是违背的。

2020-12-03 07:51 UTC, holycanvas commented
再次感谢你的贡献，不过这个pr已经太久了，而且和现在的结构不太符合，所以先关闭了

2020-12-03 07:51 UTC, closed without merging