widget value lock（Editor change not completed）
cocos/cocos-engine pull request #6655
Opened 2020-05-08 06:18 UTC by LinYunMo

Re:  https://github.com/cocos-creator/3d-tasks/issues/2977

2020-05-09 02:19 UTC, pandamicro commented
这个给 widget 增加了 12 个属性，个人觉得不是很妥当，编辑器层面通过直接锁住输入框可能会更合理

2020-05-09 02:22 UTC, LinYunMo commented
编辑器锁住输入框无法保证在节点进行移动/缩放时，widget 的值无法被锁定的问题

2020-05-09 03:59 UTC, pandamicro commented
> 编辑器锁住输入框无法保证在节点进行移动/缩放时，widget 的值无法被锁定的问题

那又怎么样呢？我想知道什么情况下开发者希望一个 widget 被锁死，任何操作都无法动

2020-05-09 07:08 UTC, LinYunMo commented
> > 编辑器锁住输入框无法保证在节点进行移动/缩放时，widget 的值无法被锁定的问题
> 
> 那又怎么样呢？我想知道什么情况下开发者希望一个 widget 被锁死，任何操作都无法动

https://forum.cocos.org/t/widget/89333
这个情况

2020-05-09 07:34 UTC, pandamicro commented
我理解了这个需求，但是这些属性只是编辑器需要的，却会影响到运行时增加十多个毫无必要的属性，第一可以做的是保障这些属性都是 @editorOnly 的，但即便如此属性数量也不会减少。如果[导入期可以剔除这些 property](https://github.com/cocos-creator/3d-tasks/issues/2665#issuecomment-610350057)倒是不会有什么影响了

2020-05-11 08:23 UTC, jareguo requested changes
需求理解有问题

2020-05-11 08:25 UTC, jareguo commented on cocos/ui/components/widget-component.ts
> +    private _isLockVerticalCenter = false;
从性能的角度考虑，请像 _alignFlags 一样用一个标志位表示就好了。例如 _lockFlags

2020-05-11 08:26 UTC, pandamicro commented
目前这个需求只有编辑器需要锁定功能，需要做出如下调整：

1. 引擎层不做修改
2. 编辑器层对 WidgetComponent.prototype 注入 `_adjustWidgetToAllowResizingInEditor` 以及 `lockTop` 等函数，在 lockTop 函数中设置私有属性值，在 `_adjustWidgetToAllowResizingInEditor` 中使用属性值。

2020-05-11 08:27 UTC, jareguo commented on cocos/ui/components/widget-component.ts
> +        this._recursiveDirty();
为什么修改完标志位要调用 dirty？

2020-05-11 08:28 UTC, jareguo commented on cocos/ui/components/widget-component.ts
>      set editorHorizontalCenter (value) {
为什么会有一个 editorHorizontalCenter？

2020-05-11 08:29 UTC, jareguo commented on cocos/ui/components/widget-component.ts
> +        if (this.isLockedRight) { return; }
运行时不应该有任何 lock 的行为，这个是纯编辑器行为

2020-05-11 08:29 UTC, jareguo commented
> 2\. 编辑器层对 WidgetComponent.prototype 注入 `_adjustWidgetToAllowResizingInEditor` 以及 `lockTop` 等函数，在 lockTop 函数中设置私有属性值，在 `_adjustWidgetToAllowResizingInEditor` 中使用属性值。

这个不一定好做，引用的东西比较多

2020-05-11 08:30 UTC, jareguo commented
> 1. 引擎层不做修改

引擎得提供一个存放锁定状态的地方

2020-05-11 09:14 UTC, pandamicro commented
> 这个不一定好做，引用的东西比较多

目前 lock 状态只在 _adjustWidgetToAllowResizingInEditor 这个函数中用到，所以应该是可以完全剥离的

> 引擎得提供一个存放锁定状态的地方

```
WidgetComponent.prototype.lockTop = function (lock) {
    this._topLocked = lock;
    // ...
}
```

直接注入就好，这样不会影响到运行时

2020-05-14 08:58 UTC, pandamicro approved these changes

2020-05-14 09:11 UTC, jareguo commented on cocos/ui/components/widget-component.ts
> +    private _lockFlags = 0;
加一个 editorOnly 吧

2020-05-14 09:39 UTC, jareguo approved these changes

2020-05-14 09:45 UTC, merged