fix undo bug for pageview
cocos/cocos-engine pull request #6682
Opened 2020-05-13 06:30 UTC by JoneLau

Re: cocos-creator/3d-tasks#3323

2020-05-15 11:15 UTC, shrinktofit requested changes

2020-05-15 11:15 UTC, shrinktofit commented on cocos/ui/components/page-view-component.ts
>          return this._verticalScrollBar;
建议修改为 super.verticalScrollBar

2020-05-15 11:15 UTC, shrinktofit commented on cocos/ui/components/page-view-component.ts
>          return this._horizontalScrollBar;
同理

2020-05-15 11:15 UTC, shrinktofit commented on cocos/ui/components/page-view-component.ts
> +        super.horizontalScrollBar = value;
target 换成 es6 就可以不用 ts-ignore了

2020-05-18 02:04 UTC, JoneLau commented
be replaced：https://github.com/cocos-creator/engine/pull/6702

2020-05-25 09:38 UTC, merged