create spriteframe function add
cocos/cocos-engine pull request #6687
Opened 2020-05-14 07:42 UTC by LinYunMo

Re: https://github.com/cocos-creator/3d-tasks/issues/2810

2020-05-14 07:42 UTC, LinYunMo commented
please @JoneLau review

2020-05-14 10:19 UTC, pandamicro requested changes

2020-05-14 10:19 UTC, pandamicro commented on cocos/core/assets/sprite-frame.ts
> +    public static createSpriteFrameByImage (image: ImageAsset) {
createWithImage

2020-05-14 10:19 UTC, pandamicro commented on cocos/core/assets/sprite-frame.ts
> +    public static createSpriteFrameByImageSource (imageSource: ImageSource) {
createWithImageSource

2020-05-14 10:19 UTC, pandamicro commented on cocos/core/assets/sprite-frame.ts
> +        const sprite = new SpriteFrame();
spriteFrame 不要命名为 sprite，会产生歧义

2020-05-15 02:37 UTC, JoneLau approved these changes

2020-05-15 02:39 UTC, JoneLau commented
似乎没 link 到文档关于这快的内容使用

2020-05-15 03:15 UTC, pandamicro approved these changes

2020-05-15 03:15 UTC, merged