Add forward-lighting
cocos/cocos-engine pull request #6707
Opened 2020-05-18 10:28 UTC by troublemaker52025

Add to v1.2

decesign: https://github.com/troublemaker52025/3d-tasks/blob/master/design-docs/render-pipeline/forward-pipeline-lighting.md

# Conflicts:
#	cocos/core/pipeline/render-pipeline.ts

Re: cocos-creator/2d-tasks#

Changes:
 *

2020-05-18 14:57 UTC, pandamicro requested changes

2020-05-18 14:57 UTC, pandamicro commented on cocos/core/pipeline/forward/forward-pipeline.ts
> +        this._flows.push(forwardFlow);
不应该有这一行修改

2020-05-18 14:57 UTC, pandamicro commented on cocos/core/pipeline/forward/forward-pipeline.ts
> +    }
所有属性位置应该放在其他公有属性之后（lightsUBO 之后）

2020-05-18 14:57 UTC, pandamicro commented on cocos/core/pipeline/forward/forward-stage.ts
> +            this._cmdBuff = null;
不应该产生这种修改

2020-05-18 14:57 UTC, pandamicro commented on cocos/core/pipeline/forward/forward-stage.ts
> +        this._renderQueues.forEach(this.renderQueueClearFunc);
同上

2020-05-18 14:57 UTC, pandamicro commented on cocos/core/pipeline/render-pipeline.ts
> +    public abstract get validLights () : Light[];
这样实现会不会更好？

```
// Before class
const EMPTY = [];

// In class
public get validLights () : Light[] {
    return EMPTY;
}
```

2020-05-19 06:41 UTC, troublemaker52025 commented on cocos/core/pipeline/forward/forward-pipeline.ts
> +        this._flows.push(forwardFlow);
这个是pipeline对flow的记录，这个是前人写的   我没有修改过

2020-05-19 06:50 UTC, troublemaker52025 commented on cocos/core/pipeline/render-pipeline.ts
> +    public abstract get validLights () : Light[];
这样修改的话  会不会造成把Forward-pipeline里的属性  提到全局   破坏封装的结果啊？
我感觉纯虚函数的作用就是子类实现其定义

2020-05-19 07:32 UTC, pandamicro approved these changes

2020-05-19 07:33 UTC, minggo approved these changes

2020-05-19 07:44 UTC, YunHsiao commented on cocos/core/pipeline/forward/forward-pipeline.ts
> +            this._lightBatchQueues[l].updateLightBuffer(this.lightBuffers[l]);
这看起来是每帧都创建新的 light queue？这肯定是不行的，另外我还是坚持没必要每个光源都建一个 queue，完全可以在同一个 queue 内维护光源的数组就行了

2020-05-19 07:45 UTC, YunHsiao commented on cocos/core/pipeline/forward/forward-pipeline.ts
> +                this._lightBuffers.push(lightBuffer);
buffer 也不能每帧创建的啊

2020-05-19 07:52 UTC, pandamicro requested changes

2020-05-19 07:52 UTC, pandamicro commented on cocos/core/pipeline/forward/forward-pipeline.ts
> +                this._lightBuffers.push(lightBuffer);
哦确实，没注意到现在都会清空，之前的逻辑是每帧检查是否有新的，有新的才添加

2020-05-19 09:02 UTC, troublemaker52025 commented
做cache优化后，性能被降低了，我查了下代码，主要的耗时在sceneculling阶段。目前还不清楚为什么
优化前49-60帧，优化后5-27帧

2020-05-19 09:51 UTC, troublemaker52025 commented on cocos/core/pipeline/forward/forward-pipeline.ts
> +                this._lightBuffers.push(lightBuffer);
改缓存后帧率下降，原因还在查

2020-05-20 08:58 UTC, troublemaker52025 commented on cocos/core/pipeline/forward/forward-pipeline.ts
> +                this._lightBuffers.push(lightBuffer);
改好了

2020-05-20 08:58 UTC, troublemaker52025 commented on cocos/core/pipeline/forward/forward-pipeline.ts
> +                this._lightBuffers.push(lightBuffer);
改好了

2020-05-21 03:25 UTC, pandamicro requested changes

2020-05-21 03:25 UTC, pandamicro commented on cocos/core/pipeline/forward/forward-pipeline.ts
> +        this._lightBatchQueue.clear();
应该在基础的 destroy 之前做当前类数据的清理。

2020-05-21 03:25 UTC, pandamicro commented on cocos/core/pipeline/render-light-batched-queue.ts
> +    public updateLightBuffers (index, lightBuffers: GFXBuffer) {
应该是 updateLightBuffer，这个接口只更新一个 buffer

2020-05-21 03:25 UTC, pandamicro commented on cocos/core/pipeline/render-light-batched-queue.ts
> +    private attache(index: number, pass: Pass, renderObj: IRenderObject, modelIdx: number, patches?: IMacroPatch[]) {
attach

2020-05-21 03:25 UTC, pandamicro commented on cocos/core/pipeline/render-light-batched-queue.ts
> +    public updateValidLights (validLights: Light[]) {
我觉得用 size 作为参数更合理，你并没使用 validLights 的任何内容。接口命名也应该改为 resizeValidLights

2020-05-21 07:42 UTC, troublemaker52025 commented on cocos/core/pipeline/forward/forward-pipeline.ts
> +            this._lightBatchQueues[l].updateLightBuffer(this.lightBuffers[l]);
改好了

2020-05-21 08:13 UTC, pandamicro approved these changes

2020-05-21 08:19 UTC, YunHsiao approved these changes

2020-05-21 08:42 UTC, merged

2020-05-25 09:31 UTC, pandamicro commented
cocos-creator/3d-tasks#2395
cocos-creator/3d-tasks#3149

2020-05-25 09:32 UTC, pandamicro commented
Previous discussion could be found here
https://github.com/cocos-creator/engine/pull/6596

2020-07-15 05:34 UTC, pandamicro commented
https://github.com/cocos-creator/3d-tasks/issues/2451