correction node.walk
cocos/cocos-engine pull request #6710
Opened 2020-05-19 04:45 UTC by Jno1995

Re: https://forum.cocos.org/t/walk-bug-2-3-3/92824

2020-05-19 06:11 UTC, knoxHuang commented on cocos2d/core/utils/base-node.js
> +                if (parent === this._parent) return;
// 这样写会不会好点？
if (afterChildren && parent !== this._parent) {
}

2020-05-19 06:33 UTC, Jno1995 commented on cocos2d/core/utils/base-node.js
> +                if (parent === this._parent) return;
这样写的话，parent === this._parent 的时候就会走下面的 else，就会死循环了。

2020-05-19 07:05 UTC, knoxHuang approved these changes

2020-05-20 02:54 UTC, pandamicro requested changes

2020-05-20 02:54 UTC, pandamicro commented on cocos2d/core/utils/base-node.js
> +                if (parent === this._parent) return;
while 中不应该直接 return，应该用 break

2020-05-21 02:22 UTC, pandamicro approved these changes

2020-05-21 06:19 UTC, merged