V1.2 shadow map
cocos/cocos-engine pull request #6843
Opened 2020-06-09 09:26 UTC by troublemaker52025

Re: cocos-creator/2d-tasks#

Changes:
 *

2020-06-09 09:45 UTC, YunHsiao requested changes

2020-06-09 09:45 UTC, YunHsiao commented on cocos/core/math/mat4.ts
> +    }
这俩是用不着加，也不太对的（translation 是 [m12 m13 m14]），去掉吧

2020-06-09 09:45 UTC, YunHsiao commented on cocos/core/pipeline/define.ts
> +            { name: 'cc_lightMatrix', type: GFXType.MAT4, count: 1 },
shadow 应该单独一个 UBO，不要再往 global 里挤了

2020-06-09 09:45 UTC, YunHsiao commented on cocos/core/pipeline/flow/stage/shadowMapA-stage.ts
> +        director.root!.device.copyFramebufferToBuffer(view.window!.framebuffer, buffers[0].buffer, readRegions);
这是肯定用不着的，像素读回在很多平台非常慢，不能放在运行时每帧做

2020-06-09 09:45 UTC, YunHsiao commented on cocos/core/pipeline/forward/forward-pipeline.ts
> +        });
这些都应该放在对应的 stage 去

2020-06-09 09:45 UTC, YunHsiao commented on cocos/core/pipeline/forward/forward-pipeline.ts
> +                        this.shadowMapQueue.add(pass, ro, m);
和上面一样，pipeline 里不应该做这些

2020-06-09 09:45 UTC, YunHsiao commented on cocos/core/pipeline/render-pipeline.ts
> +    }
同样，不要放这

2020-06-09 09:45 UTC, YunHsiao commented on cocos/core/pipeline/render-shadowMap-batched-queue.ts
> +            this._psoArray[nowStep] = renderObj.model.createPipelineState(pass, modelIdx, myForward_ShadowMap_Patches);
这个和 light 那边类似的东西在最终版必须解决，不可能每帧创建 PSO

2020-06-09 09:45 UTC, YunHsiao commented on cocos/core/pipeline/shadowCamera.ts
> +export class ShadowCamera {
整个类都是没有必要的，shadow 只关心自己的 viewProj 矩阵就行，不需要完整的 camera

2020-06-09 09:54 UTC, troublemaker52025 commented on cocos/core/pipeline/render-shadowMap-batched-queue.ts
> +            this._psoArray[nowStep] = renderObj.model.createPipelineState(pass, modelIdx, myForward_ShadowMap_Patches);
好的

2020-06-09 09:55 UTC, troublemaker52025 commented on cocos/core/pipeline/shadowCamera.ts
> +export class ShadowCamera {
感觉还是需要的  因为要计算阴影相机合适的位置，再通过合适的位置  计算它本身的viewProj，不能复用mianLight的

2020-06-09 09:57 UTC, YunHsiao commented on cocos/core/pipeline/shadowCamera.ts
> +export class ShadowCamera {
计算代码可以单独封装，感觉封装成 camera 浪费了，好多重复代码

2020-06-09 10:02 UTC, troublemaker52025 commented on cocos/core/pipeline/shadowCamera.ts
> +export class ShadowCamera {
也对 我封装一下计算

2020-06-10 03:22 UTC, caryliu1999 commented on cocos/core/pipeline/render-pipeline.ts
> +            this._shadowCamera.setWorldScale(mainLight?.node?.getWorldScale());
这里为什么要做两次 setWorldPosition ？

2020-06-10 03:23 UTC, troublemaker52025 commented on cocos/core/pipeline/render-pipeline.ts
> +            this._shadowCamera.setWorldScale(mainLight?.node?.getWorldScale());
写错了，抱歉   应该是rotation

2020-06-10 03:25 UTC, caryliu1999 commented on cocos/core/pipeline/render-pipeline.ts
> +            1.0);
this._viewport.x / width 和 this._viewport.y / height 两次以上的计算都可以提取出来了，这个方法也是每帧调用的。

2020-06-10 03:38 UTC, caryliu1999 commented on cocos/core/pipeline/shadowCamera.ts
> +            Mat4.invert(this._matProjInv, this._matProj);
这里的投影矩阵需要在 update 里每帧更新吗？

2020-06-10 08:58 UTC, troublemaker52025 commented on cocos/core/pipeline/render-pipeline.ts
> +            1.0);
如果参数改变了   就得写事件通知修改。不然的话就需要每帧去修改

2020-06-10 08:59 UTC, troublemaker52025 commented on cocos/core/pipeline/shadowCamera.ts
> +            Mat4.invert(this._matProjInv, this._matProj);
这里没有办法监听到主光源修改，如果主光源修改   就需要对透视投影矩阵进行重新计算。所以放在每帧都计算一次了

2020-06-12 07:35 UTC, closed without merging