Add Shadow map
cocos/cocos-engine pull request #6972
Opened 2020-07-10 08:38 UTC by troublemaker52025

Re: cocos-creator/2d-tasks#

Changes:
 *

2020-07-13 01:52 UTC, minggo commented on cocos/core/3d/framework/model-component.ts
> +            this._model.receiveShadow = true;
没明白为什么不论 ModelShadowCastingMode 是 ON 还是 OFF，receiveShadow 都设置为 true。

2020-07-13 01:56 UTC, minggo commented on cocos/core/pipeline/define.ts
> +export const PIPELINE_FLOW_SHADOW: string = 'ShadowFlow';
我看 shadow map 还是在 forward flow 处理，为什么这里有 shadow flow 呢？

2020-07-13 01:57 UTC, minggo commented on cocos/core/pipeline/define.ts
> +    UBO_PCF_SHADOW = MAX_BINDING_SUPPORTED -10,
PCF 是什么意思？

2020-07-13 02:18 UTC, minggo commented on cocos/core/pipeline/render-shadowMap-batched-queue.ts
> +            const psoCI = pass.createPipelineStateCI(fullPatches)!;
psoCI 还是得复用吧。

2020-07-13 02:19 UTC, minggo commented on cocos/core/pipeline/define.ts
> +export const PIPELINE_FLOW_SHADOW: string = 'ShadowFlow';
看错了，忽略。

2020-07-13 02:22 UTC, minggo commented on cocos/core/pipeline/shadow/shadow-flow.ts
> +export class ShadowFlow extends RenderFlow {
shadowmap 需要作为一个 flow 吗？我觉得作为一个 stage 应该就可以了吧。

2020-07-13 02:25 UTC, minggo commented on cocos/core/renderer/scene/model.ts
> +    public receiveShadow = true;
这个变量作用是什么？如果设置为 false 时，那么 model 对应的 patches 是否需要改变？

2020-07-13 02:29 UTC, minggo commented on cocos/core/renderer/scene/directional-light.ts
> +        return this._biasAutoAdjust;
这个值好像没有地方用？

2020-07-13 02:30 UTC, minggo commented on cocos/core/renderer/scene/directional-light.ts
> +    }
这个值好像也没有地方使用。

2020-07-13 02:30 UTC, minggo commented on cocos/core/renderer/scene/directional-light.ts
> +    }
其它的变量也检查一下吧。

2020-07-14 07:33 UTC, troublemaker52025 commented on cocos/core/pipeline/shadow/shadow-flow.ts
> +export class ShadowFlow extends RenderFlow {
我觉得可以改。 就是改动的话跟设计不符，周五开会 咱们商量一下

2020-07-14 07:34 UTC, troublemaker52025 commented on cocos/core/renderer/scene/model.ts
> +    public receiveShadow = true;
接收阴影的开关，我之前写过的引擎，接收阴影是一个全局开关，现在放在model里单独控制不知道是不是合适

2020-07-14 07:35 UTC, troublemaker52025 commented on cocos/core/renderer/scene/directional-light.ts
> +        return this._biasAutoAdjust;
这些变量我想放出来  在light-component里可以进行修改的，所以把那些没用到的  也补齐了

2020-07-14 07:35 UTC, troublemaker52025 commented on cocos/core/renderer/scene/directional-light.ts
> +    }
同上

2020-07-14 07:36 UTC, troublemaker52025 commented on cocos/core/3d/framework/model-component.ts
> +            this._model.receiveShadow = true;
修改好了

2020-07-15 01:41 UTC, minggo commented on cocos/core/renderer/scene/directional-light.ts
> +        return this._biasAutoAdjust;
但是没看到 light-component 有修改啊。

2020-07-15 01:54 UTC, minggo commented on cocos/core/pipeline/shadow/shadow-flow.ts
> +export class ShadowFlow extends RenderFlow {
之前的设计讨论时是作为一个 flow 使用的？

2020-07-15 02:25 UTC, troublemaker52025 commented on cocos/core/pipeline/shadow/shadow-flow.ts
> +export class ShadowFlow extends RenderFlow {
对

2020-07-15 02:25 UTC, troublemaker52025 commented on cocos/core/pipeline/render-shadowMap-batched-queue.ts
> +            const psoCI = pass.createPipelineStateCI(fullPatches)!;
复用了   但是何时销毁是个问题

2020-07-15 02:25 UTC, troublemaker52025 commented on cocos/core/pipeline/define.ts
> +    UBO_PCF_SHADOW = MAX_BINDING_SUPPORTED -10,
pcf的阴影   跟planer shadow区别一下名称

2020-07-15 02:27 UTC, troublemaker52025 commented on cocos/core/renderer/scene/directional-light.ts
> +        return this._biasAutoAdjust;
还没放出来，像阴影影响范围，最大可视距离  以后都会放出来的

2020-07-15 02:57 UTC, minggo commented on cocos/core/pipeline/render-shadowMap-batched-queue.ts
> +            const psoCI = pass.createPipelineStateCI(fullPatches)!;
哪里复用了？

2020-07-15 03:05 UTC, troublemaker52025 commented on cocos/core/pipeline/render-shadowMap-batched-queue.ts
> +            const psoCI = pass.createPipelineStateCI(fullPatches)!;
在下面提交修改了    现在这块还是老的代码  不知道为啥没标记Outdated

2020-07-15 03:10 UTC, minggo commented on cocos/core/pipeline/render-shadowMap-batched-queue.ts
> +            const psoCI = pass.createPipelineStateCI(fullPatches)!;
我已经刷新到最新代码了，没看到什么改动啊。

2020-07-15 05:35 UTC, pandamicro commented
https://github.com/cocos-creator/engine-design-with-hw/issues/6

2020-07-15 10:24 UTC, minggo commented on cocos/core/renderer/scene/model.ts
> +    public receiveShadow = true;
当时讨论的结果是如何的？另外，不管是否有全局的开关，当 receiveShadow 修改时，shadowMap_Patches 应该得修改吧？另外，shadow map 会缓存 PSOCI 吧，那缓存的 PSOCI 也得更新吧？

2020-07-16 10:02 UTC, YunHsiao commented on cocos/core/pipeline/forward/forward-stage.ts
> +                                pass.bindSampler(UNIFORM_SHADOWMAP.binding, sampler!);
这个是 global 的一部分，不应该 pass 自动就绑了么，应该不需要在这再调一遍

2020-07-16 10:02 UTC, YunHsiao commented on cocos/core/pipeline/render-shadowMap-batched-queue.ts
> +            if (!this._psoArray[i]) {
PSOCI 缓存起来就行，这个倒是无所谓，manager 里面已经有一层了

2020-07-16 10:02 UTC, YunHsiao commented on cocos/core/pipeline/shadow/shadow-flow.ts
> +export class ShadowFlow extends RenderFlow {
要改 fbo，肯定得一个 flow

2020-07-16 10:02 UTC, YunHsiao commented on cocos/core/pipeline/shadow/shadow-flow.ts
> +        if(!this._shadowRenderPass) {
资源初始化在 activate 函数做就行

2020-07-16 10:11 UTC, YunHsiao commented on cocos/core/pipeline/define.ts
> +    UBO_PCF_SHADOW = MAX_BINDING_SUPPORTED - 9,
理论上 shadowmap 和 planar shadow 不需要共存，其实可以做成互斥的，这里就可以共用同一个 binding 了，可以作为后续优化记一下

2020-07-16 10:11 UTC, YunHsiao commented on cocos/core/pipeline/render-shadowMap-batched-queue.ts
> +            this._psoCIArray[this._subModelsArray.length - 1].bindingLayout.update();
JS 里每次对象访问都有代价，最好养成随手存一下用到多次的局部变量的习惯：
```js
const psoci = this._psoCIArray[this._subModelsArray.length - 1];
renderObj.model.updateLocalBindings(psoci, subModelIdx);
// ...
```

2020-07-16 10:11 UTC, YunHsiao commented on cocos/core/pipeline/shadow/shadow-flow.ts
> +                    loadOp: GFXLoadOp.CLEAR, // shouldn't clear color attachment
所以现在是用 color 还是用 depth attachment 做采样？确定这不用 clear 么？

2020-07-16 10:28 UTC, caryliu1999 commented on cocos/core/pipeline/shadow/shadow-flow.ts
> +
this._shadowRenderPass，this._shadowFrameBuffer 这些对象在初始化的时候就需要判断并预先创建好了，不应该在每帧的 render 调用里面再去做判断

2020-07-16 12:11 UTC, caryliu1999 commented on cocos/core/pipeline/shadow/shadow-flow.ts
> +export class ShadowFlow extends RenderFlow {
是要改成一个 stage 才好

2020-07-17 01:38 UTC, minggo commented on cocos/core/pipeline/shadow/shadow-flow.ts
> +export class ShadowFlow extends RenderFlow {
这个应该是标准流程的一部分吧，应该在我们的标准流程的 flow 里就包含了吧？

2020-07-17 01:44 UTC, minggo commented on cocos/core/pipeline/render-shadowMap-batched-queue.ts
> +            }
这个缓存逻辑有问题吧？没看明白为什么是根据 `this._subModelsArray.length - 1` 来判断是否缓存过。

2020-07-20 01:57 UTC, minggo commented on cocos/core/pipeline/shadow/shadow-stage.ts
> +            if (ro.model.castShadow) {
Model.receiveShadow 和 Model.castShadow 是什么关系？这里是否要考虑 Model.receiveShadow?

2020-07-20 02:00 UTC, troublemaker52025 commented on cocos/core/pipeline/shadow/shadow-flow.ts
> +export class ShadowFlow extends RenderFlow {
等合并后   改成一个stage

2020-07-20 02:00 UTC, troublemaker52025 commented on cocos/core/pipeline/shadow/shadow-flow.ts
> +        if(!this._shadowRenderPass) {
初始化放在activate了

2020-07-20 02:01 UTC, troublemaker52025 commented on cocos/core/pipeline/define.ts
> +    UBO_PCF_SHADOW = MAX_BINDING_SUPPORTED - 9,
后面做成共用吧，后续建个issue

2020-07-20 02:02 UTC, troublemaker52025 commented on cocos/core/pipeline/shadow/shadow-flow.ts
> +
已经放在初始化阶段了

2020-07-20 02:03 UTC, troublemaker52025 commented on cocos/core/pipeline/render-shadowMap-batched-queue.ts
> +            }
先从已有的数组里获取    取不到再创建，这样应该达到了管理的目的  避免重复创建

2020-07-20 02:04 UTC, troublemaker52025 commented on cocos/core/pipeline/shadow/shadow-stage.ts
> +            if (ro.model.castShadow) {
一个是接收阴影   一个是参与投射阴影，要根据用户的配置确定哪些模型需要接收阴影    哪些模型需要投射阴影（比如半透明）

2020-07-20 10:22 UTC, minggo commented on cocos/core/pipeline/render-shadowMap-batched-queue.ts
> +            }
你这个缓存有问题啊，每次都执行 `this._subModelsArray.push(renderObj.model.subModels[subModelIdx]);`，导致 index 一直是增长，这样对应都 psoCI 是没有创建的。这个逻辑和每次重新创建没什么区别，而且还增加了一些开销。

2020-07-20 10:23 UTC, minggo commented on cocos/core/pipeline/render-shadowMap-batched-queue.ts
> +}
行尾换行

2020-07-20 11:54 UTC, pandamicro requested changes

2020-07-20 11:54 UTC, pandamicro commented on cocos/core/3d/framework/model-component.ts
> +                `ShadowCastingMode ${this._shadowCastingMode} is not supported.`,
这个 else 分支中 _shadowCastingMode 不可能是 OFF，这里的 assert 没意义

2020-07-20 11:54 UTC, pandamicro commented on cocos/core/3d/framework/model-component.ts
> +            this._model.receiveShadow = true;
另外，_updateReceiveShadows 依据的是 _shadowCastingMode，操作的是 model.receiveShadow，跟 _receiveShadows 属性半毛钱关系都没有

2020-07-20 11:54 UTC, pandamicro commented on cocos/core/3d/framework/model-component.ts
> +    protected _receiveShadows = ModelShadowReceivingMode.ON;
没有见到任何地方使用这个属性

2020-07-20 11:54 UTC, pandamicro commented on cocos/core/pipeline/define.ts
> +    UBO_PCF_SHADOW = MAX_BINDING_SUPPORTED - 9,
应该放在 UBO_SHADOW 之后把

2020-07-20 11:54 UTC, pandamicro commented on cocos/core/pipeline/define.ts
> +    public static MAIN_SHADOW_MATRIX_OFFSET: number = UBOGlobal.GLOBAL_FOG_ADD_OFFSET + 4;
最好放在 AMBIENT_SKY_OFFSET 之前

2020-07-20 11:54 UTC, pandamicro commented on cocos/core/pipeline/define.ts
> +            { name: 'cc_shadowLightMatrix', type: GFXType.MAT4, count: 1 },
同上，位置优先级最好放在 ambientSky 之前

2020-07-20 11:54 UTC, pandamicro commented on cocos/core/pipeline/forward/enum.ts
> +    FORWARD = 1,
如果 SHADOWMAP 是一个 flow 应该不需要修改这里的 stage priority 把？

2020-07-20 11:54 UTC, pandamicro commented on cocos/core/pipeline/forward/enum.ts
> +    FORWARD = 1,
这里应该把 SHADOWMAP 也添加上

2020-07-20 11:54 UTC, pandamicro commented on cocos/core/pipeline/forward/forward-flow.ts
> +            shadowmapUniform.texture = this._pipeline.shadowFrameBuffer?.colorTextures[0]!;
这个操作不是应该在 shadowmap flow 中完成的吗？

2020-07-20 11:54 UTC, pandamicro commented on cocos/core/pipeline/render-pipeline.ts
> +    public get shadowFrameBuffer () {
所有 shadowmap 相关的配置和 uniform 更新都应该放在 forward pipeline 中，render pipeline 是一个通用的基类，并不涉及阴影具体实现方法。比如 GI 和 Deferred 管线中，阴影的计算都不同。

2020-07-20 11:54 UTC, pandamicro commented on cocos/core/pipeline/render-pipeline.ts
> +            shadowCamera_W_S.set(mainLight!.node!.getWorldScale());
这些都应该在 forward-pipeline 的 updateUBO 中

2020-07-20 11:54 UTC, pandamicro commented on cocos/core/pipeline/render-shadowMap-batched-queue.ts
> +const myForward_ShadowMap_Patches: IMacroPatch[]= [
不符合我们的变量命名规范

forwardShadowMapPatches

2020-07-20 11:54 UTC, pandamicro commented on cocos/core/pipeline/render-shadowMap-batched-queue.ts
> +let pso:GFXPipelineState|null = null;
这两个应该是函数级别局部变量，不要放在全局，会引起很难查的问题

2020-07-20 11:54 UTC, pandamicro commented on cocos/core/pipeline/render-shadowMap-batched-queue.ts
> +            if (!this._psoCIArray[index]) {
我没看到任何 delete 逻辑，看上去不可能有缓存的

2020-07-20 11:54 UTC, pandamicro commented on cocos/core/pipeline/render-shadowMap-batched-queue.ts
> +            renderObj.model.updateLocalBindings(this._psoCIArray[this._subModelsArray.length - 1], subModelIdx);
都预计算过 index 了，为啥还要在这里重新计算一次

2020-07-20 11:54 UTC, pandamicro commented on cocos/core/pipeline/render-shadowMap-batched-queue.ts
> +            psoCI!.bindingLayout.update();
尽量避免写 ! 绕开 ts 校验，你把 psoCI 变成局部变量也就不会出现可能为空的情况了

2020-07-20 11:54 UTC, pandamicro commented on cocos/core/pipeline/render-shadowMap-batched-queue.ts
> +            psoCI!.bindingLayout.bindBuffer(UBOShadow.BLOCK.binding, this._shadowMapBuffer!);
shadowMapBuffer 万一未创建或者被销毁了怎么办？

2020-07-20 11:54 UTC, pandamicro commented on cocos/core/pipeline/render-shadowMap-batched-queue.ts
> +            pso = this._psoArray[i];
我想不到任何使用全局变量的理由

2020-07-20 11:54 UTC, pandamicro commented on cocos/core/pipeline/render-pipeline.ts
> +    public get shadowFrameBuffer () {
另外，shadowFrameBuffer 也不应该在 pipeline 级别去存储，应该只有 shadow flow 或者 shadow stage 持有

2020-07-20 11:54 UTC, pandamicro commented on cocos/core/pipeline/shadow/shadow-flow.ts
> +        super();
空构造函数不需要写

2020-07-20 11:54 UTC, pandamicro commented on cocos/core/pipeline/shadow/shadow-flow.ts
> +        priority: ForwardFlowPriority.FORWARD - 1,
应该有自己的 priority 常量

2020-07-20 11:54 UTC, pandamicro commented on cocos/core/pipeline/shadow/shadow-flow.ts
> +        super.render(view);
render 之后做好 texture 的上传，就不需要 forward flow 去处理了

2020-07-20 11:54 UTC, pandamicro commented on cocos/core/pipeline/shadow/shadow-stage.ts
> +        super.activate(flow);
没有额外实现就不需要重写，否则会多函数调用次数

2020-07-20 11:54 UTC, pandamicro commented on cocos/core/pipeline/shadow/shadow-stage.ts
> +                        const pass = ro.model.getSubModel(m).passes[p];
应该在 for 循环之前，先缓存 

let passes = ro.model.getSubModel(m).passes;

然后复用 passes，这是很基础的复用，写代码的时候要注意

2020-07-20 11:54 UTC, pandamicro commented on cocos/core/pipeline/shadow/shadow-stage.ts
> +        this._renderArea!.height = vp.height * this.pipeline.shadowMapSize.y * this.pipeline!.shadingScale;
同上，四次 `this.pipeline.shadowMapSize` 访问相当于 8 次 property access，实际上只需要两次 property access 就可以完成任务了

2020-07-20 11:54 UTC, pandamicro commented on cocos/core/pipeline/shadow/shadow-stage.ts
> +                this._pipeline.getFrameBuffer(this._pipeline.currShading)!,
shadow stage 的 frameBuffer 直接从 shadow stage 或者 flow 取不就好了。刘航那边做的资源化管线其实也是要求去除 stage、flow 对 pipeline 的依赖以及 pipeline 对资源的直接持有

2020-07-20 11:54 UTC, pandamicro commented on cocos/core/renderer/scene/directional-light.ts
> +    public set shadoshadowIntensitywRange (shadowIntensity: number) {
变量名

2020-07-20 14:39 UTC, pandamicro commented on cocos/core/pipeline/render-shadowMap-batched-queue.ts
> +            const index = this._subModelsArray.length - 1;
直接使用

```
let subModel = renderObj.model.subModels[subModelIdx];
let psoCI = subModel.psoInfos[passIdx];
```

2020-07-20 14:39 UTC, pandamicro commented on cocos/core/pipeline/render-shadowMap-batched-queue.ts
> +            const index = this._subModelsArray.length - 1;
直接使用

```
let subModel = renderObj.model.subModels[subModelIdx];
let psoCI = subModel.psoInfos[passIdx];
```

2020-07-20 14:48 UTC, pandamicro commented on cocos/core/pipeline/shadow/shadow-stage.ts
> +                        const pass = ro.model.getSubModel(m).passes[p];
应该只需要 add shadow pass 而不是 add 所有 pass，通过 pass stage 是否匹配来判断。
另外，forward-stage 里面也需要剔除 shadow pass

if (pass.stage === RenderPassStage.SHADOW_MAP) {
    ...
}

2020-07-21 04:08 UTC, pandamicro commented on cocos/core/pipeline/render-shadowMap-batched-queue.ts
> +            const index = this._subModelsArray.length - 1;
理解错误，shadow 只是一个 phase 不是一个 pass

2020-07-21 04:14 UTC, pandamicro commented on cocos/core/pipeline/render-shadowMap-batched-queue.ts
> +            }
尝试通过 fullPatches 计算一个 hash 作为标记来缓存 psoCI

2020-07-21 08:50 UTC, troublemaker52025 commented on cocos/core/pipeline/shadow/shadow-stage.ts
> +                        const pass = ro.model.getSubModel(m).passes[p];
修复了

2020-07-21 08:51 UTC, troublemaker52025 commented on cocos/core/pipeline/shadow/shadow-flow.ts
> +        super.render(view);
解决了

2020-07-21 08:54 UTC, troublemaker52025 commented on cocos/core/3d/framework/model-component.ts
> +            this._model.receiveShadow = true;
解决了

2020-07-21 08:54 UTC, troublemaker52025 commented on cocos/core/pipeline/forward/enum.ts
> +    FORWARD = 1,
添加好了

2020-07-21 09:20 UTC, pandamicro requested changes

2020-07-21 09:20 UTC, pandamicro commented on cocos/core/3d/framework/model-component.ts
> -    protected _receiveShadow: boolean = false;
别随意删属性啊。。。这是人家 LightmapSettings

2020-07-21 09:20 UTC, pandamicro commented on cocos/core/3d/framework/model-component.ts
> -    get receiveShadow () {
同上

2020-07-21 09:20 UTC, pandamicro commented on cocos/core/3d/framework/model-component.ts
> +                this._shadowReceivingMode === ModelShadowReceivingMode.ON,
不需要这个 asset，你前面不是已经判断过 OFF 了么，else 分支只可能是 ON 把？

2020-07-21 09:20 UTC, pandamicro commented on cocos/core/pipeline/forward/enum.ts
> +    FORWARD = 1,
Forward stage 里面没有 Shadow 啊，ForwardStagePriority 感觉不用改

2020-07-21 09:20 UTC, pandamicro commented on cocos/core/pipeline/render-shadowMap-batched-queue.ts
> +                psoCI.bindingLayout.update();
不需要每次 add 的时候都 update 把，应该只需要在 create 的时候 bind 一次，update 一次就可以了

2020-07-21 09:20 UTC, pandamicro commented on cocos/core/pipeline/shadow/shadow-stage.ts
> +                        const pass = ro.model.getSubModel(m).passes[p];
哪修复了？这里直接用 `passes[p]` 不就好了

2020-07-21 09:24 UTC, pandamicro commented on cocos/core/pipeline/shadow/shadow-flow.ts
> +            shadowmapUniform.texture = this._pipeline.shadowFrameBuffer?.colorTextures[0]!;
ShadowFlow 自身不就有 shadowFrameBuffer 嘛

2020-07-21 09:35 UTC, minggo commented on cocos/core/pipeline/render-shadowMap-batched-queue.ts
> + */
语言不对，另外这个注释格式也不对吧，用的 `-`，不像个句子。

2020-07-21 09:35 UTC, minggo commented on cocos/core/pipeline/render-shadowMap-batched-queue.ts
> +        // this._psoCache.clear();
不需要的代码就删了吧

2020-07-21 09:40 UTC, minggo commented on cocos/core/pipeline/render-shadowMap-batched-queue.ts
> +            }
renderObj 是和 Model 一一对应的，而 psoCI 是和 SubModel 对应的，这里的 key 应该是 SubModel 吧。更好的应该是直接用 fullPatches 作为 key 吧。

2020-07-21 09:46 UTC, minggo commented on cocos/core/pipeline/render-shadowMap-batched-queue.ts
> +
多余的空格

2020-07-21 09:47 UTC, minggo commented on cocos/core/pipeline/render-shadowMap-batched-queue.ts
> +            }
_psoCache 确实是可以不要的，因为 PipelineStateManager. getOrCreatePipelineState() 本身就做了 cache 了。

2020-07-21 10:15 UTC, troublemaker52025 commented on cocos/core/pipeline/render-shadowMap-batched-queue.ts
> +            }
尝试用fllPatches作为Key构建chache，发现在绘制ABC三个模型时，只有后传入的C模型被绘制

2020-07-21 10:15 UTC, troublemaker52025 commented on cocos/core/pipeline/render-shadowMap-batched-queue.ts
> +            }
具体原因正在查

2020-07-21 10:19 UTC, troublemaker52025 commented on cocos/core/pipeline/shadow/shadow-flow.ts
> +            shadowmapUniform.texture = this._pipeline.shadowFrameBuffer?.colorTextures[0]!;
醍醐灌顶

2020-07-21 10:19 UTC, troublemaker52025 commented on cocos/core/pipeline/render-shadowMap-batched-queue.ts
> +                psoCI.bindingLayout.update();
测了一下  确实只在创建时update就行

2020-07-21 10:23 UTC, minggo commented on cocos/core/pipeline/render-shadowMap-batched-queue.ts
> +            }
哦，跟 Pass 和 Patches 都有关系。

2020-07-21 10:31 UTC, troublemaker52025 commented on cocos/core/pipeline/render-shadowMap-batched-queue.ts
> + */
改好了

2020-07-21 10:39 UTC, minggo approved these changes

2020-07-21 10:42 UTC, pandamicro approved these changes

2020-07-21 10:42 UTC, merged

2020-07-22 01:39 UTC, Mee-gu commented on cocos/core/pipeline/define.ts
> +    public static SIZE: number = UBOPCFShadow.COUNT * 4;
SIZE 的偏移量应该是 + 4 吧？