game.restart fix
cocos/cocos-engine pull request #6980
Opened 2020-07-13 08:26 UTC by LinYunMo

Re: https://github.com/cocos-creator/3d-tasks/issues/3360

2020-07-14 07:34 UTC, pandamicro requested changes

2020-07-14 07:34 UTC, pandamicro commented on cocos/core/director.ts
> +        cc.game.resume();
不应该这样处理

2020-07-14 07:34 UTC, pandamicro commented on cocos/core/game.ts
> +            game.pause();
为什么要 pause ？

2020-07-15 07:53 UTC, LinYunMo commented on cocos/core/game.ts
> +            game.pause();
在 restart 的过程中不应该停止主循环吗？那在 restart 的过程中如果有依托于主循环的变化也会生效吧？

2020-07-19 08:02 UTC, pandamicro commented on cocos/core/game.ts
> +            game.pause();
现在代码的侵入性太强了，runSceneImmediate 不应该调用 game.resume

2020-07-19 08:03 UTC, pandamicro commented on cocos/core/game.ts
> +            game.pause();
restart 过程中如果要 pause 也应该在 restart 完成后 resume，而不应该在 runScene 的时候 resume

2020-07-20 02:59 UTC, pandamicro approved these changes

2020-07-20 02:59 UTC, pandamicro commented on cocos/core/director.ts
> -        this._root = null;
这里就没必要修改了

2020-07-20 05:31 UTC, merged