[Feature] Adding isPlaying judgement to support the function of gameview
cocos/cocos-engine pull request #6990
Opened 2020-07-16 04:27 UTC by GengineJS

2020-07-16 07:57 UTC, VisualSJ commented on cocos/core/platform/event-manager/system-event.ts
> +        if (EDITOR && !legacyCC.engine.isPlaying) {
这是为什么？
不应该是可以挂上去，但不 emit 么？

2020-07-16 08:10 UTC, GengineJS commented on cocos/core/platform/event-manager/system-event.ts
> +        if (EDITOR && !legacyCC.engine.isPlaying) {
> 这是为什么？
> 不应该是可以挂上去，但不 emit 么？感觉如果可能开启的话， on 就需要都挂上去。
> 
> 另外为啥有的是 legacyCC.engine._isPlaying

_isPlaying与isPlaying现在都有定义，所以两者效果一样，EDITOR在编辑器环境下是true，
EDITOR && !legacyCC.engine.isPlaying代表Gameview还未启动测试，EDITOR && legacyCC.engine.isPlaying代表Gameview已经启动了测试

2020-07-19 08:08 UTC, pandamicro requested changes

2020-07-19 08:08 UTC, pandamicro commented on cocos/core/platform/event-manager/system-event.ts
> +        if (EDITOR && !legacyCC.engine.isPlaying) {
我也赞同 @VisualSJ 说的，用 isPlaying 来判断是否注册事件太奇怪了，一般注册事件的监听器会相信一定可以注册成功，不会再去判断的，如果这样处理了以后很可能很多事件会丢失。@GengineJS 你的回复我也没看懂

2020-07-20 02:44 UTC, GengineJS commented on cocos/core/platform/event-manager/system-event.ts
> +        if (EDITOR && !legacyCC.engine.isPlaying) {
首先之前就有EDITOR判断，目的就是为了防止在editor环境下系统事件误触发，而GameView有运行前(isPlaying=false)与运行时(isPlaying=true)的两种状态,运行前GameView的作用相当于相机预览，而运行时就真正的会让游戏跑起来，由于GameView还是运行在Editor环境，所以CC_EDITOR还是为true，但是GameView在引擎层面并没有提供类似CC_GAMEVIEW
这类的全局属性，如果把GameView运行前称为纯编辑器环境，运行时称为编辑器环境下的GameView混合模式，目前就是通过isPlaying来判断是纯编辑器环境下还是GameView混合模式，其实isPlaying也只有GameView会对其赋值，所以其余平台isPlaying都为undefined，如果觉得legacyCC.engine.isPlaying不好作为Gameview的判断依据，那可以把legacyCC.engine.isPlaying整行代码在编辑器代码中改为CC_GAMEVIEW，因为是在编辑器代码中定义了CC_GAMEVIEW，所以其余平台在访问CC_GAMEVIEW的时候就为undefined，那上面的代码就相当于
`if (EDITOR && !CC_GAMEVIEW)`

2020-07-20 02:49 UTC, GengineJS commented on cocos/core/platform/event-manager/system-event.ts
> +        if (EDITOR && !legacyCC.engine.isPlaying) {
![image](https://user-images.githubusercontent.com/10766457/87894805-59d05a80-ca76-11ea-843b-f1b1aa105e9f.png)
为什么这里不能删` && !legacyCC.engine.isPlaying`回复信息里面已经有提到了，如果删了，GameView在运行时用户自定义的事件监听以及系统内置的监听就没法绑定，因为GameView的CC_EDITOR也为true

2020-07-20 07:59 UTC, pandamicro commented on cocos/core/platform/event-manager/system-event.ts
> +        if (EDITOR && !legacyCC.engine.isPlaying) {
明白了，我觉得我是被名字误导了，我以为这是一个运行时会切换的状态，但实际上这是一个环境状态。建议使用 `GAME_VIEW` 环境标识或者 `legacyCC.engine.playMode` 之类的状态变量

2020-07-21 09:32 UTC, pandamicro approved these changes

2020-07-21 09:36 UTC, merged