Pipeline refactoring.
cocos/cocos-engine pull request #6999
Opened 2020-07-20 06:49 UTC by caryliu1999

目前的结构：

![image](https://user-images.githubusercontent.com/39078800/87907483-53060f80-ca97-11ea-8f8a-2318e2ef4f8c.png)

1. RenderPipeline 中 renderTextures，RenderPassDesc，FrameBufferDesc 这三个关联了资源数据，这部分等编辑器加上 RenderContextAsset 的处理之后，会删除掉，这三者的访问都已经引入到 RenderContext，删掉之后会直接依赖 RenderContext 中 RenderTexture 资源。

2. pipeline, flow, stage 中对数据和 device 的访问全部通过 RenderContext。

3. RenderContext 对 root 的依赖只有 mainWindow, cumulativeTime, frameTime 这三个数据，这个在原生同步时，可以通过其他方式访问，删掉 root 的依赖。

2020-07-20 07:38 UTC, minggo commented
总体改造还是很不错的。正如会议讨论的那样，stage 还是保持和 vulkan 的 subpass 一致会好一点，至于 culling, update UBO 可以是一个函数的功能或者是一个类。保持 stage 与 subpass 的对应关系有个好处就是对于 pipeline 的整个架构的性能和流程有个比较直观的感觉。

2020-07-20 07:40 UTC, minggo commented
culling, update UBO 当成一个 stage 的一个缺点就是 stage 本身对它的一些限制。比如 update UBO stage 有 resize/rebuild 这样的接口也是比较奇怪的。

2020-07-20 07:44 UTC, minggo commented on cocos/core/pipeline/forward/forward-render-context.ts
> +};
末尾得加个空行，具体见[这里的解释](https://stackoverflow.com/questions/2287967/why-is-it-recommended-to-have-empty-line-in-the-end-of-a-source-file#:~:text=Having%20a%20newline%20at%20the,file%20has%20not%20been%20truncated.&text=An%20argument%20can%20also%20be,commas%20allowed%20in%20a%20list%3F)。

2020-07-20 07:49 UTC, caryliu1999 commented
> 总体改造还是很不错的。正如会议讨论的那样，stage 还是保持和 vulkan 的 subpass 一致会好一点，至于 culling, update UBO 可以是一个函数的功能或者是一个类。保持 stage 与 subpass 的对应关系有个好处就是对于 pipeline 的整个架构的性能和流程有个比较直观的感觉。

这个有两种方式，一种是，放在 RenderContext 里面，这样如果确实需要自定义，则可以在继承 RenderContext  的时候重写或者舍弃。另外一种就是，增加 Stage 基类，然后 RenderStage 继承 stage 并对应 subpass，culling stage 直接继承 stage，只做方法执行。

我也再看下未来 Deferred, Forward+, Deferred+ 这些管线对这方面的需求是否足够多，如果没有什么自定义需求的话可以用第一种方式。

2020-07-20 07:54 UTC, minggo commented on cocos/core/root.ts
> +        const rctx = new ForwardRenderContext(this, this._device, this._pipeline);
rctx 不能是 pipeline 自己内部建立吗？

2020-07-20 07:55 UTC, minggo commented on cocos/core/pipeline/common/culling-stage.ts
> + * @zh 前向渲染阶段。
注释不匹配

2020-07-20 07:56 UTC, caryliu1999 commented on cocos/core/root.ts
> +        const rctx = new ForwardRenderContext(this, this._device, this._pipeline);
> rctx 不能是 pipeline 自己内部建立吗？

是要改成资源关联的，然后在 pipeline 内部直接初始化，编辑器部分的修改需要森斌那里加好之后，我会把 pipeline 里面旧的序列化数据和这个一起改掉

2020-07-20 07:58 UTC, minggo commented
> > 总体改造还是很不错的。正如会议讨论的那样，stage 还是保持和 vulkan 的 subpass 一致会好一点，至于 culling, update UBO 可以是一个函数的功能或者是一个类。保持 stage 与 subpass 的对应关系有个好处就是对于 pipeline 的整个架构的性能和流程有个比较直观的感觉。
> 
> 这个有两种方式，一种是，删掉这两个 satge, 执行方法放在 RenderContext 里面，这样如果确实需要自定义，则可以在继承 RenderContext 的时候重写或者舍弃。另外一种就是，增加 Stage 基类，然后 RenderStage 继承 stage 并对应 subpass，culling stage 直接继承 stage，只做方法执行。
> 
> 我也再看下未来 Deferred, Forward+, Deferred+ 这些管线对这方面的需求是否足够多，如果没有什么自定义需求的话可以用第一种方式。

开发者自己继承然后替换对应的类，或者增加接口可以替换 culling/update UBO 函数应该也是可以的把？

2020-07-20 08:08 UTC, caryliu1999 commented
> culling, update UBO 当成一个 stage 的一个缺点就是 stage 本身对它的一些限制。比如 update UBO stage 有 resize/rebuild 这样的接口也是比较奇怪的。

想改为一个 stage 的原因主要是希望这两个方法的执行可以进行自定义，并且可以在一个 flow 的执行过程中去掉或者调整执行的序列位置。

2020-07-20 08:51 UTC, caryliu1999 commented on cocos/core/pipeline/common/culling-stage.ts
> + * @zh 前向渲染阶段。
> 注释不匹配

注释相关的已修改

2020-07-21 02:00 UTC, minggo commented
> 想改为一个 stage 的原因主要是希望这两个方法的执行可以进行自定义，并且可以在一个 flow 的执行过程中去掉或者调整执行的序列位置。尤其是 light culling 这部分，不同管线的处理都不同。

这个应该不需要用 stage 也能完成的吧。

2020-07-21 02:27 UTC, Mee-gu commented on cocos/core/pipeline/common/culling-stage.ts
> +        super.activate(rctx, flow);
activate 对 culling stage 没啥用吧

2020-07-21 02:31 UTC, shrinktofit commented on cocos/core/assets/render-context-asset.ts
> +legacyCC.RenderContextAsset = RenderContextAsset;
3D 不需要这句了

2020-07-21 02:32 UTC, shrinktofit commented on cocos/core/assets/render-stage-asset.ts
> +legacyCC.RenderPipelineAsset = RenderStageAsset;
同上

2020-07-21 03:11 UTC, YunHsiao commented on cocos/core/assets/render-stage-asset.ts
> +    public renderStage: RenderStage | null = null;
pipeline, flow, stage 这些本质上应该是加载优先级最高的脚本，应该不需要再包装一层 asset 了

2020-07-21 03:31 UTC, YunHsiao commented
我觉得我们首先得在设计原则上达成一致，我的倾向是这样的：

对于这种大的框架重构，初期设计尽量追求越简单越好，要在现有需求下对结构先把减法做到极致。一定要记得**框架设计不等于管线设计**，我们的框架提供的是管线开发者手中的基础设施，我们得反复问自己每个设计存在的意义是什么？某个需求是否真的是框架层应该关心的，还是交给实际管线开发者自己去 engineer 就好？有没有更简单干净的方法做到这件事？一定要确保真的没有其他更干净的办法的前提下，再加入框架层面的概念去引导。

在这个原则下，就可以看出一些问题：
* 所有 pipeline 相关的东西首先是一种加载优先级特殊，但功能完全齐备的用户脚本，这个属性应该没法变，所以我们就以这个为最基本的设计，来看在此基础上接下来还需要引入什么：
* 首先 render context 存在的意义似乎不明确（也可能是我没理解清楚），如果只是为了存几个全局常量，完全可以直接通过 property 机制暴露就好了；
* 像定制 culling 等步骤的需求其实并不需要框架层的任何设计，这应该取决于书写 builtin 管线的人是否把代码拆得干净，这里面可以利用的手段包括拆分出单独的类（不需要继承任何 pipeline 结构）或单独的文件，定义 culling 的 interface 和可配置的 property 等，和 render stage 还是 flow 的框架概念其实没有任何关系；

2020-07-21 03:56 UTC, YunHsiao commented
具体任务阶段大致是这样：

* 编辑器加入 pipeline 相关脚本的资源类型，先和用户脚本区分开（现在是完全相同的），把加载时序调对（Load Pipeline -> Engine Init -> Load User Scripts）；
* 修改编辑器 pipeline 资源序列化相关内容，类似 material(对应 .srp) 和 effect(对应 .pipeline, .flow, .stage) 的关系，去掉所有 GFX 资源的直接序列化内容，全部改为标准的 ccclass 序列化机制；
* 删掉引擎内置所有 forward 管线相关内容，精简 render pipeline 等三个基类的内容，理想情况下代码中应该只有框架层的内容（比如三个类之间的关系，和最基础的序列化相关代码）；
* 为确保引擎代码自我完整，引擎可以内置一个最基本的管线，无光照，无 culling，无任何定制内容；
* 开始进入 builtin 管线资源书写阶段，先写一个目前所有项目都在用的标准 LDR forward 管线，确保 instancing、shadow 等功能在符合 vulkan 使用规范下完整实现；
* 加入 TBDR 管线，确保 GLES3 等后端都能跑通使用 PLS；
* 考虑针对不同 GFX 后端做上层 variation，定向优化（compute shader 等）；
* 在结构都验证清楚，GFX 层支持完善后，加入 Foward+，后效等模块

2020-07-21 06:00 UTC, Mee-gu commented on cocos/core/pipeline/render-context.ts
> +        globalUBOBuffer.update(defaultGlobalUBOData);
只更新 HDR 的话，可以通过 offset 更新 buffer：globalUBOBuffer.update(hdrValue, hdrOffset, size);

2020-07-21 06:14 UTC, Mee-gu commented on cocos/core/pipeline/render-flow.ts
> +    public addStage (stage: RenderStage) {
好像没用到？

2020-07-21 06:30 UTC, Mee-gu commented on cocos/core/pipeline/render-pipeline.ts
> +    public addFlow (flow: RenderFlow) {
好像也没用到？

2020-07-21 15:16 UTC, pandamicro requested changes

2020-07-21 15:16 UTC, pandamicro commented on cocos/core/assets/render-context-asset.ts
> +export default class RenderContextAsset extends Asset {
不需要 Asset 把？Pipeline 里面引用一个 ccclass 类型的 RenderContext 就可以了，尽量保持最简单的实现

2020-07-21 15:16 UTC, pandamicro commented on cocos/core/assets/render-stage-asset.ts
> +    public renderStage: RenderStage | null = null;
我也觉得直接让 RenderPipeline, RenderFlow, RenderStage extends Asset 就好了

2020-07-21 15:16 UTC, pandamicro commented on cocos/core/pipeline/common/culling-stage.ts
> +        super.activate(rctx, flow);
这种默认实现就不用继承了

2020-07-21 15:16 UTC, pandamicro commented on cocos/core/pipeline/common/ubo-stage.ts
> +export class UBOStage extends RenderStage {
我希望合并 CullingStage 和 UBOStage 为一个 PrepareStage，节省一些代码和包体

2020-07-21 15:16 UTC, pandamicro commented on cocos/core/pipeline/common/ubo-stage.ts
> +    public render (rctx: RenderContext, view: RenderView) {
在 render 函数中做 updateUBO 的操作看着也挺奇怪的，另外，updateUBO 在不同的管线配置中可能是有比较大区别的，比如开启或关闭 Shadowmap 的情况，未来使用 GI 的情况，这种变化是受到 Flow 或者 Pipeline 级别影响的，如果简单的使用一个 stage 来封装，很可能反而满足不了定制化需求，比较理想的还是 Pipeline 和 Flow 可以影响 updateUBO 的行为（比如调用不同的函数组合）

2020-07-21 15:16 UTC, pandamicro commented on cocos/core/pipeline/common/ubo-stage.ts
> +        fv[UBOGlobal.GLOBAL_FOG_ADD_OFFSET + 2] = fog.fogAtten;
如上所述，这里缺乏一些判断，比如是否开启 FOG，即便是我们这里考虑了各种情况，也难免使得代码过于复杂，判断各种管线配置的组合。updateUBO 应该是根据配置自由组合的形式，而不是写死在一个大的函数中

2020-07-21 15:16 UTC, pandamicro commented on cocos/core/pipeline/common/ubo-stage.ts
> +export class UBOStage extends RenderStage {
仔细想了一下，我觉得不应该抽象 CullingStage 和 UBOStage，这两个只是 render stage 之前的准备过程，不需要硬套用 Stage 的概念，目前只是把一些函数封装成了类，实际上这些类的作用仅仅还是调用函数，看不到有什么好处。

2020-07-23 04:08 UTC, caryliu1999 commented
- 讨论之后，去掉了增加的 asset，取消了 UBOStage 和 CullingStage，目前基类的数据如下：

![image](https://user-images.githubusercontent.com/39078800/88251359-2d6a4780-ccdd-11ea-885b-f90ca60be6d6.png)

2020-07-28 09:42 UTC, minggo commented
代码有冲突

2020-07-28 09:52 UTC, minggo commented on cocos/core/pipeline/render-pipeline.ts
> +    public activate (root: Root): boolean {
应该不用 root 吧，root 可以从 director 去取吧。

2020-07-28 09:58 UTC, minggo commented
把数据都放到 RenderContext 有什么好处吗？类本来就是`数据+算法`的封装，这样分离后使得这样的结构不完整了。另外，也难以哪些数据是需要提取到父类的，这个对于 pipeline 层的抽象也是有帮助的。

2020-07-28 10:08 UTC, caryliu1999 commented on cocos/core/pipeline/render-pipeline.ts
> +    public activate (root: Root): boolean {
> 应该不用 root 吧，root 可以从 director 去取吧。

这个 root 后面加了 share memory 之后可以去掉了，现在只是 UBO 里面用到了 frameTime，需要每帧获取。

2020-07-28 10:15 UTC, caryliu1999 commented
> 把数据都放到 RenderContext 有什么好处吗？类本来就是`数据+算法`的封装，这样分离后使得这样的结构不完整了。另外，也难以哪些数据是需要提取到父类的，这个对于 pipeline 层的抽象也是有帮助的。

RenderContext 主要是管理动态数据，与动态数据相关的会在这里，序列化数据是放在 RenderPipeline，作为 RenderPipelineAsset 的一部分，context 起的作用是，集中管理并且可以共享流程中产生的数据，减少相互依赖，流程执行与数据的分离。

2020-07-28 10:25 UTC, minggo commented
> 集中管理并且可以共享流程中产生的数据，减少相互依赖，流程执行与数据的分离

如果是这样的话，那么就退回到了 c 语言的工作方式了吧。在面向对象编程中，数据应该是有归属的。

2020-07-28 11:15 UTC, caryliu1999 commented
> 代码有冲突

已解决

2020-07-28 11:20 UTC, caryliu1999 commented on cocos/core/pipeline/common/ubo-stage.ts
> +        fv[UBOGlobal.GLOBAL_FOG_ADD_OFFSET + 2] = fog.fogAtten;
> 如上所述，这里缺乏一些判断，比如是否开启 FOG，即便是我们这里考虑了各种情况，也难免使得代码过于复杂，判断各种管线配置的组合。updateUBO 应该是根据配置自由组合的形式，而不是写死在一个大的函数中

增加了 fog 是否开启的判断

2020-07-28 11:23 UTC, caryliu1999 commented
> > 集中管理并且可以共享流程中产生的数据，减少相互依赖，流程执行与数据的分离
> 
> 如果是这样的话，那么就退回到了 c 语言的工作方式了吧。在面向对象编程中，数据应该是有归属的。

Context 本身还是归属于 RenderPipeline

2020-07-29 06:14 UTC, minggo commented
> Context 本身还是归属于 RenderPipeline

context 里包含有 createUBO, updateUBO 等接口是很奇怪的。这些方法本应该放进 pipeline 里的，里面的成员变量也应该是分散到 pipeline/flow/stage 里的。目前的这种做法我觉得不是很合适，感觉只要是变量都可以扔到里面，没有归属于正确的类里。

2020-07-29 06:16 UTC, caryliu1999 commented
> > Context 本身还是归属于 RenderPipeline
> 
> context 里包含有 createUBO, updateUBO 等接口是很奇怪的。这些方法本应该放进 pipeline 里的，里面的成员变量也应该是分散到 pipeline/flow/stage 里的。目前的这种做法我觉得不是很合适，感觉只要是变量都可以扔到里面，没有归属于正确的类里。

可以，那我改下吧，分散到各自的对象里面，交由各个对象管理

2020-07-29 06:45 UTC, YunHsiao commented on cocos/core/pipeline/render-pipeline.ts
> +    public activate (root: Root): boolean {
frameTime 其实应该 pipeline 来算，root 从 pipeline 取这个数字，结构得整一整

2020-07-29 07:08 UTC, caryliu1999 commented
> > Context 本身还是归属于 RenderPipeline
> 
> context 里包含有 createUBO, updateUBO 等接口是很奇怪的。这些方法本应该放进 pipeline 里的，里面的成员变量也应该是分散到 pipeline/flow/stage 里的。目前的这种做法我觉得不是很合适，感觉只要是变量都可以扔到里面，没有归属于正确的类里。

已修改

2020-07-29 07:25 UTC, YunHsiao commented on cocos/core/pipeline/render-stage.ts
>      protected renderQueues: RenderQueueDesc[] = [];
这个也可以删了，render queue 也是管线层的概念，不需要放在框架里

2020-07-29 07:25 UTC, YunHsiao commented on cocos/core/pipeline/render-stage.ts
>          this._priority = info.priority;
这个是个潜在的好的留在框架里的设计，我觉得保留没问题

2020-07-29 07:25 UTC, YunHsiao commented on cocos/core/pipeline/render-pipeline.ts
>      protected _globalBindings: Map<string, IInternalBindingInst> = new Map<string, IInternalBindingInst>();
这个虽然确实可以留着，但应该还有不少优化余地，里面不少多余的东西，而且也别用 string 索引了。。

2020-07-29 07:25 UTC, YunHsiao commented on cocos/core/pipeline/render-flow.ts
>      protected _type: RenderFlowType = RenderFlowType.SCENE;
不要用写死的 enum 了，这其实就是需要一个 tag 的机制，让开发者可以自己做些简单的逻辑就行

2020-07-29 08:46 UTC, caryliu1999 commented on cocos/core/pipeline/render-stage.ts
>      protected renderQueues: RenderQueueDesc[] = [];
> 这个也可以删了，render queue 也是管线层的概念，不需要放在框架里

已删除

2020-07-29 08:53 UTC, caryliu1999 commented on cocos/core/pipeline/render-pipeline.ts
>      protected _globalBindings: Map<string, IInternalBindingInst> = new Map<string, IInternalBindingInst>();
> 这个虽然确实可以留着，但应该还有不少优化余地，里面不少多余的东西，而且也别用 string 索引了。。

这个其实可以放在外部，不放在 pipeline，包括 macros，这样也少一些对 pipeline 的依赖

2020-07-29 08:55 UTC, caryliu1999 commented on cocos/core/pipeline/render-flow.ts
>      protected _type: RenderFlowType = RenderFlowType.SCENE;
> 不要用写死的 enum 了，这其实就是需要一个 tag 的机制，让开发者可以自己做些简单的逻辑就行，我觉得直接给个 number 类型就好了；另外要加就在 pipeline/flow/stage 都加上，确保体验一致

已修改为 number，增加了 stage 的 type，跟 flow 保持一致，这个主要是对 flows 和 stages 列表做归类用的，pipeline 就没有必要了

2020-07-29 09:06 UTC, YunHsiao commented on cocos/core/pipeline/render-flow.ts
>      protected _type: RenderFlowType = RenderFlowType.SCENE;
还是一样的情况啊，这个 type 还是管线层的概念，框架层不需要，而 tag 是一个更通用的逻辑，pipeline 也可能需要 tag

2020-07-29 09:13 UTC, YunHsiao commented on cocos/core/pipeline/render-pipeline.ts
>      protected _globalBindings: Map<string, IInternalBindingInst> = new Map<string, IInternalBindingInst>();
这个里面最主要的是存 pipeline 提供的 uniform 信息和相关的 gfx 资源，还是有放在 pipeline 里的必要的，而且目前像 program-lib 等也依赖它创建 shader，所以看起来一下不好移出基类，可以再议

2020-07-29 10:06 UTC, minggo commented on cocos/core/pipeline/forward/scene-culling.ts
> +}
文件末尾空行

2020-07-29 10:09 UTC, minggo approved these changes

2020-07-29 10:09 UTC, caryliu1999 commented on cocos/core/pipeline/forward/scene-culling.ts
> +}
> 文件末尾空行

已修改

2020-07-29 11:18 UTC, caryliu1999 commented on cocos/core/pipeline/render-pipeline.ts
>      protected _globalBindings: Map<string, IInternalBindingInst> = new Map<string, IInternalBindingInst>();
> 这个里面最主要的是存 pipeline 提供的 uniform 信息和相关的 gfx 资源，还是有放在 pipeline 里的必要的，而且目前像 program-lib 等也直接依赖它创建 shader，所以看起来一下不好移出基类，可以再议

可以使用 uniform 的 binding 做索引，是 number 类型的，不过像 'CCLocal' 和 'CCLocalBatched' 用的是同一个 binding，改为两个会多占用一个 binding 位

2020-07-29 11:27 UTC, caryliu1999 commented on cocos/core/pipeline/render-flow.ts
>      protected _type: RenderFlowType = RenderFlowType.SCENE;
> 还是一样的情况啊，这个 type 还是管线层的概念，框架层不需要，而 tag 是一个更通用，更适合放在框架里的概念，pipeline 也可能需要 tag

已增加

2020-07-29 15:06 UTC, YunHsiao commented on cocos/core/pipeline/render-pipeline.ts
>      protected _globalBindings: Map<string, IInternalBindingInst> = new Map<string, IInternalBindingInst>();
嗯不能直接用 binding，可以再加一个自动生成 id 做 key

2020-07-29 15:07 UTC, YunHsiao commented on cocos/core/pipeline/render-pipeline.ts
> +        return this._type;
统一别叫 type 了

2020-07-30 03:39 UTC, caryliu1999 commented on cocos/core/pipeline/render-pipeline.ts
> +    public activate (root: Root): boolean {
> frameTime 其实应该 pipeline 来算，root 从 pipeline 取这个数字，结构得整一整

frameTime 和 cumulativeTime 放在了 pipeline ,  root 里面从 pipeline 里面取，去掉了 root 依赖

2020-07-30 03:52 UTC, minggo commented on cocos/core/root.ts
> +        this.pipeline.frameTime = deltaTime;
这样会导致每帧都需要 JSB 调用了。而且 frameTime 也不应该是存储在 pipeline 里的。到时可以把这个值放到 shared memory 里就可以了。

2020-07-30 04:19 UTC, caryliu1999 commented on cocos/core/pipeline/render-pipeline.ts
> +        return this._type;
> 统一别叫 type 了

全部修改为 tag 了

2020-07-30 04:22 UTC, caryliu1999 commented on cocos/core/root.ts
> +        this.pipeline.frameTime = deltaTime;
> 这样会导致每帧都需要 JSB 调用了。而且 frameTime 也不应该是存储在 pipeline 里的。到时可以把这个值放到 shared memory 里就可以了。

对，这个肯定要放在 shared memory 里面，那还是先放在 root 吧，等全局的 shared memory 加好再改这个

2020-07-30 04:26 UTC, caryliu1999 commented on cocos/core/root.ts
> +        this.pipeline.frameTime = deltaTime;
> 这样会导致每帧都需要 JSB 调用了。而且 frameTime 也不应该是存储在 pipeline 里的。到时可以把这个值放到 shared memory 里就可以了。

对，这个肯定要放在 shared memory 里面，那还是先放在 root 吧，等全局的 shared memory 加好再改这个

2020-07-30 04:47 UTC, caryliu1999 commented on cocos/core/root.ts
> +        this.pipeline.frameTime = deltaTime;
> 这样会导致每帧都需要 JSB 调用了。而且 frameTime 也不应该是存储在 pipeline 里的。到时可以把这个值放到 shared memory 里就可以了。

已修改

2020-07-31 02:11 UTC, YunHsiao approved these changes

2020-07-31 10:41 UTC, pandamicro approved these changes

2020-08-03 02:36 UTC, merged