让 ObjectLayer 支持动画tile
cocos/cocos-engine pull request #7032
Opened 2020-07-27 20:39 UTC by finscn

TiledMap 的 ObjectLayer 里可以放入 tile,  而且支持 动画tile.
之前版本的 CCTiledMap组件不支持这个特性.
该pr实现了这个特性.

同时优化了一点代码结构.
比如 对 ISO地图的判定 统一放到了前面.

2020-07-28 02:05 UTC, holycanvas commented on cocos2d/tilemap/CCTiledObjectGroup.js
> +    getPositionOffset() {
不要改空格啦，这是Creator的代码规范...

2020-07-28 17:00 UTC, finscn commented on cocos2d/tilemap/CCTiledObjectGroup.js
> +    getPositionOffset() {
我是用的VS自带的代码格式化功能自动格式化的.
你们用的是什么代码格式工具 推荐一个 .

或者写个github的脚本? 对提交的代码自动格式化? 

(顺便吐槽下, 你们的代码里 太多 行尾空格了...)

2020-07-28 17:04 UTC, finscn commented on cocos2d/tilemap/CCTiledObjectGroup.js
> +    getPositionOffset() {
改好了 , 空格加回去了

2020-08-04 03:26 UTC, holycanvas commented on cocos2d/tilemap/CCTiledObjectGroup.js
> +    getPositionOffset() {
额，继承下来的风格.

2020-08-27 07:47 UTC, 2youyou2 commented on cocos2d/tilemap/CCTiledObjectGroup.js
> +    getPositionOffset() {
vs 自带的就可以，要改下配置

![image](https://user-images.githubusercontent.com/1862402/91412626-a03a8580-e87c-11ea-8e98-9252dfa1fd67.png)

2020-08-27 08:08 UTC, jareguo requested changes

2020-08-27 08:08 UTC, jareguo commented on cocos2d/tilemap/CCTiledObjectGroup.js
> +        this._hasAniObj = false;
destroy 的时候不需要重置属性，重置是 CCObject 统一进行的

2020-08-27 08:12 UTC, jareguo approved these changes

2020-08-28 16:00 UTC, finscn commented
PR #7242 已经涵盖并增强了此PR.

2020-08-28 16:00 UTC, closed without merging