Resolve light instanced
cocos/cocos-engine pull request #7039
Opened 2020-07-29 06:52 UTC by troublemaker52025

https://github.com/cocos-creator/3d-tasks/issues/3971

Re: cocos-creator/2d-tasks#

Changes:
 *

2020-07-29 09:56 UTC, minggo commented on cocos/core/pipeline/instanced-buffer.ts
> +                }
重复代码，只要修改 fullPatches 就可以了。

2020-07-30 08:10 UTC, troublemaker52025 commented on cocos/core/pipeline/instanced-buffer.ts
> +                }
修改好了

2020-07-30 08:40 UTC, YunHsiao commented on cocos/core/pipeline/instanced-buffer.ts
> +        if (!this.psoci) {
这个 if 应该放在 switch 外面

2020-07-30 08:51 UTC, YunHsiao commented on cocos/core/pipeline/forward/forward-stage.ts
> +                            }
还得根据 pass 的 phase 判断一下，如果不是 forward add phase 还得像原来一样加入默认的那个 buffer

2020-07-30 09:19 UTC, troublemaker52025 commented on cocos/core/pipeline/forward/forward-stage.ts
> +                            }
好的

2020-07-30 09:43 UTC, troublemaker52025 commented on cocos/core/pipeline/instanced-buffer.ts
> +        if (!this.psoci) {
改好了

2020-07-30 10:13 UTC, YunHsiao commented on cocos/core/pipeline/instanced-buffer.ts
> +        return InstancedBuffer._lightBuffers.get(index)!;
这个思路还是挺好的

2020-07-30 10:13 UTC, YunHsiao commented on cocos/core/pipeline/instanced-buffer.ts
> +        if (!this.psoci) {
要改完整，fullPatch 的声明也没有必要放外面吧

2020-07-30 10:16 UTC, troublemaker52025 commented on cocos/core/pipeline/instanced-buffer.ts
> +        if (!this.psoci) {
确实

2020-07-30 10:16 UTC, troublemaker52025 commented on cocos/core/pipeline/instanced-buffer.ts
> +        return InstancedBuffer._lightBuffers.get(index)!;
改的时候   想着不能影响主版本现有的功能   我就才用了附加的想法

2020-07-30 10:27 UTC, YunHsiao approved these changes

2020-07-31 01:37 UTC, Mee-gu commented on cocos/core/pipeline/instanced-buffer.ts
> +        const subModel = renderObj.model.subModelNum[subModelIdx];
.subModelNum? 这个有问题吧？

2020-07-31 02:03 UTC, minggo approved these changes

2020-07-31 08:36 UTC, troublemaker52025 commented on cocos/core/pipeline/instanced-buffer.ts
> +        const subModel = renderObj.model.subModelNum[subModelIdx];
一般都是这么取subModel的，测下来也没遇到过问题

2020-07-31 09:34 UTC, YunHsiao commented on cocos/core/pipeline/instanced-buffer.ts
> +        const subModel = renderObj.model.subModelNum[subModelIdx];
这个肯定是错了，应该是 subModels 不是 subModelNum，还是得看清楚

2020-07-31 09:40 UTC, troublemaker52025 commented on cocos/core/pipeline/instanced-buffer.ts
> +        const subModel = renderObj.model.subModelNum[subModelIdx];
确实是我用错了

2020-08-02 15:18 UTC, pandamicro commented
同  #7055 ，我觉得主要问题是 BatchedBuffer 和 InstancedBuffer 中加入了 Light 的耦合，而不是用统一、上层无关的逻辑去合并 Light pass buffer 和 model render pass buffer。我希望 Buffer 的行为只是做数据的合并 ，不关心上层的类型。

2020-08-03 11:11 UTC, pandamicro commented
目前这个方案我觉得会更合理一些， @minggo @YunHsiao 你们觉得呢？

2020-08-04 02:26 UTC, minggo commented on cocos/core/pipeline/light-instanced-buffer.ts
> +}
文件末尾空格

2020-08-04 02:26 UTC, minggo commented on cocos/core/pipeline/pass-instanced-buffer.ts
> +}
同上

2020-08-04 02:36 UTC, minggo commented on cocos/core/pipeline/forward/forward-stage.ts
> +                            }
这个逻辑我没看懂，`pass.phase === this._phaseID` 能区分受光照影响？

2020-08-04 06:29 UTC, troublemaker52025 commented on cocos/core/pipeline/forward/forward-stage.ts
> +                            }
带光照的effect中  有这个phaseID，不带光照是没有这个的

2020-08-04 09:01 UTC, minggo commented on cocos/core/pipeline/forward/forward-stage.ts
> +                            }
额，那这个变量名取得不好啊。如果是 
```
pass.phase === this._passPhaseID;
```

就会清晰一点。

2020-08-05 06:23 UTC, troublemaker52025 commented on cocos/core/pipeline/forward/forward-stage.ts
> +                            }
改好了

2020-08-05 07:19 UTC, pandamicro requested changes

2020-08-05 07:19 UTC, pandamicro commented on cocos/core/pipeline/light-instanced-buffer.ts
> +    private static _buffers = new Map<number, InstancedBuffer>();
两个子类的差异太小了，确实不值得，可以回退到之前统一的 InstancedBuffer。另外，light 和 pass map是完全可以合并的，JS Map 的 key 可以是任意类型，实际上相当于使用 Object ref 来作为 key。建议声明为：

```
private static _buffers = new Map<Pass | number, InstancedBuffer>();
```

同时 get 接口创建 buffer 主要需要的 device 也可以作为参数传入

```
    public static get (key: Pass | number, device: GFXDevice) {
        let buffers = InstancedBuffer._buffers;
        if (!buffers.has(key)) {
            let buffer = new InstancedBuffer(device);
            buffers.set(key, buffer);
            return buffer;
        }
        return buffers.get(index)!;
    }
```

2020-08-05 09:12 UTC, pandamicro approved these changes

2020-08-05 09:22 UTC, merged