sync 2d richt text component
cocos/cocos-engine pull request #7046
Opened 2020-07-30 06:03 UTC by knoxHuang

Re: cocos-creator/2d-tasks#

Changes:
 * sync 2d richt text

使用系统字体
![image](https://user-images.githubusercontent.com/7564028/88886565-535b9300-d26d-11ea-8e37-86f384571ff0.png)

不使用系统字体
![image](https://user-images.githubusercontent.com/7564028/88886608-69695380-d26d-11ea-9484-b80449f7ecff.png)

范例效果图：

![image](https://user-images.githubusercontent.com/7564028/88886543-476fd100-d26d-11ea-91a0-6e27f8b06b0e.png)

2020-08-05 03:18 UTC, JoneLau requested changes

2020-08-05 03:18 UTC, JoneLau commented on cocos/ui/components/rich-text-component.ts
> +        const labelComponent = labelSeg.node.getComponent(LabelComponent)!;
这里也不需要加 ！

2020-08-06 06:22 UTC, JoneLau requested changes

2020-08-06 06:22 UTC, JoneLau commented on cocos/ui/components/rich-text-component.ts
> +        this.node.on(Node.EventType.TRANSFORM_CHANGED, this._onTransformChanged, this);
这里可能没有沟通清楚，transform_changed 涉及的部分是 position/rotation/scale 三个部分，不包含 anchor_changed 和 size_changed，所以你这里的监听能生效吗？按理来说 anchor 和 size 改动是不会影响到 transform，我的意思是 ui 节点按理来说计算是的 rect，不管是 anchor 还是 size 的改动，其实都是要重新计算 rect 的，把这两个部分合并到一个事件会不会合理一点（最好的做法其实是合并到 transform 里对 ui 来说是一样的，但是 transform 目前还涉及到 3d 部分，所以不是特别合适，就好比 uitransform 身上没有 transform 信息一样）

2020-08-06 06:22 UTC, JoneLau commented on cocos/ui/components/rich-text-component.ts
> +            let sprite = label.node.getComponent(SpriteComponent);
这个从 label 身上获取 spriteComponent 的做法我没看懂，一个节点身上只能有一个渲染组件，label 和 sprite 不能共存的

2020-08-06 06:30 UTC, knoxHuang commented on cocos/ui/components/rich-text-component.ts
> +        this.node.on(Node.EventType.TRANSFORM_CHANGED, this._onTransformChanged, this);
如果按照你说的，是不生效的，我这边把 anchor 加回来

2020-08-06 06:41 UTC, knoxHuang commented on cocos/ui/components/rich-text-component.ts
> +            let sprite = label.node.getComponent(SpriteComponent);
因为这个 label 是从 _labelSegments 取出来的，他里面有可能包含了 ImageElement 跟 labelElement，可以改一下名字不要叫 label

2020-08-06 06:56 UTC, knoxHuang commented
改 pr 关闭，移动到 https://github.com/cocos-creator/engine/pull/7046

2020-08-06 06:56 UTC, closed without merging