Resolve light instanced
cocos/cocos-engine pull request #7055
Opened 2020-07-31 07:33 UTC by troublemaker52025

https://github.com/cocos-creator/3d-tasks/issues/3467
Re: cocos-creator/2d-tasks#

Changes:
 *

2020-08-01 09:59 UTC, pandamicro requested changes

2020-08-01 09:59 UTC, pandamicro commented on cocos/core/pipeline/batched-buffer.ts
>  export class BatchedBuffer {
架构上来说，应该抽象 PassBatchedBuffer 和 LightBatchedBuffer 继承自 BatchedBuffer，区分通用逻辑和特有逻辑，这样会更清晰

2020-08-01 10:05 UTC, pandamicro commented on cocos/core/pipeline/forward/forward-stage.ts
> +    private _phaseID = getPhaseID('forward-add');
这种命名有问题，应该用 _forwardAddID

2020-08-01 10:05 UTC, pandamicro commented on cocos/core/pipeline/batched-buffer.ts
> +            this.psoci!.bindingLayout.update();
psoci 在 batch buffer 里面创建还是很奇怪，有打洞的意味。light 的处理流程感觉破坏了结构设计

2020-08-05 09:10 UTC, pandamicro approved these changes

2020-08-05 09:17 UTC, minggo approved these changes

2020-08-05 09:24 UTC, merged