sync 2d toggle/toggle-container component
cocos/cocos-engine pull request #7057
Opened 2020-07-31 08:57 UTC by knoxHuang

Re: cocos-creator/2d-tasks#3960
Changes:
 * sync 2d toggle/toggle-container component

2020-08-05 03:03 UTC, JoneLau requested changes

2020-08-05 03:03 UTC, JoneLau commented on cocos/ui/components/toggle-component.ts
> +    private set (value: boolean, emitEvent: boolean = true) {
引擎内除非是不希望用户之后会继承修改采用 private，不然尽量用 protected，然后这两者声明的都要加 _。建议帮忙把不合理的 private 都改成 protected

2020-08-05 04:03 UTC, JoneLau approved these changes

2020-08-11 07:18 UTC, LinYunMo approved these changes

2020-08-12 15:44 UTC, merged