sync 2d outline component
cocos/cocos-engine pull request #7061
Opened 2020-08-03 02:12 UTC by knoxHuang

Re: cocos-creator/2d-tasks#3960, https://github.com/cocos-creator/engine/pull/3564

Changes:
 * sync 2d outline component

2020-08-04 11:32 UTC, pandamicro requested changes

2020-08-04 11:32 UTC, pandamicro commented on cocos/ui/components/label-outline-component.ts
> +        return this._color.clone();
这里声明了 Readonly，不需要 clone，如果用户需要修改会自己去 clone

2020-08-05 02:19 UTC, JoneLau requested changes

2020-08-05 02:19 UTC, JoneLau commented on cocos/ui/components/label-outline-component.ts
> +        const label = this.node.getComponent(LabelComponent)!;
不能完全确定的这里不用加 ！

2020-08-05 04:04 UTC, JoneLau approved these changes

2020-08-05 05:45 UTC, pandamicro approved these changes

2020-08-05 07:28 UTC, merged