sync 2d scrollview-view component
cocos/cocos-engine pull request #7068
Opened 2020-08-04 03:01 UTC by knoxHuang

Re: https://github.com/cocos-creator/3d-tasks/issues/4023

Changes:
 * sync 2d scrollview-view component

2020-08-05 02:04 UTC, JoneLau requested changes

2020-08-05 02:04 UTC, JoneLau commented on cocos/ui/components/scroll-view-component.ts
> +        const scrollSize = uiTransformComp!.contentSize;
content 的尺寸始终对齐 node 尺寸？不然为什么始终取 node 的 uiTransform

2020-08-05 02:11 UTC, JoneLau commented
这个 pr 最终是要合到 3.0，this._content!._uiProps.uiTransformComp 建议这里直接将 content 这个属性类型是 node 的，做成 uitransform，然后做一次数据迁移

2020-08-05 03:59 UTC, knoxHuang commented
这个 pr 最终是要合到 3.0，this._content!._uiProps.uiTransformComp 建议这里直接将 content 这个属性类型是 node 的，做成 uitransform，然后做一次数据迁移
———————————————
这个之前沟通过，先让嘉宁整合到 node 属性再统一修改

2020-08-05 05:47 UTC, pandamicro commented
> 这个之前沟通过，先让嘉宁整合到 node 属性再统一修改

什么意思？uiTransform 属性不会进入 Node

2020-08-05 05:56 UTC, knoxHuang commented
是我，误解了，我这个一并弄吧

2020-08-06 04:08 UTC, knoxHuang commented
这个是按照 3.0.0 版本去处理的，所以不兼容旧版本，@pandamicro 还是需要进行数据迁移？

2020-08-06 06:47 UTC, JoneLau approved these changes

2020-08-11 07:38 UTC, LinYunMo approved these changes

2020-08-12 15:36 UTC, pandamicro approved these changes

2020-08-14 02:30 UTC, merged