sync bug fix for EditBox from 2d branch
cocos/cocos-engine pull request #7071
Opened 2020-08-04 06:57 UTC by PPpro

re: 
https://github.com/cocos-creator/3d-tasks/issues/3986
https://github.com/cocos-creator/3d-tasks/issues/4026

changeLog:
- add type definition for setter in EditBox https://github.com/cocos-creator/engine/pull/5088/commits/4c7670faf249c380dff8a17a8d6b46107907841e
- support browser type EDGE https://github.com/cocos-creator/engine/pull/4910/commits/8e041123e2bd7bbeba3a04469f0cc029a3d24d34
- hide clear button of input on EDGE browser https://github.com/cocos-creator/engine/pull/5088/commits/be6c94c4444c59b47c62ca96403b552b6a80a225

2020-08-17 03:26 UTC, VisualSJ commented
@pandamicro @JoneLau Please reconfirm the status of this PR

2020-08-18 03:12 UTC, JoneLau requested changes

2020-08-18 03:12 UTC, JoneLau commented on cocos/ui/components/editbox/edit-box-impl.ts
> +        let fontSize = textLabel.fontSize * textLabel.node._scale.y;
这个 node._scale 可以直接获取的吗，我看 node 里是 protected 的

2020-08-18 03:12 UTC, JoneLau commented on cocos/ui/components/editbox/edit-box-component.ts
> +    set placeholder (value: string) {
这里是只有 set 没有 get 是吗，不然好像没有必要定义类型，因为会根据 get 的类型决定 value 的类型

2020-08-18 03:13 UTC, JoneLau requested changes

2020-08-18 03:13 UTC, JoneLau commented on cocos/ui/components/editbox/edit-box-impl.ts
> +        let fontSize = placeholderLabel.fontSize * placeholderLabel.node._scale.y;
这里也同样不能用 node._scale，应该用 node.scale.y

2020-08-18 06:55 UTC, JoneLau approved these changes

2020-08-19 06:33 UTC, pandamicro approved these changes

2020-08-19 06:34 UTC, merged