Fix typo
cocos/cocos-engine pull request #7102
Opened 2020-08-07 11:01 UTC by shrinktofit

Re: cocos-creator/3d-tasks#

Changelog:
 *

2020-08-07 11:52 UTC, pandamicro requested changes

2020-08-07 11:52 UTC, pandamicro commented on cocos/core/components/ui-base/canvas-component.ts
> -    @property('清理颜色缓冲区后的颜色')
不能删除 property，会导致 color 无法显示在 inspector 中

2020-08-10 06:08 UTC, shrinktofit commented on cocos/core/components/ui-base/canvas-component.ts
> -    @property('清理颜色缓冲区后的颜色')
The `tooltip` is alias of `property({ tooltip })`

2020-08-10 08:05 UTC, pandamicro approved these changes

2020-08-10 08:05 UTC, merged