修改setPosition的默认行为.
cocos/cocos-engine pull request #7104
Opened 2020-08-08 05:48 UTC by finscn

当不传入 z 时,  不会改变 node的 position.z 值

Re: cocos-creator/2d-tasks#

Changes:
 *

2020-08-08 07:45 UTC, jareguo commented on cocos2d/core/CCNode.js
> +        }
不对吧，如果传入了 vec3，z 会等于传入值。这里不能覆盖传入值

2020-08-08 07:45 UTC, jareguo commented on cocos2d/core/CCNode.js
> +            z = newPosOrX.z;
如果传入 vec2，这里会 z = 0

2020-08-08 09:07 UTC, finscn commented on cocos2d/core/CCNode.js
> +            z = newPosOrX.z;
我看了源码 vec2 并没有 z属性,  z不等于0 .

2020-08-08 09:08 UTC, finscn commented on cocos2d/core/CCNode.js
> +        }
> 不对吧，如果传入了 vec3，z 会等于传入值。这里不能覆盖传入值

如果传入 vec3 , 前面会执行  
z = newPosOrX.z;

到这这步 z !== undefined.

2020-08-08 09:49 UTC, jareguo commented on cocos2d/core/CCNode.js
> +            z = newPosOrX.z;
![image](https://user-images.githubusercontent.com/1503156/89707323-7be73980-d99f-11ea-8de8-c7e02bd87153.png)
有的

2020-08-08 10:31 UTC, jareguo commented on cocos2d/core/CCNode.js
> +     * 2. 传入 cc.v2(x, y) 类型为 cc.Vec2 的对象 (此时不会改变position的z值)。
此时 z 会被重置为 0，麻烦更正一下注释。另外中文和英文之间插入个空格

2020-08-08 10:31 UTC, jareguo commented on cocos2d/core/CCNode.js
>              x = x.x;
这里代码执行顺序不可更改，改完之后 x 变成了 number，再获取 x.y 就报错了

2020-08-08 10:32 UTC, jareguo commented on cocos2d/core/CCNode.js
> +     * 当只传入 (x, y) 或 Vec2对象时, 不会改变 scale.z 的值.
这里注释也应该调整，vec2 会改变 scale z

2020-08-10 03:38 UTC, pandamicro requested changes

2020-08-10 03:38 UTC, pandamicro commented on cocos2d/core/CCNode.js
> +        if (x && typeof x !== 'number') {
没必要用 typeof 判断，我们不希望过多防御，对于参数类型的区别，仅通过参数数量来识别即可

2020-08-10 03:38 UTC, pandamicro commented on cocos2d/core/CCNode.js
> +     * node.setScale(cc.v2(2, 2)); // Notice: scaleZ will be 0
scaleZ will remain unchanged

2020-08-10 03:40 UTC, finscn commented on cocos2d/core/CCNode.js
> +        if (x && typeof x !== 'number') {
我是看到 setScale里用了, 才改的这个地方. 那直接判断 y === undefined ? 那 setScale是不是也要改?

2020-08-10 03:40 UTC, finscn commented on cocos2d/core/CCNode.js
> +     * node.setScale(cc.v2(2, 2)); // Notice: scaleZ will be 0
按照目前的设计  cc.v2 的z=0 , 所以 会用0覆盖scaleZ.

2020-08-10 03:43 UTC, jareguo commented on cocos2d/core/CCNode.js
> +        };
if 后面不要加分号

2020-08-10 03:44 UTC, jareguo commented on cocos2d/core/CCNode.js
> +     * 当只传入 (x, y) 或 Vec2 对象时，scale.z 的值将被设置为0。
从现有代码来看，只传入 x, y 两个参数时，z 并不会被修改到

2020-08-10 04:11 UTC, pandamicro approved these changes

2020-08-11 05:56 UTC, merged