Move global data of scene to pipeline.
cocos/cocos-engine pull request #7109
Opened 2020-08-10 13:45 UTC by caryliu1999

Re: https://github.com/cocos-creator/3d-tasks/issues/2395

2020-08-13 04:14 UTC, pandamicro commented on cocos/core/pipeline/forward/scene-culling.ts
> +    if (pipeline.skybox.enabled && (camera.clearFlag & SKYBOX_FLAG)) {
检查一下 model 是否存在把

2020-08-13 04:14 UTC, pandamicro commented on cocos/core/pipeline/forward/forward-stage.ts
> +        pipeline.planarShadows!.enabled && pipeline.planarShadows!.recordCommandBuffer(device, renderPass, cmdBuff);
把 pipeline 类型转为 ForwardPipeline 应该就不需要 ! 了

2020-08-13 04:14 UTC, pandamicro commented on cocos/core/renderer/scene/fog.ts
> +     * 返回当前全局雾类型
returns 只支持一个，保留英文的就可以

2020-08-13 04:14 UTC, pandamicro commented on cocos/core/renderer/scene/planar-shadows.ts
> +    }
不需要空构造函数

2020-08-13 04:14 UTC, pandamicro commented on cocos/core/renderer/scene/planar-shadows.ts
> -        if (this._scene.mainLight) { this.updateDirLight(this._scene.mainLight); }
不应该去掉这些把？运行时动态操控开启和关闭状态应该需要更新的

2020-08-13 04:14 UTC, pandamicro commented on cocos/core/renderer/scene/planar-shadows.ts
> +        this._instancingMaterial!.destroy();
感觉强制判断有些过多了，假设管线中使用了 planar shadow，但是还没有启用就被替换了，并触发旧管线的 destroy，那么应该会有不少问题

2020-08-13 04:14 UTC, pandamicro commented on cocos/core/scene-graph/scene-globals.ts
>  import { legacyCC } from '../global-exports';
scene-globals 为啥只保留 SkyboxInfos 信息，为什么不删除这个文件呢？

2020-08-14 08:50 UTC, caryliu1999 commented on cocos/core/pipeline/forward/forward-stage.ts
> +        pipeline.planarShadows!.enabled && pipeline.planarShadows!.recordCommandBuffer(device, renderPass, cmdBuff);
> 把 pipeline 类型转为 ForwardPipeline 应该就不需要 ! 了

已修改

2020-08-14 08:50 UTC, caryliu1999 commented on cocos/core/renderer/scene/fog.ts
> +     * 返回当前全局雾类型
> returns 只支持一个，保留英文的就可以

已修改

2020-08-14 08:50 UTC, caryliu1999 commented on cocos/core/renderer/scene/planar-shadows.ts
> +    }
> 不需要空构造函数

已删除

2020-08-14 08:52 UTC, caryliu1999 commented on cocos/core/renderer/scene/planar-shadows.ts
> -        if (this._scene.mainLight) { this.updateDirLight(this._scene.mainLight); }
> 不应该去掉这些把？运行时动态操控开启和关闭状态应该需要更新的

在每帧的 sceneCulling 的时候本来就会去调用更新了，而且现在这些是跟场景无关的

2020-08-14 08:52 UTC, caryliu1999 commented on cocos/core/renderer/scene/planar-shadows.ts
> +        this._instancingMaterial!.destroy();
> 感觉强制判断有些过多了，假设管线中使用了 planar shadow，但是还没有启用就被替换了，并触发旧管线的 destroy，那么应该会有不少问题

已修改

2020-08-14 15:25 UTC, pandamicro requested changes

2020-08-14 15:25 UTC, pandamicro commented on cocos/core/pipeline/render-pipeline.ts
> +legacyCC.RenderPipeline = RenderPipeline;
不需要再使用 legacyCC 暴露任何类了

2020-08-14 15:25 UTC, pandamicro commented on cocos/core/scene-graph/scene-globals.ts
>  import { legacyCC } from '../global-exports';
建议这个文件改名为 skybox-info 把

2020-08-16 14:51 UTC, pandamicro approved these changes

2020-08-17 15:08 UTC, merged