UI sharedMaterial
cocos/cocos-engine pull request #7112
Opened 2020-08-11 03:45 UTC by LinYunMo

Re: https://github.com/cocos-creator/3d-tasks/issues/4054
Re: https://github.com/cocos-creator/3d-tasks/issues/3560

2020-08-12 08:47 UTC, YunHsiao commented on cocos/core/components/ui-base/ui-render-component.ts
> +    }
这俩如果和基类声明的没啥区别的话就不用重载了

2020-08-12 08:47 UTC, YunHsiao commented on cocos/ui/components/ui-static-batch-component.ts
> +        return super.sharedMaterials;
这个也是

2020-08-13 02:18 UTC, LinYunMo commented on cocos/ui/components/ui-static-batch-component.ts
> +        return super.sharedMaterials;
这个是有个修饰器的可见性不同，所以做了个重载

2020-08-13 02:18 UTC, LinYunMo commented on cocos/core/components/ui-base/ui-render-component.ts
> +    }
已移除

2020-08-13 03:57 UTC, YunHsiao approved these changes

2020-08-13 09:22 UTC, caryliu1999 commented on cocos/core/components/ui-base/ui-render-component.ts
> +    }
这个为什么不存在 shareMaterial 里面要单独缓存在这里呢？直接放在 shareMaterial ，然后再从里面取，这样的话不是跟其他组件统一一些吗？

2020-08-13 09:38 UTC, caryliu1999 commented on cocos/core/components/ui-base/ui-render-component.ts
>      }
这里的更新应该是先确认好最终使用的 mat，然后再去对目标材质设置一次 blend 的就可以了，最后直接返回 mat，不需要中间那么多的判定

2020-08-13 09:40 UTC, caryliu1999 commented on cocos/core/renderer/ui/ui.ts
> +        }
如果 mat 存在的情况下不需要更新 blendFunc 吗？前面的 mat 赋值就不需要了吧

2020-08-13 09:44 UTC, caryliu1999 commented on cocos/ui/components/graphics-component.ts
> +        this._uiMaterialIns = mat;
这里先设置好 uiMaterial，再通过 uiMaterial 去生成材质实例吧

2020-08-13 10:38 UTC, LinYunMo commented on cocos/core/components/ui-base/ui-render-component.ts
> +    }
不能放在 sharedMaterials 里，这个值不希望被缓存，是一个为默认内置材质准备的运行时的值，而且算是专为 UI 做的缓存，所以不放在基类中去。

2020-08-14 07:00 UTC, LinYunMo commented on cocos/core/renderer/ui/ui.ts
> +        }
这段操作是为默认材质准备的，mat 存在的情况下说明用户自定义了材质，这时 blendFunc 在设置时就会试例化并存到 _materialInstances 中，不需要这个时候更新

2020-08-14 07:00 UTC, LinYunMo commented on cocos/core/renderer/ui/ui.ts
> +        }
这段操作是为默认材质准备的，mat 存在的情况下说明用户自定义了材质，这时 blendFunc 在设置时就会试例化并存到 _materialInstances 中，不需要这个时候更新

2020-08-14 07:13 UTC, LinYunMo commented on cocos/ui/components/graphics-component.ts
> +        this._uiMaterialIns = mat;
设置好 uiMaterial 再实例化会需要多一个分支或者多一个内置的材质类型，不太合适

2020-08-14 07:17 UTC, LinYunMo commented on cocos/core/components/ui-base/ui-render-component.ts
>      }
对，是的，这样是最理想的情况，我这个纠结的处理是为了尽量避免实例化（尽量保证合批）所以才做了一堆的判定，现在这个函数返回的根据条件不同会是材质资源的引用或者是实例化过后的材质，这样能够尽量保证合批。

这里，包括这个PR的很多地方其实是为了保证UI现在有的内置材质提供的功能做出的妥协（叹气）

2020-08-14 07:30 UTC, caryliu1999 commented on cocos/ui/components/graphics-component.ts
> +        this._uiMaterialIns = mat;
> 设置好 uiMaterial 再实例化会需要多一个分支或者多一个内置的材质类型，不太合适

helpInstanceMaterial 这个方法是在 OnEnable 的时候调用的，OnEnable 和 OnDisable 在节点隐藏显示的情况下应该会反复执行的，这里的材质还需要重复创建吗？

2020-08-14 07:35 UTC, caryliu1999 commented on cocos/core/components/ui-base/ui-render-component.ts
> +    }
> 默认内置材质

为什么不能存？用户没有自定义就是使用默认的材质放在 sharedMaterial 里面，这样后面用的时候直接取 sharedMaterial 就好了，不然还得再去判断是用 sharedMaterial 还是 uiMaterial

2020-08-14 07:39 UTC, LinYunMo commented on cocos/core/components/ui-base/ui-render-component.ts
> +    }
我们的内置材质是通过 builtinResMgr 存在引擎中的，在编辑器中没有对应的资源文件，参与序列化的话会在加载时无法找到资源

2020-08-14 07:43 UTC, LinYunMo commented on cocos/ui/components/graphics-component.ts
> +        this._uiMaterialIns = mat;
不用重复创建，是内置材质需要一个材质试例才能够 recompileShaders ，我们没有 USE_LOCAL 开启的内置材质，除非我在添加一个 USE_LOCAL 开启的材质才可以。

2020-08-14 08:18 UTC, LinYunMo commented on cocos/ui/components/graphics-component.ts
> +        this._uiMaterialIns = mat;
确实不需要，我更新了，不会重复创建了

2020-08-14 08:23 UTC, caryliu1999 approved these changes

2020-08-16 15:14 UTC, pandamicro requested changes

2020-08-16 15:14 UTC, pandamicro commented on cocos/core/components/ui-base/ui-render-component.ts
> +    public getUIMaterialIns () {
public 函数不符合目前的命名规范，尽量精简但不要用不成习惯的缩写

getRenderMaterial
getMaterialInstance

2020-08-16 15:14 UTC, pandamicro commented on cocos/core/components/ui-base/ui-render-component.ts
> +    get UIMaterial () {
uiMaterial

2020-08-16 15:14 UTC, pandamicro commented on cocos/core/components/ui-base/ui-render-component.ts
> +export class UIRenderComponent extends RenderableComponent {
改变继承关系的影响挺大的，比如后续的 uiComp 赋值就不能使用这个类了

2020-08-16 15:14 UTC, pandamicro commented on cocos/core/components/ui-base/ui-render-component.ts
> +        this.node._uiProps.uiComp = this;
参考前面的评论，这个类已经不是 uiComp 了，不满足需求

2020-08-17 02:44 UTC, LinYunMo commented on cocos/core/components/ui-base/ui-render-component.ts
> +export class UIRenderComponent extends RenderableComponent {
uiComp 保存的和使用的实际上就是 ui-render-component ，这里是不会有问题的，唯一的问题就是需要改一下 uiComp 的类型（之前改过了）

2020-08-17 02:44 UTC, LinYunMo commented on cocos/core/components/ui-base/ui-render-component.ts
> +        this.node._uiProps.uiComp = this;
同上

2020-08-17 03:08 UTC, LinYunMo commented on cocos/core/components/ui-base/ui-render-component.ts
> +    public getUIMaterialIns () {
已修改

2020-08-17 03:08 UTC, LinYunMo commented on cocos/core/components/ui-base/ui-render-component.ts
> +    get UIMaterial () {
已修改

2020-08-17 08:29 UTC, pandamicro approved these changes

2020-08-17 08:30 UTC, merged