throw error in promise on Native platform
cocos/cocos-engine pull request #7127
Opened 2020-08-12 09:24 UTC by PPpro

changeLog:
- 修复原生平台 async 函数里没有抛出异常的问题

2020-08-13 02:26 UTC, SantyWang approved these changes

2020-08-13 02:36 UTC, SantyWang approved these changes

2020-08-13 02:58 UTC, jareguo requested changes
还需要更多测试

2020-08-18 07:53 UTC, PPpro commented
在 pr 里
https://github.com/cocos-creator/cocos2d-x-lite/pull/2691
https://github.com/cocos-creator-packages/jsb-adapter/pull/328
解决

2020-08-18 07:53 UTC, closed without merging

2021-08-11 07:01 UTC, joewan commented
目前async函数出现异常，能上传bugly了么。