sync #6825
cocos/cocos-engine pull request #7171
Opened 2020-08-19 01:49 UTC by Jno1995

Re:  https://github.com/cocos-creator/engine/pull/6825、
https://github.com/cocos-creator/3d-tasks/issues/3983

2020-08-27 02:55 UTC, pandamicro commented
确定一下目前 widget 的控制机制是不是和 2d 不同，这样修改是否会造成问题
@LinYunMo @JoneLau

2020-09-03 06:19 UTC, LinYunMo requested changes

2020-09-03 06:19 UTC, LinYunMo commented on cocos/ui/components/widget-manager.ts
> +            widgetManager.add(widget);
enable = false 怎么还是在 add ？

2020-09-03 06:19 UTC, LinYunMo commented on cocos/ui/components/widget-manager.ts
> +            this.add(widget);
3d 的 enable 操作不只是 add 这一步，还有 事件注册，这么改事件就没有注册了

2020-09-03 06:33 UTC, Jno1995 commented
如果把原来 onEnable 里面的事件注册放到 onStart 里面去，会不会有问题？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ChiaNing"<notifications@github.com&gt;; 
发送时间: 2020年9月3日(星期四) 下午2:19
收件人: "cocos-creator/engine"<engine@noreply.github.com&gt;; 
抄送: "张哲锋"<337031709@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [cocos-creator/engine] sync #6825 (#7171)





 
@LinYunMo requested changes on this pull request.
 
 
In cocos/ui/components/widget-manager.ts:
 &gt; @@ -212,7 +212,7 @@ function visitNode (node: any) {          align(node, widget);          // @ts-ignore          if ((!EDITOR || widgetManager.animationState!.animatedSinceLastFrame) &amp;&amp; widget.alignMode !== AlignMode.ALWAYS) { -            widget.enabled = false; +            widgetManager.add(widget);  
enable = false 怎么还是在 add ？
 
 
In cocos/ui/components/widget-manager.ts:
 &gt; @@ -390,11 +390,9 @@ export const widgetManager = legacyCC._widgetManager = {          }      },      refreshWidgetOnResized (node: Node) { -        if (Node.isNode(node)) { -            const widget = node.getComponent(WidgetComponent); -            if (widget &amp;&amp; widget.alignMode === AlignMode.ON_WINDOW_RESIZE) { -                widget.enabled = true; -            } +        const widget = Node.isNode(node) &amp;&amp; node.getComponent(WidgetComponent); +        if (widget &amp;&amp; widget.enabled &amp;&amp; widget.alignMode === AlignMode.ON_WINDOW_RESIZE){ +            this.add(widget);  
3d 的 enable 操作不只是 add 这一步，还有 事件注册，这么改事件就没有注册了
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2020-09-08 06:21 UTC, pandamicro commented
这个 PR 不能简单同步，请 @Jno1995 和 @LinYunMo 讨论后再确定，先关闭 PR

2020-09-08 06:21 UTC, closed without merging

2020-09-27 10:48 UTC, zhefengzhang commented
测试 Creator 3D 1.2.0 没有 CocosCreator 2D 版本的问题。

该 pr 不用同步到 Creator 3D。

2020-09-28 10:09 UTC, zhefengzhang commented on cocos/ui/components/widget-manager.ts
> +            this.add(widget);
enabled 为 false 的时候，就不需要注册了。