Repair shadow matrix for 3d-v1.2
cocos/cocos-engine pull request #7223
Opened 2020-08-26 04:11 UTC by troublemaker52025

Re: cocos-creator/2d-tasks#

Changes:
 *

2020-08-26 06:14 UTC, 2youyou2 commented on cocos/core/renderer/scene/shadows.ts
> +        Vec3.multiplyScalar(_vec3_p, _dir_negate, Math.sqrt(2) * this._sphere.radius);
`Math.sqrt(2)` 可以提取出来预先计算

2020-08-26 06:18 UTC, troublemaker52025 commented on cocos/core/pipeline/forward/scene-culling.ts
> +                        sphere.mergeBox(shadowSphere, shadowSphere, model.worldBounds!);
这里使用sphere，是因为球的中心不管从哪往中心点观察，都能窥视到半球
aabb的长方体中心，计算就不那么准确

2020-08-26 06:23 UTC, troublemaker52025 commented on cocos/core/renderer/scene/shadows.ts
> +        Vec3.multiplyScalar(_vec3_p, _dir_negate, Math.sqrt(2) * this._sphere.radius);
可以提出来，我也写明了含义

2020-08-26 15:54 UTC, pandamicro requested changes

2020-08-26 15:54 UTC, pandamicro commented on cocos/core/renderer/scene/shadows.ts
> +    public _sphere: sphere = new sphere(0.0, 0.0, 0.0, 0.01);
private _sphere

然后添加一个 getSphere 或别的

2020-08-26 15:54 UTC, pandamicro commented on editor/assets/chunks/cc-shadow-map-fs.chunk
> +vec4 CCGetShadowFactorCommon () {
Easy Common Hard 命名不够清晰，另外，你使用的是十字采样，不是 pcf 标准的 NxN 采样，我也不确定该怎么命名比较好

2020-08-26 15:54 UTC, pandamicro commented on cocos/core/renderer/scene/shadows.ts
> +    X1: 2,
X1，X4 这个最好也跟 shader 中的命名统一

2020-08-26 15:54 UTC, pandamicro commented on cocos/core/geometry/sphere.ts
> +    public static mergeBox (out: sphere, s:sphere, a: aabb) {
static 应该放在 public 函数之前。

这个函数也应该是 mergeAABB

2020-08-27 03:17 UTC, troublemaker52025 commented on editor/assets/chunks/cc-shadow-map-fs.chunk
> +vec4 CCGetShadowFactorCommon () {
查了一下根据显卡的性能而定  2x2倍采样确实是X型采样，3x3倍采样时九宫格，最后是5x5倍采样，我看到的文章基本上到5x5就截止了
https://zhuanlan.zhihu.com/p/61460686  --X型采样
https://zhuanlan.zhihu.com/p/26853641  --PCF滤波
shader命名的话  结尾加上NxN吧   比较容易理解

2020-08-27 11:48 UTC, pandamicro approved these changes

2020-08-28 02:42 UTC, 2youyou2 commented on editor/assets/chunks/shading-standard.chunk
> +      if (2.0 > pcf && pcf > 1.0) {shadow = CCGetShadowFactorX5();}
这应该是 else if 吧

2020-08-28 03:10 UTC, caryliu1999 approved these changes

2020-08-28 03:11 UTC, troublemaker52025 commented on editor/assets/chunks/shading-standard.chunk
> +      if (2.0 > pcf && pcf > 1.0) {shadow = CCGetShadowFactorX5();}
之前有语法错误  所以分开写了   现在纠正了语法错误，改成if else的分支判断了

2020-08-28 03:12 UTC, 2youyou2 approved these changes

2020-08-28 03:14 UTC, merged