fix sharedCanvas
cocos/cocos-engine pull request #7405
Opened 2020-09-17 10:57 UTC by PPpro

Re: https://github.com/cocos-creator/3d-tasks/issues/4529

Changes:
 * 修复sharedCanvas 类型判断

目前还不能解决子域显示问题，字节不能支持 subTexImage2D 接口，需要 @LinYunMo 帮忙看看
<img width="683" alt="WX20200917-185645@2x" src="https://user-images.githubusercontent.com/17872773/93461592-8dfdb580-f917-11ea-8c5d-963e333a1657.png">

2020-09-17 12:50 UTC, LinYunMo requested changes

2020-09-17 12:50 UTC, LinYunMo commented on cocos/core/assets/image-asset.ts
> +        else if (window.sharedCanvas && this._nativeData instanceof window.sharedCanvas.constructor) {
能用宏吗？编译会被剔除，也好知道这是个特殊的处理

2020-09-18 02:14 UTC, PPpro commented on cocos/core/assets/image-asset.ts
> +        else if (window.sharedCanvas && this._nativeData instanceof window.sharedCanvas.constructor) {
已更新

2020-09-18 02:30 UTC, LinYunMo approved these changes

2020-09-18 02:33 UTC, LinYunMo reviewed
Wait test result

2020-09-18 06:13 UTC, PPpro commented
测试通过

2020-09-18 06:14 UTC, merged