init main light info
cocos/cocos-engine pull request #7427
Opened 2020-09-21 06:17 UTC by YunHsiao

Re: cocos-creator/3d-tasks#

Changelog:
 *

2020-09-21 07:09 UTC, pandamicro requested changes

2020-09-21 07:09 UTC, pandamicro commented on cocos/core/renderer/scene/directional-light.ts
> +        this.direction = this._dir;
This is not a good idea, if one day someone decide to do parameter check in direction setter, then the initialize process will be broken unintentionally.

Please explicitly set the LightView direction in pool

2020-09-21 07:09 UTC, pandamicro commented on cocos/core/renderer/scene/light.ts
> +        this.colorTemperature = this._colorTemp;
Same argument as previous

2020-09-22 02:11 UTC, minggo approved these changes

2020-09-22 08:24 UTC, pandamicro approved these changes

2020-09-22 08:27 UTC, merged