add terrain shadow
cocos/cocos-engine pull request #7500
Opened 2020-10-11 06:33 UTC by troublemaker52025

Re: cocos-creator/2d-tasks#

Changes:
 *

2020-10-12 01:12 UTC, YunHsiao commented on editor/assets/effects/builtin-terrain.effect
> +      propertyIndex: 1
这个指的是要和几号 pass 的属性保持一致，对这个 effect 来说应该是 0

2020-10-12 01:12 UTC, YunHsiao commented on editor/assets/effects/builtin-toon.effect
> +        cullMode: back
这是为啥？

2020-10-12 07:11 UTC, pandamicro commented on editor/assets/effects/builtin-terrain.effect
> +    float NL = 1.0;//0.5 * dot(N, L) + 0.5;
这里的修改我无法接受，如果要这样表现才正确说明你这个 PR 是不完善的

2020-10-12 07:14 UTC, troublemaker52025 commented on editor/assets/effects/builtin-terrain.effect
> +    float NL = 1.0;//0.5 * dot(N, L) + 0.5;
跟思忠沟通后，他将地形的effect  按照默认的光照材质编写，并添加了光照。后续我才能接着思忠的pr https://github.com/cocos-creator/engine/pull/7505  添加并测试地形阴影

2020-10-12 07:14 UTC, pandamicro commented on editor/assets/effects/builtin-terrain.effect
> +    float NL = 1.0;//0.5 * dot(N, L) + 0.5;
思忠的 PR 已合并

2020-10-12 07:15 UTC, troublemaker52025 commented on editor/assets/effects/builtin-terrain.effect
> +    float NL = 1.0;//0.5 * dot(N, L) + 0.5;
那接下来该我改掉这部分临时方案了

2020-10-12 07:18 UTC, troublemaker52025 commented on editor/assets/effects/builtin-toon.effect
> +        cullMode: back
今天早上测试了一下，在默认光照材质下，cullModel:back 显示没有异常，但是使用front后  在很接近的地方产生阴影会有bug，但是在toon.effect下 却只能使用front。这个地方确实应该使用front

2020-10-12 09:21 UTC, troublemaker52025 commented on editor/assets/effects/builtin-terrain.effect
> +      propertyIndex: 1
思忠在这里添加了forward-add ，现在的标志位是1了，之前确实写错了

2020-10-13 03:42 UTC, YunHsiao commented on editor/assets/effects/builtin-terrain.effect
> +      propertyIndex: 1
shadow 也是应该和 0 号对齐吧，最好不要这样链表式引用

2020-10-13 03:48 UTC, troublemaker52025 commented on editor/assets/effects/builtin-terrain.effect
> +      propertyIndex: 1
这个链表式引用  是说properties: *props的写法么？

2020-10-13 03:53 UTC, YunHsiao commented on editor/assets/effects/builtin-terrain.effect
> +      propertyIndex: 1
不是，是 0 -> 1 -> 2 这种，后两个 pass 都引用 0 就行了

2020-10-13 03:55 UTC, troublemaker52025 commented on editor/assets/effects/builtin-terrain.effect
> +      propertyIndex: 1
还是有一点不太明白  为什么builtin-toon.effect中  propertyIndex: 1都是从1开始的，而不是从0开始呢

2020-10-13 04:01 UTC, YunHsiao commented on editor/assets/effects/builtin-terrain.effect
> +      propertyIndex: 1
因为 toon 的 pass 0 是描边，光照 pass 应该和 shading pass 一致

2020-10-13 09:43 UTC, pandamicro requested changes

2020-10-13 09:43 UTC, pandamicro commented on cocos/terrain/terrain.ts
> +                    Vec3.copy(bbMax, position);
别这么做，min 的初始值都使用 Number.MAX_VALUE，max 的初始值都使用 Number.MIN_VALUE

2020-10-13 09:43 UTC, pandamicro commented on cocos/core/renderer/scene/shadows.ts
> +    protected _sphere: sphere = new sphere(0.0, 0.0, 0.0, -0.01);
这有什么意义？

2020-10-13 09:43 UTC, pandamicro commented on cocos/terrain/terrain.ts
> +            USE_LIGHTMAP: this.lightmap !== null ? 1 : 0,
确认一下到底哪个 key 才是正确的，之前用的是 LIGHT_MAP，现在是 USE_LIGHTMAP

2020-10-13 09:46 UTC, troublemaker52025 commented on cocos/core/renderer/scene/shadows.ts
> +    protected _sphere: sphere = new sphere(0.0, 0.0, 0.0, -0.01);
最后一个参数是半径，改成负值的话，在计算包围球的时候  可以将包围球初始值设置到该位置。这应该是上一个pr的优化，不应该出现在这里

2020-10-14 10:37 UTC, MSoft1115 commented on cocos/terrain/terrain.ts
> +            USE_LIGHTMAP: this.lightmap !== null ? 1 : 0,
和standard统一了

2020-10-14 10:38 UTC, MSoft1115 commented on cocos/terrain/terrain.ts
> +            USE_LIGHTMAP: this.lightmap !== null ? 1 : 0,
> 确认一下到底哪个 key 才是正确的，之前用的是 LIGHT_MAP，现在是 USE_LIGHTMAP

和standard shader统一使用一样的宏

2020-10-14 10:39 UTC, MSoft1115 approved these changes

2020-10-14 15:09 UTC, pandamicro commented on cocos/terrain/terrain.ts
> +                    Vec3.copy(bbMax, position);
因为 前面已经初始化为 Max 和 min 了，所以直接走下面的 Vec3.min 和 Vec3.max 就可以了，不需要对 0 位做初始化了

2020-10-14 15:09 UTC, pandamicro commented on cocos/terrain/terrain.ts
> +                    Vec3.copy(bbMax, position);
同上

2020-10-15 08:48 UTC, pandamicro approved these changes

2020-10-15 08:48 UTC, merged