update _deltaTime calculate for editor
cocos/cocos-engine pull request #7503
Opened 2020-10-12 03:11 UTC by knoxHuang

Re: cocos-creator/2d-tasks#

Changes:
 * update _deltaTime calculate for editor

2020-10-12 03:13 UTC, gameall3d approved these changes
LGTM

2020-10-12 07:17 UTC, pandamicro requested changes

2020-10-12 07:17 UTC, pandamicro commented on cocos/core/director.ts
> +                this._deltaTime = time;
万一调用的时候没传不就坑了，确保 time 不正确的时候使用一个默认值，比如 1000/60

2020-10-12 07:24 UTC, knoxHuang commented on cocos/core/director.ts
> +                this._deltaTime = time;
不太可能不传吧，默认是必须要传的，
 public mainLoop (time: number)，如果是定义 public mainLoop (time?: number) 才需要确保默认值

2020-10-13 11:09 UTC, pandamicro approved these changes

2020-10-13 11:09 UTC, merged