fix sphere.margeAABB bug && Optimize automatic shadow calculation
cocos/cocos-engine pull request #7518
Opened 2020-10-13 08:41 UTC by troublemaker52025

Re: cocos-creator/2d-tasks#

Changes:
 *

2020-10-13 09:59 UTC, pandamicro requested changes

2020-10-13 09:59 UTC, pandamicro commented on cocos/core/geometry/sphere.ts
> +            out.center = point.clone();
out 本身就是一个 sphere，center 属性就是一个 Vec3 了，你这样做相当于创建了一个新的 vec3 对象然后替换原来的，是浪费内存

2020-10-13 10:02 UTC, troublemaker52025 commented on cocos/core/geometry/sphere.ts
> +            out.center = point.clone();
如果不是有新的Vec3去替换原来的，那么所有使用到这个方法的out.center 都将通过引用的方式被改变。假如使用单线程使用5次该函数  那么其他4次中的out.center都被错误的更改（原因：out.center = point;是引用赋值，要使用值传递）

2020-10-14 01:54 UTC, minggo commented on cocos/core/pipeline/forward/forward-pipeline.ts
> +                far = shadowInfo.receiveSphere.radius * 2.0;
需要同步到原生

2020-10-14 01:55 UTC, troublemaker52025 commented on cocos/core/pipeline/forward/forward-pipeline.ts
> +                far = shadowInfo.receiveSphere.radius * 2.0;
收到

2020-10-14 01:56 UTC, minggo commented
pipeline 的修改都需要同步到原生。

2020-10-14 01:58 UTC, troublemaker52025 commented
> 
> 
> pipeline 的修改都需要同步到原生。

那数学库里添加的方法呢，还有数学库里方法的修改

2020-10-14 02:00 UTC, minggo commented
原生也有对应到数学库，如果没有到话，就自己写一个。

2020-10-14 02:00 UTC, troublemaker52025 commented
> 
> 
> 原生也有对应到数学库，如果没有到话，就自己写一个。

好的

2020-10-14 02:38 UTC, pandamicro commented on cocos/core/geometry/aabb.ts
> +    public static toSphere (out: sphere, a: aabb) {
改成 toBoundingSphere 更好一些

2020-10-14 02:38 UTC, pandamicro commented on cocos/core/pipeline/forward/scene-culling.ts
> +    let receiveWorldBounds: aabb|null = null;
将定义提前为全局复用变量，也不需要设置为 null，使用标记会更方便。这里只设置初始化标记为 false

```
let _castWorldBounds = new aabb();
let _receiveWorldBounds = new aabb();
let _boundsInited = false;

function sceneCulling (pipeline: ForwardPipeline, view: RenderView) {
    _boundsInited = false;
    ....
    if (model.castShadow && model.worldBounds) {
        if (!_boundsInited) {  _castWorldBounds.copy(model.worldBounds); }
    ....
    if (model.receiveShadow && model.worldBounds) {
       if (!_boundsInited) { _receiveWorldBounds.copy(model.worldBounds); }
    ....
    if  (!_boundsInited) { _boundsInited = true; }
}
```

2020-10-14 02:38 UTC, pandamicro commented on cocos/core/pipeline/forward/scene-culling.ts
> +    let receiveWorldBounds: aabb|null = null;
这个修改你看下，如果赞同就改，如果觉得目前实现更好也可以

2020-10-14 02:42 UTC, troublemaker52025 commented on cocos/core/pipeline/forward/scene-culling.ts
> +    let receiveWorldBounds: aabb|null = null;
我觉得应该改，每次的scene culling都能避免重复创建aabb

2020-10-14 03:02 UTC, troublemaker52025 commented on cocos/core/pipeline/forward/scene-culling.ts
> +let _receiveBoundsInited = false;
添加两个标志位是因为：一个模型可以接收阴影，但不一定产生阴影。在单线程中顺序执行   一个标志位没办法满足两个bounding box的初始化工作，故添加两个标志位分开判断是否初始化完成。

2020-10-14 03:19 UTC, pandamicro approved these changes

2020-10-14 03:20 UTC, merged