refactor collision matrix
cocos/cocos-engine pull request #7538
Opened 2020-10-15 10:43 UTC by JayceLai

Re: cocos-creator/3d-tasks#4674

Changes:
 * refactor collision matrix

2020-10-16 05:53 UTC, pandamicro commented
I think it should be merged in 3.0, or do you have a good reason ?

2020-10-16 06:01 UTC, JayceLai commented
> I think it should be merged in 3.0, or do you have a good reason ?

ok

2020-10-16 06:05 UTC, JayceLai commented
Waiting for rebase to be done

2020-10-27 11:15 UTC, 2youyou2 approved these changes

2020-10-28 05:59 UTC, pandamicro requested changes

2020-10-28 05:59 UTC, pandamicro commented on cocos/physics/framework/deprecated.ts
> +        "name": "setCollisionGroup"
We can't remove these public APIs directly, please do a deprecation with the same functionality instead.

2020-10-28 06:15 UTC, pandamicro approved these changes

2020-10-28 06:15 UTC, merged