change 2d ui component vec3 to vec2  and fix scrollview default template
cocos/cocos-engine pull request #7593
Opened 2020-10-23 09:21 UTC by yeshao2069

1 change 2d ui component public interface vec3 to vec2
2 fix scrollview default template

2020-10-24 03:49 UTC, LinYunMo requested changes

2020-10-24 03:49 UTC, LinYunMo commented on cocos/ui/components/scroll-bar.ts
> +    public onScroll (outOfBoundary: Vec2) {
公开接口改参数类型要用弃用来写

2020-10-24 03:49 UTC, LinYunMo commented on cocos/ui/components/scroll-view.ts
> +    public scrollToOffset (offset: Vec2, timeInSecond?: number, attenuated = true) {
请添加弃用及兼容性警告

2020-10-24 03:49 UTC, LinYunMo commented on cocos/ui/components/scroll-view.ts
> +        return new Vec2(horizontalMaximizeOffset, verticalMaximizeOffset);
同样，要添加兼容

2020-10-24 03:49 UTC, LinYunMo commented on cocos/ui/components/scroll-view.ts
> +    protected _setContentPosition (position: Vec3) {
这个函数移除公开的理由是？

2020-10-24 03:49 UTC, LinYunMo commented on cocos/ui/components/scroll-view.ts
> +    protected _getContentPosition () {
同上

2020-10-24 03:49 UTC, LinYunMo commented on cocos/ui/components/scroll-view.ts
> +            this._horizontalScrollBar.onScroll(new Vec2(outOfBoundary.x, outOfBoundary.y));
这是只改了部分，不需要 Vec3 的话这个函数传进来的参数为何是Vec3 ？

2020-10-24 03:49 UTC, LinYunMo commented on editor/assets/default_prefab/ui/ScrollView.prefab
> +      "y": -31.25,
请尽量做到一个 PR 解决一个问题，这个看起来与上面那个并不是一个问题来着，之后稍微注意一下

2020-10-28 12:01 UTC, yeshao2069 commented
重启一个PR

2020-10-28 12:01 UTC, closed without merging