add image stencil in mask
cocos/cocos-engine pull request #7598
Opened 2020-10-26 11:36 UTC by JoneLau

Re: https://github.com/cocos-creator/3d-tasks/issues/3647

depend on: https://github.com/cocos-creator/editor-3d/pull/4401

2020-10-27 04:07 UTC, pandamicro requested changes

2020-10-27 04:07 UTC, pandamicro commented on cocos/core/components/ui-base/ui-renderable.ts
> -                    this._uiMaterial = builtinResMgr.get('ui-sprite-material') as Material;
为什么去除这个类型？

2020-10-27 04:07 UTC, pandamicro commented on cocos/core/renderer/ui/stencil-manager.ts
> -        passOp: GFXStencilOp.KEEP,
不用省这两个属性把

2020-10-27 04:07 UTC, pandamicro commented on cocos/core/renderer/ui/stencil-manager.ts
> +    public applyStencil(material: Material, test: boolean, func: GFXComparisonFunc, failOp: GFXStencilOp, ref: number, stencilMask: number, writeMask: number) {
参数太多了，接受 state 就好了呀
applyStencil(material: Material, state: any)

2020-10-27 04:07 UTC, pandamicro commented on cocos/core/renderer/ui/ui.ts
> +                rebuild = true;
不需要增加 rebuild = true，前面的判断保障了它就是 true

2020-10-27 04:07 UTC, pandamicro commented on cocos/core/renderer/ui/ui.ts
> +     * Forced to flush material.
Force to change the current material

2020-10-27 04:07 UTC, pandamicro commented on cocos/ui/components/mask.ts
> +            this._attachToScene();
如果是从 graphics 切换到 spriteFrame，理论上应该不需要重新 attachToScene

2020-10-27 04:07 UTC, pandamicro commented on cocos/ui/components/mask.ts
> +            this._detachFromScene();
同样的，如果类型不是 Image stencil，不应该做这个处理

2020-10-27 04:07 UTC, pandamicro commented on cocos/ui/components/mask.ts
> +            this._detachFromScene();
spriteFrame 的设置应该不受类型限制，但是 attach 与否是受 stencil 类型限制的，可能可以加一个 _attached 标记

2020-10-27 04:07 UTC, pandamicro commented on cocos/ui/components/mask.ts
> +
无用修改

2020-10-27 04:07 UTC, pandamicro commented on cocos/ui/components/mask.ts
> +    set sharedMaterials (val) {
为什么要重写这个属性？

2020-10-27 04:07 UTC, pandamicro commented on cocos/ui/components/mask.ts
> +    }
去掉无意义的空行

2020-10-27 04:07 UTC, pandamicro commented on cocos/ui/components/mask.ts
> +        // }
不要保留无意义的注释

2020-10-27 04:07 UTC, pandamicro commented on cocos/ui/components/mask.ts
> +        return this._graphics !== null;
如果是 ImageStencil 应该判断 spriteFrame 把

2020-10-27 04:07 UTC, pandamicro commented on cocos/ui/components/mask.ts
> +        if (!this._clearModel) {
这个 if 中的逻辑最好放在一个 _createClearModel 函数中

2020-10-27 04:07 UTC, pandamicro commented on cocos/core/3d/builtin/init.ts
> +        maskNormalAlphaMtl._uuid = 'ui-alpha-material';
alphaTestMaskMtl
ui-alpha-test-material

2020-10-27 04:07 UTC, pandamicro commented on cocos/ui/components/mask.ts
> +    protected _attachToScene () {
应该改为 _attatchClearModel

2020-10-27 04:07 UTC, pandamicro commented on cocos/ui/components/mask.ts
> +    protected _detachFromScene (){
_detachClearModel

2020-10-27 05:38 UTC, JoneLau commented on cocos/core/components/ui-base/ui-renderable.ts
> -                    this._uiMaterial = builtinResMgr.get('ui-sprite-material') as Material;
因为 default 就是这个材质，没有特殊就不需要增加这么一个判定吧

2020-10-27 05:40 UTC, JoneLau commented on cocos/core/renderer/ui/stencil-manager.ts
> -        passOp: GFXStencilOp.KEEP,
这两个参数是固定的，直接在应用的时候写死就好了

2020-10-27 05:41 UTC, JoneLau commented on cocos/core/renderer/ui/ui.ts
> +                rebuild = true;
这个是合并的时候带来的，改动的只有 applyStencil 那一栏，我这里去掉一下

2020-10-27 06:37 UTC, pandamicro commented on cocos/core/components/ui-base/ui-renderable.ts
> -                    this._uiMaterial = builtinResMgr.get('ui-sprite-material') as Material;
那如果是从 ui-sprite-gray-material 切换回 ui-sprite-material 的情况呢，不就无法切换了

2020-10-27 06:37 UTC, pandamicro commented on cocos/core/renderer/ui/stencil-manager.ts
> -        passOp: GFXStencilOp.KEEP,
看不出必要性啊，一个是初始化好的，一个是每次函数中都要额外声明，没有更好啊

2020-10-27 08:23 UTC, pandamicro commented on cocos/ui/components/mask.ts
> +        if (!this._spriteFrame && value) {
需要在外部包一个判断，type 是否是 IMAGE_STENCIL，如果不是，不应该去处理 clear model

2020-10-28 04:13 UTC, pandamicro approved these changes

2020-10-28 04:13 UTC, merged