new UI custom material & use hash check merge
cocos/cocos-engine pull request #7649
Opened 2020-10-30 13:43 UTC by LinYunMo

Re: https://github.com/cocos-creator/3d-tasks/issues/3799
Re: https://github.com/cocos-creator/3d-tasks/issues/4054

2020-10-30 13:49 UTC, LinYunMo commented
编辑器关联数据迁移： https://github.com/cocos-creator/editor-3d/pull/4463

2020-10-31 03:37 UTC, pandamicro requested changes
👍  现在的 custom material 逻辑要比之前好很多，但是我不理解 hash 更新机制

2020-10-31 03:37 UTC, pandamicro commented on EngineErrorMap.md
> +Not support set/get BlendFactor when use customMaterial, please change it by material.
BlendFactors are disabled when using custom material, please modify the blend state in the material instead

2020-10-31 03:37 UTC, pandamicro commented on cocos/core/components/ui-base/ui-renderable.ts
> +    @displayName('CustomMaterials')
CustomMaterial

2020-10-31 03:37 UTC, pandamicro commented on cocos/core/components/ui-base/ui-renderable.ts
> +    protected updateMaterialByBuiltIn () {
应该使用 updateMaterial 更准确

2020-10-31 03:37 UTC, pandamicro commented on cocos/core/components/ui-base/ui-renderable.ts
> +    private _updateBuiltinMaterial () : Material {
更新到使用 builtin material 的时候还需要检查 blend function 是否是定制的，如果不等于默认值，需要更新

2020-10-31 03:37 UTC, pandamicro commented on cocos/core/components/ui-base/ui-renderable.ts
> +    public updateUIMaterialHash (mat: Material) {
为什么需要手动更新 hash，不能直接取 material 的 hash 吗？

2020-10-31 03:37 UTC, pandamicro commented on cocos/ui/components/graphics.ts
> +    set dstBlendFactor (value) {
为什么不允许修改？和 2.x 行为一致吗？

2020-10-31 03:37 UTC, pandamicro commented on cocos/ui/components/graphics.ts
> +    private updateMtlForGraphics () {
private 函数加下划线

2020-10-31 03:37 UTC, pandamicro commented on cocos/ui/components/mask.ts
> +        if (this.type !== MaskType.IMAGE_STENCIL || this._alphaThreshold === value) {
即便不是 image stencil，设置属性还是可以设置的，只是不执行材质更新

2020-10-31 04:47 UTC, LinYunMo commented on cocos/core/components/ui-base/ui-renderable.ts
> +    private _updateBuiltinMaterial () : Material {
更新过后有进行 blend function 的更新，在这个函数中执行完材质切换之后

2020-10-31 04:50 UTC, LinYunMo commented on cocos/ui/components/graphics.ts
> +    set dstBlendFactor (value) {
与 2.x 行为一致

2020-10-31 05:32 UTC, pandamicro approved these changes

2020-10-31 05:34 UTC, merged