fix ui transform setContentSize
cocos/cocos-engine pull request #7686
Opened 2020-11-03 13:12 UTC by yeshao2069

fix ui transform setContentSize， when setContentSize(a), it will get a undefined width and height

2020-11-04 02:15 UTC, yeshao2069 commented
@JoneLau   不知道找谁reviewer

2020-11-04 14:08 UTC, pandamicro requested changes

2020-11-04 14:08 UTC, pandamicro commented on cocos/core/components/ui-base/ui-transform.ts
> +     * @param size - 节点内容变换的尺寸。
参数注释使用英文

2020-11-04 14:08 UTC, pandamicro commented on cocos/core/components/ui-base/ui-transform.ts
> +     * All nodes have a size. Layer and Scene have the same size of the screen.
Remove this line, remove the same line in the previous API too

2020-11-04 14:08 UTC, pandamicro commented on cocos/core/scene-graph/deprecated.ts
> +            if(typeof size === 'number' || size instanceof Number){
不需要重复的判断，用 typeof 就可以了。
注意 if 括号两侧的空格

2020-11-05 02:51 UTC, JoneLau requested changes

2020-11-05 02:51 UTC, JoneLau commented on cocos/core/components/ui-base/ui-transform.ts
> +    public setContentSize (val: Size | number, height?: number) {
API 提示参数接口没有增加啊

2020-11-05 02:51 UTC, JoneLau commented on cocos/core/scene-graph/deprecated.ts
> +            if(typeof size === 'number' || size instanceof Number){
内容不需要改吧，代码提示都明确说明要么设置 Size，要们设置 （width，height），这个时候还要强行只设置一个，就是用户的问题了啊，如果要设置 width，我们有单独的 uiTransform.width 的接口

2020-11-05 07:22 UTC, yeshao2069 reviewed
已经修改

2020-11-05 07:46 UTC, JoneLau approved these changes

2020-11-05 07:47 UTC, pandamicro requested changes

2020-11-05 07:47 UTC, pandamicro commented on cocos/core/components/ui-base/ui-transform.ts
> +     * @param height - The height of node content transformation.
这个 API 只有一个参数，不能用同一个 API 注释来覆盖两个 API。这里只应该写

@param size - The size of the UI transformation

2020-11-05 07:47 UTC, pandamicro commented on cocos/core/components/ui-base/ui-transform.ts
>       * 设置节点原始大小，不受该节点是否被缩放或者旋转的影响。
往上找两行，还有一句

All nodes have a size. Layer and Scene have the same size of the screen.

要删除

2020-11-05 07:47 UTC, pandamicro commented on cocos/core/components/ui-base/ui-transform.ts
> +    public setContentSize(width: number, height: number) : void;
这里也应该添加 API 描述

    /**
     * @en
     * Sets the untransformed size of the node.
     * The contentSize remains the same no matter if the node is scaled or rotated.
     * @zh
     * 设置节点原始大小，不受该节点是否被缩放或者旋转的影响。
     *
     * @param width - The width of the UI transformation
     * @param height - The height of the UI transformation
     * @example
     * ```ts
     * import { Size } from 'cc';
     * node.setContentSize(100, 100);
     * ```
     */

2020-11-05 07:47 UTC, pandamicro commented on cocos/core/components/ui-base/ui-transform.ts
>       * node.setContentSize(100, 100);
删除这一行，这一行是下面一个 API 的案例

2020-11-05 09:19 UTC, pandamicro approved these changes

2020-11-05 09:19 UTC, merged