fix native blend target
cocos/cocos-engine pull request #7693
Opened 2020-11-04 07:16 UTC by Mee-gu

Re: cocos-creator/2d-tasks#

Changes:
 * fix native blend target

2020-11-04 08:19 UTC, YunHsiao requested changes

2020-11-04 08:19 UTC, YunHsiao commented on cocos/core/renderer/core/pass.ts
> +                    bs.setTarget(i, new BlendTarget(t as any));
这么写 web 环境有问题的啊

2020-11-04 08:20 UTC, Mee-gu commented on cocos/core/renderer/core/pass.ts
> +                    bs.setTarget(i, new BlendTarget(t as any));
我刚才测了好像可以跑

2020-11-04 08:21 UTC, YunHsiao commented on cocos/core/gfx/pipeline-state.jsb.ts
> +export const BlendState = gfx.BlendState;
应该可以把 pass 那的 import 改成从 gfx 根目录取，就不用这个文件了吧

2020-11-04 08:23 UTC, Mee-gu commented on cocos/core/gfx/pipeline-state.jsb.ts
> +export const BlendState = gfx.BlendState;
其他地方可能也隐式 import 了 pipeline-state，导致还是引用 pipeline-state 里的声明的结构体

2020-11-04 08:29 UTC, Mee-gu commented on cocos/core/renderer/core/pass.ts
> +                    bs.setTarget(i, new BlendTarget(t as any));
是有问题。。。

2020-11-04 09:03 UTC, YunHsiao commented on cocos/core/gfx/pipeline-state.jsb.ts
> +export const BlendState = gfx.BlendState;
我在 #7683 已经把所有 import pipeline-state 的地方都改了

2020-11-04 09:12 UTC, Mee-gu commented on cocos/core/renderer/core/pass.ts
> +                    bs.setTarget(i, new BlendTarget(t as any));
修改了

2020-11-05 09:38 UTC, Mee-gu commented
在这里修复了: https://github.com/cocos-creator/engine/pull/7700

2020-11-05 09:38 UTC, closed without merging