improve particle system 2d
cocos/cocos-engine pull request #7739
Opened 2020-11-09 07:03 UTC by knoxHuang

1.add tooltip
2.improve code

2020-11-09 07:10 UTC, caryliu1999 approved these changes

2020-11-09 09:07 UTC, pandamicro requested changes

2020-11-09 09:07 UTC, pandamicro commented on cocos/particle-2d/particle-system-2d.ts
> +import { warnID, errorID } from '../core/platform';
尽量不要引用庞大的模块，引用具体的模块比较好，否则很容易造成循环引用

2020-11-09 09:07 UTC, pandamicro commented on cocos/particle-2d/particle-system-2d.ts
> +    static PNGReader = PNGReader;
导出这些干啥？？？

2020-11-09 09:07 UTC, pandamicro commented on cocos/particle-2d/particle-system-2d.ts
> +    public get stopped () {
API 文档应该注释在 public 属性上

2020-11-09 09:07 UTC, pandamicro commented on cocos/particle-2d/particle-system-2d.ts
> +                    console.error(error);
使用 debug 库

2020-11-09 09:07 UTC, pandamicro commented on cocos/particle-2d/particle-system-2d.ts
> +                        console.error(error);
同上

2020-11-09 09:07 UTC, pandamicro commented on cocos/particle-2d/particle-system-2d.ts
> +        this.posVar = new Vec2(parseFloat(dict["sourcePositionVariancex"] || 0), parseFloat(dict["sourcePositionVariancey"] || 0));
我看了一下属性的声明，都是已经通过 Vec2.ZERO.clone() 初始化过后的，不应该再创建新的对象，应该用 set，这里为什么要这么改？

2020-11-09 09:07 UTC, pandamicro commented on cocos/particle-2d/particle-system-2d.ts
> +            this.gravity = new Vec2(parseFloat(dict["gravityx"] || 0), parseFloat(dict["gravityy"] || 0));
同上

2020-11-09 09:16 UTC, knoxHuang commented on cocos/particle-2d/particle-system-2d.ts
> +    static PNGReader = PNGReader;
后续编辑器的 importer 会用到

2020-11-09 09:17 UTC, knoxHuang commented on cocos/particle-2d/particle-system-2d.ts
> +        this.posVar = new Vec2(parseFloat(dict["sourcePositionVariancex"] || 0), parseFloat(dict["sourcePositionVariancey"] || 0));
这个之前是编辑器用了 set 会有 undefined 的问题，所以才改成这样的，不过 engine 应该不会有这个问题，我改回来

2020-11-09 10:09 UTC, pandamicro commented on cocos/particle-2d/particle-system-2d.ts
> +    static PNGReader = PNGReader;
ImageFormat, EmitterMode, PositionType 以及几个常量都可以是 ParticleSystem2D 的 static 属性
getImageFormatByData 作为 static 方法我也能接受，但是要直接写到类中，别声明在外面，使用上也直接调用 static 函数

codec 应该改名为 ZipUtils

ZipUtils，TiffReader 和 PNGReader 应该在模块中直接导出，不应该放在 ParticleSystem2D 类下

2020-11-09 10:15 UTC, shrinktofit commented on cocos/particle-2d/particle-system-2d.ts
> +    static PNGReader = PNGReader;
@knoxHuang  如果只为了编辑器使用，有别的途径

2020-11-09 10:17 UTC, shrinktofit commented on cocos/particle-2d/particle-system-2d.ts
> +    static PNGReader = PNGReader;
像codec TiffReader PNGReader，在运行时用户用不到吧

2020-11-09 10:19 UTC, knoxHuang commented on cocos/particle-2d/particle-system-2d.ts
> +    static PNGReader = PNGReader;
运行也要用到

2020-11-09 10:20 UTC, pandamicro commented on cocos/particle-2d/particle-system-2d.ts
> +    static PNGReader = PNGReader;
用户用不到的

2020-11-09 11:51 UTC, pandamicro requested changes

2020-11-09 11:51 UTC, pandamicro commented on cocos/particle-2d/particle-system-2d.ts
> +    static START_RADIUS_EQUAL_TO_END_RADIUS = START_RADIUS_EQUAL_TO_END_RADIUS;
这些常量应该加 readonly

2020-11-10 01:52 UTC, knoxHuang commented on cocos/particle-2d/particle-system-2d.ts
> +    static PNGReader = PNGReader;
没瞎说啊，这个是运行的时候，解析 plist 时候用到的啊

2020-11-10 03:35 UTC, pandamicro approved these changes

2020-11-10 03:58 UTC, merged