[3.0] [bugfix] Graphics memleak
cocos/cocos-engine pull request #7849
Opened 2020-11-23 10:12 UTC by PatriceJiang

Re: cocos-creator/2d-tasks#

Changes:
 *

2020-11-23 10:17 UTC, PatriceJiang commented
@JoneLau @LinYunMo 麻烦review 下

2020-11-23 10:18 UTC, PatriceJiang commented on cocos/ui/assembler/graphics/webgl/graphics-assembler.ts
> +        }
没一帧只 upload 一次, 避免内存 stagingbuffer 占用过多

2020-11-24 02:34 UTC, JoneLau requested changes

2020-11-24 02:34 UTC, JoneLau commented on cocos/ui/components/graphics.ts
> +        if (this._assembler && this._assembler.uploadData) {
我这里有一个疑惑，因为 graphics 只有绘制的时候才会去更新，这里每帧更新，是否有必要，如果是 skeleton 更新，是不是应该放到 skeleton 上去主动更新比较合适？

2020-11-24 02:57 UTC, PatriceJiang commented on cocos/ui/components/graphics.ts
> +        if (this._assembler && this._assembler.uploadData) {
已撤销相应修改. 

---- 
每帧 upload 数据会降低能效

2020-11-24 06:42 UTC, PatriceJiang commented
@minggo 麻烦合并下

2020-11-24 07:21 UTC, merged