adapt gfx changes
cocos/cocos-engine pull request #8019
Opened 2020-12-25 04:37 UTC by YunHsiao

Re: cocos-creator/2d-tasks#

Changes:
 *

2020-12-25 06:44 UTC, minggo commented on cocos/core/gfx/webgl/webgl-buffer.ts
> +            0,
含需要传吗？

2020-12-25 07:26 UTC, YunHsiao commented on cocos/core/gfx/webgl/webgl-buffer.ts
> +            0,
内层实现可以先不动，所以传个 0 就行了

2020-12-25 08:21 UTC, minggo commented on cocos/2d/components/graphics.ts
> +        const ia = subModelList[0].inputAssembler;
for 循环的 ia 会把外部的覆盖掉

2020-12-25 08:23 UTC, minggo commented on cocos/2d/components/graphics.ts
> +        ia.indexBuffer!.update(renderDataList[0].iData);
@JoneLau 看一下吧。

2020-12-25 08:38 UTC, JoneLau requested changes

2020-12-25 08:38 UTC, JoneLau commented on cocos/2d/components/graphics.ts
> +        ia.indexBuffer!.update(renderDataList[0].iData);
跟小明说的一样，这个要在循环里面，一个 vdata 对应一个 ia 的 vb

2020-12-28 08:43 UTC, minggo approved these changes

2020-12-28 09:23 UTC, merged