Revert canvas
cocos/cocos-engine pull request #8031
Opened 2020-12-26 09:38 UTC by troublemaker52025

Re: cocos-creator/2d-tasks#

Changes:
 *

2020-12-26 10:26 UTC, LinYunMo requested changes

2020-12-26 10:26 UTC, LinYunMo commented on cocos/2d/framework/canvas.ts
>      get visibility () {
这个属性现在也可以删除了

2020-12-26 10:26 UTC, LinYunMo commented on cocos/2d/framework/canvas.ts
> -
这些都是公开接口，需要写弃用

2020-12-26 10:37 UTC, troublemaker52025 commented on cocos/2d/framework/canvas.ts
> -
保留这些 getter/setter 方法并添加弃用声明么？

2020-12-26 10:46 UTC, LinYunMo commented on cocos/2d/framework/canvas.ts
> -
不用保留，直接写弃用声明，参考 deprecated 文件

2020-12-28 01:37 UTC, 2youyou2 approved these changes

2020-12-28 06:18 UTC, knoxHuang commented on cocos/video/video-player-impl-web.ts
> -            if (this._stayOnBottom) {
这个不需要加吧，上面已经有做判断了

![image](https://user-images.githubusercontent.com/7564028/103193477-833fbd00-4917-11eb-85c8-4ae15e2d069b.png)

2020-12-28 06:22 UTC, troublemaker52025 commented on cocos/video/video-player-impl-web.ts
> -            if (this._stayOnBottom) {
这个是源码上带的判断，我这边因为接口改动，所有修改了部分代码，又因为ESlint 才修改到这里，具体需不需要判断，还不是很清楚

2020-12-28 10:00 UTC, caryliu1999 commented on cocos/2d/renderer/ui.ts
> +            delta = a.camera.priority - b.camera.priority;
没有camera的canvas就从screen列表移除吧，没有就不需要去处理渲染逻辑，这里应该也不需要判定是否存在camera

2020-12-30 09:27 UTC, pandamicro commented on cocos/video/video-player-impl-web.ts
> -            if (this._stayOnBottom) {
人家说了不用判断啊，前面代码里面判断了，没有就 return 掉了，这有啥看不明白的

2020-12-30 14:38 UTC, holycanvas approved these changes

2020-12-30 14:39 UTC, merged