layout bug fix when child change
cocos/cocos-engine pull request #8070
Opened 2021-01-04 06:57 UTC by LinYunMo

2021-01-04 07:24 UTC, holycanvas approved these changes

2021-01-06 05:37 UTC, JoneLau requested changes

2021-01-06 05:37 UTC, JoneLau commented on cocos/2d/framework/ui-transform.ts
> +                    diff = a.getSiblingIndex() - b.getSiblingIndex();
这里为什么删了那部分

2021-01-06 05:37 UTC, JoneLau commented on cocos/ui/layout.ts
> +            child.on('active-in-hierarchy-changed', this._childChange, this);
这个事件是哪里来的事件，能否通过枚举来进行注册

2021-01-06 05:39 UTC, LinYunMo commented on cocos/2d/framework/ui-transform.ts
> +                    diff = a.getSiblingIndex() - b.getSiblingIndex();
因为逻辑重复了，改前后行为一致的

2021-01-06 05:40 UTC, LinYunMo commented on cocos/ui/layout.ts
> +            child.on('active-in-hierarchy-changed', this._childChange, this);
这个事件在节点 activateNode 中派发，引擎没有提供这个枚举值

2021-01-06 05:47 UTC, JoneLau commented on cocos/ui/layout.ts
> +            child.on('active-in-hierarchy-changed', this._childChange, this);
对，我的意思是，这个看起来是节点事件，是不是应该列入节点枚举里，然后通过节点枚举去注册

2021-01-06 06:13 UTC, holycanvas commented on cocos/ui/layout.ts
> +            child.on('active-in-hierarchy-changed', this._childChange, this);
这个事件应该是不想开发给用户用

2021-01-06 06:36 UTC, JoneLau approved these changes

2021-01-06 06:36 UTC, JoneLau commented on cocos/ui/layout.ts
> +            child.on('active-in-hierarchy-changed', this._childChange, this);
如果是不想开放的话，这里可以不用枚举

2021-01-06 07:09 UTC, merged