Fix unused buffer upload and buffer memory leap.
cocos/cocos-engine pull request #8074
Opened 2021-01-04 14:17 UTC by caryliu1999

2021-01-07 02:50 UTC, sunnylanwanjun commented
mesh-buffer里面的有个地方有问题, 刘航可能也要改一下
![image](https://user-images.githubusercontent.com/23014329/103845000-1de98a00-50d6-11eb-8816-ba3a1c5f3d50.png)
这个uploadBuffers执行后，_dirty没有置位，逻辑上说不通

2021-01-08 04:16 UTC, JoneLau requested changes

2021-01-08 04:16 UTC, JoneLau commented on cocos/2d/components/ui-static-batch.ts
> +        if (ui) {
我看了一下 meshbuffer 在 request 的时候，如果内容超出了，会帮忙 autoMerge，什么情况下还需要自己执行

2021-01-08 04:16 UTC, JoneLau commented on cocos/2d/renderer/ui.ts
> +    public registerCustomBuffer (attributes: MeshBuffer | Attribute[], callback: ((...args: number[]) => void) | null) {
这个接口是预留吗，似乎没有看到调用的地方

2021-01-08 04:16 UTC, JoneLau commented on cocos/2d/renderer/ui.ts
> +        if (!buffers) { buffers = []; this._customMeshBuffers.set(strideBytes, buffers); }
这里的意思似乎是相同的 attributes gong用一个 meshbuffer，如果 buffer 溢出，似乎只是单纯的重新申请，customMeshBuffer 好像没有再次填充。但是如果再次填充也很奇怪，因为 attributes 相同，这里我没有看的很懂

2021-01-11 09:32 UTC, caryliu1999 commented on cocos/2d/renderer/ui.ts
> +    public registerCustomBuffer (attributes: MeshBuffer | Attribute[], callback: ((...args: number[]) => void) | null) {
> 的

adapter 调用了

2021-01-11 09:35 UTC, caryliu1999 commented on cocos/2d/renderer/ui.ts
> +        if (!buffers) { buffers = []; this._customMeshBuffers.set(strideBytes, buffers); }
> 这里的意思似乎是相同的 attributes gong用一个 meshbuffer，如果 buffer 溢出，似乎只是单纯的重新申请，customMeshBuffer 好像没有再次填充。但是如果再次填充也很奇怪，因为 attributes 相同，这里我没有看的很懂

customMeshBuffer 是想交给外部来申请创建然后管理合批，也是为了再链接回 ui 的 mesh buffer，如果越界申请就还是跳回 ui 的

2021-01-11 09:37 UTC, caryliu1999 commented on cocos/2d/components/ui-static-batch.ts
> +        if (ui) {
> 我看了一下 meshbuffer 在 request 的时候，如果内容超出了，会帮忙 autoMerge，什么情况下还需要自己执行

> mesh-buffer里面的有个地方有问题, 刘航可能也要改一下
> ![image](https://user-images.githubusercontent.com/23014329/103845000-1de98a00-50d6-11eb-8816-ba3a1c5f3d50.png)
> 这个uploadBuffers执行后，_dirty没有置位，逻辑上说不通

这里也加上了，之前是在 reset 做的

2021-01-12 07:18 UTC, sunnylanwanjun commented
![Uploading image.png…]()
这行代码可以删了，当时因为dirty没有置位，所以加了这行比较hack的代码，现在没有用了

2021-01-12 07:24 UTC, caryliu1999 commented
> 这行代码可以删了，当时因为dirty没有置位，所以加了这行比较hack的代码，现在没有用了

删除了

2021-01-12 07:25 UTC, sunnylanwanjun approved these changes

2021-01-12 07:29 UTC, LinYunMo approved these changes

2021-01-12 07:37 UTC, merged