Support local buffer binding for ui render component.
cocos/cocos-engine pull request #8124
Opened 2021-01-12 08:42 UTC by caryliu1999

2021-01-13 08:27 UTC, LinYunMo approved these changes

2021-01-13 10:27 UTC, JoneLau approved these changes

2021-01-16 10:27 UTC, pandamicro requested changes

2021-01-16 10:27 UTC, pandamicro commented on cocos/2d/renderer/batcher-2d.ts
> +    private _descriptorSetCache = new DescriptorSetCache();c
多了一个 c

2021-01-16 10:27 UTC, pandamicro commented on cocos/2d/renderer/batcher-2d.ts
> +        if (batch.useLocalData) {
为什么 useLocalData 存的是 transform？什么情况下 use local data，什么情况下不用呢？

在原始代码中我没看到这个分支，什么情况下需要自己创建 local data ？

从现在代码看，local data 只是存储 transform，意思是类似 graphics，motion streak 这种需要 model matrix uniform 的才会设置 useLocalData ?

2021-01-16 10:27 UTC, pandamicro commented on cocos/2d/renderer/batcher-2d.ts
> +        }
_localData 不处理吗？

2021-01-16 10:40 UTC, caryliu1999 commented on cocos/2d/renderer/batcher-2d.ts
> +    private _descriptorSetCache = new DescriptorSetCache();c
> 多了一个 c

已删除

2021-01-16 10:40 UTC, caryliu1999 commented on cocos/2d/renderer/batcher-2d.ts
> +        if (batch.useLocalData) {
> 为什么 useLocalData 存的是 transform？什么情况下 use local data，什么情况下不用呢？
> 
> 在原始代码中我没看到这个分支，什么情况下需要自己创建 local data ？
> 
> 从现在代码看，local data 只是存储 transform，意思是类似 graphics，motion streak 这种需要 model matrix uniform 的才会设置 useLocalData ?

对，矩阵需要在 shader 中使用的就需要设置这个，传递节点的矩阵数据

2021-01-16 10:41 UTC, caryliu1999 commented on cocos/2d/renderer/batcher-2d.ts
> +        }
> _localData 不处理吗？

已添加

2021-01-16 11:05 UTC, pandamicro approved these changes

2021-01-18 02:25 UTC, merged