fix UIModel depth bug & fix UIModel render twice bug
cocos/cocos-engine pull request #8152
Opened 2021-01-16 07:24 UTC by LinYunMo

Re: https://github.com/cocos-creator/3d-tasks/issues/5934
Re: https://github.com/cocos-creator/3d-tasks/issues/5872

2021-01-16 10:41 UTC, pandamicro requested changes

2021-01-16 10:41 UTC, pandamicro commented on cocos/core/renderer/core/pass.ts
> +        this._depthHash = (depthTest) | (depthWrite << 1) | (this._dss.depthFunc << 2);
感觉不需要 depth hash 缓存啊，实时计算不算太费

2021-01-16 10:41 UTC, pandamicro commented on cocos/2d/renderer/stencil-manager.ts
> +            key = pass.getDepthHash() | (stage << 6) | (this._maskStack.length << 9);
我觉得这里直接计算就行了

```
const dss = pass.dss;
key = (dss.depthTest) | (dss.depthWrite << 1) | (dss.depthFunc << 2) | (stage << 6) | (this._maskStack.length << 9);
```

增加那些代码意义不大

2021-01-16 10:46 UTC, caryliu1999 commented on cocos/core/renderer/core/pass.ts
> +        this._depthHash = (depthTest) | (depthWrite << 1) | (this._dss.depthFunc << 2);
> 感觉不需要 depth hash 缓存啊，实时计算不算太费

确实没必要再给 pass 加这些处理吧，也只有 ui model 需要使用 depth test

2021-01-18 03:35 UTC, pandamicro approved these changes

2021-01-18 05:34 UTC, merged