add spine customMaterial & set default UI depthTest False
cocos/cocos-engine pull request #8205
Opened 2021-01-25 10:29 UTC by LinYunMo

Re: https://github.com/cocos-creator/3d-tasks/issues/6139

2021-01-25 10:54 UTC, PatriceJiang approved these changes

2021-01-25 11:14 UTC, holycanvas approved these changes

2021-01-25 11:28 UTC, caryliu1999 commented on cocos/spine/skeleton.ts
> -        return super.customMaterial;
组件不是有通用的材质属性吗，为什么这里要单独再设置一个属性来指定？

2021-01-26 02:01 UTC, caryliu1999 approved these changes

2021-01-26 04:15 UTC, pandamicro requested changes

2021-01-26 04:15 UTC, pandamicro commented on cocos/spine/skeleton.ts
> +        const cache = Object.values(this._materialCache);
Should use `for in` here, don't create array

2021-01-26 04:15 UTC, pandamicro commented on editor/assets/effects/builtin-spine.effect
> -    #endif
Should keep USE_LOCAL define, we might use model matrix for spine, if there are no many spine copies, using model matrix would be much better than transform all vertices to world coordinates

2021-01-26 04:15 UTC, pandamicro commented on editor/assets/effects/builtin-spine.effect
> +      texColor *= texture(cc_spriteTexture, uv0);
Should use CCSampleTexture

2021-01-26 06:17 UTC, pandamicro approved these changes

2021-01-26 06:19 UTC, merged