fix sys judge
cocos/cocos-engine pull request #8377
Opened 2021-03-18 03:56 UTC by OnlyKoei

2021-04-06 12:53 UTC, pandamicro requested changes

2021-04-06 12:53 UTC, pandamicro commented on cocos/core/platform/sys.ts
> +    getNetworkType(): NetworkType {
Do not modify the coding style, please make sure your local eslint setting is synced

2021-04-06 12:53 UTC, pandamicro commented on cocos/core/platform/sys.ts
> +            if (browserType === "qqbrowser" || browserType === "mqqbrowser") {
How about change typeReg1 to 

```
const typeReg1 = /wechat|mqqbrowser|micromessenger|qqbrowser|sogou|qzone|liebao|maxthon|ucbs|360 aphone|360browser|baiduboxapp|baidubrowser|maxthon|mxbrowser|miuibrowser/i
```

What's the test result

2021-04-12 15:45 UTC, OnlyKoei commented
关闭，另外提交

2021-04-12 15:45 UTC, closed without merging