Delete private node for v3.1
cocos/cocos-engine pull request #8382
Opened 2021-03-19 02:32 UTC by troublemaker52025

# Conflicts:
#	cocos/core/scene-graph/private-node.ts

Re: cocos-creator/3d-tasks#

Changelog:
 *

2021-03-19 02:38 UTC, troublemaker52025 commented
associate editor pr : https://github.com/cocos-creator/editor-3d/pull/5366

2021-03-29 05:59 UTC, holycanvas commented on cocos/2d/components/rich-text.ts
> +    node.hideFlags = CCObject.HideFlags.DontSave;
应该是 |= 吧

2021-03-29 05:59 UTC, holycanvas commented on cocos/core/data/object.ts
> +    public set hideFlags (hideFlags :number) {
getter 要提供下吧，另外参数类型应该明确下

2021-03-29 05:59 UTC, holycanvas commented on cocos/core/data/object.ts
> +     * @zh 开放 HideFlags 的枚举设置
objFlags 不需要开放了吧，hideFlags 就够了

2021-03-29 05:59 UTC, holycanvas commented on cocos/core/data/object.ts
> +     * @zh 开放 HideFlags 的枚举设置
注释完善下吧

2021-03-29 05:59 UTC, holycanvas commented on cocos/core/data/object.ts
> +js.value(CCObject, 'HideFlags', {
下面不是定义了 enum 了么，在 CCObject 类型里面导出一下就好了吧，这里还需要这样么

2021-03-29 05:59 UTC, holycanvas commented on cocos/core/data/object.ts
> +        Destroyed,
为啥 HideFlags 里面会有 Destroyed ?

2021-03-29 05:59 UTC, holycanvas commented on cocos/2d/components/rich-text.ts
> +        node = new Node(type);
PrivateNode 应该还有个 HideInHierarchy 才对

2021-03-29 05:59 UTC, holycanvas commented on cocos/dragon-bones/ArmatureDisplay.ts
> +                debugDrawNode.hideFlags = CCObject.HideFlags.DontSave;
不止 DontSave, 还有 HideInHerarchy

2021-03-29 05:59 UTC, holycanvas commented on cocos/physics-2d/builtin/builtin-world.ts
> +            node.hideFlags = CCObject.HideFlags.DontSave;
最好别用 =，用 =|

2021-03-29 05:59 UTC, holycanvas commented on cocos/spine/skeleton.ts
> +                debugDrawNode.hideFlags = CCObject.HideFlags.DontSave;
少了个 HideInHerarchy

2021-03-29 05:59 UTC, holycanvas commented on cocos/tiledmap/tiled-object-group.ts
> +                    imgNode.hideFlags = CCObject.HideFlags.DontSave;
同上

2021-03-29 05:59 UTC, holycanvas commented on cocos/terrain/terrain.ts
> +        this._node.hideFlags = CCObject.HideFlags.DontSave;
同上

2021-03-29 05:59 UTC, holycanvas commented on cocos/ui/sub-context-view.ts
> +        this._content = new Node('content');
同上

2021-03-29 05:59 UTC, holycanvas commented on extensions/spine/Skeleton.js
> +                let debugDrawNode = new cc.Node();
同上

2021-03-29 06:00 UTC, holycanvas commented
另外，确认下 PrivateNode 之前有没有开放出去，如果开放出去了，记得要 deprecate 一下

2021-03-29 06:01 UTC, troublemaker52025 commented on cocos/2d/components/rich-text.ts
> +    node.hideFlags = CCObject.HideFlags.DontSave;
node 的 hideFlags内部执行了 |=

2021-03-29 06:01 UTC, troublemaker52025 commented on cocos/core/data/object.ts
> +    public set hideFlags (hideFlags :number) {
明白

2021-03-29 06:01 UTC, troublemaker52025 commented on cocos/core/data/object.ts
> +     * @zh 开放 HideFlags 的枚举设置
这个有争议   我也没想好要不要开放 objFlags

2021-03-29 06:02 UTC, troublemaker52025 commented on cocos/core/data/object.ts
> +     * @zh 开放 HideFlags 的枚举设置
收到

2021-03-29 06:02 UTC, troublemaker52025 commented on cocos/core/data/object.ts
> +js.value(CCObject, 'HideFlags', {
我觉得需要  从 objFlags 中拆出来的

2021-03-29 06:05 UTC, holycanvas commented on cocos/2d/components/rich-text.ts
> +    node.hideFlags = CCObject.HideFlags.DontSave;
> node 的 hideFlags内部执行了 |=

内部做不太合适吧，内部直接赋值就行了，如果内部 |= ，用户就没法删除了

2021-03-29 06:05 UTC, troublemaker52025 commented on cocos/2d/components/rich-text.ts
> +    node.hideFlags = CCObject.HideFlags.DontSave;
确实

2021-03-29 06:24 UTC, holycanvas commented on cocos/2d/components/rich-text.ts
> +    node.hideFlags = CCObject.HideFlags.DontSave;
内部应该是先清理掉之前已经设置的 HideFlags 之后再 | 就没问题了

2021-03-29 06:30 UTC, holycanvas commented on cocos/core/data/object.ts
> +js.value(CCObject, 'HideFlags', {
我的意思是下面不是有 HideFlags 的枚举了么，这里为啥还需要这个设置？

2021-03-29 06:32 UTC, troublemaker52025 commented on cocos/spine/skeleton.ts
> +                debugDrawNode.hideFlags = CCObject.HideFlags.DontSave;
这个跟谢万翔确认过，需要在编辑器中显示。下面同

2021-03-29 06:33 UTC, troublemaker52025 commented
> 
> 
> 另外，确认下 PrivateNode 之前有没有开放出去，如果开放出去了，记得要 deprecate 一下

已经开放出去了，需要补充 deprecate

2021-03-29 06:38 UTC, troublemaker52025 commented on cocos/core/data/object.ts
> +js.value(CCObject, 'HideFlags', {
这个是设置 HideFlags 枚举对应数值的，并且应该 objFlags 中关于 HideFlags 关联项删除的

2021-03-29 06:39 UTC, holycanvas commented on cocos/spine/skeleton.ts
> +                debugDrawNode.hideFlags = CCObject.HideFlags.DontSave;
不是吧，这里和以前行为不一致啊，PrivateNode 里面有 HideInHierarchy，这里也要带上才行啊，这样才和以前效果一致

2021-03-30 03:25 UTC, pandamicro requested changes

2021-03-30 03:25 UTC, pandamicro commented on cocos/core/data/object.ts
> +const All = DontSave | EditorOnly | LockedInEditor | HideInHierarchy;
这个 ALL 不合理，ALL 一般是 0xffffffff
命名一定要注意意义

2021-03-30 03:25 UTC, pandamicro commented on cocos/core/data/object.ts
> +     * @en Provide settings for nodes: the object will not be saved, the object will not be saved when building the project,
这个属性不仅和节点有关，组件对象也可以使用类似的 hideFlags，未来编辑器也是可以处理的

2021-03-30 03:25 UTC, pandamicro commented on cocos/core/data/object.ts
> +     * @en Provide settings for nodes: the object will not be saved, the object will not be saved when building the project,
在 object 的注释中，使用通用性描述

2021-03-30 03:25 UTC, pandamicro commented on cocos/core/data/object.ts
> +     * @en Provide settings for nodes: the object will not be saved, the object will not be saved when building the project,
同时还需要列举具体哪些 flag 是生效的

2021-03-30 03:25 UTC, pandamicro commented on cocos/core/data/object.ts
> +js.value(CCObject, 'HideFlags', {
这不对啊，如果这样做 HideFlags.DontSave 和 Flags.Destroyed 就重复了，mask 位机制一定要用统一的枚举，否则会冲突

2021-03-30 03:25 UTC, pandamicro commented on cocos/core/scene-graph/deprecated.ts
> +legacyCC.PrivateNode = Node;
这个 deprecate 和原始功能不等价。应该写一个 PrivateNode 类实现，构造函数中设置 hideFlags

2021-03-30 03:25 UTC, pandamicro commented on cocos/dragon-bones/ArmatureDisplay.ts
> +                debugDrawNode.hideFlags |= CCObject.HideFlags.HideInHierarchy;
合并到同一行，以现在的实现，这两句代码相当于两次 getter 调用 + 两次 setter 调用

2021-03-30 03:48 UTC, troublemaker52025 commented on cocos/core/data/object.ts
> +js.value(CCObject, 'HideFlags', {
每个枚举都做了自己的标志位映射了，HideFlags.DontSave 与 Flags.Destroyed两个枚举位置是一样的 但是 mask 不一样

2021-03-30 07:09 UTC, troublemaker52025 commented on cocos/core/scene-graph/deprecated.ts
> +legacyCC.PrivateNode = Node;
这个 privateNode 具体是实现什么功能，应该由用户创建的普通 Node 去控制。我觉得不应该继承出多种多样的 Node 去教用户

2021-03-30 09:11 UTC, pandamicro commented on cocos/core/scene-graph/deprecated.ts
> +legacyCC.PrivateNode = Node;
deprecated 是废弃，但是功能一致，现在完全没有做到保留功能

2021-03-30 10:18 UTC, pandamicro commented on cocos/core/data/object.ts
> +const AllHideMask = DontSave | EditorOnly | LockedInEditor | HideInHierarchy;
复数 AllHideMasks

2021-03-30 10:18 UTC, pandamicro commented on cocos/core/data/object.ts
> +    export enum HideFlags {
从 enum 定义来说，HideFlags 和 Flags 是冲突的，基于这点还是不建议拆分 Flags 和 HideFlags

2021-04-01 08:11 UTC, troublemaker52025 commented on cocos/2d/components/rich-text.ts
> +        node = new Node(type);
sure

2021-04-02 03:45 UTC, troublemaker52025 commented on cocos/core/scene-graph/deprecated.ts
> +legacyCC.PrivateNode = Node;
sure

2021-04-02 03:52 UTC, troublemaker52025 commented
还有一个问题，CCObject.Flags 枚举有 22 个之多，但是 hideFlags 却只能接收 5 个。用户不会感到奇怪么？

2021-04-02 03:53 UTC, pandamicro requested changes

2021-04-02 03:53 UTC, pandamicro commented on cocos/core/scene-graph/private-node.ts
> +        console.warn('This object is deprecated, please try not to use.');
The PrivateNode is deprecated, please use Node directly with `CCObject.Flags.DontSave | CCObject.Flags.HideInHierarchy` flags activated.

2021-04-02 03:53 UTC, pandamicro commented on cocos/core/scene-graph/private-node.ts
> +        console.warn('This object is deprecated, please try not to use.');
使用 cc.warnID，不要把字符串直接写在代码中

2021-04-02 03:53 UTC, pandamicro commented on cocos/core/data/object.ts
> +        if (DEBUG && !EDITOR) {
我不理解为什么在 EDITOR 下就可以随意通过 hideFlags 设置其他 flags 了

2021-04-02 03:54 UTC, troublemaker52025 commented on cocos/core/scene-graph/private-node.ts
> +        console.warn('This object is deprecated, please try not to use.');
sure

2021-04-02 03:56 UTC, troublemaker52025 commented on cocos/core/data/object.ts
> +        if (DEBUG && !EDITOR) {
我昨天测试出一个 bug，在编辑器下能看到设置了 HideInHierarchy 这个标志位的节点。这就跟原来测试例子的效果不一致了

2021-04-02 05:52 UTC, holycanvas commented on cocos/core/data/object.ts
> +        return this._objFlags;
这个地方不是应该返回 this._objFlags & CCObject.Flags.AllHideMasks 么，需要返回其他 flag 出去么

2021-04-02 05:52 UTC, holycanvas commented on cocos/core/data/object.ts
> +        if (DEBUG && !EDITOR) {
理论上应该一直做这个检查才对

2021-04-02 05:52 UTC, holycanvas commented on cocos/tiledmap/tiled-object-group.ts
> -                if (imgNode instanceof PrivateNode) {
这个判断要问下万翔，有点奇怪，看注释说的是只删除 PrivateNode, 不删除 Node, 你这样改可能 Node 也会被删除了

2021-04-02 05:53 UTC, holycanvas commented on cocos/core/scene-graph/private-node.ts
> + @ccclass('cc.PrivateNode')
这个文件的内容移动到 deprecated.ts ？

2021-04-02 06:03 UTC, troublemaker52025 commented on cocos/core/scene-graph/private-node.ts
> + @ccclass('cc.PrivateNode')
我觉得放在 deprecated.ts 没有必要吧。放在 deprecated.ts 里也不会提示 privateNode 是废弃的类

2021-04-02 06:04 UTC, troublemaker52025 commented on cocos/tiledmap/tiled-object-group.ts
> -                if (imgNode instanceof PrivateNode) {
确实有问题

2021-04-02 06:15 UTC, holycanvas commented on cocos/core/scene-graph/private-node.ts
> + @ccclass('cc.PrivateNode')
一个是代码比较干净，另一个是我们编辑器里面提供了功能可以一键剔出所有 deprecated.ts，减少包体。
![image](https://user-images.githubusercontent.com/15109777/113386909-d06f7700-93bd-11eb-8fd6-c32156c66fcf.png)

2021-04-02 06:20 UTC, troublemaker52025 commented on cocos/core/scene-graph/private-node.ts
> + @ccclass('cc.PrivateNode')
sure

2021-04-02 06:36 UTC, troublemaker52025 commented on cocos/core/data/object.ts
> +        if (DEBUG && !EDITOR) {
如果一直做这个检查，给 this._objFlags 的属性赋值就会失败

2021-04-02 06:37 UTC, troublemaker52025 commented on cocos/core/data/object.ts
> +        return this._objFlags;
不需要

2021-04-02 07:20 UTC, troublemaker52025 commented on cocos/core/data/object.ts
> +        if (DEBUG && !EDITOR) {
就应该在设置的时候   就检测好枚举状态，只能设置 AllHideMasks 中的参数。

2021-04-02 07:31 UTC, holycanvas approved these changes

2021-04-04 16:06 UTC, pandamicro commented on cocos/core/scene-graph/deprecated.ts
> +        warnID(4500, this.name);
没有提交 4500 到 EngineErrorMap.md

2021-04-07 03:23 UTC, pandamicro approved these changes

2021-04-08 09:47 UTC, merged

2021-04-08 09:48 UTC, troublemaker52025 commented
编辑器也需要同步合并，不然更新到这个版本就会报错