feat: tween props support function
cocos/cocos-engine pull request #8398
Opened 2021-03-25 02:53 UTC by Andesome

Re: cocos-creator/3d-tasks#

Changelog:
 * tween props support function

2021-06-15 03:44 UTC, pandamicro commented on cocos/tween/tween-action.ts
> +            if (value == null || typeof value === 'string') continue;
This is a type pre-check, should be placed before all actual assigns.

2021-06-16 07:27 UTC, JayceLai requested changes

2021-06-16 07:27 UTC, JayceLai commented on cocos/tween/tween-action.ts
>              // eslint-disable-next-line no-prototype-builtins
Please also modify the comment above

2021-06-26 15:22 UTC, pandamicro approved these changes

2021-06-26 15:22 UTC, merged