AnimationCurve
cocos/cocos-engine pull request #8409
Opened 2021-03-31 06:33 UTC by shrinktofit

Re: cocos-creator/3d-tasks#

Changelog:
 *

2021-04-22 01:37 UTC, shrinktofit commented
This PR tends to be in version 3.2+. Please do not merge it into 3.1. @holycanvas

2021-04-22 01:41 UTC, shrinktofit commented
The concepts and design document can be found at [here](https://github.com/cocos-creator/3d-tasks/issues/2618#issuecomment-819347989).

2021-07-20 12:10 UTC, gameall3d approved these changes
LGTM

2021-07-20 16:09 UTC, pandamicro reviewed
- MeshRenderer weight 相关的修改是关联的吗？
- 此次重构有没有潜在的性能问题或者预期的性能提升？
- 内存控制问题可能比较严重，需要测试复杂动画和动画切换，检查垃圾创建的情况
- 能不能让兼容 legacy 数据的代码在不需要的情况下被自动或手动剔除？
- 不仅代码量增加，小文件也很多，需要一个小游戏端包体增加的数据

这和个 PR 被合并的前提还是要在 3.3 阶段能够保障以下几点
- 保障动画模块有性能提升
- 避免运行时大量垃圾对象，导致频繁的 GC
- 保障数据迁移的可靠性
- 包体增加有限

2021-07-20 16:09 UTC, pandamicro commented on cocos/core/animation/animation-clip.ts
> +        for (const eventData of events) {
不要使用 for of

2021-07-20 16:09 UTC, pandamicro commented on cocos/core/animation/animation-clip.ts
> +        };
感受到垃圾的产生

2021-07-20 16:09 UTC, pandamicro commented on cocos/core/animation/animation-clip.ts
> +        for (const eventData of events) {
请检查所有的使用

2021-07-20 16:09 UTC, pandamicro commented on cocos/core/animation/animation-clip.ts
> +        for (const joint of Object.keys(skeletonFrames)) {
for of Object.keys 使用 for in 替代

2021-07-20 16:09 UTC, pandamicro commented on cocos/core/animation/animation-clip.ts
> +                    warn(`Seems like we have animation for ${joint} but are missing its parent joint ${parentJointName} in animation?`);
使用 warnID，检查所有 warn, log, error 的使用

2021-07-20 16:09 UTC, pandamicro commented on cocos/core/animation/animation-clip.ts
> +     * @deprecated Since V3.1.
deprecated 信息需要给出替代方式的指引

2021-07-20 16:09 UTC, pandamicro commented on cocos/core/animation/animation-clip.ts
> +    public syncLegacyData () {
所有函数应该在私有属性之后

2021-07-20 16:09 UTC, pandamicro commented on cocos/core/animation/animation-state.ts
> +    protected _doNotCreateEval = false;
AnimationClip 里面的是应该存在的吗？有重复吗？

2021-07-20 16:09 UTC, pandamicro commented on cocos/core/animation/exotic-animation/exotic-animation.ts
> +export class ExoticAnimation {
这个命名有其他引擎的先例吗？如果只是模型动画，能不能用 ModelAnimation 或者 ImportedAnimation

2021-07-20 16:09 UTC, pandamicro commented on cocos/core/animation/exotic-animation/exotic-animation.ts
> +        } = this;
这是什么骚操作？

2021-07-20 16:09 UTC, pandamicro commented on cocos/core/animation/tracks/color-track.ts
> +        }
感觉会很慢

2021-07-20 16:09 UTC, pandamicro commented on cocos/core/animation/tracks/quat-track.ts
> +    }
为什么保留空构造

2021-07-20 16:09 UTC, pandamicro commented on cocos/core/animation/value-proxy-factories/morph-weights.ts
> + @ccclass('cc.animation.MorphWeightValueProxy')
整个文件的代码缩进有问题

2021-07-20 16:09 UTC, pandamicro commented on cocos/core/curves/curve.ts
> +    }:  Partial<RealKeyframeValue> = { }) {
这种构造函数会导致大量的对象创建，也就是垃圾

2021-07-20 16:09 UTC, pandamicro commented on cocos/core/curves/curve.ts
> +    public interpMode = RealInterpMode.LINEAR;
不要用缩写

2021-07-20 16:09 UTC, pandamicro commented on cocos/core/curves/curve.ts
> +export class RealKeyframeValue {
为什么要用 Real 前缀

2021-07-20 16:09 UTC, pandamicro commented on cocos/core/curves/curve.ts
> +    }
这种直接量属性为什么要加 getter setter

2021-07-20 16:09 UTC, pandamicro commented on cocos/core/curves/keys-shared-curves.ts
> +    protected calculateLocation (time: number, out: TimeLocation) {
locate

2021-07-20 16:09 UTC, pandamicro commented on cocos/core/curves/real-curve-param.ts
> +export enum RealInterpMode {
如果其他引擎找到范例，可以考虑使用 Interp 替代 Interpolation

2021-07-20 16:09 UTC, pandamicro commented on cocos/core/geometry/curve.ts
> +            }),
大量的垃圾对象

2021-07-21 01:29 UTC, shrinktofit commented on cocos/core/curves/curve.ts
> +export class RealKeyframeValue {
因为还有 QuatKeyframeValue

2021-07-21 01:32 UTC, shrinktofit commented on cocos/core/animation/animation-clip.ts
> +        };
这里是必须创建对象的，可以看看 runtimeEvent 的定义；这个方法只会在设置时候调用（一般是编辑器）

2021-07-21 01:33 UTC, shrinktofit commented on cocos/core/animation/exotic-animation/exotic-animation.ts
> +        } = this;
等价于 const a = this._a

2021-07-21 02:46 UTC, shrinktofit commented on cocos/core/curves/real-curve-param.ts
> +export enum RealInterpMode {
已替换

2021-07-21 02:47 UTC, shrinktofit commented on cocos/core/animation/tracks/quat-track.ts
> +    }
这里是一种 TypeScript 技巧，`constructor(private _a: number)` 等于同时声明了有个成员 `_a`

2021-07-21 08:44 UTC, shrinktofit commented
# Performance Report

- BunnyFrameTest: 20000 cases
- BunnyTransformTest: 20000 cases
- ModelAnimation: 1000 cases

## Desktop Browser

Environment: Microsoft Edge 91.0.864.70, Windows 10 x64

|  | BunnyFrameTest | BunnyTransformTest | ModelAnimation |
| -- | --| --| -- |
| 3.1.2| 54-58 | 16-17 | |
| 3.3(without this PR)| 48-52 |14-15 | |
| 3.3(including this PR)| | | |

## Mobile Browser

Environment: iOS 14.3

|  | BunnyFrameTest | BunnyTransformTest | ModelAnimation |
| -- | --| --|--|
| 3.1.2| 31-33 and reduce to 28-30 | 12-13 | 23-24|
| 3.3(without this PR)| 29-31 | 12-13 | 21-22 |
| 3.3(including this PR)| | | |

2021-07-21 11:19 UTC, shrinktofit commented
# Package Size Report

With features: core and gfx-webgl1

Before: 1, 265KB

After: 1, 311KB

2021-07-21 16:27 UTC, pandamicro approved these changes

2021-07-22 02:59 UTC, pandamicro requested changes

2021-07-22 02:59 UTC, pandamicro commented on cocos/core/animation/animation-clip.ts
> +    }
必要性在哪里？

2021-07-22 02:59 UTC, pandamicro commented on cocos/core/animation/animation-clip.ts
> +        for (const eventData of events) {
遗漏

2021-07-22 02:59 UTC, pandamicro commented on cocos/core/animation/animation-clip.ts
> +        for (const joint of Object.keys(skeletonFrames)) {
遗漏

2021-07-22 02:59 UTC, pandamicro commented on cocos/core/animation/animation-clip.ts
> +                    warn(`Seems like we have animation for ${joint} but are missing its parent joint ${parentJointName} in animation?`);
遗漏

2021-07-22 02:59 UTC, pandamicro commented on cocos/core/animation/compression/compressed-data.ts
> +        for (const curves of this._curves) {
for of

2021-07-22 02:59 UTC, pandamicro commented on cocos/core/animation/compression/compressed-data.ts
> +        for (const track of this._tracks) {
for of

2021-07-22 02:59 UTC, pandamicro commented on cocos/core/animation/compression/compressed-data.ts
> +        for (const curves of this._quatCurves) {
for of

2021-07-22 02:59 UTC, pandamicro commented on cocos/core/animation/compression/compressed-data.ts
> +        for (const track of this._quatTracks) {
for of

2021-07-22 02:59 UTC, pandamicro commented on cocos/core/animation/compression/compressed-data.ts
> +        for (const { type, target, immediate, curves } of compressedTrackEvalStatuses) {
for of and  for of

2021-07-22 02:59 UTC, pandamicro commented on cocos/core/animation/compression/compressed-data.ts
> +        for (const { curves, result } of keysSharedQuatCurvesEvalStatues) {
for of

2021-07-22 02:59 UTC, pandamicro commented on cocos/core/animation/compression/compressed-data.ts
> +        for (const { target, curve } of quatTrackEvalStatuses) {
for of

2021-07-22 02:59 UTC, pandamicro commented on cocos/core/animation/legacy-clip-data.ts
> +// ];
不需要的话就删除

2021-07-22 02:59 UTC, pandamicro commented on cocos/core/animation/legacy-clip-data.ts
> +    }
无意义的 getter setter

2021-07-22 02:59 UTC, pandamicro commented on cocos/core/animation/legacy-clip-data.ts
> +    set commonTargets (value) {
无意义的 getter setter

2021-07-22 02:59 UTC, pandamicro commented on cocos/core/animation/legacy-clip-data.ts
> +        for (const legacyCurve of legacyCurves) {
for of

2021-07-23 03:25 UTC, pandamicro approved these changes

2021-07-23 03:26 UTC, merged