Allow specify playback range for animation state
cocos/cocos-engine pull request #8430
Opened 2021-04-08 05:42 UTC by shrinktofit

Re: cocos-creator/3d-tasks#

Changelog:
 *

2021-04-08 05:42 UTC, shrinktofit commented on cocos/3d/skinned-mesh-renderer/skinned-mesh-renderer.ts
> +        if (comp) { this.setUseBakedAnimation(comp.useBakedAnimation); } else { this.setUseBakedAnimation(false); }
@YunHsiao

2021-04-08 05:57 UTC, YunHsiao commented on cocos/3d/skinned-mesh-renderer/skinned-mesh-renderer.ts
> +        if (comp) { this.setUseBakedAnimation(comp.useBakedAnimation); } else { this.setUseBakedAnimation(false); }
LGTM

2021-04-08 08:01 UTC, gameall3d requested changes

2021-04-08 08:01 UTC, gameall3d commented on cocos/core/animation/animation-state.ts
> +    set playbackRange (value) {
why not add type for value?

2021-04-08 08:40 UTC, gameall3d approved these changes
LGTM

2021-04-12 02:26 UTC, holycanvas approved these changes

2021-04-12 07:25 UTC, merged