Fix deserialize error on simulator.
cocos/cocos-engine pull request #8600
Opened 2021-04-29 13:29 UTC by caryliu1999

2021-04-30 03:26 UTC, jareguo requested changes

2021-04-30 03:26 UTC, jareguo commented on cocos/core/data/deserialize-dynamic.ts
> +                if (!attrs[propName + DEFAULT]) continue;
不应该有这个判断，fastDefine 后都会有 default 才对。

2021-04-30 08:38 UTC, jareguo commented on cocos/core/data/deserialize-dynamic.ts
> +                if (!attrs[propName + DEFAULT]) continue;
![image](https://user-images.githubusercontent.com/1503156/116670350-34dc2100-a9d2-11eb-938a-da57e6869ad2.png)
应该是这里导致的，这里不能直接 setClassName，而是应该
`cc.Class.fastDefine('ForwardPipeline', ForwardPipeline, { pipelineSceneData: null, });`

2021-05-11 02:51 UTC, SantyWang commented
在此 pr 解决，https://github.com/cocos-creator/engine/pull/8624

2021-05-11 02:51 UTC, closed without merging