support SystemEventType.KEYBOARD_DOWN && SystemEventType.KEYBOARD_UP event type
cocos/cocos-engine pull request #8678
Opened 2021-05-16 12:21 UTC by PPpro

Re: cocos-creator/3d-tasks#

Changelog:
 *

2021-05-26 08:40 UTC, PPpro commented on pal/input/native/keyboard.ts
> +            this._eventTarget.emit(SystemEventType.KEYBOARD_UP, inputEvent);
简单说明下，引擎里边不能直接访问 SystemEventType.KEY_DOWN 事件，否则会有一堆警告信息，所以派发事件的时候就直接写字符串 'keydown'

2021-05-26 08:40 UTC, PPpro commented on pal/input/native/keyboard.ts
> +            this._eventTarget.emit(SystemEventType.KEYBOARD_UP, inputEvent);
SystemEventType.KEYBOARD_UP 和 SystemEventType.KEY_UP 是同一个事件，所以不需要做特殊处理了

2021-06-01 10:11 UTC, holycanvas commented on cocos/core/platform/deprecated.ts
> +            return this.type as SystemEventType;
代码提示可能就没了

2021-06-02 03:38 UTC, PPpro commented on cocos/core/platform/deprecated.ts
> +            return this.type as SystemEventType;
改过来了

2021-06-02 03:50 UTC, JayceLai requested changes

2021-06-02 03:50 UTC, JayceLai commented on cocos/core/utils/x-deprecated.ts
> +                Object.defineProperty(owner, deprecatedProp, {
不应该在这里定义对象的属性，因为该对象可能已经有对应的 get 或者 set，这个时候，这里的定义就会覆盖对象原先的行为

我建议把这些扩展到  _defaultGetSet 方法里面

2021-06-02 06:54 UTC, JayceLai requested changes

2021-06-02 06:54 UTC, JayceLai commented on cocos/core/utils/x-deprecated.ts
> +                    set (v) {
这里的 set 可能得判断一下之前的 property 是否可以写入，就是加条 if (descriptor.writable)

2021-06-02 07:18 UTC, JayceLai approved these changes
nice job

2021-06-04 06:21 UTC, PPpro commented on cocos/core/platform/event-manager/index.ts
> +export { SystemEventType } from './event-enum';
防止引擎直接向开发者暴露 TouchEvent MouseEvent KeyboardEvent 和 DeviceEvent

2021-06-04 06:23 UTC, PPpro commented on cocos/core/platform/event-manager/event-enum.ts
> +export type SystemEventTypeUnion = SystemEventType.NO_TYPE | TouchEvent | MouseEvent | KeyboardEvent | DeviceEvent | 'keydown' | NodeEventType;
一些地方需要做统一的类型判断，所以需要 SystemEventTypeUnion

2021-06-04 07:27 UTC, PPpro commented on cocos/core/platform/deprecated.ts
>      },
这个事件是初始化 Event 对象用的，实际上没想好把它放在哪个模块，暂时放在 SystemEventType. NO_TYPE 下吧，反正开发者也不会用到这个枚举

2021-06-07 07:24 UTC, holycanvas commented on cocos/core/platform/event-manager/event-enum.ts
> +     KEY_DOWN = 'keyboarddown',  // NOTE: different value with SystemEventType.KEY_DOWN
缩进好像不太对

2021-06-07 11:06 UTC, merged