optimize WebGLCmdFuncBindStates
cocos/cocos-engine pull request #8705
Opened 2021-05-25 03:15 UTC by YunHsiao

Re: cocos-creator/3d-tasks#

Changelog:
 *

2021-05-25 09:38 UTC, minggo commented
所以主要的优化点是缓存 GL 状态，尽量减少 gl 函数调用是吗？

2021-05-25 11:33 UTC, pandamicro commented
https://github.com/cocos-creator/3d-tasks/issues/7487

2021-05-25 12:01 UTC, pandamicro requested changes
The check removal and data restructure part looks good to me, just follow the rule of adding warning and errors

2021-05-25 12:01 UTC, pandamicro commented on cocos/core/assets/material.ts
> +            console.warn('material already initialized, request aborted');
Use warnID instead

2021-05-25 12:01 UTC, pandamicro commented on cocos/core/renderer/core/pass.ts
> +            console.error('Pass already destroyed');
errorID

2021-05-26 01:42 UTC, YunHsiao commented
> 所以主要的优化点是缓存 GL 状态，尽量减少 gl 函数调用是吗？

主要是那些 dynamic states 原来全是散着传的，函数参数搞了一大坨，而且缓存策略也不太对。
代码质量肯定是有提升的，但不确定这些修改对性能有多少帮助。

2021-05-26 04:33 UTC, pandamicro approved these changes

2021-05-26 04:36 UTC, merged