opt: Node.invalidateChildren
cocos/cocos-engine pull request #8716
Opened 2021-05-26 07:51 UTC by YunHsiao

Re: cocos-creator/3d-tasks#

Changelog:
 *

2021-05-26 12:38 UTC, pandamicro requested changes
webgl2-commands is polluted and not possible to review, please explain what have been done in this file

2021-05-26 12:38 UTC, pandamicro commented on cocos/core/scene-graph/node.ts
>          }
better set `array_a.length = 0` here, avoid potential leak

2021-05-26 12:38 UTC, pandamicro commented on cocos/core/scene-graph/node.ts
> -        if (JSB) bookOfChange.forEach((v, k, m) => { if (k.isValid) k.hasChangedFlags = TransformBit.NONE; });
👍  good job on removing this logic

2021-05-27 02:10 UTC, pandamicro approved these changes

2021-05-27 02:12 UTC, minggo commented
Any logic to free the pool?

2021-05-27 02:16 UTC, minggo commented on cocos/core/renderer/core/pass.ts
> +    set priority (val: RenderPriority) { this._priority = val; PassPool.set(this._handle, PassView.PRIORITY, val); }
Is it better to do pool set only in JSB?

2021-05-27 02:19 UTC, merged