Enumeration extensions for layer v3.3
cocos/cocos-engine pull request #8723
Opened 2021-05-27 03:35 UTC by troublemaker52025

Re: cocos-creator/3d-tasks#

Changelog:
 *

2021-05-27 03:37 UTC, troublemaker52025 commented
@VisualSJ 引擎获取用户设置的自定义 layer 的接口封装完毕，需要编辑器配合填充数据

2021-05-27 09:48 UTC, holycanvas commented on cocos/core/game.ts
> +                const bitNum = log2(layer.value);
为啥要 log2 呢，不能直接传位数么？

2021-05-27 09:48 UTC, holycanvas commented on cocos/core/scene-graph/layers.ts
> +      const value = Layers.getLayerValue(name);
getLayer 和 getLayerValue 感觉有点懵，不知道用哪一个，参考下 unity 的命名？

2021-05-27 10:18 UTC, troublemaker52025 commented on cocos/core/game.ts
> +                const bitNum = log2(layer.value);
从project 读出来的数据  就是按位与后的结果，我这边转成位数。之前的封装要求是传位数，不支持512 1024 这样的值

2021-06-07 07:23 UTC, troublemaker52025 commented on cocos/core/scene-graph/layers.ts
> +      const value = Layers.getLayerValue(name);
目前 unity 只有这两个方法操作 Layers ”Note: LayerMask is a bitmask. Use #LayerMask.GetMask# and #LayerMask.LayerToName# to generate the bitmask. ” 我们也应该使用言简意赅的方法名，并且减少不必要的函数接口

2021-06-14 14:32 UTC, pandamicro requested changes

2021-06-14 14:32 UTC, pandamicro commented on cocos/core/scene-graph/layers.ts
> +   * @param layer Name's layer
parameter name should be after `@param` decorator, 

`@param name layer's name`

2021-06-14 14:32 UTC, pandamicro commented on cocos/core/scene-graph/layers.ts
> +   * @param name Layer's name
Wrong param comment

2021-06-14 14:32 UTC, pandamicro commented on cocos/core/scene-graph/layers.ts
> +   * @param name Layer's name
Wrong param comment

2021-06-14 14:32 UTC, pandamicro commented on cocos/core/game.ts
> +                const bitNum = log2(layer.value);
这里没什么问题

2021-06-15 03:48 UTC, pandamicro approved these changes

2021-06-15 03:48 UTC, merged