V3.1.2 zxx43 particle to fix https://github.com/cocos-creator/3d-tasks/issues/7421
cocos/cocos-engine pull request #8751
Opened 2021-06-02 09:36 UTC by zxx43

Re: cocos-creator/3d-tasks#

Changelog:
 *

2021-06-03 06:11 UTC, caryliu1999 approved these changes

2021-06-03 14:12 UTC, pandamicro commented
How do you reverse sync material changes in ParticleSystem to ParticleSystemRendererData ?
Repetitive data will definitely cause sync issue, either you should remove repetitive data or you should make sure all modifications are synced.
I personally suggest simply set render data's particle system in creation, then you won't need to check whether particle system exist

2021-06-07 10:10 UTC, zxx43 commented
> 
> 
> How do you reverse sync material changes in ParticleSystem to ParticleSystemRendererData ?
> Repetitive data will definitely cause sync issue, either you should remove repetitive data or you should make sure all modifications are synced.
> I personally suggest simply set render data's particle system in creation, then you won't need to check whether particle system exist

Now ParticleSystem will be obtained in onFocusInEditor function.

2021-06-08 02:37 UTC, pandamicro requested changes

2021-06-08 02:37 UTC, pandamicro commented on cocos/particle/renderer/particle-system-renderer-data.ts
> +        this._particleSystem.processor.onInit(this._particleSystem);
这里一定要注意，涉及到 processor 的重新创建和 init，假设真的不同的 ParticleSystem 组件对同一个 ParticleSystemRenderData 调用 onInit 会导致 processor 残留在 renderScene 中，参考 ParticleSystem 里面的 _attachToScene。
这种行为的后果不可预估，建议直接禁止替换 _particleSystem，增加一个 error，如果 this._particleSystem 已经存在的情况下调用 create 和 onInit，直接报错

2021-06-08 03:30 UTC, zxx43 commented on cocos/particle/renderer/particle-system-renderer-data.ts
> +        this._particleSystem.processor.onInit(this._particleSystem);
> 
> 
> 这里一定要注意，涉及到 processor 的重新创建和 init，假设真的不同的 ParticleSystem 组件对同一个 ParticleSystemRenderData 调用 onInit 会导致 processor 残留在 renderScene 中，参考 ParticleSystem 里面的 _attachToScene。
> 这种行为的后果不可预估，建议直接禁止替换 _particleSystem，增加一个 error，如果 this._particleSystem 已经存在的情况下调用 create 和 onInit，直接报错

此处particle system只能有一个，所以create和onInit只能跑一个；如果particle system不为null，后续ParticleSystemRenderData创建函数就不跑了

2021-06-08 03:38 UTC, closed without merging