add Native Pcf for v3.1.2
cocos/cocos-engine pull request #8867
Opened 2021-06-23 10:45 UTC by troublemaker52025

Re: cocos-creator/3d-tasks#

Changelog:
 *

2021-06-23 10:50 UTC, troublemaker52025 commented
还需要关联原生修改

2021-06-24 03:53 UTC, jk20012001 approved these changes

2021-06-24 04:17 UTC, pandamicro requested changes

2021-06-24 04:17 UTC, pandamicro commented on cocos/core/pipeline/pipeline-ubo.ts
> +            }
这里 sampler 是不是反了，soft 应该用 linear，hard 用 point

2021-06-24 04:17 UTC, pandamicro commented on cocos/core/pipeline/render-additive-light-queue.ts
> +                            descriptorSet.bindSampler(UNIFORM_SPOT_LIGHTING_MAP_TEXTURE_BINDING, globalDSManager.linearSampler);
同上

2021-06-24 04:17 UTC, pandamicro commented on editor/assets/chunks/cc-shadow-map-base.chunk
> +  float CCGetShadowFactorNative (vec4 shadowPos) {
CCGetShadowFactorSoft

2021-06-24 04:17 UTC, pandamicro commented on editor/assets/chunks/cc-shadow-map-base.chunk
> +  float CCGetSpotLightShadowFactorX9 (vec4 shadowPos, vec3 worldPos) {
删除 X5 和 X9

2021-06-24 04:17 UTC, pandamicro commented on editor/assets/chunks/cc-shadow-map-base.chunk
> +  float CCGetSpotLightShadowFactorX1 (vec4 shadowPos, vec3 worldPos) {
CCGetSpotLightShadowHard

2021-06-24 04:17 UTC, pandamicro commented on editor/assets/chunks/cc-shadow-map-base.chunk
> +#define CC_SPOT_SHADOW_FACTOR_BASE(finalColor, shadowPos, worldPos, lightPos, normal)                \
这里为什么要改名？我们内置 chunk 的改名都可能导致材质不兼容

2021-06-24 06:12 UTC, troublemaker52025 commented on cocos/core/pipeline/pipeline-ubo.ts
> +            }
NativePCF 不需要使用线性差值采样，要点对点采样。线性差值需要在 pcf 算法里做每个像素的过渡

2021-06-24 06:21 UTC, pandamicro commented
做一下 effect 的字符串升级

2021-06-24 07:42 UTC, pandamicro approved these changes

2021-06-24 08:59 UTC, merged