update_AO_SPECULAR_LINEAR-VERTEX-COLOR v3.3
cocos/cocos-engine pull request #8875
Opened 2021-06-24 07:05 UTC by linshunjun

https://user-images.githubusercontent.com/49218738/123217452-2c4d2600-d4fd-11eb-99f5-c36cbc4bd35e.mp4

Re: cocos-creator/3d-tasks#

Changelog:
 *

2021-06-24 07:07 UTC, pandamicro requested changes

2021-06-24 07:07 UTC, pandamicro commented on editor/assets/chunks/shading-standard-base.chunk
> +  // 0.04 == 0.08*tex.a(0-1)*value(0-1)   valuedefault=0.5
Do not add this kind of comment, all our code is visible to developers, try to be serious about it

2021-06-24 07:19 UTC, pandamicro approved these changes

2021-06-25 02:11 UTC, linshunjun commented
https://github.com/cocos-creator/3d-tasks/issues/7788

2021-06-25 02:40 UTC, jk20012001 approved these changes

2021-06-25 06:01 UTC, merged

2021-07-19 08:27 UTC, linshunjun commented
https://github.com/cocos-creator/3d-tasks/issues/7790