V3.1.2 rotation fix
cocos/cocos-engine pull request #8920
Opened 2021-06-30 10:36 UTC by zxx43

Re: cocos-creator/3d-tasks#

Changelog:
 *

2021-07-01 05:44 UTC, caryliu1999 commented on cocos/particle/animator/rotation-overtime.ts
> +                this._quatRot.set(this._quatRot.x, this._quatRot.y, this._quatRot.z, this._quatRot.w);
p.particleSystem.processor.getInfo().renderMode 可以只获取一次

2021-07-01 05:45 UTC, caryliu1999 commented on cocos/particle/animator/rotation-overtime.ts
> +            Quat.fromEuler(p.deletaQuat, 0, 0, this.z.evaluate(normalizedTime, rotationRand)! * dt * r2d);
r2d = 180.0 / Math.PI; 改为一个方法外的常量吧

2021-07-01 07:17 UTC, zxx43 commented on cocos/particle/animator/rotation-overtime.ts
> +                this._quatRot.set(this._quatRot.x, this._quatRot.y, this._quatRot.z, this._quatRot.w);
已改

2021-07-01 07:17 UTC, zxx43 commented on cocos/particle/animator/rotation-overtime.ts
> +            Quat.fromEuler(p.deletaQuat, 0, 0, this.z.evaluate(normalizedTime, rotationRand)! * dt * r2d);
已改

2021-07-01 10:46 UTC, caryliu1999 commented on cocos/particle/particle.ts
> +import { Color, Vec3, Mat4, Quat } from '../core/math';
这个 Mat3 导入的不正确

2021-07-01 10:49 UTC, zxx43 commented on cocos/particle/particle.ts
> +import { Color, Vec3, Mat4, Quat } from '../core/math';
去掉了

2021-07-01 12:02 UTC, caryliu1999 approved these changes

2021-07-05 12:27 UTC, SantyWang commented on cocos/particle/animator/rotation-overtime.ts
> +import { Mat3 } from '@cocos/cannon';
这个 import 有问题

2021-07-06 06:34 UTC, zxx43 commented on cocos/particle/animator/rotation-overtime.ts
> +import { Mat3 } from '@cocos/cannon';
已移除

2021-07-15 06:02 UTC, zxx43 commented
[changjing_TEST.zip](https://github.com/cocos-creator/engine/files/6820243/changjing_TEST.zip)
测试用例

2021-07-23 02:26 UTC, zxx43 commented
测试用例：[NewProject-001.zip](https://github.com/cocos-creator/engine/files/6866288/NewProject-001.zip)
cpu粒子用material.mtl材质 gpu粒子用material-particle-gpu.mtl材质

2021-07-23 05:48 UTC, holycanvas commented on cocos/particle/animator/rotation-overtime.ts
> +                this._quatRot.set(this._quatRot.x, this._quatRot.y, this._quatRot.z, this._quatRot.w);  //      vec3 rotEuler = a_texCoord2;
看起来是无效的设置

2021-07-23 06:08 UTC, zxx43 commented on cocos/particle/animator/rotation-overtime.ts
> +                this._quatRot.set(this._quatRot.x, this._quatRot.y, this._quatRot.z, this._quatRot.w);  //      vec3 rotEuler = a_texCoord2;
去掉了

2021-07-23 07:05 UTC, holycanvas approved these changes

2021-07-23 11:44 UTC, pandamicro requested changes

2021-07-23 11:44 UTC, pandamicro commented on cocos/particle/animator/rotation-overtime.ts
> +        p.deletaMat = Mat4.fromQuat(p.deletaMat, p.deltaQuat);
deltaMat

2021-07-23 11:44 UTC, pandamicro commented on cocos/particle/animator/rotation-overtime.ts
> +    private _processRoation (p: Particle, r2d: number) {
_processRotation

2021-07-23 11:44 UTC, pandamicro commented on cocos/particle/particle-system.ts
> -                    this._needRefresh = false;
如何保证发射的粒子位置是可以被更新的呢？如果拖动粒子系统，粒子是否能正常跟随？

2021-07-23 11:44 UTC, pandamicro commented on editor/assets/chunks/particle-vs-gpu.chunk
> +    return x == 0.0 ? sign(y) * 3.1416 * 0.5 : atan(y, x);
文件缩进不统一，全部都用两个空格做缩进

2021-07-23 13:11 UTC, zxx43 commented on cocos/particle/particle-system.ts
> -                    this._needRefresh = false;
> 
> 
> 如何保证发射的粒子位置是可以被更新的呢？如果拖动粒子系统，粒子是否能正常跟随？

改到了emit里，可以确保跟随

2021-07-23 13:21 UTC, zxx43 commented on editor/assets/chunks/particle-vs-gpu.chunk
> +    return x == 0.0 ? sign(y) * 3.1416 * 0.5 : atan(y, x);
已改

2021-07-23 13:21 UTC, zxx43 commented on cocos/particle/animator/rotation-overtime.ts
> +    private _processRoation (p: Particle, r2d: number) {
已改

2021-07-23 13:21 UTC, zxx43 commented on cocos/particle/animator/rotation-overtime.ts
> +        p.deletaMat = Mat4.fromQuat(p.deletaMat, p.deltaQuat);
已改

2021-07-23 14:16 UTC, pandamicro approved these changes

2021-07-23 14:17 UTC, merged