V3.1.2 particle2d bug fix
cocos/cocos-engine pull request #8924
Opened 2021-07-01 03:55 UTC by zxx43

Re: cocos-creator/3d-tasks#

Changelog:
 *

2021-07-01 10:08 UTC, pandamicro commented on cocos/particle-2d/particle-system-2d.ts
> +    public updateColor (val:Color) {
why set color should affect start and end color, I don't think it's necessary

2021-07-01 10:08 UTC, pandamicro commented on cocos/particle-2d/particle-system-2d.ts
> +        if (val) { this._startPreview(); } else { this._stopPreview(); }
What's the problem with current preview

2021-07-01 10:11 UTC, zxx43 commented on cocos/particle-2d/particle-system-2d.ts
> +        if (val) { this._startPreview(); } else { this._stopPreview(); }
https://github.com/cocos-creator/3d-tasks/issues/7031 设置 preview 为false的时候，应该取消在编辑器中的渲染。目前的情况是勾不勾选 preview 都会在选中该组件时渲染

2021-07-01 10:12 UTC, zxx43 commented on cocos/particle-2d/particle-system-2d.ts
> +    public updateColor (val:Color) {
https://github.com/cocos-creator/3d-tasks/issues/7031 设置 color ,粒子没有颜色变化

2021-07-01 10:39 UTC, caryliu1999 commented on cocos/particle-2d/particle-system-2d.ts
>      @serializable
修改序列化数据需要升级吧？

2021-07-01 11:00 UTC, pandamicro commented on cocos/particle-2d/particle-system-2d.ts
> +        if (val) { this._startPreview(); } else { this._stopPreview(); }
应该保留 preview 属性，使用 notify decorator

2021-07-01 11:05 UTC, pandamicro commented
Rendererable2D updateColor 的用法麻烦 @LinYunMo 看下

2021-07-12 08:13 UTC, zxx43 commented on cocos/particle-2d/particle-system-2d.ts
>      @serializable
> 
> 
> 修改序列化数据需要升级吧？

用formerlySerializedAs替代旧字段了

2021-07-12 08:14 UTC, zxx43 commented on cocos/particle-2d/particle-system-2d.ts
> +    public updateColor (val:Color) {
> 
> 
> why set color should affect start and end color, I don't think it's necessary

2d粒子color字段隐藏了

2021-07-12 08:14 UTC, zxx43 commented on cocos/particle-2d/particle-system-2d.ts
> +        if (val) { this._startPreview(); } else { this._stopPreview(); }
> 
> 
> 应该保留 preview 属性，使用 notify decorator

用formerlySerializedAs替代原来的serializable

2021-07-13 16:06 UTC, pandamicro requested changes

2021-07-13 16:06 UTC, pandamicro commented on cocos/particle-2d/particle-system-2d.ts
> +        this._dict = dict;
这样做太浪费了，如果只是想保存 blend state，单独存下来就可以了

2021-07-13 16:06 UTC, pandamicro commented on cocos/particle-2d/particle-system-2d.ts
> +    @visible(() => false)
直接 `@visible(false)` 不行吗？

2021-07-13 16:06 UTC, pandamicro commented on cocos/particle-2d/particle-system-2d.ts
> +        this._dict = dict;
我看了一下基类有 this._srcBlendFactor，this._dstBlendFactor 数据结构，沿用这两个数据 结构保存即可。

2021-07-13 16:06 UTC, pandamicro commented on cocos/particle-2d/particle-system-2d.ts
> +        // this._dstBlendFactor = parseInt(dict.blendFuncDestination || BlendFactor.ONE_MINUS_SRC_ALPHA);
保留这两段，在后面直接使用这两个属性 即可

2021-07-14 01:41 UTC, zxx43 commented on cocos/particle-2d/particle-system-2d.ts
> +    @visible(() => false)
不行，直接用报错

2021-07-14 01:42 UTC, zxx43 commented on cocos/particle-2d/particle-system-2d.ts
> +        // this._dstBlendFactor = parseInt(dict.blendFuncDestination || BlendFactor.ONE_MINUS_SRC_ALPHA);
这边只是消除warning，如果用原来的方法也是可以的

2021-07-14 07:03 UTC, zxx43 commented on cocos/particle-2d/particle-system-2d.ts
> +        this._dict = dict;
已经还原了

2021-07-14 15:20 UTC, pandamicro commented on cocos/particle-2d/particle-system-2d.ts
> +        this._dict = dict;
这里没有必要保存 dict，会导致不必要的内存浪费

2021-07-15 02:16 UTC, zxx43 commented on cocos/particle-2d/particle-system-2d.ts
> +        this._dict = dict;
移除了

2021-07-15 03:21 UTC, LinYunMo requested changes

2021-07-15 03:21 UTC, LinYunMo commented on cocos/2d/framework/renderable-2d.ts
> +        }
这里的判断没有意义，无法避免后续的计算

2021-07-15 03:21 UTC, LinYunMo commented on cocos/2d/framework/renderable-2d.ts
> +        }
如果确定这里的透明度级联不合适，那可以在子类中重写此方法，但要保证能够传递级联信息。

2021-07-15 03:40 UTC, zxx43 commented on cocos/2d/framework/renderable-2d.ts
> +        }
退回了

2021-07-15 04:11 UTC, pandamicro approved these changes

2021-07-15 04:12 UTC, merged