widget misc bug fix
cocos/cocos-engine pull request #8970
Opened 2021-07-13 09:02 UTC by LinYunMo

Re: https://github.com/cocos-creator/3d-tasks/issues/7169
Re: https://github.com/cocos-creator/3d-tasks/issues/7850

2021-07-20 16:15 UTC, pandamicro requested changes

2021-07-20 16:15 UTC, pandamicro commented on cocos/core/director.ts
> +        }
监听 EVENT_BEFORE_SCENE_LAUNCH 事件来处理

2021-07-22 02:06 UTC, LinYunMo commented on cocos/core/director.ts
> +        }
这个无法在 EVENT_BEFORE_SCENE_LAUNCH 中处理，这时还没有 scene 的赋值，无法遍历子节点，且这时候的 dirty 尚未初始化

2021-07-22 07:53 UTC, LinYunMo commented
widget 默认值 dirty 的问题，直接改为 false 理论上是可以直接行得通的，开始运行->canvas适配->触发 sizeChange->子节点和它对齐，但问题是canvas的对齐是在其 preload 中 手动调用了立即对齐操作，而这个时候，子节点的监听还未注册，导致子节点无法对齐，有一个比较hack 的改法，就是在canvas更新完widget之后再将其dirty设为true，这样能够保证能触发子节点的更新，但坏处是canvas的第二次更新操作是没有用的。
![企业微信截图_16269398697169](https://user-images.githubusercontent.com/42071583/126606111-567a2cda-cb18-4c74-b748-b2a4f362886b.png)

2021-07-22 07:53 UTC, LinYunMo commented
但是也有另外一种改法，由于编辑器的场景打开事件是再执行完全部 runSceneImmediate 之后再进行的，所以这时候在 EVENT_AFTER_SCENE_LAUNCH 中处理是能修复这个问题的，但是这个预先更新一次的操作和其时机还是包含了规避问题的隐含规则
![企业微信截图_16269403288575](https://user-images.githubusercontent.com/42071583/126606158-b2aa80b3-9527-4521-9af1-803e66fc5113.png)

2021-07-22 08:23 UTC, pandamicro approved these changes

2021-07-22 08:23 UTC, merged