optimize interface in screen module
cocos/cocos-engine pull request #9176
Opened 2021-08-13 07:09 UTC by PPpro

Re: cocos-creator/3d-tasks#

Changelog:
 *

2021-09-13 07:43 UTC, PPpro commented
等原生支持后再合并这个 pr

2021-10-13 10:12 UTC, SantyWang approved these changes

2021-10-13 15:09 UTC, pandamicro requested changes
Well done, the view and screen implementation seems much more elegant

2021-10-13 15:09 UTC, pandamicro commented on cocos/core/platform/screen.ts
> +                warn('Invalid setting screen.resolutionScale, director.root has not been defined.');
Use `warnID`

Failed to set shading scale, director.root is invalid.

2021-10-13 15:09 UTC, pandamicro commented on cocos/core/platform/screen.ts
> +    public convertToCocosScreenSpace (nativeScreenX: number, nativeScreenY: number, out: Vec2 = new Vec2(0, 0)) {
convertToScreenSpace is enough

2021-10-13 15:09 UTC, pandamicro commented on cocos/core/platform/sys.ts
> +        height: windowSize.height,
Please share with `windowSize` object directly to avoid manual update

`windowPixelResolution: windowSize`

2021-10-13 15:09 UTC, pandamicro commented on cocos/ui/editbox/edit-box-impl.ts
> +        const dpr = screenAdapter.devicePixelRatio;
What would happen wrong currently?

2021-10-13 15:09 UTC, pandamicro commented on pal/screen-adapter/minigame/screen-adapter.ts
> +    private _cbToUpdateFrameBuffer?: () => void;
put private property together after all public properties including getter setter

2021-10-13 15:09 UTC, pandamicro commented on pal/screen-adapter/minigame/screen-adapter.ts
> +    public init (cbToRebuildFrameBuffer: () => void) {
constructor and init functions should be put after all properties including public, private and protected

2021-10-13 15:09 UTC, pandamicro commented on pal/screen-adapter/native/screen-adapter.ts
> +    private _cbToUpdateFrameBuffer?: () => void;
Same comment as before

2021-10-13 15:09 UTC, pandamicro commented on pal/screen-adapter/native/screen-adapter.ts
> +    public init (cbToRebuildFrameBuffer: () => void) {
Also order issue

2021-10-13 15:09 UTC, pandamicro commented on pal/screen-adapter/native/screen-adapter.ts
> +    private _updateResolution () {
order issue

2021-10-13 15:09 UTC, pandamicro commented on pal/screen-adapter/web/screen-adapter.ts
> +    public init (cbToRebuildFrameBuffer: () => void) {
Same, please reorder properties, functions

2021-10-13 15:09 UTC, pandamicro commented on pal/screen-adapter/native/screen-adapter.ts
> +            size.height /= this.devicePixelRatio;
About VK/MTL orientation issue, check the timing of `onResize` and `onOrientationChanged` callback is invoked, could be mismatched

2021-10-13 15:09 UTC, pandamicro commented on pal/screen-adapter/native/screen-adapter.ts
> +        this._updateResolution();
About VK/MTL orientation issue, on init, the screen orientation could still not be updated yet, try to delay the timing to update resolution

2021-10-14 07:08 UTC, PPpro commented on cocos/ui/editbox/edit-box-impl.ts
> +        const dpr = screenAdapter.devicePixelRatio;
nothing wrong， we just don't want to access ` screenAdapter` in edit-box-impl, 
but we have to for now, because there is no `screen. devicePixelRatio` property

2021-10-14 07:40 UTC, PPpro commented on cocos/core/platform/sys.ts
> +        height: windowSize.height,
We init `sys. windowPixelResolution` here, and actually share `windowSize` in the deprecate implementation

2021-10-14 07:41 UTC, PPpro commented on cocos/core/platform/screen.ts
> +    public convertToCocosScreenSpace (nativeScreenX: number, nativeScreenY: number, out: Vec2 = new Vec2(0, 0)) {
`convertToCocosScreenSpace` need to be removed

2021-10-14 08:46 UTC, pandamicro approved these changes

2021-10-14 08:46 UTC, pandamicro commented on pal/screen-adapter/minigame/screen-adapter.ts
> +        console.warn('Setting orientation is not supported yet.');
warnID

2021-10-14 14:16 UTC, merged