Add easing method to quat curve
cocos/cocos-engine pull request #9179
Opened 2021-08-13 12:29 UTC by shrinktofit

Re: cocos-creator/3d-tasks#

Changelog:
 * Add easing method to quat curve keyframe to compatible with legacy easing methods

2021-08-14 10:30 UTC, gameall3d requested changes

2021-08-14 10:30 UTC, gameall3d commented on cocos/core/data/utils/asserts.ts
> +        debugger;
这个不需要吧？

2021-08-16 01:56 UTC, shrinktofit commented on cocos/core/data/utils/asserts.ts
> +        debugger;
需要，调试的时候方便点

2021-08-16 02:23 UTC, gameall3d approved these changes
LGTM

2021-08-16 06:54 UTC, merged