Curve document
cocos/cocos-engine pull request #9228
Opened 2021-08-22 04:57 UTC by shrinktofit

Re: cocos-creator/3d-tasks#

Changelog:
 *

2021-08-22 06:31 UTC, gameall3d requested changes

2021-08-22 06:31 UTC, gameall3d commented on cocos/core/curves/curve.ts
> + * 每个关键帧都可以指定插值模式以表示如何进行插值，每个关键帧的插值模式都可以是各不相同的。
“每个关键帧都可以指定当前关键帧到下一个关键帧的插值模式，它表示了从当前帧数值变化到下一帧数值所采用的插值方法，每个关键帧的插值模式都可以是各不相同的。“

2021-08-22 06:31 UTC, gameall3d commented on cocos/core/curves/curve.ts
> + * 由于每个关键帧都可能作为“前一关键帧”或“后一关键帧”，且不同区间上的插值是互不相关的，
当计算两帧之间的三次贝塞尔曲线时，会取前一帧的右切线、右切线权重来计算出第一个控制点，会取后一帧的左切线、左切线权重来计算出第二个控制点。

2021-08-22 06:44 UTC, gameall3d approved these changes
LGTM

2021-09-06 15:15 UTC, pandamicro approved these changes

2021-09-06 15:15 UTC, merged