Add automatically calculate the shadowDistance for v3.3.1
cocos/cocos-engine pull request #9319
Opened 2021-09-11 08:09 UTC by troublemaker52025

Re: cocos-creator/3d-tasks#

Changelog:
 *

2021-09-11 16:32 UTC, pandamicro requested changes
总体改动还是很大，感觉比较 fragile，所以 3.3.1 就不合并了

2021-09-11 16:32 UTC, pandamicro commented on cocos/core/renderer/scene/shadows.ts
> +    }
不需要暴露给用户

2021-09-11 16:32 UTC, pandamicro commented on cocos/core/renderer/scene/shadows.ts
> +        this.firstSetCSM = shadowsInfo.autoAdapt;
不应该重新引入 autoAdapt，应该在场景迁移阶段去判断是否存在 autoAdapt，之前版本设置为 true，那么就添加一个 _firstSetCSM 为 true 的属性

2021-09-11 16:32 UTC, pandamicro commented on cocos/core/renderer/scene/shadows.ts
> +        this.firstSetCSM = shadowsInfo.autoAdapt;
这样才能保证只迁移一次

2021-09-13 03:19 UTC, troublemaker52025 commented
不合并到 v3.3.1

2021-09-22 02:56 UTC, closed without merging