parent 修改的时候，opacity 状态没有设置，导致渲染数据没有更新
cocos/cocos-engine pull request #9322
Opened 2021-09-11 11:50 UTC by VisualSJ

Re: cocos-creator/3d-tasks#

Changelog:
 *

2021-09-11 11:51 UTC, VisualSJ commented
感觉还有遗漏的，级联的属性状态应该都需要重制。

2021-09-11 12:05 UTC, jareguo commented on cocos2d/core/utils/base-node.js
> +            this._renderFlag |= RenderFlow.FLAG_OPACITY_COLOR;
照你这么改的话（引擎），应该不需要 undo 也会出问题呀？现在如果不 undo，编辑器里效果是对的。

2021-09-11 12:17 UTC, VisualSJ commented on cocos2d/core/utils/base-node.js
> +            this._renderFlag |= RenderFlow.FLAG_OPACITY_COLOR;
确实是这样的，我写了下面的代码，也会出现 opacity 不更新的情况。
```typescript
var node = cc.find('Canvas/New Sprite');
node.parent = cc.find('Canvas/New Node');
```

2021-09-11 13:25 UTC, VisualSJ commented on cocos2d/core/utils/base-node.js
> +            this._renderFlag |= RenderFlow.FLAG_OPACITY_COLOR;
![image](https://user-images.githubusercontent.com/7113508/132949354-8f7e5e61-efc9-4002-8a1f-17be90479123.png)
编辑器内操作没问题是因为先设置成了 null，再设置 parent，这种情况下，所有 flag 都会自动加上。去掉 null 的这一步，就会出现 opacity 没有重现的情况。

2021-09-11 13:28 UTC, jareguo approved these changes

2021-09-11 15:38 UTC, pandamicro requested changes

2021-09-11 15:38 UTC, pandamicro commented on cocos2d/core/utils/base-node.js
> +            this._renderFlag |= RenderFlow.FLAG_OPACITY_COLOR;
查了一下 `WORLD_TRANSFORM` 这个同样是级联的 flag 是在 [onHierarchyChange](https://github.com/cocos-creator/engine/blob/7c419f9ed89a249cd805da84e2687992f89e1f13/cocos2d/core/CCNode.js#L1764) 里面修改的，`FLAG_OPACITY_COLOR` 应该在同一个地方

2021-10-06 01:00 UTC, VisualSJ commented
已更新

2021-10-07 05:28 UTC, SantyWang approved these changes

2021-10-08 05:39 UTC, pandamicro approved these changes

2021-10-08 05:39 UTC, merged