dirty local ubo when lightmap info update
cocos/cocos-engine pull request #9328
Opened 2021-09-16 03:47 UTC by MSoft1115

Re: cocos-creator/3d-tasks#

Changelog:
 *

2021-09-16 09:10 UTC, minggo commented on cocos/core/renderer/scene/model.ts
> +        this._transformUpdated = true;
哪里改了 transform 呢？

2021-09-18 09:31 UTC, MSoft1115 commented on cocos/core/renderer/scene/model.ts
> +        this._transformUpdated = true;
没有改，我看了代码，只有_transformUpdated才能触发local ubo的变更

2021-09-22 13:13 UTC, minggo commented on cocos/core/renderer/scene/model.ts
> +        this._transformUpdated = true;
那不能这么改吧。现在的问题是 lighting map 没被更新到 local ubo 是吧？

@troublemaker52025 也看一下吧。

2021-09-23 02:18 UTC, troublemaker52025 commented on cocos/core/renderer/scene/model.ts
> +        this._transformUpdated = true;
修改这个标志位，会让 local ubo 一直更新。目前这类问题的修改是这样的:

`this.node.invalidateChildren(TransformBit.POSITION);`

修改父节点的标志位，使子节点及下 model 更新 ubo && transform

2021-09-23 03:07 UTC, pandamicro commented on cocos/core/renderer/scene/model.ts
> +        this._transformUpdated = true;
这里更新的是 lightmap UV UBO，不要用 transform 机制，重点在于 model.updateUBOs 里面的 _transformUpdated 判断有问题，不应该只依赖这个判断来更新 UBO。我觉得要么改 updateUBOs 机制，要么提供手动更新 UBO 的 API

2021-09-23 03:09 UTC, pandamicro commented on cocos/core/renderer/scene/model.ts
> +        this._transformUpdated = true;
> 修改这个标志位，会让 local ubo 一直更新

不会一直更新，更新一次就会设置为 false 了，别瞎说

2021-09-23 03:43 UTC, pandamicro requested changes

2021-09-23 03:43 UTC, pandamicro commented on cocos/core/renderer/scene/model.ts
> +        this._transformUpdated = true;
看了一下 LocalUBO 的结构

```
public static readonly LAYOUT = new UniformBlock(SetIndex.LOCAL, UBOLocal.BINDING, UBOLocal.NAME, [
    new Uniform('cc_matWorld', Type.MAT4, 1),
    new Uniform('cc_matWorldIT', Type.MAT4, 1),
    new Uniform('cc_lightingMapUVParam', Type.FLOAT4, 1),
], 1);
```

@MSoft1115  建议修改 `_transformUpdated` 为 `_dataUpdated`，然后在这里修改 `this._transformUpdated = true` 就比较自然了。 
@minggo @YunHsiao

2021-09-23 03:44 UTC, YunHsiao commented on cocos/core/renderer/scene/model.ts
> +        this._transformUpdated = true;
我没问题，记得同步原生

2021-09-23 03:47 UTC, minggo commented on cocos/core/renderer/scene/model.ts
> +        this._transformUpdated = true;
我也同意。不过最好别叫 _dataUpdated，意思不够清晰。不如直接是 _localBufferDataDirty

2021-09-30 07:59 UTC, closed without merging