optimize render texture
cocos/cocos-engine pull request #9342
Opened 2021-09-17 12:23 UTC by holycanvas

Re: cocos-creator/3d-tasks#

Changelog:
 *

2021-09-17 12:31 UTC, holycanvas commented on cocos/core/assets/render-texture.ts
> +        if (this._width !== val) {
感觉不能运行时动态调整宽高不太满足需求，这次开放了这个接口

2021-09-17 12:31 UTC, holycanvas commented on cocos/core/builtin/builtin-res-mgr.ts
> +        if (TEST) return Promise.resolve();
内置资源中用到了一些 CanvasContext2D 的 API，导致测试环境还是跑不起来，暂时先跳过初始化内置资源，我们不应该在上层这里使用任何 platform specific 的 API，后续可以优化为 TypedArray

2021-09-17 12:31 UTC, holycanvas commented on cocos/core/director.ts
> -        // The test environment does not currently support the renderer
去掉之前的 hack

2021-09-17 12:31 UTC, holycanvas commented on cocos/core/gfx/empty/empty-device.ts
> +legacyCC.EmptyDevice = EmptyDevice;
之前这里遗漏了导出，初始化的地方找不到

2021-09-18 02:13 UTC, YunHsiao commented on cocos/core/assets/render-texture.ts
> +        if (this._width !== val) {
可以给 resize 函数，但不要封装成 setter 吧，这样用起来没有轻重，太容易被滥用了

2021-09-18 02:14 UTC, pandamicro requested changes
Headless mode 和 render texture opt 分开把，这两个都是比较重要的

2021-09-18 02:14 UTC, pandamicro commented on cocos/core/assets/render-texture.ts
> +        if (this._width !== val) {
resize 会引起 GPU 资源更新，width 和 height 一般都是一起更新的，建议开放 resize 接口， width 和 height 是只读

2021-09-18 02:15 UTC, YunHsiao approved these changes

2021-09-18 04:02 UTC, pandamicro approved these changes

2021-09-18 04:02 UTC, pandamicro commented on cocos/core/assets/render-texture.ts
> +        this._height = Math.floor(clamp(height, 1, 2048));
需要增加一个提示

2021-09-18 04:04 UTC, merged