Add Method: Whether the audio is playing
cocos/cocos-engine pull request #9372
Opened 2021-09-23 07:38 UTC by finscn

判断音乐是否处于播放状态 是一个常用的需求,  该api提供一个更简短的方式来实现.

否则开发者要自己写很长的一段: 
```
cc.audioEngine.getState(audioID) === cc.audioEngine.AudioState.PLAYING
```

2021-11-23 09:47 UTC, PPpro requested changes

2021-11-23 09:47 UTC, PPpro commented on cocos2d/audio/CCAudioEngine.js
> +        return this.getState(audioID) === this.AudioState.PLAYING
```suggestion
        return this.getState(audioID) === this.AudioState.PLAYING;
```

2021-12-10 06:08 UTC, finscn commented
@PPpro 改好了

2021-12-10 06:09 UTC, PPpro approved these changes

2022-02-23 06:17 UTC, merged