forwardpipeline supports fxaa
cocos/cocos-engine pull request #9387
Opened 2021-09-24 08:52 UTC by GengineJS

2021-09-24 09:15 UTC, minggo commented on cocos/core/pipeline/common/common-pipeline-scene-data.ts
> + import { PipelineSceneData } from '../pipeline-scene-data';
这个文件和 PipelineSceneData 是什么关系？

2021-09-24 09:17 UTC, GengineJS commented on cocos/core/pipeline/common/common-pipeline-scene-data.ts
> + import { PipelineSceneData } from '../pipeline-scene-data';
是继承关系，提取了deferred与forward共用的部分

2021-09-24 09:17 UTC, minggo commented on cocos/core/pipeline/common/common-pipeline-scene-data.ts
> + export class CommonPipelineSceneData extends PipelineSceneData {
额，有点看不懂这两个类的关系啊。PipelineSceneData 从名字看不就是 pipeline 共用的吗？

2021-09-24 09:19 UTC, minggo commented on cocos/core/pipeline/forward/forward-pipeline.ts
> +        inputAssemblerDataOffscreen = this._createQuadInputAssembler();
这个逻辑有点奇怪，刚 new 完就重新赋值。

2021-09-24 09:21 UTC, GengineJS commented on cocos/core/pipeline/common/common-pipeline-scene-data.ts
> + export class CommonPipelineSceneData extends PipelineSceneData {
这个类主要提取了_postprocessMaterial，forward在开启fxaa的时候会用一下，如果不开启fxaa就没用到，所以就没放到PipelineSceneData里

2021-09-24 09:24 UTC, GengineJS commented on cocos/core/pipeline/forward/forward-pipeline.ts
> +        inputAssemblerDataOffscreen = this._createQuadInputAssembler();
我改一下，没太注意

2021-09-24 09:25 UTC, minggo commented on cocos/core/pipeline/render-pipeline.ts
> +}
InputAssembler 不是就包含了 IB、VB 了吗？

2021-09-24 09:36 UTC, GengineJS commented on cocos/core/pipeline/render-pipeline.ts
> +}
这是是deferred那边遗留的，应该是为了方便访问，比如inputAssemblerDataOnscreen.quadIB,就不需要inputAssemblerDataOnscreen.quadIA.indexBuffer

2021-09-24 09:44 UTC, minggo commented on cocos/core/pipeline/common/common-pipeline-scene-data.ts
> + export class CommonPipelineSceneData extends PipelineSceneData {
所以是给 forward 专用的？那怎么放 common 呢？

2021-09-24 11:00 UTC, YunHsiao commented on cocos/core/pipeline/common/postprocess-stage.ts
> +        // (For example, the editor camera small window will cause the picture to be distorted, etc.)
这应该是有 bug 了

2021-09-25 02:21 UTC, minggo commented
我的理解是，现在 pipeline 目录下的文件就是 forward/deferred 共用的，没必要再加个 common 目录了吧？

2021-09-25 03:08 UTC, pandamicro requested changes
另外还有命名问题：postprocess 是两个单词，要用 `postProcess`, `POST_PROCESS`, `PostProcess`, `post-process` 之类的命名法

2021-09-25 03:08 UTC, pandamicro commented on cocos/core/pipeline/common/common-pipeline-scene-data.ts
> + import { JSB } from 'internal:constants';
修复一下这个文件的缩进，拷贝过程中，代码前多了一个空格，还有有一些代码尾部有空格

2021-09-25 03:08 UTC, pandamicro commented on cocos/core/pipeline/common/enum.ts
> +    POSTPROCESS = 19
POST_PROCESS

2021-09-25 03:08 UTC, pandamicro commented on cocos/core/pipeline/common/postprocess-stage.ts
> +  * @zh 前向渲染阶段。
注释修复下

2021-09-25 03:08 UTC, pandamicro commented on cocos/core/pipeline/common/enum.ts
> +    POSTPROCESS = 19
感觉 UI 也应该放在这里，未来 BLOOM 也会插在这里，建议命名为 CommonStagePriority

2021-09-25 03:08 UTC, pandamicro commented on cocos/core/pipeline/common/postprocess-stage.ts
> +            return;
@YunHsiao please review

2021-09-25 03:08 UTC, pandamicro commented on cocos/core/pipeline/forward/forward-flow.ts
> +            this._stages[this._stages.length - 1].enabled = true;
不适合这样判断，应该在 stage 内部做 feature 判断然后做流程管理。

2021-09-25 03:08 UTC, pandamicro commented on cocos/core/pipeline/forward/forward-flow.ts
> +            this._stages[this._stages.length - 1].enabled = true;
不适合这样判断，应该在 stage 内部做 feature 判断然后做流程管理。

2021-09-25 03:08 UTC, pandamicro commented on cocos/core/pipeline/forward/forward-flow.ts
> +            this._stages[this._stages.length - 1].enabled = true;
不适合这样判断，应该在 stage 内部做 feature 判断然后做流程管理。

2021-09-25 03:08 UTC, pandamicro commented on cocos/core/pipeline/forward/forward-stage.ts
> +            renderProfiler(device, renderPass, cmdBuff, pipeline.profiler, swapchain);
这个函数中关于 ENABLE_ANTIALIAS_FXAA 的三处判断感觉太 hack 了，另外，感觉也影响行为，如果开启 FXAA 就不渲染 profiler ？还是延后？

2021-09-25 03:32 UTC, GengineJS commented on cocos/core/pipeline/forward/forward-stage.ts
> +            renderProfiler(device, renderPass, cmdBuff, pipeline.profiler, swapchain);
如果开启fxaa，profiler跟ui都在postprocessstage内部会做渲染，如果不开启fxaa就走原来的方式，不然不管开不开启都统一走postprocessstage？如果要保留原来的处理方式加判断肯定是需要的

2021-09-25 03:35 UTC, GengineJS commented
> 我的理解是，现在 pipeline 目录下的文件就是 forward/deferred 共用的，没必要再加个 common 目录了吧？

pipeline目录下文件太多了，common是对pipeline信息或共用部分的进一步封装，我认为还是有必要的

2021-09-25 03:38 UTC, GengineJS commented on cocos/core/pipeline/common/common-pipeline-scene-data.ts
> + export class CommonPipelineSceneData extends PipelineSceneData {
是forward跟deferred共用的，deferred只能走离屏，所以这里deferred随时都会用。forward只是开启fxaa时会用

2021-09-25 07:03 UTC, pandamicro commented on cocos/core/pipeline/forward/forward-stage.ts
> +            renderProfiler(device, renderPass, cmdBuff, pipeline.profiler, swapchain);
profiler 直接放在 post process stage 里面渲染把

2021-09-25 09:06 UTC, GengineJS commented on cocos/core/pipeline/forward/forward-stage.ts
> +            renderProfiler(device, renderPass, cmdBuff, pipeline.profiler, swapchain);
是的，现在是这么做的

2021-09-25 09:14 UTC, GengineJS commented on cocos/core/pipeline/forward/forward-stage.ts
> +            renderProfiler(device, renderPass, cmdBuff, pipeline.profiler, swapchain);
就是有两种情况，一种是开启fxaa就会在post process stage渲染ui跟profiler。不开启就会按照原来的方式在flowstage渲染

2021-09-26 01:17 UTC, minggo commented
> > 我的理解是，现在 pipeline 目录下的文件就是 forward/deferred 共用的，没必要再加个 common 目录了吧？
> 
> pipeline目录下文件太多了，common是对pipeline信息或共用部分的进一步封装，我认为还是有必要的

如果 common 是共用部分，那么 pipeline 下的其他文件是什么呢？

2021-09-26 01:29 UTC, minggo commented on cocos/core/pipeline/render-pipeline.ts
> +}
这理由有点牵强啊。除非是确实非常影响性能才应该这样。建议建个 issue 跟进一下。

2021-09-26 02:20 UTC, pandamicro commented on cocos/core/pipeline/forward/forward-stage.ts
> +            renderProfiler(device, renderPass, cmdBuff, pipeline.profiler, swapchain);
我希望的是 fxaa, bloom, profiler 都迁移到 post process 阶段中，做统一管理，bloom 应该是独立 BloomStage，之后是 PostProcessStage。PostProcessStage 不要根据简单的宏做跳过，而是在内部做 feature 开关管理

2021-09-26 03:05 UTC, GengineJS commented
> 如果 common 是共用部分，那么 pipeline 下的其他文件是什么呢？

pipeline scene date提供基础的共用信息，用户如果自定义管线，他们可能不会用到post process stage，提供基础的pipeline scene data就好了

2021-09-26 03:23 UTC, minggo commented
> > 如果 common 是共用部分，那么 pipeline 下的其他文件是什么呢？
> 
> pipeline scene date提供基础的共用信息，用户如果自定义管线，他们可能不会用到post process stage，提供基础的pipeline scene data就好了

按照这种说法，common 是专门给 post process stage 专用的？那文件夹命名还得改得更明确些。

2021-09-26 03:40 UTC, GengineJS commented
> 按照这种说法，common 是专门给 post process stage 专用的？那文件夹命名还得改得更明确些。

以pipeline目录下的instance buffer之类的来讲，有些stage可能会用，有些可能用不到，所以应该可以看作pipeline目录下是对pipeline行为的扩展（虽然有些是pipeline的基类），但是commom下的类，deferredpipeline跟forward都有在用。uiphase enum postprocess之类

2021-09-26 03:53 UTC, minggo commented
这个目前不影响这个 PR，但是你要从管线整个的目录结构来思考。从管线的目录结构，能看出你刚才说的那些信息？自定义管线开发者能够明白？文件结构如果划分得不合理的话，会让人感到迷惑的。后续再添加代码时，也不清楚该加到哪个文件夹里。

2021-09-26 04:05 UTC, pandamicro approved these changes

2021-09-26 06:42 UTC, YunHsiao commented on editor/assets/effects/pipeline/post-process.effect
> +    if(ANTIALIAS_TYPE == 1) {
不同 aa 的 effect 分开，不要写到一块去

2021-09-26 06:43 UTC, YunHsiao commented on editor/assets/chunks/anti-aliasing.chunk
> +#define FXAA_REDUCE_MIN   (1.0/ 128.0)
AA 的 shader 不需要共享，不用拆成单独的头文件

2021-09-26 07:08 UTC, YunHsiao commented on cocos/core/platform/macro.ts
> +    ENABLE_ANTIALIAS_FXAA: false,
这个应该放在 pipeline 上控制

2021-09-26 07:25 UTC, YunHsiao commented on cocos/core/pipeline/forward/forward-stage.ts
> +        let framebuffer = camera.window!.framebuffer;
forward stage 直接无条件往 camera fbo 上画，那 fxaa 不就没用了吗

2021-09-26 08:00 UTC, pandamicro commented on editor/assets/effects/pipeline/post-process.effect
> +    if(ANTIALIAS_TYPE == 1) {
啥意思，每种 AA 一个 effect 避免编译变种？
- fxaa.effect
- smaa.effect
？

2021-09-26 08:00 UTC, pandamicro commented on cocos/core/pipeline/common/postprocess-stage.ts
> +        if (!camera.window?.swapchain && !pipeline.macros.CC_PIPELINE_TYPE) {
`CC_PIPELINE_TYPE` 这个属性啥意思？0：forward？1：deferred？
如果是的确实太 Hack 了，想想其他办法判断环境 ，或者在特定环境下从上层设置关闭 fxaa。

2021-09-26 08:00 UTC, pandamicro commented on cocos/core/pipeline/forward/forward-stage.ts
> +        if (!pipeline.postRenderPass) this._uiPhase.activate(pipeline);
希望之后用统一固定的流程，把 ui 放在 ui stage 后置到 post process 之后

2021-09-26 08:10 UTC, YunHsiao commented on editor/assets/effects/pipeline/post-process.effect
> +    if(ANTIALIAS_TYPE == 1) {
是，这些 effect 没有必要统一

2021-09-26 08:16 UTC, YunHsiao commented on cocos/core/pipeline/forward/forward-stage.ts
> +            renderProfiler(device, renderPass, cmdBuff, pipeline.profiler, swapchain);
我不建议封装统一的 "post process" 阶段，这个概念其实就很模糊，到底什么算后效呢？我建议模块化得更彻底一些，pipeline 下直接就是离散的 gbuffer stage, lighting stage, smaa stage, bloom stage, profiler stage 等。每个 stage （连带其依赖 stage）都可以被直接剔除掉，每个 camera 直接指定自己要走哪些 stage

2021-09-26 08:23 UTC, minggo commented on cocos/core/pipeline/forward/forward-stage.ts
> +            renderProfiler(device, renderPass, cmdBuff, pipeline.profiler, swapchain);
那 stage 的依赖管理得使用者自己控制是吧？如果使用了一个 stage，但是依赖的 stage 没有走会怎么样？

2021-09-26 08:26 UTC, YunHsiao commented on cocos/core/pipeline/forward/forward-stage.ts
> +            renderProfiler(device, renderPass, cmdBuff, pipeline.profiler, swapchain);
每个 stage 开始前可以检测自己依赖的东西全不全，不全就直接跳过

2021-09-26 09:08 UTC, GengineJS commented on cocos/core/pipeline/forward/forward-stage.ts
> +        let framebuffer = camera.window!.framebuffer;
在屏得有用，非在屏没做处理，如果做处理类似小窗这种图像会失真
![image](https://user-images.githubusercontent.com/10766457/134801293-c0da80fa-ee2e-4fd1-b169-82e35176dc95.png)

2021-09-26 09:13 UTC, GengineJS commented on editor/assets/chunks/anti-aliasing.chunk
> +#define FXAA_REDUCE_MIN   (1.0/ 128.0)
抗锯齿的这个文件还是有必要的，至于fxaa还是其它smaa之类的处理，赞同新建独立文件，但是anti-aliasing这个文件可以做统一管理，我们只需要导入这个文件一次就好了，不需要所有aa文件都导入到post effect里面

2021-09-26 09:37 UTC, YunHsiao commented on cocos/core/pipeline/forward/forward-stage.ts
> +        let framebuffer = camera.window!.framebuffer;
不是你在屏离屏都得先离屏画，然后再 resolve 到输出目标啊。在这直接就输出了还怎么 AA 啊

2021-09-26 10:51 UTC, GengineJS commented on cocos/core/pipeline/common/postprocess-stage.ts
> +        if (!camera.window?.swapchain && !pipeline.macros.CC_PIPELINE_TYPE) {
那咱们就把离屏camera的画面一起送出去做aa？所有稍微看上去比较hack的代码就都可以去掉了。因为比如camera小窗那个画面失真是真的会让人接受不了

2021-09-26 10:53 UTC, GengineJS commented on cocos/core/pipeline/forward/forward-stage.ts
> +        let framebuffer = camera.window!.framebuffer;
这个用的只是camera的renderpass，fbo是我们自己创建的，不是用的camera的fbo。在post stage那才用的camera自己的fbo

2021-09-26 10:55 UTC, GengineJS commented
effect的分离我已经提交了，有争议的我暂时还没改

2021-09-26 12:10 UTC, pandamicro commented
> 我不建议封装统一的 "post process" 阶段，这个概念其实就很模糊，到底什么算后效呢？我建议模块化得更彻底一些，pipeline 下直接就是离散的 forward stage, gbuffer stage, shading stage, lighting stage, smaa stage, bloom stage, profiler stage 等。每个 stage 都可以被直接剔除掉（它们本身要写得足够健壮，确保缺了任何一环都不会出错），每个 camera 直接指定自己要走哪些 stage。

理念上我赞同，不过在 3.4 阶段，尤其是这个 PR 中不要求做这么大的重构，否则很难收敛和合并，加上 bloom 还依赖这个 PR。

目前 PR 依赖于几个引擎中已有的预设：
1. Pipeline 中写死的依赖 “post-process” effect，这是之前的设计问题，暂无法在 3.4 系统性解决，所以这个 PR 的目标只是将 deferred 中原本的 fxaa 移植到前向管线也适用。[回应评论](https://github.com/cocos-creator/engine/pull/9387#discussion_r716152344)
2. 3.4 要求提供全局的后处理配置，而不是 Camera 相关的配置，而这会引起 Camera 预览小窗的渲染问题，所以会存在[这个 hack](https://github.com/cocos-creator/engine/pull/9387#discussion_r716160889)

所以这两个问题上就不蔓延需求了，先确保实现可靠，原生和 TS 引擎的统一，不影响现有行为。保障 bloom pr 可以被及时合并。

在 3.5 阶段，将后处理流程整理清晰

2021-09-27 00:23 UTC, pandamicro approved these changes

2021-09-27 00:29 UTC, pandamicro commented on cocos/core/pipeline/render-pipeline.ts
> +}
这部分应该是之前刘月实现，就不要求这个 PR 解决之前的不合理问题了

2021-09-27 00:33 UTC, pandamicro commented
我也赞同小明这个说法

> 这个目前不影响这个 PR，但是你要从管线整个的目录结构来思考。从管线的目录结构，能看出你说的那些信息？自定义管线开发者能够明白？文件结构如果划分得不合理的话，会让人感到迷惑的。后续再添加代码时，也不清楚该加到哪个文件夹里。

你们看看下面这种命名会不会更清晰：
- PipelineSceneData -> BasicPipelineSceneData
- CommonPipelineSceneData -> InternalPipelineSceneData

2021-09-27 01:47 UTC, YunHsiao commented on editor/assets/chunks/anti-aliasing.chunk
> +#define FXAA_REDUCE_MIN   (1.0/ 128.0)
不需要统一管理，不同 AA 之间没有关系

2021-09-27 01:49 UTC, YunHsiao commented on editor/assets/chunks/anti-aliasing.chunk
> +#define FXAA_REDUCE_MIN   (1.0/ 128.0)
除非两个策略是不可分割的一个整体，否则 effect 层就不应该有任何耦合，确保每个组件都可以被剔除

2021-09-27 02:17 UTC, YunHsiao commented on cocos/core/pipeline/forward/forward-stage.ts
> +        let framebuffer = camera.window!.framebuffer;
在这就做 camera 的 load op 是不合适的，camera load 只应该在 camera fbo 上做，任何其他 fbo 都是走自己专属的固定的 render pass。

比如对于两个在屏 camera, 一个 clear 一个 load，如果 fg 在你的两次 forward stage 给你的 fbo 不是同一张贴图，你第二次 load 的就是垃圾数据了

2021-09-27 02:18 UTC, YunHsiao commented on cocos/core/pipeline/forward/forward-stage.ts
> +        let framebuffer = camera.window!.framebuffer;
当然对 js pipeline 来说就没啥区别了

2021-09-27 02:23 UTC, minggo approved these changes

2021-09-27 08:30 UTC, GengineJS commented
原生pr https://github.com/cocos-creator/engine-native/pull/3924

2021-09-28 03:17 UTC, merged