cluster ts engine v340 code
cocos/cocos-engine pull request #9405
Opened 2021-09-27 01:30 UTC by DolaMay

Re: cocos-creator/3d-tasks#

Changelog:
 *

2021-09-29 05:09 UTC, pandamicro requested changes

2021-09-29 05:09 UTC, pandamicro commented on editor/assets/chunks/cc-forward-light.chunk
> +#if CC_DEVICE_SUPPORT_COMPUTE_SHADER == 0 || CC_PIPELINE_TYPE == CC_PIPELINE_TYPE_FORWARD
可以将 CC_DEVICE_SUPPORT_COMPUTE_SHADER 改为 CC_ENABLE_CLUSTERED_LIGHTING 宏，在 Pipeline 中根据 ComputeShader 支持情况和 Clustered light culling 开启情况来设置

2021-09-29 05:09 UTC, pandamicro commented
https://github.com/cocos-creator/engine-native/pull/3923

2021-09-29 05:10 UTC, pandamicro commented
https://github.com/cocos-creator/engine-native/pull/3923

2021-09-30 00:36 UTC, pandamicro requested changes

2021-09-30 00:36 UTC, pandamicro commented on cocos/core/root.ts
> +            this._pipeline.clusterEnabled = false;
条件似乎反了

if (!this._useDeferredPipeline || !this.device.hasFeature(Feature.COMPUTE_SHADER))

2021-09-30 01:24 UTC, DolaMay commented on cocos/core/root.ts
> +            this._pipeline.clusterEnabled = false;
我的意图是只有满足这两个条件，才在可以在这里修改打开或者关闭，而原始默认值是false的；如果改成！|| ！的话，修改的时候就不是改这里，而是改原始定义处的默认值；不知道哪种好一些

2021-09-30 02:10 UTC, pandamicro approved these changes

2021-09-30 02:16 UTC, merged