support system feature query
cocos/cocos-engine pull request #9428
Opened 2021-09-29 15:35 UTC by PPpro

Re: https://github.com/cocos-creator/3d-tasks/issues/8826

Changelog:
 * 支持平台相关能力支持情况的查询

2021-10-04 08:11 UTC, pandamicro requested changes

2021-10-04 08:11 UTC, pandamicro commented on pal/system-info/native/system-info.ts
> +            [Feature.INPUT_TOUCH]: this.isMobile,
We always support touch input on desktop devices (using mouse event to simulate), it's very convenient for user to design mouse and touch compatible event handlers.

Besides, there are many desktop devices have touch screen nowadays, like Microsoft Surface and Huawei notebooks.

Simply set true here is backward compatible

2021-10-04 08:11 UTC, pandamicro commented on pal/system-info/web/system-info.ts
> +            [Feature.INPUT_TOUCH]: !!(document.documentElement.ontouchstart !== undefined || document.ontouchstart !== undefined || navigator.msPointerEnabled),
Same as previous suggestion, please set to true or check both mouse and touch event to here

2021-10-04 08:11 UTC, pandamicro commented on pal/system-info/minigame/system-info.ts
> +            [Feature.INPUT_TOUCH]: !isPCWechat,
Same as other comment

2021-10-04 08:11 UTC, pandamicro commented on pal/system-info/enum-type/feature.ts
> +    GL = 'GL',
Use WEBGL instead please. Also please add GLES2, GLES3, VULKAN and METAL for native platforms.

2021-10-04 08:11 UTC, pandamicro commented on pal/system-info/enum-type/feature.ts
> +    IMAGE_BIT_MAP = 'IMAGE_BIT_MAP',
IMAGE_BITMAP

2021-10-04 08:11 UTC, pandamicro commented on pal/system-info/minigame/system-info.ts
> +            [Feature.IMAGE_BIT_MAP]: false,
Does wechat also support ImageBitmap ? @holycanvas

2021-10-07 10:23 UTC, pandamicro commented on pal/system-info/minigame/system-info.ts
> +            [Feature.WEBGL2]: false,
Wechat platform supports WebGL2, and our runtime will support it very soon, we need to dynamically analyze the result or just remove this from the feature list for now

2021-10-07 10:23 UTC, pandamicro commented on pal/system-info/native/system-info.ts
> +            [Feature.WEBGL]: true,
Native is using VULKAN, METAL, GLES3 or GLES2, and you need to detect which one is used dynamically

2021-10-07 10:23 UTC, pandamicro commented on pal/system-info/native/system-info.ts
> +            [Feature.WEBGL]: true,
The initialize process might need to be delayed to some point after renderer initialized in game

2021-10-07 10:23 UTC, pandamicro commented on pal/system-info/web/system-info.ts
> +            [Feature.WEBGL2]: supportWebGL2,
Please also add WEBGPU, try to find how to detect webgpu support

2021-10-08 02:35 UTC, SantyWang commented on pal/system-info/minigame/system-info.ts
> +            [Feature.IMAGE_BIT_MAP]: false,
only Chrome and some Android browser support it

2021-10-08 05:36 UTC, SantyWang commented on pal/system-info/web/system-info.ts
> +            [Feature.INPUT_MOUSE]: !EDITOR && document.documentElement.onmouseup !== undefined,
为啥这个需要判断 EDITOR, 其他不需要呢

2021-10-08 09:46 UTC, PPpro commented on pal/system-info/web/system-info.ts
> +            [Feature.INPUT_MOUSE]: !EDITOR && document.documentElement.onmouseup !== undefined,
这个是迁移之前的判断逻辑，应该是不希望 引擎 处理编辑器里的鼠标事件

2021-10-09 10:55 UTC, PPpro commented
### changeLog:
- remove rendering backend related Feature query
- support Game.RENDER_TYPE_METAL, Game.RENDER_TYPE_VULKAN
- support deviceManager to create device
- add INPUT_TOUCH to determine whether the platform support touch input

### tested platform
- [x] Web
- [x] Simulator
- [x] Android
- [x] iOS
- [x] Wechat
- [x] ByteDance
- [x] OPPO

2021-10-09 11:45 UTC, pandamicro requested changes

2021-10-09 11:45 UTC, pandamicro commented on pal/system-info/enum-type/feature.ts
> +    INPUT_TOUCH = 'INPUT_TOUCH',
Please add a comment not to explain difference between `INPUT_TOUCH` and `EVENT_XXX`

2021-10-09 11:45 UTC, pandamicro commented on pal/system-info/native/system-info.ts
> +            [Feature.INPUT_TOUCH]: this.isMobile,
Native desktop could support touch input too, like Microsoft surface

2021-10-09 11:45 UTC, pandamicro commented on cocos/core/device-manager.ts
> +export class DeviceManager {
please import DeviceManager in gfx and export as `gfx.DeviceManager` so that it's consistent between native and web

2021-10-09 11:45 UTC, pandamicro commented on cocos/core/game.ts
> +        this._gfxDevice = DeviceManager.create();
import DeviceManager from `gfx` otherwise it will not work on native platforms

2021-10-11 14:34 UTC, pandamicro approved these changes

2021-10-11 14:34 UTC, pandamicro commented on pal/system-info/minigame/system-info.ts
> +            [Feature.EVENT_ACCELEROMETER]: !isPCWechat,
We shouldn't determine feature availability on platform, we should use actual feature detection logic. For example, iPad and Android pad could have keyboard too.

2021-10-11 15:17 UTC, merged