occlusion query
cocos/cocos-engine pull request #9455
Opened 2021-10-09 10:12 UTC by stanleyljl

Re: cocos-creator/3d-tasks#https://github.com/cocos-creator/3d-tasks/issues/9047

Changelog:
 * add occlusion query

2021-10-12 15:25 UTC, pandamicro requested changes

2021-10-12 15:25 UTC, pandamicro commented on cocos/3d/models/baked-skinning-model.ts
> +        super._updateLocalWorldBoundDescriptors(subModelIndex, descriptorSet);
It doesn't seem meaningful to overwrite this function

2021-10-12 15:25 UTC, pandamicro commented on cocos/core/pipeline/pipeline-scene-data.ts
> +        this.initOcclusionQuery();
Please only initialize if device support occlusion query

2021-10-12 15:25 UTC, pandamicro commented on cocos/core/pipeline/pipeline-scene-data.ts
> +    private createInputAssembler () {
please add `_` as prefix of private function name. Also the function name is not meaningful, if it's for creating occlusion query assembler, you can use name like `_createOcclusionQueryIA`

2021-10-12 15:25 UTC, pandamicro commented on cocos/core/pipeline/pipeline-scene-data.ts
> +        this._occlusionQueryIndicesBuffer = null;
check whether occlusion query is initialized

2021-10-12 15:25 UTC, pandamicro commented on cocos/core/renderer/scene/model.ts
> +    protected _localWorldBoundData = new Float32Array(UBOLocalWorldBound.COUNT);
It's better to only initialize it when needed

2021-10-12 15:25 UTC, pandamicro commented on cocos/core/renderer/scene/model.ts
> +    public updateWorldBoundUBOs () {
Does  it need to be public, seems only used internally

2021-10-12 15:25 UTC, pandamicro commented on cocos/core/renderer/scene/model.ts
> +    get localWorldBoundBuffer () {
The name `local world bound` is very strange, maybe name it as `model world bound`

And ay public property of function need a API description

2021-10-13 03:45 UTC, stanleyljl commented on cocos/3d/models/baked-skinning-model.ts
> +        super._updateLocalWorldBoundDescriptors(subModelIndex, descriptorSet);
不这么写构建失败

2021-10-13 03:46 UTC, stanleyljl commented on cocos/core/pipeline/pipeline-scene-data.ts
> +        this.initOcclusionQuery();
估计还是得写上，因为支持动态开关，如果实时销毁/创建流程会很乱。不过这数据量很小，一个model多两个vector4

2021-10-13 03:47 UTC, stanleyljl commented on cocos/core/pipeline/pipeline-scene-data.ts
> +    private createInputAssembler () {
1

2021-10-13 03:48 UTC, stanleyljl commented on cocos/core/pipeline/pipeline-scene-data.ts
> +        this._occlusionQueryIndicesBuffer = null;
必然会创建

2021-10-13 03:49 UTC, stanleyljl commented on cocos/core/renderer/scene/model.ts
> +    protected _localWorldBoundData = new Float32Array(UBOLocalWorldBound.COUNT);
同上

2021-10-13 03:49 UTC, stanleyljl commented on cocos/core/renderer/scene/model.ts
> +    public updateWorldBoundUBOs () {
1

2021-10-13 05:15 UTC, closed without merging