update tooltips of "cocos/2d" and "cocos/ui"#9163
cocos/cocos-engine pull request #9489
Opened 2021-10-14 10:55 UTC by Zhmz

Re: cocos-creator/3d-tasks#9163

Changelog: 
* 在engine工程里的editor\i18n\zh\assets.js和editor\i18n\en\assets.js修改了sprite-frame和texture两个类的资源检视面板下的tooltip
* 补充了 cocos/2d/component 、 cocos/2d/framework 以及 cocos/ui 下面的遗漏的tooltip
* 新增了widget.ts下的一条英文注解

2021-10-15 07:21 UTC, xunyi0 commented on editor/i18n/zh/assets.js
> +            offsetXTip: '图集中图片矩形的X轴偏移量',
中英文之间要保留一个空格

2021-10-15 07:21 UTC, xunyi0 commented on editor/i18n/zh/assets.js
> +            anisotropyTip: '各向异性值',
这个项包括下面几个项可以稍微展开介绍一下是干啥用的吗？比较好理解一些

2021-10-15 07:21 UTC, xunyi0 commented on editor/i18n/zh/assets.js
> +            rotatedTip: '图集中的子资源是否被旋转',
建议可以参考一下文档中 SpriteFrame 各属性的介绍：https://docs.cocos.com/creator/3.0/manual/zh/asset/sprite-frame.html

![image](https://user-images.githubusercontent.com/19702899/137447774-bc32ae9f-1334-406c-b383-e60169d12f76.png)

2021-10-15 07:21 UTC, xunyi0 commented on editor/i18n/zh/assets.js
> +            wrapModeSTip: 'S(U)方向纹理寻址模式',
中文版的说明，括号要用中文的括号

2021-10-18 02:48 UTC, LinYunMo approved these changes

2021-10-19 06:11 UTC, xunyi0 commented on editor/i18n/zh/assets.js
> +            trimXTip: '裁剪矩形左上角的 x 坐标',
```suggestion
            trimXTip: '裁剪矩形左上角的 X 坐标',
```

2021-10-19 06:11 UTC, xunyi0 commented on editor/i18n/zh/assets.js
> +            trimYTip: '裁剪矩形左上角的 y 坐标',
```suggestion
            trimYTip: '裁剪矩形左上角的 Y 坐标',
```

2021-10-19 06:11 UTC, xunyi0 commented on editor/i18n/zh/assets.js
> +            anisotropyTip: '沿通过具有最高纹理像素密度的像素的坐标轴取样的数量',
```suggestion
            anisotropyTip: '各向异性值，通过对具有最高纹理像素密度的像素的坐标轴进行取样的数值',
```

2021-10-19 06:11 UTC, xunyi0 commented on editor/i18n/zh/assets.js
> +            wrapModeSTip: 'S（U）方向像素对纹理的映射模式',
```suggestion
            wrapModeSTip: '像素对纹理在 S（U）方向上的映射模式',
```

2021-10-19 06:11 UTC, xunyi0 commented on editor/i18n/zh/assets.js
> +            wrapModeTTip: 'T（V）方向像素对纹理的映射模式',
```suggestion
            wrapModeTTip: '像素对纹理在 T（V）方向上的映射模式',
```

2021-10-19 06:11 UTC, xunyi0 commented on editor/i18n/zh/localization.js
> +        opacity: '表示该物体的不透明度，取值 0 ~ 255 之间',
```suggestion
        opacity: '设置物体的不透明度，取值范围为 0 ~ 255',
```

2021-10-19 06:11 UTC, xunyi0 commented on editor/i18n/zh/localization.js
>          design_size: '子域的设计分辨率，禁止在运行时动态更新',
```suggestion
        design_size: '开放数据域的设计分辨率，禁止在运行时动态更新',
```

2021-10-19 06:11 UTC, xunyi0 commented on editor/i18n/zh/localization.js
>          fps: '主域更新子域贴图的频率',
```suggestion
        fps: '主域更新开放数据域贴图的频率',
```

2021-10-19 06:11 UTC, xunyi0 commented on editor/i18n/zh/localization.js
>          lineJoin: '用来设置2个长度不为0的相连部分（线段，圆弧，曲线）如何连接在一起的属性',
```suggestion
        lineJoin: '用来设置 2 个长度不为 0 的相连部分（线段、圆弧、曲线）如何连接在一起',
```

2021-10-19 09:38 UTC, EricCorleone requested changes

2021-10-19 09:38 UTC, EricCorleone commented on editor/i18n/en/assets.js
> +            packableTip: 'Whether to participate in dynamic combination',
```suggestion
            packableTip: 'Whether to participate in dynamic atlas',
```

2021-10-19 09:38 UTC, EricCorleone commented on editor/i18n/en/assets.js
> +            trimXTip: 'The x coord of the top left corner of the clipping rect',
```suggestion
            trimXTip: 'The x coord of the top left corner of the trim rect',
```

2021-10-19 09:38 UTC, EricCorleone commented on editor/i18n/en/assets.js
> +            trimYTip: 'The y coord of the top left corner of the clipping rect',
```suggestion
            trimYTip: 'The y coord of the top left corner of the trim rect',
```

2021-10-19 09:38 UTC, EricCorleone commented on editor/i18n/en/assets.js
> +            widthTip: 'The width of the clipping rect',
```suggestion
            widthTip: 'The width of the trim rect',
```

2021-10-19 09:38 UTC, EricCorleone commented on editor/i18n/en/assets.js
> +            heightTip: 'The height of the clipping rect',
```suggestion
            heightTip: 'The height of the trim rect',
```

2021-10-19 09:38 UTC, EricCorleone commented on editor/i18n/en/assets.js
> +            borderLeftTip: 'The left margin of sliced rect',
```suggestion
            borderLeftTip: 'The left margin of the 9-slicing',
```

2021-10-19 09:38 UTC, EricCorleone commented on editor/i18n/en/assets.js
> +            borderRightTip: 'The right margin of sliced rect',
```suggestion
            borderRightTip: 'The right margin of the 9-slicing',
```

2021-10-20 08:17 UTC, xunyi0 approved these changes

2021-10-25 03:49 UTC, SantyWang approved these changes

2021-10-25 03:49 UTC, merged