supplement docs of atlasmanager
cocos/cocos-engine pull request #9590
Opened 2021-11-01 08:58 UTC by Zhmz

Re: cocos-creator/3d-tasks#9522

Changelog:
 * 参照 v2.4 的API文档，补充了 atlas.ts 和 atlas-manager.ts 的文档。

2021-11-02 05:57 UTC, EricCorleone commented on cocos/2d/utils/dynamic-atlas/atlas-manager.ts
> +     * The maximum number of atlas that can be created.
```suggestion
     * The maximum number of atlases that can be created.
```

2021-11-02 07:04 UTC, EricCorleone requested changes

2021-11-02 07:04 UTC, EricCorleone commented on cocos/2d/utils/dynamic-atlas/atlas-manager.ts
> +     * The maximum number of atlas that can be created.
```suggestion
     * The maximum number of atlases that can be created.
```

2021-11-02 07:04 UTC, EricCorleone commented on cocos/2d/utils/dynamic-atlas/atlas-manager.ts
> +     * Has enabled textureBleeding.
```suggestion
     * Whether to enable textureBleeding.
```

2021-11-02 07:04 UTC, EricCorleone commented on cocos/2d/utils/dynamic-atlas/atlas-manager.ts
> +     * The size of the atlas that was created.
```suggestion
     * The size of the created atlas.
```

2021-11-02 07:04 UTC, EricCorleone commented on cocos/2d/utils/dynamic-atlas/atlas-manager.ts
> +     * Resets all dynamic atlas, and the existing ones will be destroyed.
```suggestion
     * Reset all dynamic atlases, and all existing ones will be destroyed.
```

2021-11-02 07:04 UTC, EricCorleone commented on cocos/2d/utils/dynamic-atlas/atlas.ts
> +     * Resets the dynamic atlas.
```suggestion
     * Reset the dynamic atlas.
```

2021-11-02 07:04 UTC, EricCorleone commented on cocos/2d/utils/dynamic-atlas/atlas.ts
> +     * Resets the dynamic atlas, and destroy the texture of the atlas.
```suggestion
     * Reset the dynamic atlas, and destroy the texture of the atlas.
```

2021-11-02 07:04 UTC, EricCorleone commented on cocos/2d/utils/dynamic-atlas/atlas.ts
> +     * Draw a texture to the specified position
```suggestion
     * Draw a texture to the specified position.
```

2021-11-02 07:04 UTC, EricCorleone commented on cocos/2d/utils/dynamic-atlas/atlas.ts
> +     * Initialize the render texture with size.
```suggestion
     * Initialize the render texture.
```

2021-11-02 09:34 UTC, xunyi0 approved these changes

2021-11-03 02:36 UTC, holycanvas approved these changes

2021-11-03 02:36 UTC, merged