Add renderData cache & simplify merge check
cocos/cocos-engine pull request #9651
Opened 2021-11-11 12:51 UTC by LinYunMo

Re: https://github.com/cocos-creator/3d-tasks/issues/6713

2021-11-15 14:44 UTC, pandamicro requested changes

2021-11-15 14:44 UTC, pandamicro commented on cocos/2d/assembler/sprite/bar-filled.ts
> +            }
这些判断代码似乎都出现在一些长函数中，建议统一在一个独立函数中，长函数保留一个固定的函数调用。这样对 JIT 会更友好，因为小函数会被 jit 优化后内联。长函数如果分支过多对于 jit 不友好。

```
renderData.update(sprite, spriteFrame);
```

2021-11-15 14:44 UTC, pandamicro commented on cocos/2d/renderer/render-data.ts
> +        // TODO: have bug when node not add to scene
Need to be fixed before merge

2021-11-15 14:44 UTC, pandamicro commented on cocos/core/assets/material.ts
> +        return this._id;
如果需要对象唯一 id，那么使用 Symbol 会比较适合，Material 已经有 hash 了，就不要加 id 机制了

2021-11-15 14:44 UTC, pandamicro commented on cocos/core/director.ts
> +                    node._uiProps.uiComp.markForUpdateRenderData();
在切换场景过程中 Node 的 _onPostActivated 应该会被调用，尝试在哪里做重置，尽量都寻找已有机制解决问题

2021-11-15 14:44 UTC, pandamicro commented on cocos/core/renderer/core/material-instance.ts
> +        this._id = idGenerator.getNewId();
同之前，只要 constructor 被调用必然是不同的对象，Symbol 应该可以分辨

2021-11-15 14:44 UTC, pandamicro commented on cocos/core/scene-graph/node.ts
> +            this._uiProps.uiComp.markForUpdateRenderData();
应该在 emit 之前做完内部处理

2021-11-18 10:16 UTC, holycanvas approved these changes

2021-11-19 07:24 UTC, pandamicro approved these changes

2021-11-19 10:21 UTC, merged