change vertex format & color use uint8
cocos/cocos-engine pull request #9670
Opened 2021-11-16 10:25 UTC by LinYunMo

Re: https://github.com/cocos-creator/3d-tasks/issues/6713

2021-11-17 02:50 UTC, holycanvas approved these changes

2021-11-17 04:41 UTC, pandamicro requested changes

2021-11-17 04:41 UTC, pandamicro commented on cocos/2d/assembler/sprite/sliced.ts
> +        const uintbuf = buffer.uintVData;
看看是不是统一一下命名，把 RenderData.vDataUint 改为 RenderData.uintVData

2021-11-17 04:41 UTC, pandamicro commented on cocos/2d/assembler/sprite/tiled.ts
> +        const uintData = buffer.uintVData!;
应该提前到 

```
const vBuf = buffer.vData!;
```

之后获取，命名上也建议关联 `uintVBuf`

2021-11-17 04:41 UTC, pandamicro commented on cocos/2d/components/graphics.ts
> +const sizePerVertex = getSizePerVertex(attributes);
size 太宽泛了，建议用 byteLength

2021-11-17 04:41 UTC, pandamicro commented on cocos/2d/assembler/sprite/tiled.ts
> +        this.fillVertices(vBuf, vertexOffset, matrix, row, col, datalist, uintData);
接口设计上建议直接改为 

```
this.fillVertices(vBuf, uintVBuf, vertexOffset, matrix, row, col, datalist);
```

或者直接传递 buffer

```
this.fillVertices(buffer, vertexOffset, matrix, row, col, datalist);
```

2021-11-17 04:41 UTC, pandamicro commented on cocos/dragon-bones/assembler/simple.ts
> +    let uintbuf: Uint32Array;
uintVBuf

2021-11-17 12:45 UTC, LinYunMo commented
已更新，在 web 端测试通过，spine 和 dragonbones 在原生仓库的数据 layout 需要调整，由 @zhakesi  进行原生调整

2021-11-18 11:55 UTC, pandamicro requested changes

2021-11-18 11:55 UTC, pandamicro commented on cocos/2d/renderer/render-data.ts
> +    color: Color.WHITE.clone()._val,
不需要 clone 了就

2021-11-18 11:55 UTC, pandamicro commented on cocos/2d/renderer/render-data.ts
> +    constructor (vertexFloatCnt = 6) {
6 这个 magic number 太多了，全部改成统一出处的常量

2021-11-19 10:46 UTC, pandamicro commented on cocos/2d/assembler/label/ttf.ts
> +    floatCountPerVertex: getAttributeFloatCount(),
还是统一做文件级缓存吧

2021-11-19 10:46 UTC, pandamicro commented on cocos/2d/assembler/label/ttfUtils.ts
> +            colorOffset += this.floatCountPerVertex;
文件内做缓存

2021-11-19 10:46 UTC, pandamicro commented on cocos/2d/renderer/vertex-format.ts
> +export function getAttributeFloatCount (attrs: Attribute[] = vfmtPosUvColor) {
getVertexFloatCount

2021-11-19 10:46 UTC, pandamicro commented on cocos/spine/assembler/simple.ts
> +    return useTint ? getAttributeFloatCount(vfmtPosUvTwoColor) : getAttributeFloatCount(vfmtPosUvColor);
用文件级缓存把两个结果都存下来，这里直接用

2021-11-19 12:01 UTC, pandamicro approved these changes

2021-11-19 12:01 UTC, pandamicro commented
Wait for @zhakesi to adapt native spine/db

2022-06-07 08:37 UTC, closed without merging