Edit box optimization v3.5 #10036
cocos/cocos-engine pull request #9735
Opened 2021-11-26 06:37 UTC by Zhmz

Re: cocos-creator/3d-tasks#10036

Changelog:
 * 当用户手动删除 placeholderLabel 时，init 里不再直接为其创建一个新的placeholder
 * 删除序列化属性 placeholder，使得 placeholder 完全自主地由一个 label 组件控制

2021-11-26 06:38 UTC, Zhmz commented
issue中的第二个问题，
因为web中输入框相对于父物体的位置时css控制，并非引擎控制，所以这里不方便修改。
我会在论坛里给用户回复方案：在editbox外套一个节点，将editbox作为一个整体来修改位置。

2021-12-14 00:02 UTC, PPpro commented on cocos/ui/editbox/edit-box.ts
> +    // }
直接移除公开接口，会直接导致 Breaking Change，
需要兼容几个大版本之后才能移除，现阶段只能先标记为废弃

另外，EditBox.placeholder 属性的设计是参考 EditBox.string 属性的，提供了属性访问的便捷性
如果 placeholder 属性可以废弃，那么 string 属性也可以废弃才对，这个设计上的改动，可以再斟酌一下

2021-12-14 00:02 UTC, PPpro commented on cocos/ui/editbox/edit-box.ts
> +        }
> 当用户手动删除 placeholderLabel 时，init 里不再直接为其创建一个新的placeholder

这里的实现是否还会再创建 一个 Label 呢

2021-12-14 00:05 UTC, PPpro commented on cocos/ui/editbox/edit-box.ts
> +    protected _addPlaceHolderLabel (value: string) {
这里标记为 `private` 就好了，`protected` 仍然是一个公开接口，
用户继承 EditBox ，可以在子类里访问到这个方法

2021-12-14 09:53 UTC, Zhmz commented
![image](https://user-images.githubusercontent.com/32831993/145975208-80aa9705-9db4-469c-b2af-85591b798ca4.png)
placeholder暂时改为deprecated

2021-12-15 02:54 UTC, PPpro requested changes

2021-12-15 02:54 UTC, PPpro commented on cocos/ui/editbox/edit-box.ts
> +     * @deprecated
```suggestion
     * @deprecated since 3.5.0, please use placeholderLabel.string to get the content of the placeholder label.
```

2021-12-15 09:08 UTC, Zhmz commented
补充一个bug的修复：
_addPlaceHolderLabel里创建的placeholderLabel的layer需要设置为UI2d。否则placeholder就不会被UICamera拍到。
至于focus到editbox能够看到placeholderLabel，是因为这个placeholderlabel是web内置的input标签的展示组件。如下图
![企业微信截图_16395589227306](https://user-images.githubusercontent.com/32831993/146156838-c83b8c92-ebd7-4f40-83be-87f5e9aaa827.png)

2022-03-17 03:08 UTC, holycanvas commented
placeHolder 属性先不废弃了吧，这个属性在 editbox 组件上取，和去 label 里面去取，对开发者而言概念不一样

2022-08-30 03:56 UTC, closed without merging