optimization: set same value attribute v3.5
cocos/cocos-engine pull request #9744
Opened 2021-11-30 07:46 UTC by Zhmz

Re: cocos-creator/3d-tasks#7172

Changelog:
 * 四个组件，spriteframe，button，progressbar，editbox，里面部分属性补充在设置相同值的属性时，直接return，在上层避免冗余计算

2021-12-14 00:08 UTC, PPpro requested changes

2021-12-14 00:08 UTC, PPpro commented on cocos/2d/assets/sprite-frame.ts
> +            console.warn(`set same texture ${this._texture.name}`);
可以用功 warnID 实现，字符串无法被压缩，容易增大引擎包体

2021-12-14 09:39 UTC, Zhmz commented on cocos/2d/assets/sprite-frame.ts
> +            console.warn(`set same texture ${this._texture.name}`);
已修改

2021-12-15 09:32 UTC, PPpro requested changes

2021-12-15 09:32 UTC, PPpro commented on EngineErrorMap.md
> +set same texture %s.
```suggestion
Set same texture %s.
```

2021-12-15 10:02 UTC, PPpro approved these changes

2021-12-19 07:07 UTC, holycanvas commented on cocos/2d/assets/sprite-frame.ts
> +            warnID(3123, this._texture.name);
这个地方不用提示，只用跳过就好了，设置成同个 texture，感觉没什么逻辑问题，不应该给警告

2021-12-21 09:16 UTC, holycanvas approved these changes

2021-12-21 09:20 UTC, merged