Audio playrate
cocos/cocos-engine pull request #9751
Opened 2021-12-02 14:48 UTC by mikecoker

Re: cocos-creator/3d-tasks#

Changelog:
 *

2021-12-06 06:48 UTC, PPpro requested changes

2021-12-06 06:48 UTC, PPpro commented on cocos/audio/audio-source.ts
> +    @tooltip('i18n:audio.playbackrate')
please add the localization in the file `editor/i18n/zh/localization.js` and `editor/i18n/en/localization.js`

2021-12-06 06:48 UTC, PPpro commented on cocos/audio/audio-source.ts
> +        if (Number.isNaN(val)) { console.warn('illegal playback rate!'); return; }
We don’t want to help developers verify whether this value is `NaN`
__TypeScript__ should tell developers that they are passing an `NaN` to the `playbackRate` property,  which is a wrong approach

We hope to use the language to do the type checking work

2021-12-06 06:48 UTC, PPpro commented on cocos/audio/audio-source.ts
> +     * Note: Playback rate may be ineffective on some platforms.
```suggestion
     * Note: Playback rate is only supported on the platform Web and ByteDance.
```

2021-12-06 06:48 UTC, PPpro commented on cocos/audio/audio-source.ts
> +     * 注意：播放速率在某些平台上可能无效。<br>
```suggestion
     * 注意：播放速率目前只在 Web 和 字节 平台支持。
```

2021-12-06 06:50 UTC, PPpro commented
I suggest to merge this Pull Request into the branch `v3.5.0`  @pandamicro

2021-12-06 15:26 UTC, pandamicro commented
I rebased it to v3.5 but it seems the merge commit is causing conflit

2022-03-28 09:42 UTC, PPpro commented
Sorry, playback rate is not currently a cross-platform feature, 
we plan to support this feature on other platforms too, this is the tracking issue: https://github.com/cocos/cocos-engine/issues/10545

I am gonna close this PR for now, but this PR will be merged after this issue is finished.
Thanks again for you comtribution

2022-03-28 09:42 UTC, closed without merging