shadow info mifration for v3.4.1
cocos/cocos-engine pull request #9857
Opened 2021-12-22 08:48 UTC by troublemaker52025

Re: cocos-creator/3d-tasks#

Changelog:
 *

2021-12-22 08:59 UTC, troublemaker52025 commented
* 需要跟 https://github.com/cocos-creator/engine-extensions/pull/27 同步合并
* 还需要添加接口废弃声明

2021-12-22 09:00 UTC, troublemaker52025 commented
* 需要同步到原生

2022-01-19 02:50 UTC, jk20012001 approved these changes

2022-01-19 05:48 UTC, minggo approved these changes

2022-01-19 08:34 UTC, VisualSJ commented
api 变更警告

2022-01-20 15:02 UTC, pandamicro requested changes

2022-01-20 15:02 UTC, pandamicro commented on cocos/3d/lights/directional-light-component.ts
> +    // public
为什么在这里标注 public

2022-01-20 15:02 UTC, pandamicro commented on cocos/3d/lights/directional-light-component.ts
> +    @visible(function (this: DirectionalLight) { return (legacyCC.director.root as Root).pipeline.pipelineSceneData.shadows.type === ShadowType.ShadowMap && this._shadowFixedArea === false; })
复杂函数展开换行

2022-01-20 15:02 UTC, pandamicro commented on cocos/3d/lights/directional-light-component.ts
> +    @visible(function (this: DirectionalLight) { return (legacyCC.director.root as Root).pipeline.pipelineSceneData.shadows.type === ShadowType.ShadowMap && this._shadowFixedArea === false; })
复杂函数展开换行

2022-01-20 15:02 UTC, pandamicro commented on cocos/3d/lights/directional-light-component.ts
> +    @visible(function (this: DirectionalLight) { return (legacyCC.director.root as Root).pipeline.pipelineSceneData.shadows.type === ShadowType.ShadowMap && this._shadowFixedArea === true; })
复杂函数展开换行

2022-01-20 15:02 UTC, pandamicro commented on cocos/3d/lights/directional-light-component.ts
> +    @visible(function (this: DirectionalLight) { return (legacyCC.director.root as Root).pipeline.pipelineSceneData.shadows.type === ShadowType.ShadowMap && this._shadowFixedArea === true; })
复杂函数展开换行

2022-01-20 15:02 UTC, pandamicro commented on cocos/3d/lights/directional-light-component.ts
> +    @visible(function (this: DirectionalLight) { return (legacyCC.director.root as Root).pipeline.pipelineSceneData.shadows.type === ShadowType.ShadowMap && this._shadowFixedArea === true; })
复杂函数展开换行

2022-01-20 15:02 UTC, pandamicro commented on cocos/core/pipeline/scene-culling.ts
> -    if (shadows.firstSetCSM) {
这个可以删除吗？从 3.3 升级上来的配置设置会出现什么情况？

2022-01-20 15:02 UTC, pandamicro commented on cocos/core/renderer/scene/directional-light.ts
> +            this._shadowSaturation = val / val;
不建议在 render scene 做这层兼容，应该在组件中做这层兼容

2022-01-20 15:02 UTC, pandamicro commented on cocos/core/renderer/scene/directional-light.ts
> +        this.fixedOrthoSize = 5;
在属性声明中有默认值，为什么还要在这里设置一样的初始值？除非对象复用 initialize 可能用来重复设置才有必要

2022-01-20 15:02 UTC, pandamicro commented on cocos/core/renderer/scene/spot-light.ts
> +        this.shadowNormalBias = 0.0;
同上

2022-01-21 01:56 UTC, troublemaker52025 commented on cocos/3d/lights/directional-light-component.ts
> +    // public
shadow map 中共同包含的属性

2022-01-21 02:00 UTC, troublemaker52025 commented on cocos/core/pipeline/scene-culling.ts
> -    if (shadows.firstSetCSM) {
用户从 v3.3.0 升级上来默认使用 CSM 模式，不需要第一次使用时，对第一层级进行额外设置

2022-01-21 05:14 UTC, pandamicro approved these changes

2022-01-21 05:14 UTC, merged

2022-01-23 09:51 UTC, PPpro commented
編輯器 npm install 過不了了

2022-01-23 09:55 UTC, troublemaker52025 commented
> 编辑器 npm install 过不了了，@pandamicro @minggo @troublemaker52025 需要重新确认一下接口变更

编辑器对应修改，已反馈给郑瀚