Fix bug multi touch
cocos/cocos-engine pull request #9917
Opened 2022-01-04 09:17 UTC by yanjifa

Re: cocos-creator/3d-tasks#

Changelog:
 * 修复 multi touch 无法通过宏 [macro.ENABLE_MULTI_TOUCH] 关闭
 * touchManager 通过 ES6 Map 管理 Touch
 * 目前自测了
   - web: 
     - iOS 15.2 Safari
     -  Android Chrome 84.0.4147.89
   - native: 
     - iPhone13 Pro iOS 15.2
     - Pixel XL Android 10

2022-01-04 11:39 UTC, yanjifa commented
[测试 Demo](https://forum.cocos.org/uploads/short-url/rsnJaVzdtdo1gDCD1Rfj3VDjjKR.zip)
---
![test](https://forum.cocos.org/uploads/default/original/3X/b/c/bcf815c81debb7e8cd64204b86c86e8e230b03c3.gif)

2022-01-06 08:11 UTC, PPpro requested changes

2022-01-06 08:11 UTC, PPpro commented on pal/input/touch-manager.ts
> +     * A map from touch.
```suggestion
     * A map from touch ID to touch object.
```

2022-01-06 08:11 UTC, PPpro commented on pal/input/touch-manager.ts
> +     */
```suggestion
```

2022-01-06 08:12 UTC, PPpro commented
感谢提交，有一些注释问题提了一些修改建议，麻烦改一下哦

2022-01-06 08:13 UTC, PPpro commented on pal/input/touch-manager.ts
> +     */
私有方法不需要写 jsDoc 注释了

2022-01-06 08:28 UTC, yanjifa commented
> 感谢提交，有一些注释问题提了一些修改建议，麻烦改一下哦

已修改

2022-01-06 08:46 UTC, PPpro approved these changes

2022-01-06 10:22 UTC, holycanvas approved these changes

2022-01-06 10:22 UTC, merged